### PR TITLE
Adding a QRCode with the user's information

### PR DESCRIPTION
**Pull request by MagicMicky**
QRCode retrieved from Google APIs, and parsed with json like that:
`{address:"",user:"",key:""}`

### CODE REVIEW

**Comment by switz** [comment]
Nice! Can you switch it to double brackets?

```
{{_user.id}}
```

**Comment by MagicMicky** [comment]
Done :)

**Comment by lefnire** [comment]
oh shit! @MagicMicky i didn't see this I'm so sorry, you could have used this forever ago for you app! merging now

**Comment by MagicMicky** [comment]
Thanks! Wanted to mention it on twitter, but then forgot to talk about it!

**Pull request merged**
