### PR TITLE
fix(chat): #5865 API should return flagged messages in chat only to mods

### PR DESCRIPTION
**Pull request by srrvnn**
filtered groups.chat if user.contributor.admin is false in api request for groups, and api request for group chats.

### CODE REVIEW

**Comment by crookedneighbor** [comment]
You changed the threshold for number of flags to block chats from 2 to 3. Was that intentional? Why?

**Comment by srrvnn** [comment]
issue #5865 is described as "Chat messages with more than 2 flags should be returned by the API only if they are requested by a moderator." by @paglias. so, i looked for flagCount < 3.

**Comment by crookedneighbor** [comment]
Got it. It should still be changed back to 2.

**Comment by srrvnn** [comment]
updated.

**Comment by crookedneighbor** [comment]
This reasonable to me, but currently it's blocked by a [new API test infrastructure we're building](https://github.com/HabitRPG/habitrpg/pull/6062). As soon that is merged in, we can add tests for this behavior and merge this in.

**Comment by crookedneighbor** [comment]
The PR is merged in. Let me know if you need help writing tests.

**Comment by srrvnn** [comment]
I'll give it a shot over the weekend.

**Comment by crookedneighbor** [comment]
This will count towards a contributor tier! What's your User ID? You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api). Be sure to only copy the User ID and _not_ your API Token.

**Comment by srrvnn** [comment]
that's my user id: 26b44255-6afa-483b-9801-fea6521b485a. yay!

**Pull request merged**
