### PR TITLE
Stops paypal from asking user for shipping address

### PR DESCRIPTION
**Pull request by kristian-welsh**
Hey, I'm completely new to this project, and the Paypal API. Which means this probably doesn't work. That being said, could you please check if this fixes the issue? I couldn't get to the Paypal page from localhost:3000 to test the change.

### CODE REVIEW

**Comment by crookedneighbor** [comment]
@kristian-welsh No worries. Just update your code, commit, and push. It'll automatically be updated in the pr.

**Comment by kristian-welsh** [comment]
Hey, i have some ideas as to what might be breaking the CI build. Should i keep committing possible fixes, or is that bad etiquette?

**Comment by crookedneighbor** [comment]
The CI build is probably unrelated to this PR. We're in the process of fixing some tests that need to be re-written. I wouldn't worry about it for now.

**Comment by kristian-welsh** [comment]
Excellent, thank you.

**Comment by crookedneighbor** [comment]
@kristian-welsh As far as I can tell, you implemented the necessary parameter in the documentation noted on issue #4676, but I'm getting inconsistent behavior from PayPal. 

I was going to tell you that you need a [PayPal developer's account (free)](https://developer.paypal.com) to test this, but after attempting to test it with my account, I ran into some issues.

When going through the sandbox version of PayPal for testing, it shows the old interface, but it still shows the shipping address field.

However, when clicking the PayPal button directly from habitrpg.com, it takes me to the new PayPal interface. So, I'll need to see if the sandbox interface can be configured to use the new system. 

I'll do some research and get back to you.

**Comment by kristian-welsh** [comment]
That is unusual, thank you for the help testing.

**Comment by lefnire** [comment]
hey @kristian-welsh thanks for the PR! i'll test soon as I can. I think the webProfile needs to be tied to each of the existing billingPlan objects. To do so we'd need to bring those billingPlans down, edit them to add the webProfile ID, & save. So this PR strikes me as step one of a multi-step process. I could be wrong, I'll dive in when I can and update here when I find out more. If indeed more needs to be done, I'll try to edit this PR myself to complete it, or I'll ping you with any further steps.

**Comment by kristian-welsh** [comment]
Okay, great.

**Comment by remmz0r** [comment]
@lefnire - I also looked into this and noticed the same thing. I was half asleep when looking through the code, but I noticed you would have to get a certain token, then create a web profile request using said toeken, to be used with each payment. You -can- do this with the v1 REST api in the developer sandbox, but it wouldn't work directly with your website without doing some stuff on your end (ie as you said generating the tokens and web profiles). Hope this helps.

**Pull request closed without merging**
