### PR TITLE
Esc now cancels item select in inventory and stable

### PR DESCRIPTION
**Pull request by pjay-io**
Solves #4772, title is self-explanatory.

### CODE REVIEW

**Comment by Alys** [comment]
It's not completely self-explanatory. I had to look at the code to work out what was supposed to happen. 

If I understand correctly, when I am on the Pets page, and I click on a food item, I can then hit Esc on my keyboard to unselect the item. That doesn't work for me though (MacOS 10.6). After hitting Esc, the food item is still highlighted with the blue outline.

The same occurs in the Inventory section on the Market page: after Esc is hit, an egg, potion, or food will still be highlighted. It works for quests, but then it Esc works for quests on the production site.

If that's not supposed to be how this works, can you please provide an explanation?

**Comment by pjay-io** [comment]
It works here on a clean build and works with the same mechanics as clicking the item again:

screen shot 2015-03-15 at 19 11 46

screen shot 2015-03-15 at 19 11 54

The border not disappearing has nothing to do with this modification, clicking it again to deselect also keeps the border.

It simply is a function bound to 'ESC' key up event on inventory / stable.

Could you or someone else test it again?

**Comment by pjay-io** [comment]
I see the issue I think, when clicking on something else before pressing ESC it stops working. Will edit!

**Comment by crookedneighbor** [comment]
@PJay- Any update on this?

**Comment by crookedneighbor** [comment]
@PJay- since I haven't heard back, I'm going to close this. Feel free to re-open if you'd like to finish this PR.

**Pull request closed without merging**
