### PR TITLE
Reorganized and improved sprites

### PR DESCRIPTION
**Pull request by Pandoro**
*Gimp file into female and male.
*Created sprites for both of them
*Created a shop.xcf Here shop versions for all items will be kept.
*Created a shop sprite. Includes potion, reroll icon and gold, silver, copper coins

*Created a development xcf. This will contain items which are in development and a base pixel art for male and female which can be used to cross check your new items against. E.g. does my helmet fit the system yes or no?

### CODE REVIEW

**Comment by lefnire** [comment]
you are insanely fast, Alex. These are great, thanks man

**Comment by Pandoro** [comment]
Took me quite some time ;) It was only so fast because I stayed home today
;)

I hope you can work with them :) I named everything the same now in the
shop in the male and female set, so I hope you can just replace the CSS and
png file and BAM done if you change between male and female :)

**Comment by lefnire** [comment]
Alex. To you I shall grant my first born.

**Comment by Pandoro** [comment]
x) Don't worry about it ;) My girlfriend is all into kids already, I don't
need another one for free ;) Buuut I appreciate the gesture :)

**Pull request merged**
