### PR TITLE
New Beatscribe 8-bit sound theme

### PR DESCRIPTION
**Pull request by JesseRatt**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)
This is a new 8-bit NES sound theme created with actual NES hardware emulation (Plogue Chipsounds) to recall vintage RPG feel.

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

Added new sound theme to menu. 

[//]: # (Put User ID in here - found in Settings -> API)

----
UUID:

### CODE REVIEW

**Comment by TheHollidayInn** [comment]
Thanks for the PR! We are testing this out on a separate server then we will merge/provide feedback.

**Comment by JesseRatt** [comment]
No problem! Looking forward to it. I tested it locally on my local build successfully as well so it should be fine. I have a 16-bit SNES JRPG style one in the works too but wanted to see how this one goes first.

**Comment by TheHollidayInn** [comment]
The theme is AWESOME :D. Thanks! Looking forward to the next.

**Comment by JesseRatt** [comment]
Ok i'll get on it in that case!

**Comment by TheHollidayInn** [comment]
Can you post your UUID so I can add this to your contributor credit?

**Comment by JesseRatt** [comment]
59051374-fcfd-4014-beaa-0c2c7b847485

**Comment by TheHollidayInn** [comment]
Congratz on tier 1!

**Pull request merged**
