### PR TITLE
Swap faq and overview in the top menu

### PR DESCRIPTION
**Pull request by ghost**
Addressing request by lemoness
https://github.com/HabitRPG/habitrpg/issues/5261

### CODE REVIEW

**Comment by ghost** [comment]
Just to be on the safe side I've asked lemoness in the issue ticket for confirmation that I had understood all the proposed changes right.

**Comment by crookedneighbor** [comment]
Looks great to me. Tier++

**Comment by ghost** [comment]
@crookedneighbor Thank you very much! It was rather unexpected, I must say ^^

I really appreciate it!

You know I'm not a developer/coder and I'm not able to handle some advanced issues. So I personally think that a single Tier+1 as a blacksmith is currently my personal level-up cap =)

So I just want to ask you: may I still try to handle some entry-level things (like simple env.t translations, as I still have them on my list) or should I leave them at place for other beginner-level coders who may also want to join contributing?

**Comment by crookedneighbor** [comment]
Feel free to keep plugging away. It's valuable work. 

Note: as you might have guessed, the higher tiers take much more work to achieve than the lower tiers.

**Pull request merged**
