### PR TITLE
WIP: add filtering code for malformed push devices.

### LINKED ISSUE #11868: pushDevices bad data cause errors for other players
A player's `pushDevices` array can have bad data in it, as shown in the example below - the first object in the array is correct, the others are not.

```
"pushDevices": [
	{
		"regId": "fzvFqZketcetcetcetcygb2Q",
		"type": "android",
		"createdAt": "2019-03-13T21:04:36.573Z",
		"updatedAt": "2019-03-13T21:04:36.573Z"
	},
	{
		"updatedAt": "2019-03-13T21:04:20.973Z"
	},
	{
		"updatedAt": "2019-03-13T21:04:20.973Z"
	},
]
```

When there's bad data, certain actions in Habitica become impossible due to errors thrown by the code that tries to use the array. This affects the player with the bad data of course but can also affect other players. The error at the bottom of this comment occurred when a guild leader tried to remove an inactive guild member. **The guild member's `pushDevices` array had the bad data in it and that was stopping the guild leader from removing them.** Being unable to remove a party or guild member is particularly troublesome because the leader of a private group might need to remove someone for privacy / personal safety reasons, and a Group Plan leader must be allowed to reliably remove members otherwise they'll continue to be charged for them.

Because bad data can affect players who don't have the bug in their own account, I think it's worth adjusting the API's code to make errors like this non-fatal when possible. I'm proposing that any code in the API that uses the `pushDevices` array be modified so that it ignores any entries that aren't valid.

I'll leave this as suggestion-discussion for a few days and then if there's no objections from Habitica's staff, I'll mark it as help wanted.

Once (if) it's marked as help wanted, a contributor can find the code that uses the array by doing `git grep pushDevices` however I believe the two main files are:
- https://github.com/HabitRPG/habitica/blob/develop/website/server/libs/pushNotifications.js
- https://github.com/HabitRPG/habitica/blob/develop/website/server/controllers/api-v3/pushNotifications.js

You'll want to check though to be sure I haven't missed important files, and also to see the current tests which will help you create new tests.

```
{
"method":"POST",
"originalUrl":"/api/v3/groups/12345678-4fa5-4e94-8114-123456789abc/removeMember/12345678-18b7-4fd7-ba30-123456789abc?message=",
"headers":{...},"body":{},
"httpCode":400,"isHandledError":true,
"fullError":{
	"errors":{
		"pushDevices.0.type":{
			"message":"Path `type` is required.","name":"ValidatorError",
			"properties":{"message":"Path `type` is required.","type":"required","path":"type"},
			"kind":"required",
			"path":"type"
		},
		"pushDevices.0.regId":{
			"message":"Path `regId` is required.","name":"ValidatorError",
			"properties":{"message":"Path `regId` is required.","type":"required","path":"regId"},
			"kind":"required",
			"path":"regId"
		},
	},
	"_message":"User validation failed",
	"message":"User validation failed: pushDevices.0.type: Path `type` is required......",
	"name":"ValidationError"
},
"timestamp":"2020-02-15T19:43:06.818Z",
"level":"warn",
"message":"ValidationError: User validation failed: pushDevices.0.type: Path `type` is required....\n
    at new ValidationError (/usr/src/habitrpg/node_modules/mongoose/lib/error/validation.js:31:11)\n
	at model.Document.invalidate (/usr/src/habitrpg/node_modules/mongoose/lib/document.js:2490:32)\n
	at EmbeddedDocument.invalidate (/usr/src/habitrpg/node_modules/mongoose/lib/types/embedded.js:291:29)\n
	at /usr/src/habitrpg/node_modules/mongoose/lib/document.js:2339:17\n
	at /usr/src/habitrpg/node_modules/mongoose/lib/schematype.js:1064:9\n
	at processTicksAndRejections (internal/process/task_queues.js:75:11)"
}
```

### PR DESCRIPTION
**Pull request by aristizabal95**
[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #11868

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
Code has been added to remove malformed push devices from a user document inside the pre-validate and pre-save hooks. This with the intention of fixing bugs were a user can't be saved due to push device validations.

At the moment validation still fails, even though the corrupted push devices are being successfully filtered from the document inside the pre-validation hook.

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 88643b14-48fa-4ae1-b45d-5ff7b793a257

### CODE REVIEW

**Comment by paglias** [comment]
Hmm there's something weird here, in that the changes applied to `pushDevices` are not being picked up for some reason

**Comment by paglias** [comment]
@aristizabal95 thanks again for the PR, I found out the issue causing the validation to still fail (we cannot call `validateSync` in a pre-validate hook).

But making these checks in the `pre-validate` hook is still the best idea.

Unfortunately i realized that this doesn't affect only push devices but a few other arrays as well so I'm going to pick up the PR and finish it.

I'll try to incorporate your commits directly so that they remain available in Github but if that isn't possible you'll still get an Habitica contribution tier for the help.

Thanks for the understanding

**Comment by paglias** [comment]
Closing in favor of #11916. But I've notated the PR towards your 2nd tier, @aristizabal95 thanks again!

**Comment by aristizabal95** [comment]
Hi @paglias, great! Didn't know I couldn't call `validateSync()` there. My line of thought was to not copy-paste validation rules so that it was easier to change them later on by only modifying the schema.

I'm happy you found a solution for this and other corrupt data problems! And thanks for noting the contribution attempt, you didn't have to, but I'm grateful.

**Pull request closed without merging**
