### PR TITLE
Keep existing Mystery Items and Hourglasses when adding to group - fixes 8643

### PR DESCRIPTION
**Pull request by joe-salomon2**
[//]: # (https://github.com/HabitRPG/habitica/issues/8643)
Fixes https://github.com/HabitRPG/habitica/issues/8643

### Changes

If a user's subscription expires (gift or self-purchase), and they join a paid group, their existing unopened Mystery Items or unopened Mystery Hourglasses will no longer be overwritten.

Modified addSubToGroupUser to save existing mysteryItems and trinket values
Added unit test in payments.test.js

----
UUID: fc28e9dc-9c84-4ee3-be6e-b4dffa54f558

### CODE REVIEW

**Comment by joe-salomon2** [comment]
Resolved branch conflicts

**Comment by joe-salomon** [comment]
I resolved the branch conflicts right in the Github website. Is there a way to kick off the Travis checks again?

**Comment by joe-salomon2** [comment]
Hmm, is this Travis failure a code issue or something else?

**Comment by SabreCat** [comment]
Great! Thanks so much for this fix. I have awarded you Blacksmith tier 1! Note that subsequent tiers require increasing amounts of effort from one to the next, so tier 2 may require multiple PRs or a larger PR to achieve. But keep helping out and we will express our gratitude accordingly!

**Pull request merged**
