### PR TITLE
column-background should have 100% width

### PR DESCRIPTION
**Pull request by kikyous**
[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes put_#_and_issue_numer_here

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

image

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 2c5d1ce1-4f45-4b0a-aa07-cd5efb0f4217

### CODE REVIEW

**Comment by paglias** [comment]
Hi @kikyous , thanks for the PR!

Could you explain the issue this PR is fixing?

**Comment by kikyous** [comment]
@paglias as you can see in the picture above, inital description not display horizontal center, because column-background width is not 100%.
I fix this issue by add width 100% to column-background.

**Comment by paglias** [comment]
@kikyous which browser are you using? and what's the resolution of your screen?

Because I'm not able to reproduce the issue
Schermata 2019-04-29 alle 10 59 59

**Comment by kikyous** [comment]
@paglias chrome 73, 1920 x 1080.
I think you cant not able to reproduce the issue because in your language, inital description is wrap lines, so it's width is as large as parent container.
But in chinese, text is shorter, it's width is smaller than container width.

**Comment by paglias** [comment]
Actually I think it's an issue with bigger screens: I have a higher resolution but likely smaller screen and it doesn't happen with Chinese. Thanks, I'll give it some extra testing and then merge it if there are no issues

**Comment by paglias** [comment]
thanks @kikyous ! the fix is looking good and will go live next week after some extra testing

**Comment by paglias** [comment]
I'm awarding your contributor tier.

Note that further tiers require increasing amounts of work from one to the next, so Tier 2 may require a couple of PRs or a larger PR to attain. But keep helping out and we'll express our gratitude accordingly!

**Pull request merged**
