### PR TITLE
Stop market background from covering featured items sign

### LINKED ISSUE #10037: decorations cover Featured Items label in Shops > Market when zoomed in
In Shops > Market, if you have your browser zoomed in a couple of levels, (e.g., for people with poor eyesight), one of the Valentine heart decorations covers part of the "Featured Items" label.

screenshot_2018-02-22_20-16-11

I imagine we won't get a fix made fast enough to fix it for this years Valentine period, but we could prevent this for any future decorations by giving the "Featured Items" label a z-index value great enough to ensure it's in front of all other items.

### PR DESCRIPTION
**Pull request by probaton**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #10037

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
Add a z-index to the market's featured items to keep the background from covering the sign. 

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 6d7d6651-604d-4e7c-adff-a040770a6768

### CODE REVIEW

**Comment by probaton** [comment]
So apparently I lost the test lottery and one of the integration tests for banned words in chat messages randomly selected the 'TEST_BANNED_WORD_HERE' string from bannedWords.js. The word is correctly identified as banned but as part of the screening the code normalizes the string, so the return message lists it as 'test banned word here', which then promptly triggers an assertion.

Simply replacing the banned word with a pre-normalized version seemed the simplest solution. However, if you prefer I can also normalize the banned words input in the test.

**Comment by Alys** [comment]
@probaton Please can you remove your changes to the three files related to swear words and banned words and then force-push that change to your probaton/habitica branch so that those three files are removed from this PR (don't just close this PR to create another - force pushing to update this PR is necessary). At the moment, your PR is displaying some of the words in its diffs and we don't want that to happen because it exposes other contributors to those words without any warning.  See the comments in website/server/libs/bannedWords.js for more details. If you need help working out how to reverse your changes, you're welcome to ask in this PR.

Now that you've raised the issue with the tests for those files, we'll discuss it internally.

**Comment by probaton** [comment]
Rebased out my second commit, so no more icky changes! 

I've copy pasted the code snippet that was causing the issue below, in case you find yourself having trouble finding the culprit without the file as reference. 
```
it('checks error message has the banned words used', async () => {
  let randIndex = Math.floor(Math.random() * (bannedWords.length + 1));
  let testBannedWords = bannedWords.slice(randIndex, randIndex + 2).map((w) => w.replace(/\\/g, ''));
```
The snippet starts at line 139 of `test/api/v3/integration/chat/POST-chat.test.js`.

Again, the test works just fine unless `randIndex` happens to return 0. Ware the 3vil of non-deterministic tests!

**Comment by Alys** [comment]
@probaton Thank you for removing the commit and THANKS SO MUCH for those details about the test bug! I didn't realise that was happening - I missed it when that code was submitted because I didn't review it carefully. I or the staff will get rid of that random behaviour. The tests should not be picking swear words randomly because that can expose any contributor who reads the tests to some nasty words.

**Comment by negue** [comment]
LGTM 👍

**Comment by SabreCat** [comment]
Thanks for this, @probaton ! Noted toward tier 2!

**Comment by probaton** [comment]
Awesome! I try to tell myself I don't really care about internet accolades but I gotta admit the new badge just totally made my day! My habitica party members are totally jealous (or so I tell myself).

**Pull request merged**
