### PR TITLE
Correct party up/on achievement string names

### LINKED ISSUE #8312: Party Up and Party On achievements are missing text
_From thebat137 (dea8a9e8-c084-438a-9a14-7fe96a73fd0a) in the Report a Bug guild:_

I was just looking at my achievements list and I noticed that the hovertext for the "Party Up" and "Party On" achievements seems to be missing. Hovering over the icons just says "Party Up/partyUpText not found" and "Party On/partyOnText not found" (where the slash in those quotes is meant to represent a linebreak). I have received the Party Up achievement, but not the Party On achievement, so the problem seems to be independent of awarded/not awarded status.

_From Cequinne (a9b44f7f-08b3-4ecb-97c2-d2855eed4e20):_

Hovering over the "Party Up" and "Party On" achievement badges shows "String 'partyUpText' not found" or "String 'partyOnText' not found" respectively in the description.

### PR DESCRIPTION
**Pull request by khipkin**
Fixes #8312.

### CODE REVIEW

**Comment by khipkin** [comment]
@TheHollidayInn

**Comment by Alys** [comment]
Sorry about this @khipkin but does website/views/shared/modals/achievements.jade need to be changed again too? I have this locally:

	website/views/shared/modals/achievements.jade:140:      p=env.t('partyUpAchievement')
	website/views/shared/modals/achievements.jade:151:      p=env.t('partyOnAchievement')

**Comment by khipkin** [comment]
Oopsie! Good catch, @Alys. 😁

**Comment by TheHollidayInn** [comment]
Can you resolve the conflicts? Then I'll merge :D

**Comment by khipkin** [comment]
Conflicts resolved! Sorry for the delay. Not sure why the diff is weird... maybe the web editor changed the line ending style?

**Comment by TheHollidayInn** [comment]
Added to tier progress!

**Pull request merged**
