### PR TITLE
Fixed word spacing in challenges.jade

### PR DESCRIPTION
**Pull request by agnesnutter**
Added spaces after "by" and before "prize" in Challenges pane so words don't run together.

### CODE REVIEW

**Comment by deilann** [comment]
Okay, your issue here is

`ent.t('prize')` pulls the string `prize`. You can't put a space in there like that.

**Comment by agnesnutter** [comment]
@deilann Whoops! Yes, of course. _facepalm_

**Comment by agnesnutter** [comment]
I have no idea what I'm doing. I probably shouldn't be messing around with this at all, actually.

**Comment by deilann** [comment]
I can help you!

So, Habit is doing everything with strings right now, 'cause it allows the site to be translated. So whenever you see "env.t('string')" it's pulling from another file. You see the English version.

The language used for that file is jade. It's kind of like HTML, but slightly different.

So to add in a space, you need to not do it in the string, but do it outside of it. I believe what you want to do is put a blank line between the two variables, but I'd need to test it.

Do you have a local version? If you have that set up, you can test your own code.

**Comment by agnesnutter** [comment]
@deilann I see, I hadn't known Habit supported localization.

I've tried to set up a local version, but I get stuck on at least steps 2 and 5 of the Unix section (I _think_ I did 1 correctly). When I try to run the first line of code there, it tells me that `apt-get` isn't a command it knows about, and I don't know how to use Git with the command line. Should I `cd` into the local directory, or...?

**Comment by colegleason** [comment]
@agnesnutter What operating system do you use? I'll see if I can help you get your local install set up.

**Comment by agnesnutter** [comment]
@colegleason OS X Mavericks. I believe I've installed MongoDB, and I'm not sure whether I've successfully installed NodeJS.

**Comment by colegleason** [comment]
Ah okay. When you have time to do this, could you hop on the IRC chatroom [here](http://webchat.freenode.net/?channels=habitrpg). I'll do my best to get you setup.

**Comment by agnesnutter** [comment]
@colegleason Okay. I really need to get some sleep, and I’ll be away until Sunday evening, but I’d be glad for help from whomever will give it! Thanks. :)

**Comment by colegleason** [comment]
Sure. Feel free to comment here or email me if I'm not around.

Basically `apt-get` is only available for some Unix based operating systems. On Mac, I prefer to use Homebrew (`brew`). you can install Homebrew with:

```
ruby -e "$(curl -fsSL https://raw.github.com/Homebrew/homebrew/go/install)"
```

Then you could do `brew install nodejs`

**Pull request closed without merging**
