### PR TITLE
Backer-Gear Tweaks, matt tweak, add NPCs

### PR DESCRIPTION
**Pull request by Shaners**
A little redesign and movement of the backer sword and helmet. 

Modified Matt's graphic a bit.

Added some NPCs in case someone is working on developing the new features they are involved in.

### CODE REVIEW

**Comment by lefnire** [comment]
@Shaners awesome-sauce, pushed to develop - will go out with next restart. Couple points: Bailey seems to have a some artefacts on her left & right, I just set your `user.flags.newStuff` to show so you can see what I'm talking about. I think there's just some overlap between sprites on either side. Also, I started playing around putting Justin in the help-popovers. He's too big to be sure, and I'm not sure how I feel about the Justin-head; however, if I shrink his full NPC down to 60% or so it actually looks great. I stupidly reverted my staging, so I don't have visuals for you - but just wondering how you feel about my shrinking his NPC - does that pixel consistency for our app, or is it edge-case enough to sneak by? I'll get some screenshots of all 3 sometime to show you so you can make a judgement call

**Comment by Shaners** [comment]
Will fix Bailey up today, probably just a CSS positioning mistake. What if we had the sword and backpack cropped out? Still too tall? Alternatively we could cut out the question mark and just use it for on page elements. Not being able to see what it looks like now though kind of hard to think up the best solution. 2x zoom is an option and may work out well but rather try out alternatives first to keep the style consistency.

Should the NPC Sprite sheet and CSS be moved to img/sprites ?

**Comment by lefnire** [comment]
Yeah, let's move that. Ps, I deleted the sprite-sheet and added to
styles/app/npcs.styl

**Comment by Shaners** [comment]
I just noticed that! Also that I wrote 138 instead of the word height... In the future is it best to make a .styl and import it in index.styl? Or should I just leave that to someone else?

**Comment by lefnire** [comment]
can leave to me :) small enough step, and that way i can error-check before
pushing (since merged PRs to develop will hit beta on server cron)

**Comment by Shaners** [comment]
Aye aye, maybe I'll put a little comment into the .css file to let anyone know that they aren't really used. Is pets, eggs and etc following a similar thing?

**Comment by lefnire** [comment]
Yeah. Or at least, should be - if I'm using any css form /public/sprites,
then I'm being inconsistent and need to update

**Pull request merged**
