### PR TITLE
Community guidelines updates #4557

### PR DESCRIPTION
**Pull request by ojintoad**
Makes requested changes to community guidelines.

### CODE REVIEW

**Comment by lemoness** [comment]
Looks good!

**Comment by crookedneighbor** [comment]
Making one correction to the usernames, then I'll merge this in.

**Comment by crookedneighbor** [comment]
@ojintoad This will count towards a contributor tier. Can you post your user id here? It can be found in [settings > api](https://habitrpg.com/#/options/settings/api)

**Comment by ojintoad** [comment]
5949e91b-97bf-496a-a7b2-7d30f21265b2

**Comment by crookedneighbor** [comment]
@ojintoad Congratulations, you are now a tier 1 blacksmith!  You should receive 3 gems the next time you log in.

**Comment by ojintoad** [comment]
Ha ha, cool, thanks.

**Pull request merged**
