### PR TITLE
Enable resizing of message box (#11950)

### LINKED ISSUE #11950: PM / private message entry box cannot be expanded
AnneLine reported:

> Hi, Bug zappers. Not sure if this is a bug, or a design issue or.... ? Here's a photo
> I think a change may have been made to the combox system for PMs on line, and I can't tell if it is a glitch or intended behavior. I'm using Chrome if that is any help.
> We now have a large box of the message that was sent to us (that moves up and down, which is nice), but just 4 lines to type in for our message. Theoretically, we can make the com box larger, but THAT is not working... nothing happens when you try to enlarge the box. 

Enlarging the box is working in Firefox, but I've confirmed the same issue happens for me in Google Chrome.

### PR DESCRIPTION
**Pull request by ajeffrey**
Fixes #11950

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

Changed the max-height to just height in the SASS, so users can resize using the drag handle. Tested in Chrome & FF latest.

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: e3edc05f-de97-4761-996a-a6093ded57e4

### CODE REVIEW

**Comment by paglias** [comment]
Hi @ajeffrey , thanks for the PR! It's working well but I noticed that if you increase the height too much it starts to break the layout of the page. I think having a max height set to 300px should make sure the textarea can be expanded enough without breaking the layout of the page

**Comment by ajeffrey** [comment]
@paglias fair point - I'll add a cap to the height tonight

**Comment by ajeffrey** [comment]
@paglias not quite the same night but it's done now! Max-height of 300px has been added :)

**Comment by paglias** [comment]
@ajeffrey  thanks for this! I'm merging the PR and awarding your contributor tier.

Note that further tiers require increasing amounts of work from one to the next, so Tier 2 may require a couple of PRs or a larger PR to attain. But keep helping out and we'll express our gratitude accordingly!

**Pull request merged**
