### PR TITLE
Removed unused I18N strings from the `npc.json` files (related to issue #9957)

### PR DESCRIPTION
**Pull request by RaitheOfDureya**
[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
This PR fixes part of issue #9957

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
I have identified the following unused strings in the `npc.json` file.  No dynamically generated strings were found.

At the moment I only removed the strings from the `locales/en` folder to make it easier to revert if necessary. Once the strings are reviewed, I can delete them from other languages.

- justinIntroMessage2
- mattShall
- daniel
- danielText
- danielText2
- danielTextBroken
- danielText2Broken
- alexander
- welcomeMarket
- displayItemForGold
- displayEggForGold
- displayPotionForGold
- sellForGold
- ian
- ianText
- ianBrokenText
- donateText1
- donateText2
- donationDesc
- payWithCard
- payNote
- amazonInstructions
- classStats
- autoAllocateText
- spellsText
- moreClass
- tourWelcome
- tourExp
- tourDailies
- tourCron
- tourHP
- tourHabits
- tourStats
- tourGP
- tourAvatar
- tourScrollDown
- tourMuchMore
- tourNifty
- tourAvatarProceed
- tourToDosBrief
- tourDailiesBrief
- tourDailiesProceed
- tourHabitsBrief
- tourHabitsProceed
- tourRewardsBrief
- tourRewardsArmoire
- tourRewardsProceed
- welcome4
- welcome5

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 6544e17f-237b-4915-ae7e-47744c0dc1bd

### CODE REVIEW

**Comment by paglias** [comment]
let's go ahead and remove the strings from the other locales!

**Comment by RaitheOfDureya** [comment]
here you go, @paglias

**Comment by paglias** [comment]
thanks @RaitheOfDureya and welcome to the 5th tier 🎉

**Comment by RaitheOfDureya** [comment]
hooray! 
thanks, @paglias

**Pull request merged**
