### PR TITLE
Removed unused I18N strings from the `achievements.json` files (related to issue #9957)

### PR DESCRIPTION
**Pull request by RaitheOfDureya**
[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
This PR fixes part of issue #9957

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
The `achievements` files are well maintained. I just found the following unused string:

- share

At the moment I only removed this string from the locales/en folder to make it easier to revert if necessary. Once this string is reviewed, I can delete it from the other languages.

**Notes for future maintenance:**
I found several dynamically generated strings in this file:
```javascript
...
- .t(`achievement${achievementTitleCase}`)
- .t(`${achievementString}ModalText`)
- .t(`achievement${achievementTitleCase}ModalText`)
- `achievement${upperFirst(achievement.mountAchievement)}`;
...
```
e.g.,
- achievementBackToBasicsModalText
- achievementAllYourBaseModalText
- achievementAridAuthorityModalText
- achievementMonsterMagusModalText
...

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 6544e17f-237b-4915-ae7e-47744c0dc1bd

### CODE REVIEW

**Comment by paglias** [comment]
Thanks @RaitheOfDureya , looking good!

**Comment by RaitheOfDureya** [comment]
This is what I believe is to be my last commit on this issue. This journey (of more than 1 month) was long, but I believe it was very productive. Thanks for the support, reviews, and encouraging messages, @paglias!

**Comment by SabreCat** [comment]
~~Strings used in the achievements modal are turning up missing:~~

~~These won't be in the repository as literals, since the achievements library puts them together based on the name of the achievement.~~

**Comment by SabreCat** [comment]
Whoops, please disregard the above. Looks like it isn't this PR that changes those... 🤔

**Comment by RaitheOfDureya** [comment]
@SabreCat the strings you mentioned belong to the `generic.json` file.

https://github.com/HabitRPG/habitica/pull/12590

**Comment by SabreCat** [comment]
Turns out it wasn't a problem with the PRs anyway, but something going on with the commit history on our testing server!

**Pull request merged**
