### PR TITLE
allow password reset to work case-insensitively - Closes #9059

### LINKED ISSUE #9059: password reset process fails if a user's email address has upper-case letters
If a user's email address in Habitica contains any upper-case letters, when they use the password reset form, their account is not given a value for `auth.local.passwordResetCode` and they do not receive a password reset email. This happens even if they enter their email address into the reset form using the exact case that it's stored in in Habitica.

If their email address in their account is changed to all lower case, the password reset form works correctly, no matter whether they enter their email address into the form in the same case as it's stored in Habitica or a different case.

This looks like the code to be changed:
https://github.com/HabitRPG/habitica/blob/136947169b466ed02b12a151c4576c791154a069/website/server/controllers/api-v3/auth.js#L563-L564
The find command should be case-insensitive and the `toLowerCase` won't be needed.

### PR DESCRIPTION
**Pull request by outofthisworld**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: #9059
Fixes https://github.com/HabitRPG/habitica/issues/9059

### Changes
[//]: # Made querying database for users with a particular email case insensitive and escaped input. This is my first pull request and I thinking pushing screwed up the formatting >.<

[//]: #8555871

----
UUID:

### CODE REVIEW

**Comment by mrbeardy** [comment]
Seems like your editor has formatted the entire file to use 4-space indentation instead of 2-space. It's also removed the space before the function parentheses ([space-before-function-paren](https://eslint.org/docs/rules/space-before-function-paren)).

Have a look at your editor's settings and see if there's a way to disable it from forcing any formatting changes, or check if your editor has support for [EditorConfig](http://editorconfig.org/) and [ESLint](https://eslint.org/).

**Comment by Alys** [comment]
@outofthisworld You can view your changes in this PR with the whitespace changes hidden by clicking on the "Files changed" tab and then adding `?w=1` to the end of the URL, like this:

https://github.com/HabitRPG/habitica/pull/9063/files?w=1

As @mrbeardy says, the indentation has been changed. We will need it changed back to 2-space for consistency with our other code, and to make our lint checks pass. There's also other formatting changes around line 120 that should be reverted. If you need help working out how to clean up the PR, just let us know!

**Comment by SabreCat** [comment]
@outofthisworld What's the status on this? We're working our way through the PR backlog now that redesign bug fixing has slowed down a bit, so we can get this reviewed once it's ready!

**Comment by librarianmage** [comment]
@outofthisworld How are you doing on this?

**Comment by Alys** [comment]
@outofthisworld I'm closing this pull request since it still needs work, however if you'd like to keep working on this issue before another contributor takes it up, you'd be welcome to push fixes to this PR and reopen it!

**Pull request closed without merging**
