### PR TITLE
increase number of gems for contributors -- fixes https://github.com/HabitRPG/habitrpg/issues/3933

### PR DESCRIPTION
**Pull request by Alys**
Replaces old PR https://github.com/HabitRPG/habitrpg/pull/3956

@lefnire: Edit `20140831_increase_gems_for_previous_contributions.js` to uncomment one of the "var dbUsers" lines, then run it, capturing STDOUT to a file. Save the file somewhere safe so that if any contributors tell us that they haven't received their correct gem increase, we can check what actually happened.
- Finds all contributors (tier 8 and below) and increases their gems.
- Displays output for every user to show how many gems they had and how many are added.
- Does a separate db query after that to retrieve and display the new balances.

It might be a little bit over-engineered now... I started programming and forgot to stop. But good record-keeping is important for gem increases. :)

Note @lemoness's [comment in the original PR](https://github.com/HabitRPG/habitrpg/pull/3956#issuecomment-53974172): _"@lefnire text me when you run these; will send you text for a Bailey announcement/handle SM announcement"_

### CODE REVIEW

**Comment by Alys** [comment]
BTW, I've been assuming that I don't have access to modify the code which gives gems to new contributors when an admin raises their contribution tier - I haven't been able to find that code anywhere. If I am able to modify it to implement the new numbers of gems per tier, feel free to tell me where it is, if you'd like me to work on it. :)

**Comment by lefnire** [comment]
Code is here https://github.com/HabitRPG/habitrpg/blob/develop/src/controllers/hall.js#L60

**Comment by lefnire** [comment]
```
events.js:72
        throw er; // Unhandled 'error' event
              ^
TypeError: Cannot read property 'username' of undefined
    at query._id.$in (/Users/lefnire/Dropbox/Sites/habitrpg/website/migrations/20140831_increase_gems_for_previous_contributions.js:78:42)
    at loop (/Users/lefnire/Dropbox/Sites/habitrpg/website/node_modules/mongoskin/node_modules/mongodb/lib/mongodb/cursor.js:284:3)
    at Cursor.each (/Users/lefnire/Dropbox/Sites/habitrpg/website/node_modules/mongoskin/node_modules/mongodb/lib/mongodb/cursor.js:232:40)
    at /Users/lefnire/Dropbox/Sites/habitrpg/website/node_modules/mongoskin/node_modules/mongodb/lib/mongodb/cursor.js:245:14
    at Cursor.nextObject (/Users/lefnire/Dropbox/Sites/habitrpg/website/node_modules/mongoskin/node_modules/mongodb/lib/mongodb/cursor.js:678:5)
    at commandHandler (/Users/lefnire/Dropbox/Sites/habitrpg/website/node_modules/mongoskin/node_modules/mongodb/lib/mongodb/cursor.js:658:14)
    at /Users/lefnire/Dropbox/Sites/habitrpg/website/node_modules/mongoskin/node_modules/mongodb/lib/mongodb/db.js:1670:9
    at Server.Base._callHandler (/Users/lefnire/Dropbox/Sites/habitrpg/website/node_modules/mongoskin/node_modules/mongodb/lib/mongodb/connection/base.js:382:41)
    at /Users/lefnire/Dropbox/Sites/habitrpg/website/node_modules/mongoskin/node_modules/mongodb/lib/mongodb/connection/server.js:472:18
    at MongoReply.parseBody (/Users/lefnire/Dropbox/Sites/habitrpg/website/node_modules/mongoskin/node_modules/mongodb/lib/mongodb/responses/mongo_reply.js:68:5)
```

Probably due to some contribs being registered with Facebook `auth.facebook.id`. I'll poke around in a bit

**Comment by Alys** [comment]
Sorry about that username error! Easiest thing to do is just remove the username from the script, since it was in there only to provide slightly more friendly output. I've just done a PR for that.

Thanks for the link to updateHere. I am embarrassed that I missed it. :)

**Comment by Alys** [comment]
I've added a commit that changes src/controllers/hall.js to make it use the new number of gems for each tier (3 gems/tier for the first three tiers, and 4 gems/tier for the next four). I've tested pretty thoroughly but given the sensitive nature of this, it would be a good idea for someone else to review and test the code. https://github.com/HabitRPG/habitrpg/commit/2f566071144d27d4d9084d25085de87cf7ada0a8

**Pull request merged**
