### PR TITLE
improve code quality by auto style check #4054

### PR DESCRIPTION
**Pull request by gasolin**
The patch 
- add  `grunt jscs` command for style check
- use `param.shared` to shorten original `bower_components/habitrpg-shared/` path in grunt
- follow google js style guide https://google-styleguide.googlecode.com/svn/trunk/javascriptguide.xml
- fixed all `*.js` under `habitrpg/`, 
- add excludeFiles in `.jscsrc` to filter out `src/` js files

### CODE REVIEW

**Comment by gasolin** [comment]
@paglias would you like add some style check for code quality? 
If so, I could contribute git pre-commit hooks in followup patch

**Comment by paglias** [comment]
@gasolin this is something i might be ok with adding, especially something like jshint for checking code, but I think it should be discussed with @lefnire . The main point usually is that we try to avoid anything that could discourage new devs from helping

**Comment by gasolin** [comment]
It's a plus when I find the source is written in a consistency style. So I could focus on logic then the syntax. Current patch did passive style check (dev need to run the command first) and does not force any change. 

For files that not passed the style check yet, there's a whitelist (.jscsrc) as well. New devs could help turning the source in a consistency style.

**Comment by crookedneighbor** [comment]
Sorry it's taken me so long to look at this. I'd prefer to use ESLint: http://eslint.org/

Going to close this now, but feel free to open a new PR that uses ESLint and I'll review it.

**Pull request closed without merging**
