### PR TITLE
Revert "Removed 'freeRebirth' from user model and everywhere else in …

### PR DESCRIPTION
**Pull request by crookedneighbor**
Reverts HabitRPG/habitrpg#5396

### CODE REVIEW

**Comment by crookedneighbor** [comment]
Didn't actually need to do this.

**Comment by hairlessbear** [comment]
@crookedneighbor Out of curiosity, why was this reverted?

**Comment by crookedneighbor** [comment]
It wasn't reverted. I thought it was related to a problem we were having, but it turned out to be unrelated. I opened it and immediately closed it when it was obvious that it wasn't affecting things.

**Comment by hairlessbear** [comment]
Heh, that's what I get for not looking at the page carefully. My bad.

**Pull request closed without merging**
