### PR TITLE
Front page's Forgot Password will report an invalid email address instead of simply errorring. Does NOT include updated locals/en/front.json

### PR DESCRIPTION
**Pull request by gjoyner**
**Issue:** https://github.com/HabitRPG/habitrpg/issues/3815
**Referenced Pull Request:** https://github.com/HabitRPG/habitrpg-shared/pull/338
The issue with Forgot Password had to do with entering nothing at all in the field and submitting. There was also no validation on the email input.
**Technical Details:** Since the passed variable into authCtrl.resetPassword was null from nothing being in the field, the "Cannot call method `replace` of undefined" error would appear. To make things more appropriate, Angular email validation was implemented. I did give the form a name to try other things, but it probably isn't needed anymore, but doesn't affect anything by being in there. In the authCtrl.resetPassword function, it first checks to see if the email passed in is not null and has a length == 0. If either are true, a message general stating "please input a valid email address" appears via alert(). The language file was updated to show this message. To find this commit, please refer to the reference pull request.

### CODE REVIEW

**Comment by lefnire** [comment]
Would the `type="email"` angular email validator not be sufficient, such that we can exclude the `if(email == null || email.length == 0)`?

**Comment by gjoyner** [comment]
Probably. I think I had that in there originally before the type change as
part of testing, but if anything it's a failsafe absolutely ensuring we're
not getting an empty or null value in somehow.

**Comment by gjoyner** [comment]
If you want me to remove that check, I can. If not, does Javascript evaluate each part no matter what, or is it like Java's where, in an or statement, it immediately stops evaluating on the first false condition going from left to right?

**Comment by lefnire** [comment]
can never be too careful, naw let's keep it in then. TMK JS evals `||` by stopping on the first truthy encountered, LTR (as you say).

**Comment by lefnire** [comment]
[UUID](http://habitrpg.wikia.com/wiki/API_Options)?

**Comment by gjoyner** [comment]
3f1c7a39-0052-415b-a194-deeeade0c588

**Pull request merged**
