### PR TITLE
Fix sellModal data caching

### LINKED ISSUE #10687: amount to sell, maximum possible to sell, sell value/price are cached after selling one type of items in the Market
Steps to show/reproduce bug:

1. Go to the drawer in the Market.
2. Find two items that you own a **different** number of (e.g., you might have 5 Wolf Eggs and 7 Tiger Cub Eggs).
3. For the item that you own **less** of (Wolf Eggs in my example), sell 2 of them (it can be any number more than 1, but I'm using 2 as an example).
4. Click on the second item (Tiger Cub Eggs).
5. **Observe that the amount to sell has already been set to 2**. It should default at 1. This is the first bug.
6. Use the arrow buttons to increase the amount as far as it will go.
7. **Observe that you cannot increase the amount to the full maximum you should be allowed to - you're given the maximum from the first item that you sold.** I.e., in my example, when selling Tiger Cub Eggs, the maximum will be set at 5. It should be set to 7. This is the second bug.

I.e., after you've sold one type of item, the number to sell and the total number permissible to sell are saved in the form for the next type of item you want to sell. They should not be cached like that.

---
EDIT:
In addition, the sell value (price) is cached as described in https://github.com/HabitRPG/habitica/issues/10720

### LINKED ISSUE #11038: Selling a hatching potion displays the wrong price
Reported by @JSn1nj4 (b1781515-6c3f-4314-a126-705b1e8390e8): "Hi. When I'm looking at hatching potion selling prices in the web app, it says 3 gold per potion. They still sell for the same prices that show in the mobile app (2 gold for some, 3 for others, 4 for the zombie and cotton candy, and 5 for the gold for example), but they display wrong on the web app. This may be trivial to fix (maybe), but I'd like to use this to finally be able to contribute if that's ok."

image

(Should net you 4 gold, and does: only the display is wrong.)

### PR DESCRIPTION
**Pull request by JSn1nj4**
Fixes #10687 
Fixes #11038

### Changes
1. Add `optional` field to several dependencies in `package-lock.json`.
2. Remove `v-once` directive causing the modal to not load new data after first item's data is loaded. 

Regarding change 1), this was a result of running `npm i`. If necessary, I can revert this file.

For change 2), the modal was loading item data the first time, and the `item` component nested within the `sellModal` component was also updating correctly each time. But the description of the item, the amount of the item to sell, and the sell price loaded directly in the `sellModal` component were unchanging after the first time an item was loaded into the modal.

Removing this directive allows these sections of the modal to update each time.

----
UUID: b1781515-6c3f-4314-a126-705b1e8390e8

### CODE REVIEW

**Comment by JSn1nj4** [comment]
If necessary, I can revert the lock file. I added it only because it updated when I ran `npm i`, but I assume the way it was before is fine. The only change is that several deps had an `optional` field added to them.

**Comment by negue** [comment]
Could you revert the `package-lock.json` changes? Otherwise it fixes the issues :)

**Comment by JSn1nj4** [comment]
@negue will have to do tonight, but sure, I'll match it to what's currently on the `develop` branch.

Out of curiosity, does the "optional" thing cause a problem on non-Windows setups?

**Comment by negue** [comment]
I'm not that experienced with `package-lock.json` that I could answer this question^^, its just better not to change that json unless we add/remove packages.

**Comment by paglias** [comment]
@JSn1nj4 "optional" shouldn't cause any issue but in general we never make edits to package-lock.json unless we upgrade something or install a new package

**Comment by JSn1nj4** [comment]
Makes perfect sense. Thanks!

**Comment by JSn1nj4** [comment]
@negue done. Just waiting for Travis.

**Comment by JSn1nj4** [comment]
Should I be concerned about the last result? I only matched the `package-lock.json` file to the one on the develop branch. 😕

**Comment by JSn1nj4** [comment]
Looks like 1 issue that's repeating is here:
```
GET /groups/:groupId/invites
  returns only first 30 invites:
Error: Timeout of 10000ms exceeded. For async tests and hooks, ensure "done()" is called; if
  returning a Promise, ensure it resolves.
(/home/travis/build/HabitRPG/habitica/test/api/v3/integration/groups/GET-groups_groupId_invites.test.js)
```

So, I originally merged a bunch of changes from "develop" after glancing through them to manually make sure there was nothing I needed to change in my PR... Was that a mistake?

Also, I assume this means that the test coverage has fallen below the required threshold (or more code has been added that doesn't have tests with it):
image

If it's absolutely necessary, I can do an interactive rebase and keep only my own changes for the PR.

**Comment by paglias** [comment]
@JSn1nj4 no worries, it's something unrelated to your changes that we're trying to fix separately. I'll review your PR during these days

**Comment by JSn1nj4** [comment]
@paglias alright, thanks! Let me know if I need to merge more changes later to make Travis and Coveralls happy. Don't mind doing that.

**Comment by paglias** [comment]
@JSn1nj4 sorry, I didn't notice it before but looks like some changes from `develop` to package-lock.json are still there, could you revert it?

**Comment by JSn1nj4** [comment]
It looks like the version number on `develop` was updated after I committed `develop` version of package-lock.json yesterday. This should do it.

**Comment by paglias** [comment]
Thanks

The issue itself seems solved, but I just noticed that the amount of items you own in the drawer doens't update unless you change the tab. Anyway that's likely a separte issue so I'm marking this as ready and will go live next week, along with your contributor tier @JSn1nj4 !

**Comment by SabreCat** [comment]
Thanks for this, @JSn1nj4! It'll go into a staging environment for a few days, then if all is well go live around this time next week.

Welcome to the ranks of the Blacksmiths at tier 1! You'll see your rewards on Habitica when next you sync there. Note that successive tiers require increasing amounts of effort from one to the next, so tier 2 will require multiple PRs or a larger PR to attain. But keep helping out and we'll show our gratitude accordingly!

**Comment by JSn1nj4** [comment]
Thanks @SabreCat! I definitely look forward to continuing contributing as a Blacksmith. 🙂

**Pull request merged**
