### PR TITLE
Fixed minor text issues

### LINKED ISSUE #5345: Some issues on source English
Hello! I hope I'm doing this right. It's my first time posting anything on GitHub so I'm a little lost here. XD
I was translating in Korean on Transifex (known as NaYa there) and I noticed some grammar and term issues, and @paglias told me to report here, so here I am.

**1.** There are a couple occasions where "**Options**" is mentioned in an instruction, but in the game there is no "**Options**" because it is displayed as "**Menu**" instead when the main toolbar is collapsed (closed). Shouldn't the instructions also say "**Menu**" then to be consistent, or vice versa? Below are the lines I've found so far that contain this word.

_habitrpg/common/locales/en/generic.json
Line 73 "untilNoFace": "Until we add Facebook, use your UUID and API Token to log in (found at https://habitrpg.com > **Options** > Settings).",_

_habitrpg/common/locales/en/quests.json
Line 6 "questSend": "Clicking \"Invite\" will send an invitation to your party members. When all members have accepted or denied, the quest begins. See status under **Options** > Social > Party.",_

**2. Misuse of comma** (Hate to be a grammar nazi, but other translators have also commented on it, so a lot of others are probably also botered by it.)

_habitrpg/common/locales/en/character.json
Line 51 "battleGearText": "This is the gear you wear into battle, it affects numbers when interacting with your tasks.",_

This should not have a comma, but a semicolon or a period instead, like below:
"This is the gear you wear into battle. It affects numbers when interacting with your tasks."

### PR DESCRIPTION
**Pull request by mayajosyula**
Minor changes with grammar/terms/typing mistakes, fixes #5345.

### CODE REVIEW

**Comment by crookedneighbor** [comment]
Looks great to me.

**Comment by crookedneighbor** [comment]
This will count towards a contributor tier! What's your User ID? You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api). Be sure to only copy the User ID and _not_ your API Token.

**Comment by mayajosyula** [comment]
Thank you!

My ID is: 9261598f-9f1a-44ef-bcfb-dc8bc4a70d86

**Comment by crookedneighbor** [comment]
Notated toward your third contributor tier.

**Pull request merged**
