### PR TITLE
Moved menu expand directive and created menu close directive

### PR DESCRIPTION
**Pull request by TheHollidayInn**
This should partially address: #5490 .

I have moved the menu expand to a directive, because AngularJS seems to want DOM manipulation in a directive. This also make it easier for use to reuse the expanding.

I have added a new close directive which will close the menu when clicking on a new page per @alys comment on the issue.

### CODE REVIEW

**Comment by TheHollidayInn** [comment]
Hmm, I'm showing passing test when I run on my local machine even after rebasing. I'm not sure how to rerun the test either.

Also, are we writing protractor tests for directives?

**Comment by Alys** [comment]
The travis build had stalled. I've restarted it.

**Comment by TheHollidayInn** [comment]
Perfect, thanks!

**Comment by crookedneighbor** [comment]
Yes, we need tests for directives. https://github.com/HabitRPG/habitrpg/tree/develop/test/spec/directives

**Comment by crookedneighbor** [comment]
That said, directives can be particularly tricky to test. Let me know if you need help.

**Comment by TheHollidayInn** [comment]
Sweet, thanks. I have some tests. But, when I run grunt karma they don't show up. I don't see the other directive test either. Is there another command?

**Comment by crookedneighbor** [comment]
The test command should be `gulp test:karma` but it's basically an alias for `grunt karma`.

I opened up the directives test and put `only` on the top level describe block and it's definitely included in the test suite. IE:

``` js
describe.only('fromNow Directive', function() {
  var element, scope;
  var fromNow = 'recently';
  var diff    = 0;
```

**Comment by crookedneighbor** [comment]
Feel free to push up your tests.

**Comment by TheHollidayInn** [comment]
Okay, I installed Gulp and it worked. Also, is there a command to add JS files to the config files or do I need to keep entering them manually? I don't recall doing this before.

**Comment by crookedneighbor** [comment]
@TheHollidayInn do you mean the manifest.json file?

**Comment by crookedneighbor** [comment]
Or the karma.conf?

**Comment by TheHollidayInn** [comment]
Both, actually.

**Comment by crookedneighbor** [comment]
You got part of the way on the tests, I finished them up for you: https://github.com/HabitRPG/habitrpg/commit/9ddf5353d12825d506a686098511f703c9e27d44

About to leave some comments on the commit to explain why I changed the things I did.

**Comment by crookedneighbor** [comment]
Also, forgot to say, good work on moving this logic to a directive :+1:

I notated this toward your next tier.

**Comment by crookedneighbor** [comment]
Oh yeah, in answer to your questions, no there is no command to add them automatically, though I will soon do some globbing on the karma.conf so that you don't have to specify it every time you add a new file.

**Comment by TheHollidayInn** [comment]
Okay, dang, I was pretty off on those tests. Thanks for the notes. I will practice on some other directives as well after finishing your notes!

**Comment by crookedneighbor** [comment]
That sounds great. Happy to have more coverage!

Rereading some tests I wrote months ago and trying to figure out what my past self was thinking.

**Pull request merged**
