### PR TITLE
Some JP translations

### PR DESCRIPTION
**Pull request by nafoster**

### CODE REVIEW

**Comment by AdrienLemaire** [comment]
@nafoster I suggest you look at the [git tips](http://habitrpg.wikia.com/wiki/Guidance_for_Blacksmiths) so you learn how not to do an irrelevant commit "merge of upstream/develop in develop".  I think you did a merge instead of a rebase :)

**Comment by lefnire** [comment]
@Fandekasp cool if I leave you in charge of merging the JP and FR pulls?

**Comment by AdrienLemaire** [comment]
@lefnire ok :)

**Comment by nafoster** [comment]
@Fandekasp: Thanks for sharing those tips. I knew merging might have not been the best idea, but I didn't know about rebasing.

**Comment by AdrienLemaire** [comment]
Can't merge your branch with all those merge commits. I cherry-picked the correct commits in [develop](https://github.com/HabitRPG/habitrpg/commits/develop), please be more careful next time, thank you :)

**Pull request closed without merging**
