### PR TITLE
add confirmation for release pets/mounts, rebirth and reroll.

### LINKED ISSUE #4104: Pop-Up Confirmation needed for Release Pets/Mount/both, Orb of Rebirth, Fortify Potion
A user who accidentally released all their mounts requested a pop-up confirmation for the Release Pets feature like there is for Rebirth. Probably a good idea.
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/5063503-pop-up-confirmation-needed-for-release-pets-mount-both-orb-of-rebirth-fortify-potion?utm_campaign=plugin&utm_content=tracker%2F68393&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F68393&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by anilanar**
Fixes #4104.

### CODE REVIEW

**Comment by Alys** [comment]
Thank you for doing this! Could you please add screenshots of the new behaviour?

**Comment by crookedneighbor** [comment]
I'd prefer not to use confirmation boxes. Maybe use a popup like leaving a guild?

screen shot 2015-10-24 at 7 05 46 pm

**Comment by anilanar** [comment]
@crookedneighbor That looks better, I'll give it a try.

**Comment by crookedneighbor** [comment]
@anilanar I'm going to close this now so we have fewer pending PRs in the queue, but definitely re-open it once you've finished the changes.

**Pull request closed without merging**
