### PR TITLE
Fixed speech bubble misalignment on static.front

### LINKED ISSUE #5067: Static.Front page speech testimonial bubbles off center/not aligned properly.
Hello! I went and checked back onto the static front page and everything looks a lot better now and It's a lot easier to read the text without it moving away. I did however notice a small issue with speech bubble placement and alignment. On the "Players use HabitRPG to Manage" section, the subsections of "School" and "Chores" have a misaligned speech bubble.

Here are some photos to help.

staticfrontspeechbubblemisplace1
(Chores problem location: -popover.content)
https://github.com/HabitRPG/habitrpg/blob/develop/website/views/static/front.jade#L409

---

staticfrontspeechbubblemisplace2
(School Problem Location: -popover.content)
https://github.com/HabitRPG/habitrpg/blob/develop/website/views/static/front.jade#L328

---

This is what the normal line of code should be looking like:
https://github.com/HabitRPG/habitrpg/blob/develop/website/views/static/front.jade#L372

I will shortly post a pull request with an easy fix to the problem. I hope that since the issue is so small that it will alright to post the pull request as well as I have worked on this file before.

User ID:6f14571c-f2e9-4446-8e4e-591a7a3a42eb
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/11829899-static-front-page-speech-testimonial-bubbles-off-center-not-aligned-properly?utm_campaign=plugin&utm_content=tracker%2F68393&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F68393&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Rbrinkley**
Small fix. Edited speech bubble testimonial code to match code of others to properly align them. (Did I English right?). Fixes https://github.com/HabitRPG/habitrpg/issues/5067

### CODE REVIEW

**Comment by crookedneighbor** [comment]
Can you provide before and after screenshots?

**Comment by Rbrinkley** [comment]
I provided before screenshots in the original post. Here ya go:(https://github.com/HabitRPG/habitrpg/issues/5067) Do the after screenshots require setting up habitrpg locally? I've been really busy with things so I haven't been able to do that. _hides behind desk_

**Comment by Rbrinkley** [comment]
Also found another misalignment on this section 
staticfrontspeechbubblemisplace3

Code too: 
https://github.com/HabitRPG/habitrpg/blob/develop/website/views/static/front.jade#L434

**Comment by hairlessbear** [comment]
You should definitely try to get this running on your machine. I just quickly tried to integrate your code into my copy, and it broke the front page. All that displayed was `{
  "err": "/vagrant/website/views/static/front.jade:324\n    322|                   img.sample-img.visible-lg-in   327|                         .arrow\n\nInvalid indentation, you can use tabs or spaces but not both"
}` It's possible that I did something wrong, but at the very least, this shows that it's worth testing.

**Comment by Rbrinkley** [comment]
Alright. I don't have time to set it up locally tonight. I will likely have some time tomorrow and on friday. There may be other code involved that I overlooked. Maybe this ".usetweet-group" code? https://github.com/HabitRPG/habitrpg/blob/develop/website/views/static/front.jade#L329 . I got to get back to work. Hope this helps!

**Comment by hairlessbear** [comment]
For the record, I did make a mistake (using tabs instead of spaces). Once I fixed that, the page loaded as expected.

**Comment by hairlessbear** [comment]
That being said, the code you added didn't fix the alignment, but I noticed something interesting that may give a hint as to what's going on. All of the out-of-alignment speech bubbles are single lines of text (as implied, all of the properly aligned speech bubbles have multiple lines).  Additionally, the out-of-alignment speech bubbles are aligned with the multilined speech bubbles on the right. Although I don't know the exact mechanics, I suspect that the issue lies in whatever code is causing the speech bubbles to right-align together. If you can find that, you might find the root of your problem.

**Comment by hairlessbear** [comment]
I just did a little tinkering, and I didn't solve the issue, but I wanted to let you know what I discovered so you don't have to replicate my work. Each `popover-content` is contained within `usetweet.tweet.popover.right`. I thought that changing that "right" to "left" might fix the issue, but all it did was move the position of the speech bubble triangle, as you can see below.
selection_002

**Comment by AnitaYCheng** [comment]
I made the original static front page, and yes, the "right" and "left" arrow features are taken directly from Bootstrap popovers. 

In terms of the alignment issue, I expect that it might be the image is pulled left, and the bubble is pulled right. I did have it set to `max-width: 76%` width of its parent container, so perhaps it's the `max-width` that's throwing the short testimonials off. Try it with `width:76%;` and see if that helps!

I'm still fixing spacing on the original, and was going to convert to jade later..which I kinda don't look forward to because I still need to set everything up locally!

**Comment by Rbrinkley** [comment]
Also while we are on the static front page. Could we add more badge images to the "We also feature" section? It seems a bit lacking in visuals with only two badges.

staticfrontwealsofeaturebadgeslacking

**Comment by lemoness** [comment]
I would love more badges for this section! If you'd like to make that
change, go ahead.

**Comment by Rbrinkley** [comment]
I'd be glad to make the change. I just need to set up habitrpg locally to make sure my code works. I hope that's alright with you. Thanks again!

**Comment by Rbrinkley** [comment]
Should be able to get habitrpg installed locally tonight or tommorrow night. Is it easy to do? I keep putting it off because I think it will take a long time. Am I correct? I have already gotten some of it done but I am still putting it off.

**Comment by hairlessbear** [comment]
Only way to find out is to try it yourself :) Worst case scenario, it doesn't work and you get installation troubleshooting help in the Aspring Coders guild. And for what it's worth, I installed locally on Linux Mint, and everything went smoothly. 

And don't forget, if it does take a while, you can always put it down and come back to it later. There's nothing forcing you to do it all in one go.

**Comment by Rbrinkley** [comment]
Will do. Thanks for the info. I'll make sure to force myself to try and work on it tonight. I will get this done one way or another. Thanks again.

**Comment by crookedneighbor** [comment]
@Rbrinkley Re-open if you'd like to continue working on it.

**Pull request closed without merging**
