### PR TITLE
Improve the checklists in the apidocs

### LINKED ISSUE #13450: Missing checklist information in API-docs
### background
This issue is in response to the suggestion of @Alys in the Comrade guild chat.

### Description
*Summary:* Checklist information is missing in the habitica [API-docs](https://habitica.com/apidoc/)

#### 1. CreateUserTasks endpoint
The API-docs for <https://habitica.com/apidoc/#api-Task-CreateUserTasks> are missing the `checklist` body parameter.
The wiki does give a good example here [source](https://habitica.fandom.com/wiki/Application_Programming_Interface):
```bash
$ curl -X POST \
    # ...
    -d '{
    "checklist": [
            { "text": "1st checklist item", "completed": false },
            { "text": "2nd checklist item", "completed": false }
        ],
```

apidocs

#### 2. AddChecklistItem and UpdateChecklistItem endpoint
As I was writing this down, I noticed that other endpoints are also missing information that is implicitly mentioned in the wiki.
For example, <https://habitica.com/apidoc/#api-Task-AddChecklistItem> does not make mention of `<completed>` body parameter. It is also unclear if the <https://habitica.com/apidoc/#api-Task-UpdateChecklistItem> supports the `<completed>` body.

### PR DESCRIPTION
**Pull request by melvio**
[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)
This ticket adds additional checklist information to the Apidocs of `website/server/controllers/api-v3/tasks.js` as talked about with @alys in the comrade guild.

---

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #13450 

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
The following changes have been introduced:
* Added checklist examples to the APIdocs
* Added the 'completed' field to checklist items
* Fixed minor typo's in nearby docs

Here are some of the side-by-side visual changes (please ignore the dark mode which is provided by a chrome plugin :wink: ):

changes-apidocs1

---

changes-apidocs2

---

changes-apidocs3

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)
----
UUID: 79551d98-31e9-42b4-b7fa-9d89b0944319

### CODE REVIEW

**Comment by melvio** [comment]
@Alys  think I might have used the wrong format in my PR because the issue to be resolved is not linked in this PR.  
This PR is ready for review.

**Comment by melvio** [comment]
I updated the description to say `fixes #13450` instead of `Fixes issue #13450`. Now the issue is properly linked to this PR [github docs](https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue)

**Comment by melvio** [comment]
Thanks @SabreCat for marking it ready for review :slightly_smiling_face:

**Review by SabreCat — APPROVED** [review]

**Comment by SabreCat** [comment]
Thanks for this, @melvio! I've added this to your contributor credits, including the Blacksmith title. Because you already had a tier from other work, a single PR won't bump you to tier 2 right away, but keep helping out and we'll bump you up accordingly!

**Comment by melvio** [comment]
Thanks @SabreCat for your help:ok_hand:. It feels good to be in the coveted Blacksmith ranks :smiley:

**Pull request merged**
