### PR TITLE
Prevent Chilling Frost from keeping streaks on challenge Dailies

### LINKED ISSUE #7809: Chilling Frost skill freezes the streaks on challenge Dailies
Chilling Frost freezes streaks on Challenge Dailies.

<strike>This is consistent with being able to edit the streaks on Dailies (necessary for recovering from unexpected crons), but not consistent with the policy that skills can't be used to affect challenge tasks. Perhaps we didn't change this when API v3 was being built due to just an oversight (I didn't think of it until cTheDragons asked about it). I'm pretty much on the fence about whether it should affect challenge tasks or not - perhaps slightly on the side of not affecting them. What do others think?</strike>

The skill should be changed so that it does NOT freeze the streak for Challenge Dailies.

### PR DESCRIPTION
**Pull request by librarianmage**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)

Fixes #7809 

### Changes

[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

Note: need to change wiki entry on merging

[//]: # (Put User ID in here - found in Settings -> API)

----
UUID: 95f16006-1504-4a9f-95b6-0c7314dbd7ee

### CODE REVIEW

**Review by crookedneighbor — CHANGES_REQUESTED** [review]
There should be tests around this behavior.

**Comment by MathWhiz** [comment]
Sorry for the messy commit history...

**Comment by librarianmage** [comment]
I'm not sure where I should put my test, @crookedneighbor.

**Comment by Alys** [comment]
@MathWhiz I'm sorry but this also needs code to prevent Group Plan tasks being affected by the skill. There's actually a PR for other skills being worked on now: https://github.com/HabitRPG/habitica/pull/8427 and soon the code from there will be abstracted to a static method inside the Task model, which would make it much easier for you to adjust your PR to exclude Group Plan tasks too. It might be best if this is put on hold for a week or too until that method is available.

**Comment by paglias** [comment]
task.challenge is always defined, the check should be on task.challenge.id

**Comment by Alys** [comment]
@MathWhiz : Once this issue has been completed, you'll be able to use a method for checking the task:
https://github.com/HabitRPG/habitica/issues/8452 ("abstract the code that checks for a task belonging to a challenge or a group plan")

It might be a couple of weeks before it's done.

**Comment by librarianmage** [comment]
Ok, I will wait. Thank you!

**Comment by SabreCat** [comment]
The PR that was a prerequisite for this got abandoned. @MathWhiz, if you'd like to take that up on your own, you can! I will close this PR for now; we can reopen it when things are clear for it to move.

**Comment by librarianmage** [comment]
@SabreCat, I am not sure if I can take up that issue for the moment; feel free to leave it open for others.

**Pull request closed without merging**
