### PR TITLE
#9354 Indicate that Orb of Rebirth is instant

### PR DESCRIPTION
**Pull request by stephqwu**
Clarified the text

[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes put_issue_url_here

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID:

### CODE REVIEW

**Comment by paglias** [comment]
Hi @stephqwu can you change the text only in `locales/en`? Other languages are handled outside github as explained here https://github.com/HabitRPG/habitica/blob/develop/website/common/locales/README.md

**Comment by stephqwu** [comment]
@paglias Sorry!! I was not aware - will be taking greater care going forward :)

**Comment by SabreCat** [comment]
@stephqwu Thank you! We'll get it merged with the next batch of contributor PRs. What's your Habitica User ID? You can find it at https://habitica.com/user/settings/api . Let us know and we can get you contributor credit for this!

**Comment by paglias** [comment]
@stephqwu thanks for this, I'm merging the PR, if you can provide us your Habitica UUID I'll be happy to award your contributor tier :)

**Comment by stephqwu** [comment]
@SabreCat @paglias Thanks! My User ID is e6d8cc0e-8e9b-44de-97f5-78af3085e894

**Comment by paglias** [comment]
@stephqwu I've awarded you contributor tier!

Note that further tiers require increasing amounts of work from one to the next, so Tier 2 may require a couple of PRs or a larger PR to attain. But keep helping out and we'll express our gratitude accordingly!

**Pull request merged**
