### PR TITLE
Market poptop fix

### PR DESCRIPTION
**Pull request by taldin**
Switched the right side of the market to have popover-placement='top'.   Original version of the fix (#4286) had all popovers converted to 'top', but it turns out that the left side has to stay 'right' because the popovers truncate at the edge of the browser window for the leftmost items.  (See also #4278.)

### CODE REVIEW

**Comment by crookedneighbor** [comment]
While it does solve the flickering problem, it introduces a new one. Unless the window is absurdly big, the popovers start ascending up and to the right as you hover over the right most items.

eggs

**Comment by crookedneighbor** [comment]
If this gets merged in, it will close #4305

**Comment by Alys** [comment]
Is it worth merging this now and fixing the popover-ascending problem later? That seems like a lesser issue, and not one that stops users doing what they need to do.

**Comment by crookedneighbor** [comment]
It probably is, but I dislike adding a new bug to squash an old one. 

Does anyone know why the items on the left's popovers adjust their widths when they reach the edge of their container, but the ones on the right do not?

**Comment by Alys** [comment]
If the new bug really is just cosmetic, then it's better than the old one which prevents a feature being used (there is a workaround but the user might not figure it out for themselves). I think we should merge this now-ish so that it goes live with the deployment that will be happening soon for the backgrounds.

**Comment by Alys** [comment]
Merged. I tested and this is definitely an improvement. Before this fix, the entire right-most column of gem-purchasable goods were not purchasable (annoying for the users; and fewer gems would be spent).

After the fix, everything is purchasable. The labels for the eggs, potions, and food are a bit too high (some users probably won't even notice). The labels for four of the quests are MUCH too high, but the quests can still be bought (if you can work out what they are). Overall, it's a better situation.

**Comment by Alys** [comment]
@taldin Thank you for this! I've noted it as partial credit towards tier 6. You have two partial credits now. I'm not sure how much more is needed; I'll leave that in the hands of people more experienced than I.

I've logged a new issue for the new popover misplacement: [Popovers misplaced on right side of Market and Pets screens - Issue #4307](https://github.com/HabitRPG/habitrpg/issues/4307)

**Pull request merged**
