### PR TITLE
Special Pets that you don't own will only show GreyPaw print | Fixes #[10866]

### LINKED ISSUE #10866: Special Pets that you don't own should show only grey pawprint
When you do not own a Special Pet, the only indicator that you see in the Stable should be the grey pawprint, not the black pawprint or the greyed-out image of the pet.

For example, for the Royal Purple Gryphon, you should see only this light grey pawprint for the Pet when you don't own it:

image

Currently, you see the black pawprint if you don't own the pet but do own a Gryphon egg and Royal Purple potion (you shouldn't see the black pawprint because you can never hatch that pet). You see the greyed-out image of the pet if you own the mount but not the pet. I.e., both of these are wrong:

image

image

In summary, the code that decides what kind of icon to show for a Pet should have different handling for Special Pets so that it shows only the grey pawprint regardless of what other items the user owns.

----

_NB we do have https://github.com/HabitRPG/habitica/issues/9498 to completely hide the pawprints for **some** pets and mounts but even after that issue has been fixed, this new one would still be a problem for the pets that should show pawprints (e.g., if you buy a special mount with an Hourglass without buying the pet)._

### PR DESCRIPTION
**Pull request by Scanace**
Fixes #10866 

### Changes
This PR aims to adjust the decision logic with which the type of icon of the animal to be shown is chosen. 

The possibilities of an icon are:

| Icon | Description |
| --- | --- |
| PixelPaw  | The pet __is hatchable__ in some way |
| GreyedOut PixelPaw | The pet __is not hatchable__ in any way |
| Pet  | The pet __is owned__ |
| GreyedOut Pet | The __mount__ relative to the pet __is owned__ |
| PetEgg HatchingPotion | The __mount__ relative to the pet __is owned__ and the pet  __is hatchable__ in some way|

To make sure that the icon shown in case of a special animal not owned was __GreyedOut PixelPaw__ I checked if the pet was not owned and if it was a special one `!isOwned && isSpecial`.

I put this PR as a WIP because I'm not sure which is the correct icon to be shown in case of __PetEgg HatchingPotion__ icon.

Here some screenshots to demonstrate the changes:
#### Previously incorrect situation
previously-incorrect-situation

#### Currently correct situation
currently-correct-situation

----
UUID: ef6803f9-7cf4-4659-8eef-ccf345c1d933

### CODE REVIEW

**Comment by paglias** [comment]
Thanks @Scanace ! @SabreCat @Alys do you know which icon should be used in this case: 

> I put this PR as a WIP because I'm not sure which is the correct icon to be shown in case of PetEgg HatchingPotion icon.

?

**Comment by majestic-owl448** [comment]
I am not Alys or SabreCat, but I think Potion+egg should tell that you can hatch the pet, as special pets can't be hatched in any way it should show only the grey paw print.

Is that the royal purple gryphon pet? That was a bug and should be fixed now, see https://github.com/HabitRPG/habitica/issues/10253

**Comment by paglias** [comment]
thanks @Ieahleen :) The issue this is fixing should be https://github.com/HabitRPG/habitica/issues/10866

**Comment by majestic-owl448** [comment]
I get it, #10253 was fixed by making so that in the inventory the combination gryphon egg+royal purple hatching potion wasn't highlighted but it didn't fix the display in the stable. Sorry for the confusion

**Comment by Scanace** [comment]
Thanks for the answers @paglias and @Ieahleen!

I'll fix this using the __GreyedOut PixelPaw__  icon in the next days.

**Comment by Scanace** [comment]
__The situation is now corrected__

corrected-situation

__Summary of changes:__

- Added isSpecial function to determine wether a pet is special or not
- Special pets that you don't own show only grey pawprint
- PetEgg HatchingPotion icon (ex. royal gryphon) is now only visible if the pet is not a special one

**Comment by paglias** [comment]
@Scanace sorry for the delay! Can you try to remove the extraneous commits that got added in the PR? It might be easier to just create a new branch from an updated version of `develop` and apply your changes there. Let me know if you have any question!

**Comment by Scanace** [comment]
I'm sorry for the delay too! I will do it tomorrow, such a big mistake working on develop 🙈

**Comment by paglias** [comment]
@Scanace thanks! I think it might be a good idea to create a new clean branch, apply the changes there and open a new PR :)

**Comment by Scanace** [comment]
Yes, it would be definitely easier as I tried to clean it without opening a new one but couldn't figure out how to do it...

**Pull request closed without merging**
