### PR TITLE
Kubernetes support for dev environments

### PR DESCRIPTION
**Pull request by SabreCat**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Continuation of https://github.com/HabitRPG/habitica/pull/6965. @ksonney, if you would like to resume work there, just say the word!

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

>This enhances the existing docker support by adding the needed files to use kubernetes as an upstream cloud controller. This has been tested against AWS, but should be easily adapted to other cloud providers.
>
>From an admin perspective, this starts work on being able to scale habitrpg horizontally. At the moment, it provides support for a persistent mongodb, and one or more web front end containers. Future plans for this include scaling mongodb horizontally, and then cross-region replication (that last one is the tricky one).

[//]: # (Put User ID in here - found in Settings -> API)

----
UUID: 4406436b-b20d-4bde-b4c7-af2fed26f90e

### CODE REVIEW

**Comment by SabreCat** [comment]
Requesting review from @TheHollidayInn as he has been working on containerized builds for Habit lately.

@khipkin, do the changes in my latest commit sufficiently address your comments from the other PR? I will need to try to get this working to include sample success output, but I think that's the only piece I haven't explicitly covered.

**Comment by ksonney** [comment]
I will be adding to it when I have the chance, sadly my day job has been eating all my free time to contribute of late. I will do a review as well, if that's OK.

**Comment by ksonney** [comment]
Documentation updates look good to me!

**Review by TheHollidayInn — APPROVED** [review]

**Comment by SabreCat** [comment]
I'm sorry you ended up waiting so long over this, but @ksonney, thank you for your contribution! I've awarded you Blacksmith tier 1 for your help.

**Comment by ksonney** [comment]
Better late and "correct" than not at all. Thank you!

**Pull request merged**
