### PR TITLE
Task achievement

### LINKED ISSUE #8663: New Achievements and Badges: Checked off X Tasks
These new achievements and badges are ready to be implemented! These should be received when a player checks off the number of tasks indicated by each badge. The badge images and the names/mouseover text for the user achievement page can be found here:

https://trello.com/c/PMBVCiyv/4-checked-off-x-tasks-badges

### PR DESCRIPTION
**Pull request by librarianmage**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #8663 

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

[//]: # (Put User ID in here - found in Settings -> API)

----
UUID:

### CODE REVIEW

**Comment by SabreCat** [comment]
@MathWhiz, we'd love to incorporate this, but it looks like it's still on the old client. Would you be up to adapting it for the Vue client?

**Comment by librarianmage** [comment]
Oh no, I've totally forgotten about this! I'll do it when I can complete my
homework.

**Comment by librarianmage** [comment]
Updated! @SabreCat

**Comment by librarianmage** [comment]
I have tested it, and it doesn't update the actual achievement.

**Comment by librarianmage** [comment]
I don't think the new client will update the sprites / text D:

**Comment by SabreCat** [comment]
Uh oh! What do you mean by the new client not updating sprites and text? You do still need to do `npm run sprites` to compile spritesheets, we haven't eliminated those yet. (Though please don't commit the resulting spritesheet PNGs or CSS, it's far easier for us to rebuild those after merge!)

**Comment by librarianmage** [comment]
I may have forgotten to do that, but another issue is that it doesn't
update in the achievements part of the member modal until I completely
refresh the page.

**Comment by SabreCat** [comment]
Hmm. That it's showing up after a refresh may be OK, but it'd definitely be better to have it dynamically update. I wonder if we may need to move `achievements` from a data property to a computed one or a method, in https://github.com/HabitRPG/habitica/blob/develop/website/client/components/userMenu/profile.vue . @TheHollidayInn / @paglias , what do you think?

**Comment by paglias** [comment]
Is the problem that this line isn't called `https://github.com/HabitRPG/habitica/blob/develop/website/client/components/userMenu/profile.vue#L673`?

**Comment by librarianmage** [comment]
@paglias I don't know — how would I check?

https://github.com/HabitRPG/habitica/blob/12fd79059b09f258bf9f7d54415180f03a2c8ba8/website/client/components/userMenu/profile.vue#L673

**Comment by paglias** [comment]
@MathWhiz you can try adding a console.log before that line and see if it's called when the achievements are updated

**Comment by paglias** [comment]
hey @MathWhiz how are you doing on this?

**Comment by librarianmage** [comment]
@paglias I completely forgot about this, oops. I'll see if I can get to it this weekend

**Comment by librarianmage** [comment]
Unfortunately, I haven't had time to work on this.

**Comment by lemoness** [comment]
@MathWhiz Do you want to keep working on this, or would you prefer to give up your claim?

**Comment by librarianmage** [comment]
@lemoness I think I will cede my claim.

**Pull request closed without merging**
