### PR TITLE
Apply Dropdown Styles to various parts

### LINKED ISSUE #12795: View Party / Guild "sort by class" and "Asc" drop down visual inconsistencies
_@tripplehelix (874e648a-2df7-4312-a9e6-7217be462204) reports:_

"The 'View Party' overlay has a different drop down type to the rest of the Habitica website. This is causing inconsistencies with the overall colour theme."

It also applies to guilds and to the Asc/Desc dropdown in the same modal.

I'm labelling this as "on hold - needs design" for a design-related decision about any potential fix.
 
image

image

### PR DESCRIPTION
**Pull request by negue**
fixes #12795

- [x] fixed dropdown style in party modal
- [x] fixed unequip-button style
- [x] fixed challenge add task dropdown

### CODE REVIEW

**Review by paglias — APPROVED** [review]
Code LGTM! So if design is fine it can be merged

**Comment by paglias** [comment]
@negue looks like the text wrapping when a dropdown item is longer than the dropdown with has some issues 
Schermata 2020-11-28 alle 19 21 56

**Comment by negue** [comment]
@paglias its quite odd that this css rule from 2018:

```css
  .dropdown-menu.show {
    width: 100% !important;
  }
```

causes this 😄 , if I change it to `min-width` it still applies to the button width AND also expands if needed (for your example) now

pushed to delta

**Comment by paglias** [comment]
Looks good now! I also tested a bunch of other dropdowns and nothing seems broken

**Pull request merged**
