### PR TITLE
removed broken img tag and added quotes to malformed a tags

### PR DESCRIPTION
**Pull request by tylerdmace**
General cleanup of public/500.html - we'll probably want to replace the picture eventually but no image is better than a broken one.

### CODE REVIEW

**Comment by paglias** [comment]
@tylerdmace I think this page is a bit outdated and I'm not even sure it's used in place of the default one by Heroku

**Comment by tylerdmace** [comment]
Would it be better to remove it entirely - or keep it around as a second line of defense (in the future Heroku may not be part of the picture, perhaps)?

**Comment by paglias** [comment]
@tylerdmace I'm not sure, let's ping @lefnire

**Comment by tylerdmace** [comment]
I wasn't sure if the memory leak message was even relevant at this point, either. Not sure where you're all at with the rewrite which was supposed to have fixed the closed issue.

**Comment by paglias** [comment]
@tylerdmace it's quite old, the rewrite has been done more than a year ago :)

**Comment by lefnire** [comment]
LTGM. I dunno if this page shows up anymore really, but a fix is a fix!

**Comment by lefnire** [comment]
@tylerdmace UUID?

**Comment by tylerdmace** [comment]
@lefnire 1a0b5d99-9d18-4b46-beb1-cca52fb80851

**Comment by lefnire** [comment]
@tylerdmace contrib.lvl++, thanks!

**Pull request merged**
