### PR TITLE
Added Pet css sprite and removed genders from player css sprites

### PR DESCRIPTION
**Pull request by Pandoro**
1. Added one sprite containing all of @Shaners' pets.
2. Fused male and female back together to 1 spritesheet again. Genders were removed although the same appearance should be obtainable with the new system! 

Proceed with caution!
The hairstyles had to be modified a little. Now there is 1 hairstyle for when players are not wearing a helmet yet. These have a "nh_" prefix in the name and the other hairstyles should be used if people are wearing a helmet. 

As both "gender" versions have been fused, often there are at least 2 or 3 versions for each item. I am not sure if there is any 1 to 1 mapping between the old and new names :( 

I took the liberty to flip the pets. These were aligned to fit the right side of the player. The pets can be moved around a little, but the alignment between pets should not be changed, or rather read, should not need to change, as I tried to align them before hand. If people don't like this, we can further experiment. I just wanted to get a sprite on the server. We can freely change this!

### CODE REVIEW

**Comment by lefnire** [comment]
awesome, awesome. i'm gonna merge this later since it takes a bit of /styles/*.styl reworking, i'll try not to wait too long so as to not let it go stale

**Comment by lefnire** [comment]
Hey @Pandoro I just created a `pets` branch. This PR is gonna require some reworking against the current html elements, so I don't want to merge it to `master` just yet. Can you close this and re-open a PR to the `pets` branch?

**Comment by Pandoro** [comment]
Will do soon. However with the recent developments in  #107 regarding pet
and mount placing, this might again have been outdated... So there is no
immediate need to merge this. Furthermore the player sprites don't need to
be in the pet branch. Should I shoot to PRs? If so which branch should the
player branch goto? development?

**Comment by lefnire** [comment]
Yeah, players can go to develop - then pets to pets. No worries about dirty
pushes, even if you're gonna clean up later.

**Comment by switz** [comment]
The css selectors aren't really valid. They need a `.` prefacing them to ensure that it's matching a class.

**Comment by Pandoro** [comment]
Hmmm sorry about that, I created these using a gimp plugin :x

Any easy find and replace solutions here?

**Comment by lefnire** [comment]
No worries, we got it taken care of. It's a quick fix, so I wouldn't even
worry in the future.

**Comment by lefnire** [comment]
actually, this was merged into our pets branch: https://github.com/switz/habitrpg/tree/inventory , so I'll close this (your commits & name will still show in the history)

**Pull request closed without merging**
