### PR TITLE
Issue 3852 vagrant

### PR DESCRIPTION
**Pull request by melissamcewen**
Adds provisioning as recommended by MongoDB documentation. Tested on local development environment twice. 

http://docs.mongodb.org/manual/tutorial/install-mongodb-on-ubuntu/

### CODE REVIEW

**Comment by Alys** [comment]
Adding a link to the issue: https://github.com/HabitRPG/habitrpg/issues/3852

Thanks @melissamcewen! I'll run up a new VM with this and see how it goes.

**Comment by Alys** [comment]
@melissamcewen This is close to what we want, but it installs version 3 of mongodb, whereas we want to keep the version as close to that used in production as possible for consistency. It's important that we can't build code that uses database features that aren't yet available in production. This page is probably a good guide: http://idroot.net/tutorials/install-mongodb-ubuntu-14-04/

Also you won't need to put sudo at the start of the commands because vagrant.sh runs all of its commands as root. Using sudo won't hurt of course, but leaving it out would be better for clarity and consistency with the other commands.

**Comment by melissamcewen** [comment]
Ah OK, I"ll fix that and test this afternoon.

**Comment by melissamcewen** [comment]
OK it installs the right version now. An issue I had was that even if I put the list file installation before the first apt-get update, it failed to get the correct packages. I had to run it again to get it to work.

**Comment by Alys** [comment]
@melissamcewen I'm sorry this is taking so long to be reviewed. I'm trying to set up a new VM using your changes, and I almost always have trouble setting up VMs (nothing wrong with your code). The process either hangs part way through (laptop memory issues probably), or fails when my internet connection drops out during a package download (annoyingly common), and it's being particularly troublesome at the moment. I've got far enough to know that the database definitely installs correctly, with the correct version, but I want to take it all the way to the end so we can be absolutely sure that the database is usable. I will keep trying until I get it working!  I just wanted to let you know that your work is not being ignored.

**Comment by melissamcewen** [comment]
Thanks Alys, totally understandable, that happens on my home computer too.

**Comment by crookedneighbor** [comment]
@melissamcewen I'm trying this out now. Takes a while to download the vagrant vm for the first time, so I may need to check back in with you tomorrow morning. Sorry this has taken so long.

**Comment by crookedneighbor** [comment]
Actually, downloaded faster than I thought. Everything looks good to me. @Alys anything you want me to check before merging in?

**Comment by Alys** [comment]
As long as you can create an account and tick off a couple of tasks it should be fine. Thanks for picking this up. It's been driving me crazy - I just can't get `npm install` to finish. I dread the next time I have to re-do my own VM.

**Comment by Alys** [comment]
MERGED! Finally. Thank you for being so patient! Tier 3 awarded.

Note that the higher tiers require more effort than the lower ones, so if you make any small changes from now on, you might find that they won't grant you an extra tier immediately, but they will be noted as partial credit towards a tier. There's a bit of information about that at [Contributor Rewards](http://habitrpg.wikia.com/wiki/Contributor_Rewards) but do ask if you have questions.

**Pull request merged**
