### PR TITLE
Misc Webhooks Fixes

### LINKED ISSUE #12036: questFinished webhook sent multiple times
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: fa756acf-9127-4a3c-8dac-8ff627d30073

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

I have a `questFinished` webhook set up and it used to work just fine, until last Friday (March 27) it started to get called multiple times. Since then it has been called 2-4 times every time we finish a quest.

Expected behavior is to be called only once per quest.

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

### PR DESCRIPTION
**Pull request by paglias**
- [x] handle existing webhooks without protocol
- [x] correctly follow redirects
- [x] do not parse response as json
- [x] upgrade got to version 10

Fixes #12036
Fixes #12026

### CODE REVIEW

**Comment by paglias** [comment]
@Alys is there a guild where people that are more likely to use webhooks can be found? i'd like to let them know that some webhooks might have been disabled incorrectly

**Comment by Alys** [comment]
@paglias Aspiring Comrades will be the best place to post.
From there we'll copy it to the wiki.

**Comment by paglias** [comment]
@Alys I posted a few good practices in a message in the Aspiring Comrades!

**Comment by Alys** [comment]
The wiki's [Webhooks](https://habitica.fandom.com/wiki/Webhooks) page has been updated with that information, mostly by @Squall

**Pull request merged**
