### PR TITLE
new knight player tier added

### PR DESCRIPTION
**Pull request by AdrienLemaire**
Right now, only NPC can have custom gears, but it wouldn't cost habitrpg much efforts to give custom gears to some contributors (especially if they design their own custom gear).

new player tier

### CODE REVIEW

**Comment by AdrienLemaire** [comment]
If this feature is accepted, you'll probably want to change the name, if we use **knight** for multi-badges contributors

**Comment by lefnire** [comment]
Actually, we should combine with this PR [the new color spectrum](http://community.habitrpg.com/content/color-spectrum-contribs-details-comments) (@lemoness), since the current PR introduces a color in conflict with that decision. @Fandekasp you up for changing the colors? 

Also, @bobbyroberts99 is this PR ok for down-the-road changes you had in mind a la [Trello](https://trello.com/c/wkFzONhE/277-contributor-gear)?

**Comment by bobbyroberts99** [comment]
Although I think it kicks the can down the road a bit, I don't think more levels creates a system that encourages and rewards contributions indefinitely. @fandekasp will have nowhere to go soon.

How about a points-based system that could also be used to calculate potential monetary sharing ala bettermeans (check vids on YouTube re credits and retrospectives modules)?

We've also currently got 3 buried levels that could have their own names and colors.

**Comment by AdrienLemaire** [comment]
Honestly, I don't think HabitRPG should expect contributors to be active forever. Monetary sharing might be an excellent way to keep contributors active a bit longer, but only when the company will be profitable, which I'm not sure it is right now. Anyways, retrospective is quite a nice idea :)

@bobbyroberts99 what do you mean by "We got 3 buried levels" ? What levels are you talking about ?

@lefnire I'm up for the task, will change all colors to rainbow style in this branch :)

**Comment by bobbyroberts99** [comment]
@fandekasp, Friend 2, Elite 4 and Champion 6 have same colors and names as predecessor. I'm suggesting one color and a distinct name for each level. 

I'm going to redo mockups to be based on points rather than badges. Will post link on trello when it's done.

**Comment by AdrienLemaire** [comment]
See also my answer to the [forum post](http://community.habitrpg.com/content/color-spectrum-contribs-details-comments#comment-1702).  I'll wait for us to agree on something before implementing anything

**Comment by lemoness** [comment]
I really like wc8's duration idea!

**Comment by Alys** [comment]
I'm closing this because we now have [Contributor Rewards](http://habitrpg.wikia.com/wiki/Contributor_Rewards) for almost all of the contrib tiers and a new colour scheme has been put in place.

**Pull request closed without merging**
