### PR TITLE
Removed unused I18N strings from the `generic.json` files (related to issue #9957)

### PR DESCRIPTION
**Pull request by RaitheOfDureya**
[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
This PR fixes part of issue #9957

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
I have identified the following unused strings in the `generic.json` file. 

At the moment I only removed the strings from the `locales/en` folder to make it easier to revert if necessary. Once the strings are reviewed, I can delete them from other languages.

- titleIndex
- habiticaLink
- titleTasks
- titleBackgrounds
- titleAvatar
- titleStats
- titleAchievs
- titleProfile
- titleInbox
- titleTavern
- titleParty
- titleHeroes
- titlePatrons
- titleGuilds
- titleChallenges
- titleDrops
- titleQuests
- titlePets
- titleMounts
- titleEquipment
- titleSettings
- expandToolbar
- collapseToolbar
- showFormattingHelp
- hideFormattingHelp
- youType
- youSee
- italics
- strikethrough
- emojiExample
- markdownLinkEx
- unorderedListHTML
- unorderedListMarkdown
- groupPlansTitle
- newGroupTitle
- subscriberItem
- loginSuccess
- youSure
- buyMoreGems
- gemButton
- moreInfo
- moreInfoChallengesURL
- moreInfoTagsURL
- showMoreMore
- showMoreLess
- gemsWhatFor
- memberSince
- lastLoggedIn
- notPorted
- buyThis
- noReachServer
- errorUpCase
- serverUnreach
- requestError
- seeConsole
- endTour
- askQuestion
- HabiticaWiki
- HabiticaWikiFrontPage
- contributeToHRPG
- January
- February
- March
- April
- May
- June
- July
- August
- September
- October
- November
- December
- checkOutProgress
- cardReceivedFrom
- levelUpShare
- questUnlockShare
- hatchPetShare
- raisePetShare
- achievementShare
- enableDesktopNotifications
- online
- onlineCount
- habiticaOfficial
- artDesign
- booksWriting
- comicsHobbies
- diyCrafts
- education
- foodCooking
- healthFitness
- music
- relationship
- scienceTech
- budgeting
- habiticaHasUpdated

I also removed a duplicated string `"creativity": "Creativity"`.

The following dynamically generated strings were found during the PR review:

- greetingCardExplanation
- greetingCardAchievementTitle
- greetingCardAchievementText
- thankyouCardExplanation
- thankyouCardAchievementTitle
- thankyouCardAchievementText
- birthdayCardExplanation
- birthdayCardAchievementTitle
- birthdayCardAchievementText
- congratsCardExplanation
- congratsCardAchievementTitle
- congratsCardAchievementText
- getwellCardAchievementTitle
- getwellCardAchievementText
- goodluckCardExplanation
- goodluckCardAchievementTitle
- goodluckCardAchievementText

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 6544e17f-237b-4915-ae7e-47744c0dc1bd

### CODE REVIEW

**Comment by paglias** [comment]
these are looking good!

**Comment by RaitheOfDureya** [comment]
Done, @paglias

**Comment by paglias** [comment]
I think the following are used:

```
greetingCardExplanation
greetingCardAchievementTitle
greetingCardAchievementText
thankyouCardExplanation
thankyouCardAchievementTitle
thankyouCardAchievementText
birthdayCardExplanation
birthdayCardAchievementTitle
birthdayCardAchievementText
congratsCardExplanation
congratsCardAchievementTitle
congratsCardAchievementText
getwellCardAchievementTitle
getwellCardAchievementText
goodluckCardExplanation
goodluckCardAchievementTitle
goodluckCardAchievementText
```

see 
Schermata 2020-10-05 alle 16 43 00
Schermata 2020-10-05 alle 16 43 26

**Comment by RaitheOfDureya** [comment]
Thanks for the review, @paglias 
Now it should be everything alright :)

**Pull request merged**
