### PR TITLE
Share avatar

### PR DESCRIPTION
**Pull request by lefnire**
Adds ability to share your avatar on social networks. A "Share" button appears top-right when hovering over your avatar:

screen shot 2014-11-12 at 2 29 51 pm

It includes a download link which simply downloads an image of your avatar (rather, redirects to the s3 link from which you can download). When you click share on the social networks, the link will redirect to /static/front#?memberId=XXX which gives you a modal of the avatar:

modal

There are a few missing bits, but most is there. TODO:
- [ ] When the user is logged into Addthis, it seems the [selected services](https://github.com/HabitRPG/habitrpg/compare/share-avatar?expand=1#diff-b15b92fe8a80bfe66aec828f1d8f71ceR50) aren't respected. This includes the Download link. IE, if they're logged in they see the Addthis's default batch of social links, minus the download link
- [ ] Some pieces on /static/front#?memberId=XXX are missing - pet count, memberSince, etc. This because those missing bits are in controllers/services from the main app which are too clunky to include into the static.js app. I've tried hand-selecting a few, but they're all so interdependent it causes issues. We can forgo those pieces for now.

---

Technical details: the download link requires S3 credentials, as well as [pageres](https://github.com/sindresorhus/pageres) which depends on [PhantomJS](http://phantomjs.org/). To get that working, you'll need to install PhantomJS locally. To get it working on Heroku, follow [these instructions](https://github.com/brenden/node-webshot/issues/25#issuecomment-23019665) (take note of the [follow-up comment](https://github.com/brenden/node-webshot/issues/25#issuecomment-52624426))

### CODE REVIEW

**Comment by deilann** [comment]
Total amount of XP needed to level up is also missing, at least from the
beta code I saw.

**Comment by paglias** [comment]
From mobile. Just a quick note abiut downloading: html5 allow for direct
download using a link with a 'download' attribute like <a href="link"
download></a>
Il 12/nov/2014 22:42 "Tyler Renelle" notifications@github.com ha scritto:

**Comment by lefnire** [comment]
@paglias sorry, I'm a bit confused on that comment. could you elaborate? (can wait till you're at a keyboard if you want)

**Comment by paglias** [comment]
Sorry it was written a bit fast. If you add the 'download' attribute to the
link it will download the avatar directly without being redirected to s3,
you'll get it download without changing page
Il 12/nov/2014 22:46 "Tyler Renelle" notifications@github.com ha scritto:

**Comment by paglias** [comment]
See http://demo.hongkiat.com/html5-download-attribute/ for an example
Il 12/nov/2014 22:48 "Matteo Pagliazzi" matteopagliazzi@gmail.com ha
scritto:

**Pull request merged**
