### PR TITLE
re #5182 replaced leave button to cancel button ...

### PR DESCRIPTION
**Pull request by jtsaich**
... for guild leader to cancel editing guild info box

### CODE REVIEW

**Comment by crookedneighbor** [comment]
## Group Leader Cannot Leave Group

@Alys Do you have any thoughts about preventing a group leader from leaving their own group without first assigning leadership to someone else?

Here are some thoughts I have:
- It's nice to require a group leader to pass leadership on instead of just bailing
- If a person creates a one person party, and then later finds another party they would like to join, they would be unable to leave their one person party because there is no other user they could make the leader.
- Similar thing for a guild, if you're the last one in a guild, you're stuck with the guild. 
- If this is something we're going to block on the ui, we should also block it on the api level

## Cancel Editing Button

Currently, when you click the cancel button the changes are not saved, but they are still displayed on the page. You have to refresh the page before your changes are reverted. 

If you want to have a cancel button, upon clicking the edit button, you're going to want to store the group in it's current state in a variable so that you can revert the changes if the user clicks cancel.

**Comment by Alys** [comment]
I think the current system is fine. The leader can choose a new leader if
they want to, but if they don't the most senior member becomes leader. I
don't see any reason to force a choice.

The current system has the flaw that the most senior member might be
inactive, but if we force a leader to choose a new one,  they could pick an
inactive person at random or by mistake. (And we should create a system to
deal with an inactive leader in general, which would also remove the
disadvantage of the automatic choice method.)

**Comment by crookedneighbor** [comment]
@tsai0606 I think the consensus is to remove the changes to the leave button and make the requested adjustments to the edit code. 

Though, now that I think about it, there's a second leave button at the bottom of the group page, so it wouldn't permanently prevent the leader from leaving the group. However, I think it would be confusing to remove the leave button from the top section.

**Comment by crookedneighbor** [comment]
@tsai0606 We haven't heard from you since you opened the PR. I'm going to close this now, but if you'd like to continue working on it, please do and re-open it.

**Pull request closed without merging**
