### PR TITLE
Convert API tests to normal JS

### PR DESCRIPTION
**Pull request by aughr**
In the process, I also ran into some other issues that I've addressed in the attached commits:
- The tests were loading static.js after app.js, so the habitrpg module definition in static.js was clobbering the main one. In other words, the tests weren't testing what they should have been testing. I changed the static.js module name to `habitrpgStatic` and updated the jade template to match.
- It looks like the symptom has been fixed on master, but when I started the tests weren't passing because some service code was looking for an object hanging off `$rootScope`. Finding dependencies is what dependency injection is for, so I added a new service wrapping window.habitrpgShared for use in non-view code.
- At least on my machine (maybe it's slower?), the `sleep 3` in `run_tests.sh` wasn't enough for selenium to start. I added a loop to wait (for up to 30 seconds) for it to answer on its port.

Finally, I translated the API tests into normal JS. There were a number of commented-out tests saying that they should be either rewritten to work or deleted, which I didn't convert under the assumption that they can be retrieved from git history if needed.

Any concerns? Also, what would be the appropriate forum to propose and discuss refactoring the test suite? I don't want to put too much time in only to find out I was working under the wrong assumptions.

### CODE REVIEW

**Comment by colegleason** [comment]
:+1: I'll base my new tests off this PR.

**Comment by lefnire** [comment]
Woo! A whopper, rock on! Ok, first thing - we have merge conflicts. Likely tests I've added since this PR. Now I'm aware, I'll avoid adding anything to api.mocha until I hear back. I'm gonna start poking at the rest and get back to you when I can.

Religion convo: Any primary reason for the CS => JS shift? I can be swayed if the others prefer it, I just rather like CS for JSON-esque files (so much more condensed!). 

@djuretic any input on this PR?

**Comment by lefnire** [comment]
(man I wish Github had a "exclude whitespace from diff" option)

**Comment by colegleason** [comment]
@aughr: Can you also rebase off develop and edit run_tests.sh so that these are run by Travis?

@lefnire: I personally dislike CS just because I think JS is more readable, even if it is more wordy. I had a hell of a time trying to figure out how to pass anonymous function as arguments in CS. And I had a stupid bug where I was setting something to false, not realizing the last line in a function returned false. Turns out _.each breaks early if you return false -- go figure. 

Also, I generally prefer brace-style blocks over indentation-style since it is annoying to coordinate between team members.

@lefnire: You could do this locally:

```
git checkout -b aughr-andrew/consolidate_tests develop
git pull https://github.com/aughr/habitrpg.git andrew/consolidate_tests
git diff -w develop aughr-andrew/consolidate
```

**Comment by colegleason** [comment]
@lefnire: Github does actually! Add `?w=1` after the URL: https://github.com/HabitRPG/habitrpg/pull/2396/files?w=1

**Comment by aughr** [comment]
@lefnire I do personally prefer JS to CS, but I was basing this work on the README in `test/` that said the tests should be converted away from CS :smile:

@colegleason Rebased off develop and it's green!

**Comment by djuretic** [comment]
Great work @aughr! @lefnire I don't have any additional input on this PR.

**Comment by lefnire** [comment]
@aughr thanks a million! what's your UUID for contrib.lvl++?

**Comment by aughr** [comment]
Thanks! My UUID is:

b2efb993-b746-4804-b205-ce9ea029af4f

**Comment by lefnire** [comment]
@aughr √ (lvl+=2, heavy commit). I thought I recognized that name.. the seed fix!

**Pull request merged**
