### PR TITLE
improve(express): update express to version 4

### PR DESCRIPTION
**Pull request by denis-sokolov**
Express 4 has a few [backwards compatibility breakages](https://github.com/visionmedia/express/wiki/New-features-in-4.x).
1. Express does not depend on Connect anymore, all bundled middlewares are not independent.
2. Express router now works slightly differently.

Merge with care, I haven't tested it too thoroughly.
I've tested a few static pages, logged in, completed some tasks, changed my profile settings, all seemed to work. But it's a big change, so beware.

### CODE REVIEW

**Comment by lefnire** [comment]
Cool PR, glad you took a stab at it. I was groaning looking at the changes with 4.x. Right now we're pinned at 3.5.x, when I get a moment to sit down with this & test what thins can be impacted, I'll hit it. I upped your contrib.lvl in any case

**Comment by Alys** [comment]
This looks highly desirable but it's been allowed to get very old. :(  @lefnire @paglias Can we still resurrect this?

**Comment by denis-sokolov** [comment]
I might try to update it if there's any assurance it will not be lost again. :)

**Comment by Alys** [comment]
Let's see if we can get that assurance.

@lefnire or @paglias, can you comment please? Is this still wanted?

**Comment by paglias** [comment]
@denis-sokolov if you update the PR the changes will be similar? 

I think at a certain point we'll have to upgrade anyway so this would be very welcomed. 

When you created it the first time it all worked correctly? If yes and you have the time, it would be great and I'll review it in a few days.

@Alys we should put it on beta when the testing for the skill rebalancing has finished

**Comment by lefnire** [comment]
:+1: hear hear

**Comment by crookedneighbor** [comment]
@denis-sokolov If you want to rebase this PR and re-open the request, I'll look at it within a couple of days.

**Pull request closed without merging**
