### PR TITLE
check for duplicate task ID when adding a new task (Fixes #4838)

### LINKED ISSUE #4838: Task creation does not check for duplicate IDs
When creating a task with the API, you can provide an id for the task. When this id already exists, a new task with the same id is created. Both tasks are now displayed in the web interface, but all interactions happen on one of the tasks (I think it's always the oldest). Resolving the issue is only possible by deleting one of the tasks (again, this may not be the one the user wanted to interact with). As the only way this could happen is with custom extensions, I'm not sure what the best fix would be. Rejecting new tasks with existing ids could be undesirable if the extension wants to interact with the task at a later time. Assigning a new random uuid could be problematic for the same reason.

### PR DESCRIPTION
**Pull request by chimericdream**
@Alys @vIiRuS I don't have a way to test the remote API (having never dealt with it or even looked at it much), but I _think_ this should fix the issue of duplicate IDs when adding a task.

### CODE REVIEW

**Comment by chimericdream** [comment]
Fixes #4838

**Comment by Alys** [comment]
@chimericdream To test the API locally, edit config.json to change BASE_URL to `"BASE_URL":"http://localhost:3000",` cancel and rerun `npm start`, then go to http://localhost:3000/static/api

**Comment by chimericdream** [comment]
@Alys Thanks. That was nice and simple. I tested the API call, and it now returns a 409 status code and a message that a task already exists with the given ID.

**Comment by negue** [comment]
Great! Once this is merged then the website / mobile app[s] would need to react to it, since it would also use this api call.

**Comment by paglias** [comment]
@negue the mobile app & the site aren't already supposed to respond to error messages like this?

**Comment by negue** [comment]
@paglias Can't find any line with a re-generating task uuid

**Comment by paglias** [comment]
I mean, if the server returns an error the app doesn't reply with the text
the server sent? Also since it's in habitrpg-shared probably it's executed
on the client too
Il 16/mar/2015 17:09 "negue" notifications@github.com ha scritto:

**Comment by crookedneighbor** [comment]
@chimericdream Anxious to get this merged in. Might solve some of our duplicate todo issues. 

@Alys I'm guessing this is another PR that would need to be announced before making a change?

**Comment by crookedneighbor** [comment]
@chimericdream meant to add that it'll need to be brought up to date with the current version of develop. If you can't do that, I will do it when it does get merged in.

Also, I'm going to change the example config.json to use localhost:3000 as the base url. It's ridiculous that it doesn't. Unless I'm missing something. Am I?

**Comment by Alys** [comment]
I always have localhost:3000 in my config and I have not noticed it causing any problems. However I cannot say for sure that it should be like that.

I think this can be merged without announcement. Duplicate task IDs are an error condition.

**Comment by crookedneighbor** [comment]
@Alys as it stands, the `BASE_URL` gets evaluated to `localhost:80` on my system. The only reason there would be a problem is if someplace used both `BASE_URL` and `PORT` to create the full URL, but a quick `git grep` confirmed that there is no where in the codebase that does that, so I just changed the example config and merged it in.

**Comment by chimericdream** [comment]
Sorry for my delay on this. The past few weeks have been pretty crazy. I will take a look in the next day or two, but I have not been able to get the tests to run on any of my computers (tried personal/work desktops, laptop, and Vagrant VM). I'll gladly write tests for it, but will not be able to verify that they pass, aside from the Travis CI build. :smile:

**Comment by crookedneighbor** [comment]
Merged with https://github.com/HabitRPG/habitrpg/commit/ca72b9a9e1e86262fcab15c7d52ae902953dc7b8

Notated toward your next contributor tier.

**Pull request closed without merging**
