### PR TITLE
Displays username and UUID for invitation errors partial fix for https://github.com/HabitRPG/habitica/issues/8735

### PR DESCRIPTION
**Pull request by JoshSears**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Partial fix for https://github.com/HabitRPG/habitica/issues/8735

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
groups.json changed error format to display user name and UUID of invitee for userAlreadyInvitedToGroup, userAlreadyPendingInvitation, userAlreadyInGroup and userAlreadyInAParty (lines 199,  201 - 203).  groups.js altered to pass the uuid and name for those particular errors, found in _inviteByUUID (starting line 871).

Does not address only showing only one error at a time.

[//]: # (Put User ID in here - found in Settings -> API)

----
UUID: 348b9f3a-83ef-4865-b4d1-8f64870c9734

### CODE REVIEW

**Comment by JoshSears** [comment]
@Alys Not sure why the travis check failed.  From the outputs, it appears that the test expected errors instead of the error messages that I fixed.

**Comment by TheHollidayInn** [comment]
It looks to me like you have changed the translation strings, but did not change them in the tests. You will need to update the tests for this route as well. Thanks!

**Comment by JoshSears** [comment]
Will do!

**Comment by JoshSears** [comment]
Still working on this.  Life had to take precedence first.

**Comment by JoshSears** [comment]
@TheHollidayInn Still having an issue with providing a name of the user for the tester to display (hence the error).  I am trying to checkout where generateUUID is imported from.  Any ideas?

**Comment by SabreCat** [comment]
@Dagrik `generateUUID` is simply the `v4` function from the `uuid` module. See e.g. https://github.com/HabitRPG/habitica/blob/develop/test/api/v3/integration/groups/GET-groups_id.test.js#L6

**Comment by JoshSears** [comment]
Sorry, I mis-typed.  I meant generateUser.  Trying to get a name to pass.

**Comment by SabreCat** [comment]
Oh, that makes sense! It's in a helpers file under the tests. See e.g. https://github.com/HabitRPG/habitica/blob/51ffe2c8c2cfc0ae6437bcfc151010759ee365f8/test/common/ops/clearPMs.test.js#L3 for an import of it. The actual function is very simple, at https://github.com/HabitRPG/habitica/blob/develop/test/helpers/common.helper.js#L13 -- the Mongo schema does most of the work.

**Pull request closed without merging**
