### PR TITLE
chore(static pages): cleanup static page route copy&paste

### PR DESCRIPTION
**Pull request by denis-sokolov**
Copy & paste always carries a risk to introduce a bug with a slight difference.
A loop prevents that from happening.
Also, [code climate stat](https://codeclimate.com/github/HabitRPG/habitrpg/src/routes/pages.js) improvement.

### CODE REVIEW

**Comment by deilann** [comment]
https://github.com/HabitRPG/habitrpg/pull/3554 ?

**Comment by denis-sokolov** [comment]
Whbrlargh.

**Comment by deilann** [comment]
Does zat'un look good to you? It looks good to me, but I've had a headache for the past 4 days or so, and so have not been trusting my judgement. If so, I'll merge it.

**Comment by denis-sokolov** [comment]
Looks good to me.

**Comment by deilann** [comment]
ty!

**Comment by deilann** [comment]
If you really want to clean up something, I've been meaning to refactor
stats.jade, so I can actually fix it to comply with the new level cap
changes. :P It makes my head hurt.

**Comment by denis-sokolov** [comment]
Oh, that's hard to improve without knowing the goals, sorry. :)

**Comment by deilann** [comment]
Oh, that was a joke, but if you look at the page, I think you'll see the
issue. It stands on its own. I'll get to it eventually, though!

**Comment by denis-sokolov** [comment]
Sorry, I don't get it. What's the issue?

**Comment by deilann** [comment]
Each of the stats is a heavily repeated line that scrolls something like
two and a half times my screen.

But like I said, it was mostly a joke bringing it up -- work that I should
have gotten to, but haven't yet. Please do not actually feel obliged to
touch it.

**Pull request closed without merging**
