### PR TITLE
add new feature descriptions to Social > Group Plans page

### PR DESCRIPTION
**Pull request by Alys**
### Changes

This adjusts the Social > Group Plans page to include two new points for the new Group Plans features (free subscriptions and a Jackalope mount, seen at the bottom of the screenshot below). It also removes Windows line breaks at the end of one of the files.

image

### CODE REVIEW

**Comment by paglias** [comment]
Can we also show the price?

**Comment by Alys** [comment]
@lemoness would you like to give me words for the price too?

**Comment by lemoness** [comment]
It should be the same as what displays later: 

$9 every month + $3 a month for every additional group member

**Comment by Alys** [comment]
I've added the price under the button:

image

**Pull request merged**
