### PR TITLE
Additional Profile Options

### PR DESCRIPTION
**Pull request by deilann**
Adds a contact field to profiles, encouraging users to share info on how others can reach them. Adds fields for external accounts, with the option to set them private. Updates the modal to show contact info and any public accounts. Oh, and display names are limited to 20 characters.

### CODE REVIEW

**Comment by lefnire** [comment]
Let's get these on 3 separate pull requests. I want to merge your pet thing immediately, I wanna get the copy updates started so I can chug at it with you. As for profile fields, I'm a bit against it actually since they can achieve the same with markdown lists + links. We used to have a `websites` field which was upkeep (everything hits bugs sometime or another), and we just removed it since they can just use markdown for the same effect

**Comment by deilann** [comment]
The external sites thing was actually partially to allow you (and everyone
else) to see what users are who on what. That way, you could easily track
people between sites. The "contact" field is just markdown, so people can
realize "oh right, people might want to contact me, maybe I should give
them a way"

Lemme get things together so I can PR separately.

**Comment by deilann** [comment]
Gonna take care of this in a bit.

**Comment by paglias** [comment]
@deilann can you use move strings in habitrpg-shared for the next PRs? Thanks

**Pull request closed without merging**
