### PR TITLE
Update front.jade

### PR DESCRIPTION
**Pull request by Rbrinkley**
Increased time for carousel sliding from 4 seconds to 10 seconds. 4 seconds too fast for user to full read all the information, 10 seconds is  not too slow but not too fast.

### CODE REVIEW

**Comment by Rbrinkley** [comment]
fixes https://github.com/HabitRPG/habitrpg/issues/5047

**Comment by Alys** [comment]
The "What people say" section looks good now but "Players use HabitRPG to manage" is still very fast. I think they might be controlled separately. Would you like to look into that as well?

**Comment by Rbrinkley** [comment]
Sure! I'd love too. I would have to look more into that tomorrow. The bed is calling me.

**Comment by Rbrinkley** [comment]
Done! https://github.com/HabitRPG/habitrpg/pull/5049

**Comment by Alys** [comment]
Thank you again! This counts as partial credit towards a future tier.

**Pull request merged**
