### PR TITLE
Added hidable markdown help table and added `formatting-help`  to private messages

### PR DESCRIPTION
**Pull request by hairlessbear**
This PR uses `formatting-help.jade` to add a hidden-by-default markdown help table.

selection_012
selection_013

I also added `formatting-help` to private messages, because why not?

selection_015
selection_014

### CODE REVIEW

**Comment by hairlessbear** [comment]
I tried to include only the markdown syntax that users were most likely to find helpful. As you can see in the code, there's a commented out row that has the image inclusion syntax. I opted to remove it because I don't think many users use it, but I kept it in the PR just in case others disagree.

**Comment by crookedneighbor** [comment]
Looking really good. Made just a few tweaks: https://github.com/HabitRPG/habitrpg/commit/681668f131d0e93a4caae92c9737d3bbfef9fb11

Here's how it looks now:

screen shot 2015-05-24 at 9 23 45 am

Anyone have other tweaks they want in before I merge?

**Comment by hairlessbear** [comment]
If we aren't including the image syntax, we should remove its commented out row from the table and remove its entries from `generic.json`.

**Comment by deilann** [comment]
I use the image code quite a bit. I'm not entirely sure why we're not
adding it _because_ it's not used a lot. I'd imagine that would be a reason
to add it: users aren't aware it's available.

**Comment by crookedneighbor** [comment]
Image example added in. Notated toward your next contributor tier.

**Comment by hairlessbear** [comment]
@crookedneighbor Did you use the image example that I wrote, or modify it? I'm asking because the one I wrote displayed the image at full-size instead of resizing it (like what happens in chat), and it is far too large for the table.

**Comment by crookedneighbor** [comment]
I modified it and used a small image.

**Comment by hairlessbear** [comment]
Figured as much, just wanted to check. Thanks for the response.

**Pull request merged**
