### PR TITLE
Api v3 challenge fixes

### LINKED ISSUE #7249: [API v3] No info about participants in challenges
General Info
- UUID: ffa26f90-f4cf-40b5-8b3b-aca988ab8ed2
- Browser: FF 46.0.1
- OS: win10
### Description

Challenges show the number of participants, but the details don't show the How's Everyone Doing? section. When I try to end a challenge and declare a winner, the list of participants is empty

### PR DESCRIPTION
**Pull request by TheHollidayInn**
#7249
#7247
#7248
#7272
#7272
#7267
#7253
### Changes

---

UUID:

### CODE REVIEW

**Comment by crookedneighbor** [comment]
Deleting a task while editing a previously saved challenge still doesn't work. Is that intended?

No group is still selected when creating a challenge.

**Comment by TheHollidayInn** [comment]
**Deleting a task while editing a previously saved challenge still doesn't work. Is that intended?**
I now see there is a difference between an already saved challenge vs already saved challenge task. I am pushing an update to fix that as well. 

**No group is still selected when creating a challenge.**
This is working for me. What are you filters set to when creating a new challenge?

**Comment by paglias** [comment]
Is this fixed now?

**Comment by TheHollidayInn** [comment]
Deleting the task should be. I'm not sure what is happening to Blade when trying to create a challenge.

**Comment by paglias** [comment]
schermata 2016-05-16 alle 21 48 18

@TheHollidayInn Confirmed that `No group is still selected when creating a challenge.`. i've just tested it locally. I'll merge the PR anyway, the fix for it can come later

**Comment by TheHollidayInn** [comment]
Can you screenshot our challenge filters/or the the whole screen? I'm not getting this issue.

**Comment by crookedneighbor** [comment]
@TheHollidayInn see https://github.com/HabitRPG/habitrpg/issues/7253#issuecomment-219531175

**Pull request merged**
