### PR TITLE
Add "Firefox Chat Extension" to the Settings > API page

### LINKED ISSUE #11042: Add "Firefox Chat Extension" to the Settings > API page
The [User Icon > Settings > API page](https://habitica.com/user/settings/api) contains a link to the Chrome Chat Extension. There should also be a link to the Firefox Chat Extension, which is at https://addons.mozilla.org/en-US/firefox/addon/habitica-chat-client-v2/

Both extensions do the same thing, the only difference being the browser they run on. Because of this, I think it would be most helpful if the same bullet-point entry was used for both extensions - that should make it obvious that you're not missing out on anything if you install only one of them. The bullet point line could read "[Chrome Chat Extension](https://chrome.google.com/webstore/detail/habitrpg-chat-client/hidkdfgonpoaiannijofifhjidbnilbb) and [Firefox Chat Extension](https://addons.mozilla.org/en-US/firefox/addon/habitica-chat-client-v2/)" and the paragraph under it could be changed to this:

"The Chat Extension for Habitica adds an intuitive chat box to all of habitica.com. It allows users to chat in the Tavern, their party, and any guilds they are in."

I'll leave this issue open as suggestion-discussion for a few days and then if there's no objections or changes to this approach, I'll change it help wanted. I'll mark it as good first issue since it will be ideal for a new contributor. EDIT: This is on hold while some changes are being made to the extension.

### PR DESCRIPTION
**Pull request by Markkop**
Fixes #11042

### Changes
I've added Firefox Chat Extension's link, removed Chrome Chat Extension's description and added a description about the Chat Extension

**Before:**
before

**After:**
after

While working on it, I've also discovered a **bug** with **Pug** and/or **Vue** that whenever using the **HTML tag with attribute** such as `li(v-html="$t('otherExtensions')")`, its children wouldn't be displayed, as you can notice how the text description of "**Other Extensions**" doesn't appear.

The **fix** is not putting the text as child by fixing its **indentation**. 

This is the final result:

final

PS: I've mistakenly changed `settings.json` indentation. Is there any problem?

----
UUID: 40387571-91ee-489e-960f-278bf8fd503a

### CODE REVIEW

**Comment by Markkop** [comment]
Here's a write-up of how I've done this fix. I think it's worth to share <3
https://dev.to/heymarkkop/my-first-open-source-contribution-21dh

**Comment by paglias** [comment]
Thanks @Markkop for the PR and the article! I'll review it soon but right now we're having some issues getting the Firefox extension available, see https://github.com/HabitRPG/habitica-chat-extension/issues/49

**Comment by Markkop** [comment]
Cool, I shall look into it. It seems a great opportunity to learn and practice Javascript

**Comment by paglias** [comment]
@Markkop thanks! let me know if you need any help

**Comment by Markkop** [comment]
Fixed indention conflict

**Comment by paglias** [comment]
@Markkop looks like the changes to settings.json disappeared?

**Comment by paglias** [comment]
Fixed some conflicts generated by changes in the client side code

**Comment by Markkop** [comment]
> @Markkop looks like the changes to settings.json disappeared?

I believe I've fixed the indention change with [this](https://github.com/HabitRPG/habitica/pull/11375/commits/5b7b87e524f15839bdb89caf481d2b7adb8babc4) commit, but I didn't get this last commit of yours. It shows lots of file being changed, am I seeing it right?

**Comment by paglias** [comment]
The last commit I did was to fix the conflicts that were generated due to some unrelated changes we did in `develop`. But I gave this a look before doing that commit and the settings.json changes were missing

**Comment by Markkop** [comment]
Oh, I see. So now what's this PR situation?

**Comment by paglias** [comment]
I haven't had time to publish the other PR in the extension repo so it'll
have to wait a bit more. But the changes to settings.json are definitely
missing so if you could try to add them again it would be great!

Make sure to pull the updated branch code before making any changes

Il Dom 20 Ott 2019, 17:11 Marcelo <notifications@github.com> ha scritto:

**Comment by paglias** [comment]
Extension approved, finally :) https://addons.mozilla.org/en-US/firefox/addon/habitica-chat-client-2/ I'm marking the PR as ready for release when possible

**Comment by paglias** [comment]
Actually @Markkop looks like the settings.json file is still missing from the pr. You should pull the most recent version of this PR from github, re-apply the change to settings.json and push again

**Comment by Markkop** [comment]
@paglias Just found what happened. I've submitted the correct settings.json, but when trying to fix an indentation problem I've actually reverted it back to the original. 
Now I've submitted the settings.json file with the corrects change plus some changes that happened by git pulling. (by the way, sorry about the double commit)

**Comment by paglias** [comment]
Sorry for the delay @Markkop ! This has been merged and will go live next week, notated towards your 4th tier

**Pull request merged**
