### PR TITLE
Message in a Bottle/Moonstone Chain quest art

### LINKED ISSUE #6555: Collection Quest Art: Message in a Bottle and Moonstone Chain
We have two new pieces of collection quest art to be implemented!

Message in a Bottle, by mako413:

message_in_a_bottle_3x_zpspxgfati2

Moonstone Chain, by eevachu:

themoonstonechain_300p_by_eevachu-d9o91kw

### PR DESCRIPTION
**Pull request by keysmashes**
I hope I did it right, it's not immediately obvious what you need to do apart from drop the images in `common/img/sprites/spritesmith/quests/` (is doing `gulp sprites:compile` right?)

Resolves #6555.

### CODE REVIEW

**Comment by Alys** [comment]
You can also run `npm run sprites`, which currently does `gulp sprites:compile` but is probably a safer method in case we ever change how the sprites are compiled.

Could you please show us screenshots of the images in the quest modals?

**Comment by keysmashes** [comment]
Is it worth making a new PR with an up-to-date branch, given the conflicts, or is there a magic Git command to fix everything?

image

image

**Comment by crookedneighbor** [comment]
Something like this should do it

``` bash
git fetch upstream # assumes you have the remote branch set up as upstream
git rebase upstream/develop # You'll get merge conflicts here
npm run sprites
git add -A
git rebase --continue
git push --force # overrides your commits on your remote branch with the rebased ones
```

**Comment by keysmashes** [comment]
That did the trick, thanks!

**Comment by keysmashes** [comment]
(Fixed merge conflicts again)

**Comment by crookedneighbor** [comment]
Sorry about the delay on this. Just want to double check it on a local install before merging.

**Comment by crookedneighbor** [comment]
Merged in with https://github.com/HabitRPG/habitrpg/commit/fae0bbc8f6e722db42737d9f5d92b3367009dcfc

This will count towards a contributor tier! What's your User ID? You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api). Be sure to only copy the User ID and _not_ your API Token.

**Comment by keysmashes** [comment]
`0e1d15f7-f36b-4f15-a9e1-0c31b732dac9`

Thanks!

**Comment by crookedneighbor** [comment]
Notated toward your next tier.

**Pull request closed without merging**
