### PR TITLE
Optimized images

### PR DESCRIPTION
**Pull request by fmarier**
Lossless-ly optimize all images contained in this repo using a [custom script](https://gitorious.org/fmarier-misc-scripts/user-scripts/source/optimize_images) which makes use of these open source tools:
- [Pngcrush](http://pmt.sourceforge.net/pngcrush/)
- [OptiPNG](http://optipng.sourceforge.net/)
- [AdvanceCOMP](http://advancemame.sourceforge.net/comp-readme.html)
- [Gifsicle](http://www.lcdf.org/gifsicle/)
- [Jpegoptim](http://www.kokkonen.net/tjko/projects.html)

About a 65% reduction in size overall.

### CODE REVIEW

**Comment by lefnire** [comment]
not all of these are still in use, but still worthwhile for those which are. Preferred we have a step in our grunt / gulp pipelines, but another day. Thanks, uuid?

**Comment by fmarier** [comment]
@lefnire My User ID is 799cd4c3-41d4-4ac9-8cfb-81c4f7155cb1

**Comment by lefnire** [comment]
√. Sorry again friend, you must be thinking "jesus dude..."

**Comment by fmarier** [comment]
Better late than never ;) Thanks!

**Pull request merged**
