### PR TITLE
Task page : task filters v2

### LINKED ISSUE #9582: sorting Dailies in "All" filter causes "Due" filter to be applied
As reported in the Report a Bug guild by Il Mago Azzurro (c073342f-4a65-4a13-9ffd-9e7fa5410d6b):

"Website, trying to reorder my dailies with the "All" filter active results in having the "Due" filter (the default one) activating everytime the page sync after I move something, I had to move only 2 things, but it was really longer than it should be..."

I've confirmed that in my account, although it didn't happen every time (just most of the time).

The correct behaviour is that when you are sorting Dailies using any of the All/Due/NotDue filters, the filter should never be changed automatically.

### PR DESCRIPTION
**Pull request by kartikadur**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #9582, #9898

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

All changes made to reduce response / processing times, improve data reactivity, and reduce data state ambiguity. I have run tests and checked things multiple time, but I don't expect them to be exhaustive. 

#### Existing files:
TaskColumn (column.vue):
+ store.getters access where possible instead of store.state
+ can only access its own task type instead of all tasks
  - __added in v2__ differentiates between user and group-plan tasks based on isUser prop passed to component
+ task Labels and Filters assigned to own file (client/libs/store/helpers/filterTasks.js)
  - task label, filter labels, and active filter function assigned when component is created
+ functions adjusted where needed to incorporate above changes
+ unit tests for functions where possible
+ __added in v2__ 'due' or 'all' filter is only set when the component is first created and not on subsequent reloads

Task-Getters (store/getters/tasks.js)
+ returns all tasks of requested type
+ returns all tasks of requested type filtered by categories (all, due, notDue for dailies, etc.)
+ unit tests

User-Getters (store/getters/user.js)
+ return user buffs, preferences, and task order by task type

#### New files:
Filter-Tasks (client/libs/store/helpers/filterTasks.js)
+ contains all task filter data and return task label, filter labels, and active filter
+ unit tests

Order-Tasks (client/libs/store/helpers/orderTasks.js)
+ assigns task order by single task type for efficiency
+ unit tests

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID:

### CODE REVIEW

**Comment by kartikadur** [comment]
I'll deal with the merge conflicts tomorrow :disappointed:

**Comment by kartikadur** [comment]
The files column.js and tasks.js seem to be simple merges, but the column.vue merge seems somehow convoluted. I tried merging / rebasing/ diffing but in each case it seems to either delete or overwrite my code with older repo code. Since I've never dealt with something like this before any help is appreciated. I figure this is a nice learning opportunity for me.

**Comment by paglias** [comment]
If merging is too difficult you can get an up to date develop branch, then create a new one and just copy your changes. Then push that branch, close this PR and open a new one (or reset this branch to develop and re-apply your changes, then to push you'll have to use --force)

**Comment by kartikadur** [comment]
yeah, that actually sounds easier to do. thanks @paglias. I'll have the new PR up over the weekend.

**Pull request closed without merging**
