### PR TITLE
Static Header & Popups

### PR DESCRIPTION
**Pull request by StanLindsey**
Header fixed to top of browser, connection display also fixed. As per this issue; 
https://github.com/lefnire/habitrpg/issues/100#issuecomment-12408991
https://trello.com/c/mrbELa6J

Wrap div now relative, top 130px. I'm not 100% if the relative 130px is the best way to do it, it works fine on my screen at various sizes but I dont know if that changes on a mobile browser. 

It also moves all popups to the left, as per this issue;
https://github.com/lefnire/habitrpg/issues/206

Note: I've not been able to test directly as I'm installing an SSD into my primary machine & my linux laptop hasn't got this set up. I did test in Chromes developer tools though. I just wanted to get some code done in my downtime =P

### CODE REVIEW

**Comment by lefnire** [comment]
cant click into "add new" input boxes for some reason

**Comment by StanLindsey** [comment]
Position:Relative is breaking the input boxes for some reason so I replaced it with a margin-top which fixes that. Again not sure if a hard number is the best way to do it?

**Comment by lefnire** [comment]
sorry to keep giving you the runaround stan, check out [firefox screenshot](http://gyazo.com/4c52c103188c6b56a36b43c8870c242f)

**Comment by StanLindsey** [comment]
And this is why you test code kids instead of uploading pull requests when you're bored at a distant relatives birthday. 

Changed width to 100% and edited bootstrap to move pull-right into the right place.

**Comment by lefnire** [comment]
er, we probly don't want to edit bootstrap - we're going to be clobbering that with each upgrade. I'll see if I can't jump in soon

**Comment by StanLindsey** [comment]
Moved the css to index.styl.

**Comment by lefnire** [comment]
looks great! thanks man!

**Pull request merged**
