### PR TITLE
Allow Un-subscribed Users to Claim Mystery Items

### PR DESCRIPTION
**Pull request by SimplyComplexable**
Resolves: #9228

### Changes

Remove restriction on mystery/special inventory items that prevents
non-subscribed users from seeing the items. Organize the imports on the
page.

One use-case for this is if a user is a subscriber but cancels their subscription,
but forgets to redeem a mystery item prior to cancelling. This would cause the 
user to have an un-redeemable mystery item.

[//]: # (Put User ID in here - found in Settings -> API)

----
UUID:

### CODE REVIEW

**Comment by negue** [comment]
@SimplyComplexable Thanks for your contribution 👍 , could you please pull the latest changes from `develop`?

**Comment by librarianmage** [comment]
@SimplyComplexable It looks like you have a file conflict. Are you having troubles resolving it?

**Comment by SimplyComplexable** [comment]
@MathWhiz I thought this had been resolved by another PR, for some reason. I will merge will develop and update the branch tonight though.

**Comment by Alys** [comment]
@SimplyComplexable How are you going with merging in develop? Do you need any advice about it?

**Comment by librarianmage** [comment]
Hi @SimplyComplexable! How is the merge conflict going?

**Comment by lemoness** [comment]
I've updated the labels to indicate that this PR has been abandoned and needs to be reviewed by our devs.

**Comment by SimplyComplexable** [comment]
Sorry about dropping off the radar. I've resolved the merge conflicts.

**Comment by paglias** [comment]
Thanks @SimplyComplexable if you provide us with your Habitica UUID I'll be happy to award you the contributor tier

**Comment by SimplyComplexable** [comment]
@paglias Thanks! My UUID is 8473521d-6635-4429-8824-6fce54deac02

**Comment by paglias** [comment]
@SimplyComplexable I've awarded your tier!

Note that further tiers require increasing amounts of work from one to the next, so Tier 2 may require a couple of PRs or a larger PR to attain. But keep helping out and we'll express our gratitude accordingly!

**Pull request merged**
