### PR TITLE
Changes animal attribute that A-Z sort is applied to.

### LINKED ISSUE #9135: A-Z Sort should be based on species
When sorting by A-Z in the Stable, the sort is applied to the leading color name rather than then animal name. This means all the Base animals are first, and it is a less useful metric than it should be.

### PR DESCRIPTION
**Pull request by thefridge111**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes https://github.com/HabitRPG/habitica/issues/9135

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
Changes the animal attribute from 'name' to 'eggName' to sort the stable animal list by species name when sorting by A-Z. 

[//]: # (Put User ID in here - found in Settings -> API)

----
UUID: cdeb5254-b2d8-4e5b-ae54-db5270e2e07f

### CODE REVIEW

**Comment by thefridge111** [comment]
I'm not sure where to grab the UUID from. It wasn't clear to me in the directions.

**Comment by deilann** [comment]
Settings > API

It's your user id so we can give you a tier if this is merged.

**Comment by negue** [comment]
LGTM 👍 

@thefridge111 could you post your userid here?

**Comment by negue** [comment]
Just pulled the code and it seems that sorting causes to list all of the animals instead of having them "collapsed", but thats not your fault, cause it is also on production^^

**Comment by thefridge111** [comment]
I added my user id to the original PR message :) thanks for the review!

**Comment by thefridge111** [comment]
Oops.. clicked the wrong comment button...

**Comment by paglias** [comment]
@thefridge111 thanks for this! I'm merging the PR and awarding your contributor tier.

Note that further tiers require increasing amounts of work from one to the next, so Tier 2 may require a couple of PRs or a larger PR to attain. But keep helping out and we'll express our gratitude accordingly!

**Pull request merged**
