### PR TITLE
change behaviour of chain quests (scrolls to owner only) - fixes #2715

### LINKED ISSUE #2715: Exponential Quest Reward Scrolls
So... as far as I can tell, if the second scroll is a reward of the first, everyone's going to get it. So a party of 7 finishes Vice pt 1. They get 7 scrolls of Vice pt 2. After that, they have 49 scrolls of Vice pt. 3.

And then another member hits level 30...

---

_edit by Alys:_

This issue applies to these four quest lines (which contain three quests each; the first only is linked to below):
- [Vice](http://habitica.wikia.com/wiki/Free_Yourself_of_the_Dragon's_Influence) - `vice1`, `vice2`, `vice3`
- [Attack of the Mundane](http://habitica.wikia.com/wiki/Dish_Disaster) - `atom1`, etc
- [Recidivate](http://habitica.wikia.com/wiki/The_Moonstone_Chain) - `moonstone1`, etc
- [The Golden Knight](http://habitica.wikia.com/wiki/A_Stern_Talking-To) - `goldenknight1`, etc

The way it is supposed to work is that when the first and second quest finish, the scroll for the next quest is given to only the person who had started the quest. All other quest rewards are given to all participants, as normal.

There's some old code in these two PRs, but they developed significant merge conflicts before they were reviewed, and I never found more time to finish it:
- https://github.com/HabitRPG/habitrpg-shared/pull/303
- https://github.com/HabitRPG/habitrpg/pull/4004

The code might be so outdated now that it could be better to start from scratch.

Here are screenshots of what we had in mind then. They were made a long time ago, so they might not exactly match the current site appearance - if so, the current site appearance should be retained. These are just a guideline for how this might be implemented now. If you want to handle it in some other way, that's fine!

**Quest Scroll when you click on it in Market or Inventory:**

1 - quest scroll when you click on it in market or inventory

**Quest Invitation:**

2 - quest invitation

**In-Progress Quest on Party page:**

3 - in-progress quest on party page

**Quest Completed pop-up:**

4 - quest completed pop-up
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/1398569-exponential-vice?utm_campaign=plugin&utm_content=tracker%2F68393&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F68393&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by Alys**
Requires https://github.com/HabitRPG/habitrpg-shared/pull/303

Allows quests to specify 'itemsForOwner' in addition to or as well as 'items'. Anything listed under itemsForOwner will be given to only the quest owner when the quest is complete. Anything listed under items will be given to all participants.

### CODE REVIEW

**Comment by crookedneighbor** [comment]
@Alys I'm just now getting a chance to look at this. Could you fix the merge conflicts?

**Comment by Alys** [comment]
No point if it's not going to go live soon, there'll just be more merge conflicts later.

@Lemoness, @lefnire, I assume you still don't want this yet?

**Comment by crookedneighbor** [comment]
Okay. I tagged it as wait then.

**Comment by lefnire** [comment]
no objections here

**Comment by Alys** [comment]
Desirable now but not urgent. Things for Alys to do:
- [x] apply changes to all chain quests - see list in https://github.com/HabitRPG/habitrpg-shared/pull/303
- [x] fix merge conflicts
- [ ] repeat tests on all quests
  - [ ] can't buy chain quests except for first in chain
  - [ ] can buy all chain quests after doing them once?? I've forgotten how this is supposed to work. Look into that.
  - [ ] on quest scroll screen:
    - [ ] for non-chain quests, all rewards are listed as for all participants
    - [ ] for chain quests except final one, rewards are split correctly into owner and all participants
  - [ ] on quest invitation pop-up:
    - [ ] for non-chain quests, all rewards are listed as for all participants
    - [ ] for chain quests except final one, rewards are split correctly into owner and all participants
  - [ ] on quest invitation box in party page:
    - [ ] for non-chain quests, all rewards are listed as for all participants
    - [ ] for chain quests except final one, rewards are split correctly into owner and all participants
  - [ ] on quest running box in party page (is this relevant???):
    - [ ] for non-chain quests, all rewards are listed as for all participants
    - [ ] for chain quests except final one, rewards are split correctly into owner and all participants
  - [ ] on quest completion pop-up:
    - [ ] for non-chain quests, all rewards are listed as for all participants
    - [ ] for chain quests except final one, rewards are split correctly into owner and all participants
  - [ ] quest achievement is still given correctly to all participants
- [ ] push changes, check Travis CI build
- [x] tell Lemoness to let me know when a Bailey is ready
- [ ] merge when Lemoness says to

**Comment by Alys** [comment]
closing because https://github.com/HabitRPG/habitrpg-shared/pull/303#issuecomment-70718333 and because it will take me at least a day or two to get through those tests again, probably longer.

**Pull request closed without merging**
