### PR TITLE
Add resync when challenges are updated

### PR DESCRIPTION
**Pull request by TheHollidayInn**
This should fix issue: https://github.com/HabitRPG/habitrpg/issues/1719 . Also, any updated challenge information should now refresh automatically.

### CODE REVIEW

**Comment by Alys** [comment]
This works as described - when the challenge owner saves edits to an existing challenge, this PR causes the challenge page to reload (as if the owner had clicked the browser's refresh button), which means that when the page reappears, the new title is in place, thus fixing https://github.com/HabitRPG/habitrpg/issues/1719

However if the challenge is not near the top of the list, then the owner has to scroll or search to get back to the challenge (not @TheHollidayInn's fault! That's just how the challenge page behaves at the moment). This could be stressful for users who are already feeling a bit lost on the challenge screen. I'm wondering if it's best to not merge this change until we do something to make the viewed challenge be instantly visible after a reload.

Note that at the moment, without this PR, when you edit any part of the challenge except the title, then the edits do appear straight away. With this PR, they still appear straight away, but the refresh happens anyway, and the challenge disappears off-screen. This PR is only useful when the challenge title is updated (which is important but I suspect that the other challenge elements are edited more often than the title).

@lemoness @anitaycheng Which do you think is most desirable - changes to the title appearing instantly because a refresh is forced, or having the challenge remain on-screen after any other edits are made?

**Comment by lemoness** [comment]
Personally, I would find it more frustrating to have my Challenge scroll
away. Is there a straightforward fix to that behavior?

**Comment by Alys** [comment]
There's a proposed, incomplete fix for the need to scroll here: https://github.com/HabitRPG/habitrpg/pull/3319
It looks like it's not straightforward. They're asking for help (I'm not an angular guru either so I'm no use there). I would expect that we will eventually fix the scrolling problem, but it might not be soon. Hopefully someone will give them advice though!

**Comment by Alys** [comment]
And @gisikw has just offered to help with #3319! :smile:  :+1:

**Comment by AnitaYCheng** [comment]
Immediate feedback is important, but losing your place in a very long page is very frustrating! If the current challenge's place can't be kept when the page is refreshed, I would opt for not refreshing it immediately. Of course, if that can be done, then immediate change of the title should be done too.

**Comment by Alys** [comment]
Let's leave this on hold until we have a fix for the scrolling problem.

**Comment by gisikw** [comment]
Working on it now!

**Comment by Alys** [comment]
This has been merged as part of https://github.com/HabitRPG/habitrpg/pull/4934.

Partial credit for tier 5.

**Comment by gisikw** [comment]
Huzzah! Consolidatin' all the things :D

**Pull request closed without merging**
