### PR TITLE
Private Messaging

### PR DESCRIPTION
**Pull request by lefnire**
This PR adds private messaging. 
- Top-right in member modal has "Block" and "Private Message"
- Added Social>Inbox for messages. Headers & tabs have a "new messages" count
- Bottom of inbox has an "opt out" of PMs 

pms

I'm gonna get this into develop so people can start testing it while I work on some other stuff. 

A note on how `user.inbox.messages` is stored. You may notice it's not an Array, but an Object. This is a new method (which I've seen referred to as "RefLists"). Arrays have a ton of issues when stored in Mongoose (see #2301 for the details); particularly when a that array is op-heavy (lots of CRUD being done). Inbox won't likely be "op-heavy", but I want to sort of move away from using arrays in general and will eventually start backtracking in Array->Object cleanup. I'm using Inbox as an experiment to see how easy refLists are to work with by comparison, and see if we hit any snags. If it's a big issue, I'll modify the code to use Arrays. 

Also, any devs who don't like the mechanics / layout of this feature - feel free to gut, I just needed a basic setup to work on Gifting (which requires private-messaging). I'm not married to any of this

### CODE REVIEW

**Comment by lefnire** [comment]
https://github.com/HabitRPG/habitrpg-shared/commit/1bca160eb6bf54c9a662f76804e17c1d0400fdd9

**Comment by Alys** [comment]
FYI: my blog post about this (linked to from the Tavern): [Beta site testing for new messaging and blocking features](http://habitrpg.wikia.com/wiki/User_blog:LadyAlys/Beta_site_testing_for_new_messaging_and_blocking_features)

**Comment by Alys** [comment]
Rachel Ann has said "In the Inbox, when you click on a name, it shows the profile of the last person you were looking at, or at least their name and description. It seems to send the message to the right person though." This will be the same bug as https://github.com/HabitRPG/habitrpg/issues/2010 but I think we should consider it a higher priority now. We'll get more people noticing the bug and it could result in poor take-up of the messaging feature or, worse, messages being sent to the wrong person (e.g, if you accidentally click on the wrong profile but don't notice it because the right profile happened to be the one you previously clicked on). I'm about to add a bounty to that bug.

**Comment by crookedneighbor** [comment]
Found a bug. When clicking on people's names in the tavern, the modal pops up and doesn't always fill in the data if a user modal was open previously. For instance, I click on @lemoness and I see the correct data:
screen shot 2014-11-21 at 11 04 21 am

If I then click on @Alys, I still see @lemoness 's data, but then some of it flashes to @Alys but much of the data remains as @lemoness .
screen shot 2014-11-21 at 11 04 29 am

Finally, if I close the modal and click on @Alys again, I get the correct data:
screen shot 2014-11-21 at 11 04 33 am

This behavior seems only to occur in beta, not the main site.

**Comment by crookedneighbor** [comment]
Oh, I see that @Alys also mentioned something similiar to what I just reported.

**Comment by lefnire** [comment]
@crookedneighbor that's fixed in https://github.com/HabitRPG/habitrpg/commit/31fdc866c3682308447ff4ee1a4fb6d18e75f806

**Comment by crookedneighbor** [comment]
Gotcha, should have checked out the branch locally.

**Pull request merged**
