### PR TITLE
Unhides scroll bar in quest selection list

### LINKED ISSUE #9640: scroll bar mostly hidden in quest selection list in party page
On the party page, when you want to start a new quest and you get the screen that lets you choose a scroll, the scrollbar is mostly hidden by the quest description in the middle.

img

This is similar to https://github.com/HabitRPG/habitica/issues/9537 and probably can be fixed in much the same way: https://github.com/HabitRPG/habitica/pull/9544

_Thanks to sonnet73 for reporting this in the Report a Bug guild._

Labels updated.

### PR DESCRIPTION
**Pull request by cassidypignatello**
Fixes #9640

### Changes

- Adjusted position of `left-panel` within `startQuestModal` component so that the scroll-bar is no longer hidden
- Changed `overflow` to `overflow-y` and set to `auto` in order to remove the whitespace along the bottom

----
UUID: 62a29b30-6dcf-47e7-92f5-87e2cf2a510f

### CODE REVIEW

**Comment by TheHollidayInn** [comment]
Looks good! Can you remove the changes to your package-lock file? You aren't adding or removing packages in this PR so we won't want to save that change.

**Comment by cassidypignatello** [comment]
Well, this turned into a bigger mess than I expected quickly. I tried running `git checkout develop -- ./package-lock.json` to overwrite the file, but that didn't seem to work. So I decided to reset my local branch to the last commit and just re-write my changes to `startQuestModal.vue`, but git forces me to pull in the changes from my remote branch before it will allow me to push back up again. I'll keep looking into this on my end, but is there an easier way to do this that I'm just unaware of?

**Comment by TheHollidayInn** [comment]
It looks like you may have ran into an issue with rebasing. I'd suggest mergeing in develop when you get out of date, but you might want to just reopen a new PR since the change was small. :/

**Comment by cassidypignatello** [comment]
Thanks so much! Good to know about merging vs. rebasing, I'll definitely keep that in mind going forward. No worries, I'll go ahead and open a new PR!

**Pull request closed without merging**
