### PR TITLE
Small login form attribute improvements

### PR DESCRIPTION
**Pull request by LionC**
Added `spellcheck='false'` to username inputs to make it less annoying to use on some devices/OSes where some usernames will be "corrected" by default.
Added `required` to user/email and password inputs on the login form.

### CODE REVIEW

**Comment by crookedneighbor** [comment]
Looks reasonable to me.

This will count towards a contributor tier! What's your User ID? You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api). Be sure to only copy the User ID and _not_ your API Token.

**Comment by crookedneighbor** [comment]
Just a note, in the future, I'd create a new branch, rather than work directly on your version of develop. That will allow you to easily work on multiple issues at once!

**Comment by LionC** [comment]
Whatever a controbutor tier is, it sounds like something good so here is my UUID: 275e0080-0338-4617-9ef2-7c7fd8761c33

If I should notice small things like that in the future, is making small pull requests like this one fine or are summarized requests with multiple improvements prefered so you guys have less work?

**Comment by crookedneighbor** [comment]
If the changes are all related to each other, feel free to make one pull request. However, if they're separate, please make separate pull requests. That makes them easier to review. 

Here's some info on contributor rewards: http://habitrpg.wikia.com/wiki/Contributor_Rewards

**Pull request merged**
