### PR TITLE
Updated fotify potion art

### PR DESCRIPTION
**Pull request by TheHollidayInn**
This is a fix for https://github.com/HabitRPG/habitrpg/issues/4952 .

I updated the file, and then ran the grunt sprite job. This is my first time updating art, so let me know if I did this incorrectly.

### CODE REVIEW

**Comment by crookedneighbor** [comment]
:+1:

**Comment by crookedneighbor** [comment]
@TheHollidayInn You need to recompile the sprite sheets, since changes have been made to this pr since you originally ran it. 

Also, the file you got has the wrong dimensions. It should be 57px by 54px, like the original file. Do you have an image editor that you can use to increase the padding around the image, without changing any pixels of the image?

**Comment by TheHollidayInn** [comment]
Hey, I can do both things you ask. Although, I'm not sure what changes have been made to the PR.

**Comment by crookedneighbor** [comment]
@TheHollidayInn no worries. Just pull in the latest changes from upstream `git pull upstream develop` (assuming you've set a remote for the main habitrpg repo called upstream) and then re-run the `grunt compile:sprites` task.

**Comment by TheHollidayInn** [comment]
@crookedneighbor Ah, is that any different than rebasing? I'll git to this in the morning.

**Comment by crookedneighbor** [comment]
Rebasing is the correct way to do it, but can be tricky to sort out if you've already pushed to a remote branch. Wasn't sure what level of git-fu you have, so if you want to rebase, go for it. 

You could also do `git pull --rebase upstream develop`, which is the shortcut command to do the rebasing (instead of `git fetch upstream && git rebase upstream/develop`. 

If you end up having an out of whack commit history, IE, it says you have commits on your remote branch that you don't have locally, it's probably because the rebasing is recreating those changes, giving them new commit SHAs. In that case, I'd `git push --force` to your remote branch, so it overrides those old versions of the commits with your new rebased ones. This is the only circumstance where use of `--force` is acceptable. :wink: 

For a change like this, where really, the only real change is one image, I think it'd be just fine to just pull instead of rebase, since that change isn't really dependent on other changes. Does that make sense?

**Comment by TheHollidayInn** [comment]
Yea, my git-fu is not so strong..

Should I have been on my fotify-potion-new-art branch when using git pull upstream develop ?

Either way, I think I made the change.  It looks like the .css went back to normal because the padding correctly placed the potion, but I am unsure.

**Comment by lemoness** [comment]
Sorry, I should have checked the submitted potion's canvas dimensions
before uploading it!

**Comment by crookedneighbor** [comment]
@TheHollidayInn notated toward your next tier

**Comment by TheHollidayInn** [comment]
Thank you

**Pull request merged**
