### PR TITLE
Implemented new Achievement and Badge: Invited a Friend (Fixes #8615)

### LINKED ISSUE #8615: New Achievement and Badge: Invited a Friend
A new achievement and badge are ready to be implemented! This should be received when a player invites a friend to Habitica, and that friend becomes an active user. The badge image and the name/mouseover text for the user achievement page can be found here: 

https://trello.com/c/46zdTjUc/10-invited-a-friend-badge

### PR DESCRIPTION
**Pull request by kvsm**
Fixes #8615

### Changes
Added new achievement 'Invited a Friend' as per #8615 
Added integration test

The achievement is awarded if a user does not currently have the achievement and invites a friend, who subsequently registers a new user account using the link provided in the invitation email.

----
UUID: 176cc46d-af71-4a98-a89b-8bc4babfbaf5

### CODE REVIEW

**Comment by kvsm** [comment]
Is this one being held until the new front end is released? Should I reimplement the client part for Vue?

**Comment by TheHollidayInn** [comment]
This has server code, so I'm fine merging it. Right now you are in the ready for review queue. @SabreCat Will most likely be reviewing. 

Also, I think you should remove the files generated from `gulp sprite` from the PR.

**Comment by SabreCat** [comment]
Removing the compiled PNG and CSS files would be preferable, yes, but I can give this a look regardless!

**Comment by kvsm** [comment]
Fixed it up :wink:

**Comment by SabreCat** [comment]
Not sure why those tests are failing after merge conflict reconciliation, there--certainly unrelated to this development. Tested out and looks good! Thank you for your contribution, @kvsm, I've noted this toward your next Blacksmith tier!

**Pull request merged**
