### PR TITLE
changed wikia links to fandom

### LINKED ISSUE #10954: Habitica wiki *.wikia.com links will change to *.fandom.com in January/February 2019
_This is on hold for now. I want it here so we don't forget later and can plan for the work when it is needed._

As described at [Help:Fandom domain migration](https://community.wikia.com/wiki/Help:Fandom_domain_migration), the wikia.com domains are being migrated to fandom.com and the process is expected to be completed in early February 2019.

This will affect our habitica.wikia.com site and all of the non-English wikis.

When the change has been made, we'll want to update wikia.com links throughout the website and mobile apps (FYI @phillipthelen). However it won't be urgent because as that help page says "The existing wikia.com domains will all redirect to fandom.com, so any bookmarks or links across the web will continue to work as they do now."

There'll likely also be some links within the wikis themselves that have the wikia.com domain hard-coded in them but wiki editors will fix that so it doesn't need to be considered in this issue.

For this issue, we might want to consider editing the locales files for all languages since they aren't being managed in Transifex any more. A search-replace with sed or similar could do it with little effort.

I'll take this off hold when the change has been made.

### PR DESCRIPTION
**Pull request by GiacomoLaw**
Fixes issue #10954

[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #10954

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

Changed links to fandom due to wikia move.

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 1951d08e-56af-445e-8554-f70633b6eaa6

### CODE REVIEW

**Comment by GiacomoLaw** [comment]
Seems like I messed up the locales. Is there any way to exclude them from the PR?

**Comment by paglias** [comment]
@Alys given the current Transifex state I think it's fine to change all the locales in this case, right?

@GiacomoLaw I think editing all the locales is fine but looks like there are some conflicts, would you mind resolving them? Thanks!

@SabreCat Given this PR and a few others changed all locales we should probably stop overriding them with the version from Transifex until a replacement is found (if it's stil being done)

**Comment by GiacomoLaw** [comment]
@paglias sure thing, I will get to it

**Comment by GiacomoLaw** [comment]
Fixed!

**Review by GiacomoLaw — COMMENTED** [review]
Just reviewed quickly, I changed the locales too so they will be fine for the latest Fandom version. In addition, only links were changed and there isn’t an effect on any core parts of the app.

**Comment by paglias** [comment]
@GiacomoLaw  thanks for this! I'm merging the PR and awarding your contributor tier.

Note that further tiers require increasing amounts of work from one to the next, so Tier 2 may require a couple of PRs or a larger PR to attain. But keep helping out and we'll express our gratitude accordingly!

**Comment by GiacomoLaw** [comment]
Awesome thank you! Glad to help 🙂

**Pull request merged**
