### PR TITLE
Only questStart if not questing

### LINKED ISSUE #2592: Quest Scrolls acting up: negative number of quest scrolls
I had what seemed to be "-1 scrolls" (actually one The Fiery Gryphon scroll), until I spent 4 gems each on Trapper Santa and Find the Cub. Now I have "1 scroll", which is actually one Trapper Santa and The Fiery Gryphon from before. The Find the Cub scroll never materialised. Any idea what is up?

_edit by Alys 2019-03-23:_

For the current status of this bug, see this comment and any comments after it: https://github.com/HabitRPG/habitica/issues/2592#issuecomment-475829848

### LINKED ISSUE #2657: boss keeps resetting HP on cron [$15 awarded]
The Fiery Gryphon keeps reseting its health either at the days roll over, or when a new player logs in... In either case it's pretty ridiculous.

screen shot 2014-01-30 at 11 02 21 am
## <bountysource-plugin>

The **[$15 bounty](https://www.bountysource.com/issues/1396584-boss-keeps-resetting-hp-on-cron?utm_campaign=plugin&utm_content=tracker%2F68393&utm_medium=issues&utm_source=github)** on this issue has been claimed at [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F68393&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by deilann**
Should fix #2592 and fix #2657

I believe the issue is questStart is being called for unknown reasons. This makes it check to see if a quest is actually running.

### CODE REVIEW

**Comment by lefnire** [comment]
Closing in favor of https://github.com/HabitRPG/habitrpg/commit/9a4e8d38b46d02475ca97121b5d77a777f8d1f92 . We need to send a `res.send/json`, else the browser will hang. @deilann keep an eye out in coming days (pushing with rats soon) to see if the reports diminish. I wasn't able to write tests yet to see if this is indeed the source, but hope to eventually. If all's well, 'course the bounty & hammer is yours (sorry for overriding this PR)

**Comment by lefnire** [comment]
hmmm... maybe I should make it a `return next('Quest already began.')` for now so I can get emails showing if this actually ever happens...

**Comment by deilann** [comment]
o7 lol it's a bounty I placed by the by

**Comment by deilann** [comment]
That seems like a good idea. Should give a better idea.

**Pull request closed without merging**
