### PR TITLE
Hide HP/GP/XP/Level in stats when header is shown.

### PR DESCRIPTION
**Pull request by Gaelan**

### CODE REVIEW

**Comment by thepeopleseason** [comment]
Does this also kill the HP/GP/XP/Level view when viewing a party member or other user?

**Comment by deilann** [comment]
@thepeopleseason I think so, yeah. That's not good!

**Comment by Gaelan** [comment]
Ooh, good catch.

**Comment by Gaelan** [comment]
Does anyone know an easy way to check if a user is currently logged in?

**Comment by Alys** [comment]
I'm not sure this is the best thing to do, even if it's only for the current user and only when they can see their stats elsewhere. Consistency is a really good thing, even when it means a bit of extra space is taken up unnecessarily.

If players see that the Stats section appears sometimes but not at other times, and don't realise that it correlates with the header being hidden/shown, they'll be likely to log unnecessary bug reports, and we don't need more of those. :)

It also could be confusing when users are trying to help each other in the Tavern if the user needing help is seeing something different than the user trying to help them. 

People who are making screenshots for wiki documentation will have to do two shots instead of one, or describe in words that the stats section doesn't always appear.

I think this could create more problems than it solves.

**Comment by Alys** [comment]
I'm closing this because of the consistency reasons given above. I'm sorry @Gaelan!

**Comment by Gaelan** [comment]
Ok, got it.

**Pull request closed without merging**
