### PR TITLE
(WIP) Conditional Buy Gem modal, cont'd

### PR DESCRIPTION
**Pull request by SabreCat**
Continuation of @AnitaYCheng's work on #5875. Rebased onto `develop` 12/8/2015.

### CODE REVIEW

**Comment by SabreCat** [comment]
As of this commit, I have the merge conflicts sorted and feedback incorporated up to [this comment](https://github.com/HabitRPG/habitrpg/pull/5875#issuecomment-145510688). I haven't yet implemented the new popup proposed by @Alys and @lemoness; that'll take a chunk of time yet. Feedback on the changes so far is welcome!

**Comment by Alys** [comment]
For the record, here's screenshots of these changes:

When a non-subscriber clicks on the gem in the header:

screen shot 2016-01-13 at 9 59 44 am

When a subscriber clicks on the gem in the header:

screen shot 2016-01-13 at 8 09 17 am

When a non-subscriber visits the subscription page:

screen shot 2016-01-13 at 10 00 26 am

When a subscriber visits the subscription page:

screen shot 2016-01-13 at 10 03 36 am

When a subscriber who has cancelled visits the subscription page:

screen shot 2016-01-13 at 8 15 17 am

**Comment by SabreCat** [comment]
There's something funky going on with the sizing/placement of the "Credit Card (using Stripe)" button. It looks fine in "Purchase Additional Gems" and at the top of non-subscriber "Purchase Gems", but elsewhere it's kinda huge in not a good way.

**Comment by SabreCat** [comment]
Also, tch, "Exclusive Monthly Items" should be in sentence case to match the rest of the "Benefits" bullets. That one's my bad!

**Comment by Alys** [comment]
This is what it looks like when a subscriber has bought all their gems:

screen shot 2016-01-13 at 9 32 23 pm

The text currently is "You have bought all the gems you can this month. Thanks for subscribing!"  Unless anyone objects, I'll change that to  "You have bought all the gems you can this month. More will become available within the first three days of next month. Thanks for subscribing!" The gem cap reset time is a semi-common question.

**Comment by Alys** [comment]
Can the "cancel" button be changed to "close" on all the screens where it appears? "Cancel" makes it sound like you can undo the purchase by clicking that button.

Also I'm wondering if we should have a sentence on the subscriber's gem purchase screen to tell them where they can find their subscription details and cancel button. If they bought the subscription by clicking on the gem, they'll expect to see the subscription details there too.

**Comment by lemoness** [comment]
I agree. How about: "Click here to see your subscription details!"

I like the idea of changing the Cancel to Close, and adding the extra
sentence to clarify gem reset times.

**Comment by Alys** [comment]
Would "Go to [Settings -> Subscription](https://habitica.com/#/options/settings/subscription) to see your subscription details!" be okay? It would let the users see the direct path to get there, and is also more informative for visually impaired users using screen readers (I believe some readers can summarise all links on a page, and links like "click here" don't give any context, but "Settings -> Subscription" would).

**Comment by SabreCat** [comment]
Where should "Go to Settings -> Subscription to see your subscription details!" be in the modal? It doesn't seem like it fits under any of the existing headings, and adding a whole "Thanks for subscribing!" panel might be overkill.

**Comment by Alys** [comment]
I was imagining it at the bottom as just a stand-alone sentence.

**Comment by lemoness** [comment]
I'd like to see a shot of what it looks like, but the wording sounds good.

**Comment by SabreCat** [comment]
Like so?
image

**Comment by lemoness** [comment]
Looks good!

**Comment by Alys** [comment]
I like it! Thank you @SabreCat!

**Pull request merged**
