### PR TITLE
Drag challenge tasks

### LINKED ISSUE #1703: challenge tasks don’t retain sort order when creating or editing a challenge
One can reorder items on the Challenges tab but the sort reverts. 

EDIT by Alys 2020-05-13: Before working on this, please read the comments below and also the comments in this pull request: https://github.com/HabitRPG/habitica/pull/12021 . If you think the code in that PR is suitable for re-use in your solution, you're welcome to use it - please mention in your PR that you've done so.

EDIT by Alys 2017: This issue will be easier to fix now because  there is code for sorting tasks in Group Plans (#8358) and it can be reused for challenges. Copying from @TheHollidayInn's [comment below](https://github.com/HabitRPG/habitica/issues/1703#issuecomment-274308541):
"the code allows to order challenge tasks (and can be shared between all three). Although, there needs to be a taskOrder object on the challenge - not sure if that exists."

EDIT by Alys 2020-02-28: What's supposed to happen is that the order of the tasks you see on the challenge's screen should be the same as the order of the task IDs in the challenge's `tasksOrder` object. Below is an example of that object in a challenge's document.

An additional problem is that the challenge's page has lost the ability for the challenge owner to reorder the tasks. The owner should be able to drag and drop in the same way that a user can drag and drop their own tasks. Admins (moderators and staff) should also be able to drag and drop the challenge's tasks (there's already code for challenges that gives admins the same rights at the challenge owner). Other players should not be able to drag a challenge's tasks in the challenge's own page (of course they can drag their own copies of the tasks after they join the challenge).

```
{
    "_id": "b7fbd6a2-6d5e-4f28-a81f-12f42f9cf447",
    "tasksOrder": {
        "habits": [
            "990933b0-4853-4f38-92b0-3864ce576f9e",
            "3d131996-768b-46e9-937d-993452a78df2",
            "5ca7fbf1-b7b5-498e-9c6d-85d328a50099"
        ],
        "dailys": [
            "30ef773b-292e-46e7-beb1-ecf2df66cbb3",
            "62782db7-8bbd-48e4-b0b0-2ab86a5d1031"
        ],
        "todos": [
            "85a5e240-8c64-446d-baab-db6debbabdd0",
            "71a67058-e022-497a-8319-d52584383b66"
        ],
        "rewards": [
            "2c0f8ed9-a61f-4ba4-9ad4-5f36a25db02a"
        ]
    },
    "official": false,
    "memberCount": 0,
    "prize": 0,
    "name": "My Challenge",
    .... etc ....
}
```

### PR DESCRIPTION
**Pull request by alecbrick**
[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #1703

I worked on this one previously (in PR #12021), but work got pretty time-consuming when I only had a few minor edits left. Sorry about that - I think this is ready for review!

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
Currently, challenge and group tasks can't be dragged and reordered. This change allows them to be reordered by anyone who can create or modify tasks.

However, one of the issues with allowing challenge and group tasks to be reordered is that challenges and groups don't respect the `tasksOrder` object. As such, this PR also ensures that the tasks are always ordered according to `tasksOrder`, which is done by ordering the tasks in the GET /tasks/user endpoint.

One thing to note is that in the front end, challenges and groups currently add tasks at the _end_ of their lists, while user tasks are added at the _beginning_ of their lists. However, this all occurs in one place in the backend, where the tasks are added to the beginning of their `tasksOrder` lists. In order to unify these, I've changed challenges and groups so that new tasks are added at the beginning of their lists, rather than at the end. Let me know if that's not something we want!

Additionally, I've refactored some of the code in the Tasks API that checks whether a user can modify a task.

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 3c2b1d99-c6f0-4e6e-a67a-bd8e023cfc7e

### CODE REVIEW

**Comment by Alys** [comment]
> I've changed challenges and groups so that new tasks are added at the beginning of their lists, rather than at the end

In my opinion I think that's a good change. When you join a challenge, you're likely to want to look at / adjust / move your new tasks straight away, which is easier if they start at the top.
If a challenge owner adds new tasks to a challenge you joined previously, you'd be likely to not notice them when they go to the bottom, so having them added at the top is much better. Similarly for when a group leader assigns a new task to you.

I've labelled this as "notify helpers" so that if this particular change does go live, I'll remember to tell the Socialites guild, Challenge Leaders guild, and wiki editors about it.

**Comment by paglias** [comment]
thanks @alecbrick for picking this up again ! I'll review it in the next few days, but I'm wondering if this comment https://github.com/HabitRPG/habitica/pull/12021#issuecomment-613691825 got addressed in this version (the fact that the API doesn't order the user tasks but it is done on the client and we should probably do the same for the challenge and group ones)

**Comment by paglias** [comment]
Hi @alecbrick, any update on my last comment? I'm happy to finish this if you don't have time, just let me know :)

**Comment by alecbrick** [comment]
Sorry for the late response! No, we're still ordering challenge and group tasks on the server here - haven't changed anything.

**Comment by paglias** [comment]
@alecbrick okay, as I said in a previous comment, I understand it might not be the best option but for the time being I prefer if the ordering remains on the client side like for user tasks. Let me know if you want to make the changes or if you can't that's totally fine I'll take over

**Comment by veeeeeee** [comment]
@paglias If you're able to take this over, I think that would be fine!

**Comment by alecbrick** [comment]
I'm back! @paglias 

I would really prefer not to add the client-side ordering in this PR. The idea that a Column is connected to a User is heavily baked-in, and a lot of the ordering logic for the user tasks revolves around that. If we were to add client-side ordering for challenges and groups, it would involve a lot of refactoring that doesn't really fit with this PR.

If client-side ordering absolutely must happen here, that's fine, but IMO it's a separate issue

**Comment by alecbrick** [comment]
Just following up - @paglias, are you able to review this?

**Comment by paglias** [comment]
Hi Alec, unfortunately I will not be able to help with the review of this PR. Pinging @SabreCat

**Comment by SabreCat** [comment]
Thanks so much @alecbrick, this is fantastic! This will make a lot of users happy. 😸 Welcome to Blacksmith contributor tier 3!

**Pull request merged**
