### PR TITLE
drag tags to reorder

### LINKED ISSUE #7541: Tags cannot be sorted / reordered
Tags cannot be sorted. If you change the order of the tags, the next time a sync occurs, they change back.

### PR DESCRIPTION
**Pull request by negue**
re-add the ability to drag tags

image
@Tressley 

closes #7541

### CODE REVIEW

**Comment by Tressley** [comment]
I think this looks good. Would it be possible to have the knurling (six dots) be #C3C0C7 and #878190 on hover? Also, the re-order doesn't stay if the user clicks cancel, correct?

**Comment by negue** [comment]
color changed, and now it only changes the tags on save :)

**Comment by Tressley** [comment]
I'll definitely want to play with a bit on Staging to see how it feels, otherwise LGTM 👍

**Comment by paglias** [comment]
Tried this locally and it works well! @Tressley it'll be on staging in about 30 minutes

**Pull request merged**
