### PR TITLE
Added confirmation before deleting messages and moved buttons to top of ...

### LINKED ISSUE #4848: inbox "Clear All" needs confirmation dialog; "Clear All" and "Opt Out" should be at top of page
Currently, in a player's inbox, there is a "Clear All" button and an "Opt Out" checkbox, but they both appear at the bottom of the messages so it's really easy to forget they are there. I'd like to see them at the top of the page.

BUT BEFORE we do that, we should make "Clear All" have a confirmation screen, because when it's at the top it will be too easy to click on accidentally (currently, one click means that all messages disappear instantly). I think it would also help to have "Clear All" renamed to "Delete All Messages" to make it really obvious what it does. The confirmation screen should also point out that it will delete messages in your own inbox, not any messages from you in other people's inboxes.

These are two separate changes, so if a programmer wants to work on only one of them that's perfectly fine, but we would not merge a change to the location of the button and checkbox until after the confirmation dialog had been created.

### PR DESCRIPTION
**Pull request by stillsnowedin**
...Inbox. (fixes #4848)

Screenshot of the confirmation dialog:
delete_confirmation

My HabitRPG account is katinahat (5a43ad99-f151-4875-964d-b2ce2564512f).

### CODE REVIEW

**Comment by Alys** [comment]
That's looking good! Thank you for working on it so quickly!

Just a couple of things: Could you remove the popover? There's no point to it now. I'm sorry I didn't mention it before - I hadn't noticed it.

Also on line 83, can you please change the key "deleteAllMessages" back to "clearAll"? The text should stay as it is (i.e., "Delete All Messages" is correct). In the locales files, the keys are sort of like variable names in that they don't need to exactly match the text that they hold, and they shouldn't be changed unless really necessary. 

One reason for not changing keys is that the same keys are used throughout all the locale files for other languages. If the name of the key is changed in the English file, then the existing translations for the old key name will stop being used, and people who use other languages will see the English string "Delete All Messages" instead of the translated version of "Clear All". It's better to let other languages keep using the old version of the string until the translators have a chance to update it to the new text.

**Comment by stillsnowedin** [comment]
I was wondering about the localization stuff, actually. My instinct was to update all the language files, but I saw the readme saying not to touch them.

Changed it back to "clearAll" and removed the popover in the latest commit. Anything else that needs fixin'?

**Comment by Alys** [comment]
Thank you for this! It's just what I wanted. 

Tier++

I'm going to put a bit of space between the delete button and the opt-out checkbox, but that's just an `&nbsp;` and I'll push it through as a direct commit. It's too small a change to be worth extra back-and-forth here. :)

**Comment by stillsnowedin** [comment]
Yay, so excited I made the cut! One down, five to go. The hydra will be mine, oh yes, it will be mine. :)

**Pull request merged**
