### PR TITLE
Triumph Theme by anastasiagaskamp

### PR DESCRIPTION
**Pull request by SabreCat**
By @anastasiagaskamp. Continuation of #9197 

# Changes

Added a new theme called Triumph.

# Notes

In 'Guidance for Bards' on the Wiki, it said to open website/views/shared/header/menu.jade. I was unable to locate this file, and edited no file to follow the given instructions.

Accio BooOOOooks gave the following instructions to Pizilden in the Aspiring Blacksmith's guild, which I ended up following:

1. Add music to website/static/audio/themeNameTheme
2. Add the line themeNameTheme into the array at line 49 of website/common/script/content/index.js (api.audioThemes = ...)

User ID: 0f428943-2414-443e-b719-d8be47b95359

I did the coding and created the theme.

### CODE REVIEW

**Comment by negue** [comment]
@anastasiagaskamp thanks for your theme :)

Could you trim the audio files at the end? I checked all of the mp3s , I guess the oggs are the same

@SabreCat  only just updated the branch so that it was easier to test ^^

**Comment by Airu216** [comment]
If the original bard isn't around I can trim the audio for them :) As well as the other theme if needed.

**Comment by paglias** [comment]
@SabreCat @anastasiagaskamp what's the status on this?

**Comment by Airu216** [comment]
I can trim the audio files if needed if someone can help provide the files.

**Comment by SabreCat** [comment]
@Airu216: The files are in the PR--do you need a hand with how to download them?

**Comment by Airu216** [comment]
I do, is it possible for it to in a downloadable rar file for me? Ie maybe
uploaded on google drive or probably emailed since the file size wouldn't
be that large.

**Comment by SabreCat** [comment]
@Airu216:
https://github.com/HabitRPG/habitica/raw/b532abaa18b227a7b51f929c2be35e4aab6a917f/website/static/audio/triumphTheme/Achievement_Unlocked.mp3
https://github.com/HabitRPG/habitica/raw/b532abaa18b227a7b51f929c2be35e4aab6a917f/website/static/audio/triumphTheme/Achievement_Unlocked.ogg
https://github.com/HabitRPG/habitica/raw/b532abaa18b227a7b51f929c2be35e4aab6a917f/website/static/audio/triumphTheme/Chat.mp3
https://github.com/HabitRPG/habitica/raw/b532abaa18b227a7b51f929c2be35e4aab6a917f/website/static/audio/triumphTheme/Chat.ogg
https://github.com/HabitRPG/habitica/raw/b532abaa18b227a7b51f929c2be35e4aab6a917f/website/static/audio/triumphTheme/Daily.mp3
https://github.com/HabitRPG/habitica/raw/b532abaa18b227a7b51f929c2be35e4aab6a917f/website/static/audio/triumphTheme/Daily.ogg
https://github.com/HabitRPG/habitica/raw/b532abaa18b227a7b51f929c2be35e4aab6a917f/website/static/audio/triumphTheme/Death.mp3
https://github.com/HabitRPG/habitica/raw/b532abaa18b227a7b51f929c2be35e4aab6a917f/website/static/audio/triumphTheme/Death.ogg
https://github.com/HabitRPG/habitica/raw/b532abaa18b227a7b51f929c2be35e4aab6a917f/website/static/audio/triumphTheme/Item_Drop.mp3
https://github.com/HabitRPG/habitica/raw/b532abaa18b227a7b51f929c2be35e4aab6a917f/website/static/audio/triumphTheme/Item_Drop.ogg
https://github.com/HabitRPG/habitica/raw/b532abaa18b227a7b51f929c2be35e4aab6a917f/website/static/audio/triumphTheme/Level_Up.mp3
https://github.com/HabitRPG/habitica/raw/b532abaa18b227a7b51f929c2be35e4aab6a917f/website/static/audio/triumphTheme/Level_Up.ogg
https://github.com/HabitRPG/habitica/raw/b532abaa18b227a7b51f929c2be35e4aab6a917f/website/static/audio/triumphTheme/Minus_Habit.mp3
https://github.com/HabitRPG/habitica/raw/b532abaa18b227a7b51f929c2be35e4aab6a917f/website/static/audio/triumphTheme/Minus_Habit.ogg
https://github.com/HabitRPG/habitica/raw/b532abaa18b227a7b51f929c2be35e4aab6a917f/website/static/audio/triumphTheme/Plus_Habit.mp3
https://github.com/HabitRPG/habitica/raw/b532abaa18b227a7b51f929c2be35e4aab6a917f/website/static/audio/triumphTheme/Plus_Habit.ogg
https://github.com/HabitRPG/habitica/raw/b532abaa18b227a7b51f929c2be35e4aab6a917f/website/static/audio/triumphTheme/Reward.mp3
https://github.com/HabitRPG/habitica/raw/b532abaa18b227a7b51f929c2be35e4aab6a917f/website/static/audio/triumphTheme/Reward.ogg
https://github.com/HabitRPG/habitica/raw/b532abaa18b227a7b51f929c2be35e4aab6a917f/website/static/audio/triumphTheme/ToDo.mp3
https://github.com/HabitRPG/habitica/raw/b532abaa18b227a7b51f929c2be35e4aab6a917f/website/static/audio/triumphTheme/ToDo.ogg

For future reference, you can get at the files by going to the "Files changed" tab of the PR and clicking "View" for the file in question!

**Comment by Airu216** [comment]
Very nice and clean trumpet theme. Trimmed them. Thank you so much @SabreCat @negue @paglias for your assistance. 

https://drive.google.com/file/d/17pFQDwSvUydl6sGKimYcDhcMyjkNGpLg/view?usp=sharing

**Comment by paglias** [comment]
Is this ready?

**Comment by SabreCat** [comment]
@paglias Yup, ready for review

**Comment by SabreCat** [comment]
@anastasiagaskamp Thanks for this! I'd like to credit you as a Bard, but the Habitica User ID you gave doesn't appear to work. Do you still have an account?

**Pull request merged**
