### PR TITLE
Fix #6657: Emojis in challenge title now properly displayed on winner's profile and in challenge-won modal

### LINKED ISSUE #6657: Emojis in challenge titles don't show properly in challenge winner's profile
Emojis in challenge titles don't show properly in the challenge winner's profile. For example, if a challenge is named "This :smile: is a test!", it shows as "This : smile : is a test!" (without the spaces between colons and emoji name) in the challenge winner's profile.

Yes, it's just a tiny low-priority thing. I wouldn't even have reported it, but was told it's an unreported bug that should probably be fixed instead of something that's just supposed to stay that way.

### PR DESCRIPTION
**Pull request by khipkin**
This addresses issue #6657.  There are lots of screenshots in the issue itself.  I will only include screenshots of the finished result here.

Here is an example of a challenge title containing the : smile : emoji (w/o spaces) on the challenge winner's profile:
image

And here is the challenge title with the emoji in the challenge-won modal:
image

### CODE REVIEW

**Comment by crookedneighbor** [comment]
Pro tip, typing closes #6657 in the PR or the commit message will automatically close the issue when this gets merged in :)

https://help.github.com/articles/closing-issues-via-commit-messages/

**Comment by crookedneighbor** [comment]
Squashed and merged in 

This will count towards a contributor tier! What's your User ID? You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api). Be sure to only copy the User ID and _not_ your API Token.

**Comment by khipkin** [comment]
Wow I didn't know that. But I said "addresses", not "closes"! Ahh :cry:  So the changes were merged? Or nah?

My User ID is f9c89bba-abf8-4f20-a974-cf1550ff603f but I just got to tier 1 yesterday...

**Comment by crookedneighbor** [comment]
Your changes were merged in (https://github.com/HabitRPG/habitrpg/commit/a0f65f8b250398944875447a60ff91698142d148), I just rebased and squashed your three commits into two commits, which changed the git sha. 

I've notated this PR toward your next contributor tier.

**Pull request closed without merging**
