### PR TITLE
Added Arashi's theme as a new audio theme

### PR DESCRIPTION
**Pull request by Airu216**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Added Arashi's theme)

### Changes
[First commit]: This adds a new theme entitled Arashi's theme, tested locally and everything works. 

----
Arashi's theme by: 
Username: Airu 
UUID: 8c798ac6-17a0-4b0c-9e5b-a33ba5fa1870

### CODE REVIEW

**Comment by Airu216** [comment]
Waitng for review ?

**Comment by TheHollidayInn** [comment]
Thanks for the PR :D We will review it soon.

**Comment by TheHollidayInn** [comment]
Looks like some merge conflicts came up while merging other PRs. Do you mind fixing those so we can merge?

I add this to your teir progress :D

**Comment by Airu216** [comment]
Alright noted. Will work on it whenever I can as I'm having exams at the
moment. Thank you for your patience and cooperation :)

**Comment by Airu216** [comment]
I apologize but since I'm not too familiar with it, I just realized that I may need to fork a new clone like before then push my changes instead of only using the 'Resolve conflicts' button to keep both changes (In this case I realized another new theme was added by Beatscribe so I added the appropriate text) ?

**Comment by TheHollidayInn** [comment]
Looks like you did it correctly! I will check locally real quick. The flow for you locally would have been the following:
1. git fetch upstream develop
2. git checkout develop
3. git merge upstream/develop
4. Fix all the conflicts in your text editor
5. git push develop (and maybe git push develop --force)

The merge editor is also fine. Next time, you might want to create a new branch too (so you can work on multiple features).
The flow is like this:
1. git fetch upstream develop
2. git checkout develop
3. git rebase upstream/develop
4. git checkout -b my-new-feature-or-fix
5. Created awesome code
6. git add .
7. git commit -m "message"
8. git push (follow command line instructions)

**Comment by SabreCat** [comment]
Fantastic! Noted toward your next contributor tier. Thanks for your contributions!

**Comment by Airu216** [comment]
Thank you both so much for the effort and kindness :)

**Pull request merged**
