### PR TITLE
Changed Difficulty link from Trello to Wiki

### PR DESCRIPTION
**Pull request by hairlessbear**
Changed the "more information" Difficulty link to point to the relevant wiki page instead of the Trello Feature Request card.

### CODE REVIEW

**Comment by crookedneighbor** [comment]
@lemoness This is desired, right?

**Comment by lemoness** [comment]
Is this for when you click on "Difficulty" in Task Edit? If so, yes.

**Comment by hairlessbear** [comment]
That's the link I was trying to change. When I searched the code for the current Trello link, only one result came up, so I'm assuming I changed the right thing.

**Comment by Alys** [comment]
Thanks @hairlessbear! Could you tell me your user ID please? (Settings -> API)

**Comment by hairlessbear** [comment]
8ac7242d-8f18-4d6f-b4f4-8f6302f7fa0b

Glad to help, I just hope the next contribution I make is something more substantial :)

**Comment by Alys** [comment]
Tier 1 awarded. Thank you @hairlessbear!

**Comment by hairlessbear** [comment]
Thanks @Alys! One quick thing though; is it supposed to say "Friend
undefined", or is that an error?

**Comment by Alys** [comment]
Deliberate! I never make mistakes........ But since you don't like it, I've changed it to Friend Blacksmith just for you. :)

Sorry about that! Thank you for mentioning it.

**Comment by hairlessbear** [comment]
Thanks @Alys! I was kind of hoping you would've seen the discussion we had about this in the tavern where I decided that the title of "Unicorn" would be wonderful. But in lieu of that, Blacksmith will do just fine :)

**Comment by Alys** [comment]
Sorry @hairlessbear, I only woke up an hour ago and have been doing mostly user support since then, so I haven't had time to read all of the Tavern yet.  We don't give custom titles to contributors, except for those who are moderators. The title explains why the person has been given a contributor tier. You can learn about the titles here: http://habitrpg.wikia.com/wiki/Contributor_Titles

**Comment by hairlessbear** [comment]
Oh, sorry, I knew about the tiers; I wasn't actually expecting a custom title, I was attempting to be amusing. I forgot that sarcasm and the like don't always work through text, especially when there's no context; that's my bad. Sorry for the confusion, and good morning!

**Comment by Alys** [comment]
Ha, sorry @hairlessbear! If I'd read the Tavern, I would have got the amused context. My bad. :)

**Pull request merged**
