### PR TITLE
Some minor changes

### PR DESCRIPTION
**Pull request by ghost**
I have forgotten a word, I changed another one, and fixed some typos.
Sorry for the multiple request!

### CODE REVIEW

**Comment by lefnire** [comment]
some merge conflicts here, I'll have to take a manual pass at this. In the mean time, can you close this and re-open the PR against the `develop` branch?

**Comment by ghost** [comment]
I've closed this PR, but if I want to re-open it in the develop branch, I've have 29 files changed (instead of 1).
Is there a way to select the commit concerned with the pull request?
(I'm not familiar with Git)

**Comment by lefnire** [comment]
Ah, you only want to PR the one file? Ok what you do is:
1) create a new branch from develop or master - which ever is "clean" on your local setup
2) `git cherry-pick` the SHA for the commit you want to push
3) push up that new branch to your Github repo
4) pull request that branch against develop (or is it translations @SlappyBag?)

If that makes your head spin, I can do a little video tutorial, or even we can just merge in those changes you made manually - which file is it you want to keep? Wouldn't want Git to disuade you from your awesome contribution! And thanks again!

**Comment by StanLindsey** [comment]
Translations are going into translations as that is the only branch atm where I've put in the view variables. You're free to move translations over to develop as and when you feel ready to test it live. I did give it limited testing at the time but only with the English translation as that was the only one I had available the begin with. 

xxx

**Comment by lefnire** [comment]
right then, `translations` branch - sorry for the false info @LazuliKazeno

**Comment by ghost** [comment]
Ok, I reopened it in translations branch. Sorry for all the mess!

**Pull request closed without merging**
