### PR TITLE
Replace hard-coded strings for env.t on folder views/shared/tasks/

### PR DESCRIPTION
**Pull request by marcelosizer**

### CODE REVIEW

**Comment by lefnire** [comment]
Dude, thanks for tackling all these. I was afraid nobody would (it's not a fun task!), you are flipping awesome

**Comment by marcelosizer** [comment]
That's a task for people with basic programming skills and it makes you read a lot of code. I've been searching for a couple of years for an open source project to contribute and practice programming but everywhere I read people saying "only contribute to something you're passionate about" and I was afraid I would never find anything!

**Comment by snicker** [comment]
:+1: perfect attitude to have when working with open source, awesome to have more passionate folks around.

**Comment by marcelosizer** [comment]
@paglias

**Pull request merged**
