### PR TITLE
Full Hebrew language locale translation

### PR DESCRIPTION
**Pull request by dannydsdaniel**
This updates includes quality top down Hebrew translation.
The previous version seemed to be of poor quality google translation.
- should be tested and tweaked for minor adjustments right after deployment

-Indingo
HabitRPG UserID: f9249447-efd5-4110-82a5-c4064dbf9b0a

### CODE REVIEW

**Comment by lefnire** [comment]
TMK @bennyp123 is a hebrew speaker, spent a bit of time over multiple commits. Too bad I can't verify, being a non-speaker :/ I know this is gonna be awkward, but I wanna loop him in just for a double check. Will merge right away with his blessing (or if we don't hear back)

**Comment by bennypowers** [comment]
HEY PRESTO, DO IT!

Benny Powers
Licensed Israel Tour Guide

In Israel 054-482-5726
In Canada 705-300-0072
In the USA 601-255-3532

bennypowers.com

**Comment by lefnire** [comment]
great! @dannybm, contrib.lvl++, thanks a ton!

**Comment by liordon** [comment]
hey, there's something bothering me with the hebrew translation that I haven't managed to solve yet.
when posting a message in the tavern or party chat, the "a few seconds ago" string is translated to the equivalent of "a few seconds from now" (in the future). I've been tormented by this since I'm about the only hebrew translator at transifex but I never translated this string, and it also didn't appear on my search in any of the json files (hebrew or english)

so.... are there by any chance parts of the translation which are taken from some secret files instead of the transifex?

**Comment by Alys** [comment]
@liordon : It's most likely that you're seeing "a few seconds from now" because your PC's clock is set to slightly the wrong time. Change the time and the message should be correct. Althernatively, temporarily change the language to English (Settings -> Site) and see if you still see that same message in English. If you do, it has nothing to do with translations and is definitely your clock. Note that it's best to change your clock at the end of the day after all your Dailies are done, just in case it triggers cron.

**Comment by paglias** [comment]
The message is from Moment.js which has its own translations

2014-09-22 22:44 GMT+02:00, Alice Harris notifications@github.com:

> @liordon : It's most likely that you're seeing "a few seconds from now"
> because your PC's clock is set to slightly the wrong time. Change the time
> and the message should be correct. Althernatively, temporarily change the
> language to English (Settings -> Site) and see if you still see that same
> message in English. If you do, it has nothing to do with translations and is
> definitely your clock. Note that it's best to change your clock at the end
> of the day after all your Dailies are done, just in case it triggers cron.
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/HabitRPG/habitrpg/pull/1835#issuecomment-56440076

## 

Matteo Pagliazzi - paglias.net

**Comment by liordon** [comment]
don't worry @Alys , I used habitRPG in english before the transifex kicked in, so I knew for a fact it worked well in english.

@paglias so will those strings be added to the transifex or do I need to make a pull request for that file and fix it through the github?

thanks for the answers! :smile:

**Comment by Alys** [comment]
I doubt that there's anything wrong with the translations in Moment.js - nothing needs to be fixed here. You're seeing the correct message for your situation. The problem is that your PC's clock is a few seconds wrong. You can test this easily by changing HabitRPG's language to English. Even if you've used English in the past, change it again now and look at the chat messages. A new chat message will still be reported as "a few seconds from now" in English, because your PC's time is different than the real time by a few seconds (and HabitRPG's servers will be using the real time). See my earlier message for tips about when to change your PC's time.

**Comment by liordon** [comment]
I see! you are indeed correct. thanks a lot for your patience, and sorry for the false alarm :sweat_smile: 
I also apologize for my false assumption, that was really out of place :sweat:

**Comment by paglias** [comment]
@Nailo anyway they won't land on Transifex because they are not part
of the HabitRPG project. But if you find an error it can be
reported/fixed with a pull request on moment.js repository

2014-09-25 10:44 GMT+02:00, Nailo notifications@github.com:

> I see! you are indeed correct. thanks a lot for your patience, and sorry for
> the false alarm :sweat_smile:
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/HabitRPG/habitrpg/pull/1835#issuecomment-56790191

## 

Matteo Pagliazzi - paglias.net

**Pull request merged**
