### PR TITLE
Move notification snackbars when resting bar is shown

### LINKED ISSUE #10169: Notifications are covered by resting in the inn status banner
As reported by citrusella:

> The inn banner forces the navbar down but doesn't push down the notifications for gold and such, which places the navbar over top of the notifications (presumably because of its z-index? I think?).

I've confirmed this behaviour on production and staging. Here's a screenshot. 
image

### PR DESCRIPTION
**Pull request by ESWAT**
Fixes #10169

### Changes
Moves notification snackbars when resting bar is shown

screen shot 2018-03-24 at 21 46 06

----
UUID: ffee6b77-0bf8-422a-a65c-c20de17f2b32

### CODE REVIEW

**Comment by SabreCat** [comment]
Thank you, @ESWAT ! Noted toward your third contributor tier!

**Comment by Alys** [comment]
I've reverted this in https://github.com/HabitRPG/habitica/pull/10203 because it was causing errors in the browser's console - see that PR for details. @ESWAT Would you like to work on this further? Let us know if you don't have time or if you're not sure what's wrong!

**Comment by ESWAT** [comment]
@Alys I’m looking at #10203 and will take a stab at debugging (I’ll likely be slow since I hadn’t encountered the error mentioned myself)

**Comment by Alys** [comment]
@ESWAT No worries, thanks very much!

**Pull request merged**
