### PR TITLE
HabitRPG-Shared Migration

### PR DESCRIPTION
**Pull request by crookedneighbor**
Is Beta being used right now? Can someone deploy this branch to beta and make sure the build process works correctly?
## TODO (Notes to self)
- [x] hammer - check on other animated gif sprites as well
- [x] logo on static page - check other images on static pages
- [x] Investigate testing issue with coffeescript module update

### CODE REVIEW

**Comment by crookedneighbor** [comment]
Ping @lefnire @paglias @SabreCat @Alys

**Comment by crookedneighbor** [comment]
Closes #3439

**Comment by lefnire** [comment]
Hohhh mama, here it is! Hope to have time to test in coming days, but feel
free to proceed without me if I'm lagging.

**Comment by crookedneighbor** [comment]
Here's the accompanying mobile pr: https://github.com/HabitRPG/habitrpg-mobile/pull/341

**Comment by crookedneighbor** [comment]
From @lefnire 

slack-imgs com

55b7d074e286a99dd2148160b21334cb
(Missing hammer)

**Comment by crookedneighbor** [comment]
Sprite paths corrected for animated gifs. Just need to sort out the tests.

**Comment by lefnire** [comment]
@lemoness do we have any releases coming up? If not, @crookedneighbor we can probably merge this since we'll all be in it locally deving

**Comment by lemoness** [comment]
Not til mid next week - merge away!

**Comment by lefnire** [comment]
Boooom!

**Comment by Alys** [comment]
http://www.youtube.com/watch?v=r6cnryxwH6A

:heart: @crookedneighbor

**Pull request merged**
