### PR TITLE
Added a second message under the "rest at the inn" button, explaining ho...

### PR DESCRIPTION
**Pull request by lorian**
...w the inn interacts with boss fights, in hopes of pre-empting a common tavern question: "If you're in a boss fight, your dailies won't hurt your party members while you're resting, but their missed dailies can still hurt you!" I put it under the button, to avoid the intimidating "big blog of text" look.

### CODE REVIEW

**Comment by lefnire** [comment]
:+1: what's uuid again?

**Comment by lorian** [comment]
142e1f47-6fae-4927-a5c2-3ea8a42b71d1

**Comment by lefnire** [comment]
√

**Comment by deilann** [comment]
I really, really don't like the way this looks, broken up by the button.

I understand wanting to avoid big block of text, but in my opinion, this is worse. I know the answer is to submit my own PR, but I'm not sure what the answer _is_.

**Comment by lorian** [comment]
I tried it as a big block of text, but even I, who loves reading text, found it intimidating. Is there some of the current Inn text that could be removed? Currently a lot of it is unrelated to the inn, and is actually about the Tavern.

**Comment by deilann** [comment]
That's what I was thinking. We might want info about the Tavern where it's
mentioned not to post bugs, especially when guidelines are created?

**Pull request merged**
