### PR TITLE
Don't gain attributes after level 100

### LINKED ISSUE #4474: prevent attribute points being gained above level 100 - related to Skill Rebalancing (for 'rebalancing-2014-12' feature branch) [$25]
This is related to the skills rebalancing that we are doing, as described in [Fix Overpowered Skills - Issue #3029](https://github.com/HabitRPG/habitrpg/issues/3029#issuecomment-68128382). It will go live at the same time as the modified skills.
#### Requirements:

When a user levels up beyond level 100, they should no longer be given a new attribute point to assign to one of their attributes.
#### Notes:
- Do pull requests to the [rebalancing-2015-03](https://github.com/HabitRPG/habitrpg/tree/rebalancing-2015-03) feature branch, not to the `develop` branch.
## <bountysource-plugin>

Did you help close this issue? Go claim the **[$25 bounty](https://www.bountysource.com/issues/7467200-prevent-attribute-points-being-gained-above-level-100-related-to-skill-rebalancing-for-rebalancing-2014-12-feature-branch-25?utm_campaign=plugin&utm_content=tracker%2F68393&utm_medium=issues&utm_source=github)** on [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F68393&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by chimericdream**
I believe this should fix #4474. I did some manual testing with the different allocation strategies and manually allocating points as well as leveling through 100 several times to make sure I didn't get any more attribute points. It all appeared to work correctly.

I abstracted the max level into a variable in case at some future point we decide to add more high-level content. It may be unlikely, but at least now the `100` is not hard coded all over the place.

ping @Alys @deilann

Let me know what you think, and I'll see it in the morning. For now... going to bed. :sleepy:

### CODE REVIEW

**Comment by chimericdream** [comment]
I should note that I created this branch off of the latest `develop`. If it's easier, I can recreate it off the `rebalancing-2015-03` branch. In either case, the relevant changes are in `index.coffee`. [See here](https://github.com/HabitRPG/habitrpg/pull/4841/files#diff-9212b31a96588a139c40288e0155f9caR65).

**Comment by Alys** [comment]
Thanks @chimericdream 

Later today or tomorrow (as soon as I can), I'll update rebalancing-2015-03 with the latest from develop and see if that cleans up your commit. If it doesn't, we will need you to re-do the changes using the rebalancing-2015-03 branch.

**Comment by Alys** [comment]
I've merged upstream/develop into upstream/rebalancing-2015-03 

@chimericdream I'm sorry but could you please recreate this from the rebalancing-2015-03 branch? I'd like the commit to be clean. Sorry about the extra trouble!

**Comment by chimericdream** [comment]
@Alys See #4852

**Pull request closed without merging**
