### PR TITLE
One does not simply *pull request* into Heroism.

### PR DESCRIPTION
**Pull request by SabreCat**
Improved descriptions of reward tiers in the Tavern chat sidebar. Also a couple of other wording/syntax tweaks I thought of along the way.

### CODE REVIEW

**Comment by lefnire** [comment]
:+1: You're already 7, so I'm just gonna keep giving you gems :) Say ol' Sabe, you wouldn't per chance wanna tackle [this puppy](http://community.habitrpg.com/content/color-spectrum-contribs-details-comments) would ya?

**Comment by SabreCat** [comment]
Might be within my reach. Looks like there's still some discussion going on though? Is there a consensus design?

**Comment by lefnire** [comment]
I _feel like_ @lemoness's last breakdown is pretty close to final. Rainbow NPC is gonna be pretty tough, I'm thinking just different background/foreground (since everyone else is white on whatever). If either of you feel it's still an unclosed convo, we'll hold off

**Comment by SabreCat** [comment]
I'm partial to Daniel's suggestion of a more neutral color for first tier, myself... the red-orange suggestion still screamed "ALERT ALERT" to me when I clicked through @lemoness' link.

**Comment by lefnire** [comment]
I'm thinking we can do some color muting for the earlier tiers. Either a a muted color RGB, or even a decreasing alpha going up the chain (red, but 70% alpha for lvl 1 won't scream too much - then yellow at 50% alpha, etc). I haven't yet experimented with this, might be easier said than done (plus browser support). But that was my own plan of action anyway

**Comment by SabreCat** [comment]
Ah sure, that could be viable. What part would you like my help with?

**Comment by SabreCat** [comment]
Also, as a question more pertinent to the actual pull request we're chatting in--with all the activity in translations, is there anything I need to be careful of when stomping around revising text like here?

**Comment by lefnire** [comment]
Don't worry - I'll be splicing out old strings from the html and replacing them with `env.t("petWolfAdjective")`, etc as I'm working through translations. Feel free to keep modifying text, and you'll know you need to hit locales/en/app.json instead of the view when you see `env.t()`

**Pull request merged**
