### PR TITLE
Remove Facebook Pixel

### LINKED ISSUE #8390: FaceBook Pixel isn't firing correctly - delete it
From jmcook (06faccc5-5f69-453c-9a9d-0eeed865985c) in the Report a Bug guild:

"**It looks like the FaceBook Pixel isn't firing correctly. I'm using the 'Facebook Pixel Helper' Chrome extension. This doesn't affect anyone, except the companies marketing team.**"

I haven't done anything to verify or investigate this.

FYI: definition of [The Facebook Pixel](https://en-gb.facebook.com/business/help/651294705016616)

### PR DESCRIPTION
**Pull request by librarianmage**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #8390 

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

Removes Facebook Pixel

[//]: # (Put User ID in here - found in Settings -> API)

----
UUID:

### CODE REVIEW

**Comment by TheHollidayInn** [comment]
@SabreCat Look good?

**Comment by SabreCat** [comment]
We should also remove `FACEBOOK_ANALYTICS` from `config.json.example`, and maybe even remove it from the Analytics service and relevant tests. In other words, revert https://github.com/HabitRPG/habitica/commit/77c276fefe85ea19a5fc6c596dc96395a5e7e0b3

EDIT: This line can stay, as it's an unrelated fix. https://github.com/HabitRPG/habitica/commit/77c276fefe85ea19a5fc6c596dc96395a5e7e0b3#diff-403b761fb22285dc620ea7ef735429e0R65

**Review by SabreCat — CHANGES_REQUESTED** [review]
See https://github.com/HabitRPG/habitica/pull/8396#issuecomment-271950812

**Comment by librarianmage** [comment]
What should I do about test/spec/services/analyticsServicesSpec.js?

**Comment by librarianmage** [comment]
Same with website/client/js/services/analyticsServices.js

**Comment by librarianmage** [comment]
I'm not sure how to fix this, @SabreCat

**Comment by SabreCat** [comment]
@MathWhiz: Ah, the trouble is that the repo structure has been rearranged since that commit, so there is no `/test/spec` folder. Attempting to revert the commit thus made a bit of a mess. My bad, I guess "revert" was bad advice... you could try undoing the changes from that commit in more of a manual fashion, editing the files in their current locations.

**Comment by librarianmage** [comment]
I think I will close this PR and reopen it

**Pull request closed without merging**
