### PR TITLE
Character Create Modal - Prevent Options From Jumping When Selected

### PR DESCRIPTION
**Pull request by rholinshead**
Currently when there are two rows of options in the Character Create Modal (Shirt or Skin Color), selecting an option from the top row and then selecting an option from the bottom row will cause the top row to jump up. This is because a border is being added to the selected option (with class `active`). This PR fixes that issue by adding a border to all options but setting the color when active.

[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes put_issue_url_here

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
- Add white border with radius to `.customize-options .option` selector
- Remove `margin-bottom` for cleaner spacing

[//]: # (Put User ID in here - found in Settings -> API)

----
UUID: 9135bc92-bf74-4c15-82c2-64f1128fe950

# Screen Shots:

##Before Changes:
charactercreatemodalbefore1of2
charactercreatemodalbefore2of2

##After Changes:
charactercreatemodalfix1of2
charactercreatemodalfix2of2

### CODE REVIEW

**Comment by lemoness** [comment]
@tressley You should take a look at this!

**Comment by paglias** [comment]
@rholinshead this looks good but can you post a screenshot before&after since it looks like the PR changes also the margins and border radius?

**Comment by rholinshead** [comment]
@paglias I've made two small changes (added the bottom margin back, change the border color to match background color so that it isn't visible). I also added before/after screenshots as requested. I know it's tough to see (sorry, I'm unable to get a screen recorder working) but in the "before" picture 2/2 the top row is closer to the "Size" and "Shirt" tabs due to the jumping behaviour that occurs when a border is added on selection

**Review by paglias — APPROVED** [review]

**Comment by Tressley** [comment]
This looks to have changed some of the styles for the purchasable items in the Edit Avatar modal.

**Before**
image

**After**
image

**Comment by rholinshead** [comment]
Wow, good catch @Tressley. I had gone overboard with power unlocking everything that I forgot there were still the concept of locked options! Simple fix here was just to make sure the `locked` styles are still being applied correctly given the other style changes. I've added the fix and have a screenshot:
lockedoptionsstylefix

**Comment by SabreCat** [comment]
Thanks for this, @rholinshead! Between the couple of PRs of yours we're merging this week, I've awarded you Blacksmith tier 2! Congratulations!

**Pull request merged**
