### PR TITLE
Fix GET chat tests stopping execution of other tests in api-v3-groups branch

### PR DESCRIPTION
**Pull request by KristianTashkov**
Note: The travis CI is failing because of lint errors from the commit before me. We can rerun the tests once the lint errors are fixed.

### CODE REVIEW

**Comment by paglias** [comment]
@KristianTashkov thanks!

@crookedneighbor @TheHollidayInn @SabreCat there was a reason for this `.only` describe?

**Comment by paglias** [comment]
@KristianTashkov I'm sorry for the linting errors, they should be fixed now

**Comment by SabreCat** [comment]
D'oh, No, just my error.

**Comment by paglias** [comment]
@KristianTashkov I'm merging the PR right now, this will count toward a contributor tier! I'll need your User ID (Settings -> API on Habitica) to award id

**Comment by KristianTashkov** [comment]
Thanks :) It's bb8db09b-5822-4608-bba3-1486964b8537, do I have to give it in every PR?

**Comment by paglias** [comment]
@KristianTashkov if you can provide it in every PR it's better :)

**Comment by KristianTashkov** [comment]
@paglias I stumbled on this while making the fix for the basilist quest scroll giving code. I have some questions to ask you about the joinGroup code. Where is a good place to write to you/have a discussion?

**Comment by paglias** [comment]
@KristianTashkov if you have a Gmail account you can ping me on google chat at matteopagliazzi at gmail dot com

**Comment by TheHollidayInn** [comment]
Awkward, I was just about to post this :P

**Comment by TheHollidayInn** [comment]
Thanks for finding it!

**Pull request merged**
