### PR TITLE
Updating User API Doc (part 2)

### PR DESCRIPTION
**Pull request by madpink**
The issue: https://github.com/HabitRPG/habitica/issues/8087

I've updated the API documentation for the first batch if User

Includes: POST /api/v3/user/buy-gear/:key – POST /api/v3/user/change-class 

----
UUID: b0413351-405f-416f-8787-947ec1c85199

### CODE REVIEW

**Comment by Alys** [comment]
@madpink This is not your fault and is not strictly related to this PR (it's from a section already fixed in your previous PR), but could you please make this small change too? In the two lines below, `mpHeal` should be `mpheal` (all lower case):

https://github.com/HabitRPG/habitica/blob/b2225f05e52b026d6c476b999943bc9b8094f270/website/server/controllers/api-v3/user.js#L410

https://github.com/HabitRPG/habitica/blob/b2225f05e52b026d6c476b999943bc9b8094f270/website/server/controllers/api-v3/user.js#L422

**Comment by madpink** [comment]
@Alys mpHeal is now mpheal

**Comment by TheHollidayInn** [comment]
Look's good to me. Anyone have objections?

**Comment by paglias** [comment]
LGTM 👍

**Comment by TheHollidayInn** [comment]
Noted towards tier progress. Thank you!

**Comment by paglias** [comment]
@madpink the `gulp apidoc` command is erroring after these changes

```
remote:        [20:53:26] Starting 'apidoc'...
remote:        warn: parser plugin 'apibody' not found in block: 16
remote:        warn: parser plugin 'apibody' not found in block: 17
remote:        error: Empty parser result.
remote:        { File: 'website/server/controllers/api-v3/user.js',
remote:        Block: 18,
remote:        Element: '@apiParamExample',
remote:        Source: '@apiParamExample {URL} /api/v3/user/hatch/Dragon/CottonCandyPinkn' }
remote:        [20:53:26] 'apidoc' errored after 250 ms
remote:        [20:53:26] Error: There was a problem generating apiDoc documentation.
```

Can you give a look? Thanks

**Comment by madpink** [comment]
I think I found it, according to  https://github.com/apidoc/apidoc/issues/448 the APIDoc parser will fail if there is a space in a parameter, i.e. -  {URL } should be {URL}

I'm not sure what I should do to fix, I've already added the next batch of enhancements to user.js and submitted a new PR... should I just make the change there? Or should I try and make another fork to make the changes ASAP?

**Comment by TheHollidayInn** [comment]
Just make the changes in the new PR, please.

**Comment by madpink** [comment]
Actually, after looking at it again, I think I was mistaken, there is no space in {URL}

What I think is the case is that I should have put my example on a separate line, so it is erroring because it is looking for the example to begin on the next line but the next line is blank... (will fix in the new PR)

Does anyone see a flaw in my logic?

**Comment by Alys** [comment]
The `gulp apidoc` error has been fixed in https://github.com/HabitRPG/habitica/commit/7ee2f90f3716ce2c828c7d1385d0c8622accbe59

**Pull request merged**
