### PR TITLE
count how many users own specified gear with mongodb JavaScript

### PR DESCRIPTION
**Pull request by Alys**
@lefnire @lemoness @caffeinatedvee

This is related to the discussion in the Magical Fun-Times Dazzle Emporium, in which Lemoness said _"we do NOT have any info on things that people can get without purchasing, like the Unconventional Armor - and it would be fantastic to know how many people have that, especially if we could link it to time periods, because then we could know roughly how many people signed up post-conferences."_

This is a script designed to be run by lefnire in mongodb. It looks through all user accounts and tallies up the number of people who own a specific item (no information about specific people is produced; just total ownership numbers).

The array `itemsOfInterest` must contain the keys of the items to be counted. Currently it contains all of the [Unconventional Armor](http://habitrpg.wikia.com/wiki/Unconventional_Armor) and nothing else.

The totals are output in two formats: CSV for importing into a spreadsheet, and a more readable format. Sample output is below.

It is not possible to find out when each person obtained the gear (at least not from the mongodb data that I'm aware of). However, you could run this report after each convention to compare numbers with previous runs (hence the date field in the CSV data).

If you would like human-friendly names for the gear to be included instead of or as well as the keys (e.g., "Mighty Mask" instead of "headAccessory_special_wondercon_red"), tell me because I can do that easily enough. And I can make any other changes required. :)

Sample output:

```
CSV DATA:

"date","headAccessory_special_wondercon_red","headAccessory_special_wondercon_black","back_special_wondercon_black","back_special_wondercon_red","body_special_wondercon_red","body_special_wondercon_black","body_special_wondercon_gold"
"2014-08-17","5","4","3","3","3","3","3"

READABLE DATA:

2014-08-17
{
  "headAccessory_special_wondercon_red": 5,
  "headAccessory_special_wondercon_black": 4,
  "back_special_wondercon_black": 3,
  "back_special_wondercon_red": 3,
  "body_special_wondercon_red": 3,
  "body_special_wondercon_black": 3,
  "body_special_wondercon_gold": 3
}
```

### CODE REVIEW

**Comment by lemoness** [comment]
:D

**Comment by veeeeeee** [comment]
Thank you, Alys! (Incidentally, this is redphoenix. I know, I have a branding problem :grin:)

**Comment by Alys** [comment]
@veeeeeee : Ha! I was wondering why your name wasn't bolding the way the others do! I'm about to tag you in https://github.com/HabitRPG/habitrpg/issues/3801 too.

**Comment by lemoness** [comment]
This explains so much.

**Comment by lefnire** [comment]
downloading snap to local, will run and report back when done

**Comment by lefnire** [comment]
@Alys 

```
localhost:website lefnire$ mongo habitrpg ./database_reports/count_users_who_own_specified_gear.js
MongoDB shell version: 2.6.3
connecting to: habitrpg

CSV DATA:

"date","headAccessory_special_wondercon_red","headAccessory_special_wondercon_black","back_special_wondercon_black","back_special_wondercon_red","body_special_wondercon_red","body_special_wondercon_black","body_special_wondercon_gold"
"2014-08-26","241","241","242","241","242","241","241"

READABLE DATA:

2014-08-26
{
  "headAccessory_special_wondercon_red": 241,
  "headAccessory_special_wondercon_black": 241,
  "back_special_wondercon_black": 242,
  "back_special_wondercon_red": 241,
  "body_special_wondercon_red": 242,
  "body_special_wondercon_black": 241,
  "body_special_wondercon_gold": 241
}
```

**Comment by lefnire** [comment]
(did I do that right?)

**Comment by Alys** [comment]
Almost certainly. :) It's saying that 242 people have used the coupons, although one of those people has chosen to "buy" only two pieces of wondercon gear. @veeeeeee Does that number sound about right to you?

**Comment by veeeeeee** [comment]
@Alys That number seems abysmally low, given that we've handed out over 2000 codes....

**Comment by lemoness** [comment]
Ten percent success rate? Depressing but possible. We can keep an eye on
this post-PAX.

**Comment by Alys** [comment]
Maybe @lefnire did not run it correctly - has he used mongodb before? ;)

I don't know. The code's pretty basic with little room for bugs but 10% is disturbingly low. Is there anything in mongo that might stop the script iterating through all the users? Timeouts or anything?? Do you get the same data if you run it again?

**Comment by Alys** [comment]
Also I would be tempted to uncomment the "good for testing, bad for privacy" line and run it again, and then for the final user printed, examine their data to see if anything is glitchy there (or maybe examine the user immediately after them in the database, if find() uses a specific order). But first replace "user.auth.local.username" with "_id" - sorry, I don't know what I was thinking!

And @lefnire, don't show that "good for testing, bad for privacy" data to anyone apart from you. Which I know you wouldn't do but I'm including it here in case anyone reading this has privacy concerns.

**Comment by lefnire** [comment]
@Alys it went straight back to shell, completed just fine. Mongo's quite sensitive to errors, time-outs, etc (I usually have to rig a script 10x before it'll complete fully) this one ran smoothly.

**Comment by lemoness** [comment]
Question - would this work to let us see how many users have the Limited
Edition Spooky Skins? I would love to have that data, since it would help
us to decide how to handle them during the upcoming Fall Event.

**Comment by Alys** [comment]
It will do that pretty soon. :)

**Comment by lemoness** [comment]
<3 <3

**Comment by Alys** [comment]
New version of the script with Spooky Skins: https://github.com/HabitRPG/habitrpg/pull/3960

**Pull request merged**
