### PR TITLE
Updating User API Doc (part 3)

### PR DESCRIPTION
**Pull request by madpink**
The issue: https://github.com/HabitRPG/habitica/issues/8087

I've updated the API documentation for the third batch of User

Includes:  POST /api/v3/user/disable-classes – POST /api/v3/user/unlock

----
UUID: b0413351-405f-416f-8787-947ec1c85199

### CODE REVIEW

**Comment by madpink** [comment]
forgot to check for extraneous spaces again... oops

**Comment by madpink** [comment]
added update to Quest related to this from the original issue:

> Alys commented 13 minutes ago
> As reported by MrTyx (cbcf8442-3be2-4f36-9331-ba277555c08b) in the Aspiring Comrades guild:
> 
>  https://habitica.com/apidoc/#api-Quest-InviteToQuest Route is listed as https://habitica.com/api/v3/groups/:groupId/quests/invite but should be https://habitica.com/api/v3/groups/:groupId/quests/invite/:questKey
> Since the groups routes have already been done, someone could add this to a PR they're doing for other routes. Please comment here to say when you've done that so that we don't get duplicated PRs.

**Comment by librarianmage** [comment]
@madpink It appears that there is a merge conflict in user.js.

**Comment by madpink** [comment]
updated

**Comment by TheHollidayInn** [comment]
Looks good to me and docs compile locally

**Comment by TheHollidayInn** [comment]
Noted towards your tier!

**Pull request merged**
