### PR TITLE
fix(challengeItem.vue): guild name hidden caused by the fixed height

### LINKED ISSUE #11500: Guild name hidden by tags on challenge page
Maybe Steve Rogers @MaybeSteveRogers (767e5d92-0e13-4e30-acb1-d8bba62824fc): "(Long) guild name is hidden under tags on the challenge page - take a look:"

image

Confirmed in Google Chrome.

### PR DESCRIPTION
**Pull request by ShupingHe**
Fixes #11500

Changes:
remove the fixed height of the `.meta-info` container

### CODE REVIEW

**Comment by ShupingHe** [comment]
before:
image
after:
image

**Comment by paglias** [comment]
Thanks @Stevens1995 ! If you have an Habitica username or UUID I'll be happy to award you a contribution tier

**Comment by ShupingHe** [comment]
@paglias  
UUID: hb-4bemli1eejp5zmawv
thank you!
image

**Comment by paglias** [comment]
I'm  awarding your contributor tier.

Note that further tiers require increasing amounts of work from one to the next, so Tier 2 may require a couple of PRs or a larger PR to attain. But keep helping out and we'll express our gratitude accordingly!

**Pull request merged**
