### PR TITLE
Deduping completed tasks on load. closes #7708

### LINKED ISSUE #7708: Duplicate completed todos
### Description

Currently, if a user checks off a todo before loading the completed todos and then proceeds to load the completed todos, the task that the user has completed in the current session is duplicated under the done todos tab.

To replicate this bug:
1. Refresh the page
2. Complete a todo
3. Click Done tab under todos
4. Look for the todo that was completed, it should have two entries in the list.
#### Console Errors

None

### PR DESCRIPTION
**Pull request by Hus274**
#7708
### Changes

This will prevent the user from seeing duplicate completed tasks. This would happen if the user completed tasks locally before loading the completed tasks tab.

---

UUID: 2a4d30ee-4833-420e-be7c-ad6a6e261c5f

### CODE REVIEW

**Comment by paglias** [comment]
I think this is something we missed from your earlier PR. Instead of filtering duplicate tasks it isn't simpler and faster to just substitute all local completed todos with the ones from loaded from the server?

**Comment by Hus274** [comment]
I think this would have been a bug before that because I didn't change the default loading logic of loading completed todos and I didn't change the fact that non completed todos were saved locally and then completed.

Either way, I think that's a good call, just remove the completed todos from the list on a load from the server. I can update this and repost.

**Comment by crookedneighbor** [comment]
Can confirm, it was a bug from before.

**Comment by Hus274** [comment]
I've updated this to clear the local copy of completed messages before loading the completed messages from the server.

**Comment by crookedneighbor** [comment]
Notated toward your next tier.

**Pull request merged**
