### PR TITLE
Fix private message preview

### LINKED ISSUE #11027: markdown should be parsed in Private Message (PM) previews
As reported by @ravenlune (9272ab2c-4b66-4b74-aebd-799725885d1c):

"Markdown doesn't render in PM previews, when it does in the actual message being previewed."

image

I.e., markdown parsing needs to be done in the preview page on the left-hand side of the PM modal.

### PR DESCRIPTION
**Pull request by HydeHunter2**
Fixes #11027

### Changes
- Markdown is parsed in PM previews

Before | After
------------ | -------------
Github | Github 

----
UUID: af1477b6-509a-4611-b851-d7a8e3a9c02a

### CODE REVIEW

**Comment by HydeHunter2** [comment]
I didn't notice any ruining the design when using big elements

**Comment by paglias** [comment]
Thanks @HydeHunter2 

I think we had decided to only allow some tags in previews? cc @Tressley 

Also this doesn't work very well with some Markdown tags, for example if you send a gift to someone and the message is longer than 30 chars it won't display the correct formatting because the closing `might be after the 30 chars limit

Or with links /images 
Schermata 2019-04-27 alle 19 16 07
Schermata 2019-04-27 alle 19 16 39

But the code is fine 👍 

Let's wait for @Tressley 's opinion before merging this

**Comment by HydeHunter2** [comment]
Good. I think I can add a filter for some tags.
Just tell me what to filter.

**Comment by HydeHunter2** [comment]
@paglias , Is it a good solution to remove undesirable tags after parse markdown using `.replace('<h1>', '')` and regular expressions for links and images tags?

(As discussed in issue, there is a way to apply CSS, but I don’t know enough CSS to filter images, links and `<h_>` tags)

-----

> Also this doesn't work very well with some Markdown tags, for example if you send a gift to someone and the message is longer than 30 chars it won't display the correct formatting because the closing `might be after the 30 chars limit

My last commit fixes it.

**Comment by paglias** [comment]
> @paglias , Is it a good solution to remove undesirable tags after parse markdown using .replace('<h1>', '') and regular expressions for links and images tags?

Hmm I pretty sure the markdown library used under the hood by [habitica-markdown](https://github.com/HabitRPG/habitica-markdown), called [markdown-it](https://github.com/markdown-it/markdown-it) has a method to filter the tags to render

**Comment by Tressley** [comment]
Text should **not** be formatted in the preview column. H1-H6, italicized, bold, strikethrough, underlined text should all render the same styles. Lists should not have bullets and images should not be displayed. A message preview should only ever grow to accommodate two lines of a preview. This should give you a better idea of the styles:

image

@HydeHunter2 -- I can't remember if you're part of our Zeplin project, but if you aren't, can you leave an email for me to invite you? Zeplin is how we handle hand-off between designers and developers to better ensure one-to-one design.

**Comment by HydeHunter2** [comment]
Oops, I accidentally deleted the forked repository and I can't make changes to PR :confused:
So I close this PR and create a new one when I fix it, taking into account the Tressley's opinion.

@Tressley -- I'm not part of your Zeplin project. Could you invite me?
email: `hidemaide@gmail.com`

**Pull request closed without merging**
