### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Medaro**
Addressing https://github.com/lefnire/habitrpg/issues/1445

### CODE REVIEW

**Comment by lefnire** [comment]
sounds good. only issue i can see is users starting now will never reach the 91?

**Comment by paglias** [comment]
Another thing is someone has wolf Cerberus too and we should a) use ngif also for veteran wolf, b) unless new users can get rare pets, hide that section for them?

**Comment by Medaro** [comment]
it seems like we should ignore https://github.com/lefnire/habitrpg/issues/1445 
i picked it because it seemed like an easy bug but the count should stay as the amount a new user can get and have 91/90 or 92/90 pets would just be a 'bonus'

**Comment by lefnire** [comment]
let's close this one for now, until we can come up with a more elegant solution for handling both situations

**Pull request closed without merging**
