### PR TITLE
fix(ui): corrects crowding in drawer title that obstructs drawer toggle icon on mobile website

### LINKED ISSUE #13914: Issue with opening and closing the item drawer on smaller screens
On the mobile browser version of Habitica, the item drawer close icon is inaccessible due to tabs overlaying the control.

image

### PR DESCRIPTION
**Pull request by AlexKliger**
Fixes #13914

**Changes**
Currently, when viewing the drawer UI in the shop on mobile, the drawer tabs crowd and obstruct the toggle drawer icon. This occurs because styling for full-screen prevents the left side of the drawer from taking up available space. This pull adds an additional media query to the drawer component to make it more responsive on mobile.

Before
160884995-6dd6c86f-50c6-429e-996e-4a7b1a2df38d

After

----
UUID: 20dcb998-4ae9-4985-8b1d-d56c12479ec2

### CODE REVIEW

**Comment by AlexKliger** [comment]
I'm a first time contributor so the workflow for tests hasn't run automatically. Can an admin click the button to start it please?

**Comment by SabreCat** [comment]
Hi @AlexKliger, thanks for submitting this!

Would you be willing to do a little bit more style cleanup while you're touching this component?

* Center the "what does my pet like to eat" text and "you don't have any" bubble within the containing div
* Give "what does my pet like to eat" sufficient space to avoid wrapping with the default English text

**Comment by CuriousMagpie** [comment]
@SabreCat I've centered the error messages; the "what does my pet like to eat" wraps at sizes smaller than 430 px--I'm not sure how many mobile web users we have below that resolution.

**Comment by CuriousMagpie** [comment]
The Equipment drawer also has display issues at screens < 1241px, so I am adding that to the scope of this PR.

Screenshot 2024-10-31 at 4 14 02 PM

**Comment by veeeeeee** [comment]
Waiting for higher priority changes to finish out before moving this forward.

**Comment by SabreCat** [comment]
Merged in f6466b161be3dd4445b06fb3ba1444144d3f38bf

I'm sure you've long ago moved on, @AlexKliger, but I'll give you Blacksmith credit on the site anyway! thanks!

**Pull request closed without merging**
