### PR TITLE
Make it easier for people to find "how to contribute" wiki page

### PR DESCRIPTION
**Pull request by SabreCat**
Adding an additional link to the Player Tiers sidebar, for folks who want to jump straight to "how do I contribute?"

(Git n00b puzzlement about the extra commit there. Think that happened when I merged some of @paglias's changes into my local repo. But the changed file data looks correct.)

### CODE REVIEW

**Comment by paglias** [comment]
@SabreCat the extra commit is ok, it happens when you commit something and in the meantime another commit has been pushed on the repo

**Comment by SabreCat** [comment]
That's what I figured, thanks!

**Comment by SabreCat** [comment]
Whoops. Git stumble. Need to create a fresh branch for this one, closing for now.

**Comment by lefnire** [comment]
Extra commits merged from upstream changes are usually benign (and in this case, were indeed benign), but we'll all want to get into the habit of avoiding those by using `git rebase` on our feature branches, not `git merge` (see [Git Tips](http://habitrpg.wikia.com/wiki/Tips)). Reason being that _sometimes_ it can actually [cause issues](https://github.com/HabitRPG/habitrpg/pull/1558#issuecomment-25209580).

**Comment by SabreCat** [comment]
Yeah, I'm being super fastidious about starting from a clean branch with every PR, lest something weird like that happen.

**Pull request closed without merging**
