### PR TITLE
10653 Disables caching for requests done by axios

### LINKED ISSUE #10653: Daily checkboxes appear to roll back when using IE11 client
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: 90145e45-71ca-4c83-8ecf-703e40ccdcda
  * Browser: IE11
  * OS: Windows (presumably)

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

User reports the following flow:

1. Log in to Habitica using IE11.
2. Check off a Daily.
3. The Daily appears to uncheck itself--goes back to unchecked state.
4. Refresh or sync. The Daily is checked, suggesting that the server state is correct but the client displayed it incorrectly.

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

User is planning to check Developer Tools later--if we hear from them, we'll add the details here!

### PR DESCRIPTION
**Pull request by VickyKoblinski**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #10653

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

Added no-cache to axios setup. Let me know if this causes any problems, but I don't see a reason you'd ever want to cache the API response and I think that's all axios is being used for. Regardless, unless specifically told otherwise, Chrome and Firefox are not going cache anyways. So I don't think there are going to be issues here. 
img

This fixed a lot of other bugs I saw in IE, like with adding tasks, or refreshing the page, making Habitica unusable in IE. 

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 7d3f909a-a2f3-49ea-865f-ff1ec9fe174a

### CODE REVIEW

**Comment by paglias** [comment]
thanks @VickyKoblinski ! what about unmodified GET requests that would return a 304 HTTP code? For example two GET /user requests without the user being modified in between.

Also, is this a bug in ie 11 only or also in edge? If it's only IE11 I'd like to enable the no-cache option just for it and no other browsers by checking the user agent

**Comment by VickyKoblinski** [comment]
@paglias I'm going to guess it's just IE11, so I'll check and confirm and update the PR. 

I'm not sure how the server acts in the case of a would-be 304 and a no-cache header, but I'll look into it!

**Comment by VickyKoblinski** [comment]
@paglias I've updated the PR.

I mistakenly did the no-cache work on the front-end, so I moved it to the backend. The work might not be in the most optimal place, but it does fix the issue here. I'd love some help on cleaning this up though, and figuring out where it needs to be done. Because I've placed this code in the `authWithHeadersHandler` middleware that's called by `tasks/user` and `user`, it works there, but if I could move this up a layer to any request under `v4`, it'd fix some more bugs (for example, in IE, every time I refresh the page, I get prompted by the same "You unlocked a Check-In Prize!" modal). 

I also think `isIE` is a proper utility function that can be moved out and imported, but I don't know if there's a general place to do that. Maybe in a new file, `/libs/browser.js`?

So to reiterate: 
* Where's the best place for this code to go?
* It would be beneficial if this is middleware to all `/v4` GET requests
* `isIE` is a good utility function that could use a home, but I don't know where the best place for it is

**Comment by paglias** [comment]
@VickyKoblinski actually i think your initial fix on the client side was better, I don't think that we want special server side code for a browser that is quite out of date at this point

**Comment by VickyKoblinski** [comment]
@paglias Honestly, I'm not sure how my initial fix even worked. Sending a 'no-cache' header to the server is telling the server not to cache the result, not the client. Sending a 'no-cache' header to the client from the server is telling the client not to cache. So I think my initial fix was causing some side-effect that just so happened to also fix this problem. ¯\\_(ツ)_/¯ Or I'm just wrong.

Let me know if you want me to change it back anyways, with your suggestions.

**Comment by paglias** [comment]
@VickyKoblinski from your initial message I understood that the client side fix was working, I think adding a server side fix for ie11 is not something we want to do but if the client side one works I'll be happy to merge it!

**Comment by VickyKoblinski** [comment]
Okay, I'll roll back to that one! 👍 I'm on vacation right now, so when I get back next week I'll update this PR.

**Comment by paglias** [comment]
Hi @VickyKoblinski ! Any update on the status of this PR? thanks

**Comment by paglias** [comment]
I'm going to close this one @VickyKoblinski but if you want to work again on this just leave a message

**Pull request closed without merging**
