### PR TITLE
Add .gitattributes file fixes #9717

### LINKED ISSUE #9717: Windows - eslint error: Expected linebreaks to be 'LF' but found 'CRLF'
### General Info
  * OS: Windows

### Description
Hello,

Like explained in the guild, I have an issue with line endings on Windows. After following the instructions on the [wiki](http://habitica.wikia.com/wiki/Setting_up_Habitica_Locally#Windows_Line_Endings), I have an error about line endings (Expected linebreaks to be 'LF' but found 'CRLF') when I run the command `npm test`.

After some investigation, I have found where does this error come from. In fact, line endings on the repository are LF, but if git option core.autocrlf is true (like explained in the wiki), git will automatically convert line endings to CRLF on checkout. After that, eslint report errors because it is configured for unix line endings (LF) and it found windows line endings (CRLF).

### Possible solution

Nowdays, many editors detect line endings and add line endings corresponding to those found on the file. So without the option core.autocrlf (the default is false), when checking out the repository, a windows user will get files with LF. After that eslint will not complain about wrong line endings and the user can modify the code (his editor will add LF line endings).

To ensure, no CRLF line endings are pushed to the repository, we can add a .gitattributes file to the repository (like explained in the [eslint documentation](https://eslint.org/docs/rules/linebreak-style#using-this-rule-with-version-control-systems)).

### Console Errors
After running `npm test`: "Expected linebreaks to be 'LF' but found 'CRLF'"

### PR DESCRIPTION
**Pull request by Clement134**
Fixes #9717

### Changes
Add a .gitattributes file to ensure LF linebreaks are pushed to the repository.

### CODE REVIEW

**Comment by paglias** [comment]
Should this be applied to all (`*`) files or only to the `.js` ones? I fear this change will also apply to binary files (see https://stackoverflow.com/questions/9976986/force-lf-eol-in-git-repo-and-working-copy)

**Comment by SabreCat** [comment]
I can confirm--this causes PNG files to be modified upon checking out the branch. Can the file selection be made more intelligent? @Clement134 @paglias

**Comment by paglias** [comment]
We can make a list of extensions that should be affected by this. Not sure if there's a way to only target text files

**Comment by Clement134** [comment]
Effectively, I haven't thought about binary files.
In order to teach git what is a text file and what is a binary file, we can map files extensions to types, with this syntax:

`*.txt text`
`*.png binary`

If haven't forgotten anything, text files in this repo have the following extensions: js, yml, md, json, sh, vue, html, css, scss and svg whereas binary files have extensions: png, gif, ogg, mp3, ico, mp4 and zip.

**Comment by paglias** [comment]
that looks like a good list!

**Comment by Clement134** [comment]
I have added file type for each extension in gitattributes. It seems that the files of the press kit have bad line endings (CRLF), so I also commited those files with LF.

**Comment by paglias** [comment]
@SabreCat can you check if everything's good when checking out the latest changed? I'd like this to be merged if everything's ok

**Comment by paglias** [comment]
My only concern is what happens the moment we add a new extension? Can we instead whitelist text files and treat all the others as before? I think the list used here is quite extensive @Clement134

**Comment by TheHollidayInn** [comment]
What do you mean by whitelist text files?

**Comment by SabreCat** [comment]
@Clement134 Why are all those binary files included on the commit?

**Comment by SabreCat** [comment]
Oh, never mind, I see the commit now!

**Comment by paglias** [comment]
@TheHollidayInn nevermind, I think this is good to go

**Comment by TheHollidayInn** [comment]
Yea, this looks good to me. Im excited to have this help on windows :P

**Comment by SabreCat** [comment]
Thanks for this, @Clement134 ! Do you have a Habitica User ID (see https://habitica.com/user/settings/api)? If so, we can get you contributor credit!

**Comment by TheHollidayInn** [comment]
So double checking here. There are two more binaries that are being converted locally:
```
modified:   website/static/presskit/Habitica - Gamify Your Life.mp4
	modified:   website/static/presskit/presskit.zip
```

Are replacing this line endings correct for these?
Also, is there a reason they weren't commited in this PR? Maybe they were created after?

**Comment by SabreCat** [comment]
@TheHollidayInn: They were committed: https://github.com/HabitRPG/habitica/pull/9722/commits/6e4a95021ec157fed85bf0e295368807f2cd9fd2

**Comment by Clement134** [comment]
@SabreCat My user id is : ba6f458a-3fb2-43f5-8a30-904c029b90f4
@TheHollidayInn I have modified these two files on my last commit, because they had wrong line endings (CRLF)

**Comment by TheHollidayInn** [comment]
Ah weird. When Alys and I pulled the develop branch and rebased, the files were still using CRLF. So we were a little confused as to why. Can either of you confirm?

**Comment by SabreCat** [comment]
@Clement134 : Great! Welcome to the ranks of the Blacksmiths at tier 1. Note that further tiers require increasing amounts of effort from one to the next, so tier 2 may require multiple PRs or a larger PR to attain. But keep helping out and we'll express our gratitude accordingly!

@TheHollidayInn: Huh. I just pulled `develop` myself, and saw no files change... :\

**Comment by Alys** [comment]
The .gitattributes file was reverted temporarily in https://github.com/HabitRPG/habitica/commit/ccf8e0b3209d0184ce31f124af03af9ba975dc3e while we sort this out. This was the message I was seeing in my local install:
```
$ git diff upstream/develop
warning: CRLF will be replaced by LF in website/static/presskit/Habitica - Gamify Your Life.mp4.
The file will have its original line endings in your working directory.
warning: CRLF will be replaced by LF in website/static/presskit/presskit.zip.
The file will have its original line endings in your working directory.
```
It was followed by lines saying that those two files had been modified locally and they were appearing in `git status` as modified files. When I tried to revert them to unmodified, they'd modify themselves again immediately. If I tried to checkout a different branch, I couldn't because they were modified.

I'm in favour of using this .gitattributes file but we need to work out how to stop that happening otherwise we'll get those files being included in other PRs by mistake. If it's just something I need to do locally once to make it stop, that's fine but we should document it first in the [Setting up Habitica Locally](http://habitica.wikia.com/wiki/Setting_up_Habitica_Locally) page and put a note in Aspiring Blacksmiths.

**Comment by SabreCat** [comment]
@Alys I'm guessing we'll want to confirm that the files work correctly (i.e., can be viewed/unpacked without issue, in this case), and that they don't continue to be re-modified after committing. If those tests go OK, it should be all right.

**Comment by Alys** [comment]
Yes, no worries. If it's just a matter of doing one more commit to get them into develop in their modified state, that's an easy fix.

**Comment by Clement134** [comment]
I'm a little confuse about this issue.  If all my modifications are into develop, git should not complaints about CRLF in these two files :(

**Comment by Alys** [comment]
@Clement134 Yeah, that's what I thought too from looking through your changes. You did seem to have covered that. It was odd! We are still going to look into this and we do want the .gitattributes file to be used.

**Comment by SabreCat** [comment]
I'll give this a look now..

**Comment by SabreCat** [comment]
When I add `.gitattributes` back, I get some warnings of the style @Alys quotes above, but not those files--instead, they're recently added sprite images. And `git status` shows a clean working directory even then. Weird. Anyone else able to reproduce the trouble?

**Comment by Clement134** [comment]
It is very strange, on windows (with core.autocrlf=false) when I add the .gitattributes file on the develop branch, I have no warnings.

**Pull request merged**
