### PR TITLE
Additional translatable line for blurb placeholder

### PR DESCRIPTION
**Pull request by ghost**
Addressing my own https://github.com/HabitRPG/habitrpg/issues/2932

Screenshot before and after (the same):
http://oi60.tinypic.com/10nf9m1.jpg

Reason: "Blurb" is rather difficult to translate into some languages and keep it the same for both the heading and the placeholder. That's why we may want a separate translatable line for the placeholder.

Another thing is that this kind of placeholder may be not very welcoming in comparison to some other placeholders used recently (e.g. "Enter promo code" etc.). I would rather suggest something like "Please introduce yourself" etc. But I guess it's a separate topic for discussion and this commit doesn't limit such a change in the future.

### CODE REVIEW

**Comment by crookedneighbor** [comment]
Pinging @lemoness. I like the idea of making the placeholder "Please Introduce Yourself", or something similar. Thoughts?

**Comment by lemoness** [comment]
I like "Please introduce yourself!"

**Comment by crookedneighbor** [comment]
@GitHubSphinx Ping me when you've made the change and I'll merge it in.

**Comment by ghost** [comment]
Screenshot: http://oi62.tinypic.com/2n96df.jpg

@crookedneighbor Please excuse my amateur git-fu. It didn't allow me to push changes unless I synced the branch with upstream. And now there are 3 commits instead of just 1 (made translatable in 2 files + syncing in 0 files + wording in 1 file). Should I create a new branch instead?

**Comment by ghost** [comment]
Closed in favor of https://github.com/HabitRPG/habitrpg/pull/5318

**Pull request closed without merging**
