### PR TITLE
Fix lostMasterclasser achievement issue

### LINKED ISSUE #10398: lostMasterclasser achievement not given when earned ("Quest Completionist: Masterclasser Series")
Two players (cyberserpent 29492073-15fc-41fd-9c98-b0719f038859 and TriggeredTigger 5e680aae-08ee-4590-9aa7-efc8fc7906f3) from the same party (47957e88-2464-49ca-a3ef-e169d8754e2a) participated in the `lostMasterclasser4` quest but were not given the "Quest Completionist: Masterclasser Series" achievement (`achievements.lostMasterclasser`) even though they had completed all the other quests needed to gain it (I confirmed that from their quest achievement lists). A third participant (3afb41d6-7307-43f0-b0b6-82e8cea0d217) was given `achievements.lostMasterclasser`.

All three participants have the achievement for completing the lostMasterclasser4 quest (`achievements.quests.lostMasterclasser4`). cyberserpent has confirmed that this was the only time cyberserpent had completed that quest. I.e., the [finishQuest method](https://github.com/HabitRPG/habitica/blob/9194e8226d8fbee81f5238c722346acdbb14791e/website/server/models/group.js#L852) must have run to set `achievements.quests.lostMasterclasser4` to true for cyberserpent but the part of that method that sets `achievements.lostMasterclasser` to true did not run or was not successful.

Loggly has no relevant error messages for those three players' User IDs or for the party's ID.

Below are the quest start and end messages for lostMasterclasser4 for that party.

```
{
	"_id" : "029dad34-33a1-4d88-bfdb-d94926178e21",
	"flagCount" : 0,
	"flags" : { },
	"id" : "029dad34-33a1-4d88-bfdb-d94926178e21",
	"text" : "`Your quest, The Mystery of the Masterclassers, Part 4: The Lost Masterclasser, has started.`",
	"timestamp" : ISODate("2018-04-26T14:42:36.721Z"),
	"likes" : { },
	"uuid" : "system",
	"groupId" : "47957e88-2464-49ca-a3ef-e169d8754e2a",
	"_meta" : {
		"participatingMembers" : "29492073-15fc-41fd-9c98-b0719f038859, 3afb41d6-7307-43f0-b0b6-82e8cea0d217, 5e680aae-08ee-4590-9aa7-efc8fc7906f3"
	},
	"__v" : 0
}
```

```
{
	"_id" : "8de58406-9404-4d89-84e2-0dabd0cd0b19",
	"flagCount" : 0,
	"flags" : { },
	"id" : "8de58406-9404-4d89-84e2-0dabd0cd0b19",
	"text" : "`You defeated Anti'zinnya! Questing party members receive the rewards of victory.`",
	"timestamp" : ISODate("2018-05-18T16:01:03.453Z"),
	"likes" : { },
	"uuid" : "system",
	"groupId" : "47957e88-2464-49ca-a3ef-e169d8754e2a",
	"__v" : 0
}
```

I've set `achievements.lostMasterclasser` to true for cyberserpent and TriggeredTigger so the problem is fixed for them now.

### PR DESCRIPTION
**Pull request by Arsnael**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #10398

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
To fix this issue, I just run the updates regarding the quest completion first, then runs the extra ones in an other `Promises.all` for the achievement award. I also put back the related tests to it, as I think it was failing on Travis for the exact same reason (that I managed to reproduce on local too... achievement update running before quest completion update). It shouldn't fail anymore now.

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: bbffb2f4-9bf8-46c4-b749-523e2ca93ef6

### CODE REVIEW

**Comment by Alys** [comment]
Ha! Good point about the test. That solves THAT mystery. :)

**Comment by Arsnael** [comment]
@Alys Yes it does ! And thanks for the investigation work, was very detailed, saved me a lot of time :) 

I think the failed build with errors on travis is unrelated right? (and I saw comments on an other PR as well at the instant).

**Comment by Alys** [comment]
:smile: 

yes, you can ignore those subscribeCancel test failures. They're known and a fix is already in `develop`. No need for you to merge develop into this PR since there's no merge conflicts.

**Comment by SabreCat** [comment]
Thanks so much for this, @Arsnael, this has been quite the thorn in user support's collective side! Welcome to your second Blacksmith tier.

**Comment by Arsnael** [comment]
No problem, you're welcome :)

**Pull request merged**
