### PR TITLE
updated messageContent to include both the intro and body of the private message

### LINKED ISSUE #8397: gem gift message is missing most of the text
When a player sends gems to another player, the recipient is supposed to see an inbox message saying:

`Hello [recipient's name], [sender's name] has sent you 2 gems!`

For example:

image

However the message currently says only this:

`2 gems!`

For example (one of these has an optional message entered by the sender):

image

I.e., `Hello [recipient's name], [sender's name] has sent you` is no longer being inserted into the message. It should be.

### PR DESCRIPTION
**Pull request by Moniarchy**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #8397 

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

The full message is back! On another branch, `privateMessageGiftGemsMessage` was separated into two parts, `privateMessageGiftIntro`, which contains what was the missing text, and `privateMessageGiftGemsMessage`, which contains the number of gems only. Using the addition assignment, I added the `privateMessageGiftGemsMessage` to the content of the `privateMessageGiftIntro`.

screen shot 2017-01-30 at 6 03 50 pm

[//]: # (Put User ID in here - found in Settings -> API)

----
UUID:  a5c92777-91df-465d-9d0a-bd99d33c4692

### CODE REVIEW

**Comment by khipkin** [comment]
#8283 combined the intro and message strings to simplify the logic behind the message generation, but a bunch of strings were accidentally reverted in [this commit](https://github.com/HabitRPG/habitica/commit/ea24eeb0199a687115da0224b64b62c57629aea2#diff-040152bf2f4ce00a01ce5aa334f0851f). In order to restore the changes from #8283 rather than partially revert them, I suggest that the intended strings be restored instead of changing the string-building logic.

**Comment by Moniarchy** [comment]
@khipkin That was my first instinct but I assumed that the strings were separated purposefully--I'll get clarification next time. :) I'm going to update my PR. Also, noticed that the Travis CI check failed. I just reforked the repo last night and only made changes to the one file for my PR.

**Comment by lynxlynxlynx** [comment]
It's pointless to change the other language files, as they'll get overwritten anyway.
The test failure is not your fault.

**Comment by TheHollidayInn** [comment]
I'm pretty sure the messages need to be separated. The fix for this should be in the code not the locales.

**Comment by khipkin** [comment]
@TheHollidayInn It had already been decided in #8294 that the strings should be combined, so they were. The only problem is that the strings were then erroneously reverted in an unrelated commit.

_(edit: link to PR instead of issue)_

**Comment by TheHollidayInn** [comment]
Ah, okay. My mistake then - I should have read the issue.

**Comment by TheHollidayInn** [comment]
@Moniarchy This looks good. If you can remove the changes to all the local files except for the `en` file, we should be good to go.

**Comment by Moniarchy** [comment]
Will do!

**Comment by Moniarchy** [comment]
Also, for clarification, I should remove the changes to all of the local files except for American English and also should have the logic in the code for concatenating the intro and the message?

**Comment by lynxlynxlynx** [comment]
No, just cancel all the other locales, no code needs changing.

If you're working with git through command line, you can do something like:
git reset --soft HEAD^ # will uncommit your work, but not discard the changes
git commit  website/common/locales/en/groups.json 
git push -f thisbranch origin/missing-gem-gift-message

**Comment by Moniarchy** [comment]
Hopefully this looks right now.

**Comment by khipkin** [comment]
@Moniarchy Can you please test this and take a screenshot?

**Comment by Moniarchy** [comment]
screen shot 2017-02-06 at 3 55 33 pm

There was one failing test: 
`  1) GET /groups/:groupId/members supports using req.query.lastId to get more members:
     Error: timeout of 8000ms exceeded. Ensure the done() callback is being called in this test.`

@khipkin

**Comment by Alys** [comment]
I've tested this locally and it's all good! Thank you @Moniarchy.

I've awarded you your first tier. You can read more about [contributor tiers and rewards here](http://habitrpg.wikia.com/wiki/Contributor_Rewards).

Note that as your tier increases, it takes progressively more work to achieve the next one, so for the higher tiers, larger PRs or a few PRs are required. There's some information about that at Contributor Rewards, but feel free to ask here if you have questions!

**Pull request merged**
