### PR TITLE
Fixed #3756?

### LINKED ISSUE #3756: Missing space between count of Guild gems and label
The number of Guild Gems mashes into the word "Guild":

screenclip

### PR DESCRIPTION
**Pull request by skairunner**
It seems to be fixed, but I don't know the good development habits for
jade/whatever technology it is. Please comment & close if the fix is not
acceptable.

### CODE REVIEW

**Comment by deilann** [comment]
LGTM; don't worry about the build fail -- that's not you.

**Comment by deilann** [comment]
Aaand lvl++ UUID grabbed from the Tavern :)

**Comment by skairunner** [comment]
Cool, I didn't know there was such a thing :P

**Comment by deilann** [comment]
Yup! You are now the recipient of a shiny contributor tier! There are 7 in
total and they get harder to achieve as they go! The first one grants you 2
gems, your title, and a black tag, and then beyond that, you'll be able to
grab cool swag like contributor armor and climb the tiers!

And now I think I've run out of exclamation points for the day. Sigh.

I'm also Ryan by the bys, on Habit. I don't always understand things 100%,
but I try to take care of the small stuff, so co-founder and chief
Blacksmith Tyler (lefnire) can spend his time on the big fish.

**Pull request merged**
