### PR TITLE
Ticking all checkboxes will complete a Daily/To-do

### PR DESCRIPTION
**Pull request by cstyles**
When the user ticks the last checkbox for an as yet uncompleted Daily or To-do, the task will now automatically register as completed. The reverse logic (i.e., unchecking a checkbox resulting in "un-completing" the task) is not implemented because I couldn't figure out a good way to do it.

### CODE REVIEW

**Comment by Alys** [comment]
I'm not sure this is a good idea for a couple of reasons.

For To-Dos, when you tick off all the checklist items and then the To-Do itself, the XP (etc) that you get is multiplied by the number of checklist items PLUS one. E.g., for a To-Do with three checklist items, the XP is whatever you would normally get for the To-Do multiplied by 4. The To-Do itself is considered as if it's a fourth checklist item. Therefore ticking off the To-Do should be done manually because there might be a final action needed to complete the To-Do that isn't on the checklist. Not everyone will be using To-Dos like that (some might put ALL actions in the checklist and might want the To-Do to disappear when the checklist is finished), but other people will want the To-Do to remain unchecked.

There's also the situation where the player hasn't finished populating the To-Do's checklist. For a large project, you might add some checklist items, complete them, then need to add more before the project is finished.

For Dailies, the checklist items reduce damage if the Daily is not actioned completely. Ticking off all checklist items but not ticking off the Daily itself means that you (and your party members) take no damage but that you gain no rewards. This is an important mechanism for some situations. E.g., you have a Challenge daily that you can't action on a particular day because it's simply not appropriate for that day. You can use a checklist to ensure that you are not unfairly punished, and you don't tick off the Daily itself because you don't want to cheat in the Challenge.

It can sometimes be inconvenient to have to do the extra step of ticking off the Daily or To-Do manually when you've finished the checklist, but that extra step gives people flexibility in how they use those tasks.

**Comment by cstyles** [comment]
Firstly, there shouldn’t be any difference in Experience or Gold earned. My code calls `changeCheck` which is what is called when the user checks the larger checkbox. Unless I’m mistaken (which isn’t unthinkable), clicking on the final checkbox should, in essence, be the same as clicking the final checkbox and subsequently the larger checkbox.

Your points about unfinished To-Dos and using the larger text box as a “final check” are interesting cases that I hadn’t considered. I would be interested in knowing how many people use To-Dos in that manner. Personally, I have every important item as a subtask, making the extra click redundant (hence why I proposed this). But if a lot of people use them as such then I suppose this change would cause more harm than good. Also, if necessary I can add some code so that the task is only automatically marked complete if it’s a Daily (and not a To-Do).

Finally, for your point about Dailies, this could just be me but that seems to be the exception to the prevailing trend. Maybe my usage of HabitRPG is incredibly simplistic but I find myself checking the larger checkbox after completing every subtask much more often than not. Requiring everyone to click an extra time just to give users in a specific situation that option doesn’t strike me as the most elegant solution. Could a change be made to the Challenge system so that users don’t have to bother with checking every box? Perhaps a "skip this daily" button?

Also, the user can uncheck the larger checkbox to un-gain the Experience and Gold if they don’t want it. I don’t fully understand that mechanism so maybe that’s not a viable alternative but I thought it was worth mentioning.

Your last point about flexibility vs ease of use is really what this all comes down to. I believe this change would make the site easier to use for a lot of people. However, if there's a significant number of people who use tasks in the ways you mentioned then I suppose things should be kept the way they are.

**Comment by Alys** [comment]
Your code definitely won't change the Experience or Gold earned. I'm sorry I wasn't clear about the point I was making! The earnings for a To-Do are calculated as if the To-Do itself is an extra sub-item in addition to all of the sub-items in the checklist. For example, if a player would earn 1 GP for a To-Do with no checklist items, then that player would earn 4 GP for a To-Do with THREE checklist items (assuming the To-Dos have equal difficulty, age, etc). I.e., there is one "set" of earnings for each checklist item and then another "set" for the To-Do itself. From this point of view, ticking off the To-Do is a separate action to ticking off all the checklist items.

_"I would be interested in knowing how many people use To-Dos in that manner."_
I don't know how many, but I know that I do, so we have at least one person on each side of the debate. ;)

For anyone who does want to add additional To-Do checklist items after ticking off all the existing ones, having the To-Do become automatically completed is inconvenient. To uncomplete it, you have to scroll/jump to the bottom of the To-Do list, click the Complete tab, scroll back up until you find the To-Do, untick it, go back down to the bottom of the list, click the Remaining tag, then find the To-Do again. Compare that to the opposite case of needing to manually mark the To-Do as completed, which is just one click.

Also, if the user hadn't noticed that the To-Do had become completed (possible if they were very busy), then they might not realise that they needed to untick it until after it had become archived three days later (or, worse, until it had been removed sooner if they used the Delete Completed button to fix the sort order bug).

For Dailies, I have often seen people talk about using a checklist to avoid damage when they legitimately cannot do a Daily. There was one such comment in the Tavern yesterday. I believe it's commonly used by people who have chronic illnesses because there are often days when they are physically unable to do certain Dailies but are able to do others and so do not want to Rest in the Inn. The strategy is mentioned in [The Keep:Dealing with Variable Goals](http://habitrpg.wikia.com/wiki/The_Keep:Dealing_with_Variable_Goals#Exemptions) ("Exemptions" section) and in [Task List FAQ](http://habitrpg.wikia.com/wiki/Task_List_FAQ#How_can_I_reduce_penalties_on_sick_days_without_resting_in_the_Inn.3F) ("How can I reduce penalties on sick days without resting in the Inn?") 

_"Could a change be made to the Challenge system so that users don't have to bother with checking every box? Perhaps a "skip this daily" button?"_
Yes, that could certainly be done, but would only help with Challenge Dailies, not normal Dailies, unless it was applied to all Dailies of course, which has been suggested elsewhere and might be done in future. However it would take significant code to implement that so it's not something that can be done quickly.

_"for your point about Dailies... Requiring everyone to click an extra time just to give users in a specific situation that option doesn't strike me as the most elegant solution."_
You don't actually have to do the extra click for Dailies. When you have completed the final checklist item on a Daily, you can ignore the checklist box for that item and tick off the Daily itself. There is no penalty for leaving checklist items unticked when the Daily itself is ticked off. So, for Dailies, you can achieve exactly the effect you want (one less click) already, just by choosing to do your final click on the Daily not the checklist.

_"Also, the user can uncheck the larger checkbox to un-gain the Experience and Gold if they don't want it."_
That is true, but the XP and GP removed are never exactly the same as the amounts awarded (we do get people complaining about that occasionally) and it doesn't help if the user was given a drop when the daily was inappropriately marked as completed. Based on comments I've seen in the Tavern, there are some players who would be unhappy about receiving a drop they hadn't earned. Drops can be a strong motivator and inappropriate ones don't sit right with some players.

_"Your last point about flexibility vs ease of use is really what this all comes down to. I believe this change would make the site easier to use for a lot of people."_
I agree that it certainly would make the site easier to use for those players who don't want to add new checklist items to a To-Do after all existing ones had been completed and who don't consider the To-Do itself to be a separate sub-task. However that ease of use is offset by a significant decrease in flexibility for everyone else, for both To-Dos and Dailies. I don't know how many people are on each side, but I think having the flexibility is more important than trying to avoid the extra click when a To-Do has been completed.

**Comment by cstyles** [comment]
Thanks for linking me to those articles. It seems my use of HabitRPG _is_ pretty simplistic and I wasn’t considering the large number of ways other people might be using it.

_“You don't actually have to do the extra click for Dailies. When you have completed the final checklist item on a Daily, you can ignore the checklist box for that item and tick off the Daily itself. There is no penalty for leaving checklist items unticked when the Daily itself is ticked off. So, for Dailies, you can achieve exactly the effect you want (one less click) already, just by choosing to do your final click on the Daily not the checklist.”_
Thank you for pointing this out. I’ve always wondered if this was the case but I was afraid to test it out for fear of breaking my streak. With that in mind, auto-complete doesn’t seem necessary anymore. Although seeing a checklist with unchecked items will probably irk me enough that I’ll feel compelled to check the remaining items anyway.

At this point the only alternatives that I can see are A) creating a button which “skips” a daily, conferring no rewards nor penalties; or B) having an option in the settings somewhere that enables auto-complete for users who explicitly want it. I think the first option is more elegant than the current hack but, as you mentioned, it would be difficult to implement and I wouldn’t want to muck up the UI with buttons that a lot of people will likely never use. As for the second option, is it viable? If it is, I might look into implementing it if I have time. Otherwise, I guess we can close this.

**Comment by Alys** [comment]
Thanks for being so understanding about this!

Option A is something I've seen a few people ask about, and I would use it often. It would be like greying out the Daily for that day of the week, but ONLY for that week. I think a lot of people would find it very convenient. It's mentioned in the [Dailies Trello card](https://trello.com/c/q7uM2Ymq/92-dailies-v-2-hide-completed-hide-until-due-dailies-minimum-does-not-apply-button) ("Does-Not-Apply Button"). If you wanted to join that discussion and/or implement that feature, I am sure you would be welcome! The UI issue you mentioned is the only downside I can see, but perhaps if a "skip today" button was in the "Repeat" section or in "Advanced Options" it wouldn't get in the way, and others in Trello might have better ideas.

Option B troubles me. Site configuration options add complexity for both users and code, and (from a more selfish perspective) they make user support much harder. There'd be users who would select the option without understanding what it does or who would forget they had enabled it, and then they'd ask questions in the Tavern or GitHub about "missing" To-Dos. Different users would experience different behaviour for their tasks, and that would sometimes cause confusion, especially in the Tavern when users who aren't familiar with every aspect of the site are trying to help each other. Site options are good for the big, important things, but I think this one might be more trouble than it's worth. However, that is purely my opinion, based only on my own experience with user support, and others might legitimately disagree! If the current To-Do checklist behaviour is annoying for many people, this could be a good option. However if you are thinking of coding it, I would recommend first finding out what the staff think about it. I'm not sure if HabitRPG has a policy about minimising site-wide options. This might be something else that could be mentioned in Trello; there's a [To-Do card](https://trello.com/c/exaF7GiC/135-to-dos-v2-frozen-to-do-attack-to-do).

**Comment by cstyles** [comment]
I think your reasoning about option B is sound. I’ll take a look at the Trello board when I have time.

Should I close this or leave it open for further comment?

**Comment by Alys** [comment]
Probably best to close it so that the list of open items contains only active things. It can still be commented on by anyone when closed. I'll close it now since I'm here. :)

**Pull request closed without merging**
