### PR TITLE
Portuguese Translation Fixes

### PR DESCRIPTION
**Pull request by DanielTheBard**
User ID: 1f7c4a74-03a3-4b2c-b015-112d0acbd593

Checked through lines 1-24:
- Fixed general verb and noun mistakes
- Fixed a few words that were still in English
- Kept role-playing game in English. RPG's should be understood by Portuguese-speakers. 
- Pretty sure como makes more sense than conforme.
- Believe I fixed some improper use of the imperative form. Correct me if I'm wrong.
- Pluralized recompensas
- Changed Bem vindo to boas-vindas. Bem-vindo may be accurate though?
- Other general fixes that escape me.

Plan to do more.

### CODE REVIEW

**Comment by DanielTheBard** [comment]
What does it mean if the Travis CI Build failed? What should I do about that?

**Comment by paglias** [comment]
@DanielTheBard nothing to worry about, this branch has a lot of old code that isn't updated to the new site version

**Comment by DanielTheBard** [comment]
@paglias Alright, thanks!

**Comment by lefnire** [comment]
merged manually, stay tuned on translations

**Pull request closed without merging**
