### PR TITLE
Autocompletion of nicknames in chat

### PR DESCRIPTION
**Pull request by snicker**
Neat little feature, makes use of an angular directive here:
https://github.com/scarletsky/Angular-At-Directive

The styling could use a little help, but this is functional.

### CODE REVIEW

**Comment by lefnire** [comment]
This looks fantastic! Quick bit - it seems to add a pretty garly performance hit to chat ([comparison in action](https://s3.amazonaws.com/lefnirePublicFiles/at_performance.mp4)). But let's push it to beta anyway and see how it fares.

Edit: looks like `NODE_ENV=production` (aka, minified code) isn't liking At. Looking at your code, everything looks in order - so I think it's probably the At library not accounting for minified angular code

errors

**Comment by snicker** [comment]
I'm finding a few other issues with it, namely the "autofollow" feature is expecting that no parent elements are postion:relative... that's just a cosmetic thing, but the performance issues look very real. I'll see what fixes I can implement, but I may want to fork "At". This is the fun part of using other peoples' code ;)

**Comment by snicker** [comment]
It seems that the way to fix the performance issue is to prevent the entire lump of at-directive code from getting executed everytime there is a keystroke. The way we could do that is setting a 500ms timeout to ensure that the text hasn't changed... that way you're only calling the callback twice a second just to check a string equality, and the execution only happens if it hasn't changed in 500ms. We could, of course, play with that delay. 

I did fix the issue with the positioning of the list though. Fix comes in another pull request.

**Comment by lefnire** [comment]
Cool beans. Dunno if you saw the above screen, tis a crit which prevents page loading in production mode. Once that's fixed I'll merge the new PR, and we can hit beta with this to see how much an issue performance is for users

**Comment by snicker** [comment]
I did, how can I get the server to load in a production environment so
I can debug?

**Comment by lefnire** [comment]
ah yes, not obvious - sorry:
`./node_modules/.bin/grunt build:prod;NODE_ENV=production ./node_modules/.bin/grunt nodemon;`

**Comment by snicker** [comment]
Fixed in the new pull request https://github.com/HabitRPG/habitrpg/pull/1798, bower components will need to be updated but my new fork of the at directive supports minification properly.

**Pull request merged**
