### PR TITLE
add group by for hatchable sort

### LINKED ISSUE #11458: "Hatchable" sort mode does not act as expected
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

I would have expected that sorting the Stable by "Hatchable" would bring all the pets that I can currently hatch to the top of the list. Instead, it groups by species, which makes it not much different from "Standard" when you can hatch a number of different animals of the same color:

image

### PR DESCRIPTION
**Pull request by adamfitzgibbon**
[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #11458 

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
Adds a group by key for the hatchable filter. Previously it was defaulting to grouping by egg key which was causing the unintuitive sorting. Now it groups by whether the pet is hatchable, so the unhatchable pets are hidden behind the "Show More" button
Screen Shot 2019-10-22 at 11 16 13 PM

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 2d02f021-be7b-4be4-b20e-3488a00336c8

### CODE REVIEW

**Comment by adamfitzgibbon** [comment]
Looks like a couple tests failed. I'll check those out tomorrow.

**Comment by paglias** [comment]
thanks @adamfitzgibbon ! this is working well and will merge as soon as possible

**Comment by paglias** [comment]
thanks @adamfitzgibbon ! I've awarded a second tier for this and https://github.com/HabitRPG/habitica/pull/11416

**Comment by adamfitzgibbon** [comment]
much appreciated, @paglias!

**Pull request merged**
