### PR TITLE
Added tooltip to show chat time in date format with minutes and seconds

### LINKED ISSUE #4316: Show precise time of message on hover in chat
From @Alys in the Aspiring Coders Guild.

_@goldfndr, following on from the discussion in github, you can see exact timestamps for party chat messages through the API if you want to - try the "groups" set of commands; there's something there about fetching a group's data, and "party" can be used as a group ID.
I like the idea of being able to see more precise times in party chat - perhaps when you hover over the vague time you then see the precise time? I think seeing precise times all the time would be more distracting than useful. "3 days ago" does give you a good sense of roughly how far back you are, without you needing to perform any mental arithmetic with dates. :) But what do you think? These are just my initial thoughts._

Thought that was a good idea, so I'm bringing it here for discussion.

### PR DESCRIPTION
**Pull request by crookedneighbor**
Closes #4316

@Alys since you came up with this idea, do you approve of my implementation? I thought a tooltip worked best for it.

### CODE REVIEW

**Comment by Alys** [comment]
Can you add a screenshot? If you still have your local install running?

**Comment by crookedneighbor** [comment]
Ha! How silly of me. Of course:
screen shot 2014-12-03 at 4 38 08 pm

That's what I get for opening a pr within half an hour of waking up.

I just used one of Angular's built in date filters.

**Comment by Alys** [comment]
I like it! Thank you!

**Comment by crookedneighbor** [comment]
Awesome, going to merge it in then.

**Pull request merged**
