### PR TITLE
Fix Footer layout gets messed up in mobile view

### LINKED ISSUE #12549: Footer layout gets messed up in mobile view
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: af292e10-b7c0-4a9b-866a-af13868920ba
  * Browser: Google Chrome
  * OS: Windows

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
Footer Bug Mobile View

Footer Layout becomes messy in mobile view and donate button touches upper paragraph. Privacy policy and terms and conditions gets messed up due to their alignment. This issue can be fixed by changing their alignment to center.  
Sir, please assign me this issue i will fix it asap.

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

### PR DESCRIPTION
**Pull request by VipulKhandelwal1999**
[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #12549 

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
Fixed footer layout in mobile view.

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: af292e10-b7c0-4a9b-866a-af13868920ba

### CODE REVIEW

**Comment by VipulKhandelwal1999** [comment]
@paglias How much time does it take to get PR accepted?

**Comment by paglias** [comment]
Usually PRs are reviewed once per week and merged once per week if they don't have any problem but last week was Thanksgiving in the US and we skipped one week.

**Comment by VipulKhandelwal1999** [comment]
Ok :)

**Comment by paglias** [comment]
Also it looks like the PR here has some extraneous commits from the skills one

**Comment by VipulKhandelwal1999** [comment]
@paglias Now as you can see the test failed not because of my commit. I have made another branch and I have fetch everything from upstream and then I have only change footer but test failed due to something else.

**Comment by VipulKhandelwal1999** [comment]
> Also it looks like the PR here has some extraneous commits from the skills one

@paglias Please guide me. I don't know what to do in this situation.

**Comment by paglias** [comment]
@VipulKhandelwal1999 The issue seems to come from the fact that you developed your skills pr in the `develop` branch, then pulled from upstream and merged into this one. I'd suggest you either wait for a pr to be merged before making a new one, read some guide on how git work and how to avoid this issues or use a GUI to manage your git repository. Unfortunately I can't really help you with this

**Comment by VipulKhandelwal1999** [comment]
> @VipulKhandelwal1999 The issue seems to come from the fact that you developed your skills pr in the `develop` branch, then pulled from upstream and merged into this one. I'd suggest you either wait for a pr to be merged before making a new one, read some guide on how git work and how to avoid this issues or use a GUI to manage your git repository. Unfortunately I can't really help you with this

Ok, I will wait.

**Pull request closed without merging**
