### PR TITLE
Allow lastpass users to autofill their credentials

### PR DESCRIPTION
**Pull request by DanielHeath**
Addresses https://github.com/HabitRPG/habitrpg/issues/1246

### CODE REVIEW

**Comment by lefnire** [comment]
thanks @DanielHeath , pushing to beta.habitrpg.com now if you wanna give it a gander. what's your uuid for contrib.lvl?

**Comment by DanielHeath** [comment]
Userid is fc72d2b8-5609-4e33-bea3-36944bba879c

**Comment by lefnire** [comment]
√

**Comment by DanielHeath** [comment]
Autofill is now working with lastpass v3

**Pull request merged**
