### PR TITLE
Fix habit streak display issue

### LINKED ISSUE #13749: Negative habits don't display 0 correctly
### General Info
  * UUID: 7c94e21b-8ff2-44a7-a5f1-cfdef807a5f5
  * Browser: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/96.0.4664.110 Safari/537.36
  * OS: Windows

### Description
From user: 

> I have a negative habit defined, with no positive equivalent defined. I have not touched it for about a month, and it is showing "-0" instead of just zero. I understand that this probably has a minus because it is a bad habit but "-0" just looks weird/confusing because zero is not positive or negative, it is just zero.

streak-counter-negative

I checked the user's value for this habit in the database and it is currently 0.

A fix for this would remove the minus symbol from the streak if the value is equal to 0.

### PR DESCRIPTION
**Pull request by ouroboran**
[//]: # (Note: See https://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #13749 

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

If the habit is either only positive or negative and if the streak is 0, hide '+'/'-' symbol.

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 61067b58-2b1c-46d0-8ea8-1fb71d734b98

### CODE REVIEW

**Comment by SabreCat** [comment]
This fix looks like it works--I just want to check with our UX folks to confirm this is actually a change we want to make.

**Comment by Tressley** [comment]
@ouroboran -- Thanks for your work on this! I'd actually like to build on this a bit to improve the UX.

Habits that are positive `and` negative are the only state that should display "+/-". This is to help differentiate the positive and negative counters.

If a Habit is positive `or` negative, it should display the counter value without "+" or "-". For a Habit like this the differentiator isn't necessary since there's only one value.

**Comment by SabreCat** [comment]
Ok, thanks for the update @Tressley!
@ouroboran so we want to expand the fix to apply to single-direction Habits at all times, not just when the counter is exactly 0.

**Comment by KrSkander** [comment]
Hey guys @SabreCat and @Tressley, can I take this issue if there is no response ?
I already made a pull request that fixed this issue as you guys have described but as the issue wasn't assigned to me it was closed. 
the pull request number 13793, I can recreate the pull request at any moment, so let me know guys.

**Comment by SabreCat** [comment]
@KrSkander Sure, it looks like @ouroboran might be too busy to take this over the finish line-- if you want to create a PR with the implementation Tressley suggested above, go for it!

**Comment by KrSkander** [comment]
@SabreCat I already have the fix for the first case in Tressley's suggestion, Should I create the pull then update it with the second case or do both at once and create the pull ?

**Comment by CuriousMagpie** [comment]
@KrSkander I went ahead and assigned the issue to you. Thanks!

**Comment by KrSkander** [comment]
@CuriousMagpie Thanks ! I already made a pull request yesterday with the updated solution waiting for its review. Pull request #13947

**Comment by SabreCat** [comment]
Closing this as abandoned, looks like ouroboran has moved on and KrSkander will wrap it up.

**Pull request closed without merging**
