### PR TITLE
Removed unnecessary "Equipment" sub-heading in Market.

### LINKED ISSUE #11232: unnecessary Equipment sub-heading in Market
As reported by @ieahleen (c073342f-4a65-4a13-9ffd-9e7fa5410d6b):

"In the Market there is an Equipment sub-header in the Items section, below Food and Saddles and above Cards, I don't think it should be there:"

scr

### PR DESCRIPTION
**Pull request by Scens**
[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #11232 

### Changes
Zrzut ekranu 2019-06-18 o 17 02 44

[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: dd59e7c1-b76a-466e-b301-783b852da699

### CODE REVIEW

**Comment by Alys** [comment]
@Scens Thanks for looking into this! 

Can you confirm that removing equipment from the categories array doesn't have any other effects? For example, does the Equipment section still appear at the top of the Market page and does the equipment filter checkbox in the left-hand column still work?

Those are just a couple of examples to check. Have a look for every place in the code that the category array is used to see if there's anything else that might be affected. :)

**Comment by Alys** [comment]
Those are just a couple of examples to check. Have a look for every place in the code that the category array is used to see if there's anything else that might be affected. :)

**Comment by Scens** [comment]
> @Scens Thanks for looking into this!
> 
> Can you confirm that removing equipment from the categories array doesn't have any other effects? For example, does the Equipment section still appear at the top of the Market page and does the equipment filter checkbox in the left-hand column still work?
> 
> Those are just a couple of examples to check. Have a look for every place in the code that the category array is used to see if there's anything else that might be affected. :)

I've checked it at found out that the filter doesn't work - now it works :).
The issue was that the same array was used to create filters and the actual rows/components to be filtered.

The fact that the EquipmentSection component is not a generated category has complicated the matter. 
Screenshot 2019-06-19 at 22 49 02

Someone has tried to solve it by adding to category array "helper category" with "Equipment" text, so it displays in filter and added some ifs to the EquipmentSection. But then it also displays as a new CategoryRow, hence the topic of this issue.
Now viewOptions (previously used only to create filter checks) keeps additional info about text to be displayed in filter and the categories array is no longer passed to the filter component.

But I don't know why do coverage checks fail. Could you explain it to me?

**Comment by paglias** [comment]
thanks @Scens ! the PR seems to be working well

**Comment by paglias** [comment]
@Scens  thanks for this! I'm merging the PR and awarding your contributor tier.

Note that further tiers require increasing amounts of work from one to the next, so Tier 2 may require a couple of PRs or a larger PR to attain. But keep helping out and we'll express our gratitude accordingly!

**Pull request merged**
