### PR TITLE
two typos in questsContent

### PR DESCRIPTION
**Pull request by andrewschultz**
First time pull requester.

* added apostrophe to isnt
* unfazed is correct spelling of unphased

I hope this isn't too trivial, but I wanted to start small before doing anything breakable. Let me know if there are other files in the repo with lots of game text that may need proofreading...it's something I'm good at.

### CODE REVIEW

**Review by SabreCat — APPROVED** [review]

**Comment by SabreCat** [comment]
@andrewschultz This looks great! If you want to hunt typos, anything in `website/common/locales/en/` is fair game. What's your User ID from https://habitica.com/#/options/settings/api ? Let me know and I can credit you for your help!

**Comment by andrewschultz** [comment]
@SabreCat thanks! I appreciate it. I thought I'd need to do more to get the recognition, but I still want to do more. So it's nice to have other files to look at, too. 

For future PRs, what is a good # of typos per PR, so that it's not too trivial, but also so I won't throw too much at you at once?

And would you rather I send stuff in on a by-file basis e.g. send 3 files per PR? Or would it make sense to divide them up by type e.g. acronyms that should be capitalized?

Whatever works best for you works for me.

Oh, I am Kruncho in-game.

**Comment by SabreCat** [comment]
@andrewschultz Typically we give people contributor credit for their first PR regardless of scope, because that can represent a fair amount of setup effort (GitHub account if you didn't have one already, cloning the repo, getting a local instance running...) and we want first-time contributors to be eager to jump in! Further tiers require more effort, though. So welcome to Blacksmith tier 1!

Number of typos per PR: doesn't particularly matter. Even if there were a hundred edits in a PR, we'd still be able to review it without too much difficulty (I've got a bit of proofreading background myself too, ha).

Grouping: Definitely by file. Multiple PRs modifying the same file adds overhead resolving conflicts.

**Comment by andrewschultz** [comment]
Belated thanks for the reply! I'm organizing stuff now. Nothing huge and, hopefully, nothing too pedantic.

Is it better to ask future questions about what/how to report in the Aspiring Blacksmiths tavern, or is here okay/preferred?

**Comment by SabreCat** [comment]
Aspiring Blacksmiths is good for general questions, whereas comments on an issue ticket or in-progress pull request are better for nitty-gritty specific things!

**Pull request merged**
