### PR TITLE
Updated hatching tooltip language in all English instances.

### LINKED ISSUE #11613: "Click the paw print to hatch" appears even when the icon is not a paw print
> @Cleminou (2153e659-6b03-4dbd-b0a3-281b4e29c537): "I'm not sure if this is the good place to mention it, but I just noticed that in the stable, when trying to hatch a pet for an already unlocked mount, the text 'Click the paw print to hatch' appears even if the icon is an hatching potion with an egg."

It's correct that this appears and might be a bit confusing.

### PR DESCRIPTION
**Pull request by oakypokey**
[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #11613 

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
Modified locale files to remove confusing language from the tool tip when hatching a discovered type in the stable. Changed "Click the paw print to..." to "Click the button to" so that it made sense.

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: bdf85c2b-391c-42cd-8d98-2d39a846aebc

### CODE REVIEW

**Comment by Alys** [comment]
The icon that you click on won't really look like a button (it's either a pawprint or a greyed-out pet or an egg+potion pair), so the "Click to hatch!" phrase (from https://github.com/HabitRPG/habitica/issues/11613#issuecomment-598295202) is probably better than  "Click the button to hatch."

You just need to edit the locales/en/ file. The other languages are handled through Weblate. :) See the _README_FIRST.md file in those directories for details.

**Comment by oakypokey** [comment]
Sweet, I got rid of the changes to the other files and just changed the locales/en/ file. Thanks for the heads up about the Read Me files :)

**Review by paglias — COMMENTED** [review]
sorry for the delay @oakypokey but it looks like changes to some locales remained

**Comment by oakypokey** [comment]
I think I fixed it @paglias ? Sorry for the trouble!!

**Comment by paglias** [comment]
looks good @oakypokey , no worries and thanks for the PR!

I'm merging the PR and awarding your contributor tier.

Note that further tiers require increasing amounts of work from one to the next, so Tier 2 may require a couple of PRs or a larger PR to attain. But keep helping out and we'll express our gratitude accordingly!

**Pull request merged**
