### PR TITLE
Fix task advanced settings display (fixes #5408)

### LINKED ISSUE #5408: "Advanced Options in tasks start collapsed" does not work
Under Settings -> Site, there is a checkbox labelled "Advanced Options in tasks start collapsed". From memory, this used to work: if the box was unticked, then whenever you opened a task for editing, the Advanced Options would already be open. If you ticked the checkbox, then the Advanced Options would be closed by default. 

However now, Advanced Options is always closed, regardless of the state of that checkbox.

### PR DESCRIPTION
**Pull request by hairlessbear**
Negates `User.user.preferences.advancedCollapsed` so the toggle on the settings page properly controls whether the task advanced settings display.

### CODE REVIEW

**Comment by crookedneighbor** [comment]
Going to want a test around this :smile:

**Comment by crookedneighbor** [comment]
Directive scan be pretty tricky to test, so I'll take care of it. I need to make the test file for another PR anyway.

**Comment by hairlessbear** [comment]
Thanks @crookedneighbor. I just started a `mocha` tutorial, so hopefully I'll be able to write tests of my own in the near future. Other than `mocha`, is there anything else you'd suggest I look into to better understand HabitRPG's testing environment?

**Comment by crookedneighbor** [comment]
Merged in with: https://github.com/HabitRPG/habitrpg/commit/685c09aa0d4b17fb8aca833349fdd4c739519b11

Notated.

**Pull request closed without merging**
