### PR TITLE
Upgrade to NPM Amplitude package

### PR DESCRIPTION
**Pull request by SabreCat**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

The existing client SDK for Amplitude analytics is being sunset soon. This PR adds the `amplitude-js` NPM package so we can use that instead of the old script, currently fetched inline.

### CODE REVIEW

**Comment by paglias** [comment]
@SabreCat looks good, I'd just check that calling `amplitude.logEvent` works fine because here https://amplitude.zendesk.com/hc/en-us/articles/115001361248-JavaScript-SDK-Installation#tracking-events and here https://amplitude.zendesk.com/hc/en-us/articles/115002889587#class-amplitude it seems that first you have a to create an instance with `amplitude.getInstance()` and then use the returned object to log events, ... but I'm not sure

**Comment by paglias** [comment]
just a reminder that this needs to go live before Jan 31st

**Comment by SabreCat** [comment]
Tested on Delta, confirmed events and user properties are coming through OK there. Will see how automated tests go, next--might need to update the syntax there as well.

**Comment by SabreCat** [comment]
This is... a very strange way for the tests to fail. 🤔 Investigating tho...

**Pull request merged**
