### PR TITLE
New Copy

### PR DESCRIPTION
**Pull request by deilann**
Okay, I seriously have no idea why I can't separate it from Cole's.

### CODE REVIEW

**Comment by ghost** [comment]
Because Cole's commit is in the branch you're issuing the PR from. You have to remove that commit somehow to get it out of your PR. Any commits in your branch that aren't in the branch you're PRing against  automatically get included in your PR.

**Comment by deilann** [comment]
Yeah, I'm trying to figure out where that commit _isn't_. I created the
branch from master, and develop had the same issue. I'll figure it out
later today.

**Comment by ghost** [comment]
This should solve your problem:

```
git reset b4cb3e4c78e832d3694c5331feb8b6d6c5cc5abe
git checkout public/js/controllers/groupsCtrl.js
git commit -a -m "new copy"
git push -f
```

Also, it looks like the commit you're having trouble with is in `master`, which means you probably merged that in at some point or else branched from it. You'll want to base your branches off of `develop` instead, as I understand it.

**Comment by deilann** [comment]
Ahahaha. Okay. Thank you so much. I have never worked on a project of this
scope, so I've never run into these issues.

**Pull request closed without merging**
