### PR TITLE
Add .idea and .git to nodemon ignore list

### PR DESCRIPTION
**Pull request by SabreCat**
Dramatically reduces unnecessary server bounces during development.

### CODE REVIEW

**Comment by SabreCat** [comment]
Aw shoot, you got to it just too fast for me. See 9cdf5678728a2dfa31990428902ada7492c12767, I think that's more efficacious. (Or will the gruntfile create the nodemonignore? It wasn't doing so for me locally)

**Comment by lefnire** [comment]
actually, I'm not sure... @paglias?

**Comment by paglias** [comment]
Using a .nodemonignore or Gruntfile configuration should be the same. https://github.com/ChrisWren/grunt-nodemon

I don't think, anyway, that adding .git and .idea should solve anything, by default nodemon should only watch for js and coffee files.

Can you post a screenshot of the message sent when the app reloads?

**Comment by SabreCat** [comment]
Making a trivial edit to stats.jade.

With `.idea*` and `.git*` in .nodemonignore:

screenclip

Terminate grunt-nodemon process. Revert file. Remove `.idea*` and `.git*` from nodemonignore. Restart `grunt run:dev` and make identical edit:

screenclip

In fact that first restart at 07:18:56 hit before I actually changed anything! It didn't even make it to connecting with Mongoose before it bounced.

**Comment by paglias** [comment]
Strange... then it's ok to commit this

2013/12/30 Sabe Jones notifications@github.com

> Making a trivial edit to stats.jade.
> 
> With .idea\* and .git\* in .nodemonignore:
> 
> [image: screenclip]https://f.cloud.github.com/assets/4501321/1822174/bc96165a-7154-11e3-964c-b4f3359d3e15.png
> 
> Terminate grunt-nodemon process. Revert file. Remove .idea\* and .git*from nodemonignore. Make identical edit:
> 
> [image: screenclip]https://f.cloud.github.com/assets/4501321/1822181/0f11fd68-7155-11e3-947b-27147183bb53.png
> 
> In fact that first restart at 07:18:56 hit before I actually changed
> anything! It didn't even make it to connecting with Mongoose before it
> bounced.
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/pull/2173#issuecomment-31345356
> .

## 

Matteo Pagliazzi - paglias.net

**Comment by SabreCat** [comment]
Done!

**Pull request merged**
