### PR TITLE
tests(api): Fix test name to use proper English

### PR DESCRIPTION
**Pull request by TayHobbs**
I am looking at starting to try to contribute to Habitica because I am a huge fan of the site. I was looking through the code to see if there was anywhere I could help improve test coverage and I noticed this typo. I thought it would be an appropriate first pull request.

Does anyone have advice for what I could contribute next? Tests, enhancements, bug fixes or otherwise?

Thank you

### CODE REVIEW

**Comment by crookedneighbor** [comment]
Seams reasonable to me, except that the commit message should be prefixed with `tests(e2e)`

**Comment by TayHobbs** [comment]
@crookedneighbor I have updated the commit message

**Comment by crookedneighbor** [comment]
This will count towards a contributor tier! What's your User ID? You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api). Be sure to only copy the User ID and _not_ your API Token.

**Comment by TayHobbs** [comment]
@crookedneighbor My user id is: 39392482-e8e9-468f-a076-3c4bd0256579  Thank you!

**Comment by TayHobbs** [comment]
@crookedneighbor I never received my contributor tier, does this take time to show up?

**Comment by crookedneighbor** [comment]
Sorry about that, got busy this week and forgot to do it. I've awarded it for you now, thanks for following up!

You can read more about [contributor tiers and rewards here](http://habitrpg.wikia.com/wiki/Contributor_Rewards).

Note that as your tier increases, it takes progressively more work to achieve the next one, so for the higher tiers, larger PRs or a few PRs are required. There's some information about that at Contributor Rewards, but feel free to ask here if you have questions!

**Pull request merged**
