### PR TITLE
New skin tones

### PR DESCRIPTION
**Pull request by Shaners**
## https://github.com/HabitRPG/habitrpg-shared/pull/22 <strong>must</strong> be completed before this will work.

Adds 3 new skin tones options for each body type. Adds adjustment to shirt option boxes making them smaller and more in line with the rest of the options.

### CODE REVIEW

**Comment by lefnire** [comment]
I'm going to go ahead and merge this, since the beta users (#develop) are already under the assumption that what they're using is ahead-of-the-curve, they shouldn't be too shocked that it's not on mobile. 

@Shaners could you add this to habitrpg-mobile too? I'll do a release to iOS, wait for their approval (takes a couple weeks), then release to everything else with a bailey.

**Comment by Shaners** [comment]
@lefnire where is habitrpg-mobile? Sorry if it's obvious...

**Comment by paglias** [comment]
It's at https://github.com/HabitRPG/habitrpg-mobile
Il 07/ott/2013 18:19 "Shane Lister" notifications@github.com ha scritto:

**Comment by Shaners** [comment]
Ah yes, thanks @paglias !

**Pull request merged**
