### PR TITLE
edited gem infor popup in response to issue #3228 (english only)

### PR DESCRIPTION
**Pull request by Verabird**
Iss #3228 requested that it be made clear in the hover text that gems cost real money. I only speak english well, so I changed it in the english files.

### CODE REVIEW

**Comment by paglias** [comment]
Translations for anything else than plain English (not en_GB) are handled
on transifex not here. Could you revert the pr to keep only en files?
Il 24/ago/2014 17:31 "Verabird" notifications@github.com ha scritto:

**Comment by Verabird** [comment]
thanks for the info. i will fix asap

**Comment by Verabird** [comment]
@paglias I'm very new to git, and I don't know if I did this right. I tried to back up to the previous commit and redo this commit.

**Comment by paglias** [comment]
Oh... You should edit the file in the habitrpg-shared repo directly... Sorry I didn't notice that before

**Pull request merged**
