### PR TITLE
Salt spell doesn't check to see if you have enough Gold #4454

### PR DESCRIPTION
**Pull request by melissamcewen**
add check to see if spell is salt, but we might want to check value in general if we plan to use this kind of thing a lot...or maybe just check it for special spells?

### CODE REVIEW

**Comment by lemoness** [comment]
It's worth noting that eventually I'd like to have this type of spell for
at least every season (since we already have Fall and Winter), so it's
probably helpful to make it easy to generalize.

**Comment by crookedneighbor** [comment]
Does the same thing happen with the opaque potion for spooky sparkles?

**Comment by melissamcewen** [comment]
How do I access the variable above the name of the spell that classifies it as special so I can check for that?

**Comment by Alys** [comment]
What might be better is a check to see if spell.value exists and if it does, then compare to gold. Value in a skill would always be the GP cost and any skill that didn't cost gold would never have a value.

**Comment by melissamcewen** [comment]
Thanks @Alys that's a great idea, hopefully I did it right

**Comment by crookedneighbor** [comment]
This is great, except that snowballs and spooky sparkles each have a value of 15, and that means that if you try to cast snowball or spooky sparkles with less than 15 gold, it won't let you, even though you have plenty of snowballs/sparkles in your inventory.

It might be better to give the salt, opaque potion, and the new years eve card a unique attribute, something that would indicate that they are cast upon purchase, like `immediateUse: true` in https://github.com/HabitRPG/habitrpg-shared/blob/develop/script/content.coffee#L662-L670

Then your check could be `if (spell.immediateUse && User.user.stats.gp < spell.value)`.

**Comment by crookedneighbor** [comment]
@melissamcewen If you're comfortable working in the [habitrpg-shared](https://github.com/HabitRPG/habitrpg-shared), go ahead and make the change. I'd put it right under the value attribute for each of those "spells".

If you're not, we can tag team this and I'll make the adjustment after you adjust this PR.

**Comment by melissamcewen** [comment]
Thanks @crookedneighbor I made the changes but hadn't worked with the shared repo before so I wasn't sure if you wanted the complied JS or just the coffeescript
https://github.com/HabitRPG/habitrpg-shared/pull/429

**Comment by crookedneighbor** [comment]
Thanks, with the habitrpg-shared PR, this works great.

@SabreCat, since you're taking point on event code, is the `immediateUse` attribute acceptable for you?

If there's ever a spell in the future that has the `immediateUser: true`, but doesn't have a `value` attribute, it should just ignore the check for gold since `User.user.stats.gp < undefined` isn't truthy.

**Comment by crookedneighbor** [comment]
@melissamcewen Thanks for this!

This will count towards a contributor tier. Can you post your user id here so I can notate it? It can be found in [settings > api](https://habitrpg.com/#/options/settings/api)

**Comment by melissamcewen** [comment]
Thanks @crookedneighbor glad it was useful my ID is 4f0ef8da-1ec1-44b7-a083-50b57aa0066c

**Comment by crookedneighbor** [comment]
Awesome! Tier+

**Pull request merged**
