### PR TITLE
Prevent multiple buy gems popups (issue #4401) - The mixins version

### PR DESCRIPTION
**Pull request by lucymhdavies**
Alternative pull request to https://github.com/HabitRPG/habitrpg/pull/4410 for issue #4401

This fix is basically the same as the original, only this one uses a mixin for the gems widget.

The widget itself:
- /views/shared/gems.jade is the "Buy Gems" Pop Up

This is sourced from 4 places:
- ./views/shared/modals/buy-gems.jade:4:      include ../gems
- ./views/shared/modals/drops.jade:21:    include ../gems
- ./views/shared/modals/rebirth.jade:18:    include ../gems
- ./views/shared/modals/reroll.jade:6:    include ../gems

Note: while I have tested the buy-gems modal, I do not know how to display the other three modals this change affects. However, as I have tested both the gemButton and gemButton(true) case in the buy-gems modal, I think those other three are pretty safe.

---

The limitations outlined in the first comment of https://github.com/HabitRPG/habitrpg/pull/4410 still apply. Copied here.

If you want this to look the same as before, it needs some CSS to override the following:

```
.tile.flush:first-child {
  border-right: 0;
}
```

Before the fix:
Without fix
After the fix:
With fix

Also, the element is still an <a>, therefore the cursor will still be a pointer.

### CODE REVIEW

**Comment by crookedneighbor** [comment]
Looks great. I made an adjustment to the CSS for the buy gems modal:

screen shot 2015-01-01 at 11 13 26 pm

This will credit you toward a contributor tier. Can you post your user id here? It can be found in [settings > api](https://habitrpg.com/#/options/settings/api)

**Comment by lucymhdavies** [comment]
Like how you've made that look. :+1:

My user id is: ce001c25-d2af-427d-b739-7a3611d765fa

Thanks :)

**Comment by lucymhdavies** [comment]
Looks like this file is still here after the merge:
https://github.com/HabitRPG/habitrpg/blob/develop/views/shared/gems.jade

And the following file doesn't appear to have the history from the original:
https://github.com/HabitRPG/habitrpg/commits/develop/views/shared/mixins.jade

Hmm. Weird.

**Comment by lucymhdavies** [comment]
Ah! GitHub says that the original pull request was also merged: https://github.com/HabitRPG/habitrpg/pull/4410

**Comment by crookedneighbor** [comment]
I merged the wrong one at first. It was my mistake. I'll remove the unused gems.jade file momentarily.

**Comment by lucymhdavies** [comment]
Ah. Easy mistake to make, especially when I give the pull requests pretty much the same name and description.

I guess to preserve file history you'd do something like deleting mixins.jade, updating gems.jade to the same content as mixins.jade, then git mv gems.jade to mixins.jade. Unless git has a cleverer way of doing it.

**Comment by crookedneighbor** [comment]
I'm sure Git has a way to do that, but it's probably a million characters long and my Git-Fu isn't that good, so I'm going to go your route:

``` bash
cat path/to/mixins.jade > path/to/gems.jade # overwrite gems.jade with mixins.jade
git rm path/to/mixins.jade # remove original mixins.jade from git
git mv path/to/gems.jade pat/to/mixins/jade # rename gems.jade to mixins.jade, retaining history
```

**Comment by lucymhdavies** [comment]
Think you'll need a commit after step 2 :)

**Comment by crookedneighbor** [comment]
@lucymhdavies Yeah, that'd be a good idea :)

**Pull request merged**
