### PR TITLE
Pi day

### PR DESCRIPTION
**Pull request by SabreCat**
Implements pie.

Fixes issue 3.14.

### CODE REVIEW

**Comment by deilann** [comment]
Can we do mole day as well? With moles?

**Comment by SabreCat** [comment]
xD I wasn't aware of Mole Day before now. You will have to petition @lemoness for such a thing!

**Comment by deilann** [comment]
Mole Day > Pi Day.

It is celebrated on 10/23 between 6:02 AM and 6:02 PM.

@lemoness pleaaaase? Moles are so cute.

**Comment by lemoness** [comment]
I will work my magical powers, but you will need to remind me in late
September ;p

**Pull request merged**
