### PR TITLE
Community Guidelines - fixes https://github.com/HabitRPG/habitrpg/issues/3801

### PR DESCRIPTION
**Pull request by Alys**
Do not merge yet! Check with @lemoness first. Also, Alys is still fixing conflicts in the habitrpg-shared PR.

Must be merged at the same time as https://github.com/HabitRPG/habitrpg-shared/pull/311
- Adds Community Guidelines document as described in https://github.com/HabitRPG/habitrpg/issues/3801
- Contains code related to changing staff to be Tier 9 and moderators Tier 8
- Has commented-out code for preventing people from chatting until they have accepted the Guidelines -- to enable that code, edit [views/options/social/chat-box.jade](https://github.com/Alys/habitrpg/blob/communityGuidelines/views/options/social/chat-box.jade#L14) (see comments in that file)

@lefnire:
- I've added some [fontello](http://fontello.com) icons so that we can use a crown to indicate staff members. I put the fontello code at [public/fontello](https://github.com/Alys/habitrpg/tree/communityGuidelines/public/fontello).  Should I move it elsewhere?
- [views/static/community-guidelines.jade](https://github.com/Alys/habitrpg/blob/communityGuidelines/views/static/community-guidelines.jade#L3) contains a short style section at the top for style changes that are needed for just that page. Would you prefer me to move those styles to [public/css/static.styl](https://github.com/Alys/habitrpg/blob/communityGuidelines/public/css/static.styl)?
- [migrations/20140914_upgrade_admin_contrib_tiers.js](https://github.com/Alys/habitrpg/blob/communityGuidelines/migrations/20140914_upgrade_admin_contrib_tiers.js) needs to be run to change staff and mod contrib tiers when this goes live. Also, It's Bailey (9da65443-ed43-4c21-804f-d260c1361596) will need to manually be set to tier 8 (moderator) because she doesn't have a tier at the moment and I can't be bothered adding code just for her. :)

### CODE REVIEW

**Comment by lemoness** [comment]
Alys - Yikes, just realized that the mods@habitrpg.com account is no longer forwarding to my main email. I'm investigating that, but until then, is it possible to swap in my normal "leslie@habitrpg.com"??

**Comment by lefnire** [comment]
> I've added some fontello icons so that we can use a crown to indicate staff members. I put the fontello code at public/fontello. Should I move it elsewhere?

Can we do it as a bower_module `bower install fontello --save`? Less clutter in code & all

> views/static/community-guidelines.jade contains a short style section at the top for style changes that are needed for just that page. Would you prefer me to move those styles to public/css/static.styl?

Whatever's clever. `*.styl` is preferred, but this is pretty one-off it seems so _shrug_

> migrations/20140914_upgrade_admin_contrib_tiers.js needs to be run to change staff and mod contrib tiers when this goes live. 

Cool cool. I'll run this right after the gems upgrade script unless you have objections

**Comment by lefnire** [comment]
Looked into Fontello, I see now it doesn't work like that (can't use bower for it in such a fashion). LGTM then!

**Comment by Alys** [comment]
I'll do the change from  mods@habitrpg.com to leslie@habitrpg.com in a few hours (unless, @lefnire , getting the mods email working is easy and preferable?). Obviously the email address change would also be easy so I don't care either way.

_" I'll run [migrations/20140914_upgrade_admin_contrib_tiers.js] right after the gems upgrade script unless you have objections"_  As long as it's run very close to the time that this PR goes live. Things would break with the current site's code if the new tiers were used with it (e.g., I'd look like a staff member and staff would, I think, look like normal grey users).

**Comment by lefnire** [comment]
Good to know! So I'll push to prod first, then run migrations right after? I just ran this one locally too, and what with 11 users total it's super smooth. The other one being ~300-some-odd, it'll be a pretty quick process.

**Comment by Alys** [comment]
I've changed mods@habitrpg.com to leslie@habitrpg.com

**Comment by lemoness** [comment]
Thanks!

**Comment by lefnire** [comment]
I merged this on local (due to merge conflicts, at the time - dunno why they're not showing now). Anyway, not sure why it didn't close this PR automatically, except that maybe I missed f4697f7 . I just cherry-picked that, pushed. I'll close this, but let me know if anything is missing.

**Pull request closed without merging**
