### PR TITLE
Avatar Edit Modal: addtional none options

### PR DESCRIPTION
**Pull request by negue**
Added a none option to:
- glasses
- animal ears / tails
- headbands

### CODE REVIEW

**Comment by paglias** [comment]
Not sure if it's related but I'm getting this error in the console `Error processing the common message "missingTypeKeyEquip"`

**Comment by paglias** [comment]
Yeah it happen when you select the new none items. 

Another issue is that you can only select the new none options only after having selected another item previously (and it's not marked as selected when you don't have any accessory of the category selected)

**Comment by negue** [comment]
Should be fixed now :)

**Comment by paglias** [comment]
LGTM!

**Pull request merged**
