### PR TITLE
Disable chat textarea and buttons while sending

### PR DESCRIPTION
**Pull request by ghost**
This was just something that personally bugged me a little (if you hit enter in the party chat box the message would start sending with no indication)

OSS websites are pretty great :+1:

### CODE REVIEW

**Comment by hairlessbear** [comment]
Could you please provide some before and after screenshots?

**Comment by ghost** [comment]
While waiting for the server, before:

somemessage

After:

latency

The delay is undetectable on localhost, but the latency with the live site for me is significant enough for it to be noticeable (might be an Australian thing)

**Comment by hairlessbear** [comment]
Thanks! I'm not an admin here, so you'll have to wait for one of them to pop by to get real feedback. For what it's worth, I like your idea; it's a small but useful change.

**Comment by crookedneighbor** [comment]
Seems reasonable to me. Made some slight adjustments before merging it in: https://github.com/HabitRPG/habitrpg/commit/1e757cc087135e4a5d55617ad6bbf34cafc5674d

This will count towards a contributor tier! What's your User ID? You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api). Be sure to only copy the User ID and _not_ your API Token.

**Pull request merged**
