### PR TITLE
Improve tests

### PR DESCRIPTION
**Pull request by gisikw**
# More tests!

Discovered that the mocha specs for the `common` JS wasn't part of the test script. Added those in, and discovered that most of them pass!

Also fixed the API spec issue where `registerNewUser` was simply updating the single user, rather than creating new ones. Was able to reinstate most of the API specs following this change.

**tl;dr: ~115 more passing specs; all changes to tests, not production code.**

_Sidenote: would it be alright in the future if I began to break off the specs into smaller modules? Having everything in flat files makes it a bit challenging to keep track of what's going on._

### CODE REVIEW

**Comment by gisikw** [comment]
Oh, hmmm. Looks like the develop branch had a history rewrite?

Happy to do a rebase once things have stabilized. But this branch definitely shouldn't be merged without #4873 on develop.

**Comment by gisikw** [comment]
Ugh, additionally, Travis uses an outdated version of Mongo, which doesn't include `$setDifference`, which is causing a test failure on CI (but not locally). I've encountered this in the past - will get Travis pulling in a decent version of Mongo.

**Comment by Alys** [comment]
Hmmm. https://github.com/HabitRPG/habitrpg/commits/develop Something odd's happened. I'm not seeing any of the PRs I merged yesterday. Will investigate.

**Comment by paglias** [comment]
Me too! I was wondering if I forgot to push to github and pushed again
today but probably something odd happened
Il 26/mar/2015 21:56 "Alys" notifications@github.com ha scritto:

**Comment by gisikw** [comment]
@Alys I see you have a revert branch here: https://github.com/habitrpg/habitrpg/tree/revert-4908-join-button-fix

Possible the revert got overzealous?

**Comment by Alys** [comment]
I don't know. It looks pretty specific: https://github.com/HabitRPG/habitrpg/commit/e9baafcbc886609d7b0693188ce9c3aba639845c

I'm wondering about this: https://github.com/HabitRPG/habitrpg/commit/c591154665a1ad38ea0e34d0df909588c4e10e1a
Although it also seem to make very few changes.

**Comment by Alys** [comment]
Although it also seem to make very few changes.

**Comment by gisikw** [comment]
Worth noting that the Egg quest stuff is missing from develop as well - though I checked and it's still on the live site. Dunno how deployment is set up, but would advise holding off on any until this gets resolved, or that'll disappear for folks.

**Comment by paglias** [comment]
That one is due to the fact that today when I synced I found 11 commits on
my local repo not pushed on github. Some were mines that I pushed yesterday
and today were absent, some others were of Alys I think. It looks like
someone force pushed
Il 26/mar/2015 22:00 "Alys" notifications@github.com ha scritto:

**Comment by Alys** [comment]
@gisikw :heart: Thanks for that Egg quest comment. I've dropped a note into a chat room for all people who are able to make deployments.

**Comment by gisikw** [comment]
It looks like the revert branch is the most up-to-date branch on the habitrpg account, at least. Maybe worth using that a develop recovery branch, and merging in or cherry-picking the last four updates from the current force-pushed develop?

**Comment by gisikw** [comment]
Put together a recovery branch here - using that revert branch as a baseline, plus the four commits from @lefnire and @paglias today.

https://github.com/gisikw/habitrpg/commits/recovery_branch

Hope this helps!

**Comment by Alys** [comment]
@gisikw Thank you!!!! I'm looking at your recovery branch now.

**Comment by lefnire** [comment]
We all ok then if I force-push https://github.com/gisikw/habitrpg/commits/recovery_branch to #develop? My personal approach before seeing the above comment was simply to merge @Alys's branch into develop, which fast-forwards just fine. So we can keep her branch in our pocket in case we notice any funny business.

**Comment by Alys** [comment]
Ok with me!

**Comment by lefnire** [comment]
done. Force pushes to origin feel so dirty _shakes hands off_. Ok all, you gotta run:

```
git fetch --all
git reset --hard origin/develop
```

**Comment by lefnire** [comment]
(not that it wasn't necessary, thanks a million for the fix @gisikw!!)

**Comment by gisikw** [comment]
You betcha!

**Comment by Alys** [comment]
@gisikw Your recover branch counts towards your next contributor tier. I've already updated your account to indicate that. Thank you!

**Comment by gisikw** [comment]
Wooo! Rackin' up dem points! :dancers:

**Comment by gisikw** [comment]
Alrighty, as far as _this_ branch goes, I've got Travis set up to pull down Mongo 2.6, so tests are running in the CI env again.

I rebased against the recovered develop branch, so this should be good to merge.

To test locally, `npm test`, or `TRAVIS=true npm test` in a headless env to skip the e2e tests (which aren't changed here).

**Comment by deilann** [comment]
Wasn't me this time!

**Comment by Alys** [comment]
```
Finished in 2.163 secs / 0.094 secs
SUMMARY:
✔ 26 tests completed
Done, without errors.
```

Sweeeet. Tier++. Thank you!

**Comment by Alys** [comment]
@gisikw Note that the higher tiers require more effort than the lower ones, so if you make any small changes from now on, you might find that they won't grant you an extra tier immediately, but they will be noted as partial credit towards a tier. There's a bit of information about that at [Contributor Rewards](http://habitrpg.wikia.com/wiki/Contributor_Rewards) but do ask if you have questions.

**Comment by gisikw** [comment]
Cheers :-)

**Pull request merged**
