### PR TITLE
Make saddles not sellable

### LINKED ISSUE #11280: Saddles should not be sellable using the API
On the website, if you try to sell a Saddle, you're prevented from doing so and you see the message "Hey! This is a pretty useful item! Are you familiar with how to use a Saddle with your Pets?" (that's the locales string `foodSaddleSellWarningNote`). This was implemented because people were selling the Saddle by accident. It was based on the assumption that no one will ever want to sell a Saddle, which I think is still a correct assumption since Saddles are a very rare prize.

However the code to prevent selling it is only in the website's front end, which means you can still sell it using the API, and therefore using the mobile apps too (one person reported today that they sold a Saddle by accident on the app).

If the API prevents selling Saddles, then it won't be possible to do so on the apps. A user who tried to might see an ugly error message but I think that will be an improvement over accidentally losing a Saddle. The apps could be adjusted later as a lower priority to give better feedback when trying to sell.

~I'll leave this issue as suggestion-discussion for a few days in case the staff disagree but then if there's no objections I'll mark it as help wanted.~

This is the website code that prevents selling:
https://github.com/HabitRPG/habitica/blob/20fc233ad7116385594deff19ae619059e21c2d8/website/client/components/shops/market/sellModal.vue#L24-L26

It uses the `sellWarningNote` parameter in the Saddle's `content` data, which should already be available through the API:
https://github.com/HabitRPG/habitica/blob/20fc233ad7116385594deff19ae619059e21c2d8/website/common/script/content/index.js#L484-L492

The API route for selling is [/api/v3/user/sell/:type/:key](https://habitica.com/apidoc/#api-User-UserSell), which is defined here:
https://github.com/HabitRPG/habitica/blob/20fc233ad7116385594deff19ae619059e21c2d8/website/server/controllers/api-v3/user.js#L1238
although this function is probably the best place to make this change:
https://github.com/HabitRPG/habitica/blob/20fc233ad7116385594deff19ae619059e21c2d8/website/common/script/ops/sell.js#L15-L54

Note that a Saddle is defined as `food`, which is included in the `ACCEPTEDTYPES` constant (referred to in the above code and defined in the code below), so that's why it's currently sellable. We don't want to stop treating it as food because that would involve too many changes, some of them breaking changes.
https://github.com/HabitRPG/habitica/blob/20fc233ad7116385594deff19ae619059e21c2d8/website/common/script/ops/sell.js#L13

### PR DESCRIPTION
**Pull request by gpalsingh**
[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #11280

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

Added check for items with `sellWarningNote` like `Saddle`.
I'm not sure if it's okay to just reuse existing error string or create a new one for this case because that'd require additional translations to be added.

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 9c3d2300-1bc4-4898-8a78-b7ffe8ac8e37

### CODE REVIEW

**Comment by Alys** [comment]
The `positiveAmountRequired` text isn't really suitable for use for this purpose. If you go to the root directory of your local install and type this: `git grep positiveAmountRequired` you'll see all the places where that string appears in the source code, and it will show you that the English text that it represents is "Positive amount is required". So that won't really help any API users who try to sell a Saddle - they won't understand why they can't sell it.

Fortunately there's already a string that you can use. Have a look at the code snippets displayed in the issue. The first snippet (from the sellModal.vue file) is the code that displays a message to a user when they try to sell a Saddle using the website. `item.sellWarningNote()` contains that text. See if you can use that same attribute to display the message when a user uses the API to try to sell a Saddle. Post here if you have questions! :)

**Comment by gpalsingh** [comment]
Hi, I made the changes. `sellWarningNote` is always in english though. What are the ways to fix it without having to make changes in the vue file?
Thanks!

**Comment by Alys** [comment]
`content[type][key].sellWarningNote()` is a strong of text so the translated version can be inserted using the same function as for other text. See how `userItemsNotEnough` is translated just above your new code.

**Comment by paglias** [comment]
Hi @gpalsingh and thanks for the PR! The error message looks good but given that only the Saddle has the `sellWarningNote` I feel like it can be a bit confusing to rely on the existence of that field to prevent selling the Saddle.

The best solution would be to have a `canSell` function on each item like we have the `canBuy` one but since this is just for the saddle now I think it's fine to check explicitly for it.

I'd simply change `if (content[type][key].sellWarningNote) {` to `if (type === 'food' && key === 'Saddle') { ...```

I would also add a test to `test/common/ops/sell.js`, let me know if you need any help :)

**Comment by Alys** [comment]
@paglias Ah sorry, it was my idea to use `sellWarningNote` in the `if` statement (https://github.com/HabitRPG/habitica/issues/11280#issuecomment-527371363). Would you want the existing Vue code changed as well?

**Comment by paglias** [comment]
Ah I missed that, in this case yeah changing the Vue code as well would be better

**Comment by gpalsingh** [comment]
HI, I made the changes and added the test

**Comment by paglias** [comment]
@gpalsingh  thanks for this! I'm merging the PR and awarding your contributor tier.

Note that further tiers require increasing amounts of work from one to the next, so Tier 2 may require a couple of PRs or a larger PR to attain. But keep helping out and we'll express our gratitude accordingly!

**Pull request merged**
