### PR TITLE
Added markdown filter to endCast notification

### LINKED ISSUE #5310: No markdown in notifications
I'm pretty sure this only matters when you cast a spell on a task with Markdown in the title, but there may be other use cases that I'm missing.

notification no emoji
notification no markdown

### PR DESCRIPTION
**Pull request by TheHollidayInn**
Fixes: #5310 

screen shot 2015-05-30 at 9 59 29 pm

### CODE REVIEW

**Comment by crookedneighbor** [comment]
Looks reasonable to me. Just [needs a test](https://github.com/HabitRPG/habitrpg/blob/develop/test/spec/rootCtrlSpec.js)

**Comment by crookedneighbor** [comment]
You'll [probably need to use $httpbackend](https://docs.angularjs.org/api/ngMock/service/$httpBackend) to mock the http request. Let me know if you need help with this.

**Comment by TheHollidayInn** [comment]
Sounds good. how am I supposed to check the text? There is no return and the notification isn't an alert.

**Comment by crookedneighbor** [comment]
I ended up going a different route. I figured it was more expressive to add a function to the Notification services for sending a markdown parsed notification then to tack the markdown filter onto a text notification. https://github.com/HabitRPG/habitrpg/commit/3291062b31e2d5ad6e3836f55fe5614cca1df58f

I then refactored the notification service and added tests: https://github.com/HabitRPG/habitrpg/commit/b375c068deed7853084f812b5a0d5b975ae4bfb7

Finally, for some reason, there's something in the root controller that is trying to load the tasks template, so I'm having a bit of trouble testing that the castEnd function actually calls the cast endpoint and notification service. I've left them as a reminder to work on them, but they are pended: https://github.com/HabitRPG/habitrpg/blob/develop/test/spec/rootCtrlSpec.js#L107-L109

**Comment by crookedneighbor** [comment]
I have added this to your list of contributions toward tier 6, since you did come up with the solution, I just refactored it. 

Probably what should happen is that the casting stuff should be moved into a separate service, and not just live on the root controller. I think the only reason it is there is because both the inventory and task controllers use it. 

Though, I bet we could abstract it out more. The inventory controller uses it to grant valentines and new years cards, but those aren't spells/skills, strictly speaking. We could maybe add the functionality to the members service? Since casting spells and granting gifts are both things that make changes to you or other users.

**Comment by crookedneighbor** [comment]
@TheHollidayInn In case you're curious: https://github.com/HabitRPG/habitrpg/commit/7a157fabb2ac1425941e074f0122f2ffd88faf6a

**Comment by TheHollidayInn** [comment]
Alright, thanks for doing that. I figured the function may need to be abstracted. I'll read through your changes right now.

**Pull request merged**
