### PR TITLE
Update landing page img

### PR DESCRIPTION
**Pull request by crookedneighbor**
Updated image on landing page to look closer to the visual look of the app (browser and mobile).

### CODE REVIEW

**Comment by deilann** [comment]
Oh thank you! UUID?

**Comment by negue** [comment]
awesome!!

**Comment by crookedneighbor** [comment]
UUID: 75f270e8-c5db-4722-a5e6-a83f1b23f76b

**Comment by deilann** [comment]
Do you want a Blacksmith or an Artisan title?

**Comment by crookedneighbor** [comment]
I have too blacksmith titles already, so I guess Artisan.

**Comment by deilann** [comment]
Oh gosh @lemoness I didn't think. Dowe need art permissions for this?

**Comment by deilann** [comment]
√ updated your titles. Next contribution will be level 3

**Comment by Alys** [comment]
@crookedneighbor : For the art permissions, could you please read [PERMISSIONS on HabitRPG Pixel Art | Trello](https://trello.com/c/eFz57Pqi/24-permissions)? It describes an email that you need to send (with sample text that you can copy and paste if you wish). If you could also mention in the email that we have already given you your contributor tier, that would help. :)

**Comment by crookedneighbor** [comment]
@Alys Sure thing. Sorry, didn't think about how this would be considered an "Art" update.

**Comment by deilann** [comment]
Haha neither did I completely until after I had given you the tier and
merged it! So you're not alone!

**Comment by Alys** [comment]
Neither did we at first, hence your premature tier. ;)

**Comment by crookedneighbor** [comment]
Done! Thanks all.

**Comment by lemoness** [comment]
All set over here :) Thanks, Blade!

**Comment by deilann** [comment]
We are boss. Thanks Leslie!

**Pull request merged**
