### PR TITLE
Updated shortname validation to support multiple browsers

### LINKED ISSUE #7382: [API v3] Path shortName is required - if challenge tag isn't at least 3 symbols long
General Info
- UUID: -
- Browser: ff 46.0.1
- OS: win10
### Description

Creating a new challenge...
- set no tag - get notification in your default (system?) language (not the one Habitica is set to use) - looks strange
- set tag of e.g. two symbols - get error "Path `shortName` is required" instead of a specified error for this case
#### Console Errors

scr

### PR DESCRIPTION
**Pull request by TheHollidayInn**
Fixes #7382
### Changes

minLength is not supported in many browsers, so I added an alert message
I completely removed minlength because ng-model does not play well with it even when the browser does not support the attribute.

---

UUID:

### CODE REVIEW

**Comment by paglias** [comment]
Looking good! One thing I would add is server side validation too, shortName is required but the minimum length isn't really enforced

**Comment by TheHollidayInn** [comment]
Hmm. I thought it was. According to the issue, the server returns shortName required. The message was incorrect though, which is why I added the front end message. Let me take a look.

**Comment by crookedneighbor** [comment]
It's not validated on the server currently. I will finish this.

**Comment by crookedneighbor** [comment]
https://github.com/HabitRPG/habitrpg/commit/8cf4f9f41469eb161de97727b1d998c74a861d01

**Pull request merged**
