### PR TITLE
Bug fixes on Merchandise Page [Fixes Issues #9144]

### PR DESCRIPTION
**Pull request by tim1234ltp**
Fixes https://github.com/HabitRPG/habitica/issues/9144

### Changes
Moved pictures of merch items from assets/images/merch/ to /website/static/merch
Image src in merch.vue is linked to the new path.
Pictures are now shown in merchandise page.

User ID:a547cd88-24e5-46d0-bd1b-eb453f653ffe
----
UUID: 
merch page

### CODE REVIEW

**Comment by paglias** [comment]
Looks good to me!

**Review by paglias — CHANGES_REQUESTED** [review]
Can you revert the changes to package-lock.json?

**Comment by paglias** [comment]
Looks like package-lock.json is still differing from `develop`. Can we fix this when merging @SabreCat ?

**Comment by SabreCat** [comment]
@paglias Looks like the only thing that changed was an ending line break being removed. There's no reason to commit it, but it won't really hurt anything either.

**Comment by paglias** [comment]
@SabreCat sounds good, feel free to merge when you prefer then!

**Comment by SabreCat** [comment]
Merged! Thank you, @tim1234ltp, and congratulations on your first contributor tier! Note that further tiers require increasing amounts of effort from one to the next, so tier 2 may require multiple PRs or a larger PR to attain. But keep helping out and we'll express our gratitude accordingly!

**Pull request merged**
