### PR TITLE
Added link to Newbies Guild in the Tavern

### PR DESCRIPTION
**Pull request by LuneFox**
Sigh. I hope I did this right.

### CODE REVIEW

**Comment by Alys** [comment]
Hi @LuneFox 

Any text on the site that appears in `=env.t('...')` is configured in the files under `common/locales/en/`. Those files are copied to Transifex for translators to create translated versions. See the README.md file in `common/locales/en/` for more information. Could you please edit one of those files to add the new string? Use the same file that contains strings for other items in the Resources box. If you commit the change to the same branch as your other changes, and then push to `origin`, it will appear in this pull request.

The `test/spec/translations.js` file should not be edited manually because it's compiled automatically when a test is run. It shouldn't have even been possible for you to commit it, but we need to adjust the `.gitignore` file to handle subdirectories under `test`.

Also, when you're creating a pull request, if you put "fixes #5945" (i.e., the issue number) in the title or description, github creates an automatic link to the issue and closes the issue if the pull request is merged.

**Comment by LuneFox** [comment]
@Alys Ah, I see. I got it wrong at first. Okay, let me see what I can do. (Both GitHub and this project are new to me, so mistakes were expected.)

**Comment by LuneFox** [comment]
I guess editing the file that is created during the test won't hurt it, for it will be created anew every time. But is there any way to discard a specific change from the pull, by the way?

**Comment by crookedneighbor** [comment]
@LuneFox Don't worry about it. I will cherry pick all but the commit that changed the fixture.

**Comment by LuneFox** [comment]
@crookedneighbor Oh, okay. To be honest I just wanted to check if the files in the test folder really can't be commited like you said. I expected some kind of an error, but suddenly it passed.

**Comment by crookedneighbor** [comment]
Oh, actually, the file I was thinking of was: `/test/spec/mocks/translations.js`

The one in `/test/spec/translations.js` is a mistake and should be deleted. Will do that when I merge in your PR.

**Comment by crookedneighbor** [comment]
This will count towards a contributor tier! What's your User ID? You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api). Be sure to only copy the User ID and _not_ your API Token.

**Comment by LuneFox** [comment]
@crookedneighbor Thanks :) My ID is 1f27893f-3808-4724-9725-f46dab93faca

**Comment by crookedneighbor** [comment]
Tier awarded! You can read more about [contributor tiers and rewards here](http://habitrpg.wikia.com/wiki/Contributor_Rewards).

Note that as your tier increases, it takes progressively more work to achieve the next one, so for the higher tiers, larger PRs or a few PRs are required. There's some information about that at Contributor Rewards, but feel free to ask here if you have questions!

**Comment by LuneFox** [comment]
@crookedneighbor Thanks again :) I'll keep that in mind.

**Pull request merged**
