### PR TITLE
Added sync on mage fireball spell

### PR DESCRIPTION
**Pull request by TheHollidayInn**
Added sync on mage fireball spell

This should fix the fireBall portion of https://github.com/HabitRPG/habitrpg/issues/2143 .

Can someone let me know if I am heading in the right direction with this? 

I believe I need to do two things:
  -Check to make sure a spell adds exp on the client side in the rootCtrl after a cast ends
  -Add the same functionality to Backstab

Here are some screen shots of before the spell is used (Exp is overflowed cause by using the footer +exp button)
screen shot 2015-03-26 at 12 05 28 am
screen shot 2015-03-26 at 12 05 40 am

 and after the spell is used (leveling up the character).

### CODE REVIEW

**Comment by Alys** [comment]
You've neglected to explain how we'll use all our free time when we no longer have to answer questions about this. :)

I've tested this locally and it certainly works. The code looks sensible to me, and it implements the fix that lefnire suggested in #2143. However I'm not the best at knowing whether something could be done in a better way in our codebase, so I reckon wait a day, and if no one says there's a better way to do it, we'll go with what you've done. Note that I'm just being cautious here - I don't think there's anything wrong with how you've done it!

**Comment by deilann** [comment]
Oh goodness. I think I could add three more Dailies. No, five!

**Comment by crookedneighbor** [comment]
Could this same method be applied to "Ethereal Surge" to have the correct amount of MP deducted immediately instead of on refresh? (Might happen in two notifications)

Looks like you've tested the scenario where exp is already overflowing and then casting burst of flames. I'd like to see the results of testing when burst of flames causes the overflow. You can do this by using the fix character values button in the settings page to put your exp at near level status, but not over.

I assume the result will be the same, but I'd like to check just in case.

**Comment by Alys** [comment]
_"testing when burst of flames causes the overflow"_  I've tested that one. It works as desired. :)

**Comment by Alys** [comment]
@TheHollidayInn  There's been no comments about the method you've chosen, so it must be okay! If you'd like to add the same thing to Backstab, that would be LOVELY!

I'd also be very much in favour of you fixing Ethereal Surge as @crookedneighbor says, but if you do decide to work on that, please submit it in its own PR. I'd want to merge it either into a skills rebalancing project that we're doing, or merge it into develop just after that project has gone live.

**Comment by TheHollidayInn** [comment]
@Alys sounds great! I'm out for the weekend, but I will make both adjustments when I return.

**Comment by TheHollidayInn** [comment]
Okay, I have uploaded the fix for Backstab.

Here are pictures of the spells overflowing and leveling the user:

Burst of Flames
screen shot 2015-03-30 at 11 37 26 am
screen shot 2015-03-30 at 11 37 37 am

Back Stab
screen shot 2015-03-30 at 11 41 21 am
screen shot 2015-03-30 at 11 41 31 am

I will send Ethereal Surge as a separate PR.

Also, I would like write test for all of these. I can see how to write a Edge to Edge test except for setting the user's exp (I could just have the test click until the user levels). And, I have no idea how to test the api. If anyone could help me get start, that would be nice. I would submit the tests in a separate PR as well.

**Comment by TheHollidayInn** [comment]
Actually, it seems that Ethereal Surge is fixed as a side effect from adding User.sync().

screen shot 2015-03-30 at 12 05 37 pm

**Comment by Alys** [comment]
THANK YOU! We had a bug report for this an hour ago - it is so nice to think that is probably the last one!

This is partial credit towards tier 4 (almost there!).

**Pull request merged**
