### PR TITLE
Add Contributor Only Pet Choice

### PR DESCRIPTION
**Pull request by Shaners**
This PR https://github.com/HabitRPG/habitrpg-shared/pull/33 should completed before this one.

### CODE REVIEW

**Comment by Shaners** [comment]
Looks like this probably won't work even if user has item pets "Hydra".

**Comment by Shaners** [comment]
This is icky but works now.

**Comment by Shaners** [comment]
Also places rare pets on one line like the other pets.

**Comment by lefnire** [comment]
this one's looking good too, sure you don't want it merged?

**Comment by Shaners** [comment]
Feel free to merge, I was playing with having the paw show up for the hydra pet and a link to the contributor page or terms: https://github.com/Shaners/habitrpg/blob/patch-2/views/options/pets.jade but that can be later. Also was playing with the migration script but realized that I'm not sure what the data for that looks like or what level people actually get the pet at.

**Comment by Shaners** [comment]
Ouuu, now I'm thinking a golden paw...

**Comment by Shaners** [comment]
What do y'all think, yay or nay?
rarwpeticonmock

**Comment by lefnire** [comment]
I love it man! Yeah, throw this onto develop since it's the wild west right now until we launch challenges.

**Comment by lefnire** [comment]
one technical hiccup: angular-ui-bootstrap doesn't allow html in popovers (you want a link in there yes?). Vanilla bootstrap doesn't play very well specifically with popovers & tooltips + Angular. Rock & hard place with popovers/tooltips. can you think of somewhere else to put the "learn more" link?

**Comment by Shaners** [comment]
The paw is a button so can be a link no? Hover text can instruct user to click the paw to discover how you too can contribute and get this pet!

**Comment by lefnire** [comment]
yep, that works!

**Comment by Shaners** [comment]
Got to be a better way to do that link. (Maybe through the controller?) But it works so feel free to merge. 
rarepeticonmock002

**Comment by lefnire** [comment]
merged to `contrib` branch

**Comment by lefnire** [comment]
ah! thanks for the Dragon-Hydra stuff, I was worried about how we were going to create a new pet tier right now. Good thinking putting in the dragon tier

**Comment by Shaners** [comment]
Still feels kind of icky! I am just thinking like if in the future we tried to run a count on dragon tier, for an achievement say, we would have to work around it. But then again if the contributor stuff encourages more coders to join it may fix itself!

**Pull request closed without merging**
