### PR TITLE
Adding new basic audio theme "rosstavoTheme"

### PR DESCRIPTION
**Pull request by rosstavo**
### Changes

Added a new audio theme with a more basic productivity app style. 

---

UUID: 5c2b354c-d5f1-4f54-8ab0-52136fe70309

### CODE REVIEW

**Comment by crookedneighbor** [comment]
@rosstavo Just checking, these are all sounds you composed/created?

**Comment by rosstavo** [comment]
@crookedneighbor Yep that's correct. Created in Ableton using virtual instruments, sample packs, and my own recorded sound effects.

**Comment by Alys** [comment]
@rosstavo Thank you! I've awarded you one tier for the Blacksmith work and another as a Bard.

Note that as your tier increases, it takes progressively more work to achieve the next one, so for the higher tiers, larger PRs or a few PRs are required. There's some information about that at [Contributor Rewards](http://habitrpg.wikia.com/wiki/Contributor_Rewards), but feel free to ask here if you have questions!

**Comment by Alys** [comment]
Thank you also for your edit to the Bard wiki page! We missed that change when the code base was reorganised.

**Comment by rosstavo** [comment]
Thanks @Alys and @crookedneighbor !

**Pull request merged**
