### PR TITLE
@lefnire => API Auth working + 1 test

### PR DESCRIPTION
**Pull request by switz**
So, first off, I should say: I think we should take a serious audit at the security implications here. I'm by no means an expert and this implementation is definitely not rock solid. So, that being said, don't merge this into develop yet. I don't want anyone's data being released on beta.habit. Pull this into a separate branch of your own so you can test it alongside habitrpg-mobile.

The implementation is fairly straightforward, plus I included a test.

``` bash
curl --compressed -X POST -H "Content-Type:application/json" \
  -d '{"username":"tweezer","password":"yeah its a phish song"}' \
  http://localhost:3000/api/v1/user/auth
```

https://github.com/lefnire/habitrpg/issues/524

### CODE REVIEW

**Comment by switz** [comment]
Just to add what it returns:

``` json
{
  "id": "654c3f51-a5cf-4756-a6b2-39c75c5e093b",
  "token": "f25eaa69-8b54-4d89-baa9-cb392762fc75"
}
```

**Comment by paglias** [comment]
Hi, 

I'm quite new to HabitRPG and I think it's really great, both for habits management and for the fact that it is open source.

Thanks for all the work!

On API authentication usually an user shouldn't have to give it's password/username to a thirdy party app. The best way probably would be OAuth 2 but it may not be so easy to implement. 

Another useful thing would be possible with OAuth (but also with basic authentication it can be done) is the ability to revoke authorization to an application previously authorized.

I've noticed that you use an authentication system based on [Passport](http://passportjs.org/), it provide a module for implementing OAuth 2 providers. But that would be incompatible with the current implementation based on user's id and api token

**Comment by lefnire** [comment]
@switz sorry for my radio silence, wifi hunter here. You still want this to stay unmerged until we've kicked it a while on mobile?

**Comment by switz** [comment]
Yeah, leave it unmerged.

**Comment by lefnire** [comment]
@paglias we just need users to be able to sign in uname/pw at some point. Eg, mobile login screen - we don't want them to have to enter uuid & api token (too long), so this api auth bit is just to retrieve their uuid & api token provided their uname & pw, then we store the tokens locally and use those moving forward

**Comment by uvwxy** [comment]
How about displaying a QR code with uuid & api token. There are enough libraries/intents on mobile platforms to decode them.

This would make things a lot easier, and we wouldn't need to use user/pass..

**Comment by uvwxy** [comment]
The content of the QR code would be

"http://habitrpg.com?uuid=...&api=...".

i.e. "$server?uuid=$uuid&api=$apitoken"

**Comment by lefnire** [comment]
manually merged, thanks @switz !

**Pull request merged**
