### PR TITLE
Fix Incorrect Heading margins

### PR DESCRIPTION
**Pull request by dnlup**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Addresses #9303 

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

In the sections `website/client/components/challegenges`, `website/client/components/inventory`, `website/client/components/shops`:

* set the `mb-0` class in h1 headers to `mb-4`.
* set the class of `h2` headers to `mb-3`.

[//]: # (Put User ID in here - found in Settings -> API)

----
UUID:

### CODE REVIEW

**Comment by dnlup** [comment]
Sorry for the mess with commits, I got a little confused with the sections of the site.

**Comment by negue** [comment]
Hey @dnlup, thanks for your contribution 👍 . Could you pull the latest changes from `develop`?

**Comment by dnlup** [comment]
@negue Sure!

**Comment by Tressley** [comment]
This looks good!

**Comment by paglias** [comment]
@dnlup thanks for this, I'm merging the PR, if you can provide us your Habitica UUID I'll be happy to award your contributor tier :)

**Comment by dnlup** [comment]
@paglias no problem! I currently don't have a UUID, I' ll ping you as soon as I have one. Thanks 😉.

**Pull request merged**
