### PR TITLE
Various Chat Fixes - Fixes #12377

### LINKED ISSUE #12377: Correct handling for adding second @mention in Tavern and Guild chats
Scenario: If you write a message with a single @mention and later decide to @mention a second user, the dropdown list of names does not appear for the second @mention. 

Ideally, selecting the desired choice from dropdown menu should not lose focus of the text area. (Currently, selecting your choice requires you to re-select text area in order to continue typing).

This issue is a cleanup of #9694 with additional UI improvement suggestion. 

For anyone wanting to work on this, most of the work was done in #10638 which was never merged but can be used as a good starting point.

### PR DESCRIPTION
**Pull request by Helcostr**
[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #12377

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
* Allow adding `@mention` anywhere (previously was fixed at the end of the text)
* Add re-focus after mouseclick on `@mention` choice

Changes that were attempted, but rollbacked:
* Remove `@mention` space barrier (since server ingests mentions without spaces in between)

Co-authored-by: Bart Enkelaar <benkelaar@gmail.com>

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 10cbe941-0e10-4763-9f4f-7a3ae5bb2198

### CODE REVIEW

**Comment by Helcostr** [comment]
Originally here (but broke out the edits for easier understanding) #13165

(Refer back to the PR for old comments)

**Comment by SabreCat** [comment]
This is looking good! I'm going to check with the UX folks about @mentions showing up during typing of an email address; they may agree that it's an acceptable tradeoff for fixing these more significant issues, but I want to make sure before merging.

**Review by SabreCat — APPROVED** [review]

**Comment by Helcostr** [comment]
@SabreCat I want to make sure that we are not trading anything off here: when I was testing with no spaces, I noticed that mentions are still properly tagged in the backend logic. So to prevent misleading the user, I have allowed for no spaces in the frontend logic.

This interpretation by me can definitely be disentangled from this PR.

**Comment by SabreCat** [comment]
Aha, that does clarify the situation for me, thanks!

**Comment by SabreCat** [comment]
@Helcostr I discussed this with @saraolson, and I think we're going to treat the _server_ behavior as a bug, here. @user1@user2 shouldn't count as two valid @-mentions. So let's restore the logic that keeps email addresses from lighting up the dropdown, and we'll document the server parsing as something to fix!

**Review by SabreCat — CHANGES_REQUESTED** [review]
Per discussion, let's put back the pre-@ word boundary check, and once this PR is merged I'll add an issue ticket to update the server behavior to match.

**Comment by Helcostr** [comment]
> Per discussion, let's put back the pre-@ word boundary check, and once this PR is merged I'll add an issue ticket to update the server behavior to match.

Boundary back, and also picked up on a bug where the selection never turned off after selecting.

**Review by SabreCat — APPROVED** [review]

**Comment by SabreCat** [comment]
Thanks for the update! Credited toward your next contributor tier. This will go into Staging for deployment to production next week.

**Pull request merged**
