### PR TITLE
On avatar page, moved flowers and made animal ears' button sizes consistent with other options

### PR DESCRIPTION
**Pull request by hairlessbear**
Implements the suggestion in #5221 and increases the size of the animal ears buttons to be consistent with the rest of the page (this doesn't affect the size of the animal ears buttons on the equipment page).
## Before:

selection_016
## After:

selection_017

### CODE REVIEW

**Comment by crookedneighbor** [comment]
How does the equipment page look after this change to how the ears are processed?

**Comment by hairlessbear** [comment]
No different. Although both pages use the `customize-option` class, the equipment page uses [`shop_headAccessory_special_*Ears`](https://github.com/hairlessbear/habitrpg/blob/move_flower_to_accessories/common/dist/sprites/spritesmith4.css#L121-168), as opposed to `headAccessory_special_*Ears`. Since there are still no `customize-option.shop_headAccessory_special_*Ears` entries, their display is not affected.

Edit: More concisely, the ear classes that are now processed differently are _not_ the same ear classes that are used on the equipment page, so there is no change.

**Comment by lemoness** [comment]
Looks good!

**Comment by crookedneighbor** [comment]
Made one change and recompiled the sprites: https://github.com/HabitRPG/habitrpg/commit/615c3f18a5b8e1b2ddfbb68f58bc59499ebfbdad

Notated toward your next tier.

**Comment by hairlessbear** [comment]
@crookedneighbor Thanks! Out of curiosity, why did you make that change? I chose the `\b` anchors because they limit the beginning and end of the text, whereas the `^` anchor only affects the beginning.

**Comment by crookedneighbor** [comment]
With the check, you were trying to isolate `headAccessory_special_...` from `shop_headAccessory_special_...`. Both options work, I just like the `^` character more and find it easier to parse when glancing at a regex.

**Comment by hairlessbear** [comment]
Makes sense. The only reason it would ever be an issue is if new items were introduced with names like `headAccessory_special_...Ears_more_text_here_for_some_reason`, and that seems incredibly unlikely. Thanks!

**Pull request merged**
