### PR TITLE
Add @-prefix to usernames in gift messages

### PR DESCRIPTION
**Pull request by mrhmouse**
This addresses part of #7722

---

UUID: e345f9e6-81d2-4494-8a4a-9c263e174dac

### CODE REVIEW

**Comment by khipkin** [comment]
@mrhmouse Please undo your changes in locale directories other than "en".  See the [locales README](https://github.com/HabitRPG/habitica/blob/develop/website/common/locales/README.md) for more details.

**Comment by mrhmouse** [comment]
Would this be better fixed by just prefixing the names with '@' prior to handing them to the template? Or should the '@' go in the template like it is now..?

**Comment by crookedneighbor** [comment]
Personally, I don't think we need to add the `@` sign at all. It doesn't have any meaning within private messages like it does in the chat.

**Comment by crookedneighbor** [comment]
@Alys @lemoness @veeeeeee thoughts?

**Comment by lemoness** [comment]
I don't think we need the @ symbol. We don't display it in most system messages.

**Pull request closed without merging**
