### PR TITLE
Preventing cardRead from notifying user.

### PR DESCRIPTION
**Pull request by vincecampanale**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes Issue #8351 

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
Added a condition to line 159 in userServices.js that checks if the op is 'cardRead.' If it is, then the user will not receive a notification saying that they read the card. 

[//]: # (Put User ID in here - found in Settings -> API)

----
UUID: 08c2b5db-70bd-4677-8a95-d84cdfec2afb

### CODE REVIEW

**Comment by SabreCat** [comment]
This would do the trick, though it's a peculiar bit of special-case hard coding. Maybe acceptable pending the frontend rewrite, even so. Thoughts @TheHollidayInn @paglias ?

**Comment by khipkin** [comment]
It would probably be better to just never create the notification to begin with, rather than selectively ignoring it after it's created.

**Comment by Alys** [comment]
When using Habitica through the API, the notification might be useful for feedback.

**Comment by vincecampanale** [comment]
So what's the verdict? Will this work for now, pending the front end rewrite?

**Comment by TheHollidayInn** [comment]
1. Where does this notification originate from? API? 

2. If we go with this fix (which I am fine with), let's do two things:
 - Moved the string "readCard" to a constant.
 - Add a test for this condition (I know it is mundane but it will ensure consistency in the redesign)

**Comment by Alys** [comment]
I suggest that the constant should be an array or object listing the types of notifications that we want to suppress. At the moment there'll be just one type in it but there might be others in future and an array / object will be easier to update.

**Comment by vincecampanale** [comment]
@TheHollidayInn 
1. Unsure where the notification originates from.
2. Put "readCard" in an array which contains opNames we want to suppress notifications for (per @Alys recommendation). 
If the `opName` is not in the `opNamesWithoutNotifaction` array, it will get a notification.

**Comment by vincecampanale** [comment]
Any further input/suggestions?

**Comment by SabreCat** [comment]
We could still add a test per @TheHollidayInn's second bullet point. We'd need to stub `$http`, spy on `Notification`, and check that `Notification.text` doesn't get called when you run `readCard`. Does that sound about right THI?

**Comment by TheHollidayInn** [comment]
Yea, just stub and spy, then call `callOpsFunctionAndRequest ` with the `"readCard"` in the param then ensure `Notification.text` is not called.

**Comment by vincecampanale** [comment]
@SabreCat @TheHollidayInn 
Hey guys, working on the test now. What exactly do you mean by "stub and spy"? Is there an example in the tests I can look at? Also will this test go in POST-user_read_card.test.js or /test/common/ops/readCard.js? 
Thanks for the help and feedback - I'm learning a lot.

**Comment by vincecampanale** [comment]
Getting a couple of errors when trying to test. 
`npm test` outputs: 
npm test output

`npm start` outputs:
npm start output

**Comment by Alys** [comment]
@vincecampanale this might not help but as a first step, merge/rebase the latest `develop`, check that your config.json is up to date with config.json.example, and run `npm install` to ensure that you have the latest libraries (check the output for errors). Post the test errors again after that if they're still happening and if they're not identical to before.

**Comment by TheHollidayInn** [comment]
The slack url error can be ignored. The first error just needs to be installed via npm. I would just run it manually.

**Comment by vincecampanale** [comment]
How would I run it manually? I tried doing `npm install -g eslint` and `npm install -g esnext` and a bunch of other things, but got the same error.

**Comment by Alys** [comment]
@vincecampanale You wouldn't use the -g flag for installing it in a specific project, like the habitica site, but really, I'd still do `npm install`. If you're missing that one, you might be missing others. The Aspiring Blacksmiths guild lists changes that are made to package.json and advises when npm install should be done again, so if you haven't noticed a few of them, definitely do the full `npm install`.

**Comment by TheHollidayInn** [comment]
`npm install eslint-config-habitrpg/esnext`

**Comment by vincecampanale** [comment]
@Alys I did try `npm install` a couple of times, and did some troubleshooting on my own. I'm especially confused because I've had this working before.

@TheHollidayInn That command is returning this error: 

screen shot 2017-02-10 at 2 19 05 pm

Sorry for being a hassle >.<

**Comment by Alys** [comment]
No worries. :) The setup is complex until you're used to it.

There's no sign of a "habitica" directory in the output. You need to run all install commands in the top level habitica directory (the one that contains package.json and config.json).  Move into that directory and run `npm install`. Examine the output carefully for errors and if there is anything that you're not at all sure of, show us the command and full output. The best way to do that is by pasting a link here to a GitHub Gist or similar (see [Setting up Habitica Locally >  Prepare for Troubleshooting](http://habitica.wikia.com/wiki/Setting_up_Habitica_Locally#Prepare_for_Troubleshooting) for details).

After you've done `npm install`, if the tests still fail, do `ls node_modules/eslint-config-habitrpg/` (still in the habitica directory). It should contain a few files. Show us that command and its output, as well as the full output of `npm install` and any other troubleshooting data that you think might be relevant..

**Comment by TheHollidayInn** [comment]
Approved!

**Comment by TheHollidayInn** [comment]
Noted towards your Tier 2 progress :D

**Pull request merged**
