### PR TITLE
Add new favicon

### LINKED ISSUE #8298: Suggestion for improvements to the new favicon
The favicon was recently changed to have a white background (https://github.com/HabitRPG/habitica/issues/7720).  This makes it look non-standard since very few websites have a non-transparent background for their favicons, and the same is true for tiles in mobile apps, etc.

A more standard way of achieving good viewability regardless of the background is using an outline.  The two files I could find were `website/client-old/favicon.ico`  and `website/client-old/favicon_192x192.png`.  I made copies of each of them with white outlines and transparent backgrounds.

I put the `png`, `ico` and the original GIMP files up: 
https://samking.org/static/habitica_favicon_192x192_outline.png
https://samking.org/static/habitica_favicon_192x192_outline.xcf
https://samking.org/static/habitica_favicon_outline.ico
https://samking.org/static/habitica_favicon_outline.xcf

If this looks good to folks, let me know, and I can submit a pull request.

Thanks!

### PR DESCRIPTION
**Pull request by librarianmage**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #8298 

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

[//]: # (Put User ID in here - found in Settings -> API)

----
UUID:

### CODE REVIEW

**Comment by librarianmage** [comment]
It would be appreciated if this PR could be reviewed, but I understand that there is an effort to try to finish up some of the older PRs.

**Comment by TheHollidayInn** [comment]
I'll check this out tomorrow. Sorry for the delay!

**Comment by librarianmage** [comment]
@TheHollidayInn Thank you!

**Comment by TheHollidayInn** [comment]
Can you also replace the favicon_192x192.png file with the new version?

**Comment by librarianmage** [comment]
There was not one referenced that looked like the new version, as far as I
could tell.

**Comment by librarianmage** [comment]
@TheHollidayInn To clarify, I did not see a similar style favicon in the .zip file that @Alys mentioned [here](https://github.com/HabitRPG/habitica/issues/8298#issuecomment-301291390).

**Comment by TheHollidayInn** [comment]
Ah, okay. I'll ask her about it then merge this in. Thanks! I added it to your tier progress already :D

**Comment by librarianmage** [comment]
Yay!

**Comment by saraolson** [comment]
favicon-192x192

Here's the 192x192 favicon!

**Comment by librarianmage** [comment]
Do you have a link to an offsite version? I believe GitHub compresses the
images

**Comment by saraolson** [comment]
@MathWhiz 
[favicon-192x192.zip](https://github.com/HabitRPG/habitica/files/1045256/favicon-192x192.zip)
how about a zip file containing it?

**Comment by librarianmage** [comment]
That will probably work!

**Comment by librarianmage** [comment]
@TheHollidayInn Ping! 🔔

**Comment by TheHollidayInn** [comment]
Thank you!

**Pull request merged**
