### PR TITLE
Challenges now display'no owner' if original owner deletes account: issue #5979

### PR DESCRIPTION
**Pull request by nicolevonvon**
Commit for issue #5979.
Please let me know if I didn't follow the Git process correctly, used to Mecurial.

### CODE REVIEW

**Comment by crookedneighbor** [comment]
This will count towards a contributor tier! What's your User ID? You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api). Be sure to only copy the User ID and _not_ your API Token.

**Comment by nicolevonvon** [comment]
Yay! Great! 
f5d9cb7c-a6db-4df1-b49e-dab74af42d66

**Comment by crookedneighbor** [comment]
Tier awarded! You can read more about [contributor tiers and rewards here](http://habitrpg.wikia.com/wiki/Contributor_Rewards).

Note that as your tier increases, it takes progressively more work to achieve the next one, so for the higher tiers, larger PRs or a few PRs are required. There's some information about that at Contributor Rewards, but feel free to ask here if you have questions!

The one note I have about git is that I'd recommend branching off of your develop branch each time you work on a new issue/feature. This will allow you to work on many issues at once, and if for some reason we can't merge in your changes, your develop branch does not go out of sync with Habit's.

**Comment by nicolevonvon** [comment]
Thanks, that's good advice, particularly when working on things bigger than 3 lines :)

**Pull request merged**
