### PR TITLE
Added filter by ownership for challenges

### PR DESCRIPTION
**Pull request by TheHollidayInn**
This is a fix for: https://github.com/HabitRPG/habitrpg/issues/1809 .

### CODE REVIEW

**Comment by Alys** [comment]
When I test this on a full copy of the challenges collection from the production database, I see this error in the Console:

```
TypeError: Cannot read property '_id' of null
    at $scope.filterChallenges (http://localhost:3000/js/controllers/challengesCtrl.js:216:28)
```

That corresponds to this line: `return (chal.leader._id == User.user.id);`

I'm not sure why it's complaining about that, because I queried the database to see if there were any challenges that don't have the leader object, and there were not. I'm hoping you might have some ideas.

This failure stops the filtering from working correctly, unfortunately.

If I can help at all with any testing or any database queries, just let me know! This will be a useful feature for some of our most active players so I'm keen to merge it when I can!

**Comment by gisikw** [comment]
I pulled a record out of my local DB, and it looks like the leader on a challenge record is just the user ID, rather than a nested user object (which makes sense - a nested document would cause issues here).

``` json
{
    "_id" : "0127a614-f9a1-4272-9398-8de585313fce",
    "group" : "aeb1e975-4883-474b-8dd3-b4097f8f4c6e",
    "leader" : "c4bd4674-26a2-484b-b02f-4b87d0102e81",
    "prize" : 0,
    "memberCount" : 0,
    "members" : [
        "c4bd4674-26a2-484b-b02f-4b87d0102e81"
    ],
    "timestamp" : ISODate("2015-03-18T00:10:34.408Z"),
    "rewards" : [ ],
    "todos" : [ ],
    "dailys" : [ ],
    "habits" : [ ],
    "official" : false,
    "__v" : 0
}
```

So the code should simply check leader, rather than leader._id, no? e.g.

``` js
//Filter challenges that are owned by the user
if ($scope.search._isOwner == true) {
  return (chal.leader == User.user.id);
} else if ($scope.search._isOwner == false) {
  return (chal.leader != User.user.id);
}
```

**Comment by Alys** [comment]
Ha ha, yes. My database has the same thing as yours. That's obvious and I didn't see it because I was using the API to look at the challenge data. :-/  )The API turns the leader into an object.)

**Comment by gisikw** [comment]
Sneaaaaaky!

**Comment by TheHollidayInn** [comment]
Hm, when I logged the chal.leader object to the console from inside `$scope.filterChallenges = function(chal){`, I get the following:
screen shot 2015-04-11 at 3 55 04 pm

I have create a new  branch after adding all the changes that have been pushed to develop since I submitted this PR. Can we try the code again?

**Comment by crookedneighbor** [comment]
@TheHollidayInn In the future, it really would be better to keep changes in a single pull request, rather than closing one and opening another. This will allow us to easier see the history and discussion around it. If you ever need help with git to pull in the latest changes from upstream, do not hesitate to ask! 

Since you've already opened another one, we'll just continue from there.

**Comment by TheHollidayInn** [comment]
Sounds good! I will definitely ask. Sorry for the confusion.

**Pull request closed without merging**
