### PR TITLE
(in)definite articles for food items. Partial fix for https://github.com/HabitRPG/habitica/issues/3571

### PR DESCRIPTION
**Pull request by Feywood**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Partial fix for https://github.com/HabitRPG/habitica/issues/3571

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
Added "a" and "the" versions for all fooditems in content.json as was agreed on before. Have done so for the original items, cakes and candies.
Also made the change for <%= foodText %> in messages.json

However, the actual messages are now "[pet] enjoys [food]" with no article at all.
Just wanted to ask for feedback on what I think solution might be before going off and mucking about. Would it be correct to go into the constants.js and create the additional the/a versions in the ITEM_LIST so that these can then be used in the script/ops/feed.js?

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 9c4776eb-7330-465b-85cc-e4ccef6c1ad1

### CODE REVIEW

**Comment by Alys** [comment]
This is looking good. I think ITEM_LIST will just need foodText replaced with foodTextThe because from what I can see at a quick glance, the data in ITEM_LIST is just used when feeding (check though; I might be wrong).  I think `website/common/script/fns/randomDrop.js` can use the foodTextA version.

**Comment by Feywood** [comment]
Made several additions:
I've removed the indefinite article from a few items as English is inconsistent and fickle.
The api.food (website\common\script\content\index.js) now contains the textA and textThe alternatives and had the article item removed from each food.
In ITEM_LIST (constants.js), food now refers to foodTextThe.
Feed.js and buyArmoire.js were modified to show textThe and textA respectively and tests worked fine.
RandomDrop.js however, same modification as for the armoire, but unsuccessful, so feedback much appreciated. <3

**Comment by SabreCat** [comment]
@Feywood -- there are some tests whose expected results need to be updated in line with the string modifications. Take a look at https://travis-ci.org/HabitRPG/habitica/jobs/318205661 and https://travis-ci.org/HabitRPG/habitica/jobs/318205666 !

**Comment by Feywood** [comment]
Last updates done and tests updated according to Travis' feedback. Should hopefully finally be ready. Thanks for everybody's help

**Comment by paglias** [comment]
Not a big fan of adding a lot of new strings but this look like a great improvement :) Haven't tested locally but the code is ok

**Comment by Alys** [comment]
I'll test this one locally.

**Comment by Alys** [comment]
This is great! I've tested it locally with the actions below and it all behaves as expected:
- gaining a food item as a drop
- buying a food item from the Armoire
- buying a food item with gems
- selling a food item for gold
- using a preferred food to feed a pet
- using a non-preferred food to feed a pet

One final change that isn't directly related to this code but would still be good to do:
https://github.com/HabitRPG/habitica/blob/028da1d6a9e1d64865dee8ab87289e121efbdd09/website/server/controllers/api-v3/tasks.js#L513
That's a comment in the api documentation that describes what is returned by the server when the user completes a task. Part of the returned object used to be `"article":"",` in the `drop` section of that line, but the article no longer exists, so if you could remove that `"article":"",` text from that line, it will be perfect.

We can mark this as suitable for merging as soon as that's done. Thanks for doing this change! It's something the translators have been asking for for a long time!

**Comment by Feywood** [comment]
committed and pushed the api change. So glad I got this done, thank you so much for all the assistance.

**Comment by paglias** [comment]
@Feywood  thanks for this! I'm merging the PR and awarding your contributor tier.

Note that further tiers require increasing amounts of work from one to the next, so Tier 2 may require a couple of PRs or a larger PR to attain. But keep helping out and we'll express our gratitude accordingly!

**Pull request merged**
