### PR TITLE
Fixed Challenge Winner Text (partial fix for #9629)

### PR DESCRIPTION
**Pull request by avirgil**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
partial fix for #9629 

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
Changed challenge winner text. There is an issue noted in the ticket: 

> (Also, there should be some space between the winner’s name and “Selected”.)

That I couldn't find in the code. That part has not been fixed.

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: c4192f1b-fa23-43aa-b278-1f6b2618949d

### CODE REVIEW

**Comment by avirgil** [comment]
Ugh. Text should read : "select A winner." I'll commit a fix.

**Comment by avirgil** [comment]
Not sure why the build failed. Looks like an issue in the build itself? The last build failed with the message: 

> The command "npm install &> npm.install.log || (cat npm.install.log; false)" failed and exited with 1 during .

But the same command in the previous jobs ran fine.

**Comment by Alys** [comment]
@avirgil Sometimes the tests time out or fail for other reasons unconnected to the PR's code changes. That message you quoted is a typical example of a transient failure. I restarted that test and it's passing now. :) Posting to the PR when you notice an unexplained failure is the right thing to do.

**Comment by avirgil** [comment]
@Alys Does it matter that coverage went down?

**Comment by TheHollidayInn** [comment]
The coverage is not a problem for this code. It was just an issue with Travis.

I don't think the space between select and the user is an issue anymore. This PR looks good!

**Comment by SabreCat** [comment]
Thank you for this, @avirgil, and welcome to the ranks of the Blacksmiths at contributor tier 1! Note that further tiers require increasing amounts of effort from one to the next, so Tier 2 may require multiple PRs or a larger PR to attain. But keep helping out and we'll express our gratitude accordingly!

**Pull request merged**
