### PR TITLE
Fix seed file

### PR DESCRIPTION
**Pull request by aughr**
Hey there, I was following the README and the seed file didn't seem to work. As far as I can tell, It needed to configure nconf so it can start and disconnect from mongo so it can end.

Please let me know if there are any contribution guidelines I haven't followed :sweat:

### CODE REVIEW

**Comment by SabreCat** [comment]
Is a seed file even needed anymore? I haven't run that step in ages, but my local copy seems to run just fine. The README is kinda out of date with respect to the [wiki](http://habitrpg.wikia.com/wiki/Setting_up_HabitRPG_locally) in any case...

**Comment by lefnire** [comment]
@SabreCat seed file presently just sets up tavern. Nothing _needs_ to exist in the database initially _except_ the tavern, since it's just one big public Guild

@aughr that's the ticket, thanks!

**Comment by lefnire** [comment]
UUID for contrib lvl?

**Comment by aughr** [comment]
b2efb993-b746-4804-b205-ce9ea029af4f

**Comment by lefnire** [comment]
√

**Pull request merged**
