### PR TITLE
Beastmasterfix

### PR DESCRIPTION
**Pull request by deilann**
These are the changes to the stable needed for the beastmaster fix. I set it so taht the pets show as not owned because I couldn't do the opacity.

### CODE REVIEW

**Comment by ghost** [comment]
Looks like @colegleason's commit got in there. Can you remove it? Just do a rebase, or else reset your branch to the commit prior, checkout the file Cole modified, and then recommit and do a force push.

**Comment by lefnire** [comment]
I'm seeing a lot of translations stuff in this PR, even just on the relevant commit 1313b1a. @Sinza- @paglias does this look like it will cause conflict in @Sinza-'s upcoming main.json split? TMK this is the only relevant code:

``` diff
+            button(class="pet-button pet-not-owned" ng-if='user.items.pets[pet]<0')
+              .PixelPaw
+              //if this could be changed to the opacity talked about? can't figure it out
```

**Comment by deilann** [comment]
That is the only relevant code.

**Comment by lefnire** [comment]
Cool, give 5caaff1 a gander

**Pull request closed without merging**
