### PR TITLE
WIP: Improve User model performances

### PR DESCRIPTION
**Pull request by paglias**
We found out that the schema definition for user documents has become so big that's creating perf problems.

This PR tries to improve the situation by not defining every single items the user can have as a field in mongoose and instead use several mixed containers.

From some local testing this seems to improve the average loading time for user documents from ~55ms to ~9ms (vs ~2ms when using mongoose `.lean()` option)

It's a WIP and shouldn't be merged yet

Ready for testing

### CODE REVIEW

**Comment by paglias** [comment]
The following screenshots are a list of all places affected by this change

**Comment by SabreCat** [comment]
Ooh, good to see you've gotten a chance to circle back to this. How close is it getting?

**Comment by paglias** [comment]
Fixed issue with the validation in the hall controller

**Comment by paglias** [comment]
Added tests

**Comment by paglias** [comment]
Should be ready for testing!

**Pull request merged**
