### PR TITLE
Fixed issue with filters div that is bigger than containing div

### PR DESCRIPTION
**Pull request by crookedneighbor**
The combination of the col-md-12 class and the margin-left styling on the div with the ng-controller attribute "FiltersCtrl" was causing the width of the div to over-extend the width of the page. You can see it by scrolling to the right on the page, a small gap will appear.

gap

It's fixed by removing the col-md-12 class so that the filters class has a width of auto instead of 100% and adding padding-left: 15px and padding-right:15px to make up for the missing padding from that class.

### CODE REVIEW

**Comment by lefnire** [comment]
LGTM! @benmanley any objections? Else I'll merge

**Comment by benmanley** [comment]
@crookedneighbor Looks good, but it seemed to remove some of the space between the tags and the task columns when I tested it. Could you try this in filters.styl?

``` sass
.filters
  padding: 1em 1.382em 0.382em
  // Clearfix
  &:after {
    content: "";
    display: table;
    clear: both;
  }
  ul ...
```

**Comment by crookedneighbor** [comment]
@benmanley You're right, it did remove a little bit of the spacing at the top and bottom, but making the padding-left and right 1.382em causes a 5px gap to appear on the left side. Since all the other padding for the other elements is using Bootstrap, I'd make the left and right padding 15px, so it matches exactly:

screen

I've updated the filters.styl with your changes, but replacing the 1.382em with 15px in the padding and it looks great that way.

**Comment by crookedneighbor** [comment]
@lefnire @benmanley 
Anything else that needs to be done here?

**Comment by benmanley** [comment]
Sorry @crookedneighbor. I was hesitating as on my local install using 15px doesn’t line up correctly. Not sure why though.

@lefnire Do you want to merge this and then we’ll see how it looks on beta? Can always tweak the values.

**Comment by crookedneighbor** [comment]
@benmanley That's weird, looks perfect on mine.

**Comment by lefnire** [comment]
@benmanley sure thing, I'll push to beta now! (check in 10)

**Comment by lefnire** [comment]
@crookedneighbor ah yes of course, what's your UUID?

**Comment by crookedneighbor** [comment]
75f270e8-c5db-4722-a5e6-a83f1b23f76b

@lefnire Thanks, you're awesome.

**Comment by lefnire** [comment]
√

**Comment by benmanley** [comment]
Thanks @lefnire. 

Well done, @crookedneighbor – everything looks fine on beta.

**Comment by crookedneighbor** [comment]
@lefnire So, my friend badge says undefined next to it. It's supposed to be a number, right?
screen shot 2014-08-01 at 3 25 51 pm

**Comment by deilann** [comment]
Haha, no, it's supposed to say Blacksmith. @lefnire just forgot to set your
user title. I've fixed it now.

**Comment by crookedneighbor** [comment]
@deilann Awesome, thank you!

**Comment by SabreCat** [comment]
I like to keep a few undefined friends on hand. That way if I'm in a bind,
I can pencil in a value, and poof! Friend.

**Comment by deilann** [comment]
@SabreCat I am always sad at Github's lack of a :+1: button. However, I feel like most repos probably don't need it.

**Comment by Alys** [comment]
https://github.com/isaacs/github/issues/9#issuecomment-33878068 -> https://www.zenhub.io/
"Use +1 Instant Feedback to: 
Focus discussion, declutter GitHub comments
Boost team spirit with positive feedback
Track priorities, votes, and opinions with less meetings"

As we are all so painfully aware, this project could certainly do with fewer meetings! :)

Also https://github.com/artemave/github-plus-one

**Comment by deilann** [comment]
That's for issues, not comments. :(

**Comment by Alys** [comment]
No, I think it (zenhub) is for comments too. If you go to their (annoying)
website and scroll down carefully until you see the +1 feature description,
it looks in the video-thingy that someone is plussing comments.

**Comment by deilann** [comment]
That seems like effort.

**Comment by lefnire** [comment]
Matteo and use zenhub. Highly recommended, in particular it has kanban
workflowy (don't mess with me card states!)

**Pull request merged**
