### PR TITLE
Add themes

### PR DESCRIPTION
**Pull request by AdrienLemaire**
Design for theme selection needs to be reviewed. Otherwise, works fine like that. Create a new directory and new select option to add a new audio theme.

### CODE REVIEW

**Comment by AdrienLemaire** [comment]
@lefnire I think this is good to merge now. Note that a migration script has been added.

**Comment by lefnire** [comment]
Good stuff man. @paglias @Fandekasp @snicker, you guys are _really_ strong coders - and pick things up very fast. Glad you guys have joined :) :)

@Fandekasp Added you as repo member, so feel free to merge this (especially since it's on a separate branch anyway). You can merge the following without permission:
- hotfixes, bugs, non-controversial changes
- anything on a feature branch

Continue to PR big things, commits that you want one of us to notice, commits that have migrations, etc.

**Comment by lefnire** [comment]
(re: this migration script, we'll run it once we push live)

**Comment by AdrienLemaire** [comment]
Got it, thanks !

**Pull request merged**
