### PR TITLE
Blade hairlessbear quest invite modal on user sync

### PR DESCRIPTION
**Pull request by crookedneighbor**
Includes commits from @hairlessbear's PR: https://github.com/HabitRPG/habitrpg/pull/5298

Here's a diff between them: https://github.com/HabitRPG/habitrpg/compare/hairlessbear:quest_invite_modal_on_user_sync...crookedneighbor:blade-hairlessbear-quest_invite_modal_on_user_sync?expand=1

@paglias Everything works, I believe, but can I get your :eyes: on this before I merge it in?

### CODE REVIEW

**Comment by hairlessbear** [comment]
@crookedneighbor You may have thought of this already, but there's a potential deploy issue.

Here's the problem:
1) User is invited to a quest
2) New code is deployed
3) User logs in
4) The quest invite watch checks for `user.party.quest.RSVPNeeded`
5) `user.party.quest.RSVPNeeded` doesn't exist in the user because they were invited before invitations set this field
6) The invite modal doesn't pop up, and the user has no way of accepting or rejecting the quest

**Comment by crookedneighbor** [comment]
Good point, we would need to run a migration. 

That reminds me. I also want to put quest accept and reject buttons on the party page && make the party page fetch the party on load.

**Comment by hairlessbear** [comment]
Regarding making the party page fetch on load, would #4816 be a problem? I'm worried that those in large parties would never see the invitation statuses of some members.

Regarding putting the accept/reject buttons on the party page, if #5157 is going to be merged, we should probably add that functionality there instead of here, right?

Also, since you've now written the tests that you asked for in #5239, should that behavior be lumped into this PR?

**Comment by hairlessbear** [comment]
Actually, looking over the tests again, it looks like the watch tests you asked for aren't there after all. My bad.

**Comment by hairlessbear** [comment]
I'm currently working on the migration script; I'm assuming I should commit changes to this branch instead of the original one, right?

**Comment by crookedneighbor** [comment]
Your old branch is fine. In fact, I'm going to close this one and re-open yours. Just push up the changes I've made.

**Pull request closed without merging**
