### PR TITLE
Changed guild notification redirect to guilds/public instead of /guilds.

### LINKED ISSUE #4902: Notification for Guild invitation leads to a empty page
I've juste been invited to a guild. I received a notification that I can click. If I indeed click the notification, this leads me to https://habitrpg.com/#/options/groups/guilds, which looks like this:

screenshot - 23032015 - 00 29 20

This is on Firefox 36 on Xubuntu. I also tested it on Firefox Mobile and Chrome Mobile on Android Lollipop with the same result.

(The cache has obviously not been updated in this last screenshot, but the problem is the same after a refresh)

What strikes me in here is that, of all the guilds options (_Public Guilds_, guilds I already joined or _Create a Guild_), none of them is selected at this point.

Now, from this page, if I click on _Public Guilds_, I am then lead to https://habitrpg.com/#/options/groups/guilds/public, which tells me that I have been invited, and I can accept or reject (or browse public guilds). This looks like the page I should have arrived in the first place. I did not find another page which allows me to accept the invitation.

My understanding is that the link in the notification is incomplete and should add `/public` to lead the user to the right place. Or maybe I missed something obvious ?

### PR DESCRIPTION
**Pull request by gkjt**
Fixes #4902

### CODE REVIEW

**Comment by paglias** [comment]
Thanks! UUID?

**Comment by gkjt** [comment]
Thanks! 025a58cc-a69e-43ce-96ca-ceb7f4f3d568

**Comment by crookedneighbor** [comment]
Correct me if I'm wrong, but I thought the `guilds` page was for accepting invitations to guilds? The problem of course being that sometimes it didn't display the invitation notice? Having it change to `guilds/public` makes it so the page always displays, but then you have to search for the guild you were invited to. 

Does that sound correct? Or am I making that up?

**Comment by paglias** [comment]
I think the link always pointed to the public page and was broken just for
some days, and from there you have the list of your guilds in the top, even
the one you're invited to. Or not? I'll check when I'm home
Il 24/mar/2015 14:20 "Blade Barringer" notifications@github.com ha
scritto:

**Comment by paglias** [comment]
@crookedneighbor from #4902:

> Now, from this page, if I click on Public Guilds, I am then lead to https://habitrpg.com/#/options/groups/guilds/public, which tells me that I have been invited, and I can accept or reject (or browse public guilds). This looks like the page I should have arrived in the first place. I did not find another page which allows me to accept the invitation.

So it seems fine.

@gkjt tier++

**Comment by crookedneighbor** [comment]
Awesome, thanks for looking into it.

**Pull request merged**
