### PR TITLE
Fixed a community guidelines layout

### LINKED ISSUE #9878: Allow text wrapping on "I agree to follow the Community Guidelines" button
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
* UUID: 2d57fd14-0fd1-4bf5-abe9-d65bb42fbc6f
* Browser: Google Chrome 63.0.3239.132
* OS: Ubuntu 17.04

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
When the screen size is less than 1400 pixels, the text of the button goes beyond it

image

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

### PR DESCRIPTION
**Pull request by lex111**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #9878

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

I fixed the responsive grid, on large screens it will be the same as it was; as the screen decreases, the button and the block with the text will change, on small screens the button will be under the text.

image

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 2d57fd14-0fd1-4bf5-abe9-d65bb42fbc6f

### CODE REVIEW

**Comment by negue** [comment]
Works on the Party Page, could you also add the changes to `tavern.vue` ?

**Comment by lex111** [comment]
@negue ok, but can in this case encapsulate this into a individual component, so as not to duplicate the code?

**Comment by negue** [comment]
yes it should be a component, to be honest I didn't think that those are separated :( 

If you want to try and extract it to an own component, that would be great 👍

**Comment by lex111** [comment]
:ok_hand:

**Comment by lex111** [comment]
@negue everything is ready, you can check.

**Comment by negue** [comment]
LGTM :+1:

**Comment by SabreCat** [comment]
@lex111 Credited this along with the several other PRs you submitted. Thanks again!

**Pull request merged**
