### PR TITLE
Recompressed images

### PR DESCRIPTION
**Pull request by Olathe**
### File size reductions

Total change -463977

<table>
<tr><th>Size change</th><th>File path</th></tr>
<tr><td>-23299</td><td>public/img/screenshot.jpeg</td></tr>
<tr><td>-22766</td><td>public/img/play_screenshot.jpeg</td></tr>
<tr><td>-22208</td><td>public/img/unprocessed/8926c83e-70b8-11e2-88d6-8e114af266f9.gif</td></tr>
<tr><td>-18157</td><td>public/img/sprites/pet_sprites.png</td></tr>
<tr><td>-7574</td><td>public/img/unprocessed/bride/d09359ee-800d-11e2-92be-000b9ce042c2.gif</td></tr>
<tr><td>-6637</td><td>public/img/sprites/female_sprites.png</td></tr>
<tr><td>-6311</td><td>public/img/unprocessed/cat_ears/906bf600-81c0-11e2-9b89-8bde0a5209bc.png</td></tr>
<tr><td>-6228</td><td>public/img/unprocessed/cat_ears/95d8d428-81c0-11e2-89ef-24dc63060497.png</td></tr>
<tr><td>-6040</td><td>public/img/sprites/player_sprites105x.png</td></tr>
<tr><td>-5577</td><td>public/img/unprocessed/pets/8839ff22-8837-11e2-84ed-3998b99719b0.png</td></tr>
<tr><td>-4776</td><td>public/img/sprites/achievements.png</td></tr>
<tr><td>-4211</td><td>public/img/sprites/css_sprite.png</td></tr>
<tr><td>-4205</td><td>public/apple-touch-icon-144-precomposed.png</td></tr>
<tr><td>-4035</td><td>public/apple-touch-icon-114-precomposed.png</td></tr>
<tr><td>-3904</td><td>public/img/npcs/NPC-SpriteSheet.png</td></tr>
<tr><td>-3856</td><td>public/img/sprites/male_sprites.png</td></tr>
<tr><td>-3762</td><td>public/logo/habitrpg_pixel.png</td></tr>
<tr><td>-3760</td><td>public/img/logo/habitrpg_pixel.png</td></tr>
<tr><td>-3732</td><td>public/img/sprites/shop_sprites.png</td></tr>
<tr><td>-3688</td><td>public/img/logo/habitrpg.jpg</td></tr>
<tr><td>-3688</td><td>public/logo/habitrpg.jpg</td></tr>
<tr><td>-3541</td><td>public/apple-touch-icon-72-precomposed.png</td></tr>
<tr><td>-3477</td><td>public/img/unprocessed/wizard/f04973e2-7dbd-11e2-9f40-e6c166d2bbc7 (1).png</td></tr>
<tr><td>-3433</td><td>public/img/sprites/player_sprites.png</td></tr>
<tr><td>-3415</td><td>public/img/unprocessed/special/compstore kitties1.png</td></tr>
<tr><td>-3350</td><td>public/img/sprites/backer-only/BackerOnly-Shop-temporary.png</td></tr>
<tr><td>-3311</td><td>public/img/unprocessed/special/compstore hermes white.png</td></tr>
<tr><td>-3282</td><td>public/img/unprocessed/wizard/final/7aed8c94-8c3d-11e2-8197-db26cdcb1275.png</td></tr>
<tr><td>-3272</td><td>public/img/unprocessed/special/compstore hermes.png</td></tr>
<tr><td>-3259</td><td>public/img/unprocessed/wizard/2c40e622-8670-11e2-8363-55bf3fe07c92.png</td></tr>
<tr><td>-3256</td><td>public/apple-touch-icon-57-precomposed.png</td></tr>
<tr><td>-3256</td><td>public/apple-touch-icon-precomposed.png</td></tr>
<tr><td>-3254</td><td>public/img/unprocessed/special/compstore bunny1.png</td></tr>
<tr><td>-3248</td><td>public/img/unprocessed/special/compstore bunny light blue.png</td></tr>
<tr><td>-3236</td><td>public/img/unprocessed/special/compstore bunny pink.png</td></tr>
<tr><td>-3235</td><td>public/img/unprocessed/special/compstore bunny yellow.png</td></tr>
<tr><td>-3218</td><td>public/img/unprocessed/wizard/final/3a151098-8c3d-11e2-9b2d-b1fa78c39718.png</td></tr>
<tr><td>-3206</td><td>public/img/unprocessed/special/compstore bunny lavender.png</td></tr>
<tr><td>-3205</td><td>public/img/unprocessed/rogue/7911afd2-7111-11e2-899b-e17fa4b0f758.png</td></tr>
<tr><td>-3201</td><td>public/img/unprocessed/wizard/final/8a448746-8f0e-11e2-8763-4c4c7ab97775.png</td></tr>
<tr><td>-3195</td><td>public/img/unprocessed/armored_samurai/274333e6-7f1d-11e2-887d-157238988fb9.png</td></tr>
<tr><td>-3190</td><td>public/img/unprocessed/wizard/981aebd8-86c3-11e2-8856-bee7c4eaa60d.png</td></tr>
<tr><td>-3188</td><td>public/img/unprocessed/rogue/d96fa1b8-7d6e-11e2-97d2-35da41d621cc.png</td></tr>
<tr><td>-3167</td><td>public/img/unprocessed/rogue/dbae71de-7d6e-11e2-9ed4-e695eb852666.png</td></tr>
<tr><td>-3165</td><td>public/img/unprocessed/rogue/dcf2eb42-7d6e-11e2-96dd-5c943b1f26a9.png</td></tr>
<tr><td>-3140</td><td>public/img/unprocessed/wizard/final/86682dbc-8f0e-11e2-9f1c-a54959ffaa72.png</td></tr>
<tr><td>-3114</td><td>public/img/unprocessed/wizard/f5653fc6-7d60-11e2-96f4-d6c887747abc.png</td></tr>
<tr><td>-3106</td><td>public/img/unprocessed/rogue/79016b86-7111-11e2-90e4-ad4483d9d0fa.png</td></tr>
<tr><td>-3077</td><td>public/img/unprocessed/gladiator/2414bd4c-7f0a-11e2-8522-9becf9bdf198.png</td></tr>
<tr><td>-3070</td><td>public/img/sprites/Egg_Sprite_Sheet.png</td></tr>
<tr><td>-3057</td><td>public/img/unprocessed/rogue/78aa437e-7111-11e2-97b5-1f1d1e2b99e0.png</td></tr>
<tr><td>-3053</td><td>public/img/unprocessed/wizard/df8f8496-704e-11e2-8511-3170ca6c0df2.png</td></tr>
<tr><td>-3047</td><td>public/img/unprocessed/robed_samurai/a4dd91d8-7f14-11e2-9302-7b378721bb9b.png</td></tr>
<tr><td>-3046</td><td>public/img/unprocessed/wizard/1d9e2166-8670-11e2-9b44-7e58fa80c479.png</td></tr>
<tr><td>-3042</td><td>public/img/unprocessed/rogue/d665bcaa-7d6e-11e2-8389-ad021a8995e6.png</td></tr>
<tr><td>-3042</td><td>public/img/unprocessed/rogue/e091be2c-7d6e-11e2-99d7-6cdca4393a65.png</td></tr>
<tr><td>-3040</td><td>public/img/unprocessed/wizard/e34309a0-7d6e-11e2-841b-e54bddb82577.png</td></tr>
<tr><td>-3030</td><td>public/img/unprocessed/rogue/d7a969cc-7d6e-11e2-8ae6-4bfc48340897.png</td></tr>
<tr><td>-3030</td><td>public/img/unprocessed/wizard/1653261e-7dbe-11e2-9905-1746529f137b.png</td></tr>
<tr><td>-3007</td><td>public/img/unprocessed/armored_samurai/18f83282-7f1d-11e2-9605-686c0f6603be.png</td></tr>
<tr><td>-3005</td><td>public/img/unprocessed/wizard/eb37ac0c-7d5e-11e2-8ab8-eb061afe4082.png</td></tr>
<tr><td>-3002</td><td>public/img/unprocessed/wizard/f9700c38-7d5e-11e2-8914-d456c3c0ece0.png</td></tr>
<tr><td>-3001</td><td>public/img/unprocessed/wizard/f1e7c3c0-7d5e-11e2-8857-b58547e05c76.png</td></tr>
<tr><td>-3000</td><td>public/img/unprocessed/wizard/8c23270a-7d5e-11e2-9ca0-60b5ef2de784.png</td></tr>
<tr><td>-2999</td><td>public/img/unprocessed/wizard/e55999e8-7c7e-11e2-80f7-c4d91580bf60.png</td></tr>
<tr><td>-2993</td><td>public/img/unprocessed/rogue/e2088d76-7d6e-11e2-9488-0bd0f499213c.png</td></tr>
<tr><td>-2991</td><td>public/img/unprocessed/wizard/final/80f159d6-8c3d-11e2-89c6-e7ec50cd4a85.png</td></tr>
<tr><td>-2987</td><td>public/img/sprites/Mount-SpriteSheet.png</td></tr>
<tr><td>-2985</td><td>public/img/unprocessed/wizard/638eb6ce-7d5e-11e2-9bcc-0e3de0e4d484.png</td></tr>
<tr><td>-2983</td><td>public/img/unprocessed/wizard/4ac3b2c0-7d5e-11e2-928a-9ab34f91ce77.png</td></tr>
<tr><td>-2983</td><td>public/img/unprocessed/wizard/5cb7a96e-7d5e-11e2-99d0-f9a52eb29c27.png</td></tr>
<tr><td>-2981</td><td>public/img/unprocessed/wizard/20445f76-7dbe-11e2-9f63-a80d7a8caa47.png</td></tr>
<tr><td>-2978</td><td>public/img/unprocessed/wizard/d318da56-7d5e-11e2-9d79-79ea485542c9.png</td></tr>
<tr><td>-2976</td><td>public/img/unprocessed/wizard/final/e002d874-8c3c-11e2-96ad-16523c29bd32.png</td></tr>
<tr><td>-2974</td><td>public/img/unprocessed/wizard/cba70400-7d5e-11e2-8e7a-1c216a2074e1.png</td></tr>
<tr><td>-2971</td><td>public/img/unprocessed/wizard/0a8db056-7c7e-11e2-8cc3-743d54724f15.png</td></tr>
<tr><td>-2970</td><td>public/img/unprocessed/wizard/e71ce75e-7c7d-11e2-9d15-635aaff4e8d1.png</td></tr>
<tr><td>-2970</td><td>public/img/unprocessed/wizard/f1bac41a-7c7d-11e2-90f3-f2f53b5e2a00.png</td></tr>
<tr><td>-2969</td><td>public/img/unprocessed/wizard/0c731010-7d5e-11e2-85b1-63b96dc716e7.png</td></tr>
<tr><td>-2964</td><td>public/img/unprocessed/wizard/40c01002-7d5e-11e2-8226-b8cde96483aa.png</td></tr>
<tr><td>-2961</td><td>public/img/unprocessed/rogue/300cde96-704f-11e2-95f1-25d59dee29c2.png</td></tr>
<tr><td>-2955</td><td>public/img/unprocessed/wizard/1fa8bc34-7d5e-11e2-8ba9-7cc5d914c82a.png</td></tr>
<tr><td>-2949</td><td>public/img/unprocessed/wizard/056fe680-7d5e-11e2-995d-92d377750e12.png</td></tr>
<tr><td>-2930</td><td>public/img/unprocessed/armored_samurai/2a920c8e-7f1d-11e2-9656-d4b63e736b26.png</td></tr>
<tr><td>-2930</td><td>public/img/unprocessed/wizard/3bb788ae-8670-11e2-842a-315c136bb7bc.png</td></tr>
<tr><td>-2930</td><td>public/img/unprocessed/wizard/9b44e94e-86c3-11e2-9aa9-a0a999d60f4c.png</td></tr>
<tr><td>-2929</td><td>public/img/unprocessed/immortal/a23653d0-7f36-11e2-8993-7146e23b80d2.png</td></tr>
<tr><td>-2923</td><td>public/img/unprocessed/wizard/final/3fee9142-8c3d-11e2-9e55-a1034a05deba.png</td></tr>
<tr><td>-2922</td><td>public/img/unprocessed/immortal/a267e12a-7f36-11e2-8cc3-3b7ef849783c.png</td></tr>
<tr><td>-2921</td><td>public/img/npcs/ian.gif</td></tr>
<tr><td>-2919</td><td>public/img/unprocessed/bride/d1120898-800d-11e2-9fea-be1dc75b04ce.gif</td></tr>
<tr><td>-2917</td><td>public/img/unprocessed/armored_samurai/193a14b8-7f1d-11e2-991a-2897b90a61c4.png</td></tr>
<tr><td>-2906</td><td>public/img/unprocessed/robed_samurai/a4ade7e4-7f14-11e2-8aa2-c3b501009e1a.png</td></tr>
<tr><td>-2899</td><td>public/img/unprocessed/wizard/final/1ac07976-8c3d-11e2-8be6-b20569cccbbc.png</td></tr>
<tr><td>-2887</td><td>public/img/unprocessed/wizard/1b4e12c8-7dbe-11e2-8a37-ae0693395de9.png</td></tr>
<tr><td>-2869</td><td>public/img/unprocessed/robed_samurai/a50d855a-7f14-11e2-8cb6-096ba49e0084.png</td></tr>
<tr><td>-2867</td><td>public/img/unprocessed/gladiator/245a7d3c-7f0a-11e2-9aab-f5ad8aeeff98.png</td></tr>
<tr><td>-2855</td><td>public/img/unprocessed/gladiator/2441dfe8-7f0a-11e2-8289-74dc99e5d9cb.png</td></tr>
<tr><td>-2853</td><td>public/img/unprocessed/immortal/a2986c6e-7f36-11e2-8858-f817af009adb.png</td></tr>
<tr><td>-2851</td><td>public/img/unprocessed/immortal/a2ba320e-7f36-11e2-9bc6-d0a02b66408c.png</td></tr>
<tr><td>-2825</td><td>public/img/unprocessed/wizard/22967a7e-8670-11e2-8306-f9c38bc4d573.png</td></tr>
<tr><td>-2821</td><td>public/img/unprocessed/robed_samurai/a53c91f6-7f14-11e2-98c0-d9ca8adfd77f.png</td></tr>
<tr><td>-2816</td><td>public/img/unprocessed/gladiator/23e7ab0e-7f0a-11e2-9d36-bfab6944f6b7.png</td></tr>
<tr><td>-2796</td><td>public/img/unprocessed/gladiator/2454557e-7f0a-11e2-98e9-364700741380.png</td></tr>
<tr><td>-2495</td><td>public/img/unprocessed/c9633120-8dab-11e2-8291-73b4993357a0.png</td></tr>
<tr><td>-2372</td><td>public/img/sprites/backer-only/BackerOnly-SpriteSheet.png</td></tr>
<tr><td>-2029</td><td>public/img/glyphicons-halflings.png</td></tr>
<tr><td>-1914</td><td>public/img/unprocessed/79cace6c-8512-11e2-87f4-fff9639ec4cb.gif</td></tr>
<tr><td>-1871</td><td>public/img/sprites/backer-only/BackerOnly-Weapon-DarkSoulsBlade.gif</td></tr>
<tr><td>-1658</td><td>public/img/sprites/dead.png</td></tr>
<tr><td>-1633</td><td>public/img/unprocessed/272fa94c-8338-11e2-80f8-eba642a48a63.png</td></tr>
<tr><td>-1520</td><td>public/img/unprocessed/957247ce-70a6-11e2-839c-96add9efa68d.png</td></tr>
<tr><td>-1439</td><td>public/img/unprocessed/efbd21c4-82a1-11e2-8190-fbc609b5c58b.png</td></tr>
<tr><td>-1416</td><td>public/img/unprocessed/70470c0c-70b8-11e2-9448-a2ac8b8779d1.png</td></tr>
<tr><td>-1404</td><td>public/img/unprocessed/ff218da6-7ff6-11e2-90a5-691ce50f46a2.gif</td></tr>
<tr><td>-1254</td><td>public/vendor/jquery-ui-1.10.2/demos/images/pbar-ani.gif</td></tr>
<tr><td>-1254</td><td>public/vendor/jquery-ui-1.10.2/demos/progressbar/images/pbar-ani.gif</td></tr>
<tr><td>-1190</td><td>public/img/unprocessed/dragon_hunter/2e6af9d6-80aa-11e2-8c2e-812b03736b26.gif</td></tr>
<tr><td>-1130</td><td>public/img/unprocessed/dragon_hunter/e854c3b4-80a9-11e2</td></tr>
<tr><td>-1128</td><td>public/img/unprocessed/backer/ab1da3a4-77b6-11e2-95c0-5e5e3300f202.gif</td></tr>
<tr><td>-1086</td><td>public/img/unprocessed/backer/96c696a0-7f8f-11e2-9bf9-5e67f9e4ed85.gif</td></tr>
<tr><td>-1061</td><td>public/img/unprocessed/backer/6c742fa6-7801-11e2-8ce2-02ca676c031d.gif</td></tr>
<tr><td>-1053</td><td>public/img/unprocessed/pets/7beaf3ee-805c-11e2-994f-a8158102048c.gif</td></tr>
<tr><td>-1036</td><td>public/logo/HABITRPG-logo-version-1.gif</td></tr>
<tr><td>-1000</td><td>public/vendor/bootstrap/img/glyphicons-halflings.png</td></tr>
<tr><td>-815</td><td>public/vendor/jquery-ui-1.10.2/demos/tooltip/images/tower-bridge.jpg</td></tr>
<tr><td>-813</td><td>public/vendor/jquery-ui-1.10.2/demos/tooltip/images/st-stephens.jpg</td></tr>
<tr><td>-706</td><td>public/img/npcs/justin.png</td></tr>
<tr><td>-677</td><td>public/vendor/jquery-ui-1.10.2/themes/base/minified/images/ui-icons_2e83ff_256x240.png</td></tr>
<tr><td>-677</td><td>public/vendor/jquery-ui-1.10.2/themes/base/minified/images/ui-icons_cd0a0a_256x240.png</td></tr>
<tr><td>-676</td><td>public/vendor/jquery-ui-1.10.2/themes/base/images/ui-icons_2e83ff_256x240.png</td></tr>
<tr><td>-676</td><td>public/vendor/jquery-ui-1.10.2/themes/base/images/ui-icons_cd0a0a_256x240.png</td></tr>
<tr><td>-545</td><td>public/img/sprites/backer-only/BackerOnly-Pet-CerberusPup.gif</td></tr>
<tr><td>-435</td><td>public/img/sprites/backer-only/BackerOnly-Shield-TormentedSkull.gif</td></tr>
<tr><td>-391</td><td>public/img/unprocessed/pets/b13c795c-6f2a-11e2-8be9-dec462891e6f.png</td></tr>
<tr><td>-389</td><td>public/img/facebook-login-register.jpeg</td></tr>
<tr><td>-326</td><td>public/img/npcs/justin-face.png</td></tr>
<tr><td>-211</td><td>public/vendor/jquery-ui-1.10.2/themes/base/images/ui-icons_222222_256x240.png</td></tr>
<tr><td>-207</td><td>public/vendor/jquery-ui-1.10.2/themes/base/minified/images/ui-icons_222222_256x240.png</td></tr>
<tr><td>-202</td><td>public/vendor/jquery-ui-1.10.2/themes/base/images/ui-icons_454545_256x240.png</td></tr>
<tr><td>-201</td><td>public/vendor/jquery-ui-1.10.2/themes/base/minified/images/ui-icons_454545_256x240.png</td></tr>
<tr><td>-201</td><td>public/vendor/jquery-ui-1.10.2/themes/base/minified/images/ui-icons_888888_256x240.png</td></tr>
<tr><td>-200</td><td>public/vendor/jquery-ui-1.10.2/themes/base/images/ui-icons_888888_256x240.png</td></tr>
<tr><td>-192</td><td>public/favicon.ico</td></tr>
<tr><td>-189</td><td>public/img/PixelPaw002.png</td></tr>
<tr><td>-177</td><td>public/img/coin_single_silver.png</td></tr>
<tr><td>-164</td><td>public/img/sprites/favicon.png</td></tr>
<tr><td>-124</td><td>public/img/PixelPaw.png</td></tr>
<tr><td>-73</td><td>public/img/coin_single_gold.png</td></tr>
<tr><td>-69</td><td>public/img/calendar_ical.png</td></tr>
<tr><td>-68</td><td>public/vendor/jquery-ui-1.10.2/demos/autocomplete/images/jquery_32x32.png</td></tr>
<tr><td>-67</td><td>public/vendor/jquery-ui-1.10.2/themes/base/images/ui-bg_flat_0_aaaaaa_40x100.png</td></tr>
<tr><td>-67</td><td>public/vendor/jquery-ui-1.10.2/themes/base/images/ui-bg_flat_75_ffffff_40x100.png</td></tr>
<tr><td>-67</td><td>public/vendor/jquery-ui-1.10.2/themes/base/minified/images/ui-bg_flat_0_aaaaaa_40x100.png</td></tr>
<tr><td>-67</td><td>public/vendor/jquery-ui-1.10.2/themes/base/minified/images/ui-bg_flat_75_ffffff_40x100.png</td></tr>
<tr><td>-41</td><td>public/img/sprites/backer-only/BackerOnly-Equip-ShadeArmor.gif</td></tr>
<tr><td>-29</td><td>public/img/sprites/backer-only/BackerOnly-Equip-ShadeHelmet.gif</td></tr>
<tr><td>-29</td><td>public/img/unprocessed/dragon_hunter/ed357a86-80a9-11e2-997f-35c1841e1688.gif</td></tr>
<tr><td>-28</td><td>public/img/calendar_google.png</td></tr>
<tr><td>-28</td><td>public/vendor/jquery-ui-1.10.2/demos/autocomplete/images/transparent_1x1.png</td></tr>
<tr><td>-25</td><td>public/vendor/jquery-ui-1.10.2/demos/autocomplete/images/ui-anim_basic_16x16.gif</td></tr>
<tr><td>-21</td><td>public/img/sprites/backer-only/BackerOnly-Equip-CrystalHelmet.gif</td></tr>
<tr><td>-14</td><td>public/img/bs-docs-masthead-pattern.png</td></tr>
<tr><td>-13</td><td>public/vendor/jquery-ui-1.10.2/themes/base/images/ui-bg_glass_65_ffffff_1x400.png</td></tr>
<tr><td>-13</td><td>public/vendor/jquery-ui-1.10.2/themes/base/minified/images/ui-bg_glass_65_ffffff_1x400.png</td></tr>
<tr><td>-11</td><td>public/vendor/jquery-ui-1.10.2/demos/autocomplete/images/jqueryui_32x32.png</td></tr>
<tr><td>-11</td><td>public/vendor/jquery-ui-1.10.2/tests/unit/images/jqueryui_32x32.png</td></tr>
<tr><td>-11</td><td>public/vendor/jquery-ui-1.10.2/themes/base/images/ui-bg_glass_75_dadada_1x400.png</td></tr>
<tr><td>-11</td><td>public/vendor/jquery-ui-1.10.2/themes/base/minified/images/ui-bg_glass_75_dadada_1x400.png</td></tr>
<tr><td>-10</td><td>public/img/sprites/backer-only/BackerOnly-Equip-CrystalArmor.gif</td></tr>
<tr><td>-10</td><td>public/vendor/bootstrap/img/glyphicons-halflings-white.png</td></tr>
<tr><td>-9</td><td>public/vendor/jquery-ui-1.10.2/themes/base/images/ui-bg_glass_55_fbf9ee_1x400.png</td></tr>
<tr><td>-9</td><td>public/vendor/jquery-ui-1.10.2/themes/base/images/ui-bg_glass_75_e6e6e6_1x400.png</td></tr>
<tr><td>-9</td><td>public/vendor/jquery-ui-1.10.2/themes/base/minified/images/ui-bg_glass_55_fbf9ee_1x400.png</td></tr>
<tr><td>-9</td><td>public/vendor/jquery-ui-1.10.2/themes/base/minified/images/ui-bg_glass_75_e6e6e6_1x400.png</td></tr>
<tr><td>-6</td><td>public/img/glyphicons-halflings-white.png</td></tr>
<tr><td>-6</td><td>public/vendor/jquery-ui-1.10.2/themes/base/images/ui-bg_glass_95_fef1ec_1x400.png</td></tr>
<tr><td>-6</td><td>public/vendor/jquery-ui-1.10.2/themes/base/minified/images/ui-bg_glass_95_fef1ec_1x400.png</td></tr>
<tr><td>-5</td><td>public/vendor/jquery-ui-1.10.2/themes/base/images/ui-bg_highlight-soft_75_cccccc_1x100.png</td></tr>
<tr><td>-5</td><td>public/vendor/jquery-ui-1.10.2/themes/base/minified/images/ui-bg_highlight-soft_75_cccccc_1x100.png</td></tr>
<tr><td>-4</td><td>public/vendor/jquery-ui-1.10.2/demos/autocomplete/images/sizzlejs_32x32.png</td></tr>
<tr><td>-1</td><td>public/img/unprocessed/bride/d0d1c5f8-800d-11e2-869c-46f3ce3925f2.gif</td></tr>
</table>

### CODE REVIEW

**Comment by Olathe** [comment]
@Pandoro or @Shaners, can you please verify that the recompression made no changes to appearance?

Also, is this the correct repo to be compressing or is something like [HabitRPG/habitrpg-shared](https://github.com/HabitRPG/habitrpg-shared) better?

**Comment by lefnire** [comment]
I'll get back to you on this, with the rewrite and mobile current progress
kinda redefining habitrpg-shared, that will likely be the future place to
handle this stuff. But for the meantime it's all amuck

**Comment by Pandoro** [comment]
Sorry I haven't answered yet. From what I remembered from the discussions a
while back, it was close to perfect, I just didn't see the real point of
it. The worst part I didn't like about it was that you need to manually
take care about it after every change ;)

Since we need to keep the originials anyways, just do it and submit them
under a different name. I think it will be well worth it, especially for
the mobile version where 100kb difference might be an expensive thing ;)

**Comment by lefnire** [comment]
On thing - on mobile, we're using `grunt build` which runs images through [imgmin](https://github.com/rflynn/imgmin) automatically for compression (and renaming is unnecessary since it creates a deployable `dist/` directory separate from the main `app/` dir). We should compare the quality of your output with imgmin at some point, because the latter could save us some cycles as an automated build step

**Comment by lefnire** [comment]
We'll be using imgmin after all, since we've not got Grunt baked pretty well into our workflow. Thanks for the PR though @Olathe , sorry to not merge it!

**Pull request closed without merging**
