### PR TITLE
Optional feedback on account deletion

### LINKED ISSUE #7942: optional feedback in account deletion confirmation screen
When a player goes to Settings > Site to delete their Habitica account, they are given a confirmation modal. The modal should contain a textarea for **optional** feedback about Habitica (e.g., what they didn't like, why they decided to stop using it).

The API route ("Delete an authenticated user's account") should also accept an optional feedback message.

The feedback should be emailed to admin@habitica.com. It does not need to be stored in the database.

The words describing the textarea should ask if the player would like to give any feedback, should emphasise that it's optional, and should say that it can be in whichever language the player feels comfortable with (does not have to be English).

### PR DESCRIPTION
**Pull request by SabreCat**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #7942.

Continuation of https://github.com/HabitRPG/habitica/pull/7985. @JSchneidler, if you'd like to resume work on this, comment here!

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

* Adds a text field for feedback when a user deletes their account. Information entered there is emailed to the tech assistance email address.
* Adds integration tests for the delete user API route covering the above, as well as one missing test for a null password sent. Some minor refactoring of validation errors was done to facilitate this.

---

UUID: b1f8093a-76b7-4f80-95ce-5c00bec74c0a

### CODE REVIEW

**Comment by SabreCat** [comment]
Addressed the outstanding comments from the prior PR. @Alys @paglias, does this resolve your concerns from back there? If so, please sign off review!

I will credit @JSchneidler when this is merged, as I only tidied up a couple of comments from the end of the thread there.

**Comment by Alys** [comment]
It resolves my comments from the old PR. Thanks @SabreCat !

**Review by paglias — APPROVED** [review]
@SabreCat looks good, the only thing: why was the code using req..checkBody changed with manual checks? It works as well but I was wondering if there was a specific reason

**Comment by SabreCat** [comment]
@paglias: For whatever reason, `req.body` would not throw its specific errors during tests. It always returned the generic failed-validation error. 🤔 In manual testing, I'd get the correct error in the notification growl, but in tests it never seemed to show. (I wonder if that's why we didn't have a test for that case before either?)

**Comment by SabreCat** [comment]
@JSchneidler Late though it is (with our apologies), I've raised your contributor tier to 2! Thank you for your PR.

**Comment by paglias** [comment]
@SabreCat yes req.checkBody shows a generic error message but if I remember correctly it also has an errors prop with more detailed messages (for future reference)

**Pull request merged**
