### PR TITLE
Implements Dailies repeat every X days since last completion  (Fixes #6941) [reverted for extra testing]

### LINKED ISSUE #6941: Repeat Every X Days Since Last Completed
In the 'Repeat' section under 'Advanced Options' for a Daily, it'd be great to have an entry called something like 'Every X Days Since Last Completed'.  This should add a Daily that becomes active on the specified 'Start Date' and, upon completion, gets scheduled for X days from the completion date.  It should remain active and count as a missed Daily every day until it is completed.  If it is checked while not active, the Daily should be scheduled for X days from the date of being checked.

Example use cases:
- Cleaning bathrooms once every month
- Replacing your home air filter once every three months
- Getting a free credit check once every four months

There has been a lot of discussion about implementing something like this on the Trello card linked to below, and there isn't a clear consensus about how this and similar features (Ex: repeat every X days, but have the Daily remain active until completed) should be implemented.  The approach described above seems reasonable, though, and is in line with what sites like Todoist do (they have the 'every' keyword tied to repeat every X days and 'every!' which would be the equivalent to this feature.)  Anyway, I wanted to make a ticket for this functionality and post a bounty to encourage someone to implement it unless there are serious reservations about adding this.

https://trello.com/c/q7uM2Ymq/92-dailies-v-3-dailies-minimum-does-not-apply-button-weekly-rolling-over-streak-history

[Bountysource](https://www.bountysource.com/issues/32123883-repeat-every-x-days-since-last-completed?utm_source=32123883&utm_medium=shield&utm_campaign=ISSUE_BADGE)

### PR DESCRIPTION
**Pull request by asifmallik**
fixes https://github.com/HabitRPG/habitica/issues/6941

### Changes

- Implemented repeat after completion for both the new and old UI
- Added tests for the feature in shouldDo.test.js

UUID: bc6a5bb0-b458-4526-b822-a1e63c581ce4

### CODE REVIEW

**Comment by librarianmage** [comment]
@asifmallik Please keep in mind that people usually request to work on an Issue before working on it. This way, multiple people don't start working on it and feel frustrated when a person "steals" their Issue that they asked to work on.

**Comment by asifmallik** [comment]
@MathWhiz I am sorry, I will always request before starting from next time.

**Comment by librarianmage** [comment]
Also, keep in mind that PRs are not going to be accepted until the new client redesign is out.

**Comment by SabreCat** [comment]
@asifmallik, you can remove the old client files here! Then we'll look into getting it reviewed and merged for the updated site.

**Comment by librarianmage** [comment]
Should they also remove the "fixes" line, as the issue has expanded to fill
more than just "X after completion"?

**Comment by SabreCat** [comment]
@MathWhiz, no, I think that's still fair--we can move the additional feature requests to a new ticket.

**Comment by librarianmage** [comment]
I can do that!

**Comment by SabreCat** [comment]
@asifmallik, how are things going with the requested update? Looks like it might be a good idea to merge `develop` and resolve conflicts, too!

**Comment by asifmallik** [comment]
@SabreCat I will get right on it!

**Comment by SabreCat** [comment]
@asifmallik Thanks much for this, and welcome to the ranks of the Blacksmiths! I've awarded you your first contributor tier. We'll spend a couple weeks using this feature in a staging environment before it goes live, but if all goes well you'll see your work in action soon!

@MathWhiz A note since you're working on the broader features here--this only implemented Every X Days. It hasn't yet been generalized to allow Every X Weeks or Every X Months, which would still be handy!

**Comment by Alys** [comment]
We're still testing this on a test website, but in addition, we're also going to hold off on deploying it to production until:
- we've modified the cron code that runs when the player is resting in the inn (currently Dailies that use these new scheduling options aren't re-scheduled when the player is resting)
- we've updated the mobile apps to support the new scheduling options 
- Tressley and paglias have finished some design improvements to the tasks page which will affect how the new options are laid out

**Comment by paglias** [comment]
The new design has just been merged in develop, this code will have to be changed

```
          template(v-if="task.frequency === 'daily'")
            .form-check
              label.custom-control.custom-checkbox
                input.custom-control-input(type="checkbox", v-model="task.repeatAfterCompletion")
                span.custom-control-indicator
                span.custom-control-description {{ $t('repeatAfterCompletionTitle', {everyX: task.everyX}) }}
```

to something like this

```
          template(v-if="task.frequency === 'daily'")
            .form-check
              .custom-control.custom-checkbox.custom-control-inline
                input.custom-control-input(type='checkbox',  v-model="task.repeatAfterCompletion", id="repeatAfterCompletion")
                label.custom-control-label(for="repeatAfterCompletion") {{ $t('repeatAfterCompletionTitle', {everyX: task.everyX}) 
```

Which branch should be edited for this change?

**Comment by Alys** [comment]
I'm working on merging `develop` into this, including making the changes paglias requested above.
I'll then do some local testing to make sure it's still working and create a new PR (being sure to link back to this one and credit @asifmallik). 
We can then push it to the test site and let the Socialites test it again.

@SabreCat Do you remember if any changes were made to the test site (gamma I think) that aren't in this PR (excluding all the regular updates from develop of course)? I.e., is there any code directly related to this PR that I should change in my copy of the PR?

Once this is all tested and confirmed working correctly, before it can be released to production we'll need to update the mobile apps to support the new scheduling options (in my PR I'll post a screenshot of the new options to help with the design changes for the apps).
The other blockers from the earlier comments have been done (cron modifications and design improvements).

If anyone thinks of other things that should be changed before this can go live, please post here!

**Comment by Alys** [comment]
Oh @SabreCat no need to look into my question on the weekend! I'll have enough to keep me busy today without an answer. :)

**Comment by SabreCat** [comment]
@Alys: If there had been anything, it'd be on the PR, so I think you're clear!

**Comment by Alys** [comment]
This is continued in https://github.com/HabitRPG/habitica/pull/10854 
I've made minor changes there to bring the PR up to date with `develop`

**Pull request merged**
