### PR TITLE
Hide chat notification

### PR DESCRIPTION
**Pull request by AdrienLemaire**
I found annoying that I needed to click on the notification menu to check whether I had new messages or not.
So I updated the code to hide to notification button unless there is a new message to display.

### CODE REVIEW

**Comment by AdrienLemaire** [comment]
very simple change, and useful, I hope it can be merged soon, thanks :)

**Comment by SabreCat** [comment]
Fix to #3270? Sweet! There's a (small) bounty there for you to claim, if this works out!

**Comment by Alys** [comment]
This looks like it will hide the notification icon when there's no new messages even when there are other reasons to show the icon (e.g., invitations, mystery items being available). For users that are not currently in any party or guild, this would mean that they never see any notifications. But I might be wrong. :) @Fandekasp can you check that?

**Comment by AdrienLemaire** [comment]
Nice catch @Alys , fixed.

**Comment by AdrienLemaire** [comment]
@lefnire this PR is an easy one, would be nice if it could be released with the sound!

**Comment by lefnire** [comment]
I'll check it out when I can. We're cutting back on these function watchers, as they're called every digest cycle causing major performance issues. Better we have a [watchGroup](https://docs.angularjs.org/api/ng/type/$rootScope.Scope#$watchGroup) on the variables which will change, and update a scope variable accordingly.

**Comment by AdrienLemaire** [comment]
I see

**Comment by paglias** [comment]
@Fandekasp we already have a different icon when there aren't messages to read (the same icon less bright) the problem is that except for new users we have a problem in the database that prevent it from working, there is a ticket somewhere

**Comment by Alys** [comment]
The existing code to change the notification button can be fixed easily by deleting User.user.newMessages[gid] instead of setting newMessages[gid].value to false (see my comments in https://github.com/HabitRPG/habitrpg/issues/3270). I can finish that in a few days if no one else wants to take it on.

**Comment by AdrienLemaire** [comment]
Thanks @Alys !

**Comment by paglias** [comment]
@Alys I think the problem isn't that we set false instead of deleting but that for some reasons there are values with key undefined in the database and while I fixed the code that made those values we can't really remove them from the database, @lefnire run a lot of migrations without success, see https://github.com/HabitRPG/habitrpg/issues/3270#

**Comment by paglias** [comment]
@Alys  sorry link is https://github.com/HabitRPG/habitrpg/issues/3270#issuecomment-41032939

**Comment by Alys** [comment]
@paglias : See these comments:
https://github.com/HabitRPG/habitrpg/issues/3270#issuecomment-51696497
https://github.com/HabitRPG/habitrpg/issues/3270#issuecomment-51696776
https://github.com/HabitRPG/habitrpg/issues/3270#issuecomment-51698852

The "undefined" guild problem is fixable by adding the "if (gid)" statement that I wrote about. It's not a database problem as such, it's just that the incorrect entry keeps on being readded.

**Comment by paglias** [comment]
@Alys you're right, sorry!

**Comment by Alys** [comment]
I've fixed the underlying bug that prevented the existing styles from changing the notification button from black to grey: https://github.com/HabitRPG/habitrpg/pull/3907

**Comment by lefnire** [comment]
@Alys is your recent merge + this PR mutually-exclusive? (Should we close this?)

**Comment by Alys** [comment]
Yes, this PR isn't needed now that my change has been merged. I believe this can be closed.

**Pull request closed without merging**
