### PR TITLE
Valentine's Day

### LINKED ISSUE #4646: Hair color selection buttons are inconsistent
The baseline hair colors use simple color swatches for their buttons, while all subsequent hair colors have sprite previews of what they look like on their buttons. This is inconsistent and a little odd, especially if you happen to have the earliest premium hair colors available right next to them:

image

I know I frequently find myself thinking, "wait, where are the normal colors?" before I realize the brown box is the thing I'm looking for. We should update the baseline hair colors to use the same style of button as everything else.

### PR DESCRIPTION
**Pull request by SabreCat**
- Reimplements Valentine's Day cards, including a new poem
- Holiday cards now silent in party chat
- Adds notifications for holiday cards
- Makes poem strings available for translation
- Fixes some hairstyle sprites not correctly implemented
- Fixes https://github.com/HabitRPG/habitrpg/issues/4646
- Bailey news for the above and a correction to the previous news

### CODE REVIEW

**Comment by crookedneighbor** [comment]
I just checked out the branch, the only thing I've noticed so far is that it's possible to give a valentines card to yourself. Not sure if that was intended behavior (didn't check to see if the NYE cards behaved the same way).

**Comment by SabreCat** [comment]
You can do that, aye - when I did New Years, I fixed an issue where that
would award two achievements. We could change it, but it would make people
without parties sad.

**Comment by crookedneighbor** [comment]
Cool. Looks good to me then.

**Comment by lemoness** [comment]
Yep, giving a Valentine to yourself is intended!

Making the poems translatable is a great idea :)

**Pull request merged**
