### PR TITLE
Refactoring & Feature: edit/delete controls of tasks

### PR DESCRIPTION
**Pull request by Xaz16**
[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Improve https://github.com/HabitRPG/habitica/pull/11349#issuecomment-529470815

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

- Remove showOption from tasks props
- Pass all needed data to task for understand in mapGetter function which controls we should show
- Improve current solution with edit and delete logic

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: d94eca66-c6de-423c-a864-9cb103b9eb77

### CODE REVIEW

**Comment by Xaz16** [comment]
@paglias could you check this one as well, please? :)

**Comment by paglias** [comment]
thanks @Xaz16 ! Working very well and the code is clean and well organize ! Notated towards your next tier

**Comment by Xaz16** [comment]
@paglias thank you for review :) 
Doing my best

**Comment by SabreCat** [comment]
FYI we had to revert this on production as it was making Challenge tasks completely uneditable from users' main task lists, which isn't correct--there are fields, such as the Notes, that users should be able to edit in their own copies of Challenge tasks.

**Comment by Xaz16** [comment]
> FYI we had to revert this on production as it was making Challenge tasks completely uneditable from users' main task lists, which isn't correct--there are fields, such as the Notes, that users should be able to edit in their own copies of Challenge tasks.

@SabreCat 
Sorry for that... as I understand notes it is part of edit modal and when I checked it, it is really strange when you trying to save task and you receive "you can't edit this task" message... So should I fix it in such way?

**Comment by Alys** [comment]
@Xaz16 In case it helps, the wiki's [Challenges](https://habitica.fandom.com/wiki/Challenges) page describes what elements of a challenge task can be edited by a participant - see the "Challenge Participant's Permissions" section. It also links to a similar section describing the permissions of challenge owners.

Ask here if you have questions about that.

**Comment by Xaz16** [comment]
@Alys the main question still is: " when you trying to save task and you receive "you can't edit this task" message is it correct behavior?" Even for notes, which you can edit

**Comment by Alys** [comment]
Not correct on the website. The website would prevent you changing any of those elements that you aren't allowed to edit - you shouldn't be able to even use the form fields for those elements. When you change any fields you are allowed to edit, the task should save as normal with no error message.

For editing the task through the API:
If you edit only elements that you're allowed to edit, the edits should save with no error.
If you edit any elements that you don't have permission to change, then your API request should return an error message.

Let me know if that's not clear!

**Comment by Xaz16** [comment]
@Alys yes, it is clear. I will modify this functionality to show for user and create another pull request

**Pull request merged**
