### PR TITLE
Fix a grammatical error in donateText3

### PR DESCRIPTION
**Pull request by ghost**
Previously was mixing 'it' and 'we' when referring to HabitRPG. Switch to using 'it' in both cases since HabitRPG is not talking in the first person.

### CODE REVIEW

**Comment by crookedneighbor** [comment]
Only the files in `/common/locale/en/` should be changed. Everything else [is managed by Transifex](https://github.com/HabitRPG/habitrpg/pull/4733).

Please revert the changes made to the other files.

**Comment by ghost** [comment]
Oops, fixed.

**Comment by crookedneighbor** [comment]
@lemoness What do you think about this change?

**Comment by Alys** [comment]
"it can use all the help it can get" sounds kind of desperate to me. I am guessing that it was added ages ago before the website was as mature as it is now, and it's probably time that we updated it.

The image below shows where the message appears. It might be more appropriate to describe how the money supports the site. For example, something vaguely like this maybe:

"HabitRPG is an open source project and thrives from the support of its players. The money you spend on gems goes towards keeping the site running, paying the wages of the staff, and providing incentives to our volunteer programmers. Thank you for your generousity!"

@lemoness What do you think? That's just a rough example of the sort of thing I had in mind and I won't be at all offended if you shred and burn it. :)

screen shot 2015-03-14 at 11 53 43 pm

**Comment by lemoness** [comment]
Haha, I didn't realize that was on the donation page ;p I definitely prefer
your new version! Slightly tweaked:

"HabitRPG is an open source project that depends on our users for support.
The money you spend on gems helps us keep the servers running, maintain a
small staff, develop new features, and provide incentives for our volunteer
programmers. Thank you for your generosity!"

(I was sad to get rid of that extra U, but we tend to use US spellings, so
I figured I would keep it consistent. Our UK translators can switch it
back!)

**Comment by lemoness** [comment]
Totally unrelated: does the UK version of the site automatically apply for
people in NZ and Australia?

**Comment by deilann** [comment]
Only if they use UK English as their default computer setting. That's how
all the translations work.

**Comment by Alys** [comment]
@lemoness I should give you my keyboard that deletes ALL THE U's! :)

@ghswa Would you like to change the text string again to use Lemoness's text?

**Comment by ghost** [comment]
I noticed last night that some of the other text on the donation page could do with being updated, especially the mouseover for "supports the developers" which is almost identical to the current donateText3.

Benefits

I hadn't previously suggested changing the text as I'm new round here and didn't want to tread on anybody's toes. I'll update donateText3 to @lemoness's version this evening and make some suggestions for the other text too. Right now it's time for lunch for Mother's Day.

**Comment by ghost** [comment]
FWIW, I'm wearing my hat of +5 picky and I've hard-coded a few numbers as I'm not aware of the correct variables, if any.

It might be nice to add a little flavour to these mouseovers. I've had a quick go with the "Buy Gems for Gold" text.

### Disable ads

I'd remove the mention of original users being grandfathered. Personally it raised questions rather than encouraging me to subscribe, I'm sure others have felt the same way. I've changed "will stay" as it sounds a little like a threat to turn them back on if one stops subscribing! It'd be nice to add a little flavour to this, perhaps something about repairing the rifts in the fabric of space that allow advertisements to sneak through?

~~_Ads will stay disabled while you have an active subscription (original users with disabled ads are grandfathered)._~~

Ads are disabled while you have an active subscription.

### Buy Gems with Gold

I think it'd be good to get rid of the parentheses and I'm not sure it's worth talking about farming. Perhaps instead mention that the cap increases over time and link to the [wiki page](http://habitrpg.wikia.com/wiki/Gems#Subscribing).

~~_(1 Gem costs <%= gemCost %> Gold) Addresses the \"pay to win\" concern, as everything is now achievable through hard work. There's a <%= gemLimit %> Gem monthly conversion cap to prevent farming._~~

Alexander the Merchant will sell you gems at a cost of <%= gemCost %> gold per gem. His monthly shipments start at <%= gemLimit %> gems per month and increase in size every three months up to a maximum of 50 gems per month. This addresses the \"pay to win\" concern by making everything achievable through hard work.

### Retain full history entries

It may be worth clarifying this one but I'm not the one to do it. Having recently started subscribing I'm not entirely sure what this benefit is. My habits are still binned into days which is something I'd expected to change. Does this just mean that my history won't start getting merged into larger bins after X months?

_Makes your full history available in graphs and export. Non-subscriber histories get consolidated for database optimization._

### Daily drop-caps doubled

I don't see anything wrong with this but it could probably be sold a little better.

~~_Complete your stable faster!_~~

Both your base drop-cap and contribution from perception are doubled. Complete your stable faster!

### Unique Monthly Subscription Items

Perhaps change main text to "Unique monthly gifts". There isn't any mention of the hourglasses. Being able to get items you've missed out on is quite a big deal and could be pointed out here.

~~_Each month, all subscribers will get a totally unique cosmetic item for their avatars!_~~

Each month you will receive a unique cosmetic item for your avatar! Every three months the Mysterious Time Travelers will grant you access to historic (and futuristic!) cosmetic items.

### Supports the developers

This has basically the same text as donateText3.

~~_This open source project can use all the help it can get. Help us keep Habit alive!_~~

Your subscription helps keep Habitica thriving and helps fund the development of new features. Thank you for your generosity!

**Comment by deilann** [comment]
wrt: Both your base drop-cap and contribution from perception are doubled.
Complete your stable faster!

I'd just say that your drop cap is doubled. You've left out another source
of drop cap, which is contribution tiers, so it sounds like that isn't
doubled because of the specificity, which it is.

The thing about the original donors and ads... it was a common question if
original donors who donated to get rid of ads would get ads back if they
subscribed and then unsubscribed. What kind of questions did it raise for
you?

**Comment by ghost** [comment]
I agree @deilann. I'd overlooked that and the text would get far too convoluted if everything is mentioned.

The ads text got me wondering about whether there were other things I'd missed out on simply because I'd started playing Habit more recently than others. It has me thinking that there might be other instances of grandfathering, other than Kickstarter rewards and seasonal events, that affected gameplay in some way.

My interpretation of the current text was that people who were playing Habit before ads were introduced will never see ads regardless of whether they've ever subscribed. From your comment I get the impression that it's actually Kickstarter donors that have been grandfathered, rather than all early adopters. If that's correct, maybe "original users" could be changed to "Kickstarter donors" to remove any element of doubt.

**Comment by deilann** [comment]
Originally, you could purchase gems once, and ads would be hidden forever.
When subscriptions were introduced, they became the way to hide ads, and a
single gem purchase no longer hid ads.

Perhaps "original donors"?

**Comment by ghost** [comment]
Sounds good to me.

**Comment by crookedneighbor** [comment]
Where are we at with this? @lemoness care to weigh in on the text that should be changed?

**Comment by lemoness** [comment]
This would be my preference (slight tweaks to proposed text above):Disable
ads

Ads are disabled while you have an active subscription (original donors are
grandfathered).
Buy Gems with Gold

Alexander the Merchant will sell you gems at a cost of 20 gold per gem. His
monthly shipments are initially capped at 25 gems per month, but this cap
increases by 5 gems for every three months of consecutive subscription, up
to a maximum of 50 gems per month!
Retain full history entries

Makes your full history available in graphs and export. Non-subscriber
histories get consolidated for database optimization.
Daily drop-caps doubled

Complete your stable faster!
Unique Monthly Subscription Items

Each month you will receive a unique cosmetic item for your avatar! Plus,
for every three months of consecutive subscription, the Mysterious Time
Travelers will grant you access to historic (and futuristic!) cosmetic
items.
Supports the developers

Your subscription helps keep Habitica thriving and helps fund the
development of new features. Thank you for your generosity!

**Comment by ghost** [comment]
So, I've gotten my act together and updated this PR, however, it's damn ugly thanks to my original error of altering the Transifex generated files and now missing a comma.

If you're happy with the result I'll cook up a clean PR.

**Comment by crookedneighbor** [comment]
@lemoness Would you review the string updates in this PR and confirm if I should merge it in?

**Comment by crookedneighbor** [comment]
This will count towards a contributor tier! What's your User ID? You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api). Be sure to only copy the User ID and _not_ your API Token.

**Comment by ghost** [comment]
Here you go: 40891154-6548-4dc0-a752-adc284396af0.

**Comment by crookedneighbor** [comment]
I've awarded you your first contributor tier! If interested, you [can read more about the contributor system here](http://habitrpg.wikia.com/wiki/Contributor_Rewards).Thanks for helping to make Habitica awesome!

**Comment by ghost** [comment]
Cheers!

**Pull request merged**
