### PR TITLE
Add game options

### PR DESCRIPTION
**Pull request by tmas**
Added game options tab under the settings modal, moved the reset button to the new tab, and removed the settings header to match the character customization modal.

### CODE REVIEW

**Comment by tmas** [comment]
Merging this in doesn't make sense at the moment because it would mess up the restore button. I'll move that into game options when I get the chance, which will probably be the middle of next week.

**Comment by lefnire** [comment]
Ok. Sorry I didn't merge this earlier, let's actually have a conversation about this soon (IRC? G+?) - @horusofoz has some Avatar screen mockups that might be of interest for a combined-effort approach between this and his

**Comment by tmas** [comment]
@lefnire I can do whatever. Let me know when you want to do it. I'm generally available in the 3:30-5:30 and 7:00-8:00 (EST) time slot or pretty much any time on weekends.

**Comment by Pandoro** [comment]
Di-Di-Ding, personal call for Mr @lefnire  and Mr @tmas, I repeat a personal call for Mr @lefnire  and Mr @tmas Have you come around to discussing this?

(Wow, I always wanted to play a personal reminder for people, while acting as if I am the nice lady calling out for late passengers on an airport.)

**Comment by lefnire** [comment]
@ruddfawcett let's hold off on the night theme

@tmas hit me up with an updated pull request if you get the chance (merge conflicts right now). I realize the changes @horusofoz are going to be to the avatar dialogs, and won't effect these changes.

**Comment by wildcate** [comment]
Will the game settings/options include the possibility to toggle things like the priority multiplier? And maybe an option to have the new tasks added to the bottom of the to-do list?

**Comment by Pandoro** [comment]
@wildcate, a little of topic, but do you really thiink the priority
multipliers need toggling? They default to 1, so you will not notice the
effect if you ignore them. I'm just curios to hear why you would really
want to toggle them.

**Comment by wildcate** [comment]
@Pandoro I explained under [580](https://github.com/lefnire/habitrpg/issues/580) - basically it makes me feel as if I should think about assigning priority to my tasks, and that is something that just does not work for me. 
Yes, I can ignore it, but it sort of itches.

**Comment by Pandoro** [comment]
@wildcate, Yes I saw, thank you for explaining. I can understand and I
think it fits in perfectly with the other stuff asked in that thread. If we
make options, then we can also hid stuff completely.

Do you never get the feeling that it is more critical to perform a certain
task though ^^?

**Comment by wildcate** [comment]
@Pandoro Yes, I have tasks that I see as more and less critical. It is, however, a very fluid system that exists more or less subconsciously in the back of my mind and that is re-shuffling priorities depending on current mood, time they are already on my mental list, and due dates. I often swap between tasks or re-schedule because I get good progress on one item and don't want to stop there, or I need a break from task A and do something else for a while, or I get distracted by task C because someone phoned me and I had to open that file, and so on. And then there are days where I know I should work on item X but just don't get into it, so I skip that for the day. Which means that it creeps back to higher priority for every day that I do not work on it... I hope you get my drift.

Having to assign an additional, fixed priority feels like it's breaking my internal system. Plus, when I add something to the list and I get reminded that it might be a different priority than the normal priority, I start questioning my subconscious which has assigned something like a "priority slot" already. And questioning one's own subconscious system of prioritising... often not a good idea. So just seeing the possibility to change overt priority already irks me, because it makes me consider whether I should install priority settings or not. The slowly-getting-redder of tasks, on the other hand, fits perfectly for me. It makes sure I can note all the small tasks as well, to make sure I do not forget them, and the reddening ensures they do not stay on the list forever.

I realise that this might just be me who has this system of non-prioritising consciously, it does sound a little weird explained in writing ; )

**Comment by wc8** [comment]
Is this related to [Gamification Options](https://trello.com/c/EKxy5lYI)?

**Comment by lefnire** [comment]
added the tabs into the new setup

**Pull request closed without merging**
