### PR TITLE
Proper reset autocomplete - allow @mentions dropdown to close itself - Fixes #13254

### LINKED ISSUE #13254: @mentions dropdown should not stay visible after selecting from it
As reported by @citrusella and replicated by me (Ubuntu Firefox):

> a bug [I saw] while adding SabreCat's name to the middle of the post I posted prior to this:
> 
> The newly added/fixed ability (https://github.com/HabitRPG/habitica/pull/13180 by helcostr and benkelaar) to go back into the middle of the text and get an autocomplete if you add a mention there is great!
> But if you hit enter on that mention to select from the dropdown (which properly adds the relevant name and a space), it stays visible until the next time you hit space (or enter, or backspace) *after* that.
> 
> It also becomes uninteract-able by keyboard (i.e. using the arrow keys doesn't select a dropdown option but instead moves you around the text box like it would if you were just typing (and the dropdown follows your cursor around), enter also doesn't select an option but adds a new line like it would if you were typing (and dismisses the dropdown)), and further letter typing doesn't cause the dropdown to autocomplete again or anything. But you can still click names that are visible and they will be added, just without an @ in front, as follows: @citrusella citrusella citrusella citrusella citrusella citrusella  (This text typed *before* the preceding mentions.) Clicking does not cause the dropdown to disappear; all those extra citrusellas are from me clicking the dropdown multiple times. XD
> 
> It also seems to not happen if there's a space at the end of the text in the text box, which I discovered while I was trying to enter examples for reporting. :P

### PR DESCRIPTION
**Pull request by Helcostr**
[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #13254

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
Reset searchResults back to an empty array (utilizing an unused cancel function to reduce reused code).

(My bad lol).

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 10cbe941-0e10-4763-9f4f-7a3ae5bb2198

### CODE REVIEW

**Comment by SabreCat** [comment]
Does what it says on the tin! Thankya!

**Comment by SabreCat** [comment]
I've put a note toward next contributor tier on these, btw!

**Comment by Helcostr** [comment]
> I've put a note toward next contributor tier on these, btw!

Does it count if it's on a mistake I made 🤔

**Comment by SabreCat** [comment]
@Helcostr: Yes, as we appreciate it when people help with fixes regardless of where the issues come from! It might not count for quite as much as a PR on a fresh topic, though. 😸

**Pull request merged**
