### PR TITLE
Remove white backgrounds from mount sprites

### LINKED ISSUE #8215: Some mount image backgrounds are not transparent
General Info
  * UUID: 804ca182-f16c-4ff5-b115-d73cdba94935
  * Browser: Chrome
  * OS: Windows 7

### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)

First off -- this is unlikely to be a priority, since it's noticeable to me because I sometimes use extensions that change pages' backgrounds colors ([Dark Reader](https://chrome.google.com/webstore/detail/dark-reader/eimadpbcbfnmbkopoojfekhnkhdbieeh?hl=en) or Stylish themes), but I wanted to point out that some mount images are not transparent on the Mounts page and instead have white backgrounds. I've discovered that the issue is that these mounts are shown via [this group of sprites](https://github.com/HabitRPG/habitica/tree/develop/website/assets/sprites/spritesmith/stable/mounts/icon), of which about has 10-20% have non-transparent backgrounds (e.g., [this image](https://github.com/HabitRPG/habitica/blob/develop/website/assets/sprites/spritesmith/stable/mounts/icon/Mount_Icon_FlyingPig-Zombie.png).)

If, as it appears to me, solving this issue would only require all affected sprites to have their backgrounds removed and reuploaded, I'd be happy to take care of this.

This shows an example of what the Stable page looks like to me: 
image

This shows which all sprites have white backgrounds currently. ([via](https://habitica.com/spritesmith-main-11-b1637069.png))
image

#### Console Errors
[//]: # (Include any JavaScript console errors here.)
N/A

### PR DESCRIPTION
**Pull request by mchlltt**
Fixes #8215 

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
As described in #8215, I noticed that some mount sprites have white backgrounds instead of being transparent and offered to remove backgrounds from all affected sprites. @Alys requested that I correct only one before posting this PR, so that an Artisan can review before I correct them all. If given the go-ahead, I'll fix them all and update this PR. Thanks!

----
UUID: 804ca182-f16c-4ff5-b115-d73cdba94935

### CODE REVIEW

**Comment by Alys** [comment]
@lemoness Is this okay with you?

**Comment by lemoness** [comment]
Yes, this looks good!

**Comment by Alys** [comment]
@mchlltt Please go ahead with the others. Thank you!

**Comment by mchlltt** [comment]
Hi all! I modified a total of 40 sprites, which is what appears to have been called for given the look of this screenshot that I included in the issue post (https://cloud.githubusercontent.com/assets/15218445/20277395/f96e8b82-aa65-11e6-961e-c150223f0cf1.png). If anyone has any feedback or requests, I'd be happy to amend what I've done, but I believe that it is set. Thanks!

**Comment by crookedneighbor** [comment]
:+1:

**Comment by Alys** [comment]
I've uploaded this change to a test website: http://192.241.249.166:3000/

Log in with the username test1 and the password test or create a new account if desired. It's a test-only database so there's no real user information in there.

If there's no complaints in a couple of days, I'll merge this. It looks okay to me, but I'm not a graphics person.

@lemoness You might want to review this.

**Comment by khipkin** [comment]
I'm not too great at CSS, but I made the body's background-color "red" and now it looks like this:

image

**Comment by Alys** [comment]
@khipkin There's probably some other CSS that does backgrounds on specific parts of the page.

My main concern in testing this was that it looks normal when no styles changes are applied by the user, and it does to my eye. I'm not too concerned about display problems when the user uses themes or custom styles, although I definitely think it's a good thing that the image backgrounds have been made consistently transparent.

**Comment by Alys** [comment]
@lemoness has approved this so I've merged it and awarded a tier. @mchlltt Thank you for noticing and fixing this!

**Pull request merged**
