### PR TITLE
Add Task Delete to API

### PR DESCRIPTION
**Pull request by arscan**
This is the first time I've done anything with Derby/Racer, so I'm not 100% sure this is the correct way of interacting with the model.  But its based on what I found in other parts of the app, so I'm pretty sure its ok (at least for now)

### CODE REVIEW

**Comment by switz** [comment]
This is nice. Thanks for including specs!

Before we let people start DELETE-ing things I want to make sure it's rock solid. I'll give it a closer look later today.

**Comment by switz** [comment]
I updated the code slightly. I'm a bit worrisome of taking the entire `typeIds` array and rewriting it. I'd rather just remove a single id using Derby's built in `remove` function.

Just run `git pull git@github.com:switz/habitrpg.git api-delete-arscan` in your `develop` branch. Push it back up and we'll be ready to merge. Thanks!

Check here for the diff: https://github.com/switz/habitrpg/compare/arscan:develop...switz:api-delete-arscan

**Comment by arscan** [comment]
Regarding the rewriting of the whole list -- yeah, I agree.  I think I was having trouble with the remove function for some reason (as I said, new to racer), and got the idea from here:

https://github.com/lefnire/habitrpg/blob/master/src/app/tasks.coffee#L108

Thanks a ton for cleaning that up for me!

**Comment by switz** [comment]
I was also having issues with the `remove` function. Once I moved the `del` call above `remove` it worked fine. No idea why it doesn't work the other way around, but I assume it's something in racer. Maybe Tyler can weigh in.

**Pull request merged**
