### PR TITLE
Replace golden rock mount body sprite

### LINKED ISSUE #8647: Golden Rock Mount Sprite Fix
The body sprite for the Golden Rock Mount currently has a stray pixel some distance from the rest of the body. The image attached to the Trello card linked below has been corrected to remove the stray pixel and has the correct filename.

https://trello.com/c/lduSl5jU/17-corrected-golden-rock-mount-body-sprite

### PR DESCRIPTION
**Pull request by CooperFLe**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes https://github.com/HabitRPG/habitica/issues/8647

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
Update golden rock mount body sprite to remove stray pixel
floating_pixel
fixed_mount

----
UUID: 9a4525a5-fc2b-4e0e-b687-140d8ae6b3bd

### CODE REVIEW

**Comment by paglias** [comment]
@SabreCat do we want spritesheets to be recompiled in PRs or we do it when we release a new version?

**Comment by SabreCat** [comment]
@paglias It's kinda inconsequential, especially when there are only a couple of files changed as here. In general I would say no, don't recompile spritesheets in PRs.

**Review by SabreCat — APPROVED** [review]
In future, no need to commit compiled spritesheets. This will be OK as is, though!

**Comment by SabreCat** [comment]
@CooperFLe I'm merging this with today's content deploy (branch https://github.com/HabitRPG/habitica/tree/sabrecat/bgs-armoire-1704). Welcome to contributor tier 1! Note that subsequent tiers require increasing amounts of effort from one to the next, so tier 2 will require multiple PRs or a more substantial PR to attain. But keep helping out and we will express our gratitude accordingly!

**Comment by CooperFLe** [comment]
Thank you for that! I had to recompile the spritesheet to make sure that the issue was resolved, was not aware that it was recompiling it was preferred, I am sorry for that.

I definitely will continue contributing! I want to contribute actual code to the project instead of just updating images soon!

**Comment by SabreCat** [comment]
@CooperFLe Yeah, no problem! You absolutely need to recompile the sheets for local testing, but it's not necessary to commit them to the PR. (Such changes will get overwritten the next time we add content anyway.)

**Pull request closed without merging**
