### PR TITLE
Made uuid in hall of heroes populate the input box

### PR DESCRIPTION
**Pull request by crookedneighbor**
Click on a uuid in hall of heroes and the input will automatically be filled in.

screen shot 2015-04-09 at 9 57 29 pm

### CODE REVIEW

**Comment by crookedneighbor** [comment]
Will merge in tomorrow night if I don't hear anything otherwise.

**Comment by Alys** [comment]
Ooooo... I was thinking just yesterday that I wanted this. So nice! 

I refuse to award any more tiers until this is merged! :)

**Comment by lemoness** [comment]
I had no idea how much I wanted this until I saw it. `paws hopefully at
Merge`

**Comment by crookedneighbor** [comment]
Added behavior so that it'll scroll to the top to the start of the form and auto load the hero and added tests to make sure those functions get called when calling this function. Will merge when the build is done.

**Pull request merged**
