### PR TITLE
Added catch for cron error

### PR DESCRIPTION
**Pull request by TheHollidayInn**

### CODE REVIEW

**Review by paglias — COMMENTED** [review]
I'm not entirely sure if this is needed. All the code is wrapped in a try/catch so any await that throws is already logged

**Comment by paglias** [comment]
this is the global error handler https://github.com/HabitRPG/habitica/blob/develop/website/server/middlewares/errorHandler.js

**Comment by TheHollidayInn** [comment]
This will prevent the 500 error if there is a version error. And will log the previous error better.

**Comment by TheHollidayInn** [comment]
The issue is we never see the error on line 117 because the update is throwing the error.

**Review by SabreCat — APPROVED** [review]

**Pull request merged**
