### PR TITLE
7039: Update South Pole background

### LINKED ISSUE #7039: Minor Change to Background
The North Pole background had some artifacts, so here is a slightly adjusted version to replace the version that is in-game.
ygfoyll

### PR DESCRIPTION
**Pull request by keysmashes**
Fixes #7039
### Changes

The previous background had some artifacts.

I can provide pictures if I need to, but spinning up the whole development server for one image seems overkill. GitHub's image diff tools are better than a screenshot in this case, IMO.

---

UUID: 0e1d15f7-f36b-4f15-a9e1-0c31b732dac9

### CODE REVIEW

**Comment by SabreCat** [comment]
Shouldn't the striped pole still be red and white, rather than white/red/black?

**Comment by crookedneighbor** [comment]
Looks like it was made transparent. That's the penguin poking through. @lemoness

**Comment by lemoness** [comment]
Hm, okay -- will need to fix that before this can proceed, then.

**Comment by crookedneighbor** [comment]
I corrected the image myself and compiled the sprites. I've notated this towards partial credit to tier 3 for getting this started @anowlcalledjosh

**Pull request closed without merging**
