### PR TITLE
Replace hard-coded strings with env.t on views/static folder and en/app.json

### PR DESCRIPTION
**Pull request by marcelosizer**
Replace hard-coded strings with env.t on views/static folder and en/app.json

### CODE REVIEW

**Comment by lefnire** [comment]
This is a very important PR. I'm gonna try to make sure I don't get too out of step with it while working on other things in the mean time. One quick question: all strings in the HTML files are the _canonical_ versions, since the translation files are outdated. In this PR, did you favor the HTML strings over the app.json strings? (eg, replacing the old app.json strings with the new app.json strings)?

**Comment by lefnire** [comment]
Also queuing @paglias in on this, as he was looking into finishing some translations stuff.

**Comment by marcelosizer** [comment]
Front, layout and index.jade had very few text and privacy and terms.jade had nothing on the app.json files. Also, with the exception of privacy and terms everytime I added a sentence to the en/app.json file I also added to pt/app.json file and checked on the local website to see if it was working and I don't believe there were strings that needed to be replaced. The strings that appeared on both were probably the likes of "login" and "login / register". If you have files that want to see edited first just point me at them and I'll start right away.

And if you have some time I would appreciate some feedback to know if I'm on the right direction or not.

**Comment by paglias** [comment]
Awesome @Sinza- !

Really great work, I think that now translation files are quite outdated and probably miss a lot of strings for new features.

The best way to go probably is to start using translation files for everything and add new strings directly there and not in jade files.

The important is english so that we have all the strings using variables and we can safely update all the other languages.

**Comment by marcelosizer** [comment]
Thanks @paglias ! Yes, new feature strings are not available yet. Not only translations but en/app.json is pretty outdated.

Ah, can I move the existing strings around in app.json? For instance, creating a "_commentgeneral" for strings like "login" that are everywhere, since now they are located under HEADER and are used on other pages like FRONT.

**Comment by paglias** [comment]
Yes yes you can reuse a string everywhere you want. It would be useful to split app.json in multiple files (it's becoming to big...) or it's usable?

**Comment by marcelosizer** [comment]
No no =p what I meant was to change the order of the json.app file, like taking a string that is under "_commentheader" and put it under "commentfooter".

It's becoming too big, at least separate files for privacy.jade and terms.jade would be good since they have lots of text and together take 140 lines (some of them really long). It would be easier to translate them that way.

**Comment by paglias** [comment]
ok, I didn't understood :) Yes, the order is only for organizative purpose, you can move strings everywhere you want, only the name matters.

Separate files: I'll post here as soon as I set up multiple files working. I'm going to keep it simple, referencing a string will be like before so it may be a good idea to keep a naming convention for strings in separate files (ie strings under privacy.json may be prefixed by `privacy`).

**Comment by marcelosizer** [comment]
I'm already using that kind of naming convention. Privacy are `priv` and Terms are `terms`.

**Comment by paglias** [comment]
@lefnire @Sinza- 

With https://github.com/HabitRPG/habitrpg/commit/cb07bc9229f48810b5fd30ccca2d9f5526be3146 and https://github.com/HabitRPG/habitrpg/commit/34319bdcd3c138c34b10f60a9e916dd679c56264 I've added support for multiple translations files:
1. Old translations have been moved to `locales-old`
2. The entry point is now `locales/lang/app.json` where you define the list of files that you want to be loaded.
3. Everything else is as before

I've added an example `secondary.json` file for english, feel free to remove it.

This pull request will have to be updated to support the changes.

**Comment by marcelosizer** [comment]
@paglias I believe it's done.

**Comment by paglias** [comment]
Great, I think we can merge this and if someone wants to separate files/translate other strings, go ahead

**Comment by marcelosizer** [comment]
@paglias hey, this is my first time using git/github and the contributing guidelines weren't clear if I should commit every small change to the same pull request or if I should commit each change on a separate pull request or if I should wait until everything is done before commiting. Right now I'm commiting every time a folder is done and to the same pull request, is it ok? Thanks.

**Comment by paglias** [comment]
Wow! You're doing an awesome job!

Usually a pull request contains commit about a single feature/bug/whatever so it's ok to keep everything into this single one.

About the commit frequency it's a personal choice, if you prefer doing more small commits then it's probably better instead of one big commits with all the changes. In this case I think one commit for every jade file translated is ok. But whatever you feel better.

Thanks again! 

When you think you're done, have question or anything just comment here

**Comment by marcelosizer** [comment]
@paglias got a question =p

I'm doing the lists.jade file and it has a section under //Winter event that uses strings from the content.coffee file so I wanted to know how will content.coffee be translated?

**Comment by lefnire** [comment]
Cool, I'm gonna merge this to get the ball rolling & make sure we don't get too far out-of-sync. Keeping having your convo, you two.

**Comment by lefnire** [comment]
@Sinza- uuid?

**Comment by marcelosizer** [comment]
\o/
@lefnire b4597033-349c-4282-8aa3-1fa56047cf7f 

@paglias Just repeating the question so that it doesn't get lost: "I'm doing the lists.jade file and it has a section under //Winter event that uses strings from the content.coffee file so I wanted to know how will content.coffee be translated?"

**Comment by paglias** [comment]
@Sinza- ok:

`content.coffee` comes from [habitrpg-shared](https://github.com/HabitRPG/habitrpg-shared) which contains all the algorithms, items shared between all the HabitRPG repos (server, client, mobile)...

In the case of [lists.jade](https://github.com/HabitRPG/habitrpg/blob/develop/views/shared/tasks/lists.jade), there's some content from `content.coffee` as you said but it's not put there from the server like the other strings you translated but directly on the browser.

Translated strings are also avalaible in the browser using `window.env.t(stringName)` but things from habitrpg-shared are not ready to be translated so if you could skip them for now.

If you don't understand something of what I said here above just tell me, anyway for now skip those strings.

@lefnire I forgot about that... I would move the translations to `habitrpg-shared` but keep them outside the compiled version so we don't have all the languages in a single which would make the file really heavy.

The logic for loading translations would be kept in this repository for server & client and in habitrpg-mobile for mobile strings when we'll translate the mobile app.

Let me know if it's ok for you and I'll go ahead

**Comment by lefnire** [comment]
@paglias sounds good to me!

**Comment by paglias** [comment]
ok then @Sinza- hold on until I make the switch to habitrpg-shared, I'll post here when it's done

**Comment by marcelosizer** [comment]
@paglias okay! I made another pull request earlier today do you want me to close it?

**Comment by paglias** [comment]
@Sinza- yes

@lefnire we might have a problem, when using translated strings for items in content.coffee they must be avalaible when habitrpg-shared is run, we can't setup them later.

We might add a setup function for the whole habitrpg-shared which loads translations and then `content.coffee`, to be called when we start the server/browser page before anything from habitrpg-shared is used but we should discuss about that before continuing

**Comment by lefnire** [comment]
Went a bit over my head. So we need content.coffee strings available, and
then we need translations, and then we need to load content.coffee again?

**Comment by paglias** [comment]
It's like this, when habitrpg-shared code is run (required in node or loaded in the browser) the code inside `content.coffee` is executed. 

Let's say we re-write [this line](https://github.com/HabitRPG/habitrpg-shared/blob/develop/script/content.coffee#L18):

``` coffee
0: text: "Training Sword", notes:'Practice weapon. Confers no benefit.', value:0
```

this way:

``` coffee
0: text: translations.translate('trainingSword'), notes:'Practice weapon. Confers no benefit.', value:0
```

And that `translations.translate('stringName')` returns a string from a `translatedStrings` objected:

``` coffee
translate = -> (stringName)
    translatedStrings[stringName] or translatedStrings.notFound
```

Then `translatedStrings[stringName]` must be avalaible at compilation time otherwise an error will throw about trying to access property `stringName` of and undefined `translatedStrings` object.

---

We have three possible solutions for this:
1. Loads translations immediately from `locales` into habitrpg-shared. We can't do this unless we do want to bundle `habitrpg-shared.js` with all the avalaible languages.
2. Create a specific version of `habitrpg-shared.js` for every avalaible language, or a separate files for every language containing only translations to be loaded before `habitrpg-shared.js` in the browser. But we can't do so, too, because in node we don't have global variables so there isn't a way to tell the habitrpg-module to use translations we loaded before from the server or to create node specific code that won't be bundled by browserify.
3. Defer the execution of habitrpg-shared code after translations have been loaded.

We wrap the `api` object used as `module.exports`  in a function. Then we define a function called `setup` or whatever that takes a language code and load the necessary files, execute the wrapped `api` object and substitute it to the existing `module.exports` that contained only the `setup` function.

1, 2 seems impracticable to me so I would go with 3 but would like to hear what do you think and possibly some better solution.

---

Sorry for the previous bad explanation, I have some serious problem expressing in english :)

**Comment by paglias** [comment]
@lefnire just pinging on my last comment

**Pull request merged**
