### PR TITLE
Angularjs rewrite

### PR DESCRIPTION
**Pull request by yangit**

### CODE REVIEW

**Comment by litenull** [comment]
Erm, coffeescript ?

**Comment by yangit** [comment]
Yes. Anything wrong with it?

**Comment by litenull** [comment]
Dont you think the angularjs rewrite could attract more developers with Javascript ?

**Comment by ghost** [comment]
@litenull All depends on preference, I prefer coffeescript so

**Comment by litenull** [comment]
ok, nice work anyways.

**Comment by yangit** [comment]
Well, I never tried coffee until @lefnire asked me to join habitrpg.
It turned out to be a very quick and painless transition.

**Comment by ghost** [comment]
Yep, if you ask me it's fairly easy to get into.

**Comment by switz** [comment]
+1 for coffee - don't think I'll ever go back to writing plain javascript.

**Comment by yangit** [comment]
Since you are here.
Anyone can chat with me about scoring system?
Especially in angular?
yan@yan.my in g+.

**Comment by ghost** [comment]
@yangit I invited you via GTalk was that the intention or?

**Comment by yangit** [comment]
@litenull I need to coordinate with you on shared scoring system in https://github.com/HabitRPG/habitrpg-shared repo. Otherwise we will end up with 3 different places to update scoring function.
Let's hangout?

**Comment by lefnire** [comment]
Also @thedecimal (who's doing mobile-to-api syncing) would be a very useful
person to coordinate with. And @switz is in charge of API proper, but I
think @thedecimal & @litenull will be your guys

**Comment by litenull** [comment]
Hey, Yan. Yes, but im pretty busy lately. Need to sync our new team member
- going out of country from thursday - sunday. We can do next monday, or in
  the weekend. I have plenty of time. is it OK for ya ? If not, ping
  thedecimal. He's the sync person.

On Tue, May 7, 2013 at 11:03 AM, Tyler Renelle notifications@github.comwrote:

> Also @thedecimal (who's doing mobile-to-api syncing) would be a very
> useful
> person to coordinate with. And @switz is in charge of API proper, but I
> think @thedecimal & @litenull will be your guys
> 
> On Tuesday, May 7, 2013, Yan wrote:
> 
> > @litenull https://github.com/litenull I need to coordinate with you
> > on
> > shared scoring system in https://github.com/HabitRPG/habitrpg-sharedrepo.
> > Otherwise we will end up with 3 different places to update scoring
> > function.
> > Let's hangout?
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/lefnire/habitrpg/pull/904#issuecomment-17530730>
> > .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/lefnire/habitrpg/pull/904#issuecomment-17531180
> .

## 

LP, Tomaž :)

**Comment by yangit** [comment]
@thedecimal @litenull @switz
Guys, please drop me a line at yan@yan.my
I need to get in touch with you and have no idea how to do it via github.

**Pull request merged**
