### PR TITLE
Added link to challenge creator on challenges.

### PR DESCRIPTION
**Pull request by TheHollidayInn**
In case we go with a link to the challenge creator profile, here is a possible solution to: https://github.com/HabitRPG/habitrpg/issues/4687 .

If we don't want to use this, that is fine. I am just practicing working tickets.

### CODE REVIEW

**Comment by Alys** [comment]
I'll check this out this weekend. Thank you!

**Comment by Alys** [comment]
Grrr. My local install is refusing to play nicely with the challenges page, even when the codebase is identical to production. I think I need to update some node modules. Unfortunately I have a bunch of other stuff to get done this weekend and I don't want to risk a broken install, so I won't be able to test this until early to mid next week. Not that I imagine it will need much testing, but I like to be safe rather than sorry. :)

**Comment by TheHollidayInn** [comment]
No worries! I am not in any rush. I appreciate you testing it!

**Comment by Alys** [comment]
This is lovely! Thank you. It's been recorded in your profile as partial credit towards your next tier.

**Comment by Alys** [comment]
@lemoness FYI when this goes live (in a day or two most likely), then on the Challenges page, you'll be able to click on the challenge creator's name to view their profile (and therefore to message them, or to see how long ago they last logged in if you are curious about whether the challenge might still be active).

**Comment by lemoness** [comment]
FANTASTIC! That definitely goes in a Bailey announcement.

**Comment by lemoness** [comment]
@TheHolidayInn Is this your HabitRPG name, too?

**Comment by TheHollidayInn** [comment]
@lemoness It is :) Except, my name as 2 "l"'s instead of one. I think that is why the link above does not work when you @ mention me.

**Comment by lemoness** [comment]
Noted!

**Pull request merged**
