### PR TITLE
Fixed footer to bottom of page

### LINKED ISSUE #9859: Footer not stay bottom always
### General Info
  * UUID: 2d57fd14-0fd1-4bf5-abe9-d65bb42fbc6f
  * Browser: Google Chrome 63.0.3239.132 / Safari 11.0
  * OS: Ubuntu 17.04 / macOS High Sierra 10.13

### Description

It floats half way down up the page on pages with less content (for example https://habitica.com/user/settings/data-export)

image

### PR DESCRIPTION
**Pull request by lex111**
Fixes #9859

image
Page - https://habitica.com/user/settings/data-export

### CODE REVIEW

**Comment by paglias** [comment]
Code looks good but haven't tested locally

**Comment by negue** [comment]
Can't reproduce it on the current website, maybe my Screen Resolution is too low (and then it just works as "expected")

**Comment by lex111** [comment]
@negue try to zoom out, the footer should always be at the bottom.

**Comment by negue** [comment]
Now I can reproduce it haha, thanks!

It works, but the footer gets the `margin-right: -12px` (resulting in a bottom scrollbar, because the content was too long^^), I guess your rule in `.footer-row` got overridden.

But a simple `!important;` helped out and fixed it

**Comment by lex111** [comment]
@negue hmm, but can you give me please a screenshot and the URL on which it happens?

**Comment by negue** [comment]
Everything is good, seems that switching between branches caused the webpack to hickup some styles 😅 .

Restarted webpack now its working fine. 

Sorry for the scare ^^

**Comment by paglias** [comment]
@lex111 can you post your UUID so i can record this in your contribution notes? Thanks!

**Comment by lex111** [comment]
@negue my UUID - 2d57fd14-0fd1-4bf5-abe9-d65bb42fbc6f

**Comment by paglias** [comment]
@lex111  thanks for this! I'm merging the PR and awarding your contributor tier.

Note that further tiers require increasing amounts of work from one to the next, so Tier 2 may require a couple of PRs or a larger PR to attain. But keep helping out and we'll express our gratitude accordingly!

**Comment by lex111** [comment]
@negue yeah, I want to do something more difficult of course, what can you recommend?

**Pull request merged**
