### PR TITLE
Fix homepage text

### PR DESCRIPTION
**Pull request by NathanMaton**
Fix for "A typo in the Habitica's homepage #6443"

### CODE REVIEW

**Comment by NathanMaton** [comment]
Uid: 2ab55d89-a3e5-4565-ba35-b6c9e145a60a

**Comment by crookedneighbor** [comment]
There are merge conflicts in your PR. They must be resolved before we can consider merging this.

Also, it looks like you made more changes than the ones specified in the issue. Can you explain why?

**Comment by NathanMaton** [comment]
Edit: think I've resolved the merge conflicts which were in the habitrpg-shared.css file which I'm not sure how it is getting modified, not happening on my end.

For the question about more changes. What changes do you mean? Reading through the issue I saw this as the core request:
'"Goals" and "Chores" both have tasks that are formatted like Habits, but the text indicates that maybe they're meant to be Dailies. For example, "20 mins of housework" is there as a plus-and-minus Habit, but the minus doesn't make much sense in that context.'

I went ahead and swapped out the habit formatting for daily formatting in those two sections.

**Comment by NathanMaton** [comment]
Develop is the branch I should be pulling in for these changes right?

**Comment by Alys** [comment]
@NathanMaton Can you please include a screenshot that shows the changes on the home page?

Also note that when you edit a comment, we're not notified that it's happened. We are notified when new comments are added. It's safest to always put changes to what you've written previously into a new comment. :)

**Comment by NathanMaton** [comment]
Ok, will just comment in new comments thanks for the FYI. Here are screenshots.
screen shot 2016-01-06 at 3 41 19 pm
screen shot 2016-01-06 at 3 41 11 pm

**Comment by SabreCat** [comment]
`habitrpg-shared.css` is built automatically when the server starts. It doesn't need to be included in pull requests.

**Comment by Alys** [comment]
_removed my stupid comment_ :)

**Comment by Alys** [comment]
It's also in website/views/social/landing-page.jade :

````
      li=env.t('landingCopy3', {userCount:'900,000'})
````

**Comment by Alys** [comment]
For the record, the Discover logo exhibits the same problem that I reported here: https://github.com/HabitRPG/habitrpg/issues/6485
although I expect that's not something that needs to be fixed in this PR since it affects other images as well.

**Comment by NathanMaton** [comment]
@Alys aren't you referring to another bug that Sighne put a PR out for? Not sure your comments match the ui changes I'm making here.

See the PR 6476: https://github.com/HabitRPG/habitrpg/pull/6476

**Comment by Alys** [comment]
Ugh, yes, so sorry, totally the wrong PR.

**Comment by NathanMaton** [comment]
Its ok. Pretty impressive all that you're doing so no worries at all! Have a great day.

**Comment by SabreCat** [comment]
Merged and noted toward your next contributor tier! Thanks @NathanMaton!

Tip for future: the merge conflict was `common/dist/sprites/habitrpg-shared.css`. That file gets updated every time the server runs, and thus doesn't need to be included on commits. Leaving it out makes PRs a little easier to merge!

**Pull request merged**
