### PR TITLE
Fixed small typo in API docs

### PR DESCRIPTION
**Pull request by SunSparc**
Just a single letter typo in the docs. Not a big deal. Just bugged me and decided to change it.

### CODE REVIEW

**Comment by paglias** [comment]
Hi @SunSparc and thanks for the PR! Sorry for the delay, we'll review it this week

**Comment by paglias** [comment]
Good catch @SunSparc ! If you have an Habitica username I'll notate this in your contributions

**Comment by SunSparc** [comment]
@paglias, my Habitica username is the same as my Github username. Cheers!

**Comment by paglias** [comment]
@SunSparc your first contributor tier has been awarded!

Note that further tiers require increasing amounts of work from one to the next, so Tier 2 may require a couple of PRs or a larger PR to attain. But keep helping out and we'll express our gratitude accordingly!

**Pull request merged**
