### PR TITLE
Removed unused I18N strings from the `rebirth.json` files (related to issue #9957) 

### PR DESCRIPTION
**Pull request by RaitheOfDureya**
[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
This PR fixes part of issue #9957

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
I have identified the following unused strings in the `rebirth.json` file. No dynamically-generated strings found.

At the moment I only removed the strings from the `locales/en` folder to make it easier to revert if necessary. Once the strings are reviewed, I can delete them from other languages.

- rebirthBegin
- rebirthStartOver
- rebirthAdvList1
- rebirthAdvList2
- rebirthAdvList3
- rebirthAdvList4
- rebirthInherit
- rebirthInList1
- rebirthInList2
- rebirthInList3
- rebirthInList4
- rebirthEarnAchievement
- beReborn
- reborn
- confirmReborn

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 6544e17f-237b-4915-ae7e-47744c0dc1bd

### CODE REVIEW

**Comment by paglias** [comment]
thanks @RaitheOfDureya , this is looking good, you can remove the strings from the other locales

**Comment by RaitheOfDureya** [comment]
here you go, @paglias

**Comment by paglias** [comment]
Merged with https://github.com/HabitRPG/habitica/commit/13d1f1b48bb1ed8a35e556ed73419d60ddafbd71

**Comment by paglias** [comment]
thanks @RaitheOfDureya ! noted towards your 5th tier

**Pull request closed without merging**
