### PR TITLE
Increase scrollable-message max-height (AKA integrate unspool chat messages extension)

### PR DESCRIPTION
**Pull request by hairlessbear**
I'm a huge fan of the [unspool chat messages extension](http://habitrpg.wikia.com/wiki/Unspool_HabitRPG_Chat_Messages), and can't think of any reason that it shouldn't be the default behavior. This PR integrates the extension; it increases the maximum height of chat messages, making long messages much more readable.

### CODE REVIEW

**Comment by crookedneighbor** [comment]
I'm fine with it. I've always thought the message boxes were two small.

**Comment by deilann** [comment]
This will make it far more difficult to hide messages that might be
triggering or spoilery.

**Comment by Alys** [comment]
That's a good point. At the moment, on the occasions when we need to post something that might be a trigger for people, we can put a trigger warning at the top, then a couple of blank lines, and then the content. Anyone who doesn't want to read it can avoid scrolling down.

Admittedly this doesn't need to happen very often in many guilds, but when it is needed, it's important.

@hairlessbear, I'm sorry, I didn't comment on this when I saw your question in a guild because I didn't have any opinion either way or know if there was a reason why chat had been built like that, but I agree with deilann now that he's mentioned this.

**Comment by hairlessbear** [comment]
@Alys not a problem :) In a way, it's good that you didn't respond, because now we can have this discussion here and not clutter up the guild.

I agree that having a mechanism for managing trigger warnings is essential, but I think small message sizes are a very poor solution. There's a chance that people could accidentally scroll and see the trigger anyway, and if they have the unspool chat messages extension installed, then it won't make a difference.

What do you guys think about implementing some sort of clickable button or text for trigger warnings/spoilers (e.g., the [spoiler template](http://habitrpg.wikia.com/wiki/Template:Spoiler_start) we use on the wiki)? This would allow us to increase the message height size and guarantee that spoilers/triggers would only be seen intentionally.

**Comment by crookedneighbor** [comment]
I'm hesitant to add that kind of complexity to the chat system.

**Comment by hairlessbear** [comment]
@crookedneighbor That makes sense. After thinking about it further, I think there might be a middle ground. Most sites that I've seen with trigger warnings don't actually hide the sensitive content; they use a highly-visible warning, leave some space, then add the content. Something like:

> ## TRIGGER WARNING
> 
> .
> .
> .
> .
> .
> .
> _sensitive content_

I think that's a strong enough visual indication that it would be sufficient to ensure that users don't see content they don't want to, even if it is technically visible on the screen. What do you guys think?

**Comment by crookedneighbor** [comment]
Personally, I think if the chat box height is increased, our community will adapt and create alternate methods, like the one you've proposed.

**Comment by deilann** [comment]
Considering I read the Tavern backwards, no, I don't think that's enough
warning. I'd prefer we had a button to unspool messages. You can or can't
click on it to see the whole thing without scrolling.

**Comment by deilann** [comment]
@crookedneighbor While it's true that I'm sure the communities that need
trigger warnings will adapt and create new methods, it's really, really
uncool to make a sudden change and leave them with no methods, especially
as I'm in a guild where if this change went through, it would just suddenly
show a bunch of triggering content.

**Comment by Alys** [comment]
I agree with deilann, especially with the point about reading from the bottom up, which I would guess most users do. That makes a top-down trigger warning less effective.

The small message size might not have been intended to protect people from triggering content, but it's become used for that in various sensitive guilds. One of HabitRPG's most positive aspects is that we try hard to make it a safe space for everyone, and that includes people who need to be cautious about what they read for their own safety and mental wellbeing. Those people _might_ be in a minority, but their needs are important.

The current situation is a reasonable compromise: those who want expanded messages can use an extension, those who need protection have it by default. Admittedly, not everyone is able to install extensions or use a browser that allows that much customisation, but that's a less damaging disadvantage than making HabitRPG less of a safe space.

An in-built button or other feature instead of the extension would be a good thing. But it needs to be optional.

**Comment by hairlessbear** [comment]
@deilann @Alys What about adding a checkbox to the site settings page? The only potential issue I see with that is that we'd need to figure out a way to ensure that users understand they may see triggers if they enable the option (maybe this could be achieved by improving the popover text). But if we can figure that out, a checkbox setting seems like an effective solution to me.

**Comment by deilann** [comment]
Considering the average message isn't longer than the current size of the box, I think that a button you can press to unspool a specific message will be useful for everyone and give folks who don't want to see triggering content an easy way to read long, non-triggery messages.

**Comment by AnitaYCheng** [comment]
Definitely agree with a "Read more..." button to unspool longer messages. That way people can choose and there's no surprises for anybody. The existing message box is so small, that scrolling within them is an inconvenience, if you even notice that a message is long enough to scroll to begin with.

**Comment by crookedneighbor** [comment]
The bigger question would be how to implement a read more feature. Maybe by detecting the height of the message and if it's larger than a normal message, add a read more link to expand it?

**Comment by deilann** [comment]
That's what I was thinking, but make it a button next to where the +1 and
the trash can are.

**Comment by hairlessbear** [comment]
@deilann Those icons are at the end of a message, so when a message is too large, those icons are hidden until you scroll all the way to the bottom.

selection_002

I think it should be somewhere above the chat text. Maybe the button could be directly to the right of the user name?

**Comment by deilann** [comment]
Oh right, I completely forgot about that.

I wonder if it would be possible to make those buttons float at the lower
right hand regardless of how long the message is.

**Comment by crookedneighbor** [comment]
I'm :+1: on that. 

Personally, I think the whole chat system needs a major UI update :disappointed:

**Comment by AnitaYCheng** [comment]
Could be done if it was absolutely positioned. I'm guessing the user names are, that's why they stick to the top left of the message box regardless of scrolling. A "Read more" button should really be near the area where someone would want to read more, at the bottom of the message.

**Comment by AnitaYCheng** [comment]
@crookedneighbor Hear hear. Sketches here or on Trello?

**Comment by crookedneighbor** [comment]
Here is fine.

**Comment by Alys** [comment]
"I wonder if it would be possible to make those buttons float at the lower right hand regardless of how long the message is." Definitely! Allow flagging without having to see the whole message.

Note that the whole chat system will be replaced at some shadowy future time. I'd suggest not putting too much effort into this one, apart from fixing usability issues (which probably includes message expansion and positioning of those buttons).

**Comment by hairlessbear** [comment]
@Alys I've been discussing adding a live-preview to the chat system with @crookedneighbor [here](https://github.com/HabitRPG/habitrpg/pull/4714#issuecomment-103268669); should I put off working on that until the chat system is replaced?

**Comment by Alys** [comment]
Hmmm. I've just seen your screenshots with preview and formatting help ideas, and I did like them a lot. I think they'd be immediately popular. It's up to you. I'd like to see that done.

I guess I was just trying to say that we might want to not do a weeks-long redesign project.

**Comment by crookedneighbor** [comment]
Going to close this PR. Open a new one when you something worked up for the markdown help.

**Pull request closed without merging**
