### PR TITLE
remove broken website field from profile

### PR DESCRIPTION
**Pull request by AdrienLemaire**
Websites can be added with markdown in the blurb field

Fix for Issue #923

### CODE REVIEW

**Comment by SabreCat** [comment]
Ah, I was about to write up an issue here re the groups. Good to know I should be using markdown instead!

**Comment by lefnire** [comment]
Elegantly done, this is a very strong PR!

**Comment by AdrienLemaire** [comment]
thanks :)

**Comment by paglias** [comment]
A migration should be written for groups too?

**Comment by lefnire** [comment]
yep, sorry there was a followup commit aad8f80. good catch @paglias

**Pull request merged**
