### PR TITLE
New potions

### PR DESCRIPTION
**Pull request by chimericdream**
I like casting spells, but the rate at which MP is recovered seems rather slow to me. I know I could "cheat" and just give myself the MP, but thought this would be a little better.

Imgur

The health potion is unchanged, while the new mana potion is 15MP for 25GP and the elixir is 25MP + 25HP for 125GP. I tried to pick numbers that were high enough to prevent abuse but cheap enough to be affordable.

The icons are just the same as the original health potion after a bit of fiddling around with the hue slider.

### CODE REVIEW

**Comment by Alys** [comment]
in the past, we've avoided having a mana potion because it makes it too easy for Rogues to get infinite mana, since they have skills that give them gold. In addition, in an upcoming change, mana will be easier to get (Dailies and Habits as well as To-Dos). I'm not certain this change is desirable, although it is a requested feature (we generally advise people to make their own mana potion with a custom reward and Fix Character Values).

ping @lemoness

**Comment by chimericdream** [comment]
I can understand the issue with Rogues, but I feel like that hinders other classes. Is there a way to find some middle ground? I'm glad to hear that MP regen will be improved soon, but I don't necessarily think that would be mutually exclusive with this.

As you mentioned, it is already easy to "cheat" by using the Fix Character Values screen, so something like this which gives three classes a nice way to recoup some MP and one class a way to cheat faster has more benefit than it does drawback in my opinion.

One compromise I thought of while writing this (and I'm not sure where I fall on this, but figured I would throw it out there) could be to make the amount MP recovered by the mana potion based on your class or a function of INT. That way, mages would get the most benefit, then healers, rogues, and warriors. That makes sense thematically as well, since "mana" is generally associated more with magic than physical abilities.

**Comment by chimericdream** [comment]
@Alys is there a cap to the amount of GP a Rogue can get from backstab? It looks like the max from pickpocket is 25GP, so they'd have to cast it twice to afford the mana potion (spending 20MP to recover 15MP). If there is a similar cap on backstab, perhaps there is a middle ground we can find where there isn't much point for Rogues to buy the potion, but other classes still benefit. Perhaps making it INT-based as I mentioned in my previous reply would do this.

**Comment by Alys** [comment]
Quick reply because I'm getting ready for work: Skills are being changed - see https://github.com/HabitRPG/habitrpg/issues/3029#issuecomment-68128382 for details. The issue and PR for backstab might contain test data showing limits.

I am interested in your ideas regarding INT.

**Comment by chimericdream** [comment]
I'm not quite sure how the INT-based formula would work, but after reading through all of the comments on #3029 I am more convinced that the skill changes work well with these new potions. The Rogue's ability can't result in enough GP per MP spent to allow them to break even, much less have a net gain.

Based on this, I don't see a problem adding the potions now (as opposed to waiting until after the skill overhaul). People who want to cheat are probably already doing it, so I don't think this will have a significant impact on Rogues' "broken-ness". But for the people who want an in-game way to gain back some of their MP will be satisfied.

It looks like the skill changes are almost complete, so I may have to jump in and look at what's left to see if I can help get it merged faster.

**Comment by chimericdream** [comment]
I should note that I think the new potions would work as-is without having any complicated formulae to determine how much MP the user gets back.

**Comment by Alys** [comment]
The only thing left for the skill changes are for me to merge the code into the new site code (habitrpg-shared went away), then a small change to be finished by deilann which is best done after I've done the merging, and then testing on beta.

**Comment by Alys** [comment]
... and a small change to be finished by deilann which is best done after I've done the merging.

**Comment by chimericdream** [comment]
Ah. There were a few unchecked boxes on the list toward the bottom. Are those features that were determined to not be needed at this point?

**Comment by Alys** [comment]
The unticked Rogue skills uncertain changes? Yes, ignore those.

**Comment by chimericdream** [comment]
Yes. I think the only other unticked item I saw was "Prevent attribute points being gained above level 100". Is that getting pushed back as lower priority?

**Comment by Alys** [comment]
See my comment above about deilann, and see also the comments on the linked issue for that point.

If you did want to work on that project, you could do the merging of code. I had wanted to do it myself but my laptop has been sort-of-broken so I haven't got my local install working properly yet, and I don't know how much longer it will take me to get myself sorted out. No pressure if you don't want to do it. :)  All code in that branch was written before habitrpg-shared was removed, so the code just needs to be inserted into the correct places in the new code-base (while keeping it in a separate branch from develop).

**Comment by chimericdream** [comment]
I'll give it a go. I really want those changes and these. :smile:

Basically all that's left is bringing the commits from `habitrpg-shared/rebalancing-2014-12` into `habitrpg/rebalancing-2014-12`, is that correct?

**Comment by Alys** [comment]
Yes, thank you!

**Comment by Alys** [comment]
after rebasing habitrpg/rebalancing-2014-12 of course :)

**Comment by chimericdream** [comment]
Of course.

**Comment by chimericdream** [comment]
@Alys It looks like the skill stuff is on track to be merged in the near future, so I think I'd like to revisit the discussion about the new potions. I don't think they are more "broken" than anything else under the current system (since people can manually adjust MP already), and I think they fit very well with the updates coming soon to the class skills/spells.

One other side benefit of this PR is that it opens the door for a wider variety of spells. The gear, eggs, scrolls, etc are all whole categories of items in the code, but the current health potion is just a single element. With this PR, we get a little closer to being able to easily add all sorts of potions based on new features (status effects are one thing that come to mind).

**Comment by lemoness** [comment]
I would be amenable to these potions if we can be assured that they won't
be a problem with the new Backstab and Pickpocket modifications.

**Comment by chimericdream** [comment]
@lemoness I will do some math tonight based on the formulas in the updated skills branch and post the results here. My gut tells me that they will fit quite nicely, but I understand wanting to have concrete numbers. :smile:

**Comment by chimericdream** [comment]
I'll also make sure that the pull request has all the latest changes from `develop` merged into it.

**Comment by chimericdream** [comment]
@lemoness @Alys Great news! It looks like both spells cap well under the cost of the mana potion. They are both now using the [diminishing returns](https://github.com/HabitRPG/habitrpg/pull/4812/files#diff-427547b556682eeb851937c56e08d5ddR480) function, and [pickpocket caps at 25GP](https://github.com/HabitRPG/habitrpg/pull/4812/files#diff-427547b556682eeb851937c56e08d5ddR589) while [backstab caps at 18GP](https://github.com/HabitRPG/habitrpg/pull/4812/files#diff-427547b556682eeb851937c56e08d5ddR601). It looks like there's no way for Rogue's to get infinite MP with the potion now.

I have merged the latest changes from `develop` into the branch with the pull request, so it should be good to go!

**Comment by Alys** [comment]
I would like to wait until the new skills are live for a few days before merging this. If there is any feedback in the Tavern about the new skills and related changes (e.g., about whether people have enough / too much mana now) then I want to be sure that their feedback is based solely on the skills-rebalancing changes.

**Comment by chimericdream** [comment]
I can live with that. Is there an estimate when the new skills will be merged in? I remember there was one more task and some final testing, but from what I recall it was pretty close to ready.

Looking forward to both the new skills changes and the new potions shortly thereafter!

**Comment by deilann** [comment]
The final task is the no more attributes after level 100 which I haven't
finished. If you want to do it, rather than waiting for me to be able to,
I'd be not unhappy at all!

**Comment by chimericdream** [comment]
@deilann I should have some time this evening, so I'll see what I can do. Which thread do you want me to reply to if I get it done, and which branch? I'm assuming I can use the `rebalancing-2015-03` branch for the latter. Do you want me to just post here if I am able to get it done?

**Comment by Alys** [comment]
Please post to the issue that was created for that change: https://github.com/HabitRPG/habitrpg/issues/4474

**Comment by chimericdream** [comment]
@Alys Sounds good.

@deilann Do you have some code started that I can look at, or should I just take it and run?

**Comment by deilann** [comment]
I do, but not on this computer, unfortunately.

**Comment by webmuskie** [comment]
I think a more interesting potion would be a shapeshifter's potion. Use it, and you can cast one spell from another class.

**Comment by chimericdream** [comment]
@webmuskie I like that concept. I am actually working on some ideas for a whole new set of mechanics (teaser: potions and status effects). I'll add your suggestion to the list.

**Comment by Alys** [comment]
@webmuskie that's an interesting suggestion, but @chimericdream it would be best if you described your ideas at a very early stage in your process so that you'll know in advance whether your changes will be accepted or not. Please be aware that we might reject some ideas if we feel that they will make the game unbalanced, or too complex for new users, etc.

**Comment by chimericdream** [comment]
@Alys definitely. I am not planning to write any code until posting the ideas here, but a friend and I are working on fleshing out some of the concepts so we can present something a little more well thought out.

**Comment by Alys** [comment]
Waiting for the rebalanced skills to be live for a couple of weeks, then we'll see how we think this PR will go based on the new mana / INT balances.

**Comment by chimericdream** [comment]
Sounds good. From your tone, can I infer that the skills will be going live soon? I'm excited. :grinning:

**Comment by crookedneighbor** [comment]
Skills rebalancing is now live. @Alys @chimericdream ready to continue this conversation?

**Comment by Alys** [comment]
No not, yet. I want to wait at least the two week period that has to elapse before we allow feedback. We can't judge what the current mana balance is like while everything is so new and while users are still experimenting.

**Comment by chimericdream** [comment]
That works for me as well. Besides, I'll need to merge in the latest `develop` branch as well as try to figure out what the heck is going on with my environment so I can actually run the tests.

**Comment by crookedneighbor** [comment]
Update @Alys ?

**Comment by Alys** [comment]
As far as I know, we're still collecting feedback and we haven't analysed it yet.

My personal feeling is that I get too much mana now, and I've seen similar comments from others in the Tavern. Some think that even the skills that we nerfed are too powerful now because you can cast them more often.

I haven't seen any requests for a mana potion for a while, although they never came in very regularly, so that could well be just coincidence.

**Comment by crookedneighbor** [comment]
I have also not felt the need recently for a mana potion recently. If anything, I have too much mp now.

**Comment by chimericdream** [comment]
I've actually run out a couple times, but I have also been far less productive than usual lately. I've been maintaining my habits and (mostly) my dailies, but haven't been ticking off very many to-do items. So I haven't been gaining mana quite as fast as i spend it.

I agree that it seems like much less of an "OMG MUST HAVE TEH THINGZ" issue than before, but I think I could see the argument both for and against the new potions at this point.

**Comment by lemoness** [comment]
I definitely don't think that there is a need for a mana potion now. We've
gotten mostly feedback that people have a ton of mana; as Alys says, we've
gotten some complaints as well.

**Pull request closed without merging**
