### PR TITLE
Revert "Put list back into removeTask fn, update removal logic within ch...

### PR DESCRIPTION
**Pull request by Alys**
Reverts HabitRPG/habitrpg#5000
because of sorting issues for Habits, Dailies, non-dated To-Dos, and maybe Rewards but I didn't test them :)

### CODE REVIEW

**Comment by gisikw** [comment]
If this revert goes up, removing tasks from challenges will be broken, so you'll want to revert #4996 as well.

**Comment by Alys** [comment]
@gisikw Yes. :)

Sorry, I had every intention of explaining this to you properly but you've seen this first. :)  Give me a few minutes.

**Comment by gisikw** [comment]
Can I get a repro steps for the sorting issue? That way I can ensure a revised PR works for that case, and write some tests as well before reintroducing date sorting. Cheers!

**Comment by Alys** [comment]
Yes but later, and in https://github.com/HabitRPG/habitrpg/pull/4996. I have a few things that have to be done first.

**Pull request merged**
