### PR TITLE
Remove Beast Master requirement to unlock Rebirth

### LINKED ISSUE #8593: Orb of Rebirth still visible after rebirth + reload of website
Yesterday when I used the Orb of Rebirth, I noticed it was still visible (and set to cost 6 gems) in the Market - even after reloading the website multiple times.

Just checked again, to be sure - and the Orb is still visible in the Market.

Browser used: Google Chrome (checked using Microsoft Edge as well).
OS: Windows.

### PR DESCRIPTION
**Pull request by Yutsuten**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #8593 

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
Getting the Beat Master achievement won't enable the Orb of Rebirth to be bought in the market anymore.

[//]: # (Put User ID in here - found in Settings -> API)

----
UUID: 203f208a-e0f0-4442-bf16-d4f19e553e8a

### CODE REVIEW

**Comment by TheHollidayInn** [comment]
Can you update the unit test for this, please?

**Comment by Yutsuten** [comment]
In the file ``test/common/fns/updateStats.test.js`` I found the test that checks if rebirth is enabled:

``` JavaScript
it('add user notification when rebirth is enabled', () => {
  user.stats.lvl = 51;
  updateStats(user, { });
  expect(user.addNotification).to.be.calledTwice; // once is for drops enabled
  expect(user.addNotification).to.be.calledWith('REBIRTH_ENABLED');
});
```

But it isn't testing if the rebirth is enabled when the user get the Beat Master achievement. So I think that there is nothing to be changed...

**Comment by TheHollidayInn** [comment]
Ah, sorry. I see you removed the condition. This PR looks good to me then.

**Comment by TheHollidayInn** [comment]
Tested Locally:
 - Set user to have beast master achievement
 - Checked and did not see orb of rebirth

**Comment by paglias** [comment]
Thanks @Yutsuten, notated towards your next tier :)

**Pull request merged**
