### PR TITLE
Merge Rebalancing branch from habitrpg-shared and preserve commit history

### PR DESCRIPTION
**Pull request by crookedneighbor**

### CODE REVIEW

**Comment by crookedneighbor** [comment]
@Alys @chimericdream Want to check my work on this?

**Comment by chimericdream** [comment]
Much quicker than me. At first blush, everything looks good.

**Comment by crookedneighbor** [comment]
@chimericdream If you're interested in how I pulled in the other commits, this is how I did it. (I'm writing this from memory, so forgive me if I miss a crucial step)

Earlier on, when I merged the shared repo into the main repo, I did this:

``` bash
# in habitrpg-shared
mkdir common
git mv all/the/files common
git commit -m "moved files to common"
git remote add main git@github.com:HabitRPG/habitrpg.git
git pull main develop
# sort out new paths and stuff to use common dir
git push main habitrpg-shared-conversion-branch
# Open PR
```

So when merging in the rebalancing branch, all I really had to do was:

``` bash
# in habitrpg-shared
git fetch upstream rebalancing-2014-12
git checkout -b blade-rebalancing upstream/rebalancing-2014-12
git pull main develop
# sort out merge conflicts, just some dist js files that were compiled from coffeescript. IE, just run grunt tasks to compile
git push main blade-rebalancing
# open PR
```

**Comment by crookedneighbor** [comment]
Edited last comment to correct errors/make clearer

**Comment by chimericdream** [comment]
@crookedneighbor that makes sense. I was trying to pull the commits into the `habitrpg` repo. I didn't think about pushing them from `habitrpg-shared`.

**Comment by Alys** [comment]
Thanks @crookedneighbor!

**Pull request merged**
