### PR TITLE
Fixes #14438: a11y: add semantic roles to habit and todo controls

### LINKED ISSUE #14438: improve link selection when using accessibility options
> A new bug report from @jamiehooper:
> This is not technically a bug, but is a user interface accessibility issue for disabled people. I cannot use a mouse due to chronic pain so I use a Chrome extension called Vimium to click on links. For it to work the links have to be labeled with HTML tags. The links for checking a daily habit off are exclusively JS so I can't click on them which really limits my accessibility for website. If y'all were able to add that that would be amazing :))

### PR DESCRIPTION
**Pull request by ashbork**
# Changes
Habit and task controls (meaning the +/- button in Habits and the checkbox in Dailies/Todos) didn't have an appropriate ARIA role. This caused some accessibility tools _such as Vimium in this issue's case_ to ignore them when looking for clickable elements to select, since these clickable elements are actually `div`s in our case. This PR adds the roles to these clickable elements (`checkbox` to `daily-todo-control` and `button` to `habit-control`) and `aria-disabled` when appropriate.

An example of the PR in action; the extension Vimium successfully finds the correct buttons, respecting when they're disabled
_An example of the PR in action; the extension Vimium successfully finds the correct buttons, respecting when they're disabled_

Due to these changes being only relevant with A11Y tools (Vimium and screen readers such as ChromeVox), there is no impact otherwise and only positive impact if using these tools.

I think it may also be a good idea to add [aria-label](https://developer.mozilla.org/en-US/docs/Web/Accessibility/ARIA/Attributes/aria-label)s for these buttons as there's currently no way to tell + and - with screen readers alone; I can do that in another PR

Fixes #14438

### CODE REVIEW

**Comment by ashbork** [comment]
Hi, I'm a first time contributor and the test hadn't run because of that, could an admin take a look?

**Comment by SabreCat** [comment]
Nice! I think this will work.
One question or suggestion: should aria-labels be delivered in the user's language where possible? If so, we could create string tokens in `website/common/locales/en/tasks.json` and use e.g. `:aria-label="$t('scoreUp')"`

**Comment by ashbork** [comment]
I hadn't considered doing that, I'll have to take another look

**Comment by ashbork** [comment]
Done! I believe the other locales' translations will be done automatically, is that right?

**Comment by ashbork** [comment]
Could someone take a look?

**Comment by CuriousMagpie** [comment]
This looks really good! Thanks so much for your work on this. And if you can let us know your Habitica UUID, that would be awesome.

**Pull request merged**
