### PR TITLE
Removed unused I18N strings from the `front.json` files (related to issue #9957)

### PR DESCRIPTION
**Pull request by RaitheOfDureya**
[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
This PR fixes part of issue #9957

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
Took me a while, but I finally identified the following unused strings in the `front.json` file.  No dynamically generated strings were found.

At the moment I only removed the strings from the `locales/en` folder to make it easier to revert if necessary. Once the strings are reviewed, I can delete them from other languages.

- alexandraQuote
- althaireQuote
- andeeliaoQuote
- autumnesquirrelQuote
- dragonsilverQuote
- dreimQuote
- elmiQuote
- evagantzQuote
- frabjabulousQuote
- infhQuote
- irishfeet123Quote
- sixteenBitFilQuote
- skysailorQuote
- supermouse35Quote
- zelahQuote
- kazuiQuote
- businessSample1
- businessSample2
- businessSample3
- businessSample4
- businessSample5
- businessText
- choreSample1
- choreSample2
- choreSample3
- choreSample4
- choreSample5
- communityBug
- communityFeature
- communityKickstarter
- communityReddit
- devBlog
- companyPrivacy
- companyTerms
- companyVideos
- contribUse
- examplesHeading
- featureAchievementByline
- featureAchievementHeading
- featureEquipByline
- featureEquipHeading
- featurePetByline
- featurePetHeading
- featureSocialByline
- featureSocialHeading
- featuresHeading
- forgotPass
- gamifyButton
- goalSample1
- goalSample2
- goalSample3
- goalSample4
- goalSample5
- goals
- wellness
- healthSample1
- healthSample2
- healthSample3
- healthSample4
- healthSample5
- landingp4
- landingp4header
- landingend
- landingend2
- landingp1
- landingp2
- landingp2header
- landingp3
- landingp3header
- leadText
- loginAndReg
- loginFacebookAlt
- loginGoogleAlt
- motivate
- motivate1
- motivate2
- passConfirm
- passMan
- presskitDownload
- pkVideo
- psst
- punishByline
- punishHeading1
- punishHeading2
- questByline1
- questByline2
- questHeading1
- questHeading2
- rewardByline1
- rewardByline2
- rewardHeading
- sampleDailies
- sampleHabits
- sampleToDo
- schoolSample1
- schoolSample2
- schoolSample3
- schoolSample4
- schoolSample5
- socialTitle
- teamSample1
- teamSample2
- teamSample3
- testimonialHeading
- localStorageClearing
- localStorageClearingExplanation
- tutorials
- unlockByline1
- unlockByline2
- unlockHeadline
- useUUID
- watchVideos
- marketingInquiries
- apps
- imagine1
- alreadyHaveAccount
- getStartedNow
- altAttrWebstorm
- altAttrGithub
- altAttrTrello
- altAttrSlack
- altAttrNavLogo
- altAttrLifehacker
- altAttrNewYorkTimes
- altAttrMakeUseOf
- altAttrForbes
- altAttrCnet
- altAttrFastCompany
- altAttrKickstarter
- altAttrDiscover
- altAttrFrabjabulous
- altAttrAlexandraSo
- altAttrEvaGantz
- altAttrSupermouse35
- altAttrAlthaire
- altAttrInfH
- altAttrDreiM
- altAttrKazui
- altAttrAutumnesquirrel
- altAttrIrishfeet123
- altAttrElmi
- altAttr16bitFil
- altAttrZelahMeyer
- altAttrSkysailor
- altAttrIonic
- missingAuthParams
- marketing4Lead3-3

The following dynamically generated strings were found during the PR review:

- pkPromo
- pkLogo
- pkBoss
- pkSamples
- pkWebsite
- pkiOS
- pkAndroid

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 6544e17f-237b-4915-ae7e-47744c0dc1bd

### CODE REVIEW

**Comment by paglias** [comment]
these are looking good!

**Comment by RaitheOfDureya** [comment]
Here you go, @paglias :smile:

**Comment by paglias** [comment]
I think these ones are all used here https://habitica.com/static/press-kit (except for the Video one)

```
pkVideo
pkPromo
pkLogo
pkBoss
pkSamples
pkWebsite
pkiOS
pkAndroid
```
Schermata 2020-10-13 alle 19 30 25

**Comment by RaitheOfDureya** [comment]
> I think these ones are all used here https://habitica.com/static/press-kit (except for the Video one)

> pkVideo
...

@paglias, should I re-add `pkVideo` too? 

Do you suspect this string is being used elsewhere? or are you telling me to add all but `pkVideo` ?

**Comment by paglias** [comment]
@RaitheOfDureya sorry I meant to add back all of them except for `pkVideo`, I'm pretty sure it's only used there

**Comment by RaitheOfDureya** [comment]
Thank you for clarifying this issue, @paglias.
I made the requested changes and updated the description of the PR.

**Comment by LioZam** [comment]
There were some checks not passed in the commit @RaitheOfDureya @paglias .  The change caused an issue with parsing of (at least) one file. I am not sure what the procedure is.. but erm.. Just thought I mention it here.

(re: ko/Front.json error)

**Comment by RaitheOfDureya** [comment]
Thanks for finding this bug, @LioZam 

Probably one of the strings removed was the last one in the file which ended up leaving a trailing comma.
Your bugfix #12790 went straight to the point :)

**Comment by RaitheOfDureya** [comment]
I ended up jumping to conclusions. This error must have been introduced in another commit, because the changes made in the `site/comum/locais/ko/front.json` file in this PR did not leave a trailing comma.

**Comment by LioZam** [comment]
This was a correct jump, though. It is like you said first: You deleted the last line and the new last line did still have a comma for the next entry, that was not deleted. I did also comment this now in the file-changing log in the history of the file. I hope you can find it now XD

**Comment by RaitheOfDureya** [comment]
That's it, @LioZam! Double checked :)

**Comment by SnowCrasher** [comment]
For some reason, Korean is still displaying those strings on Weblate but looks like they are ghost strings since they just give internal server error upon interacting with them. Currently impossible to progress translating Front component in Korean since it just keeps trying to access those 'removed' strings next. It also still says 328 strings total in [front/ko/](https://translate.habitica.com/projects/habitica/front/ko/) while the other languages display the correct 181 strings.

**Comment by RaitheOfDureya** [comment]
The `website/common/locales/ko/front.json`looks fine for me, but there is a strange file in the `locales/ko` folder: `website/common/locales/ko/backgroundsjson_ko.json`.

It is not a simple copy of the `website/common/locales/ko/backgrounds.json` file, because the translations differ in them...

**Comment by paglias** [comment]
cc @SabreCat

**Pull request merged**
