### PR TITLE
Added indication of current preferences to avatar customization page

### PR DESCRIPTION
**Pull request by hairlessbear**
Added the `selectableInventory` class to current preferences to match the style of the equipment page.

selection_020

### CODE REVIEW

**Comment by Alys** [comment]
Oh YES!!!

**Comment by crookedneighbor** [comment]
I just noticed this problem today! Good timing.

**Comment by hairlessbear** [comment]
Woo! Don't merge it quite yet though. I just noticed that my branch was missing the new animal ears and skins. The current code works for the new skins, but not the ears. I'm working on fixing that now.

**Comment by hairlessbear** [comment]
So the animal ears are more complicated than all of the other options. The issue is that they appear on the equipment page as well, and thus can be used in a costume. This means that it is possible to have two different sets of animal ears enabled; one that is equipped, and one that is a costume. 

I thought I could fix this with a ternary operator, something like `ng-class='{selectableInventory:user.items.costume.headAccessory == item.key ? user.items.costume.headAccessory == item.key : user.items.gear.equipped.headAccesory == item.key}'`. The issue is that the costume settings persist after you disable the costume, unless you click the "Unequip Costume" button. This means that `costume.headAccessory` will still be populated when the costume isn't enabled, leading to a set of ears being labeled as "active" when they in fact aren't. I won't be able to continue work on this until later tonight, but I'd appreciate any suggestions on how to write the logic.

**Comment by Alys** [comment]
`preferences.costume` is true if you have costumes enabled, and false otherwise. 

If the user is using a costume, we don't care if the ears are equipped as Battle Gear because they have zero stats and aren't visible.

So I think mark the ears as green if `preferences.costume is true & item is equipped as Costume` or if `preferences.costume is false & item is equipped as Battle Gear`.

**Comment by hairlessbear** [comment]
@Alys I made the check based solely on `preferences.costume`. If `preferences.costume` is true, we want the ear preferences of the costume to display, even if there are none selected, because that will be what appears in the avatar. Also worth noting: when the costume is enabled, choosing the ears from the avatar customization page changes the `costume.headAccessory` setting. The `equipped.headAccessory` setting is only modified when the costume isn't enabled.

**Comment by Alys** [comment]
Yup, that's the same thing. Looks good.

**Comment by hairlessbear** [comment]
@Alys I see; I just reworded what you said in a more complicated manner. I have a bad habit of doing that :confounded: 

I'm pretty sure every option has the `selectableInventory` logic attached to it now. I'll double check, but let me know if I missed anything!

**Comment by Alys** [comment]
But your code was simpler!

**Comment by hairlessbear** [comment]
@Alys Fair point. You can ignore my previous message about rewording; it was a result of me being ridiculous. I'm tired, and sometimes when that happens I get self-deprecating and paranoid about the quality of my work. I usually catch it and stop myself from saying anything silly, but alas, I missed it this time. Nothing to worry about though, I just need to go to bed soon :sleeping: Sorry for the confusion.

**Comment by crookedneighbor** [comment]
Awesome work, notated toward your next tier.

**Comment by hairlessbear** [comment]
@crookedneighbor Thanks! Out of curiosity, why did the number of commits suddenly jump to a billion?

**Comment by crookedneighbor** [comment]
Weird. Don't know. Did you rebase while on this branch or something?

**Comment by hairlessbear** [comment]
I think I figured it out. As I said earlier, the branch I started this from didn't contain the animal ears. So I pulled the most recent code, and updated the section on animal ears. Only after I did this did I realize that I was on my develop branch and not the correct branch. After some googling, I used [this method](http://stackoverflow.com/a/13897766) to push the changes from develop onto this branch. That's probably what happened. I'm still not sure why they didn't show up until you merged though.

**Pull request merged**
