### PR TITLE
add some visual feedback to the avatar customizer on click

### PR DESCRIPTION
**Pull request by caycefischer**

### CODE REVIEW

**Comment by caycefischer** [comment]
Just some subtle visual feedback saying “yes, the app registered your click and has made that change”

toast

**Comment by lefnire** [comment]
Woo, glad you added this! It was on my bucket list, but my + css = wah wah

**Comment by caycefischer** [comment]
No problem! I noticed it right away, and it was a quick fix. 

Speaking of markup/css... I don't want to rock the boat or change code you're comfortable with—but is there a particular reason the layout for stuff like customizations use `table`s? If I rewrote some of layout/UI with non-table markup (in a branch of course!) would that be OK? 

One immediate benefit would be that those new highlights would "fit" the options better instead of filling up the whole empty box of the `td`.

**Comment by lefnire** [comment]
Gonna be honest with you Zak, was counting on you to say just that :) I tried with divs, floats, then Bootstrap `row-fluid` containers, and couldn't get anything working. So i said "screw this, I'm going tables and hopping @Zakkain steps in like last time" haha

**Comment by caycefischer** [comment]
Haha, awesome! OK, I'll make a `ui-layout` branch, and start with re-writing the tables in that modal.

handshake

**Comment by lefnire** [comment]
The whole party system introduced tables everywhere too. So anywhere you see places that make you cringe, have at it!

Edit: Omg. your gifs are amazing.

**Comment by caycefischer** [comment]
Aye aye, sir! I'll keep an eye out.

(PS: http://zkkn.co for a whole bunch of gifs :smiley: )

**Comment by StanLindsey** [comment]
I'd like to point out I just sat through all those GIFs. Thank you sir.

**Comment by lefnire** [comment]
I actually spent a good 10-15m in there myself.

**Comment by StanLindsey** [comment]
Or should I say;
 (approval)

**Pull request merged**
