### PR TITLE
Level 100 no more attribute points message

### LINKED ISSUE #5203: prevent ongoing questions about no attribute points after level 100
Now that attribute points are not gained above level 100, we're going to get ongoing questions about that; we've had several over the past few days. I suggest that when you are above level 100, the User -> Stats screen contains a message stating that there's no more points, but that you can keep levelling up, or use the Orb of Rebirth for free. It could perhaps go just under the arrowed text in the image below.

@lemoness What do you think?

screen shot 2015-05-13 at 8 14 57 pm

### PR DESCRIPTION
**Pull request by hairlessbear**
Fixes #5203. 
selection_019

### CODE REVIEW

**Comment by hairlessbear** [comment]
I opted to put the message before the unallocated attribute points since that number no longer matters after level 100. We want the message to be the first thing they see when they look in the area, so it should be at the top.

**Comment by crookedneighbor** [comment]
Should we mention something about how the orb is free after level 100?

@lemoness Do you have a particular phrasing you want?

**Comment by Alys** [comment]
@lemoness Looking at the message in the screenshot, the "Congrats!" part seems out of place. We've had a few minor complaints about lack of attribute points being demotivating, so some players won't feel this message is congratulatory.

**Comment by hairlessbear** [comment]
@lemoness @Alys @crookedneighbor what do you think about this? "Now that you've hit level 100, you won't gain any more Attribute Points. You can continue leveling up, or start a new adventure at level 1 by using the Orb of Rebirth, available for free in the Market."

**Comment by crookedneighbor** [comment]
I like it!

**Comment by crookedneighbor** [comment]
I've changed the text to @hairlessbear's new version. @lemoness If you want something different, just post it here and I'll change it straightaway.

[I did make one more change](https://github.com/HabitRPG/habitrpg/commit/9017ba7d7e583458db008a47de1718562af4f405). I made the "0 Attribute points" message hide if the user is at or above level 100 and does not have any points to allocate. That way, all they'll see is the new warning message:

screen shot 2015-05-16 at 10 54 01 pm

If they're at or above level 100 and have attribute points, they'll see both the message and attribute points they have left:

screen shot 2015-05-16 at 10 55 04 pm

If they're below level 100 and have used all their points, they'll still see the 0 attribute points message:

screen shot 2015-05-16 at 10 56 17 pm

**Comment by crookedneighbor** [comment]
@hairlessbear I've notated this toward your next tier.

**Comment by hairlessbear** [comment]
@crookedneighbor I noticed that you added a one-time binding to one of the `user.stats.lvl` checks, but not the other. Is there any particular reason for that? I'm not sure there should be a one-time binding on either, since there is a possibility that a user could hit level 100 while on the page (e.g., third-party extension, quest completion). Although I admit, the chance of that occurring is pretty small.

**Pull request merged**
