### PR TITLE
fix challenge layout 

### PR DESCRIPTION
**Pull request by negue**
This fixes issues on smaller devices

### CODE REVIEW

**Comment by Alys** [comment]
@negue We have a couple of issues related to challenge layout problems and one of them has someone working on it now, so I'm just wondering if this is related to either of those issues and/or if the contributor needs to know about this fix. I don't suppose you have before and after screenshots for this PR? Or are there any descriptions about what it changes that you could add, maybe something that's already been written about the problem somewhere else that could be pasted in quickly?

These are the issues I'm thinking of:
- https://github.com/HabitRPG/habitica/issues/11500 (in progress by a contributor)
- https://github.com/HabitRPG/habitica/issues/11259 (on hold waiting for design decisions)

**Comment by Alys** [comment]
Actually, sorry, I see that you've already approved a PR by the contributor for the first issue I listed, so they definitely don't need to know about this. :) 
The other issue might be affected by this though - after this is merged will we need to check #11259 to see if the problems described in it have changed?

**Comment by negue** [comment]
The issues I fixed in this PR in a narrow view:
- (where two challenge cards were side by side) the task-counts per type didn't wrap at all => here I added a wrap to give them some "space" to breath ^^
- all challenge cards were only listed as 80% width => changed to 100%
- added a margin under the add-challenge-button 

I couldn't find any other (challenge) layout issues, if someone does please add them here :)

#11500 (fixed by #11618) shouldn't be affected by these changes

**Comment by Alys** [comment]
@negue Great, thanks! I've marked this PR as "notify helpers" so that when it's merged, I'll be reminded about it and then I'll update https://github.com/HabitRPG/habitica/issues/11259 if needed.

**Comment by Tressley** [comment]
Still seeing display issues. This one seems to be when the username is too long for the line and wraps into the categories.

Screen Shot 2019-12-12 at 9 16 21 AM

**Comment by negue** [comment]
@Tressley this issue will be fixed by #11618

**Comment by paglias** [comment]
Is this ready to go?

**Comment by Tressley** [comment]
@paglias -- LGTM. 👍

**Pull request merged**
