### PR TITLE
Added more information on two methods

### PR DESCRIPTION
**Pull request by Atomk**
In my opinion API documentation could be more clear, so a developer that is totally new to HabitRPG could understand what every method does without having to try each one.
@lefnire Seems that this can be merged automatically, is there anybody that checks if what I'm doing is right?

### CODE REVIEW

**Comment by Atomk** [comment]
I'm totally a newbie about GitHub, sorry.

**Comment by lefnire** [comment]
Legit! yeah, I'll manually review each PR before merging. UUID?

**Comment by Atomk** [comment]
Well, this way I'm sure I can't make big errors!
My UUID id d8fc8d8b-a10f-416a-b089-587db2af9e4d, however if it is for contributor level don't worry, I don't feel I made something that special (and I'm level 4 yet, what a honour)
Maybe #3619 is something worth it anyway!

**Comment by deilann** [comment]
I'll still put your contribution in the hall so it's noticed as you get
closer to level 5 :)

**Pull request merged**
