### PR TITLE
Tried to make a line translatable

### PR DESCRIPTION
**Pull request by ghost**
Tried to make the "Only group leader can create challenges" line in the
guild creation dialog translatable

### CODE REVIEW

**Comment by ghost** [comment]
Addresses issue https://github.com/HabitRPG/habitrpg/issues/4522

Separate issue created by mistake https://github.com/HabitRPG/habitrpg/issues/5179 is closed

**Comment by Alys** [comment]
@GitHubSphinx Can you please show us a screenshot of the guild creation dialog with this change in place so that we can be sure that it looks the same? If you don't have a local install yet and run into problems while setting one up, you can post here or in the Aspiring Coders guild.

**Comment by ghost** [comment]
@Alys sure, please excuse me for not doing it beforehand. As the line is the same, I've changed wording for local test. Suggested translatable line line is just the same as previously online (i.e. without words in brackets).

Screenshot of special test line: http://oi58.tinypic.com/1zgbwnt.jpg
Screenshot of normal suggested translatable line while Russian locale is selected (this line is still in English as locales are updated on transifex): http://oi61.tinypic.com/29c5rag.jpg

I'm not able to create a guild, as I haven't found a way to assign myself gems locally yet (I've seen the guide, but I can't access admin console yet) - so I'm not able to make a screenshot of the second occurrence of the line inside the guild.

I must tell you that for some reason my local copy keeps crashing even with no changes to the trunk. So I'll have to consult with the Aspiring Coders guild.

@paglias Guidance for linguists says one shouldn't change other locales than "en" so I only added the key of the line to "en" locale. Is that right?

**Comment by paglias** [comment]
Yeah it's ok
Il 10/mag/2015 13:30, "Sphinx" notifications@github.com ha scritto:

**Comment by crookedneighbor** [comment]
Looks great!

Couple of housekeeping tips for the future.

When working on the app locally, at the bottom of the app, in the footer, there should be a debug menu where you can add gems for yourself.

I'd recommend [creating a branch](https://help.github.com/articles/github-flow-in-the-browser/) when working on the git repository, rather than committing directly to the develop branch. That will allow your develop branch to stay clean and in sync with Habit's. Plus, if each feature/bug you're working on is on a separate branch, you can work on and submit multiple pull requests!

Is there a reason you committed your "local test" change? You can always work on things and view them in the app without committing the change. Since the first commit is the only relevant one, I'm going to `git cherry-pick` just that one, but that will leave your develop branch out of sync with Habit's. I recommend resetting it to Habit's develop branch (let me know if you need help doing that, and if so, what you're using to commit your changes: command line, Github's app, etc).

Finally, and this is a really nitpicky thing, but our translatable strings are in mixedCase, so it should be `leaderOnlyChallenges` not `LeaderOnlyChallenges` with the first letter not capitalized. I've corrected it and am merging it in now.

Thanks for your help with this! I've notated this toward your fourth contributor tier and added blacksmith to your list of contributor titles.

**Comment by ghost** [comment]
@crookedneighbor Thank you for your kind words and tips! Please excuse me for all the mess. I wanted to follow the guideline to begin with something "small". It's true that I haven't got any real experience with GitHub - and experience in programming is very limited and nearly forgotten. I feel uncomfortable about making you spend your time on nursing with me. So I'll keep in mind all your tips. I do greatly appreciate the time you kindly paid to my first steps!

**Comment by crookedneighbor** [comment]
No worries. One of my favorite parts of working on Habit is helping new programmers. Never be afraid to ask for help!

**Pull request closed without merging**
