### PR TITLE
added test case for #8423 (searing brightness should not affect challenge tasks)

### PR DESCRIPTION
**Pull request by lynxlynxlynx**
split off #8427

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
There you have it, the test fails, 0.5957446808510638 vs 0.

**Comment by paglias** [comment]
Can this test go into #8427? The fact that current tests weren't failing means they weren't written correctly to spot these bugs and I'd like to have one working once #8427 is merged

**Comment by paglias** [comment]
actually never mind, I'll merge both at the same time, thanks a lot for this!

**Comment by TheHollidayInn** [comment]
IF I am reading this correctly, this test only fails without the change. The test won't fail once the change is made (which is already tested for in the other PR). So, we won't merge this in, right?

**Comment by paglias** [comment]
We'll merge it to be sure this case is covered by tests and in future if
this bug comes back we'll notice it immediately. The problem is that
current tests around this functionality weren't working as expected (I'm
still unsure why)

Il 23 Gen 2017 16:15, "Keith Holliday" <notifications@github.com> ha
scritto:

**Pull request merged**
