### PR TITLE
highlight spell item when it has class of 'active'

### PR DESCRIPTION
**Pull request by kangabell**
re: https://github.com/HabitRPG/habitrpg/issues/4399

### CODE REVIEW

**Comment by kangabell** [comment]
@crookedneighbor can you hook up the items with a class of "active" when they are selected? It should go on the corresponding a.btn-buy. Also feel free to change the class name if you think of a more appropriate one.

**Comment by crookedneighbor** [comment]
`active` is great. All the other active classes are just as specific to their respective elements, so it shouldn't collide with anything.

**Note:** If _I supply the angular code_ to make this work, you'll only get partial credit toward a [contributor tier](http://habitrpg.wikia.com/wiki/Contributor_Rewards). If you'd like help doing it yourself, you'll get full credit towards a contributor tier. Not sure what contributor level you're at (will need your user id to look that up), but this could be the difference between gaining a contributor level and just getting credit toward a level. Does that make sense?

**Comment by crookedneighbor** [comment]
And the `ng-class` directive is MY FAVORITE ANGULAR DIRECTIVE. So I'm happy to teach people about it.

**Comment by kangabell** [comment]
Okay cool did not know that – I haven't officially contributed yet so that would be cool. Yes please guide me! I am excited to use your favorite angular directive lol.

**Comment by crookedneighbor** [comment]
Okay! I updated the `views/shared/tasks/task.jade` file to make this process easier, so you're going to want to pull in the latest changes from the main repo. (I just changed a variable name from `spell` to `skill`. You'll see why later)

Well, `ng-class` will be added to the `a.btn-buy` element like any other attribute: `a.btn-buy(ng-class='')`, there are [a couple of ways to use ng-class](http://stackoverflow.com/questions/7792652/what-is-the-best-way-to-conditionally-apply-a-class), but the most straightforward way for what we need to do is this: `ng-class='{ class-name: condition-where-we-would-use-class-name }'`

So if we had a class `error` and we only wanted it to apply when array errors contains at least one string (the text of the error), we might say `ng-class='{ error: errors.length > 0 }'`. So when `errors = []`, then `errors.length == 0` and does not satisfy the condition. If `errors = ["email not formatted correctly", "Another error"]` then `errors.length == 2`, which is greater than 0, so the class `error` would be applied.

For our case, we're going to want to check and see if the current spell being cast is the same as the spell we just clicked. The current spell being cast is [defined here](https://github.com/HabitRPG/habitrpg/blob/ff3d942696c374226f445a9e2a122b286744f95c/public/js/controllers/rootCtrl.js#L202). Whenever a spell is begun, the variable `$scope.spell` is populated with the spell that was cast. So all we need to do is compare the unique key of `$scope.spell` with the unique key of the spell in the task list. 

The skills are [populated for the user to see in the Jade file here](https://github.com/HabitRPG/habitrpg/blob/develop/views/shared/tasks/lists.jade#L125-L137).

It looks a little complicated, but it's using an `ng-repeat` (another Angular directive) to populate each of the skills that the user has for their own class. So even though only one `li` element is listed, it'll end up populating 4 `li`s for a user that has chosen a class and leveled up enough to get all of the skills. You can see on [line 131](https://github.com/HabitRPG/habitrpg/blob/develop/views/shared/tasks/lists.jade#L131) that the ng-click is what starts casting the spell, by activating `castStart(skill)`.

So what we need to check the value of `skill.key` to `spell.key`, if they match, apply the class of active. (We don't have to worry about the `$scope` part, that's taken care of by Angular) This is why I had to change the ng-repeat's variable name to `skill`, if we left it as `spell`, the check would be if `spell.key` was equal to `spell.key`, which is always true, because the variable inside the `ng-repeat` would override the variable spell in the root controller, and it would just be checking against itself.

There's one other place we'll need to adjust (the area for snowballs and spooky sparkles), but it should be pretty easy once we've done it once for the regular spells.

That's kind of an information dump, so if you have questions feel free to ask. When you're ready, just push your change to this branch and I'll review it.

**Comment by crookedneighbor** [comment]
@kangabell How's it going? No rush, just checking in.

**Comment by kangabell** [comment]
@crookedneighbor Awesome thanks for all this info! Sorry been a bit under the weather but I'm back on now. 

I looked at your most recent commit with that file you mentioned  (https://github.com/HabitRPG/habitrpg/commit/dd4e8d74c7ca675de627c5d4e477816fa1b47951#diff-d909bd43f8de75ff3be7f2fe6f5bc317) but doesn't look like you changed any variable name there. Am I missing something?

**Comment by crookedneighbor** [comment]
I changed spell to spellObj here: https://github.com/HabitRPG/habitrpg/commit/9da000ec4e87e96792b486461496180ba5660037

Then I decided the spellObj was a really stupid name, and since they're referred to as skills in the rewards column, I changed it to skill here: https://github.com/HabitRPG/habitrpg/commit/8ba0bb5d88e9625b1f956125e11f724800df0e15

**Comment by kangabell** [comment]
Ah okay, wrong file. Got it.

**Comment by kangabell** [comment]
How do I get snowballs and spooky sparkles on my account?

**Comment by crookedneighbor** [comment]
Before I answer your question about snowballs and spooky sparkles, I took a look at your file, and it doesn't look like you've merged in the change from develop yet. (If you have, and you just haven't pushed the change up to your remote branch, skip to the spooky sparkles section) To pull in the lastest changes, run this command in your terminal while in the habitrpg repo:

``` bash
git pull https://github.com/HabitRPG/habitrpg.git develop
```

You're going to get a merge conflict in the `views/shared/tasks/list.jade` file. You'll see this starting at line 131:

```
<<<<<<< HEAD
    a.money.btn-buy.item-btn(ng-click='castStart(skill)', ng-class='{active: skill.key == spell.key}')
=======
    a.money.btn-buy.item-btn(ng-click='castStart(skill)')
>>>>>>> cda16d5bc01068b6681a93bf98757e6432f7ca5a
```

You should just be able to remove the git comments and my version of the line (the one without the ng-class) and then commit all the changes for the merge. That'll get you up to date and should be all you need to do for the regular skills to work.

Okay, onto Spooky Sparkles and snowballs.

Now that you have all the latest changes from the develop branch, you should be able to get snowballs from [the seasonal shop](http://localhost:3000/#/options/inventory/seasonalshop) (link to localhost:3000).

For Spooky Sparkles, you can either update the database directly, or follow these directions and give your user admin rights and then grant it through the hall of heroes page.
1. Follow [these instructions to make your user an admin](http://habitrpg.wikia.com/wiki/Guidance_for_Blacksmiths#Get_Admin_Rights).
2. Get your [user id](http://localhost:3000/#/options/settings/api) and go to the [hall of heroes](http://localhost:3000/#/options/groups/hall/heroes). Put your user id in the text box. Press submit.
3. Go to the items section. Put in `items.special.spookDust` and however many you want. Press the submit button at the bottom.
4. Go back to tasks and refresh the page. You have spooky sparkles!

To make the `ng-class` work on the snowballs/spooky sparkles, you'll have to add it to [this line](https://github.com/HabitRPG/habitrpg/blob/8ba0bb5d88e9625b1f956125e11f724800df0e15/views/shared/tasks/lists.jade#L107). But instead of comparing `spell` with `skill`, you'll be comparing `spell` with `Content.spells.special.#{k}`. So it'll be `ng-class='{active: Content.spells.special.#{k}.key == spell.key}'`

**Comment by kangabell** [comment]
@crookedneighbor okay have a look now

**Comment by crookedneighbor** [comment]
Just tested it, looks great!

This will count towards a contributor tier. Can you post your user id here? It can be found in [settings > api](https://habitrpg.com/#/options/settings/api)

**Comment by kangabell** [comment]
Great, thanks for your help!!
ID: 3ea394da-612a-41ba-be59-74fcedcf36a1

**Comment by crookedneighbor** [comment]
Tier++

**Pull request merged**
