### PR TITLE
add extra text to flagging confirmation dialog and to top of PM inbox -- Fix for issue #4648, parts 3 and 4

### PR DESCRIPTION
**Pull request by pnrich**
This addresses parts 3 and 4 of issue #4648. It's just a couple changes in the English translation files to clarify some things about when it is appropriate to flag a message or post.

### CODE REVIEW

**Comment by Alys** [comment]
@pnrich Thank you for this! Could you please post a screenshot of what it looks like now? That will help us review the change.

**Comment by pnrich** [comment]
Part 3

abusemodal change

Part 4

blurbinbox change

**Comment by Alys** [comment]
@lemoness What do you think of the text in those two screenshots? In the second one, the sentence at the top of the inbox has been changed to include instructions to email you about flaggable offences (a short-term fix until we can make flags work in the inbox).

**Comment by lemoness** [comment]
Both look great!

**Comment by SabreCat** [comment]
Thanks @pnrich! This will count toward a contributor tier. Could you provide us with your Habitica User ID, from https://habitica.com/#/options/settings/api ? Do not include your API Token, as that's equivalent to a password.

**Comment by pnrich** [comment]
Thanks! User ID is 5914861f-d267-45c5-9cfb-f6be2dca4e12. Glad I could help!

**Comment by SabreCat** [comment]
Great! I've noted this as progress toward Tier 2. Each contributor tier requires more effort than the previous, so this alone didn't bump you up, but keep helping out and we'll express our thanks accordingly!

**Pull request merged**
