### PR TITLE
Removed unused I18N strings from the `limited.json` files (related to issue #9957)

### PR DESCRIPTION
**Pull request by RaitheOfDureya**
[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
This PR fixes part of issue #9957

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
I have identified the following unused strings in the `limited.json` file.  **There are probably some dynamic generated strings**.

At the moment I only removed the strings from the `locales/en` folder to make it easier to revert if necessary. Once the strings are reviewed, I can delete them from other languages.

- limitedEdition
- seasonalEdition
- winterColors
- valentineCardExplanation
- valentineCardAchievementTitle
- valentineCardAchievementText
- seasonalShopClosedTitle
- seasonalShopTitle
- seasonalShopClosedText
- seasonalShopSummerText
- seasonalShopFallText
- seasonalShopWinterText
- seasonalShopSpringText
- seasonalShopFallTextBroken
- seasonalShopRebirth
- nyeCardExplanation
- nyeCardAchievementTitle
- nyeCardAchievementText
- holidayCard
- winterPromoGiftHeader
- winterPromoGiftDetails1
- winterPromoGiftDetails2

Are `dateEndApril`, `dateEndJune`, `dateEndAugust`, `dateEndSeptember` being used in `website/common/script/content/hatching-potions.js` ?
```javascript
... date: t(`dateEnd${pot._season}`), ...
```

Are the following strings being used [here](https://github.com/HabitRPG/habitica/blob/026e1a5bca2783c48069751d84f423266a78129b/website/client/components/inventory/items/cards-modal.vue#L43-L47) (`habitica/website/client/components/inventory/items/cards-modal.vue`)?
- valentine0
- valentine1
- valentine2
- valentine3
- nye0
- nye1
- nye2
- nye3
- nye4

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 6544e17f-237b-4915-ae7e-47744c0dc1bd

### CODE REVIEW

**Comment by paglias** [comment]
```
Are the following strings being used [here](https://github.com/HabitRPG/habitica/blob/026e1a5bca2783c48069751d84f423266a78129b/website/client/components/inventory/items/cards-modal.vue#L43-L47) (`habitica/website/client/components/inventory/items/cards-modal.vue`)?
- valentine0
- valentine1
- valentine2
- valentine3
- nye0
- nye1
- nye2
- nye3
- nye4
```

These are used!

Also all the ones ending in `CardExplanation`, `CardAchievementTitle` `CardAchievementText` and the ones starting with `seasonalShop`

**Comment by paglias** [comment]
Sorry, looks like `winterPromo...` are used as well, I think this PR can be limited to the following;

```
holidayCard
limitedEdition
seasonalEdition
winterColors
```

**Comment by RaitheOfDureya** [comment]
@paglias , thanks for the review. I restored the strings that are in use and removed only those that you approved from all the files.

**Comment by paglias** [comment]
thanks! By the way @RaitheOfDureya , I'm not sure if this was explained before but we test the PRs for around a week to make sure nothing broke, so I'm going to merge all the ones marked as `being tested on delta` next Monday

**Comment by RaitheOfDureya** [comment]
Yeah, you had already explained this to me. Thanks anyway.

**Comment by paglias** [comment]
thanks! Noted

**Pull request merged**
