### PR TITLE
Improvements for class tour

### PR DESCRIPTION
**Pull request by dwhitlow**
Fix wording in class guide, and also don't show a step to new users if they haven't unlocked that tab yet.

### CODE REVIEW

**Comment by dwhitlow** [comment]
@lefnire First contribution to this project, so I think I may have gotten the wrong branch. Please let me know if that's the case and I'll switch to master.

**Comment by lefnire** [comment]
Alas, a noble effort (and I imagine lots of code-hunting). You found a good problem, but the better solution is to not show the button at all unless they have class system available: 3b3b0e6 (doesn't unlock till lvl 10). gimme your UUID anyway

**Comment by lefnire** [comment]
re the wording change 50% => 1.5%, methinks it actually _is_ 50% since it's `bonus*1.5`. Were there other wording updates I'm missing?

**Comment by dwhitlow** [comment]
Thanks. UUID is b04df801-7efc-48c2-99a0-f44e1f345fb7.

For the wording update, it's actually the other way around. Currently, the class guide says the bonus is 1.5%, but as you've stated, the bonus is 50%. This change updates the text to reflect that.

**Comment by lefnire** [comment]
So it is! *facepalm*. Thank you sir

**Pull request closed without merging**
