### PR TITLE
return group members on questAccept / questAbort

### PR DESCRIPTION
**Pull request by negue**
For #4000

This is just a possible fix to return the members.

I had to clone the object, because without, the group.members stayed the same :(

Any other workaround? or hints?

### CODE REVIEW

**Comment by negue** [comment]
@lefnire Do you have any hints ? Any "better direction" I should go to fix this issue.

**Comment by Alys** [comment]
I've tested this locally and it fixes the problem described in #4000. I can't comment though on whether this is the best direction. :)

**Comment by negue** [comment]
@paglias @deilann Could any of you, tell me if there is a better fix (refactored code) , I don't have any mongodb experience, and also don't know who is the mongodb pro here ^^

**Comment by Alys** [comment]
I've tested this again, just to be paranoid, and I still can't see anything wrong with it. All quest begin/cancel/abort actions work (both manual and automatic begin) and quest progress and completion works. It certainly fixes https://github.com/HabitRPG/habitrpg/issues/4042 which is driving many people crazy, so I'm merging this now, even though this kind of code isn't my strong point yet. I think fixing #4042 is more important than any hard-to-find glitches that might or might not be in this code. :)

**Comment by negue** [comment]
It fixes 4042 ? W00t, really? Didn't know that this is also a solution.

I just thought it would "only" fix #4000.

My current problem with my code is that I "load the current group with all members from mongodb" then "copy just members to the already existing group Obj" I just thought this would create some unneeded performance issues.

**Pull request merged**
