### PR TITLE
Replace hard-coded strings for env.t on views/shared/tasks/ folder

### PR DESCRIPTION
**Pull request by marcelosizer**
Added the "Other" popover to the button instead of the i.icon-question-sign and it's working now on file `task.jade` line `174`.

### CODE REVIEW

**Comment by lefnire** [comment]
Closed to follow up on other ticket I assume?

**Comment by marcelosizer** [comment]
@lefnire , @paglias requested to close this PR and wait until he makes the change to habitrpg-shared to continue replacing the strings.

**Comment by paglias** [comment]
In theory, @Sinza-, if you avoid translating strings from `content.coffee` you could continue.

Seeing this PR (it's perfect!) I think you can go on!

**Comment by paglias** [comment]
The only change is that translations files are now in [habitrpg-shared](https://github.com/HabitRPG/habitrpg-shared) so you'll have to send two PR one in habitrpg-shared from the translated strings and one here for references inside the jade files.

**Comment by marcelosizer** [comment]
Ok, I'll update them and then reupload.

**Comment by marcelosizer** [comment]
@paglias done. Want me to open a new PR?

**Comment by paglias** [comment]
no no, it's ok on this one, reopened

**Comment by paglias** [comment]
Ahhh, I accidentally merged that, don't know how but it's merged.... So if you could open a new one.... sorry @Sinza-

**Comment by marcelosizer** [comment]
Hahahaha, no problem!

**Pull request merged**
