### PR TITLE
Wiki, now with added locales

### PR DESCRIPTION
**Pull request by tjwds**
pew pew pew

[https://github.com/HabitRPG/habitrpg-shared/pull/200](https://github.com/HabitRPG/habitrpg-shared/pull/200)
[https://github.com/HabitRPG/habitrpg/pull/3420](https://github.com/HabitRPG/habitrpg/pull/3420)

### CODE REVIEW

**Comment by deilann** [comment]
thx! See shared comment. :)

**Comment by deilann** [comment]
lgtm uuid?

@lefnire et al: Build is failing for unrelated things, yeah?

**Comment by lefnire** [comment]
yes, unrelated

**Comment by tjwds** [comment]
@deilann 41777fc7-4647-4008-a2e9-3789e10e0652

**Comment by deilann** [comment]
:thumbsup: Documented, level 2 in progress! :)

**Comment by tjwds** [comment]
Also note [here](https://github.com/HabitRPG/habitrpg-chrome/pulls) ;-)

**Comment by deilann** [comment]
I'm not a chrome admin. :) Can't merge it.

**Pull request merged**
