### PR TITLE
Make all gears hidable

### PR DESCRIPTION
**Pull request by AdrienLemaire**
That's a feature I wanted to see. Heavy gears block some parts of the body, and users might want to hide them like it's possible with the helm.

### CODE REVIEW

**Comment by AdrienLemaire** [comment]
@lefnire works fine for me in local, but that's my first time doing jade/angular code, and there are no tests, so you'll want to double-check before merging (if this feature is ok with you, maybe there was some reason to only have helms hidable).

Note that a new migration file has been added to add default preferences to users.

Here a screenshot:

no helmet & no shield: 
helm

no weapon & no armor
armor

**Comment by lefnire** [comment]
The code looks great! You've really got a handle on all this, every time I think "let me just make sure he accounted for... yep, he did!"

Ok, I'll merge soon. I gotta move some stuff around a bit (master / develop, pulling in parts of mounts, etc). Also, we eventually have plans for [an armory](https://trello.com/c/83M5RqQB/299-armory), where users can hoard all the things they've purchased rather than being upgraded. Something you may be interested in.

**Comment by Pandoro** [comment]
Can we get some screenshots from how this looks? I'm afraid that just
hiding stuff will not look so great considering, and please correct me if I
am wrong, the skin sprites do not have outlines. This would pretty much
break the whole look of habit in my opinion :x

**Comment by lefnire** [comment]
Actually, yeah - @lemoness & @Pandoro might have some particular insight on this

**Comment by SabreCat** [comment]
It shouldn't look any different from just not buying the item in question, yeah?

That said, Hide Armor is going to be a mediocre option until you can customize clothing. Both genders' default clothes are kind of pants, no pun intended.

**Comment by Pandoro** [comment]
What I just was thinking is that it would look as if you are naked.
Probably this is a problem anyways as we would have to come up with
underwear :x But if it just reverts you to the basic look I guess
everything is fine.

**Comment by AdrienLemaire** [comment]
yes, I made it so removing armor would actually show armor lvl.0

Anyways, as @lefnire stated earlier, this would only be a temporary feature until the armory gets released.

**Comment by lefnire** [comment]
@Fandekasp sorry to do this to you man, could you rebase & fix this up to HEAD? I made the merge incompatible :x I say we get this on beta so pixelists can play with it

**Comment by AdrienLemaire** [comment]
lol

**Comment by AdrienLemaire** [comment]
@lefnire done, please merge again

**Comment by lefnire** [comment]
Seeing some funky-ness after changing gender. show some / hide some, switch gender and everything's shown (with checkbox mismatches). If a fix requires complex watchers & such, ping back here before jumping down rabbit hole and we'll discuss

**Comment by AdrienLemaire** [comment]
oh, I didn't see that. Wasn't even aware of the clothing choice for women.  Will also make it available to men then :D

**Comment by AdrienLemaire** [comment]
@lefnire 

I cloned the habitrpg-shared repo, then from the habitrpg one, I removed `build/bower_components/habitrpg-shared`, `public/bower_components/habitrpg-shared` and `node_modules/habitrpg-shared`, then I symlinked the habitrpg-shared repo that I cloned in all those places.

When I start grunt, I get this error: http://sprunge.us/UcCi?console
Not sure what to fix here. any idea ?

**Comment by paglias** [comment]
@Fandekasp could you give another link for the screenshot because the one above doesn't work for me

**Comment by AdrienLemaire** [comment]
oops a bad backslash got added in the url. fixed : http://sprunge.us/UcCi?console

**Comment by paglias** [comment]
Have you run npm install in both habitrpg & especially in the symlinked
habitrpg-shared?

**Comment by AdrienLemaire** [comment]
No I didn't in the habitrpg-shared ! makes sense now, will try it soon

EDIT: omg that was a stupid one.... fixed ! thanks @paglias

**Comment by paglias** [comment]
Then I think it's that because it wasn't installed as a submodule of
habitrpg but only linked. Also next time you run npm install on habitrpg of
there's a newer version of habitrpg-shared it will probably override the
symlink or even the content of the symlink with the updated version from
gitub
Il 18/nov/2013 23:33 "Adrien Lemaire" notifications@github.com ha scritto:

**Comment by AdrienLemaire** [comment]
@paglias hmm do you have a better idea to avoid that problem then ? I'll update my git notes on the wikia with those informations afterwards

**Comment by paglias** [comment]
Which problem? For the symlinks if you remember to check they are still
there after every npm install, which doesn't have to be done so often, then
you'll be fine. And don't symlink folders into /build because its files are
generated by grunt only in production mode from files in
public/bower_components/habitrpg-shared
Il 18/nov/2013 23:40 "Adrien Lemaire" notifications@github.com ha scritto:

**Comment by AdrienLemaire** [comment]
ok got it, thanks for your help

**Comment by AdrienLemaire** [comment]
@lefnire I'm sorry, but the issue you raised existed before. If you go hide your helmet, then change sex, the helmet is shown again.

I spent 1~2 hours trying to figure out why all gears show up again when changing the sex, and couldn't figure it out unfortunately. Too busy, can't keep digging into it today.

I'd suggest to merge that branch and create a new one to fix the bug that hasn't been introduced by my changes

**Comment by lefnire** [comment]
Ah, sorry for the wild goose chase! Didn't realize. Will merge and push soon

**Pull request merged**
