### PR TITLE
Interactive Tour

### PR DESCRIPTION
**Pull request by lefnire**
Refactor the Justin Guide to be more streamlined and interactive: 
1. Much less verbiage (we found from user tests that users were burning out)
2. Interaction. Requires actions at particular steps (eg, you can't move on until you've checked off the "join habitrpg" todo)
3. Backdrop focuses the user on the task at hand
4. "Chapterized" tutorials so you can run them concurrently. Not very obvious in current implementation (just using `intro` and `classes`), but will be adding more steps on various pages upon first access (see [internal card](https://trello.com/c/T6eBsfxZ/278-onboarding-next-steps))

(also, disables ads until lvl 2 because they make the tour super ugly)

tour

### CODE REVIEW

**Comment by lefnire** [comment]
We also want to improve the highlighting to indicate multiple divs at once, which bootstrap-tour doesn't support out of the box. Eg, when we hit "buy a reward", it would be nice to highlight their GP (in additiont to the rewards column), but I can't find an easy way. https://gist.github.com/lefnire/ef3715637cca26ea0930 shows my attempt, but it causes some really weird HTML results

**Comment by lemoness** [comment]
It says Training Sword costs 0 gold, instead of 1 gold?

Otherwise, looks awesome!

**Comment by Alys** [comment]
The Training Sword is the free sword given to all new players. It costs 0 gold to bvy it back if it is lost.

**Comment by crookedneighbor** [comment]
Lefnire changed it. It is now 1gp to buy (to illustrate the rewards system in the tour). The gif is just outdated, I tried it out on my local install and it was 1gp.

**Comment by lemoness** [comment]
Yes, we changed the price so users could have something to buy by the end
of the tour :)

**Comment by Alys** [comment]
Okay, thats clever! It will also simplify the death code since we will no
longer need to make an exception to the cannot-lose-free-items rvle.

**Comment by lemoness** [comment]
Ooh, good catch :)

**Pull request merged**
