### PR TITLE
Mocha 3 and Coverage

### PR DESCRIPTION
**Pull request by paglias**
This PR is based mostly on https://github.com/HabitRPG/habitica/pull/8487/files by @FedyuninV

### CODE REVIEW

**Comment by TheHollidayInn** [comment]
Looks good to me. I'll test locally. Where do the unit test coverage reports get placed locally?

**Comment by paglias** [comment]
@TheHollidayInn in theory in coverage/ but I'm not sure it works correctly locally. Let me know if you have any idea on how to fix it

**Comment by paglias** [comment]
And according to https://coveralls.io/builds/10791930 it has coverage data only for the new and old client. So maybe it's not working on travis either for the other tests

**Comment by paglias** [comment]
Tests are now passing except for the api-v3 ones that fail with this error
schermata 2017-03-28 alle 12 50 12

**Pull request merged**
