### PR TITLE
German Locale

### PR DESCRIPTION
**Pull request by JesperDramsch**
Translated Habit to German. Integrated in i18n

### CODE REVIEW

**Comment by lefnire** [comment]
@JesperDramsch  I'm getting merge conflicts, but can't verify which one to choose as I don't understand de. can you do a re-checkout of HabitRPG/translations and see if your updates still apply?

**Comment by Pandoro** [comment]
I think it is safe to say merge whatever the new commit holds. I looked at the stuff in the habit master branch and parts were wrong that have been fixed in the new commit.

**Comment by JesperDramsch** [comment]
I'll take a look at it.

**Comment by lefnire** [comment]
Also, double check against `develop` instead of `master` - master is really outdated on the translations (we can't pull them in yet for technical reasons)

**Comment by AdrienLemaire** [comment]
@JesperDramsch  can you do a new pull request on the develop branch ? I suggest you use the git stash method (cf [git tips](http://habitrpg.wikia.com/wiki/Guidance_for_Contributors#Git) ), then create a new feature branch from the develop branch and pull request again.

Thanks !

**Comment by JesperDramsch** [comment]
I'm trying to get the repos up to date at the moment. I'm not really experienced with big projects, so please bear with me...

**Comment by JesperDramsch** [comment]
Updated the [translations] branch. Guess this one can be discarded.

**Pull request closed without merging**
