### PR TITLE
Added invite to friends in header, added setting to hide the invite friends, and localized the invite friends string

### LINKED ISSUE #5044: Way to Invite Friends from the Tasks Page
It would be nice to have a way to invite friends from the tasks page, to make it more obvious to new users that this is something they can do. 

For solo parties, could we add a "+" or something similar to the space where a party member would be that, when clicked,pops up the "Invite a Friend" modal?

We'd also need something under Settings that would let you turn it off or hide it, for people in solo parties who didn't like it.

### PR DESCRIPTION
**Pull request by TheHollidayInn**
Fixes https://github.com/HabitRPG/habitrpg/issues/5044 . 

screen shot 2015-04-29 at 6 10 20 pm
screen shot 2015-04-29 at 6 11 59 pm
screen shot 2015-04-30 at 6 01 52 pm

### CODE REVIEW

**Comment by hairlessbear** [comment]
What does it look like if you're in a party?

**Comment by TheHollidayInn** [comment]
Well, you have to be in a party of one for it to show. You won't see the button at all if you have more than one person. That was the requirement of the issue.

**Comment by hairlessbear** [comment]
Ah, I misunderstood the requirements. I thought it was asking for two things: a button like what you added, and some other function that all users would see. But if that's not what was asked for, that's perfectly fine too. Carry on :)

**Comment by hairlessbear** [comment]
Wait, does it show if you're not in a party at all, not even a single-person party? If it doesn't, I think it should.

**Comment by TheHollidayInn** [comment]
No, I was suggesting we add some sort of start a party button.

The current functionality is as follows:
If in a party with one member and setting to show is true: show
else: hide

**Comment by hairlessbear** [comment]
A start a party button is a really good idea.

**Comment by lemoness** [comment]
I also love the idea of a start party button. Maybe that button could serve
as both, with the text "Play with Friends."

So, if you weren't in a party, clicking that would automatically enroll you
in a party and bring up the Invite Friends modal; if you were in a party of
one, it would just bring up the modal.

Also, pinging @sugarfiend and @redphoenix for feedback on design. I'm not
sure how I feel about its current positioning.

**Comment by crookedneighbor** [comment]
I agree that if you're not in a party yet, it should be a "start a party" button.

If in a party, it should convert to an "add someone to your party" button. 

I also liked @lemoness's idea to have it occupy the place where your future party member will reside. @lemoness, did you ever work up some pixel art for that? I liked your shadowy figure idea with a super-imposed plus sign. Maybe a tooltip or popover could explain what it was more explicitly. 

^ That idea could work for both options. The popover would just change depending on the context.

**Comment by TheHollidayInn** [comment]
Sounds good. I like the idea. Should we use @crookedneighbor wording or @lemoness 's ? Also, should I wait for the pixel art or a decision on the placement of the button?

**Comment by lemoness** [comment]
I wasn't satisfied with my shadowy pixel art, and thought it would probably
look more clean if it were just a nicely designed "+" or something in the
middle.

**Comment by TheHollidayInn** [comment]
And the message would be under the plus sign?

**Comment by crookedneighbor** [comment]
I think the plus sign is enough to suggest that something will happen if you click on it. We can have a popover with some text when you hover over it.

**Comment by lemoness** [comment]
Yes, I think a popover is the way to go!

**Comment by TheHollidayInn** [comment]
Okay, how does this look?

screen shot 2015-05-11 at 8 17 10 pm
screen shot 2015-05-11 at 8 16 22 pm

**Comment by crookedneighbor** [comment]
Personally, I think it could use some pixel artist love.

**Comment by TheHollidayInn** [comment]
I'm happy to include any art from them :)

**Comment by paglias** [comment]
I would go with a box that occupies the whole height and a plus inside it,
grey maybe so it doesn't distract from the most important parts of the
header.

I'll draw something in a few hours
Il 12/mag/2015 16:14, "Keith Holliday" notifications@github.com ha
scritto:

**Comment by SabreCat** [comment]
Agreed with @paglias - the little + cube floating in space looks a bit lonely.

**Comment by paglias** [comment]
My design skills are as bad as you can imagine so I didn't even try to come up with a real design, but my idea was somethiing like this with an explanatory popup on hover:

selezione_017

**Comment by crookedneighbor** [comment]
That is roughly what I have imagined too.

**Comment by lemoness** [comment]
I like that image, too! Will try a rough mockup.

**Comment by lemoness** [comment]
A bunch of rough mockups. Any thoughts on which direction to go, if any?

plus draft5
plus draft4
plus draft3
plus draft2
plus draft1

**Comment by lemoness** [comment]
At the 3x size that they would be displayed:
plus draft5
plus draft4
plus draft3
plus draft2
plus draft1

**Comment by deilann** [comment]
What if we think about it in another direction? Like not adding party
members, but inviting them? So maybe a full party member size door that is
slightly ajar. I think that might fit the site aesthetic better, be more
fun, and possibly get more interested clicks. I also like the idea that the
image could then be different before you have a party. maybe a closed door
with a key in the keyhole. I really do feel that making it full size is a
lot more likely to make it look better. also none of the plus signs feel
like add a party member mostly because we use that sign to mean other
things  already on habit.

**Comment by crookedneighbor** [comment]
I really like the door idea.

**Comment by lemoness** [comment]
Ooh, a door could be cool! We might want to test the image to see which one
people click on.

**Comment by lemoness** [comment]
Pinging also @veeeeeee and @anitaycheng for feedback.

**Comment by veeeeeee** [comment]
@deilann has some good points. I think it's worth testing to see which converts better, especially with less tech-savvy individuals (who are probably not numbered among present company).

**Comment by AnitaYCheng** [comment]
How about a door with a plus sign on it? :wink: I really do like @deilann's idea of a door, but it may fly over people's heads. "Add people to a group" with a plus sign is more standard tech parlance than "Inviting people" using a door icon.

**Comment by lemoness** [comment]
Gonna work on a couple of quick mockups! When we have a two favorites, we
can start testing.

**Comment by lemoness** [comment]
I've decided that I really hate mockups. If any designer wants to come leaping in and try their hand at this, please please do. I'm just kinda throwing rough, non-symmetrical stuff at the wall to see if anything sticks.

plus draft7b
plus draft7a
plus draft6d
plus draft6c
plus draft6b
plus draft6a

At this point, I'm willing to go back to the "Invite Friends" message from the very top :( I think this will be an important feature, and I'm worried about delaying it forever because I am not a designer.

**Comment by lemoness** [comment]
Also, something to note - I've been running user tests, and people frequently don't even know to click on their own avatar. I'm worried that we might be getting less obvious... although that's something that testing will reveal.

**Comment by AnitaYCheng** [comment]
Clicking on one's own avatar isn't necessary to get stuff done - it's a shortcut instead of using the navigation. I wouldn't worry too much about that interaction specifically. :)

My impression is that the avatars look so artistic and un-button-like, that people may not realize that they're clickable. Perhaps the "Invite Friends" area should look like a button within the space, because that interaction does affect gameplay.

**Comment by TheHollidayInn** [comment]
I really like your designs @lemoness , although, I do share your concern.

**Comment by lemoness** [comment]
Are there particular design that people like best that we could test
against the invite friends button?

**Comment by hairlessbear** [comment]
I really don't think any version of a closed door works because a closed door indicates that something is unavailable. If I was a new user, I'd assume a closed door meant something would appear there after I unlocked it (or I'd find a key or something), and I doubt I'd click on it except out of idle curiosity. Not only that, it could signal that a user is missing out on something fun, and if they don't want to be in a party, that reminder will always be in their header, which isn't good.

Actually, I can't think of any version of a door that presents the right message. If it's partly or completely open, it would still be unclear what it's for (e.g., Am I entering a room?). 

I like the fourth from the bottom and the bottom two the most. They may not perfectly indicate that they mean "invite friends", but they're the closest of the bunch, and I think worth testing. They definitely indicate that a user should interact with them, which puts them above the doors, in my opinion.

**Comment by veeeeeee** [comment]
Seconding @hairlessbear's comments.

**Comment by lemoness** [comment]
Since we're still ironing out our testing process, I'd propose starting with the "Invite Friends" button, and then once we can test the difference, rolling out this one (https://cloud.githubusercontent.com/assets/3494081/7766196/9c45be94-001b-11e5-8d51-7cbdb18ee698.png) as the first alternate option, and then cycling through the others until we find the one that people like the most. That way we're not still holding up this feature in limbo. Sound good?

**Comment by hairlessbear** [comment]
@lemoness Are you going to test all of the options that you proposed (the various pluses and the second set of icons/doors), or a smaller subset? Just curious.

**Comment by lemoness** [comment]
A smaller subset, I hope!

**Comment by TheHollidayInn** [comment]
Okay, I changed the button back to have the Invite Friends text.
screen shot 2015-06-01 at 9 10 19 pm

**Comment by lemoness** [comment]
It looks good, although it seems a bit stranded right now, floating in the center. I've mocked up two alternate positions:

invite friends1b
invite friends1a

I prefer the first, but would be happy to hear other opinions!

**Comment by deilann** [comment]
@lemoness First image is broken.

**Comment by lemoness** [comment]
Sorry, it posted the pictures in reverse. I prefer the second ("1a"), where it is under the Subscribe button.

**Comment by lemoness** [comment]
Hm, it's displaying for me on Github. Posting again:
invite friends1b
invite friends1a

**Comment by deilann** [comment]
It's probably cached for you. I still can't see the "1b" and if I click on it, I get a broken link.

**Comment by lemoness** [comment]
invite friends1b copy

How's this?

**Comment by deilann** [comment]
Now it's good!

I also prefer the other one.

**Comment by lemoness** [comment]
Vicky has a slight preference for the one next to the stat bars.

**Comment by deilann** [comment]
What if we had a peeking up Ian with a text bubble that said "start a
party"?

**Comment by lemoness** [comment]
I think that would be another fun option to test, but I'd like to start
with this one so that we can get things out there!

**Comment by TheHollidayInn** [comment]
I was just aligning the button with the party section. The button is horizontally aligned with the character rather than aligned with other UI elements. Either way, just let me know where to put it.

**Comment by lemoness** [comment]
Let's start with it under the Submit button. We can always test the
position as well!

**Comment by crookedneighbor** [comment]
@lemoness did you mean the subscribe button?

**Comment by lemoness** [comment]
I did mean the Subscribe button. My apologies.

**Comment by veeeeeee** [comment]
I think that was the flower version of @lemoness talking earlier re: submit ;)

**Comment by TheHollidayInn** [comment]
Updated!

**Comment by lemoness** [comment]
Can we see a final screenshot?

**Comment by TheHollidayInn** [comment]
Of course.

screen shot 2015-06-03 at 11 37 07 pm

**Comment by crookedneighbor** [comment]
Made some final adjustments: https://github.com/HabitRPG/habitrpg/commit/7a1c5835d0050b79116243af9c4b66691a971d6f

Notated toward your next tier.

**Comment by TheHollidayInn** [comment]
Thanks. I need to read about this sinon function. I have no idea how to use it.

**Comment by crookedneighbor** [comment]
http://sinonjs.org/docs/

Going to be refactoring soon to use http://sinonjs.org/docs/#sandbox

**Pull request merged**
