### PR TITLE
Bindonce implementation

### PR DESCRIPTION
**Pull request by snicker**
The site definitely seems snappier... I recommend leaving this one on beta for a while and see if anyone has any issues. Mobile chat improved quite a lot with just this addition.

### CODE REVIEW

**Comment by lefnire** [comment]
This is absolutely fantastic. I've been looking for something like this for a very long time, Derby had static variable injections (aka, bindonce) as `{{{variable}}}` and dynamic listeners as `{{variable}}`. When I went Angular, that was one of the things I missed the most, for performance reasons. I didn't think to look for a 3rd party directive, and I'm glad you've captured a lot of other places this will work against. Deploying to beta in a bit, let's give 'er a whirl

**Comment by snicker** [comment]
woot

**Comment by lefnire** [comment]
@snicker I know there's been a lot of flux on the bindonce front. Tell me if you think things are stable at any point and that I should merge to master (production), I'll hold off till then

**Comment by snicker** [comment]
If the latest commits from this morning are on Beta, I think that's okay for now... probably should leave them there for a bit in case there are any edge cases

**Comment by lefnire** [comment]
Sounds good. Yeah, beta is deployed from develop#HEAD as of 5m ago

**Comment by lefnire** [comment]
@snicker heads up, we're on prod now. Things seem to be running well on beta now (and have some other hotfixes & wanna deploy)

**Pull request merged**
