### PR TITLE
WIP for refactoring base achievements #11541

### PR DESCRIPTION
**Pull request by moniwang**
[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: #11541 
WIP for #11541 

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
The reason for the changes made here were getting rid of some base achievements in order to create a simplification of these achievements both on the client side and server side.

In refactoring these achievements, there are some extra dependencies that I could not find that resulted in the failure of some of the functionality. This resulted in the need to include lines 37-38 back into the file habitica > website > server > models > userNotifications.js

I need assistance for finding this dependency.

[//]: # 43f0b0bd-c910-4453-bd41-d8f38a7adc59

----
UUID:

### CODE REVIEW

**Comment by paglias** [comment]
thanks @moniwang ! This is partially related to https://github.com/HabitRPG/habitica/pulls that should be merged this or next week so I'll give a look at this one after that is one

**Comment by paglias** [comment]
As expected this resulted in some conflicts after https://github.com/HabitRPG/habitica/pull/11536 got merged https://github.com/HabitRPG/habitica/pull/11536, in particular I added a new way to add achievements, see https://github.com/HabitRPG/habitica/pull/11536/files#diff-185b25f0cc4f353ec1071bca388d362fR239

As this change will take some more time and more changes I'd like to take over the PR @moniwang if you don't mind. Of course it'll be noted as a contribution of yours

**Comment by moniwang** [comment]
Ok! Should I close the PR?

**Comment by paglias** [comment]
Hi @moniwang  , sorry for the delay but I'm still catching up from the end of year holidays, I hope to get to this PR in the next couple of days, in the meantime let's leave this open

**Comment by paglias** [comment]
Hi @moniwang there's some good stuff in this PR that I'll use in my refactoring so I'm going to keep this open

**Comment by SabreCat** [comment]
With paglias no longer available to help, it's looking likely this will need to be rewritten, given the age of the PR. Closing with our apologies!

**Pull request closed without merging**
