### PR TITLE
@lefnire => i18n support... aka Translations!

### PR DESCRIPTION
**Pull request by switz**
Bet you weren't expecting this one. Turns out it's super easy to add translations thanks to the `derby-i18n` module.

I'm going to write up a wiki on how to add translations.

### CODE REVIEW

**Comment by switz** [comment]
https://github.com/lefnire/habitrpg/wiki/Translations

**Comment by switz** [comment]
https://github.com/lefnire/habitrpg/issues/62

**Comment by lefnire** [comment]
Epic PR! Can't wait to get back and merge

**Comment by lefnire** [comment]
i'm gonna hit this in a few, but real quick - have you tested it on local a bit? IIRC derby-i18n adds language routes (eg /en, /he) which _might_ conflict with some bootstrap components (modals, tabs)

**Comment by switz** [comment]
Yes. I haven't messed with any actual implementation yet, i.e. the only way it works on the site is if you set `defaultLocale`. But this will enable us to start building out a list of terms that we need translated. While that's being done, we can work on fine-tuning the implementation within Habit. For now, it just defaults to `en`.

**Comment by switz** [comment]
Just to be clear, if you set `he` as the `defaultLocale`, it will display the appropriate values. aka, it works!

**Comment by lefnire** [comment]
awesome, tested on local to be sure - I forgot, it's actually registration routes that were hitting me last time I tried derby-i18n (/register /login /logout etc), but looks like they work just fine on your branch. Merging

**Pull request merged**
