### PR TITLE
Fixed grammatical errors in Tech Info section of DOCS-README

### PR DESCRIPTION
**Pull request by cjnething**
There were some grammatical errors in the Tech Info section that I changed:
- "Wide range" is not a hyphenated phrase, so I took out the hyphen
- "File types" are two separate words, so I added a space between them
- The "including being able to generate documentation" is not the correct sentence structure (does not match with the structure of the first half of the sentence), so I modified that structure

### CODE REVIEW

**Comment by crookedneighbor** [comment]
I don't think this file is actually used and should probably be deleted from the repo. @Alys, thoughts?

**Comment by Alys** [comment]
@crookedneighbor I was thinking the same but waiting for you to comment. :)

**Comment by crookedneighbor** [comment]
@cjnething I've deleted the file and I'm going to close this pull request, but please do feel free to peruse the issue queue and submit another PR!

**Comment by cjnething** [comment]
@crookedneighbor Sorry about that! I'm new to open source contributions, trying to get my feet wet :)

**Comment by crookedneighbor** [comment]
No worries. I wasn't even aware that this file existed. :wink:

**Pull request closed without merging**
