### PR TITLE
Fix markdown in client README file

### PR DESCRIPTION
**Pull request by ccmaris**
The README.md file in the website/client/ directory had a flaw.

[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
Just fixed the '#' markdown in the README.md file in the website/client/ folder. All it need was a couple of spaces.

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 438c3270-6269-461f-b59e-53f2ce0a61f4

### CODE REVIEW

**Comment by Alys** [comment]
@ChristosMr Thank you for finding this problem!

I'd actually really like it if the README didn't replicate content available on the wiki but instead directed users to read the wiki page. That will give them significantly more information (e.g., what to do if problems occur, what things to watch out for, where to request help). The wiki is updated more frequently than our READMEs so is a better resource.

If none of the staff object (wait a couple of days for their feedback), can you please replace the whole content of the "Running" section with text like this:
```
For information about installing Habitica locally, see
[Setting up Habitica Locally](http://habitica.wikia.com/wiki/Setting_up_Habitica_Locally)
and for information about running the local client, refer to the
["Run Habitica" section](http://habitica.wikia.com/wiki/Setting_up_Habitica_Locally#Run_Habitica)
in that page.
```

Also, at the bottom of the "Preparation Reading" section, please add text like this:
```
For further resources, see
[Guidance for Blacksmiths](http://habitica.wikia.com/wiki/Guidance_for_Blacksmiths),
in particular the
["Website Technology Stack" section](http://habitica.wikia.com/wiki/Guidance_for_Blacksmiths#Website_Technology_Stack).
```

Line breaks have been inserted just for readability here; they're not needed in the README.

**Comment by ccmaris** [comment]
@Alys 

I am guessing that you would want me to squash the commits as well right?

I will have that done by the evening.

**Comment by Alys** [comment]
Don't bother to squash commits - github lets us do that when we merge and it's best done then because sometimes it can be easier to review a PR commit by commit. Thanks for offering though!

**Comment by ccmaris** [comment]
I already did xD

But it wasn't anything special about those two commits I squashed, they both applied changes to the same file, just different changes.

**Comment by paglias** [comment]
@ChristosMr  thanks for this! I'm merging the PR and awarding your contributor tier.

Note that further tiers require increasing amounts of work from one to the next, so Tier 2 may require a couple of PRs or a larger PR to attain. But keep helping out and we'll express our gratitude accordingly!

**Comment by ccmaris** [comment]
@paglias Thanks a lot!

I'll be sure to keep engaging.

**Pull request merged**
