### PR TITLE
Fix alignment of buttons

### PR DESCRIPTION
**Pull request by TheSisb**
Simple fix. Currently it looks like this http://puu.sh/7f0c9.png

### CODE REVIEW

**Comment by paglias** [comment]
@TheSisb thanks! but we would like to avoid inline styles, can you move them to the css?

**Comment by TheSisb** [comment]
Updated.  Wasn't sure which CSS file would be most proper as there isn't a layout.styl so I put it near the previous .btn styling edit found in index.styl

**Comment by paglias** [comment]
@TheSisb index.styl is fine, thanks. Merged. If you post your UUID I'll give you the contributor badge

**Comment by TheSisb** [comment]
UUID: 8de4e11a-9423-416f-a1ba-ca4c6f18a8ea
Thanks :)

**Comment by paglias** [comment]
Sorry, that is the username, you can find the id here https://habitrpg.com/#/options/settings/api

**Comment by TheSisb** [comment]
My mistake.  Edited my post.
8de4e11a-9423-416f-a1ba-ca4c6f18a8ea

Also is there a TODO for styling fixes / changes somewhere?  [edit] found it.

**Comment by paglias** [comment]
Contributor badge :+1:

**Pull request merged**
