### PR TITLE
Correct add task icon alignment

### LINKED ISSUE #5148: Add Task plus not vertically centered
On Chrome, the plus sign for adding a new task to one of the four main columns is not vertically aligned in its button. It's substantially higher than center:

image

Note that the screenshot above also features the "cross" look from #4539, which may or may not be related. 
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/13110983-add-task-plus-not-vertically-centered?utm_campaign=plugin&utm_content=tracker%2F68393&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F68393&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by excentris**
Fixes #5148

### CODE REVIEW

**Comment by hairlessbear** [comment]
Can you include screenshots? They're needed for any PR with a visible change.

Also, if you're removing this from the .styl file, you should also remove it wherever it's used. No reason to keep a call to a class that doesn't exist.

**Comment by excentris** [comment]
@hairlessbear You're right. Right now I'm at work, but will take care of this when I'm home.

**Comment by excentris** [comment]
@hairlessbear removing the class on the lists.jade makes some tests fail, as far as I could see. I'm not exactly sure how to proceed...

**Comment by excentris** [comment]
The screenshot:
align-add-task

**Comment by crookedneighbor** [comment]
@excentris What test failed?

**Comment by excentris** [comment]
@crookedneighbor Well, actually I think it's the build that failed. A couple of comments above I made a commit ('Removed unused class') and it seems the build failed. I am not sure if it was due to my change though... :(

**Comment by deilann** [comment]
If you click on that notif, you can see where it failed and by looking at
that, determine whether or not it is related to your PR.

**Comment by excentris** [comment]
@deilann If I click through at the end I see "npm ERR! Test failed..." so I would say it is not related to my fix. Should I recommit my fix then? (sorry about the extra work such a small fix is costing you guys...)

**Comment by deilann** [comment]
Check out line 1582.

**Comment by deilann** [comment]
The fact that reverting that commit causes the build to pass makes me believe that it's related, although I don't have time to research why right now.

**Comment by hairlessbear** [comment]
You can test on your machine by running `npm test`, which will let you know before you commit if things aren't working properly.

**Comment by excentris** [comment]
@deilann @crookedneighbor The fact that the class applied to that div is "empty-task-notification" (for a button that adds a task...) seems suspicious to me too.

**Comment by excentris** [comment]
@hairlessbear thanks for the tip! I'll add that to the wiki.

**Comment by crookedneighbor** [comment]
That div was created to generate a tooltip when a user tries to press the plus button when no task information has been supplied. It's also what is causing the plus button to get pushed around. 

The tooltip should appear when hovering over the button, and only if the input is empty. It seems to not be behaving correctly :frowning: . It was flaky before, but without that styling, it's extra flaky.

I don't want to merge this in until the tooltip is working correctly.

**Comment by excentris** [comment]
@crookedneighbor I'll see what I can do!

**Comment by excentris** [comment]
I am unfortunately very busy at the moment and will not be able to fix this issue right now. I am closing this pull request, since it is not a complete fix to avoid polluting the open pull requests.

**Pull request closed without merging**
