### PR TITLE
Reposition Markdown formatting link

### PR DESCRIPTION
**Pull request by bobbyroberts99**
There's probably a better way to do this. Feedback appreciated.

UPDATE: Ignore 7fdda14. Use db7e582 instead.

### CODE REVIEW

**Comment by lefnire** [comment]
Wanna be careful of using z-index. Unless you're actually intending to add layers (aka, armor goes over avatar, shield goes over armor, etc) - then it's often a yellow flag. Mayhap [Bootstrap layouts](http://getbootstrap.com/2.3.2/scaffolding.html#fluidGridSystem) may come in handy instead? Whatcha trying to achieve here incidentally, got some before/after screens?

**Comment by bobbyroberts99** [comment]
Thanks for the bootstrap link. Not sure how to use that for this small tweak. Is inline css ok or would it be better to add to docs.css (or some other file)? I'll pull another commit with no z-index.

**After #1 --works better and doesn't need z-index**
after2

**After #2** (In this position, hover doesn't work very well.
before-tavern

**Before**
after-tavern

**Comment by SabreCat** [comment]
Ooh. :+1: I noticed when I made my changes that the Tavern link didn't act like the ones in the other chat pages, but couldn't immediately figure out how to fix it. I like Option 1, but can we get rid of the underline? (or were you moused over it when you took the screenshot?)

**Comment by bobbyroberts99** [comment]
I must have been moused over when i took the screenshot. Here's option 1 with no mo and equal space between the chat box and the alert. 

Right now the css is inline. I'm gonna play with adding a class to docs.css. Any opinions about that? UPDATE: Scratch that unless someone tells me that's how it's gotta be. Doesn't really make sense to add one-off classes for this.

name001

**Pull request merged**
