### PR TITLE
[Docs Project] Initial Progress Made on Commenting .js Files

### PR DESCRIPTION
**Pull request by AndreCaseyScott**
- Adds generated files for all source files in their current state of commenting
- Initial progress made on models/user.js
- changed default css styling of docs

### CODE REVIEW

**Comment by paglias** [comment]
Cool!

Just two small things:
- I would not check the documentation into git, devs can manually build it if needed and an hosted version can be kept online
- Since we're using Grunt, it would be easier to use a grunt plugin for that http://gruntjs.com/plugins/docco

And we could also give a look to something more than commented source like an api documentation with something like [YUIDoc](http://yui.github.io/yuidoc/)

**Comment by AndreCaseyScott** [comment]
Thanks @paglias! 

Putting the documentation in git seemed OK, because then once you install Habit, you could navigate to the subdirectory to view the docs. A little clunky, I admit. I'll remove them from the branch.

My thoughts have been towards using grunt all along (see #1557), but I don't know how to use grunt at the moment, and didn't want to try and grok a new tech when I really needed to dig in and document.

That said, the ultimate workflow would have grunt auto-build the documentation and push it to a folder/server that could be linked under habitrpg.com, the wiki, or something. I've heard a lot of people mention that the more people have to manually be involved with maintaining docs, the easier it is for them to become out of date. Using the comments is perfect, because in theory the dev would comment as they go or as a cleanup step in their workflow. Either way, once it's in the code, no one should have to think about adding to the docs, it should just show up there. 

How to do that though, is beyond me at this point... I'm still just trying wrap my head around javascript to be able to contribute to Habit is a more useful way.

As to to YUIDoc, I've heard good things. Maybe [Groc](http://tech.gilt.com/post/57089759513/rock-your-doc-with-groc-our-favorite-automated) is the best of both worlds? Allows for Markdown formatting and supports javadoc syntax for listing params and things. Also works on CSS, coffeescript, and anything Docco can parse. Plus the layout of resulting docs seems nicer. Thoughts?

**Comment by paglias** [comment]
I think that the best option is to use a grunt task that is run automatically when building for production and that create the docs in a subfolder (ignore in git) of /public os that they are reachable on the website (everything put in /public can be browsed from habitrpg.com). 

If you have any problem setting up a grunt task using a plugin found here http://gruntjs.com/plugins/docco then let me know and I'll give an help. You just need to put the package in package.json and reference it in Gruntfile.js as it's done for the other plugins.

Groc seems quite cool but probably I was wrong with suggesting YuiDoc because it's probably more useful for projects with a public api (something like a library with methods that can be called from another script) not for somwthign like HabitRPG. 

Habit's REST Api can't be documented with Docco & co I believe. It isn't a set of methods but of urls so we can keep using the wiki but I agree with you that it's easier to get docs outdated this way.

**Comment by AndreCaseyScott** [comment]
Oh awesome! I didn't realize everything under /public can be browsed. That will simplify things a lot!

I will mess around with grunt and see if I can get it working. 

Is the REST API stored in src/routes/api.js? If so, it absolutely can be documented with Docco/Groc! All either of them do is parse out the comments in the code. I'm leaning towards using Groc, since it seems more robust than Docco (including creating a table of contents), and would allow for javadoc syntax, if it proved helpful. Plus it supports block comments, which Docco doesn't.

**Comment by AndreCaseyScott** [comment]
An alternative for the API if Groc/Docco doesn't work is [Apiary.io](http://http://apiary.io/). It might be worth a look anyways, as it also has test and things. Free for hackers, and integrates with GitHub. #overmyhead @lefnire @paglias

**Comment by paglias** [comment]
Today or tomorrow I'll try to set up Groc on this branch so we can really
start this!

**Comment by AndreCaseyScott** [comment]
After a lot of playing, tweaking, hacking, and searching, I've decided to use Docker as the generator. It still uses docco, and supports javadoc should we need it.

I got it working with grunt pretty easily. Currently attached to build:dev as it was easiest for me to understand at the moment. I agree that having it on prod is best.

Reasons for going with Docker are primarily the layout of the generated HTML. The tree and index is clearer, and markdown files with no code display full width, opening up the possibility of combining all the documentation in one place.

I will rewrite the readme for this tomorrow (currently is docs-home.md)

**Comment by paglias** [comment]
I am merging it into docs-project branch so we can continue working there instead of using pull requests. I'll post on this issue to discuss about it

**Comment by paglias** [comment]
mmm.... #1569 reverted some code to an older version so we may have to revert some changes in develop and since this repo has newer commits it's probably going to cause some problems when merging back into develop. I'm deleting this branch, then @onduhray when everything is back to normal you'll have to update your fork and re-apply all the changes you made and then reopen a pull request or recreate this branch beacuse otherwise I believe we'll mess up everything.

**Comment by AndreCaseyScott** [comment]
ahhhh crap. I seriously don't know how that happened, according to the repo timeline. :/

When I reverted changes, I only reverted the ones I committed. I'm still getting used to git, and when I pushed some code directly to the docs-project branch, it also merged some code from my forked develop directly into lefnire/develop. Strange thing is that when I reverted, it didn't revert the user.js file I was working on in my local develop. Sorry man. :(

I might stick to pull requests myself for now. I'll merge them in right away, but I don't want to chance messing up develop again.

**Comment by AndreCaseyScott** [comment]
@paglias if we reverted my revert, would that catch the code back up? Sucky for the history, but at least it would fix things. When I look closer at the commits in that merge, it seems like that would work.

**Comment by paglias** [comment]
No problem! I think that if we revert to the latest commit by Tyler we'll be ok

**Comment by AndreCaseyScott** [comment]
@paglias any chance you can successfully revert this? I've been trying for at least an hour and I can't seem to grasp what I need to do revert this...

I've checked out a new copy of develop, try to revert to commit `bf7ad9cb4154a5a17c466851dd461cf04fb326ed` in sourcetree and says I need -m command. (This was the last commit by Tyler) Then I try to revert via terminal `git revert -m 1 bf7ad9cb4154a5a17c466851dd461cf04fb326ed` and it says I have nothing to commit. Tried reseting to that commit, and then it won't merge changes because it's behind the remote. I think I understand why `reset` and `rebase` are not appropriate for trying to fix the history, but I'm at a loss for how to `revert` correctly.

I seem to be misunderstanding some basic concepts around git. It should be much easier to revert changes in the history. I must be missing a step or something.

**Comment by AndreCaseyScott** [comment]
@paglias @lefnire does `revert` only revert changes on a single commit or merge? Thus, it acts as "undo" on any changes done on _that_ commit only? Do I need to revert each of my commits individually? Should I be reverting to a commit I want, or the one just before? is there a way to cleanup the history without pissing people off?

this is really embarrassing...

**Comment by paglias** [comment]
@onduhray not worry I think git is made for these things :) I just leave this to @lefnire because I'm not very good at git so I would like not to cause any other problem

**Comment by lefnire** [comment]
Hey guys, the repo is really borked right now. Many commits have gone haywire / lost, and heroku won't accept the code push. I'm going to be fixing this by hand right now, nobody make any change to #develop until I report back.

**Comment by lefnire** [comment]
Ok, I fixed the issues. @onduhray look at https://github.com/lefnire/habitrpg/compare/ab669ac3c5847b42177a8104476ed2b9950a1056...92485a938e30c4ba9f8d273d3eba6a5e423eaee0 (very closely!) and make sure all your commits are accounted for. Particularly I didn't cherry-pick https://github.com/lefnire/habitrpg/commit/2015749f9ac868d80d6ba79dbb8e1d5d4714acad , do you definitely want that revert committed, or was that a "oh shit" backpedalling commit?

So what I had to do was `git checkout` the last commit deployed to heroku, `git push --force` to remove all history on #develop since then. I then cherry-picked @onduhray's commits one-by-one (except the revert mentioned above) in order to exclude all the other-branch merges and merge-reverts. What happened was you merged develop into your branch, but then reverted the merge - meaning you reverted all commits that merge came with, and then committed that change-set. 

**What this means for everyone**: You will need to re-clone the repo, or at least delete #develop & re-checkout #develop.

Ok, so here are some tips for everyone so we can avoid this problem in the future:
- MOST IMPORTANTLY! don't `git merge develop` _onto a feature branch_. Use `git rebase develop`. Do this every time before pushing your commits. develop->feature = rebase, feature->develop = merge. Here's the difference. Git merge will pull all commits from develop and make history entries out of them. When you then git merge _back onto_ develop from your branch, those history entries are duplicated - so you have one or more duplicates of every merged commit - making it easy to accidentally act on those duplicates (as was the case here). Git rebase says "for all commits, do I need to worry about anything? (aka do I need to create a merge-conflict commit)? If not, don't do anything (fastforward). If so, only create a single conflict-resolution commit". This way commits aren't duplicated. It can get pretty weird, so if anyone needs any help with this hit me up, but do some reading on `git rebase` to get familiar, because it's _very_ important.
- when working on your own branch, if you want to combine or undo commits, use `git rebase -i` (squash, remove, etc - read up on it)
- If, on the other hand, you've pushed to develop/master and need to revert multiple commits, [use --no-commit](http://stackoverflow.com/questions/1463340/revert-multiple-git-commits) to squash reverts. 

I may follow up with some more rebase tips. We will probably need to go through any PRs against develop and make sure they don't carry along the removed change-set (eg, https://github.com/lefnire/habitrpg/pull/1572 needs to be reworked).

**Comment by AndreCaseyScott** [comment]
Thanks @lefnire. https://github.com/lefnire/habitrpg/commit/2015749f9ac868d80d6ba79dbb8e1d5d4714acad was definitely an "oh shit" backpedal. Though technically, none of the commits on https://github.com/lefnire/habitrpg/compare/ab669ac3c5847b42177a8104476ed2b9950a1056...92485a938e30c4ba9f8d273d3eba6a5e423eaee0 were supposed to make it to develop either. 

The real problem here was my configuration of SourceTree, the gui I've been using with Git. It (by default) selects all repos with matching names on local and remote to push. I didn't notice this when I pushed commits directly to the `docs project` branch, and it pushed all my local `develop` too. I was working on the docs stuff in my local `develop` branch you see. When I noticed this, I figured I would simply revert all the commits with my name attached, but I assume SourceTree chose to `merge` my local develop (probably with some of those duplicated commits) into remote develop. 

shitshitshit

This whole process definitely taught me some lessons:
1. Pay really close attention when pushing anything to remote. Like, really close attention. 
2. I should probably bite the bullet and learn git on the commandline. Accidents are too easy on SourceTree.
3. Study the correct use of `rebase` and `merge`

Thanks again @lefnire, for fixing my mistake and for giving such a detailed explanation on preventing this in the future. I am sorry this happened at all, and am grateful that it wasn't a complete loss. I hope to not repeat this mistake again.

**Comment by lefnire** [comment]
Cool beans man, no worries! and yeah, `rebase` v `merge` - clutch. Ok, do you want me to do anything with what's currently on develop now? Should I revert anything? All your commits are benign since it's all comments, so we're cool to roll with what's there - unless you actually were planning on taking a different direction and didn't want those commits there in first place? If so I can do a squashed multi-revert if you need

**Comment by AndreCaseyScott** [comment]
@lefnire I was hoping to keep develop clean for now. I'll do a pull request for any changes onto develop. Also, is it safe to delete the `docs-project` and `onduhray/develop` branches? Was going to recreate a clean branch off of latest develop and cherry pick my changes for the `docs-project`. Is `onduhray/develop` needed anymore?

**Comment by lefnire** [comment]
it'll be a pain for now to go through and pull everything out of develop again (I'd have to do another force-push). Since it's all comments and documentation let's just leave it in for now, and you can augment what's there on a separate branch. Sorry I should have checked with you how you wanted the repo structure before doing my `rebase -i`. Yes, you can delete both of those branches

**Comment by AndreCaseyScott** [comment]
Oh no worries. The main bugger I didn't want in there was the Docker config in grunt. If anything I'll just delete them manually and issue a pull request.

**Pull request merged**
