### PR TITLE
Initial Round of tests for creating, updating, and deleting todos

### PR DESCRIPTION
**Pull request by crookedneighbor**
Wrote the start of some tests for creating, updating and deleting todos.

Test related to task type require https://github.com/HabitRPG/habitrpg-shared/pull/438

### CODE REVIEW

**Comment by Alys** [comment]
@crookedneighbor Just checking if these are still relevant too. I suspect they are, but this comment will at least bump them up the list. :)

**Comment by crookedneighbor** [comment]
:+1:

**Comment by gisikw** [comment]
Ditto on this one. Tests are passing after a rebase :) This one rebased cleanly too, so it should be mergeable :)

**Comment by crookedneighbor** [comment]
I know it'd probably merge fine, but I'd be happier seeing the Travis build looking happy first.

**Comment by Alys** [comment]
closed by https://github.com/HabitRPG/habitrpg/pull/4931 thanks to @gisikw

**Pull request closed without merging**
