### PR TITLE
Missing Pet Icons, Resting Graphics

### PR DESCRIPTION
**Pull request by Shaners**
### Features
- 2 new missing pet pixely icons
- Resting Zzzs 
### Notes
- I've changed the pets.html to use one of the new missing pet icons
- There are 2 solutions for the missing pet icon feel free to play and pick the best one or revert back to what we currently are using
- In addition to the Zzz icon added to shop_sprites, I threw in some closed eyes art that'll require some CSS positioning to get in the correct place. Mostly just added this for playing with / testing since I thought it would be neat if the avatar had their eyes closed as well. Will only work with one skin colour type and if implemented the closed eyes would probably reside in a different sprite sheet.

### CODE REVIEW

**Comment by lefnire** [comment]
you speedy gonzalaz you. I'll start implementing this asap

**Comment by lefnire** [comment]
I love it! http://gyazo.com/3e7f8629ad15c04256f82fbe4cecab44 - I guess the closed eyes does pose extra work for all the skin types, what with the eyes being 2 pixels high instead of 1. Meh, we can roll with zzz's for now and keep this on our mindgrapes

**Comment by Shaners** [comment]
Since the closed eyes thing is such a small amount of pixels and we have a limited number of skin colours maybe could just be done with CSS. But yea don't really see it as a priority at all unless there is an uproar of people asking why their resting character is sleeping with their eyes open.

My mind grapes are really fresh this morning!

**Comment by StanLindsey** [comment]
Note - can we use this for people who haven't logged in in a while? Or some sort of AFK symbol to show people in your party haven't logged in in ages.

**Comment by Shaners** [comment]
Or a pile of bones if they haven't been around in a really long time!

**Comment by StanLindsey** [comment]
@Shaners - love it.

**Comment by lefnire** [comment]
would it be easy enough with css? can you think of something for that? I'm down to put it in

**Comment by Shaners** [comment]
@lefnire well probably easy enough for someone that knows CSS better than I... maybe an area and can learn and look into sometime.

**Pull request merged**
