### PR TITLE
Normalize theme audio volumes

### PR DESCRIPTION
**Pull request by bennyty**
I used a combination of mp3Gain and Vorbisgain to rebalance these audio files. I am confident that the .mp3 files sound more balanced across the board but am not confident that the .ogg files have been
modified correctly. Perhaps my audio player isn't compatible?

From the Vorbisgain website:

> It needs player support to work. Non-supporting players will play back the files without problems, but you'll miss out on the benefits. Nowadays most good players such as Winamp or Foobar2K or recent XMMS are already compatible. If your player isn't, consider upgrading to one that is.

### CODE REVIEW

**Comment by bennyty** [comment]
@SabreCat mentioned wanting to do this in issue #5924

**Comment by crookedneighbor** [comment]
If you include: 

fixes #5924

in a comment, or commit message, it will automatically close the issue if this PR gets merged in.

**Comment by bennyty** [comment]
@crookedneighbor Thank you! I already knew this but thought that this PR does not address that specific issue. @fragmental's issue dealt with adding volume control while this PR only normalizes the existing audio files.

**Comment by Alys** [comment]
For those of us not familiar with audio, what do rebalancing and normalising mean?

**Comment by SabreCat** [comment]
I like how this sounds from what I've tested thus far! Can somebody with a better ear than me try Watts' Theme on production vs. this PR, though? I feel like the tempo's faster on the normalized version, somehow.

**Comment by bennyty** [comment]
@Alys I would not call myself immensely "familiar" with audio but as I understand it what I have done is normalization not balancing (have updated the PR title).

Since I don't want to get this wrong this Wikipedia's definition:

> Audio normalization is the application of a constant amount of gain to an audio recording to bring the average or peak amplitude to a target level (the norm).

So since these audio files were (presumably) created by different people using different functions/sources, they are wildly different in volume(amplitude). The filter that I ran the audio through tries to make all the files the same reasonable volume.

**Comment by SabreCat** [comment]
Never mind my comment about the speed. I just used that theme a bit on production and it was as rapid as when using this PR. It'd been a while since I'd used that theme (I prefer LuneFox), so I guess I just remembered it being a different tempo than it actually was. :cat::sweat_drops:

**Comment by SabreCat** [comment]
@bennyty: Thanks much for this! It'll be live next time we deploy to the site. Your work will count toward a contributor tier! What's your Habitica User ID (from Settings > API)?

**Comment by bennyty** [comment]
Thanks! I'm glad you found it useful! UserID: 97d3419d-5277-4e1f-aac8-77a1ac1b30a5

**Comment by SabreCat** [comment]
@bennyty: Tier awarded, congratulations!

Note that contributor tiers require increasing amounts of effort from one to the next, so a PR of similar scope may not immediately bump you to Tier 2. But keep helping out and we'll express our thanks accordingly!

**Pull request merged**
