### PR TITLE
Single challenge view updated

### PR DESCRIPTION
**Pull request by gisikw**
- Manually pulled in changes from #3319  - add a "Singleton" challenge view.
- Locked v2 API /challenges/:cid behind user auth (allows `_isMember` on that response, and probably closes a security hole).
- Fix a minor issue where deleting a challenge from the singleton view wouldn't correctly transition back.
- Set the "list view" for challenges to transition to singleton view on edit (allows us to use the fix from #4814)
- Added in the fix from #4814.

This should satisfy both pull requests, and fixes the issues mentioned with the in-progress one :)

### CODE REVIEW

**Comment by gisikw** [comment]
Travis is having issues because rabbitmq is being intermittently non-responsive, so it can't get the build going. Feel free to kick the tests off again at your leisure.

**Comment by Alys** [comment]
Nice!

_"Locked v2 API /challenges/:cid behind user auth (allows _isMember on that response, and probably closes a security hole)."_
Can you give details about what effect this has? We wouldn't want the challenges to be locked down more tightly than they are on the website.

**Comment by gisikw** [comment]
Yep yep - so basically this endpoint wasn't locked behind user auth, which means you can actually hit it without passing in a UUID/key:

`curl https://habitrpg.com/api/v2/challenges/55103f6a-7fef-4f04-ba57-0b6695ac1ffb`

So, provided you happen to know a challenge's ID, you don't even have to have an account to get the info back. And since that endpoint didn't include the auth mixin, it wasn't looking up the current user. That meant that we couldn't tell if the user had already joined the challenge or not, and couldn't forward it in the response.

Per the [API docs](https://habitrpg.com/static/api),
_Every authenticated request should include two headers. Your api key (x-api-key) and your user id (x-api-user). Do not include {} braces in your header (-H 'x-api-user: a94b6d9d-6b64-43ae-856c-2c3f211bd426')_

So with this change, if you hit https://habitrpg.com/api/v2/challenges/:cid, it'll expect the UUID/key to be passed in with the request - which matches what the API docs read anyway. Then, since we have the user id, we can include the _isMember: true/false property on the response.

Let me know if this needs any clarification!

**Comment by Alys** [comment]
So it's been changed so that only a HabitRPG user can see the challenge details? To be honest, I'm not sure that's necessary for public challenges, given that anyone can become a HabitRPG user (although I can see that improving access control would be desirable for party challenges and private guild challenges). But `GET /challenges` is locked down, so it was probably an oversight that `GET /challenges/{cid}` wasn't. Making it consistent is good. Thank you.

Something to note though for any future API changes you might make: _"Every authenticated request should include two headers"_ -- I don't think that means that every request has to be authenticated. For example, the `content` requests shouldn't need authentication. I think it just means that if a request needs to be authenticated, then it should include the headers.

I'll try to get this reviewed in the next few days, if none of the other admins review it first.

If it's accepted (likely!), you'll get partial credit towards a contributor tier as normal.
@chrisdotcode and @TheHollidayInn : You will too for your PRs that this is based on.

**Comment by gisikw** [comment]
Yep, that's effectively the change. As it stands right now, all the challenge-fetching comes from the /collections endpoint, so we have that `_isMember` property available. The reason for the breakages on @chrisdotcode's stuff was that the view depends on that property existing, so the switching of the endpoint broke the behavior.

If it doesn't make sense to change the API, we could _probably_ do some cross-checking of the records on the client-side, but this seemed like a more straightforward approach.

As a sidenote though, if the intention is to have some publicly available API endpoints, and some private, we should update the API docs to be explicit about which require auth. That way, any future projects built against the API aren't blindsided.

**Comment by Alys** [comment]
_"If it doesn't make sense to change the API, we could probably do some cross-checking of the records on the client-side, but this seemed like a more straightforward approach."_
You're right - the approach you have taken is good.

_"we should update the API docs to be explicit about which require auth"_ Yes, that's a good idea. I will look into it.

**Comment by chrisdotcode** [comment]
@gisikw Remember that my PR is almost a year old, so (even though I'm sure you did), make sure the code therein is updated to match whatever that code looks like in HabitRPG currently.

**Comment by gisikw** [comment]
@chrisdotcode Yep yep - already done :)

**Comment by gisikw** [comment]
Rebased and passing :)

**Comment by Alys** [comment]
This is such a convenient feature but there's one problem we'll need fixed before it can go live. In the single challenge view, the group name and the challenge creator's name doesn't appear:

screen shot 2015-04-04 at 1 11 12 pm

For comparison, this is the same challenge when viewed from the Challenges page:
screen shot 2015-04-04 at 1 11 40 pm

The code to display the missing elements starts at https://github.com/HabitRPG/habitrpg/pull/4934/files#diff-0d406c9f752a9491f32ad6f33f8c4579R146

@chrisdotcode or @gisikw : Would you like to look into this?

**Comment by gisikw** [comment]
Sure thing - should be an easy fix. I can get that done in the morning :)

**Comment by gisikw** [comment]
Rebased, fixed, and passing :)

**Comment by Alys** [comment]
I am not able to edit challenges that I created. If that was happening before and I didn't notice it then, I am sorry for the additional back-and-forth. :(

There have been a few challenge-related [commits](https://github.com/HabitRPG/habitrpg/commits/develop) recently, so it's possible something there might be interfering with this new code.

Also - and this is entirely optional! - would you be interested in making the guild name (https://github.com/HabitRPG/habitrpg/pull/4934/files#diff-0d406c9f752a9491f32ad6f33f8c4579L144) a link to the guild page?

**Comment by gisikw** [comment]
Oh, hmmm, that's odd. I can take a look in the AM. For the record - did you try to edit from a single challenge view, or from multi-challenge view?

As for linking the guild - sure thing. Should be an easy fix.

**Comment by Alys** [comment]
I tried both, and the edit (and completion) buttons didn't appear in either.

It is slightly possible that the problem is that I am doing something stupid, and if that turns out to be the case you are allowed to mock me. :)

**Comment by gisikw** [comment]
Nope, I'm seeing the same issue on my end after a rebase. Taking a look now :)

**Comment by gisikw** [comment]
@Alys Should be fixed on both counts :)
- `challenges.jade` was trying to compare `challenge.leader==user_id`, when it should have been checking `challenge.leader._id==user._id`. To be honest, I'm not sure how that was ever working 
  ¯\_(ツ)_/¯
- Guild now links to the guild. I set the endpoint to forward up the group type as well, otherwise clicking on a party challenge would hit a guild page. So now it'll click through to either the guild or the party. Two for the price of one! :)

**Comment by Alys** [comment]
:heart:

Testing now, excitedly.

**Comment by Alys** [comment]
Yes, this is awesome! @gisikw Tier 5 awarded. 

See also the tier comments for chrisdotcode and TheHollidayInn at the bottom of https://github.com/HabitRPG/habitrpg/pull/3319 and https://github.com/HabitRPG/habitrpg/pull/4814

@gisikw Thank you very much for your help getting those two PRs merged!

**Comment by lemoness** [comment]
Should this go in a Bailey announcement? I'm thinking of putting it in a
"fixed bugs" section along with the XP-overflow fix.

**Comment by Alys** [comment]
@lemoness I think it's worth it. I've already seen three comments in various guilds thanking the (currently anonymous) programmers who did this, so it's clearly popular.
gisikw and chrisdotcode created the single challenge view, and TheHollidayInn did a fix for ttps://github.com/HabitRPG/habitrpg/issues/1719

**Comment by lemoness** [comment]
Will do!

**Pull request merged**
