### PR TITLE
Translations

### PR DESCRIPTION
**Pull request by frankfriberg**
norwegian translation implemented

### CODE REVIEW

**Comment by lefnire** [comment]
awesome! this is going to be on hold for a bit, translations is in limbo since it's on the old derby branch and won't work with the new setup. Once we get things squared away, we'll revisit this PR and massage it to the new setup. ETA 4 months.

@paglias did we close some translations PRs without merging? I can't remember, but I think I saw some. We should keep all translation PRs open until we can revisit, even though they won't work in the new setup we'll need them for reference

**Comment by paglias** [comment]
I don't remember having closed any translation pr but I'll check when I
have some time.

**Comment by paglias** [comment]
I've checked and we didn't close any of them, there are still some opens anyway

**Comment by lefnire** [comment]
Awesome! Sorry for the false alarm

On Sun, Sep 29, 2013 at 10:00 AM, Matteo Pagliazzi <notifications@github.com

**Comment by lefnire** [comment]
@frankfri I'm getting merge conflicts, but can't verify which one to choose as I don't understand NO. can you do a re-checkout of HabitRPG/translations and see if your updates still apply?

**Pull request closed without merging**
