### PR TITLE
Added pseudo class to clear button float

### PR DESCRIPTION
**Pull request by AnitaYCheng**
Pinging @crookedneighbor. This should do the trick! -crosses fingers-

### CODE REVIEW

**Comment by AnitaYCheng** [comment]
Did the original ping I edited in not work? :P @crookedneighbor :grin:

**Comment by deilann** [comment]
If you edit it in, it won't ping.

**Comment by AnitaYCheng** [comment]
Thanks for the note, still learning! :)

**Comment by deilann** [comment]
Edits also don't send email alerts, so it's almost always better to respond
with a new comment. If you want to then clean it up afterwards, you can
edit the original comment with the second comment's content, then delete
the second comment. This way, folks who mainly follow along via email get
the full story.

**Comment by crookedneighbor** [comment]
Sorry @AnitaYCheng, I did get your original ping. I just had a super busy day yesterday. Thanks for the reminder.

**Comment by crookedneighbor** [comment]
Merged into https://github.com/HabitRPG/habitrpg/pull/5110

**Pull request closed without merging**
