### PR TITLE
Visual fixes

### PR DESCRIPTION
**Pull request by zeroos**
Fixed some minor visual issues.

### CODE REVIEW

**Comment by lefnire** [comment]
I'm a CSS n00b - I'm playing with your fork locally, but I can't tell the difference it's made compared to the current site. @zakkain how does this look to you?

**Comment by zeroos** [comment]
Sorry, maybe I was not clear enough in comments - it was pretty hard for me to describe this changes. I've created a screenshot of what has been done: http://i44.tinypic.com/2w22agl.png , hope it'll help.

I've put a word (without spaces) in the input in first red box, but it doesn't have to be one word - longer tasks descriptions are also hidden below the `+` button.

**Comment by lefnire** [comment]
fantastic! i see it now, thanks a million @zeroos

**Comment by lefnire** [comment]
comment with your user id (uuid), i'm gonna give people "contributor rewards" once they've been implemented

**Comment by zeroos** [comment]
My uuid: f8e5fcfc-a9bc-4014-9914-46c8d24757f4

**Comment by caycefischer** [comment]
Very nice, thank you for the fix! This was stumping me for a little while

sweet

**Pull request merged**
