### PR TITLE
Removed unused strings

### PR DESCRIPTION
**Pull request by ghost**
Removed the following strings from character.json

-displayPhoto
-bodySlim
-bodyBroad
-unlockSet
-bodyHead
-bodySkin
-bodyHair
-hairBangs
-ponytail
-hairBase
-basicSkins
-equipmentBonusText
-classBonusText
-classEquipBonus
-battleGearText
-useCostumeInfo1
-useCostumeInfo2
-costumePopoverText
-autoEquipPopoverText
-gainedLevel
-fullyHealed
-levelBonusText
-allocatedPointsText
-buffsText
-wizardText
-optOutOfPMs
-youDied
-dieText
-sureReset
-displayNameDescription1
-displayNameDescription2
-displayNameDescription3
-unequipBattleGear
-unequipCostume
-unequipPetMountBackground
-youDied
-dieText
-sureReset
-chooseClassHeading
-warriorWiki
-mageWiki
-rogueWiki
-healerWiki
-showQuickAllocation
-hideQuickAllocation
-quickAllocationLevelPopover

Removed the following from communityGuidelines.json

-iAcceptCommunityGuidelines

Removed the following from content.json

-premiumPotionAddlNotes

Removed the following from contrib.json

-championSixth
-championFifth
-legSeventh
-guardianText
-heroicText
-modalContribAchievement
-helpedText1
-helpedText2
-visitHeroes
-currentSurvey
-surveyWhen
-blurbInbox
-blurbGuildsPage
-blurbChallenges

Removed the following from defaultTasks.json

-defaultHabit5Text
-defaultHabit5Notes
-defaultDaily1Text
-defaultTodo2Text
-defaultTodo2Notes
-defaultReward2Text
-defaultReward2Notes

Removed the following from challenge.json

-challengeWinner
-deleteOrSelect
-challengeDiscription
-noNone
-notParticipating
-challengeTag
-challengeTagPop
-prizePop
-prizePopTavern
-selectGroup
-sureDelCha
-sureDelChaTavern
-removeTasks
-challengedOwnedFilterHeader
-challengedOwnedFilter
-challengedEitherOwnedFilter
-backToChallenges
-challengeNotEnoughGems
-noPermissionEditChallenge
-noPermissionDeleteChallenge
-noPermissionCloseChallenge
-noChallengeOwner
-noChallengeOwnerPopover
-noCompletedTodosChallenge
-userTasksNoChallengeId
-shortNameTooShort

Removed the following from generic.json

-titleTasks
-titleAvatar
-titleBackgrounds
-titleStats
-titleAchievs
-titleProfile
-titleInbox
-titleTavern
-titleParty
-titleHeroes
-titlePatrons
-titleGuilds
-titleChallenges
-titleDrops
-titleQuests
-titlePets
-titleMounts
-titleEquipment
-titleSettings
-expandToolbar
-collapseToolbar
-markdownBlurb
-showFormattingHelp
-hideFormattingHelp
-youType
-youSee
-emojiExample
-markdownLinkEx
-markdownImageEx
-unorderedListHTML
-unorderedListMarkdown
-groupPlansTitle
-newGroupTitle
-moreInfoChallengesURL
-moreInfoTagsURL
-showMoreMore
-showMoreLess
-gemsWhatFor
-notPorted
-buyThis
-noReachServer
-errorUpCase
-serverUnreach
-seeConsole
-endTour
-audioTheme_danielTheBard
-audioTheme_wattsTheme
-audioTheme_gokulTheme
-audioTheme_luneFoxTheme
-audioTheme_rosstavoTheme
-audioTheme_dewinTheme
-audioTheme_airuTheme
-audioTheme_beatscribeNesTheme
-audioTheme_arashiTheme
-audioTheme_maflTheme
-audioTheme_pizildenTheme
-checkOutProgress
-greetingCardExplanation
-greeting0
-greeting1
-greeting2
-greeting3
-greetingCardAchievementTitle
-greetingCardAchievementText
-enableDesktopNotifications
-artDesign
-booksWriting
-comicsHobbies
-diyCrafts
-education
-foodCooking
-healthFitness
-scienceTech

Removed the following from front.json

-accept1Terms
-accept2Terms
-alexandraQuote
-althaireQuote
-andeeliaoQuote
-autumnesquirrelQuote
-businessSample1
-businessSample2
-businessSample3
-businessSample4
-businessSample5
-businessText
-choreSample1
-choreSample2
-choreSample3
-choreSample4
-choreSample5
-communityBug
-communityFeature
-communityKickstarter
-companyPrivacy
-companyTerms
-companyVideos
-contribUse
-dragonsilverQuote
-dreimQuote
-elmiQuote
-evagantzQuote
-examplesHeading
-featureAchievementByline
-featureAchievementHeading
-featureEquipByline
-featureEquipHeading
-featurePetByline
-featurePetHeading
-featureSocialByline
-featureSocialHeading
-featuresHeading
-footerDevs
-footerCommunity
-footerCompany
-frabjabulousQuote
-gamifyButton
-goalSample1
-goalSample2
-goalSample3
-goalSample4
-goalSample5
-healthSample1
-healthSample2
-healthSample3
-healthSample4
-healthSample5
-infhQuote
-irishfeet123Quote
-kazuiQuote
-landingend
-landingend2
-landingp1
-landingp2
-landingp3
-landingp4
-landingp2header
-landingp3header
-landingp4header
-loginAndReg
-loginFacebookAlt
-loginGoogleAlt
-passMan
-punishByline
-punishHeading1
-punishHeading2
-questByline1
-questByline2
-questHeading1
-questHeading2
-rewardByline1
-rewardByline2
-rewardHeading
-sampleDailies
-sampleHabits
-sampleToDo
-schoolSample1
-schoolSample2
-schoolSample3
-schoolSample4
-schoolSample5
-sixteenBitFilQuote
-skysailorQuote
-socialTitle
-supermouse35Quote
-teamSample1
-teamSample2
-teamSample3
-testimonialHeading
-localStorageClearing
-localStorageClearingExplanation
-unlockByline1
-unlockByline2
-unlockHeadline
-watchVideos
-zelahQuote
-imagine1
-landingCopy1
-landingCopy2
-landingCopy3
-getStartedNow
-altAttrNavLogo
-altAttrLifehacker
-altAttrNewYorkTimes
-altAttrMakeUseOf
-altAttrForbes
-altAttrCnet
-altAttrFastCompany
-altAttrKickstarter
-altAttrDiscover
-altAttrFrabjabulous
-altAttrAlexandraSo
-altAttrEvaGantz
-altAttrSupermouse35
-altAttrAlthaire
-altAttrInfH
-altAttrDreiM
-altAttrKazui
-altAttrAutumnesquirrel
-altAttrIrishfeet123
-altAttrElmi
-altAttr16bitFil
-altAttrZelahMeyer
-altAttrSkysailor
-altAttrIonic
-altAttrWebstorm
-altAttrGithub
-altAttrTrello
-altAttrSlack

Removed the following from messages.json

-messageDuplicateTaskID
-messageEquipped
-messageAlreadyPurchasedGear
-messageAuthPasswordMustMatch
-messageAuthCredentialsRequired
-messageAuthUsernameTaken
-messageAuthEmailTaken
-messageAuthNoUserFound
-messageAuthMustBeLoggedIn
-messageAuthMustIncludeTokens
-messageGroupNotFound
-messageUserOperationNotFound

Removed the following from npc.json

-donateText1
-donateText2
-donationDesc
-payWithCard
-payNote
-amazonInstructions
-moreClass
-tourWelcome
-tourExp
-tourDailies
-tourCron
-tourHP
-tourHabits
-tourStats
-tourGP
-tourAvatar
-tourScrollDown
-tourMuchMore
-tourAvatar
-tourAvatarProceed
-tourToDosBrief
-tourDailiesBrief
-tourDailiesProceed
-tourHabitsBrief
-TourHabitsProceed
-tourRewardsBrief
-tourRewardsArmoire
-tourRewardsProceed

Removed the following from overview.json

-webStep1Text
-webStep2Text
-webStep3Text

Removed the following from pets.json

-stableMountMasterProgress
-mountAchievement
-beastMountMasterName
-triadBingoAchievement
-hatchAPot
-displayNow
-displayLater
-earnedCompanion
-useSaddle
-raisedPet
-earnedSteed
-rideNow
-rideLater
-petKeyName
-petKeyPop
-petKeyBegin
-petKeyInfo
-petKeyInfo2
-petKeyInfo3
-petKeyInfo4
-petKeyPets
-petKeyMounts
-petKeyBoth
-confirmPetKey
-petKeyNeverMind
-gemsEach
-foodWikiText
-foodWikiUrl

Removed the following from tasks.json

-lotOfToDos
-deleteToDosExplanation
-newHabit
-newHabitBulk
-habitsDesc
-expandChecklist
-extraNotes
-direction/Actions
-difficultyHelpTitle
-difficultyHelpContent
-newDaily
-newDailyBulk
-dailysDesc
-streakCounter
-dailyRepeatHelpContent
-weeklyRepeatHelpContent
-newTodoBulk
-newRewardBulk
-newReward
-sureDeleteCompletedTodos
-dailiesRestingInInn
-habitHelp1
-habitHelp2
-habitHelp3
-newbieGuild
-dailyHelp1
-dailyHelp2
-dailyHelp3
-dailyHelp4
-dailyHelp5
-toDoHelp1
-toDoHelp2
-toDoHelp3
-toDoHelp4
-rewardHelp1
-rewardHelp2
-rewardHelp3
-rewardHelp4
-clickForHelp
-strengthExample
-intelligenceExample
-perceptionExample
-constitutionExample
-counterPeriod
-counterPeriodDay
-counterPeriodWeek
-counterPeriodMonth
-repeatTypeHelpTitle
-repeatType
-repeatTypeHelp
-repeatZero
-monthlyRepeatHelpContent
-yearlyRepeatHelpContent
-summaryStart
-yesterDailiesTitle
-yesterDailiesOptionTitle
-yesterDailiesDescription
-repeatDayError
-searchTasks
-repeatDayError

Removed the following from settings.json

-showHeaderPop
-restartTour
-classTourPop
-passwordSuccess
-usernameSuccess
-emailSuccess
-usernameOrEmail
-recurringText

Removed the following from subscriber.json

-subDescription
-cancelSubInfoGoogle
-cancelSubInfoApple
-adminSub
-morePlans
-organizationSub
-organizationSubText
-hostingType
-hostingTypeText
-customDomain
-customDomainText
-maxPlayers
-maxPlayersText
-priSupport
-priSupportText
-timeSupport
-timeSupportText
-gameFeatures
-gold2Gem
-gold2GemText
-infiniteGem
-infiniteGemText
-notYetPlan
-buyGemsGoldTitle
-becomeSubscriber
-freeGemsTitle
-buyGemsAllow1
-buyGemsAllow2
-purchaseGemsSeparately
-subFreeGemsHow
-seeSubscriptionDetails
-mysticHourglassPopover
-mysterySet201402
-mysterySet201403
-mysterySet201404
-mysterySet201405
-mysterySet201406
-mysterySet201407
-mysterySet201408
-mysterySet201409
-mysterySet201410
-mysterySet201411
-mysterySet201412
-mysterySet201501
-mysterySet201502
-mysterySet201503
-mysterySet201504
-mysterySet201505
-mysterySet201506
-mysterySet201507
-mysterySet201508
-mysterySet201509
-mysterySet201510
-mysterySet201511
-mysterySet201512
-mysterySet201601
-mysterySet201602
-mysterySet201603
-mysterySet201604
-mysterySet201605
-mysterySet201606
-mysterySet201607
-mysterySet201608
-mysterySet201609
-mysterySet201610
-mysterySet201611
-mysterySet201612
-mysterySet201701
-mysterySet201702
-mysterySet201703
-mysterySet201704
-mysterySet201705
-mysterySet201706
-mysterySet201707
-mysterySet201708
-mysterySet201709
-mysterySet201710
-mysterySet201711
-mysterySet301404
-mysterySet301405
-mysterySet301703
-mysterySet301704
-mysterySetwondercon
-hourglassBuyItemConfirm
-petsNotAllowedHourglass
-mountsNotAllowedHourglass

Removed the following from rebirth.json

-rebirthBegin
-rebirthStartOver
-rebirthAdvList1
-rebirthAdvList2
-rebirthAdvList3
-rebirthAdvList4
-rebirthInherit
-rebirthInList1
-rebirthInList2
-rebirthInList3
-rebirthInList4
-rebirthEarnAchievement
-beReborn
-confirmReborn

Removed the following from quests.json

-whereAreMyQuests
-yourQuests
-questsForSale
-petQuests
-unlockableQuests
-goldQuests
-questOwnerReceived
-youWillReceive
-questOwnerWillReceive
-dropQuestCongrats
-questSend
-questSendBroken
-questLater
-questStartBroken
-itemsToCollect
-bossDmg1
-bossDmg1Broken
-bossDmg2
-bossDmg2Broken
-tavernBossInfo
-tavernBossInfoBroken
-bossColl1
-bossColl1Broken
-bossColl2
-bossColl2Broken
-questOwnerNotInPendingQuest
-questOwnerNotInPendingQuestParty
-questOwnerNotInRunningQuest
-questOwnerNotInRunningQuestParty
-questParticipants
-noScrolls
-scrollsText1
-scrollsText2
-scrollsPre
-alreadyEarnedQuestLevel
-alreadyEarnedQuestReward
-completedQuests
-mustComplete
-mustLevel
-mustInviteFriend
-questWarning
-questWarningBroken
-whichQuestStart
-getMoreQuests
-unlockedAQuest
-leveledUpReceivedQuest

Removed the following from noscript.json

-jsDisabledText

Removed the following from merch.json

-merchandiseDescription
-merch-teespring-summary
-merch-teespring-goto
-merch-teespring-mug-summary
-merch-teespring-mug-goto
-merch-teespring-eu-summary
-merch-teespring-eu-gotof
-merch-teespring-mug-eu-summary
-merch-teespring-mug-eu-goto
-merch-stickermule-summary
-merch-stickermule-goto

Removed the following from loadingScreenTips.json

-tipTitle

Removed the following from limited.json

-limitedEdition
-seasonalEdition
-winterColors
-gildedTurkey
-polarBearPup
-nye0
-nye1
-nye2
-nye3
-nye4
-dateEndApril
-dateEndMay
-dateEndJune
-dateEndJuly
-dateEndAugust
-dateEndOctober
-dateEndNovember

### CODE REVIEW

**Comment by negue** [comment]
Thanks for your first contribution, but it seems you pushed all files from a different folder to your repo. 

Could you revert those changes ?


On the unused strings, did you go through all of them and tried searching for those in files?
Some of the strings are concatenated so those strings probably wouldn't be able to find.

For example: all `mysterySet`-strings

**Comment by ghost** [comment]
Oh geez, sorry about that. I'm fairly new to Git commands.

I should be able to revert this and create a new pull request.

With the strings, I searched for each strings existence within the entire project to see if it was used anywhere other than just the en locale .json file.

Was unsure if this was the best method and asked a while back if anyone could suggest something else but didn't get many other responses.

**Comment by ghost** [comment]
Hi @negue, sorry I'm having trouble finding how I managed to upload the changes as a sub folder instead of just overwriting the existing files with the changes. 

I essentially just opened Git Bash in the Habitica project, performed a commit and then pushed to my remote Repo.

Any suggestions on where I went wrong?

**Comment by paglias** [comment]
@Inshabel I'm not familiar with Git Bash but I'd suggest that you try to apply your changes again in a clean branch

**Comment by negue** [comment]
Closing this because of #10332

**Pull request closed without merging**
