### PR TITLE
Tokens = Gems for front-end display.

### PR DESCRIPTION
**Pull request by StanLindsey**
What do @Shaners & @zakkain  think about the gem position for the main token display?

### CODE REVIEW

**Comment by Shaners** [comment]
Is there anyway to quickly see the positioning in git hub? Or can I get a quick screenshot? I'm sure it's fine though.

**Comment by StanLindsey** [comment]
2013-05-10-184828_1366x768_scrot

**Comment by Shaners** [comment]
Looks perfect!

**Comment by lefnire** [comment]
Yeah, now taking a second look at it Stan it fits exactly right, don't know
why we were swaying on it lol

**Pull request merged**
