### PR TITLE
Remove lodash and moment

### PR DESCRIPTION
**Pull request by paglias**
**Update: they are included but not exported in habitrpg-shared, need to update it before merging**

Lodash and moment are included in habitrpg-shared, right? So they can be removed safely I think.

### CODE REVIEW

**Comment by lefnire** [comment]
but habitrpg-shared uses browserify, which wraps the require statements in a `function(moment,require){ ... }(INLINE_MOMENT, INLINE_REQUIRE)` closure, meaning they're not exposed to the window object. I could be wrong, but we'll want to test this PR first to make sure it works

**Comment by paglias** [comment]
Yes sorry I updated the description. It doesn't work. we should export them or they won't be avalaible out of the closure. Do you plan to rewrite habitrpg-shared in js? Then we could drop all the browserify thing (well that can be done also if we keep using coffee)

**Comment by lefnire** [comment]
we run browserify with the coffeeify flag, so it's all good. However, I do indeed plan to move it to JS eventually. I've been postponing it since habitrpg-shared is really heavy, and that conversion could take a good solid day.

well, here's why we're using browserify. the API uses `require('habitrpg-shared/algos')`, etc in order to pull in the modules exposed as module.exports. Browserify is meant to take commonjs-compatible modules & convert them to the browser by inlining the required modules. so this is just a method of making habirpg-shared easily available to both node.js & the browser. I'm not sure exporting the modules outside their closure is the solution - we may need to revisit how to handle habitrpg-shared in general, but i _think_ our current setup is probably the best bet

**Comment by paglias** [comment]
Yuo're right, we run also on node....

We could check if `window` is there and then attach `_` and `moment` to it

**Comment by lefnire** [comment]
Could do

``` javascript
var _, moment;
if (typeof window == 'undefined') {
  _ = require('lodash');
  moment = require('moment');
} else {
  if (!window._ || !window.moment) 
    throw("You must include lodash.js & moment.js in your <scripts>, and above habitrpg-shared");
  _ = window._;
  moment = window.moment;
}
```

**Comment by paglias** [comment]
Fantastic, maybe editing `index.js` would be better:

``` javascript
exports.algos = require('./algos.coffee');
exports.items = require('./items.coffee');
exports.helpers = require('./helpers.coffee');
// Multiple require do not means multiple version of moment/lodash, checked that!
var moment = require('moment);
var _ = require('lodash);

try {
    window;
    window.habitrpgShared = exports;
    window._ = _;
    window.moment = moment;
} catch(e) {}
```

So we have to manage lodash/moment version only on habitrpg-shared and no need to update on both mobile & site and they will also use the same version.

**Comment by lefnire** [comment]
sounds good! I'll check into it tonight unless you beat me to it. 
Edit: Oh I get it now. Yeah, that method is way better - good thinking!

**Pull request closed without merging**
