### PR TITLE
User can now check out of inn from tasks page

### LINKED ISSUE #5651: Resting at the Inn quick check out
Currently when you're resting at the inn you see a warning on your tasks page like this:

screenshot 2015-07-20 19 03 18

The functionality of resting at the inn is kind of tucked away and hard to find (under the Social dropdown on the Tavern view, with no menu item mentioning the Inn at all), which is maybe a separate issue. One change that could somewhat alleviate that, though, would be to add a button under the alert labelled "Check Out of Inn".
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/24675875-resting-at-the-inn-quick-check-out?utm_campaign=plugin&utm_content=tracker%2F68393&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F68393&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by gauthamchandra**
Fixes #5651

### CODE REVIEW

**Comment by crookedneighbor** [comment]
@gauthamchandra Would you mind posting a screenshot of the button?

**Comment by gauthamchandra** [comment]
It's the same button with the same style as the one used to check out from the Tavern.  

When I get back from work, I will post a screenshot.

**Comment by gauthamchandra** [comment]
Sorry for the delay:

screen shot 2015-11-11 at 12 52 04 pm

**Comment by gauthamchandra** [comment]
As mentioned before, its has the exact same classes and styling applied to the original button in the tavern to keep it consistent.

The only difference is a small `margin-top` added for better spacing

**Comment by SabreCat** [comment]
I like it!

**Comment by crookedneighbor** [comment]
This will count towards a contributor tier! What's your User ID? You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api). Be sure to only copy the User ID and _not_ your API Token.

**Comment by gauthamchandra** [comment]
@crookedneighbor Here is my User ID: `252142c8-9f08-4e9e-8a9c-c2d5f9c51baf`

and thanks!

**Comment by crookedneighbor** [comment]
Tier awarded! You can read more about [contributor tiers and rewards here](http://habitrpg.wikia.com/wiki/Contributor_Rewards).

Note that as your tier increases, it takes progressively more work to achieve the next one, so for the higher tiers, larger PRs or a few PRs are required. There's some information about that at Contributor Rewards, but feel free to ask here if you have questions!

**Pull request merged**
