### PR TITLE
Don't show unneeded spaces between buttons in chat

### PR DESCRIPTION
**Pull request by ghost**
Don't show spaces in front of a button in a chat message if button itself is not shown.

Addresses " Copy as To-Do looks a bit misplaced on system messages in chat #5201 "

Screenshots: 
Before before

After for users after for users

After for admins after for admins
- _The cause of the bug_:
  in front of each button there are two hard spaces, then the button itself - either shown or not.
- _Solution_
  may be not very elegant, but I believe it may be at least a temporary one.
- _Logic_:
  have hard spaces in `span`s with the same `ng-if`s as the following button

### CODE REVIEW

**Comment by ghost** [comment]
Hooray! :-) Thank you!
I'll close the ticket a bit later.

**Comment by crookedneighbor** [comment]
@GitHubSphinx FYI, if your PR or commit message says closes #5201 it'll automatically close it when the PR gets merged in. https://help.github.com/articles/closing-issues-via-commit-messages/

I made one adjustment and nested the links under the spans you created so we only had the `ng-if` stuff once: https://github.com/HabitRPG/habitrpg/commit/3644d43f0a9b1754afded47cb025595253ad64c6

**Comment by ghost** [comment]
Thank you! I've been thinking about a way to have only one ng-if, but
haven't found it. My bad. And I'm sorry once again you had to spend your
time helping me with entry level things...

**Comment by crookedneighbor** [comment]
No worries. This stuff has been bugging me for months. Glad to have an excuse to help you with it.

**Pull request merged**
