### PR TITLE
Restrict Challenge Summary String in API

### PR DESCRIPTION
**Pull request by calasada**
Uses substring to cleave off the end of a challenge summary if it's over the constant defining the size limit for the summary.

[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
https://github.com/HabitRPG/habitica/issues/9244

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

Just *hopefully* adds a string length limit for the summary to a challenge on the API level, which shouldn't happen anyway because the website restricts the length.

[//]: # (Put User ID in here - found in Settings -> API)

----
UUID: 4a58daa4-52de-49ff-b768-38bfbc84a563

### CODE REVIEW

**Comment by Alys** [comment]
I think it would be better to return an error message and not change the summary, rather than use a truncated version. The person editing the summary might not notice the truncation.

Even though the website will give good error handling, the API needs to do something similar because it's used by the mobile apps and third-party tools.

**Comment by paglias** [comment]
Yes, I agree with @Alys, this should be an error at the schema level in models/group.js

**Comment by librarianmage** [comment]
@Calasada How are you doing with this?

**Comment by lemoness** [comment]
I've updated the labels to indicate that this PR has been abandoned and needs to be reviewed by our devs.

**Pull request closed without merging**
