### PR TITLE
Removed unused I18N strings from the `character.json` files (related to issue #9957)

### PR DESCRIPTION
**Pull request by RaitheOfDureya**
[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
This PR fixes part of issue #9957

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
I have identified the following unused strings in the `character.json` file.  

At the moment I only removed the strings from the `locales/en` folder to make it easier to revert if necessary. Once the strings are reviewed, I can delete them from other languages.

- displayPhoto
- displayBlurb
- bodySize
- bodySlim
- bodyBroad
- unlockSet
- bodyHead
- bodySkin
- bodyHair
- ponytail
- hairBase
- basicSkins
- equipmentBonusText
- classBonusText
- battleGearText
- costumeText
- useCostumeInfo1
- useCostumeInfo2
- fullyHealed
- levelBonusText
- allocatedPointsText
- buffsText
- haveUnallocated
- optOutOfPMs
- respawn
- youDied
- dieText
- sureReset
- displayNameDescription1
- displayNameDescription2
- displayNameDescription3
- unequipBattleGear
- unequipCostume
- unequipPetMountBackground
- chooseClassHeading
- warriorWiki
- mageWiki
- rogueWiki
- healerWiki
- chooseClassLearn
- showQuickAllocation
- hideQuickAllocation
- quickAllocationLevelPopover

**Requires Attention:**
the string `strText` is not being used anywhere, but the strings conText, perText, intText are...

Reviewing the `website/client/src/components/userMenu/profileStats.vue` file I noticed that `strengthText` is being used instead of `strText`, however  `strengthText` it is not listed in any locales files :sweat_smile:.

```javascript
...
allocateStatsList: {
  str: { title: 'allocateStr', popover: 'strengthText', allocatepop: 'allocateStrPop' },
  int: { title: 'allocateInt', popover: 'intText', allocatepop: 'allocateIntPop' },
  con: { title: 'allocateCon', popover: 'conText', allocatepop: 'allocateConPop' },
  per: { title: 'allocatePer', popover: 'perText', allocatepop: 'allocatePerPop' },
},
...
```

What should I do with the `strText` string?
Remove it, rename to `strengthText, or leave it as it is?

The following dynamically generated strings were found during the review process: 
```javascript
$t(`${heroClass}Text`)
```

- warriorText
- wizardText
- mageText
- rogueText
- healerText

These two are being used here 0837d17:

- costumePopoverText
- autoEquipPopoverText

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 6544e17f-237b-4915-ae7e-47744c0dc1bd

### CODE REVIEW

**Comment by paglias** [comment]
@SabreCat is the `strText` vs `strengthText` something we want to change?

**Comment by paglias** [comment]
The gained/lost strings are used here 
Schermata 2020-10-02 alle 19 14 01

**Comment by paglias** [comment]
```
warriorText
wizardText
mageText
rogueText
healerText
```

are used 
Schermata 2020-10-02 alle 19 19 12

**Comment by RaitheOfDureya** [comment]
Thanks for the review, @paglias 
I include the following strings again:

- warriorText
- wizardText
- mageText
- rogueText
- healerText
- gainedLevel
- gainedGold
- gainedMana
- gainedHealth
- gainedExperience
- lostGold
- lostMana
- lostHealth
- lostExperience

**Comment by paglias** [comment]
`battleGear` seems used, otherwise it's looking good!

**Comment by RaitheOfDureya** [comment]
here you go, @paglias  :smile:

**Comment by RaitheOfDureya** [comment]
@paglias,
I believe I found 2 more strings that might be being used.
I remembered that you corrected a few weeks ago an interpolation format problem and I don't recall if I updated the list of strings dynamically generated after that...

Could you check if the following strings are being used in the code that you have fixed with this commit 0837d17616a4e1f55271ba6259d32cfd5d6be78c:

- costumePopoverText
- autoEquipPopoverText

**Comment by paglias** [comment]
Schermata 2020-10-06 alle 13 10 08

they are used indeed!

**Comment by RaitheOfDureya** [comment]
Here it goes again, @paglias 
I hope this time we caught everything :sweat_smile:

**Pull request merged**
