### PR TITLE
Fix knockout image

### PR DESCRIPTION
**Pull request by sporeball**
Fixes https://github.com/HabitRPG/habitrpg/issues/7738

User ID: ce3d1e2b-be53-4e5e-8101-273157548178

(I don't know why my PR from an older issue and the PR I made to my fork to update it are in this PR)

### CODE REVIEW

**Comment by khipkin** [comment]
Did you rebase your fork?

**Comment by khipkin** [comment]
Also, can you post a screenshot? Maybe the updated version of the one from your bug report? :smiley:

**Comment by sporeball** [comment]
@khipkin I rebased a second ago. I didn't know how to do that before...

Anyway, in 7b9a340 I changed the width of the knockout image from 200px to 160px; I realized 200px was a bit too much. Here's a screenshot:

image

However, to position the knockout image like this I changed `.knockout` to this in Chrome's developer tools (the imgur link being the updated knockout image):

image

@SabreCat So, if sprites were compiled again with the updated knockout image, would the spritesheet and the CSS for `.knockout` update to reflect the changed width?

**Comment by khipkin** [comment]
Yayy rebasing!

You can run `npm run sprites` to recompile the image spritesheets and see what happens.

**Comment by sporeball** [comment]
Rebasing, please stop this madness.

What am I doing wrong aah

**Comment by khipkin** [comment]
It doesn't _look_ like you rebased... if you had, all of your commits that aren't already in `upstream/master` would be replayed _**on top of**_ all those other commits.  Basically, your commits that haven't already been merged into the main repo would be the most recent ones, so alllll of those other commits wouldn't show up here.

What commands did you run to rebase?

**Comment by crookedneighbor** [comment]
Looks to me like a merge of develop, followed by a rebase against your own upstream, which would replay the develop commits over it. 

I would do this. 

``` bash
git reset upstream/develop #assuming you have the main repo's remote set to upstream
git add -A # stage all files
git commit -m "message here"
# at this point your commits will have diverged. You'll have some on your Github remote that you won't have here and one here you won't have there
git push --force # overwrite changes on your Github account with the local ones
```

**Comment by sporeball** [comment]
Woo, thanks @crookedneighbor . Now to fix things and test items.

So I can use that code every time I make changes locally, right?

**Comment by khipkin** [comment]
I think those commands were to overwrite the weird rebase attempt and also do the correct rebase.

To just do the correct rebase, run these commands (from the ["Using Habitica Git" wiki page](http://habitica.wikia.com/wiki/Using_Habitica_Git#Rebase_Branch)):

```
git checkout develop
git fetch upstream             # to fetch commits that aren't in your fork
git rebase upstream/develop    # to replay those commits with yours on top
git push                       # to update your fork on GitHub
```

**Comment by MrEikono** [comment]
@khipkin
*cough*

I ran the commands you listed above, plus `git pull` before `git push` (because Git Shell had me do so) and then this happened again. Running @crookedneighbor 's commands again did nothing.

Why am I never able to do this correctly...?!

**Comment by crookedneighbor** [comment]
Just rememberd: you'll need to read this trello card and follow the instructions before we can merge this in: https://trello.com/c/eFz57Pqi/24-permissions

**Comment by sporeball** [comment]
@crookedneighbor Permissions got sent over yesterday. :)

**Comment by crookedneighbor** [comment]
@MrEikono In the issue @lemoness said to go with the double knockout image. Any reason you didn't do that for this PR?

**Comment by sporeball** [comment]
@crookedneighbor It's because I'm still unable to compile sprites, so I haven't been able to test after making changes to the image, so I haven't made any updates to the image in this PR yet.

(I closed and reopened the issue because I once again screwed up on mobile. _cough_)

**Comment by khipkin** [comment]
@MrEikono If you're still unable to compile sprites, maybe you could just push your latest changes and someone else can post a screenshot of the result?

**Comment by sporeball** [comment]
@khipkin Oh, I haven't tried yet. I've been insanely busy lately so haven't had a chance to. x-x

**Comment by crookedneighbor** [comment]
I'm going to close this for now. But re-open it if you're able to work on it again.

**Comment by sporeball** [comment]
@crookedneighbor I can't reopen this, but I do have a week-long break from school to work on this issue again... Could you reopen this for me, please?

**Comment by crookedneighbor** [comment]
I cannot because the changes are so out of date with the current codebase. You'll need to either resolve the conflicts or open a new PR.

**Pull request closed without merging**
