### PR TITLE
Updating User API Doc (part 4)

### PR DESCRIPTION
**Pull request by madpink**
The issue: https://github.com/HabitRPG/habitica/issues/8087

I've updated the API documentation for the fourth batch of User

Includes:  POST /api/v3/user/revive – POST /api/v3/user/custom-day-start

----
UUID: b0413351-405f-416f-8787-947ec1c85199

### CODE REVIEW

**Comment by TheHollidayInn** [comment]
Thanks! Looks like you have a small linting error.

**Comment by madpink** [comment]
I swear, as the Magical Axolotl as my witness, that I did a search and replace for trailing spaces before I submitted the PR

**Comment by madpink** [comment]
quick mea culpa... looking back, I should've run my search and replace for trailing spaces more than once...

**Review by SabreCat — APPROVED** [review]

**Comment by SabreCat** [comment]
Thanks @madpink! Noted toward Blacksmith contributor tier 3.

**Pull request merged**
