### PR TITLE
fix(achievements): Differentiate singular and plural

### PR DESCRIPTION
**Pull request by SabreCat**
Allows Streak and Perfect Day achievements to dynamically show a singular or plural version of their text based on how many achievements the viewed profile has stacked.

BREAKING CHANGE: Will lead to 'string not found' errors until the singular version strings are implemented in all locales on habitrpg-shared.

### CODE REVIEW

**Comment by SabreCat** [comment]
Having some troubles with my local install, and it'll take a while to sort out, so I'm setting up the PR in case someone else can vet the code/test while I'm hung up. Otherwise I'll see if I'm back up and running, test and merge in the next couple of days.

**Comment by deilann** [comment]
HI FIVE! We can have local install issues!

**Comment by SabreCat** [comment]
What's more, I managed to break the VM I built yesterday, so now I'm on my third attempt at getting an Ubuntu VM up and running with a Habit dev env... sigh.

**Comment by SabreCat** [comment]
D'oh. I still don't get how to rebase without blowing up my commit. Gonna try this again.

**Pull request closed without merging**
