### PR TITLE
Rebirth (former working title "New Game+") feature

### PR DESCRIPTION
**Pull request by SabreCat**
Web implementation of the "Rebirth" feature!

At level 50, or when the user earns a "Beastmaster" or "Ultimate Gear" achievement, they unlock a new item in the Market: the Orb of Rebirth. This item, costing 8 Gems, allows them to begin a new game while retaining their tasks and task history. Using the item earns an achievement, and shows a prestige icon next to the user's level readout that, when hovered over, displays the maximum level the user has previously attained. The user can stack their Rebirth achievement by using another Orb of Rebirth when they're at a higher level than they've previously attained.

### CODE REVIEW

**Comment by lefnire** [comment]
Cool man, this (and the habitrpg-shared equiv) look good. I'm trying to think, sounds like @lemoness wants to release this on 1/1 (since the feature maps well). If that's the case, I'll leave this in the queue until then, then I'll do the merge.

I'll probably merge habitrpg-shared now, since the op won't be available without this commit, and since you fixed a bug on fortify

**Comment by lefnire** [comment]
oh wait actually maybe not, since rebirthEnabled flags the modal to show, and if I merge shared now that will be set to `true` beforehand, so they won't see the modal come 1/1

**Comment by SabreCat** [comment]
If it's easier to deal with conflicts by merging that now, a Bailey notification would probably be sufficient to let people with the prereqs know to stop by the Market to see what's there.

**Comment by SabreCat** [comment]
Or! Merge everything now, but comment out the watcher so the flag doesn't get set yet. Then do a simple flip-the-switch commit on 1/1. There's options :)

**Comment by lefnire** [comment]
Ah yes, good call! (not the `$scope.$watch` anyway, but the habitrpg-shared post-score flags checker thingy).

**Comment by lefnire** [comment]
eh, close enough to the time - I'll just merge & launch 12/31

**Comment by SabreCat** [comment]
Yay! :smile_cat:

**Comment by SabreCat** [comment]
:metal:

**Comment by lefnire** [comment]
We may want a wikia on this, probably just copy/paste what you have in the modal (it's really informative)

I'll be jumping in to answer your Qs & progress on autoAllocate soon as I can, don't worry - not ignoring/forgetting

**Comment by SabreCat** [comment]
Ah yes. I remember a conversation we had, where you said something along the lines of "devs are fine with documenting their code, they don't want to write post hoc wikis"... I'm feelin' it :cat::sweat_drops: I'll put it on the to-dos, ha.

As for questions etc., all cool, don't let me slow you down!

**Pull request merged**
