### PR TITLE
Allow Masterclasser achievement when quests completed out of order

### LINKED ISSUE #9461: Quest Completionist achievement should not require quests to be completed in order
As reported by Tex Geoffiamson in the Report a Bug guild and as confirmed by Lemoness, there is a bug with how you achieve the "Quest Completionist" achievement ("Completed all sixteen quests in the Masterclasser Quest Series and solved the mystery of the Lost Masterclasser!").

With our current code the achievement is only assessed when Masterclasser Part 4 is assessed: https://github.com/HabitRPG/habitica/blob/0e2b80ef2edec85b978ecac85f18aa41a97ce3bc/website/server/models/group.js#L776-L801

The correct behaviour to get the achievement is that you must complete all 16 quests, BUT you should be able to do them in any order. 

Steps to Reproduce:
   - Party member A completes "Stoïkalm Calamity, Part 1: Earthen Enemies"
   - Party members A & B complete 14 other Masterclasses prerequisite quests other then "Sto?kalm Calamity, Part 1: Earthen Enemies" and "The Mystery of the Masterclassers, Part 4: The Lost Masterclasser"
   - Party members A & B complete "The Mystery of the Masterclassers, Part 4: The Lost Masterclasser"
   - Party member B completes "Stoïkalm Calamity, Part 1: Earthen Enemies"

Current Behavior:
   - ONLY Party members A has "Quest Completionist: Masterclasser Series"

Expected Behavior:
   - Party members A & B has "Quest Completionist: Masterclasser Series"

For anyone who works on this, you can set up appropriate test user accounts without completing all the quests manually by setting the data below in each account in your local install's database. Leave out one of these achievements to make a test account that hasn't yet done all the quests before "The Mystery of the Masterclassers, Part 4".
```
"achievements.quests": {
	"dilatoryDistress1": 1,
	"dilatoryDistress2": 1,
	"dilatoryDistress3": 1,
	"mayhemMistiflying1": 1,
	"mayhemMistiflying2": 1,
	"mayhemMistiflying3": 1,
	"stoikalmCalamity1": 1,
	"stoikalmCalamity2": 1,
	"stoikalmCalamity3": 1,
	"taskwoodsTerror1": 1,
	"taskwoodsTerror2": 1,
	"taskwoodsTerror3": 1,
	"lostMasterclasser1": 1,
	"lostMasterclasser2": 1,
	"lostMasterclasser3": 1,
},
```

## What to do if this bug happens to you

**Anyone who has completed all 16 quests and doesn't have the  "Quest Completionist" achievement can post to the Report a Bug guild to have the achievement given to them.** Please do NOT post to this issue to request that. It's easier for us and faster for you if you post to the Report a Bug guild.

### PR DESCRIPTION
**Pull request by AlyxMoon**
Fixes #9461

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
Updated file `website\server\models\group.js`
- Changed the check that current completed quest is the final in Master Classer series, it now checks that the completed quest is any in the series
- Updated query to include last Master Classer quest

Updated test file `test\api\v3\unit\models\group.test.js`
- Added a new test to check whether Master Classer achievement is given when the final quest to be completed is not the final one in the series
- Updated test for Master Classer achievement (existing test and new test for when completed out of order) to include an `exec()` call after `findById()`

----
UUID: cc212fcc-5f96-403b-a785-17ba66c7b11a

### CODE REVIEW

**Comment by Alys** [comment]
The Travis tests are failing with this message:

  1) Group Model Instance Methods #finishQuest gives out super awesome Masterclasser achievement when quests done out of order:
     AssertionError: expected undefined to deeply equal true
      at _callee82$ (test/api/v3/unit/models/group.test.js:1453:65)

When I tested your code on my local install, I saw that same message twice, but then the test passed in another three runs of it. I think it's only failing because something in the test or in the new code is timing out. The code itself looks fine apart from that and the fact that test passes sometimes shows that the code is correct when there's no timeout.

We will need to stop the timeout happening but I'm not sure how to achieve that. I'm throwing this back to the other admins to look at. :)

**Comment by SabreCat** [comment]
I'm having trouble reproducing the test failure locally, but we definitely don't want to introduce another timeout issue into a test suite that's already somewhat vulnerable to them. I'm going to try something and push it to another branch, see if it helps, then merge back here if it works. Stand by!

**Comment by SabreCat** [comment]
Hmm, no luck yet. Will check in with the other devs.

**Comment by AlyxMoon** [comment]
Okay thanks guys, I was stuck on this.

I had added a call to exec() as first recommended for the tests, but I was always getting the tests to pass regardless of whether I had that exec() in there or not.

**Comment by paglias** [comment]
@AlyxMoon I think it might be worth to try changing this code in website/server/models/group.js

```
async function _updateUserWithRetries (userId, updates, numTry = 1, query = {}) {
  query._id = userId;
  return await User.update(query, updates).exec()
    .then((raw) => {
      return raw;
    }).catch((err) => {
      if (numTry < MAX_UPDATE_RETRIES) {
        return _updateUserWithRetries(userId, updates, ++numTry);
      } else {
        throw err;
      }
    });
}
```

to something like this

```
async function _updateUserWithRetries (userId, updates, numTry = 1, query = {}) {
  query._id = userId;
  try {
    return await User.update(query, updates).exec();
  } catch (err) {
    if (numTry < MAX_UPDATE_RETRIES) {
      return _updateUserWithRetries(userId, updates, ++numTry);
    } else {
      throw err;
    }
  }
}
```

to see if there was a concurrency problem.

**Comment by AlyxMoon** [comment]
@paglias I tried implementing your change. Local test still worked, Travis CI remains the same.

I also somehow made a mess when I synced my changes up, now I think I screwed up the pull request by bringing in other commits.

**Comment by TheHollidayInn** [comment]
It looks like you rebased. After a few days (maybe if the next) it is better to merge in develop so you don't have collision like this. Something I have faced many times :P

**Comment by AlyxMoon** [comment]
Is there any way I can run the Travis CI checks without opening a PR or updating it? It must be that the test I added is causing a problem but I don't know enough about this stuff to fix it without just tweaking the code a bunch.

It works when running the tests locally, so it's just something with the Travis CI, and I don't want to clutter up the PR any further than I've already been doing if that's an annoyance.

**Comment by TheHollidayInn** [comment]
You have to be an owner of the repo, so unfortunately no. You probably can add Travis to your forked repo and just test out a branch there.

**Comment by AlyxMoon** [comment]
Okay thanks, I'll give that a shot to play around with things more.

**Comment by paglias** [comment]
How is this going @AlyxMoon  ? Let me know if you need any help

**Comment by lemoness** [comment]
I've updated the labels to indicate that this PR has been abandoned and needs to be reviewed by our devs.

**Comment by SabreCat** [comment]
Fixed elsewhere... mostly...

**Pull request closed without merging**
