### PR TITLE
Add Dewin's new Theme

### PR DESCRIPTION
**Pull request by Ozzystrasza**
### Changes

Uploaded audio files to common/audio/dewinTheme;
Added a new string "audioTheme_dewinTheme": "Dewin's Theme", in common/locales/en/generic.json
Added 'dewinTheme' in website/server/models/user/schema.js
Added 'dewinTheme' in website/views/shared/header/menu.jade
dewintheme

---

Dewin's Theme by:
Username: Dewin
UUID: 08a24da8-28ee-4c88-9138-9c22020cacdf

My UUID: 8389891a-ba52-4580-b08b-2cb706c7e0b4

### CODE REVIEW

**Comment by khipkin** [comment]
`Boss Battles Background Music.*` and `Settings Page Background Music.*` should not have spaces in the filenames.  Also, these files don't exist for any other established audio theme, which seems like a big deal.

**Comment by Ozzystrasza** [comment]
Hmm I didn't check the audio files I received from Dewin, I thought everything was ready to upload. What should I do about it?

**Comment by Alys** [comment]
Rename the files to have underscores instead of spaces (I should have noticed that). You can leave them in the directory even though they won't be used. They might be used in future if we implement those sound features. The [sound effects Trello card](https://trello.com/c/tljx8gKC/18-music-sound-effects-v3) supports the idea of background music in future.

**Comment by Ozzystrasza** [comment]
The changes requested are all done.

**Comment by Alys** [comment]
Ozzystrasza and Dewin, thank you for this! It will be merged later today. I'm just waiting for a site deployment to be finished so that this doesn't get caught up in it. It will go live with the next deployment after that.

Ozzystrasza, I have noted this as credit towards your next tier.

Dewin, I've given you Tier 1 for this.
Note that as your tier increases, it takes progressively more work to achieve the next one. There's some information about that at [Contributor Rewards](http://habitrpg.wikia.com/wiki/Contributor_Rewards), but feel free to ask here if you have questions!

**Comment by Ozzystrasza** [comment]
@Alys : Did it work? I still don't see Dewin's Theme on the list

**Comment by crookedneighbor** [comment]
It hasn't been deployed yet.

**Pull request merged**
