### PR TITLE
Fixes #4647. reduce padding at bottom of food-tray container 

### LINKED ISSUE #4647: Awkward scrollbar breakpoint on food box
When the food storage area of the Pets page reaches four rows of items, it gets a scrollbar, but the scrollbar isn't actually necessary to show everything:

image

The appearance of the scrollbar is a little bit unsightly and misleading, looking like there's more to see when there isn't. It'd be nice to have the scrollbar appear only when it's necessary to display an additional row of items.

The above is Chrome on Windows 7. It doesn't appear to be resolution-dependent, because the food box remains the same size even if I scale down the browser window.

### PR DESCRIPTION
**Pull request by kangabell**
to avoid awkward scrollbar breakpoint

### CODE REVIEW

**Comment by crookedneighbor** [comment]
I'm very hesitant to make a global change to the `.well` class. Doing a [quick search](https://github.com/HabitRPG/habitrpg/search?l=jade&q=.well&utf8=%E2%9C%93) shows that at least 8 different Jade files use the `.well` class.

**Comment by kangabell** [comment]
@crookedneighbor good point. How's about `.food-tray?`

**Comment by crookedneighbor** [comment]
Yes, food-tray is a much better choice.

**Comment by kangabell** [comment]
@crookedneighbor updated.

**Comment by crookedneighbor** [comment]
Tier++

**Pull request merged**
