### PR TITLE
(WIP) API summary limit - Fixes #9244

### LINKED ISSUE #9244: API must enforce maximum length for summaries for Guilds and Challenges
Guilds and Challenges have a summary field and the website enforces a maximum length for it:
https://github.com/HabitRPG/habitica/blob/6838b7d0a60c1b5b089ae5dab17f9cf10e09b937/website/common/script/constants.js#L9-L10

The API's routes for creating and editing Guilds and Challenges should enforce the same maximum.

Note that currently the API does not make the summary field mandatory - that is desired behaviour at the moment because a mandatory summary would be a breaking change for the API. Because of this, the API should enforce the maximum length only if a summary is provided. Don't make the summary mandatory.

There should also be tests that ensure that IF a summary is provided, it is not too long.

### PR DESCRIPTION
**Pull request by Helcostr**
[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #9244 

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
* Adds a length checker for `summary` at the express-validator level before hitting the mongoose schema level
(WIP)

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 10cbe941-0e10-4763-9f4f-7a3ae5bb2198

### CODE REVIEW

**Comment by SabreCat** [comment]
If this is a WIP, can you set it to draft status until it's ready for review?

**Comment by Helcostr** [comment]
I am working on the API, and i notice there are two methods for throwing an error...

We have apiErrors (a full english non translated library), and we have res.t (grabbing error messages). I am not sure which one to use when making new error msgs.

**Comment by Helcostr** [comment]
I am looking at the API, and I am confused...

Why does v3 [CreateChallenge](https://habitica.com/apidoc/#api-Challenge-CreateChallenge-0.0.0) doesn't intake a challenge object like the API suggests???

It seems like it's taking it in on the first dimension (so no challenge object is actually passed for some reason 🤔)

(looks like I am going off the books and just doing whatever the previous format did, even though it doesn't match the documentation)

**Comment by SabreCat** [comment]
> We have apiErrors (a full english non translated library), and we have res.t (grabbing error messages). I am not sure which one to use when making new error msgs.

I'd recommend `apiErrors`. Technical responses don't need to be localized.

> (looks like I am going off the books and just doing whatever the previous format did, even though it doesn't match the documentation)

Huh, good catch! If you'd like, you can update the documentation to match the API's expectation.

That said, it looks like you haven't worked on this in a while--are you still planning to tackle this, @Helcostr ?

**Comment by Helcostr** [comment]
Sure!

**Pull request closed without merging**
