### PR TITLE
Commit to allow selenium testing

### PR DESCRIPTION
**Pull request by kevany23**
[//]: # (Note: See https://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes put_#_and_issue_number_here

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
This PR adds an npm command to run Selenium tests that the developer can add into the test folder as a file named `selenium`. The folder would contains the test files and must be able to run `npm test`.
The app must be running locally.
My current repo for selenium testing with Habitica, an example of such a Selenium test:
https://github.com/kevany23/habitica-selenium

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID:
e3dc3680-cd76-4bc8-8976-ce11bd297cf3

### CODE REVIEW

**Comment by kevany23** [comment]
Sorry, this is my first PR.

**Comment by SabreCat** [comment]
Would it be possible to include at least one sample test with this PR? So folks unfamiliar with Selenium can see how it's done!

**Comment by kevany23** [comment]
Yes, I'll be looking to add some sample tests!

**Comment by kevany23** [comment]
I've added a sample test workflow. To set it up, you need chromedriver.exe in the test/selenium folder. The test cases are still a work in progress in my repo.

**Comment by kevany23** [comment]
Additional test cases have been put in this pull request:
https://github.com/HabitRPG/habitica/pull/13664

**Comment by pleshevskiy** [comment]
If you are looking at integration tests, I highly recommend using [cypress](https://www.cypress.io/). It is intuitive in setting up each case for any developer.

**Comment by kevany23** [comment]
I have not used cypress before, but it looks interesting. I found selenium to be surprisingly easy to set up and it was recommended by my peers, and I wanted to test some web page functionalities.

**Comment by SabreCat** [comment]
By the look of it, everything in this PR is contained in #13664, so it's not needed as a separate pull request. Let me know if I'm mistaken!

**Pull request closed without merging**
