### PR TITLE
Remove Ian's wolf "flicker"

### LINKED ISSUE #7867: Weird wolf head thing
General Info
- UUID: ce6fa251-fed2-4023-b752-9a4c5d106c9d
- Browser: Firefox
- OS: ???
### Description

[//](#): # When I went to the quest shop, the wolf head shown in front of Ian the quest shop guy showed for a frame before it disappeared. (I assume this was not intentional.) It then reappeared and roared (like it is supposed to do, I assume) and then the animation looped.
#### Console Errors

I do not know how to see the Console, so I do not know of any errors in the console..

### PR DESCRIPTION
**Pull request by librarianmage**
Fixes #7867
### Changes

Removes the "flicker" frame in Ian's normal sprite

---

UUID: 95f16006-1504-4a9f-95b6-0c7314dbd7ee

### CODE REVIEW

**Comment by khipkin** [comment]
:+1:

**Comment by crookedneighbor** [comment]
@MathWhiz You'll need to read this trello card and follow the instructions before we can merge this in: https://trello.com/c/eFz57Pqi/24-permissions

**Comment by librarianmage** [comment]
@crookedneighbor Done!

**Comment by crookedneighbor** [comment]
Confirmed that we got it. Thanks! Notated toward your next tier.

**Pull request merged**
