### PR TITLE
Added member search to group member view

### LINKED ISSUE #1806: Need way to expand/search guild members list - can't assign new leader or boot member when member isn't listed
At present, Guilds only list the first 15 members, plus a little blob saying how many more members than that you have. But there's not any way to access the rest of that list--today I wanted to know if somebody was still a guild member, and had no means of determining that.

Suggestions, in order of my most preferable to least (though you could do more than one):
1. Add a search field to the member list, something like what we have in the Public Guilds tab.
2. Add a button to click to load the full list of guild members.
3. Implement incremental-load scrolling, so you can roll down to the bottom of the list, it picks up the next 15 (or however many) names, and you continue...
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/1386145-need-way-to-expand-search-guild-members-list-can-t-assign-new-leader-or-boot-member-when-member-isn-t-listed?utm_campaign=plugin&utm_content=tracker%2F68393&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F68393&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by TheHollidayInn**
This should fix https://github.com/HabitRPG/habitrpg/issues/1806 and subsequently https://github.com/HabitRPG/habitrpg/issues/2160 

However, I am unsure how to test on the large number of users. 

Here are some screenshots:
screen shot 2015-03-19 at 2 14 42 pm
screen shot 2015-03-19 at 2 15 00 pm
screen shot 2015-03-19 at 2 15 08 pm

### CODE REVIEW

**Comment by Alys** [comment]
I'm afraid I can't get this to work with any name that isn't already showing up in the list of 15 members.

There have been quite a few PRs pushed to `develop` in the past couple of weeks, so maybe some new code is interfering with this.

**Comment by gisikw** [comment]
Yep - the issue here is that a max of 15 users are returned from the API (presumably so it doesn't take years to load up large guilds). Filtering on the client-side can only then operate on that list of 15.

What's really necessary to support this feature would be a new endpoint (probably something like `/groups/{gid}/members`, which could then be polled for records. Still though, that's 17074 records for the Scholars Guild, which is a lot to query mongo for, and a lot to serve back.

We could try to mitigate it by maybe instead having a `/groups/{gid}/memberQuery/{startString}` perhaps? And then just debounce the heck out of the updating on the frontend side of things? Alternatively...ElasticSearch FTW (though that'd be a whole bunch of setup).

I think the 15-cap was put in place for performance reasons though, so it's probably best that someone familiar with the production stack comment on whether or not opening up a members endpoint is feasible here.

**Comment by paglias** [comment]
@TheHollidayInn I posted also on the other PR, so forgive me if I repeat myself: the problem with fetching members is that each member is stored in the Group model as its UUID and fetching it means making another query to MongoDB for every single user

**Comment by crookedneighbor** [comment]
Closing this as it has stalled, If you figure out a way to do this, please re-open it. 

@gisikw @paglias What if we did a query on username, got a list of ids that match that string, and then check those ids in the member list?

**Pull request closed without merging**
