### PR TITLE
10829 Allows short name to be updatable

### LINKED ISSUE #10829: Changes to Challenge short name (tag name) do not save
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

If, when editing a Challenge, you change the "Short Name" that's used to define the Challenge's tag, the edits do not save to the database. Next time you refresh, the Challenge will still have the old tag.

### PR DESCRIPTION
**Pull request by VickyKoblinski**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #10829

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
It looks like shortName was not intended to be updatable, so the "fix" was pretty easy.

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 7d3f909a-a2f3-49ea-865f-ff1ec9fe174a

### CODE REVIEW

**Comment by Alys** [comment]
Thanks for this! 

Can you please add a test to confirm that the tag's name is not updated in the personal tags list of an existing participant?

**Comment by Alys** [comment]
Unless that test already exists. :) Sorry, I'm not on a good computer so I can't check.
It looks like one test related to tag names is failing, so that might be it. Can you look into that test failure and see if anything in the code needs to be changed? If that failing test is for something else, then a new test for the participant's tag list will still be needed.

There's also a second test failure related to group plans, but you can ignore that. I can't see any reason it could have been caused by this PR.

**Comment by VickyKoblinski** [comment]
Sure, I'd be happy to! :)

**Comment by VickyKoblinski** [comment]
Status update: I'm on vacation right now but I'll be sure to get back to this when I get back next week.

**Comment by paglias** [comment]
hi @VickyKoblinski ! any update on the status of this PR? thanks

**Comment by paglias** [comment]
Hi @VickyKoblinski , I'm going to close this one but leave a message if you want to work more on it

**Pull request closed without merging**
