### PR TITLE
Fixing misspelling and inconsistent punctuation in the api doc

### PR DESCRIPTION
**Pull request by JacobFrericks**
### Changes
Fixing misspelling and inconsistent punctuation in the api doc 

----
UUID: 6c4ef2c1-2ae1-41a4-85cc-35228c926366

### CODE REVIEW

**Comment by JacobFrericks** [comment]
build failed with the following:
```
1) payments - stripe - #subscribeCancel
       success
         cancels a user subscription:
     ENOENT: no such file or directory, stat '/home/travis/build/HabitRPG/habitica/dist-client/index.html'
  
  2) payments - stripe - #subscribeCancel
       success
         cancels a group subscription:
     ENOENT: no such file or directory, stat '/home/travis/build/HabitRPG/habitica/dist-client/index.html'
```

This is a simple PR that didn't change any code. Is this expected?

**Comment by paglias** [comment]
@JacobFrericks the errors are unrelated, thanks for noticing them, they should be fixed now

**Comment by JacobFrericks** [comment]
@paglias Thanks! How do I kick off the build again?

**Comment by paglias** [comment]
@JacobFrericks I've restarted it!

**Comment by paglias** [comment]
Actually the build will fail again because your branch is not up to date with `develop` but don't worry, we know it's unrelated

**Comment by SabreCat** [comment]
Thanks for this, @JacobFrericks, and welcome to the ranks of the Blacksmiths at tier 1!

Note that further contributor tiers require increasing amounts of effort from one to the next, so tier 2 will require multiple PRs or a larger PR to attain. But keep helping out and we'll express our gratitude accordingly!

**Pull request merged**
