### PR TITLE
Update modules where possible and remove unused modules from package.json

### PR DESCRIPTION
**Pull request by paglias**
- [x] Update Express from 3.5.x to 3.17.x with code for breaking changes
- [x] Upgrade Moment from 2.4.x to 2.8.x with code for breaking changes
- [x] ~~Use npm version of paypal-express-checkout as changes in fork are there too now~~ Reverted
- [x] Specify version for nconf
- [x] Upgrade other packages without breaking changes
- [x] Remove unused packages
- [x] Update .nodemonignore
- [x] Update jade with code for breaking changes

Not done:
- nodemailer newest version is a complete rewrite, needs more work
- stick to stripe version
- coffee-script might require changes when loading .coffee files from node, so not updated for now
- ui router
- update angular 1.3 version and fork bindonce because currently does not work
- bower dependencies
- do the same on shared

### CODE REVIEW

**Comment by paglias** [comment]
I would like to get this merged as is with , will continue with the other items later but it's a quite good cleanup of the modules. I especially like Express, Async and Moment upgrades because they contain a lot of fixes. I've done some basic testing but it's impossible to test everything so if we could set it on beta for a week or so

@lefnire

**Comment by paglias** [comment]
Goes with https://github.com/HabitRPG/habitrpg-shared/pull/326

**Comment by lefnire** [comment]
great, yeah we're way behind on modules aren't we. I'll get this on beta and bet back to you. Don't know if you saw the other PR with upgrade to express 4.x, been meaning to tackle it but I haven't had time - might be food for thought here?

**Comment by lefnire** [comment]
pushing to beta now

**Comment by lefnire** [comment]
hmm, push failing with https://gist.github.com/lefnire/8325f9d63f8cb282e061 . I'll look into tomorrow

**Comment by paglias** [comment]
Mmm... Seems the blocking one is winston-mail incompatible with Winston
0.8, we have to update it to 0.2.9 and should work. Will do when come back
this afternoon unless someone does it before me. As for express 4.0 will
give a look at the existing pr and try to merge/update it if it works. But
at least this way we get a ton of bug fixes with almost no change in the
code

hmm, push failing with https://gist.github.com/lefnire/8325f9d63f8cb282e061
. I'll look into tomorrow

**Comment by paglias** [comment]
~0.2.7 should match 0.2.9 anyway... Mysteries of npm
Il 03/ott/2014 02:32 "Tyler Renelle" notifications@github.com ha scritto:

**Comment by lefnire** [comment]
Cool, I'll update to 0.2.9 tomo and give it a whirl!

**Comment by paglias** [comment]
@lefnire specified winston-mail version and rebased, I tested from scratch on my machine and it installs correctly (remember that it goes with https://github.com/HabitRPG/habitrpg-shared/pull/326)

**Comment by lefnire** [comment]
on beta now! also, your payments.js stuff is on prod (i've tested it and am monitoring for errors), and the tags fix is launched

**Comment by paglias** [comment]
@lefnire rebased and fixed the only error I noticed on NR regarding the static/api page. Of course on beta we don't test everything because only a few people use it nowadays but I think we can merge and move to prod

**Comment by lefnire** [comment]
I agree, merging

**Pull request merged**
