### PR TITLE
Special message when complete all check-in prizes

### LINKED ISSUE #8573: Check-in prize when you have all available prizes should have a special message
_edit by Alys 2017-03-25:_

_The original bug report here by Qchristensen is below but has also been copied to the Android repo at https://github.com/HabitRPG/habitica-android/issues/732 - all work on the Android bug should be recorded there. The iOS version is at https://github.com/HabitRPG/habitica-ios/issues/447.  This issue is now for related changes to the website version of the check-in message._

On the website, when you have received the final check-in prize available so far, you are shown the modal in the screenshot below. It should have an additional message on it saying:
**"You have received all the Check-In prizes currently available! More will be added in the future."**

Note though that at some time in the future, we will stop adding new check-in prizes (ref: [Lemoness's comment below](https://github.com/HabitRPG/habitica/issues/8573#issuecomment-288570486)) and at that time the message will need to be changed, and we'll need a reminder about that.

So the actions needed for this issue are:
- [ ] Add a string to `website/common/locales/en/loginIncentives.json` containing the new message ("You have received all the Check-In prizes currently available! More will be added in the future.")
- [ ] Display that string on the modal below, probably just above the "Awesome" button but only when the user has received the last prize currently available.
   - The code that defines the prizes is in https://github.com/HabitRPG/habitica/blob/develop/website/common/script/content/loginIncentives.js -- i.e., you can use that content data and the user's `user.loginIncentives` count to determine if the user has just been given the final prize.
- [ ] Add this code comment to `website/common/script/content/loginIncentives.js` just below [this line](https://github.com/HabitRPG/habitica/blob/0ec293bd158a17e9c9f3763715fde22ad99d5080/website/common/script/content/loginIncentives.js#L227):
      `// When the final check-in prize is added here, change {string name} in website/common/locales/en/loginIncentives.json to say "You have received the final Check-In prize!". Confirm the message with Lemoness first.`
   - [ ] Replace {string name} with the name you chose for the string.
- [ ] Edit [this line](https://github.com/HabitRPG/habitica/blob/0ec293bd158a17e9c9f3763715fde22ad99d5080/website/common/script/content/loginIncentives.js#L229) in loginIncentives.js to fix the two "reference" typos (refence and refernce) if they haven't already been fixed by then. :)

image

----

_This is the original bug report by Qchristensen but it's being handed in the Android repo, not here, since it's for the Android app:_

  * Browser: Android App
  * OS: Android

When I checked-in for the 95th day in a row, I got a check-in prize (yay, go me!) and at the bottom, it informs me my next check-in prize will be at 0 days.  Expected behaviour is that the next prize would normally be at 100 days.  Screenshot attached:

[screenshot_20170316-062823](https://cloud.githubusercontent.com/assets/15902216/23997545/ce11870a-0aa5-11e7-95bd-cacd14e58983.png)

### PR DESCRIPTION
**Pull request by Yutsuten**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #8573 

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
Added a special message to the last check-in prize, and other small code modifications as requested in the issue (#8573).

LastReward

[//]: # (Put User ID in here - found in Settings -> API)

----
UUID: 203f208a-e0f0-4442-bf16-d4f19e553e8a

### CODE REVIEW

**Comment by TheHollidayInn** [comment]
Looks good to me.

**Comment by TheHollidayInn** [comment]
Test:
 - Pulled locally
 - Set user to loginincentive 99 (1 before max)
 - Use debug menu to add one day
 - Refreshed
 - Saw new message

**Comment by paglias** [comment]
@Yutsuten can you fix the conflicts on this one so we can merge it?

**Comment by Yutsuten** [comment]
Fixed the conflict!

**Comment by paglias** [comment]
Thanks, noted towards your next tier

**Pull request merged**
