### PR TITLE
Backer-Only Shop Sprites

### PR DESCRIPTION
**Pull request by Shaners**
Update to the shop sprite sheet to include the backer only gear. Ice armor and helm to be added later.

I was going to do the CSS as well but didn't know if you want it to live in the same place as the other shop items or not and figure it's really simple code anyway.

### CODE REVIEW

**Comment by Shaners** [comment]
The timing adjustments may appear a little slow since we're focused on them while implementing but I think better for prolonged long term exposure. They'll probably be adjusted again at some point.

Expanded the backer-only pet size a bit since it had a zero border, think this may help with cramping a bit.

**Comment by Shaners** [comment]
Noticed that my new box size sprite sheet was missing some assets. I guess we are using male_sprites.png /.css and female_sprites_png / css and not player_sprites.png? Are we planning on sticking with that separated method?

**Comment by lefnire** [comment]
absolutely. beautiful. and I'm glad you brought up player_sprites, I completely forgot about that change! Sorry @Pandoro :/ I'll do that move in tandem

**Comment by Shaners** [comment]
@lefnire where are we at with the move to @Pandoro 's player_sprites.png / css? I think this needs to be done before we can try the move to a 105x avatar box and integrating Lemon's new player hair customizations.

**Comment by lefnire** [comment]
Ok, I'll move this up in priority. Hopefully within the week

**Comment by Shaners** [comment]
Yea not to be a jerk but there are a few things dependant on this move and any errors that may arise from it. I wouldn't want to put effort into male_sprites and female_sprites and then have to do it again for player_sprites.

**Comment by lefnire** [comment]
duly noted. Got some server crits & other bits to hit asap, then I'll move directly into this

**Pull request merged**
