### PR TITLE
Implemented new Achievement and Badge: Joined a Challenge (Fixes #8613)

### LINKED ISSUE #8613: New Achievement and Badge: Joined a Challenge
A new achievement and badge are ready to be implemented! This should be received when a player participates in their first Challenge. The badge image and the name/mouseover text for the user achievement page can be found here: 

https://trello.com/c/rBBuCJWR/2-joined-a-challenge-badge

### PR DESCRIPTION
**Pull request by kvsm**
Fixes #8613

### Changes
Added new achievement 'Joined a challenge' as per #8613 
Added integration tests and fixed broken tests

The achievement is awarded if a user does not currently have the achievement and joins or creates a challenge.

----
UUID: 176cc46d-af71-4a98-a89b-8bc4babfbaf5

### CODE REVIEW

**Comment by kvsm** [comment]
Just occurred to me - should I change this so it's awarded retroactively too?

**Comment by Alys** [comment]
@kvsm I suggest not. If we decide to award it retrospectively, we can do that with a once-off migration script and we already have scripts that we can modify for that. But thanks for asking!

**Review by TheHollidayInn — APPROVED** [review]
Works for me. 
1. I created two separate accounts
2. With one account, I created a challenge, received the pop up and the achievement
3. With the other, I joined a challenge, received the pop up and the achievement

**Comment by kvsm** [comment]
Resolved merge conflicts.

**Comment by SabreCat** [comment]
Looks good to me too! A question for @lemoness: when this one goes live, should we run a migration to award the achievement to anyone who is currently part of a Challenge or who has won a Challenge in the past? Or shall we leave this to go only to users who join Challenges going forward?

**Comment by SabreCat** [comment]
Actually, just checked with @beffymaroo offline, and she says yes. We'll do some db updates when this goes live!

**Comment by SabreCat** [comment]
Noted toward your next tier. Blacksmith 2 is not far off for you, methinks! Thanks much for contributing!

**Comment by kvsm** [comment]
Thanks! :)

Though I already have blacksmith 2. ;P

**Comment by Alys** [comment]
@kvsm Thank you for telling us! I've adjusted your tier notes to make this one count towards your future tier 3.

**Pull request merged**
