### PR TITLE
#3534 - Rewards: Broken layout when the text is too long.

### PR DESCRIPTION
**Pull request by rcichy**

### CODE REVIEW

**Comment by deilann** [comment]
Awesome! I know nothing about CSS, so I'm not gonna touch this one. @benmanley , you da man?

**Comment by rcichy** [comment]
I attached a screenshot. https://github.com/HabitRPG/habitrpg/issues/3534#issuecomment-46087272

**Comment by lefnire** [comment]
Thanks! UUID? (also, this work for larger vals like 160GP?)

**Comment by rcichy** [comment]
231a2c9e-6001-417e-a5ea-83bc9562536e

No, #1993 still not solved.

**Pull request merged**
