### PR TITLE
antidote display and functionality

### LINKED ISSUE #9758: antidotes for avatar transformation buffs should not allow multiple purchases (salt, etc)
When a [Transformation Item](http://habitica.wikia.com/wiki/Transformation_Items) such as Snowball is used on you, the antidote (e.g., Salt) appears in your Rewards column to buy with gold. That works correctly, however the buy modal gives you the option to buy multiples, which isn't helpful and will be confusing (e.g., makes the users think they can store salt for use later). 

The buy modal should not have the text "How many would you like to buy?" or the field for selecting a number.

I'm labelling this as high priority since people will be using it a lot at the moment.

### LINKED ISSUE #10160: Transformation Item Antidotes do not work
I'm seeing reports of this in both staging and production, and so far it's been confirmed for at least Shiny Seeds and Spooky Sparkles.

When one goes to purchase an antidote, one is able to buy multiples which may not be desired behavior since those items were instant use. Upon purchasing any amount of them, no gold is deducted and my avatar is not un-transformed. This persists upon refresh or reload.

### PR DESCRIPTION
**Pull request by negue**
based on #10171, thanks to @CalebFung

fixes #9758 
fixes #10160

### CODE REVIEW

**Comment by SabreCat** [comment]
Looks pretty good! Just one issue, fairly minor: you can attempt to pin the antidote item in Rewards, which doesn't work (correct, shouldn't be able to pin), but it throws a strange error, `The item type "" is not valid.`

Should either (preferably) not show the pinning UI element at all, or (if that's not feasible) give a more informative error message like "This item is temporary and cannot be pinned."

**Comment by caleb-fung** [comment]
@SabreCat I will take a look at it as soon as I can. I wasn't sure if @negue was wrapping this up. 
Are there any other features you wanted added/removed?

**Comment by SabreCat** [comment]
@CalebFung Not to worry, @negue should be on it from here!

**Comment by caleb-fung** [comment]
Okay, thanks for letting me help out! This is my first contribution to the Habitica repo. 
I hope to submit more thorough fixes in the future.

**Comment by SabreCat** [comment]
@CalebFung Normally it's not a problem to have some back and forth during review, and to take a few days to implement each round of fixes. This was an unusual case!

**Comment by paglias** [comment]
The problem mentioned by @SabreCat has been fixed so I'm merging

**Pull request merged**
