### PR TITLE
Add Additional Skin Tone Options

### PR DESCRIPTION
**Pull request by Shaners**
https://github.com/HabitRPG/habitrpg-shared/pull/22 needs to be completed first or in conjunction with this pull request.

Adds 3 new skin tones as options. Rearranges the current options. Adjusts the shirt colour choice to fit the other customization options.

New skin colours are roughly named by their hex value.

### CODE REVIEW

**Comment by lefnire** [comment]
hold off on this merge, the repo got pretty broken and many of the commits in here came from that breakage. We're going to need to `rebase -i` this branch, remove the onduhray commits. Or you can copy/paste in your changes manually on a fresh branch. I'll tell you more in a bit

**Comment by lefnire** [comment]
ps, for future to avoid this, don't `git merge` into your branch. Use `git rebase develop` instead. develop -> feature-branch = rebase, feature-branch -> develop = merge. Read [this comment](https://github.com/lefnire/habitrpg/pull/1558#issuecomment-25209580) for more details. I'll help you out if you have rebase troubles (it took me a while to figure it out)

**Comment by Shaners** [comment]
Aye aye, will fix.

**Comment by lefnire** [comment]
let me know if you decide to go the `rebase -i` route & need my help. 'course, if you do the copy/paste into a new branch method, you won't need me

**Comment by Shaners** [comment]
I should be able to figure it out. Good opportunity to learn about rebase.

**Comment by Shaners** [comment]
@lefnire Sadly it was a bit too much for me and I didn't want to go through the 134 commits for the rebase I was unsure I was doing correctly... So I just blew things up, reforked, and copy pasted. I think I am going to try and use git daily so I can get a better understanding of all this.

**Comment by lefnire** [comment]
copy/paste method is a totally legit. Heck, produces a cleaner commit anyway.

**Pull request closed without merging**
