### PR TITLE
Removed Challenge Tag Maxlength 

### PR DESCRIPTION
**Pull request by Arodang**
PR for issue #4186 - Removed the challenge tag maxlength limit and changed the field size of Tag and Prize to [col-sm-12](http://i.imgur.com/KDXVlBF.png), [col-md-6](http://i.imgur.com/pZkNjQY.png), [col-lg-6](http://i.imgur.com/rHgMvUX.png). 

This is my first contribution to this project (and my first PR ever!). Please let me know if I did anything wrong or if anything needs to change to fit your styling requirements, etc!

### CODE REVIEW

**Comment by crookedneighbor** [comment]
The `col-lg-6` class shouldn't be necessary since `col-md-6` is defined. The viewport for `lg` inherits from `md` if no `lg` class is specified.

**Comment by Alys** [comment]
@Arodang Could you please include a screenshot of what it looks like now? That will help Lemoness and others comment on it (no need for them to run up their own local install to review it).

**Comment by Arodang** [comment]
Large screen - http://i.imgur.com/rHgMvUX.png
Medium screen - http://i.imgur.com/pZkNjQY.png
Small screen - http://i.imgur.com/KDXVlBF.png

**Comment by SabreCat** [comment]
Looks good! The change will be live soon. @Arodang, this will count toward a contributor tier! What's your Habitica User ID (from Settings > API)?

**Comment by Arodang** [comment]
Thanks! Glad to see this go through :)
My User ID is 5b42a38e-abdb-4424-ae9c-ec7de43e20b9

**Comment by SabreCat** [comment]
@Arodang: Tier awarded! Note that while your first tier is easy to get, further tiers require increasing amounts of effort from one to the next, so another PR of this scope may not bump you to 2. But keep helping out and we'll express our thanks accordingly!

**Pull request merged**
