### PR TITLE
Added Farvoid Theme

### PR DESCRIPTION
**Pull request by SalethiNat94**
### Changes
*Added audio files and modified relevant files to add Airu's Farvoid Theme. [Here's a link to the audio files used](https://drive.google.com/file/d/0B5o5vJHYPmPLS19qTzJRaHZHMkE/view) (May require RAR opening software to view)

I discovered an issue while testing this theme - The Daily and Level_Up sounds won't play on Chrome, but would play perfectly fine when testing the local install on a different browser such as Firefox or Internet Explorer. Does anyone know what might be causing this?

----
Audio theme created by Airu (UUID: 8c798ac6-17a0-4b0c-9e5b-a33ba5fa1870)
Submitted to GitHub by Pizilden (UUID: 7a1b0a51-0221-4542-b09f-c5e27ba83f31)

### CODE REVIEW

**Comment by negue** [comment]
I had the same issues with the files:

- Daily
- Level_Up 

Once I deleted the `.ogg` the `.mp3` loaded instead and this worked properly.

I'm don't know much about the ogg files but maybe something happened during the export as ogg?
@Airu216 could you re-export / -encode those again ?

**Comment by Airu216** [comment]
Noted, thanks for reviewing it.

**Comment by Airu216** [comment]
https://drive.google.com/open?id=1mKFpBL7hSbx5WNlNVHzcXVQtGNmrhrzj

I uploaded a rar file containing the recoded ogg's one set with the same program done again and another with another program. Hope it works this time. Audio plays fine on its own but I'm not sure if it will on the website. Thanks pizilden and negue. I appreciate your help :))

**Comment by SalethiNat94** [comment]
I'm just gonna go ahead and create a cleaner branch for this theme too, since it'll take care of updating it with the changes in /develop

**Pull request closed without merging**
