### PR TITLE
ICS exportation

### PR DESCRIPTION
**Pull request by ozziefallick**
Ported ICS exportation into API v2, as discussed in issue #1485 and #1488.

### CODE REVIEW

**Comment by colegleason** [comment]
Hey, just curious, did you update the CHANGELOG on purpose?

**Comment by ozziefallick** [comment]
No, I didn't. Since it happened automatically and I don't know anything about it, I decided to just leave the changes in. Should I take them out?

**Comment by colegleason** [comment]
No thats fine for now. Something is going on that I need to debug.

On Fri, Jan 24, 2014 at 2:28 PM, J. Ozymandias Fallick <
notifications@github.com> wrote:

> No, I didn't. Since it happened automatically and I don't know anything
> about it, I decided to just leave the changes in. Should I take them out?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/pull/2549#issuecomment-33257750
> .

## 

## Cole Gleason

Student, University of Illinois at Urbana-Champaign
Email: cg@colegleason.com
Website: colegleason.com

**Comment by lefnire** [comment]
@ozymandiasthegreat I couldn't get this working. Looks like user isn't being passed to the route, because `auth.auth` isn't one of the middlewares. See some of the other routes for an example, they have `auth.auth` at the beginning of the process, which sets `res.locals.user` for later use (a dependency of this feature). 

However - since we're gonna be requesting `/calendar.ics` as a GET request from a link, not an AJAX call, we're probably not going to be able to use `auth.auth` anyway. Instead, we'll need to use something similar to the dataexport routes. See [dataexport](https://github.com/HabitRPG/habitrpg/blob/f26cb2abf3ff906cc5af23e4fc67a15ecbb38a93/src/routes/dataexport.js) examples.

If this is something that makes your head spin, let me know and I'll take care of this. You've gotten this PR pretty near complete, just needs a bit more - and I don't want to hinder the process if that last stretch is a pain for you

**Comment by ozziefallick** [comment]
I'll take a crack at it when I get a chance. That may be a while, sadly, so if you'd rather do it yourself, I don't mind.

**Comment by ozziefallick** [comment]
It looks like it would be best for me to pass off responsibility for this. I just have too many things competing for my attention right now. Sorry!

**Comment by Alys** [comment]
I'm closing this because recent site changes have made this too conflicty, but I've noted it in https://github.com/HabitRPG/habitrpg/issues/1488 so we can find it easily to continue this work. Thanks @ozziefallick!

**Pull request closed without merging**
