### PR TITLE
Market (not working)

### PR DESCRIPTION
**Pull request by paglias**
The market is almost complete but I get an error when I try to update `user.balance` on the server using `User.log` it complains about `user.balance` being a protected path.

schermata del 2013-09-05 15 33 22

The `500` error is displayed only on the server's console, in the browser the return code is `200`.

---

In the screenshot above the server complains also about `items.eggs` being an object (it happens every time I try to update items.eggs/pets/hatchingPotions) but anyway the database is updated correctly.

The problem here is that `items.eggs` is an array not an oobject;

schermata del 2013-09-05 15 32 33

And indeed if you look at the database is correctly saved as an array.

---

After that someone solves the problem above, before merging, double check that the gems's number is correctly updated immediately by angular and not after the batch update is returned from the server. It may be needed to add something like:

`User.user.balance = (gems - item.value) / 4`

### CODE REVIEW

**Comment by lefnire** [comment]
That error is completely benign. The reason I put it in there was to warn us developers to move more towards adding op-based API routes (like `/api/v1/user/market/buy`, `/api/v1/user/pets/select`, etc), and to move _away_ from using `{op:set}` as often as possible, since it's not RESTful, and is potentially dangerous.. I don't think we need to worry riht now, we should probably deal with that later - after we release to production. 

Is this error actually showing up as a red notification to the user? If so, I'll fix it. If not, let's just ignore this and feel free to merge

**Comment by paglias** [comment]
No red notification but I can't get `balance` to be saved in the database.

**Comment by lefnire** [comment]
Oh right! Yeah, `user.balance` is a protected path from `{op:'set'}` so people can't add gems if they know the API route. So looks like we're gonna have to add a new route after all, maybe a general `/api/v1/user/buy`. Check out `src/controllers/user.js:api.reroll()` for an example. Also needs to be added to `/src/routes/api.js`. 

I can do it m'self if you prefer, but can't get to it till tonight.

**Comment by paglias** [comment]
I'll give a look to it. `/api/v1/user/buy` exists but it is for items that can be bought with GPs, I think another one is needed, any suuggestion? `buy-gems` also is already used for stripe payment

**Comment by paglias** [comment]
Also I think we should set this router to allow only gems reduction or anyone will be able to add more gems to his account...

**Comment by lefnire** [comment]
Maybe `/api/v1/user/market/buy`? Or maybe just `/api/v1/market/buy`? Hmm.. we eventually want users to be able to "gift" purchases to other users. In which case 2 might be better?  yeah, let's do no 2 since "market" isn't an actual attribute on the user resource, so it doesn't much make sense. And we'll eventually add the `/api/v1/market` route for read-only list, non-user-specific

Yeah, and it should definitely only allow gem reduction

**Comment by paglias** [comment]
It affects groups creation also, I think siince the code uses User.set. I'll give a look to everything in a few hours.

The fastest way would be to create a route which only decreases user's gems and then create the group7buy an egg but that is not exactly the safest solution, ie the server crash after the gems have been decreased but before the egg is "bought..." or maybe not since it should be updated next time server works from localstorage.... Let me know what do you prefer. A complete route would be longer to develop

**Comment by litenull** [comment]
Only one note.
Dont use localstorage. These ops should be calculated server side.

Create a unified route for each feature (groups, market).
We shouldnt cache money-related API ops. These should be direct, and should trigger user fetch AFTER the call is done and succesful.

**Comment by paglias** [comment]
Yes Yes. I meant if we used two routes one for decreasing gems (no local
storage) and the other for buying the item and the server crash after the
first router you'll have less gems but no item. In that case since were
using local storage for the second op it will update the user from local
storage when server is up, right?

**Comment by litenull** [comment]
I'm saying lets make one unified route (decreasing gems, and add the item to user), and then return success.
Caching those ops is a security breach.

**Comment by paglias** [comment]
OK but then we should protect also items.pets, eggs and potions and will be
long

**Comment by lefnire** [comment]
(edited post):
Separate routes for separate purchasing actions. They perform different logic, and the _purchasing_ part is simply `user.balance-=NUMBER`, so no need to DRY that. `/api/v1/groups`  will decrease gems and create a guild. `/api/v1/market/buy` will decrease gems buy an egg . It's pretty easy to make these atomic operations:

``` coffeescript
# POST /api/v1/groups
group = new Group({...})
async.series [
  (cb) -> group.save(cb)
  ,(cb) -> user.balance--,user.save(cb)
], (err, results) ->
  return res.json(500,{err}) if err
  res.send(results[0])
```

or

``` coffeescript
# POST /api/v1/market/buy (req.body or req.query will contain info on item)
user.items.eggs.push(...)
user.balance--
user.save (err, saved) ->
  return res.json(500,{err}) if err
  res.json(saved)
```

If group.save fails, user never loses balance. If user.balance-- fails, group-creation goes through - but that's fine IMO. But yeah, no localStorage on this one 

Note the second route returns the saved user. ngResource will automatically populate the UI with the updated user, including his new pets.

**Comment by paglias** [comment]
We could start returning only the necessary information if that is not
going to conflict with ngResource.

Also if you plan to wait for the response from the server we should
introduce a loading spinner, even thought I would like to continue not
waiting for the server response and in case of a rare (very rare) error we
can send an alert advising to refresh the page.

**Comment by litenull** [comment]
@lefnire yep, that's what I meant. You're reading my mind lol.
@paglias The 'update in advance, return if fails' technique can be used with 90% of the features in-app, but not with money-related stuff. IMO.

**Comment by lefnire** [comment]
Yeah i was thinking the same. If you look at Guilds & Tavern, I have a load spinner waiting on http response - but the best thing would be an $httpProvider interceptor that adds a load spinner _any_ time we're waiting on data (I think.. do you agree? any issues we can think of here?). There are some tutorials out there for adding such a thing. Alternatively looks like there's a [module for it here](https://github.com/lavinjj/angularjs-spinner), but I haven't explored it.

@paglias ngResource ties the resource object of the UI to the api route as an object, we may have to rethink how we're using it to cut back on data transfer. So groups for example. We're using ngResource with groups, and if `group.$save()` is ever called - if it doesn't return the full group object, it will delete the group from the UI since they're tied together. ngResource forces you to bid by proper REST protocol, which (evidently) requires returning the full saved object for edit & create. So we may have to rethink how, or whether in general, to use ngResource. (did that paragraph make any sense?)

**Comment by paglias** [comment]
About ngResoruce it seems that it will update the resource with whatever is returned from the server only in case the response has a body (http://stackoverflow.com/questions/15192511/why-is-ngresource-modifying-saved-object-to-this-g-0-o-1-k-after-r). We should return the full object on resource creation (POST) but nothing except the http code on resource update (PUT), which I think it's quite standard in RESTful APIs.

About user object since it isn't a ngResource we already said that we can use `_v` to see if the user was modified in the meantime and return something in the server response only that case.

The loading spinner we actually use is ok for a first load but it's quite intrusive for smaller updates. And I don't think we will need it many times more than now.

The usual behavior should be to update the model on the client immediately and return nothing from the server unless there's an error.

For the market and the gems route I would leave this to you unless you don't have time.

**Comment by lefnire** [comment]
Got it. That all sounds pretty accurate to me!  Ok cool, I'll add in the route tonight (should be a quickie). Thanks @paglias !

**Comment by paglias** [comment]
@litenull I agree for real money (ie stripe payment) but see no difference when _trading_ gems, in the rare case of error send an alert, waiting for the server response will not give any safety. Unless... no ok there's a problem with my approach, if we do not wait for server but update localstorage anyway in case the server fails the op the next time it will be updated from localstorage. We should have a way to wait before saving to localstorage, update local model but no localstorage.

In general personally I love the approach used by batchUpdate wich exec the right operation on the server. But I see that you wanted to move away from that approach. Do you plan to stop using it? Moving to something more RESTful also for the user would be cool if used wiith ngResource.

**Comment by lefnire** [comment]
Yeah, I think we want to move to a more RESTful approach over time (it could be a long ways away, since User.log() is so engrained in our apps). If we do get rid of batch-update, we'll want to still allow for some mechanism for batching updates since it's needed for offline usage on the mobile app. We could handle all batch stuff on the client, just store a list of REST calls to send and then send them to individual API routes one-by-one. The downside here is simply performance / scalability, we're gonna be sending / receiving a lot of data. But your'e right - it lets us tie into ngResource properly.

Wait - we should be using ngResource on the user! I just realized, we're doing _.extend(user, data) - I'm not sure how ngResource compares in performance to _.extend (when it gets back a saved object), but it could be significant.

Anyway, sorry for that tangent. If we decide to _keep_ /batch-update, I think we should modify it so it's more consistent with the other API routes. So instead of the current

```
[{op:'set',data:{..}},
{op:'reroll',data:{..}]
```

it should be direct mappings to API resources like

``` javascript
[{method:'POST', action:'/api/v1/user/reroll', body: {..}, params: {...}, query: {...},
{method:'POST', action:'/api/v1/user/pets/select', body:....}
```

That way we can get rid of all the logic in the batch-update route, and simply redirect every item in the array to their respective express routes based on the information provided.

Maybe we should have a vote on this:
1. Keep batch-update but make it more consistent
   - Pros: performance / scale, easier with current setup, offline usage
   - Cons: pretty wack by API standards, won't play with ngResource
   - Easy to forget to fix the real API route and instead fix batch-update, since we're not usually consuming the former
2. Kill batch-update and use proper REST
   - Pros: plays with ngResource, we're forced to create a proper REST API
   - Cons: we'll have to build a batching mechanism to support offline usage without killing data transfer perforamnce

**Comment by litenull** [comment]
I dont have the time to read all your convo guys, but to answer @paglias 

If the API is down, gem decreasing ops could queue in localStorage, potentially leaving there dozens of decrease ops. This is too dangerous. If we enable gem-trading ONLY when API is online, and returning data, we scrap the whole 'out-of-sync' issue when dealing with gems. We should be really careful with gems and money.

**Comment by paglias** [comment]
@litenull Yes you're right, I agreed with you some post before in this thread when I realized that there could be serious problems when using it offline. What I would like to know is if you want the only-online approach only for gems or also, for example, when hatching a pet.

**Comment by lefnire** [comment]
Good chat guys :) I'm gonna have bookmark this convo for a future whiteboarding session, some good stuff in here. Anyway, I'll add the buy route & push this market stuff up - thanks @paglias

**Comment by lefnire** [comment]
note to self on loading-interceptors: http://chieffancypants.github.io/angular-loading-bar/#

**Pull request merged**
