### PR TITLE
add top margin on all modals to prevent overlap with nav/messaging - fixes #10475

### LINKED ISSUE #10475: Modal positioning wrong in specific cases
From Report a Bug:

> Charlie (41fa2ec5-0f75-4b52-9038-4209eb9fe5ac) 
> @shanaqui I worked out how to reliably reproduce the z-index issue. It looks like it is only caused by a certain set of steps. If I click help (https://habitica.com/static/faq) then the habitica logo on the menu bar then the modal always sits lower than the menu until I reload all assets (CSS, etc) with a Ctrl+F5/Ctrl+R Screenshot: https://imgur.com/a/0xa1Y88

I've confirmed this myself.

image

### PR DESCRIPTION
**Pull request by flhat**
Fixes #10475

### Changes
- Added 100px top margin on all modals to prevent overlap issues with the nav and message banner

screen shot 2018-08-24 at 9 34 12 pm

----
UUID: 495eed5c-2828-4e24-a19d-755ac5e95295

### CODE REVIEW

**Comment by paglias** [comment]
@BlkStormy thanks, can you post a screenshot of how this looks without the "checked into the inn" blue banner? Would it be possible to apply the extra margin only when the banner is present?

**Comment by negue** [comment]
This way all modals would stay at the same position. 

@Tressley what do you think?

Avatar Modal checked into the inn:
avatar modal checked into the inn


Avatar Modal without:
image

**Comment by Tressley** [comment]
Is there a reason we can't have the modal positioned in the same spot relative to the navigation? I am not a fan of how the modal overlays the navigation when the user is checked into the inn.

**Comment by negue** [comment]
@BlkStormy could you try the idea I mentioned in
- https://github.com/HabitRPG/habitica/pull/10513#issuecomment-404268215
- https://github.com/HabitRPG/habitica/pull/10513#issuecomment-404568554

**Comment by flhat** [comment]
Sorry for the radio silence on this, I was gone for a few days.  I've made the update and I think this works well:

screen shot 2018-08-30 at 1 44 06 pm

screen shot 2018-08-30 at 1 44 18 pm

**Comment by Tressley** [comment]
I think this is the right fix.

**Comment by paglias** [comment]
Hi @BlkStormy thanks for the help here, I just tested this locally and while it works in some situations there are still some problem, in particular:

1. As mentioned in the comments linked by @negue (https://github.com/HabitRPG/habitica/pull/10633#issuecomment-417361160) the .restingInn class is only applied to the menu and header, so this change only affects modal that are defined inside the header/menu of the website. For example if you go to the market while resting in the inn and try to buy an item you'll see that the modal isn't positioned correctly
2. This is less important and not a big deal if you can't find the source but if you follow the instructions to reproduce the bug at the top of https://github.com/HabitRPG/habitica/issues/10475 you'll see that even with your fix the modals seem to be positioned behind the app menu, so when you scroll them they disappear behind the menu

**Comment by flhat** [comment]
@paglias Got it - I ended up backing out the margin changes and updating the z-index on modals.  The scenarios that I've seen so far all check out on this end.

**Comment by paglias** [comment]
schermata 2018-09-04 alle 12 23 19
schermata 2018-09-04 alle 12 23 29

^ This is how it looks now.

So the issue with the modal being under the navigation is fixed, although I think @Tressley wanted to have all the modals start a bit lower?

**Comment by Tressley** [comment]
Yeah, the modals need to be lower. They should be roughly ~48px from the bottom of the navigation.

**Comment by paglias** [comment]
Any update on this one?

**Comment by paglias** [comment]
Closing for lack of updates

**Pull request closed without merging**
