### PR TITLE
Update README.md for better grammar

### PR DESCRIPTION
**Pull request by Yeah-Jack**
### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
Improved the grammar in GitHub README.

### CODE REVIEW

**Review by MM1132 — COMMENTED** [review]
If I had the power within me, I would APPROVE this amazing Pull Request :)

**Comment by CuriousMagpie** [comment]
Looks great, @Yeah-Jack! If you'll let us know your UUID or username, we'll give you Blacksmith contributor tier.

**Comment by Yeah-Jack** [comment]
Aww, that's nice. My UUID is: 17136e56-89aa-4931-bb49-687debb38150

**Comment by MM1132** [comment]
> Looks great, @Yeah-Jack! If you'll let us know your UUID or username, we'll give you Blacksmith contributor tier.

What's a blacksmith contributor tier though? When I hear things like that, my instant thought is "Woah I want to be part of this too". If you understand :)

**Comment by CuriousMagpie** [comment]
You get an icon next to your name--the shape changes to match which tier you have. And for tier 1, you also get 3 gems. 😄 
Screenshot 2024-04-26 at 1 20 04 PM

However, the higher the tier, we like to see more substantial contributions (we have lots of open issues!).

**Pull request merged**
