### PR TITLE
Cron does not count days with all-grey dailies as perfect

### LINKED ISSUE #2565: "perfect day" is awarded if all Dailies are unticked Grey Dailies, or there are no Dailies
If you have no Dailies or all your Dailies are greyed out because none are set to be actioned that day, then you get a "perfect day" achievement, even if you didn't tick off any Dailies at all.

You also get a Perfect Day if you use Stealth to avoid all Dailies.

There's a proposed fix at https://github.com/HabitRPG/habitrpg/issues/4535 but it hasn't been tested and it's very old now. 
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/1385942-perfect-day-is-awarded-if-all-dailies-are-unticked-grey-dailies?utm_campaign=plugin&utm_content=tracker%2F68393&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F68393&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by khipkin**
Fixes #2565 
### Changes

Cron only counts days as "perfect" if at least one daily was due.

### CODE REVIEW

**Comment by crookedneighbor** [comment]
I have mixed feelings about this. I _think_ I agree that someone shouldn't get a perfect day achievement for not doing anything in a day, but if a user doesn't have any active dailys on a particular day of the week, should they lose their perfect day buff?

IE, I have active dailys on M,T,R,F and no active dailys on Wednesday. I finish all my due dailys on MT. I have a perfect day buff. I don't have any active dailys on Wednesday, but I check off some gray ones. On Thursday, I've lost my perfect day buff. All because, for whatever reason, I don't have any dailys on Wednesday.

If there are no due dailys, maybe it should noop? IE, not increment the achievement, but also not remove perfect day stats buffs if they are applied.

**Comment by crookedneighbor** [comment]
Anyone else have thoughts on this?

**Comment by khipkin** [comment]
I also have mixed feelings.  But having the buff removed isn't really a punishment; it's just a lack of a reward.  The default state is NO buff, so I don't think players should get a reward for doing nothing.

**Comment by Alys** [comment]
The way I see it is that the perfect day buff is a reward for completing
everything you needed to do on a day, so it doesn't feel right to get it
when there's nothing you needed to do. If the buff is retained, someone who
has no Dailies on one day is being rewarded more than someone who has a lot
of Dailies and can't quite finish all of them. That's not a big reason
since there's so many other factors that make Habitica uneven between
players and we don't normally worry about any of them, but it feels like an
inconsistency.

In cases where a player feels they have earned a buff on their days off,
they can create a Daily for "completed all of yesterday's Dailies" and
schedule it for any days when they have no other Dailies. We can even
mention that in the Perfect Day wiki page. It's consistent with the kind of
advice we give in the Tavern when people are asking about customising
Habitica to how they want it to work.

**Comment by khipkin** [comment]
@crookedneighbor Are you convinced?

**Comment by crookedneighbor** [comment]
/shrug

If Alys feels strongly, that's good enough for me.

**Pull request merged**
