### PR TITLE
fix broken links in locales readme files

### PR DESCRIPTION
**Pull request by mleko**
### Changes

Fixes broken _README_FIRST link

---

UUID:

### CODE REVIEW

**Comment by Alys** [comment]
Ah, sorry about that, I'd missed the fact that those links would be broken.

Let's future-proof this in case of further changes. Can you please make each file say just this:

```
 Do not edit any files in this directory!

 For more information read README.md in the parent `locales` directory.
```

**Comment by Alys** [comment]
That's great, thank you! 

If you'd like this to count towards a contributor tier, please tell us your User ID (that's what the UUID field is for in the Pull Request template, but please add it to a new comment now so that we get emailed automatically when you've added it).

**Comment by mleko** [comment]
UUID: 59543ced-98ce-4d5c-8226-aa82f896b928

**Comment by Alys** [comment]
I've awarded you a tier. You can read more about [contributor tiers and rewards here](http://habitrpg.wikia.com/wiki/Contributor_Rewards).

Note that as your tier increases, it takes progressively more work to achieve the next one, so for the higher tiers, larger PRs or a few PRs are required. There's some information about that at Contributor Rewards, but feel free to ask here if you have questions!

**Pull request merged**
