### PR TITLE
Add checkmark to completed quests in shop

### PR DESCRIPTION
**Pull request by mirrorcoloured**
[//]: # (Note: See https://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
* Adds 'completed' property to quest items based on achievement status
* Adds a checkmark icon to the upper left of quest items in the store to show which have been completed

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: b8874025-15f2-485b-9c7e-ce3a2f13ab0f

### CODE REVIEW

**Comment by SabreCat** [comment]
Hi @mirrorcoloured, thanks for sending a PR! Is there an issue ticket this addresses? If so, could you provide a link to it in the description?

**Comment by SabreCat** [comment]
Before/after screenshots would also be helpful for our UX folks to see how the design looks!

**Comment by mirrorcoloured** [comment]
I'm not aware of any issue tickets for this--it's just a feature I've been wanting and decided to see if I could implement it.

Here's a screenshot showing that I've completed two of these quests:
image

I chose the upper-left to match the style of the 'locked' quests but a quest can be both locked and completed so both can be displayed at the same time. I also used the existing 'check.svg' instead of making a new asset, but maybe another icon would be more appropriate?

**Comment by SabreCat** [comment]
great, thank you! I'll have the rest of the team look at this and see if it feels like the right implementation. I do know you're not the only one who's asked for something like it!

One thing I notice in the screenshot--it looks like adding that element might be causing the quantity bubble to stretch slightly or otherwise get off center. Compare to this, from the live site:

image

The "1" on your count of Unicorn quests isn't vertically centered the way the "1" in my count of Turquoise quests is, here.

**Comment by mirrorcoloured** [comment]
Hmm good eye. I just reverted to the develop branch and it looks the same, though my live site looks like yours. So could it be from something else in the develop branch?

**Comment by SabreCat** [comment]
Could be, though I'm not aware of any other recent changes in that area--I'll give it a closer look during review!

**Comment by mirrorcoloured** [comment]
Aha my develop branch was old (~3 months) from when I originally forked it. I believe this pull request is up to date with the latest but let me know if I need to rebase.

**Comment by SabreCat** [comment]
I'm not reproducing the stretchy number bubble after merging current develop, and I've gotten the OK from the designers on this solution for now, so we're good to go! Welcome to the ranks of the Blacksmiths at tier 1!

**Comment by Tressley** [comment]
@mirrorcoloured -- Thanks for your hard work on this! Attached is a mock-up to better illustrate positioning and color. Can you please update the check icon to this SVG? 

image

Icon can be grabbed here: icon-check

**Comment by mirrorcoloured** [comment]
@Tressley Sure thing! Just a few clarifications:
There is already a 'check.svg' in the repo that I had pulled. Do you want to replace it with the definition above, or is just sizing the existing item to 16x16 and bumping the left and top to 4px okay?

image

What do the 74px and 100px indicate in your image? My overall div.item is 94x120 px.

image

Finally: should this update go in a new PR?

**Comment by Tressley** [comment]
@mirrorcoloured - Actually, can you replace it with this SVG? I noticed an issue with both the existing `check.svg` and the previous file I provided. They were both missing the 16 x 16px bounding box that should be applied. Sketch/Zeplin's SVG renderer is also adding a lot of complicated markup. This one was exported using Adobe Illustrator, so it should be more succinct, and will need to be properly styled with CSS: [`check.svg`](https://user-images.githubusercontent.com/2686586/197607502-aad250c7-9e52-4511-b28a-3dcb4b87de17.svg)

No need to worry about the differing proportions. Those are artifacts from my static design and the website being dynamic.

PR question is for @SabreCat. Tagging him in.

**Comment by SabreCat** [comment]
@mirrorcoloured yes, if you'd like to continue helping us polish these elements, please do create a follow-up PR!

Looks like the changes needed are

* Replace `check.svg` in the repo's client assets with the one @Tressley supplied above
* Make sure the checkmark icon on completed quests is positioned 4px from the top and left of the outer div
* In the CSS for task checkboxes, change the margin on `.check.svg-icon` to 5px all around instead of 9px 8px, to account for the revised SVG there

**Comment by mirrorcoloured** [comment]
It's been a minute, but here's the new svg in place:
image
image
Just to confirm, we're looking for 4px from the top-left, and a 5px margin, for a total of 9px from the top-left to the icon?

**Comment by Tressley** [comment]
@mirrorcoloured -- Looking better, but I think there might have been some confusion around @SabreCat's request.

Once the new `check.svg` has been uploaded, you'll need to account for the other instance of it appearing, the task checkboxes. That is where you'll need to update some additional CSS -- Changing the margin on `.check.svg-icon` to 5px all around instead of 9px 8px.

As for the checkmark you've added, that only needs to be 4px from the top and left margin. 👍🏻

**Comment by mirrorcoloured** [comment]
Understood--I've got it fixed in the shop and on tasks.
image
image
I also adjusted the CSS in buyGemsModal (the checks were quite small there).
image
I see several other places where this asset is used, though I don't know where they exist in the UI to check them out.
- invitationListModal
- canceledModal
- successModal
- subscription
- approvalFooter
- selectList

Several look like they're associated with payments, is there any guidance on mocking up going through the payment screens on a dev build? The last two look like they're in tasks and ui, but I'm not sure where those elements are used or where the checks appear.

**Comment by mirrorcoloured** [comment]
I've put these changes in a new pull request for now, but I'm happy to make any follow-up edits to these other locations if necessary.

**Comment by Tressley** [comment]
@mirrorcoloured -- I think you've done plenty! Thank you again for your hard work on this. 🥇 

@SabreCat -- Would you mind taking a peek at this and identifying the additional areas highlighted as references to the `check.svg`? And also bringing this in the loop for testing?

**Pull request merged**
