### PR TITLE
Removes excessive padding in footer on mobile view - Fixes issue #12631

### LINKED ISSUE #12631: Unnecessary padding in footer in mobile view.
**General Info**
Browser - Chrome

**Description**
The footer of the website has an unnecessary right and left padding of 6em and also the layout of bottom links is not proper.

image

Can I work on this issue?

### PR DESCRIPTION
**Pull request by lilithi**
[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #12631 

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
In appFooter.vue, I added a condition to the footer. The margins become smaller when the screen size is 770px or less. The footer now has nicer spacing on small windows and mobile. 
Please ignore the changes to the other files. They are a mistake I am unsure how to fix as this is my first time using git

New vs old mobile view:
HabiticaMorePretty
HabiticaLessPretty

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 8d2b6289-4523-4a1e-a463-fd8f9e23057a

### CODE REVIEW

**Comment by benkelaar** [comment]
@lilithi Awesome work, thanks for contributing!  You've done some interesting things with the files here!  https://github.com/HabitRPG/habitica/blob/4e9f024bbbeb7173af5628264a8df867984d304a/%1B%1B%1B%1B%1B seems to be some kind of grep result in a file which has as a name of 5 ESCAPE character encodings 😄

I think your easiest bet would be to reset your local branch to develop, so from your habitica root folder do:

```bash
git reset --hard develop
```

And then checkout only the file you want your changes for committed.

```bash
git checkout origin/branchy -- website/client/src/components/appFooter.vue
```

And then recommit (`git commit -C origin/branchy`) and force push (`git push -f`).

I think that should fix this merge request for you.

**Comment by lilithi** [comment]
@benkelaar  Thank you for the help! I'm not quite sure how I managed those other files 😅 but the merge request is fixed now.

**Comment by Alys** [comment]
@lilithi Thank you for this! I've given you Tier 1 as a Blacksmith - congratulations! :)

Note that as your tier increases, it takes progressively more work to achieve the next one, so for the higher tiers, larger PRs or multiple PRs are required. There's some information about that at [Contributor Rewards](https://habitica.fandom.com/wiki/Contributor_Rewards), but feel free to ask if you have questions!

**Comment by Alys** [comment]
@benkelaar thank you for helping to get the accidental extra files removed!

**Pull request merged**
