### PR TITLE
Fixed bug #3007 where using wrong "old password" when changing password ...

### PR DESCRIPTION
**Pull request by ebiagogo**
...results in "Password changed succesfully" message even though password change fails.

The root of this issue was in public/js/app.js, specifically myHttpInterceptor wasn't rejecting the promise correctly when there's an error. The fix was pretty simple but it had implications in other parts of the UI because there were several $http.post calls that had ".error(function(..." doing the wrong thing (handling the data instead of data.err). I updated that code as well.

Related to this problem, the check for '400 range?' (also in public/js/app.js) is incorrect. It's checking if response < 500 instead of response.status. I changed it to check "response.status". And instead of rejecting the promise for everything (because I wasn't sure if that's correct) I changed the code to do it if the response.status is 401 (since this is the exact response returned from the controller in case of error). I figured the more conservative approach was the safer one.

### CODE REVIEW

**Comment by ebiagogo** [comment]
So clearly I've messed up this pull request. I pushed the branch for me second pull request (pull #3930) into this one so all the changes are here. So this code has fixes for both issue #3007 as well as for #3477).

**Comment by lefnire** [comment]
LGTM! did you have a chance to test it on a few server error cases?

**Comment by lefnire** [comment]
I always look at the "Files Changed" tab. If that looks clean, then a dirty merge history isn't the end of the world. If, however, that tab has a bunch of unrelated changes I usually request a new PR. This one looks fine

**Comment by lefnire** [comment]
did some testing, looks checks out on my end. Thanks again for the help! lvl++

**Comment by ebiagogo** [comment]
Yes, I checked the file changes and it looked good to me. All the changes are pretty straight forward (which is why I chose them). I tested the original problem (incorrect old password) pretty well and that looks to be fine. I tested the change username with an existing one and that looked fine as well. I looked into the existing unit tests but those seem a bit "light". I'm a little new to the way unit tests are done on this project and up next for me is a deeper dive into them and I hope to write the tests related to the changes I made here. I figure that's a good way to dig in to the testing.

**Comment by lefnire** [comment]
yeah, our tests are very lacking - _definite_ place of need

**Pull request merged**
