### PR TITLE
Other user checkins: user profile modal checkin count

### LINKED ISSUE #9359: Can't View Check-Ins for other users
Currently, when you open a user's profile modal, the area that is supposed to show their number of Check-ins is broken and does not display. This should be fixed.

### PR DESCRIPTION
**Pull request by kartikadur**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes https://github.com/HabitRPG/habitica/issues/9359

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
+ Add `loginIncentives` field to publicly accessible data fields in backend api so that non-loggedin user checkins are visible on member profile modal
+ Add integration tests for the same in member and group apis

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID:

### CODE REVIEW

**Review by paglias — APPROVED** [review]

**Comment by SabreCat** [comment]
Sorry to bounce this back at you after @paglias marked it OK, but can you take a look at that test failure, @kartikadur? It appears to be directly caused by your changes.

**Comment by kartikadur** [comment]
@SabreCat No problem. I was just surprised that the PR was approved despite the errors. I will look into it and update as necessary.

**Comment by kartikadur** [comment]
I had forgotten to update the integrations tests. updated now.

**Comment by kartikadur** [comment]
I looked at the error and it says:

```
1) GET /groups/:groupId/members supports using req.query.lastId to get more members:
Error: Timeout of 8000ms exceeded. 
For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```
This error is unrelated to any changes I made as far as I know. 

@SabreCat, @paglias  any suggestions?

**Comment by SabreCat** [comment]
Yeah, that's an inconsistent issue in the test suite. I'll restart it, should straighten it up. Thank you!

**Comment by SabreCat** [comment]
That does it, thanks! Let us know if and when you get a Habitica account so we can reward you there for your contributions. 😺

**Comment by kartikadur** [comment]
@SabreCat thanks, will do.

**Pull request merged**
