### PR TITLE
feat(archive_todo): Update batchUpdate

### PR DESCRIPTION
**Pull request by jbutz**
This is part 3 of habitrpg#3062. It makes batchUpdate look at the archived flag
not the completed date

Part 1: habitrpg/habitrpg#3302
Part 2: habitrpg/habitrpg-shared#198

### CODE REVIEW

**Comment by deilann** [comment]
UUID?

**Comment by lefnire** [comment]
Ok. I like the sentiment here. I wanted to get them all in and we can fiddle with as necessary before deploying. Have you had a chance to test this yet @jbutz? Does it check out ok? @deilann, could you give him a level for these PRs? 

We may want a button which performs the old "clear completed" action. Eg, when I clear completed I don't want them on my user object anymore - they're done.

**Comment by jbutz** [comment]
All of these worked in my vagrant box without issue. I was manipulating the lastCron and making sure I could run it as many different ways as possible. With them merged I'll run through and try them all again.

**Comment by jbutz** [comment]
It looks like everything still works for me in my vagrant box.

**Comment by jbutz** [comment]
@deilann 
UUID: cb15097c-1743-4ce7-a769-55cf391d4cef

**Pull request merged**
