### PR TITLE
Add tooltip with exact health/exp/mana

### PR DESCRIPTION
**Pull request by jdpopkin**
See [this issue](https://github.com/HabitRPG/habitrpg/issues/3223). This is my first attempt at fiddling with HabitRPG. I also don't know if anyone with strong feelings about UX has reviewed this idea yet - is there anyone I should ask/tag for that purpose?

### CODE REVIEW

**Comment by Alys** [comment]
Could you please show us a screenshot?

@benmanley does a lot of work on the UI

I think having a tooltip is a nice idea.

**Comment by jdpopkin** [comment]
screen shot 2015-01-04 at 5 42 36 pm
Sorry about that - here it is. I've just noticed that the tooltip's location isn't relative to the mouse - it's always centered, which rubs me the wrong way. I might try to change that.

**Comment by Alys** [comment]
Looks good! I think centred is okay, although at the mouse position would also be fine with me.

At the moment, Fix Character Values is showing my XP as 653.9058071605414. Does that much precision show up in the tooltip? Do we want that? Not saying we don't; just asking. :)

**Comment by jdpopkin** [comment]
screen shot 2015-01-04 at 5 58 12 pm
It does, unfortunately. Here's a screenshot of what it looks like with that kind of XP value. I could limit it to however many decimal points if I multiply the value by 10**n, round, and divide again (although the jade starts to get a bit less pretty that way; perhaps there's already a utility function for this? If not, that's probably where this kind of logic should go).

Good call on Fix Character Values - I'd been clumsily messing around clicking tasks trying to remember if HabitRPG gives out fractional XP or not.

**Comment by crookedneighbor** [comment]
Everything looks good to me. :+1: 

If the goal is to show more info by using the tooltip, I think showing the "exact" amount is fine.

**Comment by Alys** [comment]
That looks fine!

When you have a full set of party members, the bars shrink a lot, but from the looks of it, the tooltip will still just fit within the bars. If I have time after work today and if no one merges this before then, I'll test on my local install where I already have a large party set up, just in case there's some odd edge effects.

screen shot 2015-01-05 at 9 05 31 am

**Comment by crookedneighbor** [comment]
Here's a screenshot for a user with a lot of party members:
screen shot 2015-01-04 at 5 22 10 pm

**Comment by Alys** [comment]
Thanks @jdpopkin! What's your unique user ID? (Settings -> API)

**Comment by jdpopkin** [comment]
No problem! I'm 499a5370-c67c-41c0-a8c3-dbff93a3ca12

**Comment by deilann** [comment]
I really don't think _that_ much accuracy is necessary for this
situation... and I think it makes it kind of cluttery.

**Comment by Alys** [comment]
@jdpopkin Tier++

**Comment by benmanley** [comment]
Hi all. I agree with @deilann that it looks cluttered, so I'd prefer a limit.

How many decimal places would be useful? @wc8 raised the issue, so might have a view.

**Comment by crookedneighbor** [comment]
I'd say 3 or 4 decimal places is the most you'd want to see. Even that is pretty excessive. I'd be happy with 2.

**Comment by deilann** [comment]
I think 1 or 2 is all that's really necessary.

**Comment by benmanley** [comment]
1 or 2 sounds good to me.

**Comment by deilann** [comment]
I think the whole point of the tooltip is to easily see if your "4" health
is actually 3.1 health, not higher.

**Comment by crookedneighbor** [comment]
Is it cool if it rounds up? IE, 10.12521020393 exp becomes 10.3?

screen shot 2015-01-06 at 1 50 04 pm

**Comment by deilann** [comment]
Yeah. The numbers that would affect your health/etc. are generally large
enough that if you need to worry about that level of precision, maybe you
should take a risk at death. :P

**Comment by crookedneighbor** [comment]
Done: https://github.com/HabitRPG/habitrpg/commit/53c466ee7fb0bafd687af9296d0c80ac841d77eb

**Comment by deilann** [comment]
Awesome, Blade!

**Pull request merged**
