### PR TITLE
updated the phoenix sprite with the one lemoness provided

### PR DESCRIPTION
**Pull request by danielvancamp**
fixed the issue : 

Phoenix Mount problem - Weapon cuts through the mounts neck #6174

### CODE REVIEW

**Comment by crookedneighbor** [comment]
@danielvancamp You changed the compiled spritesheet, not the image that is used to compile the spritesheet, so this change will get overwritten the next time the spritesheet is compiled.

Body: https://github.com/HabitRPG/habitrpg/blob/develop/common/img/sprites/spritesmith/stable/mounts/Mount_Body_Phoenix-Base.png
Head: https://github.com/HabitRPG/habitrpg/blob/develop/common/img/sprites/spritesmith/stable/mounts/Mount_Head_Phoenix-Base.png

**Comment by danielvancamp** [comment]
I see! Stupid :P 
I'll fix it right away.

**Comment by SabreCat** [comment]
To spare us further merge conflict hassles, I've cherry-picked this into the main branch on 98a62c5 and recompiled the spritesheet on 9cbe94c. So the fix will be live soon!

@danielvancamp, this will count toward a contributor tier! What's your Habitica UUID (from Settings > API)?

**Comment by danielvancamp** [comment]
Thank you very much, hope to do some more in the future. 
Here is my ID : bb183c7e-47bc-487c-9431-06bb24745c43

**Comment by SabreCat** [comment]
@danielvancamp: Tier awarded! Note that while your first tier is easy to get, further tiers require increasing amounts of effort from one to the next, so another PR of this scope likely won't bump you to 2. But keep helping out and we'll express our thanks accordingly!

**Pull request closed without merging**
