### PR TITLE
Starting a Slovene translation

### PR DESCRIPTION
**Pull request by mrgoodwrong**
I'm kind of lost here, hope I did the pull request correctly. Anyway, I wish to do a Slovene translation. I don't know if this matters, but we use some special characters: č, ž, š.

### CODE REVIEW

**Comment by litenull** [comment]
@mrgoodwrong Kje si brate :D

**Comment by mrgoodwrong** [comment]
@litenull Ooo, pa le nisem sam tu gor! Predvidevam, da si bolj domač tu gor, boš svetoval, če mi ne bo kaj jasno :)

**Comment by litenull** [comment]
@mrgoodwrong Jaz sem eden glavnih developerjev, tako da ti bom lahko pomagal :)
Samo vprašaj.

**Comment by mrgoodwrong** [comment]
@litenull Noro! Fajn slišat, da imamo tudi Slovenci prste zraven :) No, glede na to, da sam ne znam programirat, lahko vsaj s prevodom malo pomagam. Sem si že ogledal, kako bi naj to potekalo, zdaj samo počakam, da dodate mape pod translations/locales? Pa predvidevam, da je pri določenih zadevah omejitev znakov?

**Comment by mrgoodwrong** [comment]
After translating a good part of the text, I noticed that the English template isn't really up to date, but I guess you guys have more pressing matters to attent to at the moment. Also, since you are using some items in different contexts (desert potion, desert pet, fox, fox egg...), the whole thing won't really be grammatically correct, due to the complex Slovene grammar, especially concerning word endings and word classes. Maybe some other languages have the same issue?

**Comment by lefnire** [comment]
@mrgoodwrong this PR got broken somehow, there are 126 commits coming from different branches - they have a very high chance of clobbering the code base ([happened in the past](https://github.com/HabitRPG/habitrpg/pull/1558#issuecomment-25209580)). Can you create a new branch, just copy your translation files in, and re-submit? Sorry for all the troubles!

**Comment by lefnire** [comment]
actually, reopening this so it doesn't get buried. let's just remember not to merge. I can copy the file manually if @mrgoodwrong's thinking "dude, no! i just did all this work"

**Comment by mrgoodwrong** [comment]
Actually you can close this one, since all the work is actually still on my PC. From the translation tutorial I figured I had to wait for a Slovene folder to get created to start editing the template. Or can I somehow simply start doing work here? As I've said, I'm new here and a bit lost with all the pulls, forks, commits and branches :)

**Comment by lefnire** [comment]
Actually, if it's giving you beef you can just [shoot me](mailto:tyler@habitrpg.com) the file (and your UUID for reward) and I can just drop it in

**Comment by mrgoodwrong** [comment]
I guess that might be best, I'll do that when I'm finished. However the grammar concerning eggs and potions will still be a problem, but I guess we can figure that out later.

**Comment by lefnire** [comment]
Yeah, I'd say worry about the egg/potion grammar later because the mount system is going to be changing all that verbiage pretty substantially, so we may face new problems in the near future :)

**Comment by lefnire** [comment]
https://github.com/HabitRPG/habitrpg/commit/f64ca7d4d0e1367e8fb7ba57dbda4892fe81eb4a

**Pull request merged**
