### PR TITLE
Added ability to keep feeding a single item and to feed multiple items to pet.

### LINKED ISSUE #5024: Batch Feeding Pets
Feeding pets individually takes a lot of clicking and is a waste of time! It would be nice to implement batch feeding pets.
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/11080229-batch-feeding-pets?utm_campaign=plugin&utm_content=tracker%2F68393&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F68393&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by TheHollidayInn**
Fixes #5024 .

I have added two abilities here:
1. You can now feed a single food item multiple times to a pet
2. You can now feed multiple items to a pet

Also, I have adjusted the selling to pass the tests and to display correctly. However, currently you can only sell one food item.

### CODE REVIEW

**Comment by lemoness** [comment]
Hooray!

**Comment by crookedneighbor** [comment]
Seems to me like this PR allows you to select multiple kinds of food to feed to a pet, but it does not let you feed multiples of the same kind of food to the same pet. 

For instance, if I have 5 x meat, 2 x strawberries and 1 x fish, I can feed 1 meat, 1 strawberry and 1 fish to my base panda. I am unable, however, to feed all 5 meat to my base panda. 

There also isn't a good indication about which food are selected. 

It might be that I just don't understand how to do it correctly, but even that should be a good indication that some work needs to be done so it's intuitive for the user.

**Comment by crookedneighbor** [comment]
Okay, I see, you select the meat, then keep clicking on the pet to feed it multiple times. 

I still think the interface could be better. Took me way to long to figure it out.

**Comment by TheHollidayInn** [comment]
I was thinking of reducing clicks even more. For example: feeding 5 cotton candy at one time. That seems pretty feasible, but these edits were straightforward and a huge improvement.

There are two things that are suppose to indicate that you can continue to feed an item (one selected):
--The green around the pets persists
--The items are highlighted in blue

I think I was having issues with the blue highlight, so let me look into it in an hour or so.

**Comment by TheHollidayInn** [comment]
Update:

screen shot 2015-04-15 at 12 05 31 pm

**Comment by lemoness** [comment]
Given the way food preferences work, I think it will be pretty important to
be able to feed pets a large amount of the same type of food - I frequently
want to feed all 10 of one food type to my pets at once, for example.

**Comment by TheHollidayInn** [comment]
I could alter the alert box to do something like the following:
--If amount left is equal to 1, just ask for confirmation
--if greater than 1, ask user how many of that particular food you would like to feed

Does that work? I can code up an example tomorrow.

**Comment by deilann** [comment]
If they're preferred foods, you wouldn't want to feed ten. 9 would be the
max.

There needs to be handling for if the user feeds a pet more than it needs.

**Comment by TheHollidayInn** [comment]
That is easy to check for. I'll be sure to include it.

**Comment by Alys** [comment]
I like the idea of being able to select how many foods you feed to a pet. I
often feed all-but-one of the foods required to turn a pet into a mount (I
have my reasons...). Perhaps the default selection could be the full number
of the food available, with a note saying that if it's more than the pet
needs, the extras will not be fed (if there's no note, we'll get constant
questions about that).

**Comment by crookedneighbor** [comment]
Can we not use the alert box? I hate that thing. 

I'm thinking a popover that contains an input box if you have more than one of the food item available.

**Comment by TheHollidayInn** [comment]
@alys sounds good to me. I will definitely include a note. I kind of think the default should be 1, so people don't accidentally give away more than intended. 

@crookedneighbor I also hate the alert box. I'll user popovers. That actually gives me an idea about how to set up the workflow.

**Comment by TheHollidayInn** [comment]
Okay, here is what I have added.

screen shot 2015-04-16 at 1 37 48 pm

Also, can anyone help me set the default values? I'm looking online, but can't find anything. Using ng-value with ng-model on a numbers textfield doesn't seem to be working.

**Comment by TheHollidayInn** [comment]
Just Kidding. I figured it out. Here are some more screenshots. 

screen shot 2015-04-16 at 1 46 42 pm
I changed the last cotton candy to two before submitting the modal.
screen shot 2015-04-16 at 1 46 50 pm

**Comment by crookedneighbor** [comment]
1) I'd prefer a popover, not a modal. Like the popover that appears when leaving a guild. 

2) I don't like the "feed multiple kinds of food at once" option. Seems just ripe for errors. (Admittedly, since I know what each kind of pet likes, I can't imagine purposely feeding them something they wouldn't like, but maybe that's just me)

3) tests tests tests

**Comment by TheHollidayInn** [comment]
1) Alright, I was going to use a popover, but I thought the modal might be better to include all the html. I'm not sure how to reference a large amount of dynamic html into a popover. I'm sure I could figure it out though.

2) I think this is needed. Especially if you have all the mounts that correspond to a certain food. But, if we all agree it is not needed, I can remove it.

3) I can work on the tests. Using `npm test` runs all tests, but I just need to run the e2e and karma tests, right?

**Comment by deilann** [comment]
"How much do you want to feed your pet?" asks your level of enthusiasm.
"How many," on the other hand...

**Comment by crookedneighbor** [comment]
The end to end tests aren't helpful right now. I'd focus on the karma tests: `grunt karma`

I'm willing to be overruled regarding multiple kinds of food, but the tests will need to be rock solid.

**Comment by crookedneighbor** [comment]
Also, let me mention that a modal makes more sense if multiple kinds of food are available. So if that's the route we go, modal is preferred.

**Comment by TheHollidayInn** [comment]
@deilann Ah, thanks. I will make the edit.

@crookedneighbor Okay, can do. I have already correct the tests a little to prepare for the multiple selection. Do you foresee a particular problem? 
Also, I should have the tests up tomorrow or by the end of the weekend at the latest.

**Comment by crookedneighbor** [comment]
You have a lot of new behavior that the tests didn't anticipate, so I imagine more tests will need to be written to cover each scenario.

**Comment by TheHollidayInn** [comment]
Yea, I understand. I was just checking to see if you had a specific concern.

**Comment by crookedneighbor** [comment]
Looking at the test file and it looks like there is actually no existing test for feeding pets. :anguished: 

So it's all up to you :wink:. If you get stuck, let me know and we can write them together.

**Comment by TheHollidayInn** [comment]
Alright, how are these tests?

**Comment by TheHollidayInn** [comment]
I have updated the modal confirmation to feed. Before it said select. Let me know if there is anything else I need to do for this PR.

**Comment by WhitneyFox** [comment]
I just created a new issue that may be related to this addition:  No longer able to feed pets #5139. It looks like part of the confirmation code is jamming the ability to feed at all.

**Comment by Alys** [comment]
@WhitneyFox When a pull request hasn't been marked as merged (in purple at the top of the page) then it hasn't been added to the live site, so it can't be affecting the site. Even some merged pull requests don't yet appear on the site - there can be a delay of days or weeks, depending on circumstances.

**Comment by crookedneighbor** [comment]
I think we need to table this for now. It's still something I want to happen, but we need a stronger UI plan for it.

**Pull request closed without merging**
