### PR TITLE
Added Pizilden's Theme

### PR DESCRIPTION
**Pull request by SalethiNat94**
### Changes
*Added audio files and modified the relevant files in order to add my new audio theme (an electronic theme with lots of drums. bass, and synths). Let me know what you think of the audio theme and if it's appropriate to use in Habitica in-game.

[Here is the link to the audio files used in this theme!](https://drive.google.com/drive/folders/0BxjXUni35plrTGpxQm52MXFFLWc)

Audio files created and submitted by Pizilden
UUID: 7a1b0a51-0221-4542-b09f-c5e27ba83f31

### CODE REVIEW

**Comment by SalethiNat94** [comment]
This is probably the fourth or fifth time I've tried submitting this PR (still getting used to using Git, my apologies ^__^) and the last time I did so, all checks passed for my own theme - not sure why this isn't the case this particular time.

**Comment by SabreCat** [comment]
@Pizilden Nothing to worry about there--we have a couple issues in our tests that cause random failures, it's something that'll need to be corrected separately. I'm restarting the test, so you'll probably see the red X clear up in a bit!

**Comment by negue** [comment]
@Pizilden thanks for the many theme-pullrequests :D 👍 , could you update them all to the latest `develop` branch changes? that way its easier for me to test (build the website, which gets many build errors because of bootstrap-vue)

**Comment by SalethiNat94** [comment]
Yes! I will do this as soon as possible!

**Comment by SalethiNat94** [comment]
That should have pulled the commits from Pizilden/develop (which I made even with HabitRPG/develop) into Pizilden/pizilden, which should now contain all of the most recent commits from HabitRPG/develop PLUS the commit that added my audio theme. Did I do this properly? If so I will repeat this process for the other three themes

**Comment by negue** [comment]
You could do this: https://help.github.com/articles/merging-an-upstream-repository-into-your-fork/   (for the next time ^^)

Your way is still right, but it takes propably a bit longer :), for now just merge your `Pizilden/develop` into the other PRs and we're good to go.

**Comment by SalethiNat94** [comment]
Done! Thanks 👍

**Comment by negue** [comment]
Could you trim the end of `Achievement_Unlocked` it has about a second without a sound, otherwise this PR is good to merge. I'll wait for the trimmed files and then this is ready for merge

**Comment by SalethiNat94** [comment]
Oops, extra commits were due to merge issues - Achievement_Unlocked should be properly trimmed now

**Comment by paglias** [comment]
@Pizilden can you remove the extra commits? The easiest thing might be to create a new clean branch and reapply your changes there

**Comment by SalethiNat94** [comment]
Looks like creating a new PR is the only way to go here. I'll tag everyone who was involved in this PR in the new one

**Pull request closed without merging**
