### PR TITLE
Issue 5563 pin or replace unregistered packages

### PR DESCRIPTION
**Pull request by kaizensoze**
In reference to issue #5563:

Go through unregistered packages in package.json, bower.json. If still no registered version available, pin it to commit/branch, otherwise swap out with now registered version and test. Also simplify github repo url since npm recognizes simpler user/repo format.

### CODE REVIEW

**Comment by crookedneighbor** [comment]
This will count towards a contributor tier! What's your User ID? You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api). Be sure to only copy the User ID and _not_ your API Token.

**Comment by kaizensoze** [comment]
b3a7ce77-5966-4534-b655-b1b341b88fb3

**Comment by crookedneighbor** [comment]
Contributor tier granted! You can read more about [contributor rewards here](https://habitrpg.wikia.com/wiki/Contributor_Rewards)

**Comment by kaizensoze** [comment]
Cool thanks!

**Pull request merged**
