### PR TITLE
Update Website's Task Page image

### LINKED ISSUE #8789: New PressKit Screenshot
There is a new screenshot to add to the PressKit! It should replace the old task list screenshot.

### PR DESCRIPTION
**Pull request by librarianmage**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes https://github.com/HabitRPG/habitica/issues/8789

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

[//]: # (Put User ID in here - found in Settings -> API)

----
UUID:

### CODE REVIEW

**Comment by TheHollidayInn** [comment]
Thanks! Can you post a screenshot?

**Comment by librarianmage** [comment]
Sorry for the late update!

image

**Comment by MathWhiz** [comment]
@TheHollidayInn Ping!

**Comment by librarianmage** [comment]
@TheHollidayInn Ping!

**Review by SabreCat — CHANGES_REQUESTED** [review]
The press kit ZIP included here seems to be broken. It contains only the MP4 promo video and four empty folders.

**Comment by librarianmage** [comment]
@SabreCat Fixed!

**Comment by SabreCat** [comment]
Excellent! Merged and noted in your progress toward the coveted Tier 7!

**Pull request merged**
