### PR TITLE
Esc only closes active tags box, not entire task

### LINKED ISSUE #10520: Esc key with tags box active should dismiss only that, not entire task
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

Minor usability issue reported in the bug guild:

>**whydidthetilda** (719c2e68-dd23-44fd-a27c-ef87dff4e3e1):
>this isn't really a bug (but it's happened to me enough times to be frustrating) but also not super worth putting in the features request thing either (I couldn't really work out where to put it there) - when setting the tags for a task, it would be v helpful if the esc key just closed the tag box rather than closing and losing the whole task.

### PR DESCRIPTION
**Pull request by thefifthisa**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #10520 

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

Pressing the escape key closes only the tags box if it's open, and the entire task if it's not.

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 9ca2bb65-ce6c-4e4c-a367-5ef9b5c7421e

### CODE REVIEW

**Comment by texastoland** [comment]
@thefifthisa would you want to implement close when user clicks out of the tag box too? I just [commented on it](https://trello.com/c/LlJccgmY/293-chat-tavern-talk-enhancements-party-talk-enhancements-friend-list#comment-5b528759211b5eda86143166) in Trello with @TheHollidayInn.

**Comment by thefifthisa** [comment]
@texastoland sure! By clicking out, do you mean just within the task modal or anywhere in the background too?

**Comment by texastoland** [comment]
🙏🏽 exactly @thefifthisa. Awesome! Aside from being intuitive the close button usually open off screen for me.

**Comment by texastoland** [comment]
🙏🏽 anywhere outside the tags popup (inside the task modal or not). Aside from intuitiveness the close button usually open off screen for me. You're awesome @thefifthisa!

Coveralls is being odd. You didn't touch any file where coverage changed.

**Comment by paglias** [comment]
Coveralls can be odd, don't worry about it :)

**Comment by paglias** [comment]
This is working well @thefifthisa , it'll be merged this week, thanks!

**Comment by texastoland** [comment]
One more question: do your fixes apply to both the task tags popup as well as the filter tags one?

**Comment by thefifthisa** [comment]
@texastoland just the popup!

**Pull request merged**
