### PR TITLE
new GSalvadi audio theme, created by NomindTR

### PR DESCRIPTION
**Pull request by Alys**
This adds a new audio theme called **GSalvadi**, which was created by NomindTR (70d88957-673a-4edd-b97e-f1ecb018dd89). See comments in https://trello.com/c/tljx8gKC/18-music-sound-effects-v3 around 13 June 2015.

I've copied this to our beta site so that we and NomindTR can test it. We don't normally do this but I think in this case it's essential because there is no other way that NomindTR can review the audio before it goes live.

---

**NomindTR:**
You can access the beta site at https://beta.habitrpg.com/ and you'll see that your theme exists there.
The beta site uses the **same** user data as the normal site, so log in as you usually do. Keep in mind that every action you take on the beta site will be permanently saved, just as if you'd done it on the main site, so if you create and tick off a lot of tasks for testing your sounds, you'll find that you retain the gold, experience, etc from those tasks. Of course testing is worth doing if you want to, so it's not a bad thing that you'll earn gold etc from it! 

If you'd like to test without affecting your real account, you can create a test account and then delete it when you've finished with it.

Is the GSalvadi entry in the audio menu correct? If that's not exactly what you wanted, tell me! I can change it easily.

Comment here or on the Trello card if you have any questions or if something doesn't look or sound right.

Tell us when you're happy with it all.

After your testing is finished, it's best if you do not continue to use the beta site. We often use it for testing incomplete features and so it can produce strange, undesirable behaviour. However it's perfectly safe at the moment! You can safely use it as much as you want to test your sounds. I'll add a comment to this thread when the beta site is no longer suitable for use.

### CODE REVIEW

**Comment by Alys** [comment]
FYI I've edited the beta URL in my post to use https rather than http.

**Comment by Alys** [comment]
@lemoness : In the [MUSIC + SOUND EFFECTS v3](https://trello.com/c/tljx8gKC/18-music-sound-effects-v3) Trello card, NomindTR asks
"What is the ideal length of a background music? Having background music for each page still has technical concerns?"
Is this something you'd like us to consider now?

**Comment by gsalvadi** [comment]
I tested it creating a test account. It looks OK. Please change the name to " Gokul Theme"

Thank you.

**Comment by crookedneighbor** [comment]
The down habit sound is much quieter than the up habit sound. Is that intentional? I almost thought it was missing until I turned up the volume.

**Comment by crookedneighbor** [comment]
We're also not using the chat sound (for any audio theme)

**Comment by gsalvadi** [comment]
@crookedneighbor I will rewrite the down habit file. I understand it's quieter. And, there was a chat.mp3 file in the template so, created one. Should I replace it with blank file?

Please check Dailies sound and let me know if it would be better when louder like other sounds.

**Comment by gsalvadi** [comment]
This zip download contains fix for Minus Habits and for To Dos. 

https://drive.google.com/file/d/0B0iK5-G-EFCXSU9hV09jLVJ5QzQ/view?usp=sharing

**Comment by crookedneighbor** [comment]
@NOMINDTR I think we should definitely keep the chat sound and just fix the code that _should_ be playing it.

**Comment by gsalvadi** [comment]
@crookedneighbor Like user can mute it?

**Comment by crookedneighbor** [comment]
@NOMINDTR No, there's no place in the codebase that actually makes the call to play a chat sound. It has nothing to do with your audio at all, so you don't have to worry about it :smile:

**Comment by crookedneighbor** [comment]
Also, dailies sound is :+1:

**Comment by gsalvadi** [comment]
Sounds good ? Great!!

**Comment by gsalvadi** [comment]
OK. Now I understand what you meant by fixing the code for chat sound :)

**Comment by lemoness** [comment]
Background music is not high priority - what are the technical needs?

**Comment by gsalvadi** [comment]
@lemoness Was just asking as I read "Decisions/Considerations/Technical Concerns" on trello
https://trello.com/c/tljx8gKC/18-music-sound-effects-v3

**Comment by gsalvadi** [comment]
@crookedneighbor Got it.

**Comment by Alys** [comment]
@NOMINDTR I've downloaded the new sound files so you can delete the zip file if you wish to. I'll update the beta site in my lunchbreak in a few hours.

You can keep using beta today, but if you do go back to the normal site, before you leave beta, choose one of the other audio themes (or "off") because the setting for your new theme won't work yet in the main site, and will cause errors.

**Comment by gsalvadi** [comment]
@Alys OK.

**Comment by Alys** [comment]
@NOMINDTR I've uploaded the new sound files and the new name to the beta site. Please test again and let me know if you'd like further changes.  You and any other testers will need to select the new theme again when you get onto the beta site.

Remember to select a different theme or turn sound off before going back to the main site.

**Comment by Alys** [comment]
And let us know if you want more changes or if you're happy for it to go live.

**Comment by gsalvadi** [comment]
@Alys It looks OK. Good to go.

**Comment by Alys** [comment]
Cool! I'll merge it later today and assign you your contributor tier.

You can keep using beta for a short time now, but I recommend that all you do there is select a different audio theme, and then move back to the normal site. Pretty soon, beta will not be reliable to use.

**Comment by gsalvadi** [comment]
@Alys No problem. I don't use an audio theme for now and I use the beta site only for testing with a test account. I continue using the regular site. No problem at all.

**Comment by Alys** [comment]
@NOMINDTR Your theme will appear on the website the next time we release new content - that should be in just a few days! I have awarded you a contributor's tier. Thank you!

**Comment by gsalvadi** [comment]
@Alys  Thank you very much.

**Comment by Alys** [comment]
@NOMINDTR Ignore any reversion messages you see here. We're just experimenting with something. Your audio will still go live. :)

**Comment by gsalvadi** [comment]
@Alys. OK. Got it :)

**Comment by Alys** [comment]
This will not be going live in the next release which is today, but almost certainly will in the one after that. We had a glitch on our staging server which resolved itself when I reverted this, but personally I suspect it was not related to this new theme and reverting the theme merely restarted the staging server and removed the unrelated glitch. I'll experiment further after work today.

**Comment by crookedneighbor** [comment]
@alys I think you're right, I don't think this had anything to do with the staging server problems.

**Comment by Alys** [comment]
This is back in our staging branch with no problems.
https://github.com/HabitRPG/habitrpg/commit/07b41d16b60442f50564df9a70caa8d9dc9b2db9

**Comment by gsalvadi** [comment]
@Alys Now I see the theme on regular site. Is it live?

**Comment by crookedneighbor** [comment]
@NOMINDTR It is live. An announcement about it will go out with the next deploy.

@lemoness I've updated the trello card to have the correct name for the audio theme.

**Comment by ghost** [comment]
@NOMINDTR to quote @WoodlandEve from [Trello](https://trello.com/c/tljx8gKC/18-music-sound-effects-v3) since you may miss a message without notification:

> I love the new Gokul Theme! I'm wondering if its possible to have a less abrupt ending to some of the sounds. <...> I guess what I'm asking is, is it possible to create a smoother audio fade out to reduce the 'pop' effect that's there?

**Comment by gsalvadi** [comment]
@GitHubSphinx   Let me will fix that. 
Can I post download link here once it's done?

**Comment by Alys** [comment]
@NOMINDTR Yes, here is good. I am emailed for every comment that's made here, so I'll see it and import the new files.

**Comment by gsalvadi** [comment]
These new sound files may be lengthier than the original. But they don't play music for any additional duration. They are filled with fade out tail.

Post here if something sounds wrong or somebody think something needs a fix. 
@Alys 
The link to new sound set https://drive.google.com/file/d/0B0iK5-G-EFCXTy1kX2dVZW9sTnc/view?usp=sharing

**Comment by Alys** [comment]
@NOMINDTR I've replaced the files with the new versions. They should go live in a day or two. https://github.com/HabitRPG/habitrpg/commit/a4e9e5dbfc298780e9d0aecce37702ca887e9287

**Pull request merged**
