### PR TITLE
Member modal spacing

### PR DESCRIPTION
**Pull request by thepeopleseason**
Updated member modal to add spaces between (Member since|Last logged in) and the respective dates (untracked in issue #2582).

### CODE REVIEW

**Comment by zoebeagle** [comment]
It looks like this is not exactly working properly yet... it appears as though it's not resolving the space and just leaving the HTML code in place: http://i.imgur.com/gNNw1pp.png

**Comment by lefnire** [comment]
Can add a space after the pipe `|`. Not explicit, but works?

**Comment by deilann** [comment]
That's how you're supposed to do it in jade, iirc.

**Comment by thepeopleseason** [comment]
Ach. Sorry guys.

**Comment by paglias** [comment]
@thepeopleseason it happens because jade escape HTML code when rendering the string.

Instead of `=` you should use `!=` to avoid escaping

**Pull request merged**
