### PR TITLE
Added links to multiple task help phrases (fixes #5349)

### LINKED ISSUE #5349: Every second to last list item on each Tasks help list displays: "Error processing string. Please report to http://github.com/HabitRPG/habitrpg."
error

UserId: 38040a8f-6adb-4bc0-93e2-be69cec72326

Chrome 43.0.2357.81 m, Windows 7 SP1

I have changed the language from danish to english, but don't know if the error was there before changing.

### PR DESCRIPTION
**Pull request by hairlessbear**
Fixes #5349.

selection_024

### CODE REVIEW

**Comment by hairlessbear** [comment]
I noticed that the second to last item in "Habits" formats its link slightly differently than the Dailies and To-Dos (i.e., link is on "these sample X" instead of "sample X"); I changed it to conform to the style of other two.

selection_025

**Comment by ghost** [comment]
@hairlessbear could you please consider making links to wiki translatable as well? 
@Alys please correct me if I'm wrong about it and you don't want wiki links to be "flexible" any more

some linking, for what it's worth
general: https://github.com/HabitRPG/habitrpg/issues/5202 and 
partial: https://github.com/HabitRPG/habitrpg/issues/5333 and https://github.com/HabitRPG/habitrpg/commit/af94236a01c0c10c7cb763adf6c298d6ef63be0d

**Comment by Alys** [comment]
Ah, yes. Sorry @hairlessbear, lately we've been including the wiki URLs in the locales files so that translators can, when appropriate, replace the URLs with ones that point to translated pages on the non-English wikis. It does mean that translators have to be more careful so as not to incorrectly modify URLs, but it provides a more seamless method of getting to documentation for non-English speakers.

**Comment by hairlessbear** [comment]
Not a problem, I'll fix that today.

**Comment by hairlessbear** [comment]
Updated!

**Comment by hairlessbear** [comment]
Interesting note though: in the original issue, the second to last item in the rewards column (`rewardHelp4`), wasn't functioning properly, and I have no idea why. As you can see in my most recent update, no changes have been made to `rewardHelp4` or how it's processed on the page, and yet it's working fine for me. Not only that, it's currently working as expected on the production site. Not sure what happened there.

**Comment by ghost** [comment]
@hairlessbear it's been fixed separately with https://github.com/HabitRPG/habitrpg/commit/af94236a01c0c10c7cb763adf6c298d6ef63be0d ("partial" link above)

**Comment by hairlessbear** [comment]
@GitHubSphinx Ah, that must have been pushed in between when the issue was posted and when I fetched the most recent version of `develop`. Thanks!

**Comment by crookedneighbor** [comment]
Yep, I fixed that one when it was reported separately.

**Comment by hairlessbear** [comment]
Does anything else need to be done on this? It looks complete to me.

**Comment by crookedneighbor** [comment]
I just haven't gotten around to giving it a final review. Merged or closed 20 PRs over the last couple of days.

**Comment by hairlessbear** [comment]
Got it. I apologize if that came off as nagging; I was trying to ensure that you weren't waiting on me to finish something I didn't see/understand.

**Comment by crookedneighbor** [comment]
I didn't take it that way at all. Pardon my brevity. I was responded by on a phone.

**Comment by hairlessbear** [comment]
Not a problem; I often have trouble interpreting tone in text-only conversations with strangers, and I have a tendency to assume the worst (HabitRPG is actually helping me improve that particular bad habit, albeit not as quickly as I'd like). I'll try to be less worried next time :sweat_smile:  

Besides, brevity is more efficient and should be used as often as possible, regardless of my neuroses.

**Comment by crookedneighbor** [comment]
Notated toward your next tier.

**Pull request merged**
