### PR TITLE
Fix Hippo-Crite Scroll Image (Fixes #10105)

### LINKED ISSUE #10105: Hippo-Crite quest icon is smaller than all others
### General Info
  * UUID: c073342f-4a65-4a13-9ffd-9e7fa5410d6b
  * Browser: Google Chrome
  * OS: WIndows 7

### Description
habitica gamify your life
In the selection quest modal the Hippo-Crite quest icon is smaller than all other quest icons

### PR DESCRIPTION
**Pull request by hathix**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #10105

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

[As I mentioned in a comment](https://github.com/HabitRPG/habitica/issues/10105#issuecomment-376502207), I found that the Hippo-Crite scroll image was 48x51 instead of the usual 68x68. The actual image (without padding) was 48x48, like all the other scrolls, but there was much less padding on the Hippo-Crite scroll image than the other scrolls. So I used GIMP to trim away the extra 3 pixels, leaving the Hippo-Crite scroll image at 48x48, then added 10px of padding on each side, yielding 68x68. Thus, the Hippo-Crite scroll image matches the others.

Also, I ran `npm run sprites` as mentioned in the Guidance for Blacksmiths.

Before (look at the very last scroll):

screen shot 2018-03-27 at 22 57 24

After:

screen shot 2018-03-27 at 23 04 05

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: cc3e8b88-f3e8-4428-91b3-ec4c9f814703

### CODE REVIEW

**Comment by paglias** [comment]
@SabreCat this looks good to me, but we should merge it without the compiled sprites?

**Comment by SabreCat** [comment]
@paglias Normally we'd skip, but with just one spritesheet affected I think it's OK! I'll merge it in after next `develop` deploy.

**Comment by paglias** [comment]
Not merging this one myself since @SabreCat knows better than me how to deal with this kind of conflicts

**Comment by SabreCat** [comment]
Noted toward your next contributor tier, @hathix !

**Review by SabreCat — APPROVED** [review]

**Pull request merged**
