### PR TITLE
Style fixes: Onboarding

### PR DESCRIPTION
**Pull request by negue**
Fixes:
- [x] Move Justin above the dialog for the last 2 pages
- [x] fix avatar position
- [x] item white background + border radius
- [x] Menu Indicator
- [x] New Option Style

Extract Parts of Onboarding:
- [x] Sub-Menu
- [x] Customize-Option List (Generic for all Items)
- [x] Body-Settings
- [x] Skin-Settings
- [x] Hair-Settings
- [x] Extras-Settings

Misc.:
- [x] Moved Tasks to content
  - [x] Replace Strings for Translation

### CODE REVIEW

**Comment by negue** [comment]
@SabreCat @Alys could you take a look too?

**Comment by Alys** [comment]
@negue I can put this on my local install to do some testing. Could you fix the conflict first though?

**Comment by negue** [comment]
As of right now only the menu changed for the body settings (need to replace the submenu on the other pages too), some other styles changed too, but still not finished

As for the merge conflict ... took some time to merge this huge file ^^ one reason more to extract multiple parts of it 😄 

@Alys ready for the first look

**Comment by Alys** [comment]
I'm not super-familiar with the requirements for this but it looks okay.
The top of Justin's head is cropped (or maybe hidden under the header) in some screens like the one below. Not sure if that's intentional or not.

image

**Comment by negue** [comment]
Yeah it shouldn't be under the toolbar, its weird how some browsers work as expected and some not...

What browser / os ?
Was it with `client:dev` or with the prod-build version ? (there was already an issue I fixed in this PR, which had this kind of dev/prod weirdness)

**Comment by Alys** [comment]
`npm run client:dev`
Firefox Quantum 66 on Ubuntu

**Comment by paglias** [comment]
@negue what's the status on this? also looks like there are some lint issues

**Comment by negue** [comment]
@Alys I can't reproduce this issue on mac, on any browser, could you check if a simple z-index change would help there?

**Comment by Alys** [comment]
@negue The head is still being cut off on Firefox on Ubuntu when viewing the delta site. It does look like a z-index problem but I haven't had time to investigate the code to be sure. It's only a display issue though, and it's only for the image. The actual text is still visible and the controls still work.

**Comment by negue** [comment]
@Alys on a production build the toolbar has a higher z-index, which is weird why it wasn't "over" the modal in develop mode, found the issue and added a higher z-index for the modal

**Comment by paglias** [comment]
What's the status on this?

**Comment by negue** [comment]
I'll fix the conflicts

@Tressley anything left todo on this? (In case I missed something)

**Comment by Tressley** [comment]
@negue -- I'm seeing a bunch of onboarding-related issues on Delta at the moment. Might need to double back to see what is causing the new issues.

**Comment by paglias** [comment]
Also there are some conflicts due to a different PR that got merged (https://github.com/HabitRPG/habitica/pull/11351)

**Comment by paglias** [comment]
(I'm marking this as needing work for better organization)

**Comment by Tressley** [comment]
@negue -- Can we add a hover state for `.option`? Something like `background-color: rgba(213, 200, 255, .32);`? It would look like this:

image

The rest looks good to me!

**Comment by negue** [comment]
Added hover

**Comment by Tressley** [comment]
@negue -- Hover doesn't need to be on the item that is selected already. 
image

**Comment by Tressley** [comment]
This LGTM. 👍

**Pull request merged**
