### PR TITLE
Update achievements.json

### PR DESCRIPTION
**Pull request by JohnJSal**
Capitalized "pets" for Golden, Skeleton, and Red collection achievement text, to be consistent with all others.

[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes put_#_and_issue_number_here

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID:

### CODE REVIEW

**Comment by paglias** [comment]
I'm going to leave this one to @SabreCat or @Alys as I'm not sure if it's a change we want

**Comment by Alys** [comment]
Having Pets capitalised is correct. :)

**Comment by paglias** [comment]
Sorry for the delay @JohnJSal ! The change will go live in a few days, if you have an Habitica uuid / username I'll be happy to award a contribution tier for the pr!

**Comment by thewilloftheshadow** [comment]
624e48a3-cbea-4bbe-ae44-ca9183f49626

I believe this is it (I already had it cause I was playing around with looking at different profiles with the API and his was one of them 😂)

**Comment by paglias** [comment]
Sorry @thewilloftheshadow but maybe you commented on the wrong PR? This one is from @JohnJSal

**Comment by thewilloftheshadow** [comment]
Nope right PR. His profile was one I was pulling so his ID was already in my clipboard

**Comment by paglias** [comment]
noted :)

**Comment by JohnJSal** [comment]
Thanks very much! My UUID/username is:

624e48a3-cbea-4bbe-ae44-ca9183f49626
@johnjsal (lowercase in Habitica, but it changes to camel case here)

I already have the Blacksmith title, so I'm not sure if this PR is enough for another tier, but that's not for me to decide! :)

**Comment by paglias** [comment]
@JohnJSal I added it to the list of your contributions but did not award the next tier

**Pull request merged**
