### PR TITLE
shrink spritesmith images to reduce page load

### PR DESCRIPTION
**Pull request by Andrux51**
As part of Issue #3486 I have put the spritesmith generated images into tinypng.com - this greatly reduces their file size without any impact to the visual quality (if you can tell the difference, I'll give you money)

I would also advise using this feature for sprites that are to be added later. This cut the image size by 1MB (56%) - here's a screenshot showing the impact: [imgur tinypng results](http://i.imgur.com/waQnGfj.png)

### CODE REVIEW

**Comment by crookedneighbor** [comment]
The sprites are generated dynamically using a Grunt task, so we cannot use this PR as is. I agree that shrinking the size of the compiled sprites is a good idea, but should be done programmatically in the Grunt task.

We're also slowly moving every task from Grunt to Gulp, so this might be a good time to refactor the spritesmith task anyway. 

Thoughts?

**Comment by Andrux51** [comment]
I actually experimented with shrinking the individual files, but when I ran them through spritesmith they blew back up to near the original size. Basically, the only way to get spritesmith to play nice with smaller files would be to shrink them after the concatenation.

I'll be happy to add this feature into grunt/gulp (would it be preferable to shift the entire task to gulp at this point?)

**Comment by Andrux51** [comment]
Good news, looks like there's a gulp plugin available to do just this! https://www.npmjs.com/package/gulp-imagemin/

**Comment by Andrux51** [comment]
@crookedneighbor I'm looking into this more, it looks like a possible best contender is [sprity](https://www.npmjs.com/package/sprity)

The downside of this plugin is that it can either load all the images into one spritesheet (probably terrible) or split them into separate files by folder (potentially not awesome without some rework) - it also puts everything into a single css file, which even with minification is ~200KB.

Here's what I'm proposing: short term, it looks like there's a plugin for imagemin for Grunt, so I can implement that. Long term, it might make sense to pack the images into folders that will play nice with Sprity, instead of the spritesmith hack that's going on in Grunt.

Let me know what you think. I'll make a PR for grunt-contrib-imagemin for now.

**Comment by crookedneighbor** [comment]
Don't use sprity. When I started a migration to gulp earlier, the spritesmith stuff was the only thing that gave me trouble. I'd prefer us to stick with Grunt for now. 

@gisikw and @SabreCat, looks good to me. Any thoughts from y'all?

**Comment by gisikw** [comment]
:+1: from me!

**Comment by SabreCat** [comment]
Runs great in my dev env. OK by me!

**Comment by crookedneighbor** [comment]
This will count towards a contributor tier! What's your User ID? You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api). Be sure to only copy the User ID and _not_ your API Token.

**Comment by Andrux51** [comment]
Awesome, glad this could help. Here's my user id: `fe5f5afa-8b71-4aa4-ad49-08ac50ed49ac`

For your comment above, there is a gulp plugin for spritesmith, so maybe that'd be a good middle ground.

**Comment by crookedneighbor** [comment]
Congrats, you've just earned yourself your first contributor tier!

If you'd like to learn more about [contributing and contributor rewards, you can do so here](http://habitrpg.wikia.com/wiki/Contributor_Rewards)

**Pull request merged**
