### PR TITLE
fixing #6146 ("Deleting a reward asks you if you want to delete the task")

### PR DESCRIPTION
**Pull request by manonthemat**
fixing #6146 by simply deleting the word "task"

### CODE REVIEW

**Comment by crookedneighbor** [comment]
I think the string should be changed to something like:

```
"Are you sure you want to delete the <%= taskType %> with the text \"<%= taskText %>\"?"
```

The task view would also need to be updated, obviously.

**Comment by crookedneighbor** [comment]
@manonthemat Any update on this?

**Comment by manonthemat** [comment]
Great suggestion, I will update the PR as suggested.

**Comment by crookedneighbor** [comment]
@manonthemat Going to close this for now, but definitely re-open it when you're ready for us to review it.

**Pull request closed without merging**
