### PR TITLE
Added support for a Kubernetes Helm chart !

### PR DESCRIPTION
**Pull request by hclaria**
### Changes

- Added support for a Kubernetes Helm Chart
```
$ helm install --name habitica --namespace habitica . 
NAME:   habitica
LAST DEPLOYED: Fri Jul  5 10:40:09 2019
NAMESPACE: habitica
STATUS: DEPLOYED

RESOURCES:
==> v1/Deployment
NAME      READY  UP-TO-DATE  AVAILABLE  AGE
habitica  0/1    1           0          0s

==> v1/Pod(related)
NAME                          READY  STATUS             RESTARTS  AGE
habitica-55dfb656bd-qnctf     0/1    ContainerCreating  0         0s
habitica-mongodb-arbiter-0    0/1    ContainerCreating  0         0s
habitica-mongodb-primary-0    0/1    ContainerCreating  0         0s
habitica-mongodb-secondary-0  0/1    ContainerCreating  0         0s

==> v1/Secret
NAME              TYPE    DATA  AGE
habitica-mongodb  Opaque  3     0s

==> v1/Service
NAME                       TYPE       CLUSTER-IP     EXTERNAL-IP  PORT(S)    AGE
habitica                   ClusterIP  10.43.33.246   <none>       3000/TCP   0s
habitica-mongodb           ClusterIP  10.43.133.176  <none>       27017/TCP  0s
habitica-mongodb-headless  ClusterIP  None           <none>       27017/TCP  0s

==> v1/StatefulSet
NAME                        READY  AGE
habitica-mongodb-arbiter    0/1    0s
habitica-mongodb-primary    0/1    0s
habitica-mongodb-secondary  0/1    0s

==> v1beta1/Ingress
NAME      HOSTS               ADDRESS  PORTS  AGE
habitica  habitica.localhost  80       0s

==> v1beta1/PodDisruptionBudget
NAME                        MIN AVAILABLE  MAX UNAVAILABLE  ALLOWED DISRUPTIONS  AGE
habitica-mongodb-arbiter    1              N/A              0                    0s
habitica-mongodb-primary    1              N/A              0                    0s
habitica-mongodb-secondary  1              N/A              0                    0s


NOTES:
1. Get the application URL by running these commands:
  http://habitica.localhost/
```
```
$ kubectl get pods -n habitica
NAME                           READY   STATUS    RESTARTS   AGE
habitica-55dfb656bd-qnctf      1/1     Running   0          46s
habitica-mongodb-arbiter-0     1/1     Running   0          46s
habitica-mongodb-primary-0     1/1     Running   0          46s
habitica-mongodb-secondary-0   1/1     Running   0          46s
```
Screenshot from 2019-07-05 10-41-21

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: ee1f0b73-ae25-45ee-825c-3de911e7894f

### CODE REVIEW

**Comment by paglias** [comment]
Hi @M0nsieurChat and thanks for the PR, could you explain what this does and how it improves the current setup?

**Comment by hclaria** [comment]
Helm (https://helm.sh/) is a package manager for Kubernetes, it permits to deploy applications in a standard way on any kubernetes cluster. It's a bit Heroku-like 

It extends this PR : https://github.com/HabitRPG/habitica/pull/6965 but instead of importing raw YAML files into your Kubernetes cluster, you can ask Helm to deploy habitica as an application into your kubernetes cluster.

Helm provides multiple benefits over importing your own YAML files directly on the cluster, such as :
- Versioning of the application template
- Keep track of release history (can do rollback and rollforward)

There's also a README inside the Helm chart directory (https://github.com/HabitRPG/habitica/pull/11256/files#diff-ab8bb3bf2035102c5ec9934e0f25061c) to explain how to deploy Habitica on a Kubernetes cluster using Helm (which is basically `helm install --name habitica --namespace habitica .`)

**Comment by paglias** [comment]
thanks for the explanation, tbh I'm not sure this is something we want to do now even if useful but pinging @SabreCat since he manages most of our dev ops

**Comment by paglias** [comment]
ping @SabreCat

**Comment by paglias** [comment]
Thanks for the PR @M0nsieurChat but I don't think we're currently interested in adopting a Kubernetes Helm Chart so I'm going to close this

**Pull request closed without merging**
