### PR TITLE
Login Incentives

### PR DESCRIPTION
**Pull request by SabreCat**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

Adds a new feature for retention: a ladder of goodies awarded to the user for checking in to Habitica (i.e., triggering cron). The more often or consistently you log in, the more stuff you get!

[//]: # (Put User ID in here - found in Settings -> API)

- [x] https://github.com/HabitRPG/habitica/pull/8230#issuecomment-262410405@TheHollidayInn
- [x] https://github.com/HabitRPG/habitica/pull/8230#issuecomment-262411785 @thehollidayinn
- [ ] https://github.com/HabitRPG/habitica/pull/8230#issuecomment-262344893
- [ ] https://github.com/HabitRPG/habitica/pull/8230#issuecomment-262350509
- [ ] https://github.com/HabitRPG/habitica/pull/8230#issuecomment-262410856 (This can be reproduced from the market page. I believe it is a separate issue with achievements).
- [ ] https://github.com/HabitRPG/habitica/pull/8230#issuecomment-262413309 ( This is happening on the live site as well)
- [ ] https://github.com/HabitRPG/habitica/pull/8230#issuecomment-262415785 @thehollidayinn (Updated the text. I think the plural check should be moved to v2)
- [x] https://github.com/HabitRPG/habitica/pull/8230#issuecomment-262417521 @thehollidayinn
- [x] https://github.com/HabitRPG/habitica/pull/8230#issuecomment-262418141  @thehollidayinn
- [ ] https://github.com/HabitRPG/habitica/pull/8230#issuecomment-262418629 (From Keith: I can't recreate)
- [x] https://github.com/HabitRPG/habitica/pull/8230#issuecomment-262420258 @thehollidayinn
- [x] https://github.com/HabitRPG/habitica/pull/8230#issuecomment-262420701 @thehollidayinn
- [x] https://github.com/HabitRPG/habitica/pull/8230#issuecomment-262421039 @thehollidayinn
- [ ] https://github.com/HabitRPG/habitica/pull/8230#issuecomment-262423507 (Keith: Can't reproduce)
- [ ] https://github.com/HabitRPG/habitica/pull/8230#issuecomment-262424994 @thehollidayinn (I think this was caused by an error I had with text strings. I can't recreate now - so will hold off until it happense again)
- [x] https://github.com/HabitRPG/habitica/pull/8230#issuecomment-262425472 @thehollidayinn
- [x] https://github.com/HabitRPG/habitica/pull/8230#issuecomment-262425447 @thehollidayinn
- [x] https://github.com/HabitRPG/habitica/pull/8230#issuecomment-262425682 @thehollidayinn

### CODE REVIEW

**Comment by lemoness** [comment]
Comments from the Socialites!

"Just possibly discovered one bug. I died, then completed some dailies plus habits then made a day pass... This happened: http://prnt.sc/daipap [missing the title of the background set prize]"

"I don't seem to be able to take damage from dailies.
I tried:
not completing any
completing some but not all
starting a boss quest (the message says boss does 0 damage)"

"I was just customizing my avatar for use over there -- changing hair color and bangs and hair style was fine, but changing to a gray shirt got me an error: https://trello-attachments.s3.amazonaws.com/57ab9e4d4c648b263870b9cb/58349d61834c036fe25573d9/e6fefba90bab47655e27984d63da88b7/Screen_Shot_2016-11-22_at_2.31.46_PM.png"

"When I tried to restart the costume (remove them all) it just didn't work."

Let me know if you need follow-up questions!

**Comment by lemoness** [comment]
"I'm not sure if this is intended, but my Cactus Ears was already unlocked but I just found a pair of the same thing purchasable in the Rewards section?" (possibly due to death?)

Followup to the person who isn't taking damage from tasks overnight -- it also applies to challenge tasks.

"Giving myself 10 gems also gave me 150 xp. Might only be relevant to the test environment."

**Comment by lemoness** [comment]
~"I broke the armoire by giving myself all the equipment manually. Now the armoire still says I have 71 items in there, but when I click literally nothing happens (again, not sure if this is related to the actual feature or just a problem with the test environment)"~ EDIT: looks like this was resolved with a refresh.

There's a report of a Challenge Daily disappearing but the user can't replicate it, so it was probably a server error.

**Comment by TheHollidayInn** [comment]
@lemoness re: "Followup to the person who isn't taking damage from tasks overnight -- it also applies to challenge tasks." **- I believe this is caused because they need to set the start date of the dailies. The +1 day button does not change the day, just the day the last cron ran.**

**Comment by lemoness** [comment]
The new Background set is available to purchase with gems before I've been awarded it. Instead, it shouldn't appear, or should explain that it unlocks with check-ins, not gems.

**Comment by lemoness** [comment]
From Socialites: "When trying to send a greeting card to yourself, you get this error: https://www.dropbox.com/s/fncjmbr2pu5exyu/Screen%20Shot%202016-11-22%20at%207.48.45%20PM.png?dl=0"

I was not able to reproduce it -- the feature worked as expected for me.

**Comment by lemoness** [comment]
check-inincentivestesting1


Some comments on the profile screen: 

- "Checkins" > "Check-Ins"
- The "progress until" section seems like it's missing some information. Possibly just because I'm still at 0, which won't be the case in future iterations?

**Comment by lemoness** [comment]
The Time Travelers don't have any indication of how many mystic hourglasses things cost, though I still can't buy them.

**Comment by citrusella** [comment]
~~When I signed up, I didn't get the dust bunny quest. I tried to add it via the inventory modification button but got a "not found" message (along with what looked like another error that disappeared so fast I didn't get the chance to read it). Refreshing took away access to all debug functions and they won't come back. :flushed: (The last bit resolved itself after the refresh I did right after posting this.)~~

Might have been a random weirdness. Just tried again and got via the modification screen just fine.

**Comment by lemoness** [comment]
check-inincentives2
  A few small text tweaks:

1. "a Bardic Robes"  - can we vary this based on whether or not it's plural? If it's complicated, we can make it a V2 feature. Ditto with "1 check-ins"


2. The spacing is a little clunky and the text isn't scanning quite right, so let's swap in this instead:
"You've earned [a] [prize] for being committed to improving your life!"

**Comment by cTheDragons** [comment]
I entered a daily when it was speaking about adding dailies. (Which effectively stopped it). Daniel? is displaying in the toolbar but I have no way of reactivating again despite a prompt bubble to Continue Tour. Clicking Daniel did not help. After refreshing I was able to continue.
unabletocontinuetour


*Browser Opera 41.0.2353.56 
Windows 10
JS Console Errors:
> moment.js:288Deprecation warning: moment().zone is deprecated, use moment().utcOffset instead. http://momentjs.com/guides/#/warnings/zone/
Arguments: 
Error
    at v.zone (https://habitrpg-gamma.herokuapp.com/js/habitrpg-shared.js:7:7599)
    at Object.authenticate (https://habitrpg-gamma.herokuapp.com/js/services/userServices.js:589:35)
    at Object.<anonymous> (https://habitrpg-gamma.herokuapp.com/js/services/userServices.js:680:22)
    at Object.invoke (https://habitrpg-gamma.herokuapp.com/bower_components/angular/angular.js:4182:17)
    at Object.enforcedReturnValue [as $get] (https://habitrpg-gamma.herokuapp.com/bower_components/angular/angular.js:4035:37)
    at Object.invoke (https://habitrpg-gamma.herokuapp.com/bower_components/angular/angular.js:4182:17)
    at https://habitrpg-gamma.herokuapp.com/bower_components/angular/angular.js:4000:37
    at getService (https://habitrpg-gamma.herokuapp.com/bower_components/angular/angular.js:4141:39)
    at Object.invoke (https://habitrpg-gamma.herokuapp.com/bower_components/angular/angular.js:4173:13)
    at extend.instance (https://habitrpg-gamma.herokuapp.com/bower_components/angular/angular.js:8441:21)k @ moment.js:288
https://m.addthisedge.com/live/boost/ra-5016f6cc44ad68a4/_ate.track.config_resp Failed to load resource: net::ERR_BLOCKED_BY_ADBLOCKER
https://m.addthis.com/live/red_lojson/300lo.json?si=5834f175a58b7de3&bl=1&p…s=5834eedddab9940b001&skipb=1&callback=addthis.cbs.oln9_288508513630113540 Failed to load resource: net::ERR_BLOCKED_BY_ADBLOCKER
addthis_widget.js:2 undefined(anonymous function) @ addthis_widget.js:2
https://fls-na.amazon.com/1/batch/1/OP/A3BXB0YN3XH17H:155-8555593-7445452:6…3D336%26t%3D1479864699401%26ctb%3D1%26csmtags%3Dnonredirect%7CnoAmznJQ:339 Failed to load resource: net::ERR_BLOCKED_BY_ADBLOCKER

**Comment by citrusella** [comment]
Purple potion doesn't have the word "potion" in its award popup. It just says "Royal Purple".

**Comment by lemoness** [comment]
Day 5 was supposed to award Chocolate, Meat, and Pink Cotton Candy, but only Chocolate was mentioned in the modal. All three food items were successfully delivered to my inventory.

**Comment by froggily** [comment]
Double notifications when feeding pets/raising pets to mounts if you switch your language. Unsure about anything else. [(Screenshot)](https://www.dropbox.com/s/v6qhjd67hd8epzk/Screen%20Shot%202016-11-22%20at%208.52.58%20PM.png?dl=0)


Edit: Fixed itself after refresh.

**Comment by lemoness** [comment]
screen shot 2016-11-22 at 5 56 44 pm

Oh dear, this modal looks pretty messy. The information is very confusing, and the "6 check-ins" randomly placed in the middle of the text is also bizarre. It shouldn't show what the prize is yet, and the "6 total count" is very large and doesn't convey that it's the number of check-ins. 

I am okay with us leaving these tweaks until v2, though, especially since nobody will see them for six day after launch, which gives us some buffer.

**Comment by TheHollidayInn** [comment]
@lemoness I was under the impression the prize was supposed to be shown with the count down. I agree the styling of the center is off. That can be adjusted.

**Comment by froggily** [comment]
I apparently earned a <no text> as a reward. 
screen shot 2016-11-22 at 9 15 19 pm

**Comment by citrusella** [comment]
The last few +1 day clicks I've done have immediately brought up modals/awarded items. I didn't think that was how it was supposed to work (in terms of the testing environment), though I don't know whether or not the change in behavior is relevant or important to this.

**Comment by lemoness** [comment]
screen shot 2016-11-22 at 6 18 17 pm

The rest of the paw prints are missing, and the cactus should not be the first pet!

**Comment by TheHollidayInn** [comment]
@citrusella That is expected when debugging the cron.

**Comment by citrusella** [comment]
@TheHollidayInn Okay; it was just requiring a refresh before, so I wasn't sure!

In other news, I got the notification that the backgrounds had unlocked and assumed they'd properly unlocked, but they're still locked on the background page.

**Comment by froggily** [comment]
I'm not getting "+3 gold" or whatever notifications when I sell pet eggs/hatching potions/food. Is this expected?

**Comment by TheHollidayInn** [comment]
@froggily Nope. That is an error. I am not able to reproduce it on the test site though. Can you reproduce after a refresh?

**Comment by froggily** [comment]
@TheHollidayInn Yep, it's still happening.

**Comment by citrusella** [comment]
@lemoness I thought that was how magic potions are supposed to work? (That's the way it works on the main site, and the way I was told it should work when I reported the same thing during v3 testing... It only happens when you don't have a potion of that type and can't purchase it)

**Comment by lemoness** [comment]
@citrusella Interesting! I hadn't noticed it working that way, but as long as it's not specific to this build, it can be temporarily disregarded.

**Comment by CloJo** [comment]
I also didn't receive the Dust Bunny quest when I created a new account.  (Possibly because I used same email address as current live account?)

**Comment by TheHollidayInn** [comment]
@CloJo The Dust Bunny quest will be delivered via a migration.

**Comment by lemoness** [comment]
screen shot 2016-11-22 at 6 53 27 pm

Something very strange is going on here. I shouldn't ever be getting "0 left" in these modals, particularly as I shouldn't be getting the second quest until 22 check-ins.  Furthermore, when this first appeared, it was layered on top of the bardic lute, which is the standard award for the day. 

The following day, everything was back on track.

**Comment by lemoness** [comment]
Thinking about the "X left" and "X total count" phrasing... I think it would be more clear if it didn't display the total count, and instead just showed the avatar and "X more check-ins" under the box.

**Comment by citrusella** [comment]
[Your next prize will unlock in -50 more check-ins!](http://citrusella-flugpucker.tumblr.com/private/153542326018/tumblr_oh2r2lGTLM1rl47k3)

**Comment by froggily** [comment]
Not sure "unlocked" is the right word when you're talking about chocolate.
screen shot 2016-11-22 at 10 05 49 pm

**Comment by cTheDragons** [comment]
rE @froggily post on Chocolate, Maybe the word receive instead of unlock? Found it a bit jarring too when I received some equipment and potions.

**Comment by citrusella** [comment]
@cTheDragons @froggily Or earned?

**Comment by CloJo** [comment]
@citrusella @cTheDragons @froggily Earned gets my vote!

**Comment by cTheDragons** [comment]
Have joined a party but I still have the Battle with Mates icon in the top left.

partystillsayingpartywithmates

**Comment by CloJo** [comment]
Using the Orb of Rebirth at level 100 as a mage wearing mage equipment returned me to level 1 warrior still wearing the mage gear.  Possibly the way it works now after the equipment changes to the Orb?

**Comment by CloJo** [comment]
I'm a level 14 rogue with no skills.  I levelled to 14 with the +1 level at the bottom of the screen, but levelling to level 16 by clicking a habit didn't add the skills to the reward column. 

screen shot 2016-11-23 at 3 18 11 pm

**Comment by CloJo** [comment]
At level 14, I opted out of the class system with the "rogue" box highlighted, but I didn't choose it.  I got the rogue gear in my rewards column, but none of the rogue skills.  Opting back into the system, and choosing rogue at level 16 gave me all the skills.  
screen shot 2016-11-23 at 3 18 11 pm

**Comment by lemoness** [comment]
More comments from Socialites:

"(1) Unallocated stats show '1' even though its actually 49.
(2) Somehow selecting a class (by level 10/3 gems) is difficult ie: pressing mage won't select mage.
(3) Fortify potion not working."

"I accepted the quest in party, but apparently it doesn't show that I accepted it.
Not sure if also a bug on the regular site - Attacked the Monstrous Moon without beginning the quest." (when Alys asked for more info) "Just the notification itself appearing. You know, the one that says, Snowdeath attacks Monstrous Moon for 12.3 damage. Monstrous Moon attacks party for 0.0 damage....I'm 90% sure [it was still in the invitation phase]. I remember seeing the pending / accepted / declined screen when that happened."

**Comment by cTheDragons** [comment]
IS the email notifications working? Just haven't received any notifications for invite to party/ invite to quest/ quest started etc

**Comment by paglias** [comment]
Emails are not setup correctly in the test server so it's normal if
they don't work

2016-11-23 12:12 GMT+01:00, cTheDragons notifications@github.com:

> IS the email notifications working? Just haven't received any notifications
> for invite to party/ invite to quest/ quest started etc
> 
> ## 
> 
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/HabitRPG/habitica/pull/8230#issuecomment-262487066

## 

Matteo Pagliazzi - paglias.net

**Comment by SabreCat** [comment]
@lemoness background set issue: Haha, yup. Thus my "fix backgrounds moar" to-do item...
Socialite greeting card issue: Probably unrelated. Try reproducing with a new account on production.
@lemoness Time Traveler issue: This is how it currently works in production. Worth a separate ticket.
@cTheDragons Justin issue: I believe I've bumped into that elsewhere. Separate ticket.
@froggily double notifications: Peculiar! Try reproducing on production and making a separate ticket.
~@lemoness missing potions: That's definitely acting the way it currently does, **but** the logic should maybe be updated to show them if you can earn the potion via check-in? What do you think?~ @TheHollidayInn went ahead and added a special case for the Royal Purple potion.
~@CloJo @TheHollidayInn: Dust bunnies quest should definitely be awarded immediately to new accounts. Will investigate.~ Should be fixed.
@CloJo Orb of Rebirth: Expected behavior.
@CloJo Rogue bait-and-switch: Unrelated. Separate ticket.
Socialites unallocated stats, class select, fortify potion: Wat. No idea how these issues could be caused by check-in incentives, but will investigate.

**Comment by lemoness** [comment]
V2 fix, NOT necessary before V1 feature rollout: the purple paw prints have some strange formatting.
screen shot 2016-11-23 at 11 36 57 am

**Comment by lemoness** [comment]
@sabrecat @TheHollidayInn When I created a new account, I had the dust bunny scroll in my inventory, but did not receive a popup about it. I went through the whole tutorial first, including checking off a task. Going through the tutorial without checking anything off and skipping the tutorial also did not yield a popup.

Other than that, things are looking really good.

**Comment by froggily** [comment]
Little tiny error: the word is "received," not "recieved."

**Comment by lemoness** [comment]
THE BACKGROUNDS UNLOCK CORRECTLY!! `confetti everywhere`

**Comment by lemoness** [comment]
Newest batch -- looks like all tutorials are triggering the dust bunnies popup @SabreCat

**Comment by lemoness** [comment]
Aha, I think I've figured out what people meant about the avatars -- they're slightly off for me when viewing someone else's avatar:

screen shot 2016-11-23 at 4 49 31 pm


If that's all that people are reporting, it can be fixed in V2.

**Comment by cTheDragons** [comment]
I have received the Dust Bunnies Check in Counter twice.

Actions I took.

+ Created a new account
+ Proceeded through the tutorial directly by click next all the way through.
+ Once the tutorial finished I received Dust Bunnies Check In award
+ I then cron - click the next reward (robes)
+ I then cron - click the next reward (backgrounds)
+ I then when to the backgrounds, click on the blue then red. 
+ Proceeded to the Tavern and met Justin. Click ok 
+ Received the incorrect notification as per below.

dustbunniestwice

I can confirm though I only have one scroll.

**Comment by SabreCat** [comment]
@cTheDragons: Yup, we spotted that too. Fixed in dc19917 above!

**Comment by cTheDragons** [comment]
Thanks ! Too slow again. Everything else worked backgrounds etc. Let me know if you need me to test again.

**Comment by thebat137** [comment]
@lemoness, the strange formatting on the pawprints appears to have to do with old pawprints not being taken away when a pet is acquired --- there are still 9 pawprints in your screenshot, even though two purple pets have been tamed.  (This issue showed up for me as well, and @citrusella pointed me here.)

**Comment by Alys** [comment]
@thebat137 Thank you! I've logged that here: https://github.com/HabitRPG/habitica/issues/8239

**Pull request merged**
