### PR TITLE
Update gear.json

### PR DESCRIPTION
**Pull request by ghost**
Fixed a minor typo on line 284 ('perception' > 'Perception').

### CODE REVIEW

**Comment by Alys** [comment]
I'm sorry @Fasolt but we can't accept this change. The translations (even the "translation" to real English) is handled in Transifex. Have a look at the _README_FIRST.md files in the en_GB directory for details. If you'd like to sign up on Transifex to make this and future changes, you'd be welcome to!

**Comment by ghost** [comment]
Thank you, Alys, and my apologies for the error; I have now signed up to Transifex.

**Comment by SabreCat** [comment]
Apropos of nothing: is your Git username a Banner Saga reference, @Fasolt? If so, :heart:

**Comment by ghost** [comment]
@SabreCat Sorry to disappoint, but I'm afraid not; it's the name of a character in one of my favourite operas.

**Pull request closed without merging**
