### PR TITLE
Prevent submission of blank invitation, fixes #7807

### LINKED ISSUE #7807: Says "Invitations Sent" even if you leave "Email" or "User ID" fields empty
General Info
- UUID: 8389891a-ba52-4580-b08b-2cb706c7e0b4
- Browser: Chrome Version 51.0.2704.103 (64-bit)
- OS: Windows 10
### Description

In the "Invite Friends" window of either party or guild, if you leave the fields "Email" or "User ID" empty and click on the "Send Invitations" button, you will receive a notification saying "Invitations Sent".

### PR DESCRIPTION
**Pull request by JTorr**
Fixes https://github.com/HabitRPG/habitrpg/issues/7807
### Changes

Previous Behavior: Submitting an invite with no email or UUID displayed message 'Invite Sent', and then redirected to Guild or Party page, as with successful submission.

screen shot 2016-09-25 at 6 35 24 pm

Current Behavior:

Email invitations with an empty array of emails triggers a BadRequest error, with message 'Missing Email in Invite.'

UUID invitations with an empty array of UUIDs triggers a BadRequest error, with message 'Missing User ID in Invite.'

Modal window stays open instead of closing and redirecting.

screen shot 2016-09-28 at 9 07 50 pm

screen shot 2016-09-28 at 9 07 38 pm

---

UUID: 1bf2957d-600e-4952-9e7b-d796cf99763d

### CODE REVIEW

**Comment by JTorr** [comment]
@crookedneighbor I closed the other pull request and opened this one. The API now returns an error when email & UUID are both blank.

**Review by crookedneighbor — COMMENTED** [review]
Am I reading this right that it will return an error if you send both emails and uuids properties, but one of them is an empty array?

**Comment by JTorr** [comment]
@crookedneighbor Good question. That wouldn't be possible through the UI, but I hadn't considered users that are accessing the API through other means. I'll change it to return a single error if both UUIDs and emails are empty arrays.

**Comment by JTorr** [comment]
@crookedneighbor Revised this to error only if both the uuids & emails are empty arrays, or if one is an empty array and the other is undefined. I also moved all of the validations / BadRequest errors into the same if/else block, to reduce duplication.

**Comment by crookedneighbor** [comment]
Tier awarded! You can read more about [contributor tiers and rewards here](http://habitrpg.wikia.com/wiki/Contributor_Rewards).

Note that as your tier increases, it takes progressively more work to achieve the next one, so for the higher tiers, larger PRs or a few PRs are required. There's some information about that at Contributor Rewards, but feel free to ask here if you have questions!

**Comment by crookedneighbor** [comment]
FYI, I took your validation checking and moved it to a static method on the group model:

https://github.com/HabitRPG/habitrpg/commit/76499412edbc560e24accf38daf79c99c1db86d5
https://github.com/HabitRPG/habitrpg/commit/24562f8d600463c8819c1aceee92c5c5408b9194

**Comment by JTorr** [comment]
@crookedneighbor Awesome! Thanks!

**Pull request merged**
