### PR TITLE
Place link to Markdown help prominently in Tavern chat (fix #1906)

### LINKED ISSUE #1906: Resource added
Suggestion to add markdown cheat sheet link in the resource panel of tavern. or something similar.

### PR DESCRIPTION
**Pull request by SabreCat**
Added the Markdown help link beneath all chatboxes. This caused an awkward repetition of the link when editing groups, so I stripped the links there and simply clarified in the prompts that Markdown is OK in those fields.

### CODE REVIEW

**Comment by SabreCat** [comment]
Misc tweak to Inventory wording while I have a PR out.

**Comment by SabreCat** [comment]
Also fixed the inaccuracy about Gem rewards for contribution, which was causing some confusion for @bobbyroberts99 et al.

**Comment by bobbyroberts99** [comment]
@SabreCat Just in case you'd rather link to wiki for markdown help, here's a [link](http://habitrpg.wikia.com/wiki/Markdown_Cheat_Sheet).

**Comment by snicker** [comment]
I'd recommend using the wiki link, it's much more concise, but throw a link to the daringfireball page on the wiki page?

**Comment by snicker** [comment]
I took care of the link on the wiki page.

**Comment by lefnire** [comment]
Good stuff. I'm gonna work on getting CI working with Travis to deploy beta to heroku with passing builds, probably tomorrow, so y'all can get your wonderful commits in the wild without me being a bottle neck.

**Comment by SabreCat** [comment]
Cool, thanks for the tip @bobbyroberts99! @lefnire, let me track down where that link template is defined and update it to point at the wiki instead before you merge.

**Comment by SabreCat** [comment]
Done and ready!

**Comment by bobbyroberts99** [comment]
That was quick! I reorganized the table a bit and put the link to daringfireball under the table. The cheat sheet gets inserted in the tavern article so I thought table first was better but don't feel strongly about it. Feel free to put the link back on top if you like.

**Comment by bobbyroberts99** [comment]
@snicker here's an emoji test (everyone ignore this message)
:relaxed:
:smile:
:wink:

**Comment by snicker** [comment]
They display as images on mobile. But I can't seem to post emoji from my phone. It denies the message

**Comment by snicker** [comment]
I believe that has something to do with a limitation on github. Emoji (from a unicode standpoint) are very F'd up things that do not get along with certain flavors of extended character sets. We can probably make it work on HabitRPG though, it's just pretty low priority. the unicode and "colon style" emoji will have to be parsed out and displayed as images.

**Comment by bobbyroberts99** [comment]
Agreed that it's low priority.

**Comment by SabreCat** [comment]
Doop doop, still fussing around on my branch. Today, a few typo fixes in app.json. The area needs more work, hand in hand with the tour overhaul I've been slacking on, but this at least removes a reference to a non-implemented feature (Health loss for Reward overdrafts) and makes our use of "To-Do" instead of "Todo" more consistent.

**Comment by SabreCat** [comment]
Ut oh. Conflicts. Now I prolly couldn't figure out how to merge this even if I had the guts to do so myself :frowning:

**Comment by SabreCat** [comment]
Ah, probably it's because of the updates to submitting issues in the Tavern file. Easy enough to eyeball the resolution, but I'll need to learn how to use the command line for it.

**Comment by lefnire** [comment]
@SabreCat sorry for the lateness, I'll merge this manually.

**Comment by lefnire** [comment]
merged manually (github auto-detected that! man this site is cool). pushing to beta

**Comment by SabreCat** [comment]
Wootsauce! Thanks my good sir!

**Pull request merged**
