### PR TITLE
Change stable text

### LINKED ISSUE #8132: Pet system is not Locked after using the Orb of Rebirth
## General Info

bc10ec41-4213-4482-bbb8-558e3c3ea8d5
Opera 37.0.2178.43
Windows 10 32-bit
## Description

Reported as per @Alys instructions
After using the Orb of Rebirth my pet was automatically unequipped. However I am able to do all things with my pets and mounts as before except receive drops. This is the case with App (Android v) and Website client.

Things tested:

| Action | Web | Android App |
| --- | --- | --- |
| Creating New Pet | Yes | Yes |
| Feeding Pet | Yes | Yes |
| Feeding a Pet Till Mount | Yes | Yes |
| Equipping Avatar With Pet | Yes | Yes |
| Equipping Avatar With New Mount | Yes | Yes |

I assume even though the Pet system is locked, players still should receive rewards from Pet Quests.

### PR DESCRIPTION
**Pull request by librarianmage**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #8132 

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

screenshot 2016-12-01 at 10 05 56 pm

[//]: # (Put User ID in here - found in Settings -> API)

----
UUID: 95f16006-1504-4a9f-95b6-0c7314dbd7ee

### CODE REVIEW

**Comment by khipkin** [comment]
Suggestion: Why not include food in the initial list of things found after level 3? Seems weirdly like an afterthought at the end of the text block.

**Comment by librarianmage** [comment]
@Alys, what do you think?

**Comment by TheHollidayInn** [comment]
Does the text change once you are level 3?

**Comment by Alys** [comment]
I'm going to merge this as-is even though the wording isn't perfect. I do like that it talks about only eggs and potions and creating pets first (food isn't relevant for creating pets) and then introduces food later after it's explained how to create a pet. Maybe that order helps new users understand that eggs and potions go together. Anyway, it fixes the original confusion in the issue.

I'm not worried about the text becoming less relevant after you've already reached level 3. We don't change the other Justin texts, and it fades into the background anyway once you've seen it a few times.

Notated. Thanks @MathWhiz !

**Pull request merged**
