### PR TITLE
Fix removing user salt+hash from API response

### LINKED ISSUE #5800: Remove sensitive informations from API endpoints
The /user endpoint returns hashed_password + salt, these should never be required in any application using the API, and should be removed.

Related (old) issue #1914

### PR DESCRIPTION
**Pull request by 3onyc**
Fixes #5800 

_Note: untested, can't get the development environment to work (see #5801)_

### CODE REVIEW

**Comment by crookedneighbor** [comment]
This _must_ have tests around this behavior  before we will merge it in. Since you are not able to get a local instance up and running, I will add the tests when I have time.

**Comment by 3onyc** [comment]
This is the contents of an example `auth.facebook`, I'd say only keep displayName (and for `auth.local` only keep the username).

``` json
"facebook": {
  "id": "%user_id%",
  "username": null,
  "displayName": "First Last",
  "name": {
    "familyName": "Last",
    "givenName": "First",
    "middleName": null
  },
  "gender": "%gender%",
  "profileUrl": "https://www.facebook.com/app_scoped_user_id/%user_id%/",
  "emails": [
    {
      "value": "email@example.com"
    }
  ],
  "provider": "facebook",
  "_raw": "{\"id\":\"%user_id%\",\"email\":\"email\\u0040example.com\",\"first_name\":\"First\",\"gender\":\"%gender%\",\"last_name\":\"Last\",\"link\":\"https:\\/\\/www.facebook.com\\/app_scoped_user_id\\/%user_id%\\/\",\"locale\":\"en_US\",\"name\":\"First Last\",\"timezone\":2,\"updated_time\":\"2015-08-16T15:14:08+0000\",\"verified\":false}",
  "_json": {
    "id": "%user_id%",
    "email": "email@example.com",
    "first_name": "First",
    "gender": "%gender%",
    "last_name": "Last",
    "link": "https://www.facebook.com/app_scoped_user_id/%user_id%/",
    "locale": "en_US",
    "name": "First Last",
    "timezone": 2,
    "updated_time": "2015-08-16T15:14:08+0000",
    "verified": false
  }
```

**Comment by crookedneighbor** [comment]
Added tests for the items that are deleted. 

This will count towards a contributor tier! What's your User ID? You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api). Be sure to only copy the User ID and _not_ your API Token.

**Comment by 3onyc** [comment]
@crookedneighbor What's your thought on the Facebook auth, so I can get that done too.

Additionally, I think we should test explicitly that only the email+username are returned (similar for Facebook), to prevent any accidental sensitive information leaks in the future.

Anyway, **User ID:** `46b31968-121c-4bd5-ab43-ff06d010eb34`

**Comment by crookedneighbor** [comment]
I've notated this toward your next tier. 

Re: the test, feel free to submit a PR for it. I'll review it then.

Re: Facebook. Not sure. I can see applications for keeping some of that data.

**Pull request merged**
