### PR TITLE
Removed labels of potions and eggs in inventory list

### PR DESCRIPTION
**Pull request by nafoster**
I remember pitching the idea of removing the labels of potions and eggs in the inventory list to help spacing problems, especially with the Cotton Candy potions. With two indicators of what the potion/egg is, a label acting as a third is unnecessary imo.

The pull request discussion I was referencing: https://github.com/lefnire/habitrpg/pull/1224

Also, I'm new to pulling on GitHub, so if I did something wrong, feel free to revert anything.

### CODE REVIEW

**Comment by SabreCat** [comment]
Ooh. Got a screenshot?

**Comment by nafoster** [comment]
habitrpg - gamify your life

**Comment by SabreCat** [comment]
Niiice. How do I upvote this? ^.^

**Comment by nafoster** [comment]
Sorry, new to Git and GitHub, so I didn't know that all my new commits would be pushed to this pull request.

Added commit: expanded width of .option-short input to 4em to allow for typing 100 or more for gold rewards. 

From issue: https://github.com/lefnire/habitrpg/issues/1269

Screenshot of fix below:

habitinputfix

**Comment by lefnire** [comment]
Looks like something went wrong in this pull request. see [this screenshot](https://www.evernote.com/shard/s17/sh/3ff24d14-6ae2-435f-aa6a-feccc5acd469/9b40721a7259cdaefa504c2242134744) 391 files changed, 205k deletions. Also, we have a workflow of doing pull-requests against develop instead of master so that we can test it first on beta.habitrpg.com and then merge into habitrpg.com once it's tried-n-true.

No fault of yours of course, I stupidly don't have any of this stuff documented anywhere (I need to get on that). I'd start from scratch, checkout develop, apply your changes manually again, re-pull-request:
- On github.com, delete your fork, then re-fork (but keep your local checkout handy so you can copy in your original changes)
- `git clone --recursive -b develop https://github.com/nafoster/habitrpg.git habitrpg_round2`
- `cd habitrpg_round2`
- make your changes
- `git commit -am 'Revert to previous 3em width, expanded width of input to allow for inputs of 100+'`
- `git push origin develop`
- create new pull-request against lefnire:develop 
- close this PR, add link to new one

Sorry for all those steps. If you prefer, you can just show me the changes that need to be made and I can do them myself. Let me know if you need any help

**Comment by nafoster** [comment]
Sorry for all the trouble! I'll take care of those, but in the meantime, the changes were super simple so you can implement them if you like:

For removing the inventory labels, add this to inventory.styl:

```
 .inventory-list p
    display: none
```

and for expanding the width of .option-short, change width: 3em to width: 4em in this block of code in tasks.styl

```
.option-short
  .option-content
    width: 4em
    display: inline-block
```

**Comment by nafoster** [comment]
Here's the new pull request that should be done right: https://github.com/lefnire/habitrpg/pull/1274

Thank you for your help Tyler.

**Pull request closed without merging**
