### PR TITLE
Minor bug: In challenges area, Join button has a yellow background

### PR DESCRIPTION
**Pull request by holyspecter**
https://www.bountysource.com/issues/1439320-minor-bug-in-challenges-area-join-button-has-a-yellow-background

### CODE REVIEW

**Comment by paglias** [comment]
@holyspecter thanks! could you post a before and after screenshot?

**Comment by paglias** [comment]
#3069

**Comment by holyspecter** [comment]
@paglias yep. Here is before screenshot: 
selection_001
and here is after:
selection_002

There is no label like "Official HabitRPG Challenge" on my "after" screenshot, but it should be fixed too.

**Comment by lefnire** [comment]
sweet. @holyspecter UUID?

**Comment by holyspecter** [comment]
@lefnire 
User ID: 31c68fa6-0028-427e-bf7d-715be49f3e68

**Comment by lefnire** [comment]
@holyspecter contrib.lvl++, thanks!

**Pull request merged**
