### PR TITLE
Fix Death Modal

### LINKED ISSUE #7132: The death modal looks messy on small screens
The [death modal](https://github.com/HabitRPG/habitrpg/blob/develop/website/views/shared/modals/death.jade) looks messy for me both on Opera for Android and FF for win - when viewed with small window width

Screenshot is taken in Russian to show all the issues:
scr
- image and text look misplaced
- dontDespair heading overlaps the image
- the button with refillHealthTryAgain caption needs wrapping (e.g. using the class introduced with https://github.com/HabitRPG/habitrpg/pull/5586 )

### PR DESCRIPTION
**Pull request by librarianmage**
Fixes https://github.com/HabitRPG/habitrpg/issues/7132
### Changes

Fix death modal (pictures are using Russian to show fix):
image
image

---

UUID: 95f16006-1504-4a9f-95b6-0c7314dbd7ee

### CODE REVIEW

**Comment by crookedneighbor** [comment]
Seems reasonable to me. Could you change your git message to be more descriptive of what the change was? If I was to look through the git history, I would have no idea what you did based on the message alone.

**Comment by librarianmage** [comment]
Sure!

**Comment by librarianmage** [comment]
Done!

**Comment by crookedneighbor** [comment]
Notated toward your next tier.

**Pull request merged**
