### PR TITLE
Task notes now disappear when they are deleted from the main task. Fix #11152 

### LINKED ISSUE #11152: task Notes don't disappear when deleted (client-side cache bug)
On the website, if you have a task with a note and you delete the note, the note still appears when you view the task until you reload the website.

It is however deleted from the task immediately (I've confirmed that by database searches) so this is just a website client-side caching problem.

If you change the text of the note, the change appears immediately so this bug seems to be just related to deleting the whole note.

Reported by cTheDragons and godless_toast, confirmed by me.

### PR DESCRIPTION
**Pull request by garayj**
[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes issue: task Notes don't disappear when deleted (client-side cache bug) #11152

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
Changed the v-markdown component to a v-html component. This seems to fix the issue of the notes persisting after deleted.

### CODE REVIEW

**Comment by paglias** [comment]
Thanks @garayj but it looks like this way markdown in tasks notes won't be rendered correctly

**Comment by garayj** [comment]
@paglias Ok, I hopefully got it this time. I didn't want to break anything by changing the logic from if-if to if-else so I just added on to the second if statement. The markdown now works as intended!

**Comment by paglias** [comment]
thanks @garayj !

I'd only ask for a last change to be sure the markdown library doesn't create issues with empty strings

```
if (value) {
    el.innerHTML = habiticaMarkdown.render(String(value));
} else {
    el.innerHTML = '';
}
```

**Comment by paglias** [comment]
Thanks @garayj ! It's working well and will go live next week :) If you have an Habitica UUID or Username I'll be happy to award a contribution tier for this PR

**Comment by garayj** [comment]
Thanks so much @paglias ! My UUID is 48bdc7c5-cd7e-4c66-b88e-cdc2e642b512. Thanks again!

**Comment by paglias** [comment]
Welcome to the first contributor tier!

Note that further tiers require increasing amounts of work from one to the next, so Tier 2 may require a couple of PRs or a larger PR to attain. But keep helping out and we'll express our gratitude accordingly! your profile :)

**Pull request merged**
