### PR TITLE
Add SpacePenguin's Theme

### PR DESCRIPTION
**Pull request by librarianmage**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

Add SpacePenguin95's (user id: f88a9110-4638-456b-a60e-39bc4db4ae17) theme

[//]: # (Put User ID in here - found in Settings -> API)

----
UUID:

### CODE REVIEW

**Comment by negue** [comment]
Some of the audio files have two seconds without any sound, @MathWhiz could you ask the creator to cut the "empty" parts out?

Those empty seconds probably increase the file-size, which takes longer to load for users with a slower connection, also it could produce unexpected results if sounds are played after another.

**Comment by librarianmage** [comment]
Do you have a list of which sounds have the extra time?

**Comment by negue** [comment]
Sorry for the late response 😞 , I've tested all mp3's , each file has about 2 seconds extra time, I guess the ogg files share the same length

**Comment by librarianmage** [comment]
@negue I have heard no response from the theme creator; do you have any other suggestions?

**Comment by negue** [comment]
@Pizilden could you help out and maybe trim the files?

**Comment by SalethiNat94** [comment]
@negue @MathWhiz [Here is the link](https://drive.google.com/open?id=1sz8wmpV6-viVFQgIk76o-q1WX686g-yN) to the trimmed files! Sorry for the delay

**Comment by librarianmage** [comment]
Oh my, thank you!

**Comment by negue** [comment]
@Pizilden thank you! 
Tested the sounds, now those are good to go 👍 

@MathWhiz could you update the files and merge from develop ?

**Comment by librarianmage** [comment]
@SabreCat Are these no longer added to my entry in the Hall?

**Pull request merged**
