### PR TITLE
#1623 - charts: readable (vertical) labels on horizontal axis

### PR DESCRIPTION
**Pull request by rcichy**

### CODE REVIEW

**Comment by deilann** [comment]
Ooooh, can we get a screenshot? I am excite about this.

**Comment by rcichy** [comment]
Here: https://github.com/HabitRPG/habitrpg/issues/1623#issuecomment-46110467

**Comment by deilann** [comment]
Ahh, awesome! Merging, contrib level granting!

**Comment by rcichy** [comment]
> @deilann 
> contrib level granting

My contrib level in hall is 1, but description notice about level 2. I am on level 2 or in progress to level 2? I am asking because it's not explicit :-)

**Comment by deilann** [comment]
I pressed the wrong button.

**Pull request merged**
