### PR TITLE
Fixes feeding modal display text

### PR DESCRIPTION
**Pull request by katerberg**

### CODE REVIEW

**Comment by colegleason** [comment]
Can you update it to replace "a" with food.article?

**Comment by katerberg** [comment]
Done. Am I reading the content.coffee file incorrectly when I read that Saddle is a food that is missing article? Don't want to reference the undefined there.

**Comment by colegleason** [comment]
Saddle doesn't hit that point in the if statement so that's fine.

**Comment by katerberg** [comment]
@colegleason I looked at it and it looks like all the articles have a space after them already e.g. "a "

**Comment by katerberg** [comment]
The latest commit modifies pet names per @deilann 's request on https://github.com/HabitRPG/habitrpg/issues/2431

**Comment by colegleason** [comment]
Sorry to make this such a big terrible commit for a small change @diablomarcus, but that last commit broke a test (click the red x by the commit number there to see why). Can you fix it please?

**Comment by katerberg** [comment]
Absolutely. I need to get it properly set up on my box to ensure that
doesn't happen again. I'll get it in tomorrow. Appreciate the help!

**Comment by colegleason** [comment]
You don't need to fix the test actually. Just change that last commit to not modify the pet variable.

**Comment by katerberg** [comment]
Fixed it!

**Comment by colegleason** [comment]
Cool, thanks!

@lefnire Can we get a contrib.lvl++?

**Comment by lefnire** [comment]
was just gonna say @colegleason, feel free to merge PRs. I'm gonna set you as a GM so you can grant rewards if you feel up to it

**Comment by colegleason** [comment]
Sure.

On Fri, Jan 17, 2014 at 9:47 PM, Tyler Renelle notifications@github.comwrote:

> was just gonna say @colegleason https://github.com/colegleason, feel
> free to merge PRs. I'm gonna set you as a GM so you can grant rewards if
> you feel up to it
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/pull/2439#issuecomment-32673683
> .

## 

## Cole Gleason

Student, University of Illinois at Urbana-Champaign
Email: cg@colegleason.com
Website: colegleason.com

**Comment by lefnire** [comment]
(go [here](https://habitrpg.com/#/options/groups/hall/heroes) for that)

**Comment by colegleason** [comment]
@diablomarcus can I get you UUID please?

**Comment by katerberg** [comment]
@colegleason For sure: b38cb051-4eb8-4ba7-aef1-c37728debd7f    Thanks!

**Pull request merged**
