### PR TITLE
Losslessly recompressed images

### PR DESCRIPTION
**Pull request by Olathe**
[Smush.it](http://smush.it/) is a website that will losslessly recompress images. This means that every pixel will be exactly the same (including PNGs with alpha and JPEGs) but the file sizes will be smaller.

If others want to use it, some caveats (that I've handled properly in this pull) when using it:
- Choose to download a ZIP file to get the images without mangled filenames.
- I doubt we'll use GIFs, but it might change nonanimated ones to PNGs.
- It will rename `favicon.ico` to `favicon.ico.png`.

I've heard talk about Gittip. If this is used, I changed a lot of files but didn't do any creative work, so I'm not sure if that's handled properly.

### CODE REVIEW

**Comment by Pandoro** [comment]
Hmmm, sounds like a nice idea, but I checked the files. In fact it is not lossless. It might be actually true that it is lossless, but the site seems to have tampered with the color a little. All of the new files are darker than the original ones. Furthermore I am wondering if it will really pay of. For the pets it might seem like a big difference, but as soon as they will be merged to 1 png with a corresponding CSS file, the difference won't be so big (as you can already see with the shop, male and female spritesheets.) 

So honestly I doubt that the additional effort will be worth it. Any reason why you think this is really needed?

**Comment by Olathe** [comment]
Do the files look darker in a browser or something else?

If it looks different in an image editing program, which one?

If a browser, can you please attach a screenshot (like of https://github.com/lefnire/habitrpg/pull/418/files) so that I can verify it and stop using Smush.it elsewhere?

As far as the effort, if no one else wants to spend the time, that's no problem. I'll occasionally make pull requests for it. I like doing it to reduce data charges and page load times for very bad connections (like I'm on sometimes) and so on. It seems quite similar to the Javascript minification that's done on the site already.

**Comment by Pandoro** [comment]
when saved you are right, there is no difference, but in the browser I can see a clear difference. (windows 7, FF)
comparison

I took a screenshot, selected both gray colors in the large center of the helmet and drew some blobs next to each other where you can see a clear difference. And well in general I think you can see the overall difference in the images.

**Comment by Olathe** [comment]
Ahh, it appears you're right. That one looks different in Chrome, too, which can be seen best with the `Swipe` method. I'll look into why and whether there are alternatives.

Thanks for letting me know :D

**Comment by lefnire** [comment]
@Pandoro since you're a repo admin, and more familiar with the graphics side, I'll leave it to you to do merge the pull request if / when this is in a good spot (if that's ok)

**Comment by Pandoro** [comment]
@lefnire, sure, sounds fine to me. I will only merge stuff without code
though. I don't want to mess up anything. That would include CSS stuff
though, as I think you should probably give it a quick test spin before
putting it onto the server.

Let's see what @Olathe finds out regarding this thing. I think it might not
hurt, but honestly I don't think the png standard will be optimizable
easily without actually changing the pixels :x If it is possible though,
I'll merge it :)

**Comment by Olathe** [comment]
Hello, @Pandoro.

I've become swamped with work, but I looked into the problem. The RGBA values were preserved perfectly, but the color profile stored with the images was deleted. Because it was `Generic RGB Profile` instead of the standard `sRGB built-in`, color-profile-aware programs like browsers will alter how they display them.

In case I get hit by a bus or something and anyone else cares, here's what I've found so far.

Gimped
(by manually using Gimp and then PNGOUT, the above file is now only 199 bytes instead of 1825, and I think it looks the same now)

[Gimp](http://www.gimp.org/) can convert them **flawlessly** out of the box, which would be great, but I haven't yet found a way to automate that. I found that ImageMagick can <b><i>almost</i></b> do it on the command line, reducing the file size of the smaller images considerably:
<code>convert file.png -profile [sRGB.icc](http://www.color.org/srgbprofiles.xalter) -alpha set -strip file.new.png</code>

I tried that with the [sRGB v4 Preference profile](http://www.color.org/srgbprofiles.xalter#v4pref), but that slightly altered the greys so that they weren't quite grey (like `#cccccd` instead of `#cccccc`), which was not lossless and which ruined automatic use of PNG's greyscale storage schemes. Perhaps another profile on that page will work flawlessly like Gimp.

When I finally get that sorted out, I plan on using [OptiPNG](http://optipng.sourceforge.net/) and [Deflopt](http://www.walbeehm.com/download/) and I already have a hacked-out Ruby script ready to go to aggressively use [PNGOUT's Linux version](http://www.jonof.id.au/kenutils) (for use in [the Windows version](http://advsys.net/ken/utils.htm), change the `-argument` format to `/argument`) on a file for a set amount of time. Usage is `compress file.png seconds` (note that the seconds only start counting down once it figures out what options to reuse):

``` ruby
#!/usr/bin/env ruby

require 'open3'
require 'fileutils'

THREAD_COUNT = 6

if ARGV[0].nil?
  puts "Needs an argument: file.png"
  exit 1
end

puts "[#{ Time.now }] #{ ARGV[0] } started out at #{ File.size ARGV[0] } bytes"

# PNGOUT will automatically set the file extension to '.png', so let's make sure to handle it nicely.
if File.extname(ARGV[0]) == '.png'
  filename = ARGV[0]
else
  filename = ARGV[0] + '.png'
  FileUtils.cp ARGV[0], filename
end

puts "[#{ Time.now }] Finding best options"
opts = []
args = ['pngout', filename, '-v', '-y', '-kt', '-k0']
[0, 2, 3, 4, 6].each do |c|
  args << "-c#{ c }"
  (((c == 0) or (c == 3)) ? [1, 2, 4, 8] : [nil]).each do |d|
    args << "-d#{ d }" unless d.nil?
    [0, 1, 2, 3, 4, 5].each do |f|
      args << "-f#{ f }"
      [0, 1, 2, 3].each do |s|
        args << "-s#{ s }"
        (1..20).each do |n|
          args << "-n#{ n }"
          opts << args.dup
          args.pop
        end
        args.pop
      end
      args.pop
    end
    args.pop unless d.nil?
  end
  args.pop
end

threads = []
results = []
THREAD_COUNT.times do
  threads << Thread.new do
    loop do
      thr_args = opts.pop
      break if thr_args.nil?
      output, status = Open3.capture2e(*thr_args)
      redo if status.exitstatus == 1
       results << [Integer(output.scan(/\sOut:\s*(\d+) bytes/m).first.first), thr_args] unless status.exitstatus == 3
    end
  end
end
threads.each { |t| t.join }
results.sort!

$running = true
$best = results.first.first
threads = []
num = 1
results.first(THREAD_COUNT).each do |bytes, args|
  puts "[#{ Time.now }] Thread #{ num }: #{ bytes } bytes from #{ args.join(' ').inspect }"
  threads << Thread.new(num, args) do |thr_num, thr_args|
    thr_args += ['-r']
    while $running
      output, status = Open3.capture2e(*thr_args)
      redo if status.exitstatus == 1
      unless status.exitstatus == 3
        size = Integer(output.scan(/\sOut:\s*(\d+) bytes/m).first.first)
        if size < $best
          $best = size
          puts "[#{ Time.now }] New best: #{ size } bytes from #{ thr_args.join(' ').inspect }"
        end
      end
    end
  end
  num += 1
end
puts "[#{ Time.now }] Randomizing tables"
sleep(ARGV[1].nil? ? 60 : Integer(ARGV[1]))

puts "[#{ Time.now }] Shutting down"
$running = false
threads.each { |t| t.join }

# Fix the filename back to one without '.png' if needed.
FileUtils.mv filename, ARGV[0] unless filename == ARGV[0]

puts "[#{ Time.now }] Best was #{ $best } bytes"
```

**Comment by Pandoro** [comment]
Hey, I was away for a few days and rather busy. This sounds cool :) Once we
get some stuff done this will probably really be worth converting them once
and getting that done.

Sadly I really don't have time for this right now :( But if you want, feel
free to apply it to the CSS sprite images already. Once we get all the new
stuff into sprites we can really get working on this and reduce that size :D

I am interested to know though, how would I do this with GIMP? I normally
use gimp and creating the CSS sprites is pretty much not really automated,
but rather manual effort. Saving it in a special way is no real big added
effort.

**Comment by Olathe** [comment]
@Pandoro,

I've found out the manual conversion method. Go to the `Image` menu, `Mode`, `Convert to Color Profile...`. Then, use the options `RGB workspace (sRGB built-in)`, `Perceptual`, and _no_ `Black Point Compensation`. Then click `Convert`.

I also finally have a somewhat nice setup now on Ubuntu 12.10 with Gimp 2.8, PNGOUT, and Ruby 1.9. It includes a much-improved version of the script above. I'm going to let it run for a day and see what I get.

It has a few deficiencies: it only deals with PNG files (though it assumes that `favicon.ico` is a PNG file in disguise), and it doesn't deal well with adding new files. It handles all the PNG files in the repository, though, including autoconverting them to sRGB.

I've included some instructions, if anyone is interested. Let me know if they are flawed.

## Compressing PNGs

Once everything is set up, run the following:

``` shell
git clone git://github.com/lefnire/habitrpg.git
cd habitrpg
png-to-srgb-all
make-compress-script
./compress-all
```

Let it run until new improvements are very rare or until you feel like stopping it. Otherwise, it will literally run forever, trying random improvements.

Once you get through all the steps except the last one, you can run `./compress-all` any time you like. You can also stop it any time you like and pick back up later.

If you add new files, you should run `make-compress-script` to generate a new `./compress-all`, unless you can figure out how to add entries manually.

## Setting everything up

Run the following:

``` shell
sudo apt-get install gimp ruby wget
wget -qO- http://static.jonof.id.au/dl/kenutils/pngout-20130221-linux.tar.gz | tar -xz
find -maxdepth 1 | grep -P pngout-\\d+-linux | xargs gnome-open
```

The folder names are possible processor types. Figure out which is closest to your processor (if you're unsure, try `x86_64`, since just about all PCs made in the past several years have that and it's the fastest option), then run the following, replacing `PROCESSOR_NAME` with the exact name of the folder.:

``` shell
find -maxdepth 1 | grep -P pngout-\\d+-linux | xargs -I dirname sudo cp --preserve=mode,timestamps dirname/PROCESSOR_NAME/pngout /usr/local/bin
rm -rfI pngout-*-linux
```

Save the following to `/usr/share/gimp/2.0/scripts/png-to-srgb.scm`:

``` scheme
(define (png-to-srgb pattern)
  (let* (
      (filelist (cadr (file-glob pattern 1)))
    )
    (while (not (null? filelist))
      (begin
        (catch ()
          (let* (
              (filename (car filelist))
              (image (car (file-png-load RUN-NONINTERACTIVE filename filename)))
            )
            (begin
              (plug-in-icc-profile-apply-rgb RUN-NONINTERACTIVE image 0 0)
              (file-png-save2 RUN-NONINTERACTIVE
                  image (car (gimp-image-get-active-drawable image))
                  filename filename
                  0 9 0 0 0 0 0 0 0)
              (gimp-image-delete image)
            )
          )
        )
        (set! filelist (cdr filelist))
      )
    )
  )
)
```

Save the following to `/usr/local/bin/png-to-srgb-all`:

``` ruby
#!/usr/bin/env ruby
require 'open3'

puts "Converting PNGs to sRGB color profile"
favicons = Dir['**/favicon.ico'].map! { |filename| File.expand_path filename }
pngs = Dir['**/*.png'].map! { |filename| File.join(File.dirname(File.expand_path(filename)), '*.png') }.uniq.sort!

output, status = Open3.capture2e(*(['gimp-console', '-i', '-d', '-f'] + (favicons + pngs).sort!.map! { |filename| ['-b', "(png-to-srgb \"#{ filename }\")"] }.flatten + ['-b', '(gimp-quit 0)']))
puts output
p status
```

Save the following to `/usr/local/bin/make-compress-script` (change `ThreadCount` at the top from 2 to how many processor cores you have, hyperthreaded included):

``` ruby
#!/usr/bin/env ruby
require 'open3'
require 'tempfile'

ThreadCount = 2

Infinity  = 1.0/0.0
Filenames = Dir['**/favicon.ico', '**/*.png'].map! { |filename| File.expand_path filename }
BestSizes = Hash.new { |h, filename| h[filename] = [Infinity, nil] }

def pngout args
  args = args.dup
  filename = args[1]
  if File.extname(filename) == '.png'
    temp_file = nil
  else
    temp_file = Tempfile.new(['pngout-needs-png-extension-', '.png'])
    temp_file.close
    FileUtils.cp filename, temp_file.path
    args[1] = temp_file.path
  end

  exit_code = 1
  while exit_code == 1
    output, status = Open3.capture2e *args
    exit_code = (output =~ /unsupported format/) ? 3 : status.exitstatus
  end

  unless temp_file.nil?
    FileUtils.cp temp_file.path, filename if exit_code == 0
    temp_file.unlink
  end

  if exit_code == 3
    nil
  else
    Integer(output.scan(/Out:\s*(\d+) bytes/m).last.first)
  end
end

def process_file filename
  puts "[#{ Time.now }] Starting to process #{ filename }"
  args = ['pngout', filename, '-v', '-y', '-kt', '-k0']
  [0, 2, 3, 4, 6].each do |c|
    args << "-c#{ c }"
    # Only continue trying this color type if it can work
    unless pngout(args + ['-f0', '-s4', '-n1']).nil?
      (((c == 0) or (c == 3)) ? [1, 2, 4, 8] : [nil]).each do |d|
        args << "-d#{ d }" unless d.nil?
        # Only continue trying this bit depth if it can work
        if d.nil? or pngout(args + ['-f0', '-s4', '-n1']).nil?
          [0, 1, 2, 3, 4, 5].each do |f|
            args << "-f#{ f }"
            (f == 0 ? [0, 4] : [0]).each do |s|
              args << "-s#{ s }"
              # Try uncompressed once: some really small files do better.
              if s == 4
                args << '-n1'
                pngout args
                args.pop
              else
                best_size = Infinity
                best_n = 1
                n = 1
                while n <= best_n + 3
                  args << "-n#{ n }"
                  size = pngout args
                  unless size.nil?
                    if size <= best_size
                      best_size = size
                      best_n = n
                    end
                    BestSizes[filename] = [size, args.dup] if size < BestSizes[filename].first
                  end
                  n += 1
                  args.pop
                end
              end
              args.pop
            end
            args.pop
          end
        end
        args.pop unless d.nil?
      end
    end
    args.pop
  end
  size, args = BestSizes[filename]
  if size == Infinity
    puts "[#{ Time.now }] Cannot handle #{ filename }"
  else
    puts "[#{ Time.now }] Best: #{ size } bytes with #{ args.first } \"#{ filename }\" #{ args[2..-1].join(' ') }"

    # Try the other -s settings once just in case they are smaller
    (1..3).each { |temp_s| pngout(args[0..-3] + ["-s#{ temp_s }", args.last]) }
  end
end

Array.new(ThreadCount) do
  Thread.new do
    filename = Filenames.shift
    until filename.nil?
      process_file filename
      filename = Filenames.shift
    end
  end
end.each { |thr| thr.join }

File.open('compress-all', 'wb') do |script|
  script.chmod(0755)
  script.puts <<"END"
#!/usr/bin/env ruby
require 'open3'
require 'tempfile'

ThreadCount = #{ ThreadCount }

Args = [
END
  BestSizes.keys.sort.each do |filename|
    size, args = BestSizes[filename]
    script.puts "  #{ (args + ['-r']).inspect }," unless size == Infinity
  end
  script.puts <<'END'
]
FileCount = Args.length
FileSizes = Hash.new { |h, filename| h[filename] = File.size filename }

def pngout args
  args = args.dup
  filename = args[1]
  if File.extname(filename) == '.png'
    temp_file = nil
  else
    temp_file = Tempfile.new(['pngout-needs-png-extension-', '.png'])
    temp_file.close
    FileUtils.cp filename, temp_file.path
    args[1] = temp_file.path
  end

  exit_code = 1
  while exit_code == 1
    output, status = Open3.capture2e *args
    exit_code = (output =~ /unsupported format/) ? 3 : status.exitstatus
  end

  unless temp_file.nil?
    FileUtils.cp temp_file.path, filename if exit_code == 0
    temp_file.unlink
  end

  if exit_code == 3
    nil
  else
    Integer(output.scan(/Out:\s*(\d+) bytes/m).last.first)
  end
end

Array.new(ThreadCount) do
  Thread.new do
    loop do
      Args.shuffle.each do |args|
        filename = args[1]

        old_size = FileSizes[filename]
        new_size = pngout args
        if old_size > new_size
          puts "[#{ Time.now }] #{ old_size } => #{ new_size } (#{ filename })"
          FileSizes[filename] = new_size
        end
      end
    end
  end
end.each { |thr| thr.join }
END
end

puts "[#{ Time.now }] ./compress-all generated!"
```

Run the following:

``` shell
sudo chown root:root /usr/local/bin/png-to-srgb-all /usr/local/bin/make-compress-script /usr/share/gimp/2.0/scripts/png-to-srgb.scm 
sudo chmod 0755 /usr/local/bin/png-to-srgb-all /usr/local/bin/make-compress-script
sudo chmod 0644 /usr/share/gimp/2.0/scripts/png-to-srgb.scm
```

**Comment by Pandoro** [comment]
Hey there :)

I actually tried the manual way and that had no effect whatsoever, maybe
this is actually the default in newer gimp versions?

Could you try your script on this:
https://github.com/Pandoro/habitrpg/blob/811e9a673cab49ff7c16a5b6aa0f195c25419458/public/img/sprites/player_sprites.png
to see if it has any effect?

**Comment by Olathe** [comment]
@Pandoro,

Original: 14,739 bytes (100.0%)
Smush.it: 14,652 bytes (99.4%)
My setup: 11,321 bytes (76.8%)

It will probably get it smaller if I let it run longer, but it's tapering off, so probably not by much. Here's the current version for comparison with the original:

player_sprites

**Comment by Pandoro** [comment]
@Olathe Very nice work! 

This is indeed a substantial reduction and with more and more assets coming in, this will eventually really make sense.

I must say, I don't have the time for it right now :x If you shoot a pull request, I will be happy to merge it, but once we get the system a bit more stable, as in no major changes coming up in the next few weeks, then we should run your script for a while! Soon we will revamp the pet system and probably get by far more items. So I guess it makes sense to really do it then :)

**Pull request closed without merging**
