### PR TITLE
WIP: Push notifications

### PR DESCRIPTION
**Pull request by negue**
Dont merge!

Current push notifications available:
- Won a challenge
- Invitation to a Guild / Party / Quest
- Received a Subscription / Gem Gift

### CODE REVIEW

**Comment by negue** [comment]
@Alys what is tag-A?^^

**Comment by lefnire** [comment]
@Alys seriously, it better not be tag-author your you're _dead to me_

**Comment by lefnire** [comment]
tag-alys, though, i can get behind

**Comment by Alys** [comment]
tag-author-of-the-site, so just pop off and fix all of those now, lefnire, there's a dear.

**Comment by lefnire** [comment]
Let's make a million-dollar company that provides a "like" button for Github :)

**Comment by lemoness** [comment]
+++++++++

**Comment by Alys** [comment]
I'm assuming this can be closed now that https://github.com/HabitRPG/habitrpg/pull/4932 exists. @negue , reopen if I'm wrong.

**Pull request closed without merging**
