### PR TITLE
Don't hardcode total pets count

### PR DESCRIPTION
**Pull request by djuretic**
I saw this problem in https://github.com/lefnire/habitrpg/issues/1445#issuecomment-24142125.

### CODE REVIEW

**Comment by lefnire** [comment]
psssh, you make it look so easy :)

**Comment by lefnire** [comment]
this is a better solution than the hard-coded 90, but we'll still want to revisit in the future since some pets in window.items.items.pets are unattainable (like backer pet, veteran, etc)

**Comment by djuretic** [comment]
That's just the discussion on #1445 :)

**Comment by paglias** [comment]
Personally I like @djuretic approach: special pets are, well, "special". Which means that you can normally find them so if we counted them someone would have 90/92 or 91/92 pets found but will never have the possibility to achieve the ones missing

**Pull request merged**
