### PR TITLE
Replace hard-coded strings for env.t on views/shared/modals folder

### PR DESCRIPTION
**Pull request by marcelosizer**
@paglias I didn't commit drops.jade and though I've replaced strings in it, I used the version from #2482, so I'm waiting for feedback to see if it's going to be merged or dropped. And I didn't touch the file newstuff.jade as there was no decision on what to do with it.

Forgot to add that login.jade wasn't touched as there is a comment on it that states it's no longer being used.

This PR goes along with [habitrpg-shared #110](https://github.com/HabitRPG/habitrpg-shared/pull/110)

### CODE REVIEW

**Comment by paglias** [comment]
Fantastic, have you already checked it works on your local server?

Anyway, it seems there are some conflict but shouldn't be a problem, will try to merge them as soon as possible

**Comment by marcelosizer** [comment]
Usually I test it on my local server but you never know. Version conflicts?

**Comment by paglias** [comment]
Ok, the conflicts are in git because in the mean time the file has been
modified by someone else, nothing problematic because you didn't modified
older strings.

2014/1/22 Marcelo Sizer notifications@github.com

> Usually I test it on my local server but you never know. Where are the
> conflicts so I can test?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/pull/2522#issuecomment-33053182
> .

## 

Matteo Pagliazzi - paglias.net

**Comment by marcelosizer** [comment]
What do you mean by older strings?

**Comment by paglias** [comment]
I mean that git didn't allow me to automatically merge your pr because you
used a version of the main.json file older than the actual one because some
hours ago I merged another pr about this file.

But since you didn't touched older parts of the file but only added new
lines to it it isn't a problem, it isn't a real conflict, simply git can't
decide on its own if a commit causes problems to another one.

2014/1/22 Marcelo Sizer notifications@github.com

> What do you mean by older strings?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/pull/2522#issuecomment-33053450
> .

## 

Matteo Pagliazzi - paglias.net

**Comment by marcelosizer** [comment]
Ah, ok. I thought you were talking about the jade files here =p

**Comment by paglias** [comment]
selezione_015

Also here there is one because the file has changed in the meantime

**Comment by marcelosizer** [comment]
Yup, missed that. I'm still a noob in git. =p

**Comment by paglias** [comment]
No, no, it was to explain what happened, nothing you could do =p

**Pull request merged**
