### PR TITLE
End-to-end testing

### PR DESCRIPTION
**Pull request by djuretic**
Here are the first working end-to-end tests. I'm using Protractor instead of ngScenario.
So now `npm test` will call the Karma unit tests and then the Protactor tests. Protractor needs both the NodeJs server and the Selenium server up, I've modified the Travis config file to take care of that.

Problems to be solved:
- Resetting the MongoDB database between tests. It might be a good idea to use a different database instead of `habitrpg` (e.g.: `habitrpg_test`), so the e2e test can be run against that it.
- Automatically start the Node and Selenium servers if they are not running when executing `npm test`. 

Any help is appreciated :)

### CODE REVIEW

**Comment by djuretic** [comment]
Hmm, I guess I have to fix the build.

**Comment by lefnire** [comment]
phenomenal! I'm still quite newbie in the testing sphere, as you know. I'll try to study up on this and start contributing at some point, but feel free to merge it whenever you see fit (sounds like you have reservations on current PR per your last message)

**Comment by djuretic** [comment]
Done!
To run the e2e tests, a Node server (DB habitrpg_test, port 3001) and Selenium server are launched (and killed when the tests are finished).
Before running the tests the `habitrpg_test` database is _dropped_.

**Comment by lefnire** [comment]
:+1: you are a titan

**Pull request merged**
