### PR TITLE
Golden Knight 1 and Egg Hunt art completed, fixes #4936

### LINKED ISSUE #4936: Collection quests without images have confusing text formatting
### EDIT FROM ADMIN

Many of the collection quests are missing illustrations, which is causing some weird formatting in the quest modals (see below for screenshots). The following need art:
- [x] [Find the Cub](http://habitrpg.wikia.com/wiki/Find_the_Cub) (fixed in #5545)
- [x] [Find the Lair of the Wyrm](http://habitrpg.wikia.com/wiki/Find_the_Lair_of_the_Wyrm) - common/img/sprites/spritesmith/quests/quest_vice2.png
- [x] [Egg Hunt](http://habitrpg.wikia.com/wiki/Egg_Hunt) - common/img/sprites/spritesmith/quests/quest_egg.png
- [x] [The Moonstone Chain](http://habitrpg.wikia.com/wiki/The_Moonstone_Chain) - common/img/sprites/spritesmith/quests/quest_moonstone1.png
- [x] [A Stern Talking To](http://habitrpg.wikia.com/wiki/A_Stern_Talking-To) - common/img/sprites/spritesmith/quests/quest_goldenknight1.png
- [x] [Message in a Bottle](http://habitrpg.wikia.com/wiki/Message_in_a_Bottle) - common/img/sprites/spritesmith/quests/quest_dilatoryDistress1.png

---

The quest summary and collection goal aren't clearly separated, making the goal appear to be part of the quest summary. This is most prevalent in the _Egg Hunt_ quest, but it's an issue in any collection quest without an image. 

habitrpg - collection formatting - egg hunt
habitrpg - collection formatting - a stern talking-to
habitrpg - collection formatting - find the lair of the wyrm
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/10140069-collection-quests-without-images-have-confusing-text-formatting?utm_campaign=plugin&utm_content=tracker%2F68393&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F68393&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by mdakan**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes https://github.com/HabitRPG/habitica/issues/4936

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

Added collection quest images to Egg Hunt and The Golden Knight, Part 1.

before_egg_hunt
before_stern_talk
after_egg_hunt
after_stern_talk

[//]: # (Put User ID in here - found in Settings -> API)

----
UUID: e48c8f5d-6ec9-49a0-9713-354447be2d17

### CODE REVIEW

**Comment by mdakan** [comment]
Re-sharing screenshots:
https://goo.gl/photos/h3jAb2CuWx7DDPAaA

**Comment by crookedneighbor** [comment]
:+1:

**Review by crookedneighbor — APPROVED** [review]
Just need someone to compile the sprites after merging this in.

**Comment by mdakan** [comment]
@crookedneighbor Is that something I could have done differently? I committed after running ```gulp sprites:compile```.

**Comment by SabreCat** [comment]
Thanks, @mylesdakan! I've awarded you a contributor tier for your first merged contribution. Note that successive tiers require more effort from one to the next, so tier 2 will require multiple pull requests or a more substantial one. But keep helping out and we'll express our gratitude accordingly!

As for the compiled spritesheets, no, this is the best way of going about it. You could commit the compiled spritesheets and CSS, but it's typically best for us to just do that on `develop`.

**Comment by mdakan** [comment]
Thanks for the explanation! If there's anything I can look through to become more helpful, I would be happy to do that.

**Pull request merged**
