### PR TITLE
Fix Server Errors Appear As Blank Red Bar

### LINKED ISSUE #9213: Server errors appear as blank red bar
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

If an error is returned from the server for an action, the client tries to display a notification, but it has no content. So you just get an uninformative red stripe that flies up through your notifs.

To reproduce locally, start the client and server as usual (`npm run client:dev` and `npm start` in separate terminal sessions). Load your tasks page. Then stop the server (^C the `npm start`) and check off a task. You'll see the empty error blob appear briefly.

### PR DESCRIPTION
**Pull request by LulaV14**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #9213 

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
Changed the path for the error text that was pointing to null data.
From  `error.response.data.message` to `error.response.data`.

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 4a5d7afb-d65e-485b-8e46-c9414a43b0bb

### CODE REVIEW

**Comment by LulaV14** [comment]
@SabreCat so sorry for the delay. I found as you said that the path to `error.response.data.message` was the problem and didn't contain anything, and what contains the error message is `error.response.data`. 

I just have one question with this line, is there another way the error path needs to be `error.response.data.message` ?
https://github.com/HabitRPG/habitica/blob/63bba13b5fda4c38d95c2b172e30e7580f52ab7a/website/client/app.vue#L210-L212

**Comment by LulaV14** [comment]
I don't know why Travis is failing and coverage is decreased :S ... I just changed two lines of code

**Comment by TheHollidayInn** [comment]
Not your fault! Travis is just bugging out. I reset it

**Review by SabreCat — APPROVED** [review]

**Comment by SabreCat** [comment]
Looks good! Thank you, @LulaV14 -- I've granted you the Blacksmith contributor title and noted this toward your tier 2 contributor level!

**Pull request merged**
