### PR TITLE
new Habitica urls

### PR DESCRIPTION
**Pull request by teh-maxh**
Changed URLs in footer to reflect HabitRPG->Habitica name change.

### CODE REVIEW

**Comment by sgabler** [comment]
@teh-maxh: Is this task finished? I still see lots of habitrpg urls

**Comment by teh-maxh** [comment]
Whoops, yeah; I'd only hit the ones I noticed while trying to use the site. Fixed the other ones that have moved as well now. The following links are still 'habitrpg':
- Google Play
- Github
- Kickstarter ('habitica' versions don't exist at all)
- Blog
- Reddit ('habitica' versions _exist_ but are incredibly boring)

**Comment by sgabler** [comment]
Looks good to me: :+1:

**Comment by crookedneighbor** [comment]
Looks good to me too. 

This will count towards a contributor tier! What's your User ID? You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api). Be sure to only copy the User ID and _not_ your API Token.

**Comment by teh-maxh** [comment]
`991d201d-8307-4117-a3b3-b974adbf2327`

**Comment by crookedneighbor** [comment]
I've awarded you a blacksmith tier!

You can read more about [contributor tiers and rewards here](http://habitrpg.wikia.com/wiki/Contributor_Rewards).

Note that as your tier increases, it takes progressively more work to achieve the next one, so for the higher tiers, larger PRs or a few PRs are required. There's some information about that at Contributor Rewards, but feel free to ask here if you have questions!

**Comment by teh-maxh** [comment]
Yay! :D

**Pull request merged**
