### PR TITLE
Ensure correct join/leave button for parties

### PR DESCRIPTION
**Pull request by gisikw**
Addresses #5077 

Similar logic to our fix for checking Guild membership - if the group is the user's current party, return true early from the isMemberOfGroup function.

And also a spec. :sunglasses:

### CODE REVIEW

**Comment by paglias** [comment]
@gisikw @TheHollidayInn we should choose between this and the code proposed in #4961. I would go for #4961 but just because is server-side and will work for all the apps that rely on the API

**Comment by gisikw** [comment]
I'd argue that both are valid here - technically speaking, a check if we're dealing with the current party is still faster than crawling the group members.

But yeah, getting a server-side impl is important as well.

**Comment by paglias** [comment]
@gisikw the fact is that after #4961 is merged the user will always appear in the party's members field so it will be addressed by https://github.com/gisikw/habitrpg/blob/party-join-leave-buttons/website/public/js/controllers/groupsCtrl.js#L33-L34

**Comment by gisikw** [comment]
Oh yeah, it will. This is technically faster though ;)

But if the server-side stuff is ready to go, both will address the actual bug :)

**Comment by paglias** [comment]
@gisikw good point, especially when showing the big list of guilds, and since there's code for them there's no reason not to add this for  the party. Merging :)

@TheHollidayInn if you still want to work on #4961 I would like to have that too

**Comment by paglias** [comment]
@gisikw for the contributor level, I will defer to @crookedneighbor or @Alys because they probably know the situation better than me :)

**Comment by Alys** [comment]
I've noted this as partial credit for Tier 7 for @gisikw

**Pull request merged**
