### PR TITLE
User status model: fix attributes box size being too small on Japanese

### LINKED ISSUE #9979: User status modal: layout breaks when there are unallocated stats points and language is Japanese
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: 203f208a-e0f0-4442-bf16-d4f19e553e8a
  * Browser: Google Chrome 64.0.3282.140 (Official build)
  * OS: Debian

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
A small layout bug but it always annoys me.
The text "points" (ポイント) and the arrow for allocating the point it out of the place when I have unallocated points.

If it is fine I can fix it myself.

Screenshot

#### Console Errors
[//]: # (Include any JavaScript console errors here.)
Not applicable.

### PR DESCRIPTION
**Pull request by Yutsuten**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #9979

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
Increased the width of the box a little so the text "points" (ポイント) fits in its space.
The difference of the box is almost imperceptible when in English.

Also tested seeing the same modal in all available languages, I can guarantee the text "points" in Japanese is the biggest one.

#### - Before
screenshot1
screenshot2

#### - Now
screenshot3
screenshot4

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 203f208a-e0f0-4442-bf16-d4f19e553e8a

### CODE REVIEW

**Comment by negue** [comment]
It does fix the issue, but it also moves the `Perception`box a bit to the right

@Tressley  what do you think ?

**Comment by Alys** [comment]
I've tested this locally and it looks okay to me. The boxes are a bit further to the right than before but it's not that obvious. Tressley has said in the issue that he's not going to provide a design for this because the section will be reworked in future, so I think this is good to go live as it is to make things easier right now for players who use languages other than English.

**Comment by Tressley** [comment]
Yeah, just push this through as a quick fix. Thanks for relaying information @Alys 👍

**Comment by paglias** [comment]
@Yutsuten thanks for this! I'm merging the PR and awarding your contributor tier.

Note that further tiers require increasing amounts of work from one to the next, so Tier 2 may require a couple of PRs or a larger PR to attain. But keep helping out and we'll express our gratitude accordingly!

**Pull request merged**
