### PR TITLE
Support for deleting tasks

### PR DESCRIPTION
**Pull request by BlackEdder**
This pull request also adds habitrpg-shared as a submodule. But both commits can be applied separately if needed.

### CODE REVIEW

**Comment by BlackEdder** [comment]
Apparently github automatically added newer commits by me as well (a339cd4 and 6b59beb) 
Let me know if you want me to separate all these commits into separate pull requests.

**Comment by lefnire** [comment]
will visit this soon. @litenull wanna take a look at this, since your'e closer to the rewrite than I at present?

**Comment by litenull** [comment]
Yeah, will do

**Comment by litenull** [comment]
I did this already.

**Comment by lefnire** [comment]
DO IT AGAIN!

**Comment by litenull** [comment]
Oh wow shit. Only read the title, there are actually multiple commits!

**Comment by lefnire** [comment]
wait, I was kidding

**Comment by AndreCaseyScott** [comment]
Haha, you guys are hilarious :P

**Comment by lefnire** [comment]
join our various IRC parties!

**Comment by AndreCaseyScott** [comment]
Will do! Though given my wonky schedule, I'll probably miss most of the antics. I'm sure if I lurk long enough, I'll catch some of you folk :P

**Comment by AndreCaseyScott** [comment]
While I'm thinking if it, is there a checklist for the remaining things needed to complete the web and mobile apps somewhere? :/

**Pull request merged**
