### PR TITLE
Fixed broken business link

### LINKED ISSUE #5142: Front page business.html dead link
https://habitrpg.com/static/front has a link to https://habitrpg.com/business.html should it be https://habitrpg.com/static/plans instead?

### PR DESCRIPTION
**Pull request by NotGonnaGitUs**
Fixes #5142

### CODE REVIEW

**Comment by paglias** [comment]
@NotGonnaGitUs uuid?

**Comment by NotGonnaGitUs** [comment]
Wow. I get contribution for this! Awesome. Thanks!

**Comment by paglias** [comment]
@NotGonnaGitUs it's a partial credit towards level 2 :)

**Comment by NotGonnaGitUs** [comment]
Thanks!

**Pull request merged**
