### PR TITLE
Add client Dockerfile and change docker compose process

### PR DESCRIPTION
**Pull request by BradLugo**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes are based on discussion from [#9043](https://github.com/HabitRPG/habitica/issues/9043)

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

- Added another Dockerfile for the client side development
- Updated the docker-compose.yml file to accommodate the aforementioned Dockerfile
- Updated the version for the docker-compose.yml and docker-compose.dev.yml files

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: b20e27a5-e552-4247-9e91-65442a04f6d4

### CODE REVIEW

**Comment by paglias** [comment]
Is it possible to have a single docker file that runs both the client and server?

**Comment by BradLugo** [comment]
Yes we could but we'd be abusing containers at that point for the same reason we don't have Mongo in the same container as this project's source code. If you want other's opinion on the matter, [here's a DevOps StackExchange post](https://devops.stackexchange.com/questions/447/why-it-is-recommended-to-run-only-one-process-in-a-container). But if ya'll don't agree or don't see an issue with that, I can change it to one docker file

**Comment by TheHollidayInn** [comment]
I support having two. That is the recommended way by docker and Docker Compose is there to help have a single command.

**Comment by luanmuniz** [comment]
Can we have the same Dockerfile for both but overwrite the command in the docker-compose file? They are both the exact same container, the only thing that change is the command. That way would be just one file to maintain 

Reference: https://docs.docker.com/compose/compose-file/#command

**Comment by BradLugo** [comment]
I just made a change but you're right, these containers would be the same if the EXPOSE statements weren't there (admittedly, the EXPOSE doesn't really do anything when using the docker-compose.yml). The reasons I'd argue for keeping them different are:

- It's not obvious that you need both containers to run the app code successfully (not including the database). This could include running unit tests without having to remember that the client side needs to have a different entry point
- If the client side and server side had different environmental dependencies that need to be resolved at build time instead of run time. For example, if we wanted to have just the client side artifact in the client container and just the server side artifact in the server container (as opposed to having both build artifacts in both containers)

All of that being said, I don't have a preference. I can change it if we want it that way

**Comment by TheHollidayInn** [comment]
I can see the issue. We currently couple the client and the server together tightly. There is definitely a case to remove that coupling - which would require two environments, but that is out of scope.

**Comment by lex111** [comment]
Hi all. 

This works fine for me, followed the instructions for the Docker on the wiki page, it did not work. Let's merge this already?

**Comment by harakuri** [comment]
Hey all,

Really like the change! Quick question though: Should the mongo image be specified to version 3.4 in the compose file?

**Comment by paglias** [comment]
I'm fine with specifying the mongo version but we're not using 3.4 in production. We're still on mongo 3.2, 3.4 works anyway, 3.6 will once we upgrade to mongoose 5 (which has some bug currently)

**Comment by SabreCat** [comment]
Thanks for this, @BradLugo! Noted as credit toward Blacksmith tier 2!

**Comment by Alys** [comment]
@BradLugo Thanks for this! Are there any changes needed to the Docker section of [Setting up Habitica Locally](http://habitica.wikia.com/wiki/Setting_up_Habitica_Locally)?

**Comment by BradLugo** [comment]
@Alys Yes but nothing in the process changes. The only thing that needs to change is describing what's going on at the end of the Docker section. For example, I can see how "Habitica is available on port 3000 and mongo is on port 27017" can be misleading because the server is running on 3000 and the client is running on 8080. I don't know how y'all want to phrase that since the two are tightly coupled but it's mainly semantics. This documentation change also relates to the Vagrant change (#9732) so whatever we decide here, I can make that change in the Vagrant section as well

**Comment by Alys** [comment]
@BradLugo Would you like to edit those sections in whatever way you think will be most helpful to people using Docker and Vagrant?

**Comment by paglias** [comment]
I was able to install docker and the habitica image today but then I'm stuck when trying to run tests following the wiki instructions which are likely out of date. @BradLugo how do you run tests now?

**Pull request merged**
