### PR TITLE
lists banned words in the chat error message - fixes https://github.com/HabitRPG/habitica/issues/8812

### PR DESCRIPTION
**Pull request by pineapple-joe**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
https://github.com/HabitRPG/habitica/issues/8812

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
I changed the method textContainsBannedWords from boolean
to return the matched words, and renamed it getBannedWordsFromText.

I added the banned words matched to the thrown BadRequest.

I created a stringUtils file that contains 2 methods:
1. removePunctuationFromString  - removes punctuation marks from a string
2. getMatchesByWordArray -  given a string and a word array, returns the matched words.

I used the removePunctuationFromString to return clean matches,
so for the sentence:
badWord1, badword2! 
instead of returning the words (badWord1,, badword2!)
I return (badWord1, badWord2).

I have some questions, so for now this PR can't be merged:

1. `\\b([^a-z]+)?${word.toLowerCase()}([^a-z]+)?\\b`
The regex that is used to match the bannedWords, doesn't include matches in a substring,
only as a whole word, and there are a couple of tests that check that:
does not error when bad word is suffix/prefix of a word

I think that's a little odd, cause then suppose badwordAnotherBadWord is not caught.
If you change the remove the \\b from regex, it is more strict.
what do you think?

2. because I remove the punctuation, the bannedWord used for testing:
TEST_PLACEHOLDER_SWEAR_WORD_HERE

doesn't work, and I wanted to change it to testPlaceholderSwearWordHere
in the file bannedWords.js
but didn't yet, because of what is said in the comments.

I did change it in the test file.

what do you think?

3. When showing the words to the user, words can be half hidden with ***.

[//]: # (Put User ID in here - found in Settings -> API)

----
UUID: 
f011fa04-2a3a-454f-a048-1b41ba66b340

### CODE REVIEW

**Comment by Alys** [comment]
I haven't reviewed or tested your change yet (we'll be sure to do that though before it's merged) but to answer your questions:

1. We deliberately check for only whole words to avoid the [Scunthorpe problem - Wikipedia](https://en.wikipedia.org/wiki/Scunthorpe_problem).
2. Some of the banned words contain punctuation. For example, if dog was a banned word and if d*g was a common way of getting around the ban, then the list would contain d*g. Does your PR still allow words like that to be banned? You might like to do a test on your local install to see if d*g is banned, only spell it backwards. :) 
3. When showing banned words to the user who's trying to post them, there's no need to obscure the words, but thank you for thinking of it! It's best to leave them unobscured so that the user can't be in any doubt about which word was wrong, especially in the case of people who don't speak English natively.

**Comment by pineapple-joe** [comment]
Hey,
Thanks for your comments.

I did a small refactor, and checked that all the banned words, 
including words with *, are caught.
I added a test for that.

The branch build tests still fail, because I still haven't committed 
the change to the bannedWords.js file, for the testBannedWordMessage.
let me know how to proceed.

Thanks!

**Comment by SabreCat** [comment]
It looks like you've got a lot of unrelated changes pulled in on this branch. Can you rebase to current `develop` so it's clearer what your PR modifies?

**Comment by SabreCat** [comment]
...I didn't know I could push to your fork. Oops! I hope that's OK, seems to have straightened out the spurious diffs.

For future reference, best practice in these situations is to `pull` the latest from the official Habitica `develop` branch, then `merge` that into your PR branch. (I said "rebase" earlier, but a merge is easier.)

**Comment by pineapple-joe** [comment]
Hey, thanks.
I tried to straighten things out, but without success.
Now we can proceed :)

**Comment by SabreCat** [comment]
With the recent merge of https://github.com/HabitRPG/habitica/pull/8177 , this will need to check against two different bad-word lists. Would you be able to incorporate that, @borisabramovich86 ?

**Comment by pineapple-joe** [comment]
Yeah, I believe that I will.

**Comment by Alys** [comment]
I'm not sure there's much point to checking the list of slurs because when a user has posted a slur, their chat permissions are immediately revoked and they can't post again - no real need to tell them which word was bad. Moderators can explain that in the rare cases where the user wouldn't know what they'd done wrong (e.g., a non-English speaker).

At the least, there's no point reading the list of slurs for the current message that this PR produces because that message won't be thrown when a slur has been detected (slur detection comes first). If you want to adjust the new `bannedSlurUsed` message to include the slur, that would be fine, but maybe in a different PR? That would let us get this PR released sooner.

**Comment by SabreCat** [comment]
OK! In that case, @borisabramovich86, just resolve the merge conflicts and we'll get this reviewed for you.

**Comment by SabreCat** [comment]
Thanks so much, @borisabramovich86, this works great! And welcome to Blacksmith tier 1. Further tiers require increasing amounts of work from one to the next, so tier 2 may require multiple PRs or a larger PR to attain, but keep helping out and we'll express our gratitude accordingly!

**Pull request merged**
