### PR TITLE
Fix #4259 HP/EXP meter bars always 100% on IE11

### LINKED ISSUE #4259: HP/EXP meter bars always 100% on IE11
Issue #2879 has too generic a title & I thought you might want more specific reporting.

It appears Angular is ignoring the meter width binding on IE11. I don't know why that would be, possibly and issue with AngularJS itself, but the inline width is empty.

``` html
<!-- Chrome as rendered -->
<div class="meter health">
  <div style="width: {{Shared.percent(user.stats.hp, 50)}}%;" class="bar"></div>
  <span class="meter-text value">{{Math.ceil(user.stats.hp)}} / 50</span>
</div>

<!-- Chrome as computed -->
<div class="meter health">
  <div style="width: 65%;" class="bar"></div>
  <span class="meter-text value ng-binding">33 / 50</span>
</div>


<!-- IE 11 as rendered -->
<div class="meter health">
  <div style="width: {{Shared.percent(user.stats.hp, 50)}}%;" class="bar"></div>
  <span class="meter-text value">{{Math.ceil(user.stats.hp)}} / 50</span>
</div>

<!-- IE 11 as computed -->
<div class="meter health">
  <div class="bar"></div>
  <span class="meter-text value ng-binding">33 / 50</span>
</div>

```

### PR DESCRIPTION
**Pull request by sbreiler**
Fixes bars width on IE11 allover the place (Jade-Templates).

### CODE REVIEW

**Comment by paglias** [comment]
@sbreiler thanks! Is this going to be necessary somewhere else or only here? I mean using `ngStyle` in place of using interpolation inside the `style` attribute.

If you give me your UUID I'll award you a badge!

**Comment by paglias** [comment]
@sbreiler if you have some time can you give a look at the other issues pointed out at #2879? thanks

**Comment by lefnire** [comment]
Got a problem here. After pulling, I get this error:

`
err: "/habitrpg/website/views/shared/header/header.jade:13 11| ter-label(tooltip=env.t('experience')) Invalid indentation, you can use tabs or spaces but not both"
`

Looks like hard tabs were used (windows or IDE spaces v tabs configuration). When I replace tabs with two spaces:

``` diff
diff --git a/views/shared/header/header.jade b/views/shared/header/header.jade
index baa61fb..aac9ef6 100644
--- a/views/shared/header/header.jade
+++ b/views/shared/header/header.jade
@@ -10,13 +10,13 @@
       .meter-label(tooltip=env.t('health'))
         span.glyphicon.glyphicon-heart
       .meter.health
-       .bar(ng-style='{width: Shared.percent(user.stats.hp, 50) + "%" }')
+    .bar(ng-style='{width: Shared.percent(user.stats.hp, 50) + "%" }')
         span.meter-text.value
           | {{Math.ceil(user.stats.hp)}} / 50
       .meter-label(tooltip=env.t('experience'))
         span.glyphicon.glyphicon-star
       .meter.experience
-       .bar(ng-style='{width: Shared.percent(user.stats.exp,Shared.tnl(user.stats.lvl)) + "%" };')
+    .bar(ng-style='{width: Shared.percent(user.stats.exp,Shared.tnl(user.stats.lvl)) + "%" };')
         span.meter-text.value
           span(ng-show='user.history.exp', tooltip=env.t('progress'))
             a(ng-click='toggleChart("exp")').glyphicon.glyphicon-signal 
```

It looks like this:

screen

**Comment by lefnire** [comment]
@crookedneighbor fixed the header part here https://github.com/HabitRPG/habitrpg/pull/4294. But now I'm [getting this](https://www.evernote.com/shard/s17/sh/d78467a2-05aa-46c3-937c-d56b41d3b306/dae702aee906758c03c3f25ee242d399). Not sure if any other css issues are going on, should we maybe revert this until it can get hammered out?

**Comment by paglias** [comment]
@lefnire sorry about that, I'll try to sort this out. If I can't I'll revert

**Comment by lefnire** [comment]
Oh, and checkout the HP / EXP bars - no hp / exp (the thing it was trying to fix). Yeah, I'm gonna revert in a bit (since I need to do a push coming up). I'll drop the revert commit here so you can revert my revert on a separate PR

**Comment by lefnire** [comment]
3204418

**Comment by paglias** [comment]
@lefnire sincerely I don't know why but this works:

``` diff
diff --git a/views/options/inventory/stable.jade b/views/options/inventory/stable.jade
index 6fa5b75..e96469e 100644
--- a/views/options/inventory/stable.jade
+++ b/views/options/inventory/stable.jade
@@ -8,7 +8,7 @@ mixin petList(source)
             div(popover-trigger='mouseenter', popover=env.t('petName', {potion: potion.text(env.language.code), egg: egg.text(env.language.code)}), popover-placement='bottom')
               button(class="pet-button Pet-#{pet}", ng-if='user.items.pets["#{pet}"]>0', ng-class='{active: user.items.currentPet == "#{pet}", selectableInventory: selectedFood && !user.items.mounts["#{pet}"]}', ng-click='choosePet("#{egg.key}", "#{potion.key}")')
                 .progress(ng-show='!user.items.mounts["#{pet}"] && "#{egg.key}"!="Egg"')
-                  .progress-bar.progress-bar-success(style='width:{{user.items.pets["#{pet}"]/.5}}%')
+                  .progress-bar.progress-bar-success(ng-style='{width: (user.items.pets["#{pet}"]/.5+"%")}')
               button(class="pet-button pet-not-owned", ng-if='!user.items.pets["#{pet}"]')
                 .PixelPaw
               button(class="pet-evolved pet-button Pet-#{pet}", ng-if='user.items.pets["#{pet}"]<0')
diff --git a/views/options/social/boss.jade b/views/options/social/boss.jade
index 4644f28..5787e63 100644
--- a/views/options/social/boss.jade
+++ b/views/options/social/boss.jade
@@ -47,13 +47,13 @@ mixin boss(tavern, mobile)
             .meter-label(tooltip=env.t('bossHP'))
               span.glyphicon.glyphicon-heart
             .meter.health
-              .bar(style='width: {{Shared.percent(progress.hp, boss.hp)}}%;')
+              .bar(ng-style='{width: (Shared.percent(progress.hp, boss.hp)+"%")}')
               span.meter-text.value
                 | {{Math.ceil(progress.hp) | goldRoundThousandsToK}} / {{boss.hp | goldRoundThousandsToK}}
             .meter-label(tooltip='Rage', ng-if='boss.rage')
               span.glyphicon.glyphicon-fire
             .meter.mana(ng-if='boss.rage',popover="{{::boss.rage.description()}}",popover-title="{{::boss.rage.title()}}",popover-trigger='mouseenter',popover-placement='right')
-              .bar(style='width: {{Shared.percent(progress.rage, boss.rage.value)}}%;')
+              .bar(ng-style='{width: (Shared.percent(progress.rage, boss.rage.value)+"%")}')
               span.meter-text.value
                 | {{Math.ceil(progress.rage)  | goldRoundThousandsToK}} / {{boss.rage.value | goldRoundThousandsToK}}
         div(ng-if='::Content.quests[group.quest.key].collect')
diff --git a/views/shared/header/header.jade b/views/shared/header/header.jade
index ce41538..28a8791 100644
--- a/views/shared/header/header.jade
+++ b/views/shared/header/header.jade
@@ -10,13 +10,13 @@
       .meter-label(tooltip=env.t('health'))
         span.glyphicon.glyphicon-heart
       .meter.health
-        .bar(style='width: {{Shared.percent(user.stats.hp, 50)}}%;')
+        .bar(ng-style='{width: (Shared.percent(user.stats.hp, 50)+"%")}')
         span.meter-text.value
           | {{Math.ceil(user.stats.hp)}} / 50
       .meter-label(tooltip=env.t('experience'))
         span.glyphicon.glyphicon-star
       .meter.experience
-        .bar(style='width: {{Shared.percent(user.stats.exp,Shared.tnl(user.stats.lvl))}}%;')
+        .bar(ng-style='{width: (Shared.percent(user.stats.exp,Shared.tnl(user.stats.lvl))+"%")}')
         span.meter-text.value
           span(ng-show='user.history.exp', tooltip=env.t('progress'))
             a(ng-click='toggleChart("exp")').glyphicon.glyphicon-signal 
@@ -25,7 +25,7 @@
       .meter-label(tooltip='Mana', ng-if='user.flags.classSelected && !user.preferences.disableClasses')
         span.glyphicon.glyphicon-fire
       .meter.mana(ng-if='user.flags.classSelected && !user.preferences.disableClasses')
-        .bar(style='width: {{user.stats.mp / user._statsComputed.maxMP * 100}}%;')
+        .bar(ng-style='{width: (user.stats.mp / user._statsComputed.maxMP * 100+"%")}')
         span.meter-text.value
           span
           | {{Math.floor(user.stats.mp)}} / {{user._statsComputed.maxMP}}
(END)
```

I mean, it's the same code.

BTW, how do you publish those nice diffs?

**Comment by crookedneighbor** [comment]
@paglias is this what you mean? All you need to do is put diff after ```

``` diff
diff --git a/views/options/inventory/stable.jade b/views/options/inventory/stable.jade
index 6fa5b75..e96469e 100644
--- a/views/options/inventory/stable.jade
+++ b/views/options/inventory/stable.jade
@@ -8,7 +8,7 @@ mixin petList(source)
             div(popover-trigger='mouseenter', popover=env.t('petName', {potion: potion.text(env.language.code), egg: egg.text(env.language.code)}), popover-placement='bottom')
               button(class="pet-button Pet-#{pet}", ng-if='user.items.pets["#{pet}"]>0', ng-class='{active: user.items.currentPet == "#{pet}", selectableInventory: selectedFood && !user.items.mounts["#{pet}"]}', ng-click='choosePet("#{egg.key}", "#{potion.key}")')
                 .progress(ng-show='!user.items.mounts["#{pet}"] && "#{egg.key}"!="Egg"')
-                  .progress-bar.progress-bar-success(style='width:{{user.items.pets["#{pet}"]/.5}}%')
+                  .progress-bar.progress-bar-success(ng-style='{width: (user.items.pets["#{pet}"]/.5+"%")}')
               button(class="pet-button pet-not-owned", ng-if='!user.items.pets["#{pet}"]')
                 .PixelPaw
               button(class="pet-evolved pet-button Pet-#{pet}", ng-if='user.items.pets["#{pet}"]<0')
diff --git a/views/options/social/boss.jade b/views/options/social/boss.jade
index 4644f28..5787e63 100644
--- a/views/options/social/boss.jade
+++ b/views/options/social/boss.jade
@@ -47,13 +47,13 @@ mixin boss(tavern, mobile)
             .meter-label(tooltip=env.t('bossHP'))
               span.glyphicon.glyphicon-heart
             .meter.health
-              .bar(style='width: {{Shared.percent(progress.hp, boss.hp)}}%;')
+              .bar(ng-style='{width: (Shared.percent(progress.hp, boss.hp)+"%")}')
               span.meter-text.value
                 | {{Math.ceil(progress.hp) | goldRoundThousandsToK}} / {{boss.hp | goldRoundThousandsToK}}
             .meter-label(tooltip='Rage', ng-if='boss.rage')
               span.glyphicon.glyphicon-fire
             .meter.mana(ng-if='boss.rage',popover="{{::boss.rage.description()}}",popover-title="{{::boss.rage.title()}}",popover-trigger='mouseenter',popover-placement='right')
-              .bar(style='width: {{Shared.percent(progress.rage, boss.rage.value)}}%;')
+              .bar(ng-style='{width: (Shared.percent(progress.rage, boss.rage.value)+"%")}')
               span.meter-text.value
                 | {{Math.ceil(progress.rage)  | goldRoundThousandsToK}} / {{boss.rage.value | goldRoundThousandsToK}}
         div(ng-if='::Content.quests[group.quest.key].collect')
diff --git a/views/shared/header/header.jade b/views/shared/header/header.jade
index ce41538..28a8791 100644
--- a/views/shared/header/header.jade
+++ b/views/shared/header/header.jade
@@ -10,13 +10,13 @@
       .meter-label(tooltip=env.t('health'))
         span.glyphicon.glyphicon-heart
       .meter.health
-        .bar(style='width: {{Shared.percent(user.stats.hp, 50)}}%;')
+        .bar(ng-style='{width: (Shared.percent(user.stats.hp, 50)+"%")}')
         span.meter-text.value
           | {{Math.ceil(user.stats.hp)}} / 50
       .meter-label(tooltip=env.t('experience'))
         span.glyphicon.glyphicon-star
       .meter.experience
-        .bar(style='width: {{Shared.percent(user.stats.exp,Shared.tnl(user.stats.lvl))}}%;')
+        .bar(ng-style='{width: (Shared.percent(user.stats.exp,Shared.tnl(user.stats.lvl))+"%")}')
         span.meter-text.value
           span(ng-show='user.history.exp', tooltip=env.t('progress'))
             a(ng-click='toggleChart("exp")').glyphicon.glyphicon-signal 
@@ -25,7 +25,7 @@
       .meter-label(tooltip='Mana', ng-if='user.flags.classSelected && !user.preferences.disableClasses')
         span.glyphicon.glyphicon-fire
       .meter.mana(ng-if='user.flags.classSelected && !user.preferences.disableClasses')
-        .bar(style='width: {{user.stats.mp / user._statsComputed.maxMP * 100}}%;')
+        .bar(ng-style='{width: (user.stats.mp / user._statsComputed.maxMP * 100+"%")}')
         span.meter-text.value
           span
           | {{Math.floor(user.stats.mp)}} / {{user._statsComputed.maxMP}}
(END)
```

**Comment by lefnire** [comment]
Exactly, see "Syntax Highlighting" of [this](https://help.github.com/articles/github-flavored-markdown/) (can use javascript, coffeescript, diff, shell, etc - and it will try to auto-detect). And for really long'n's, I drop em in https://gist.github.com/

**Comment by lefnire** [comment]
Oh, and I'll test that ^ sometime soon

**Comment by crookedneighbor** [comment]
@paglias And I think it works because of some under the hood angular magic that applies the style after the dom gets loaded. I'm no expert on that, but I think that's what's going on.

**Comment by paglias** [comment]
I mean, I rewrote the code bit it seems exactly the same one of the
original pr except for the indentation
Il 30/nov/2014 17:22 "Blade Barringer" notifications@github.com ha
scritto:

**Comment by crookedneighbor** [comment]
Ahh, I misunderstood, I thought you were referring to the `ng-style` changes.

I've noticed that Jade is very finicky about tabs and spaces, so that's probably it.

**Pull request merged**
