### PR TITLE
Trying to align the mount heads correctly

### PR DESCRIPTION
**Pull request by joyheron**
Fixing #4618

### CODE REVIEW

**Comment by joyheron** [comment]
This fix essentially generates an extra class for the mount heads which is then centered on the Mounts page.

Before:
uneven-mounts

After:
mounts-aligned

**Comment by joyheron** [comment]
TRex before and after:

Before:
trex-before

After:
trex-after

**Comment by deilann** [comment]
Are those both after photos?

**Comment by joyheron** [comment]
The first is after I made the initial fix. So yes...the default width for all mount heads is now 105px, so they all align better. The second is after I edited the css for TRex so that it is centered in its own column.

**Comment by deilann** [comment]
Ah hah! Now I understand.

**Comment by joyheron** [comment]
If this solution is a good idea, I can start going through and modify the other mount types.

**Comment by crookedneighbor** [comment]
I think this is a clever solution, but it does add some more complexity to the spritesheet creation process as it requires a programmer to do those width calculations every time a new pet is added. 

@lemoness and @veeeeeee What do you think? Is this something that @joyclark should keep doing? If so, I recommend that a readme.md file gets added to one of the image directories to describe the process for calculating the width (and also serve as a reminder that it should be done).

Personally, I'd still like to set the hoards of pixel artists on creating special versions of the mounts for the mount selection page (whether full body mini ones, or just heads), but I understand that I'd just be passing off that extra work that would need to be done for every pet/mount to the pixel artists instead of the programmers :wink:.

**Comment by lemoness** [comment]
It's actually very easy for a pixel artist to create head-only versions -
just time consuming. That would be a good "entry level pixels" task,
though. If you want me to, I will create a card on Trello for them!

**Comment by crookedneighbor** [comment]
@lemoness I would like that. Especially if it allows some newbie pixel artists to get some practice. 

We just need to make sure the canvas sizes are all the same.

**Comment by lemoness** [comment]
What dimensions do you need?

**Comment by joyheron** [comment]
Right now the dimensions of all mounts are 105px wide in the grid (although the fattest "head only" mount is probably the tiger at approximately 85px wide. The penguin (which also has a body) takes up the full 105px, and the mounts that also have wings also are very wide). They are also 93px tall (which with padding and margin makes a total height of 105px so that the whole block has the dimensions 105px x 105px)

**Comment by crookedneighbor** [comment]
If possible, I'd like the mount heads to be the same dimensions as the pets- Width: 81px, Height: 99px

I imagine the hard ones will be the egg baskets and rock monsters.

**Comment by lemoness** [comment]
Okay, I will make the Trello card!

**Comment by crookedneighbor** [comment]
Going to close this, since it looks like we're going with the "separate head art" option. If we decide to go back to this, we can re-open it.

**Pull request closed without merging**
