### PR TITLE
made style change for pet item class to have more margins.

### PR DESCRIPTION
**Pull request by seekheart**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
I've added the changes to style the pet items class for more whitespace as discussed in #9651 

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
I added a scoped item class change with the margins.

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID:  0848ed18-0966-4d90-83da-a1b4ae1500cc

### CODE REVIEW

**Comment by paglias** [comment]
thanks @seekheart ! Can you post a screenshot of before and after the change?

**Comment by seekheart** [comment]
**Before**
screen shot 2018-01-29 at 9 12 36 am

**After**

screen shot 2018-01-29 at 9 14 32 am

@paglias

**Comment by Alys** [comment]
This makes changes in other part(s) of the site too, which is not desirable. I've found this example but haven't gone looking for others:

Production:


New code:

**Comment by seekheart** [comment]
@Alys I'm gonna make a new class to encapsulate just the pets items in this case will commit changes shortly

**Comment by seekheart** [comment]
@Alys I also noticed that the server `nodemon` stopped working it just errors on

```
[22:09:35] [nodemon] starting `node ./website/server/index.js`
[22:10:00] [nodemon] Internal watch failed: watch /workspace/habitica/website/raw_sprites/spritesmith/stable/mounts/icon/Mount_Icon_Whale-CottonCandyBlue.png ENOSPC
```

**Comment by seekheart** [comment]
@Alys please check code should be good?

**Comment by Alys** [comment]
@seekheart A lot of unrelated commits have been included in this PR. Can you remove them? We'll need to see just the changes you've made to be able to review this.

**Comment by seekheart** [comment]
@Alys how do I remove them?

**Comment by Alys** [comment]
If you get your local branch to be identical to `upstream/develop` except with the addition of your own commits for this fix, then you can force-push to your  develop branch on seekheart/habitica and that will probably fix it. Alternatively, close this PR and start a new one. Note that it's not recommended to use a branch called `develop` since it limits you to just one fix at a time - see [Using Your Local Install to Modify Habitica%27s Website and API](http://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API) for details.

**Comment by seekheart** [comment]
@Alys I will resubmit PR

**Pull request closed without merging**
