### PR TITLE
[Old] XP Changes, Better Notifications and Fixes!

### PR DESCRIPTION
**Pull request by PhilipHow**
Here are some changes to a few features, but it's focused on tasks, XP and notifications.

It's done in the style of a change-log, but everything is up for discussion, so please clone, test and discuss!
# XP Changes
- The TNL (To Next Level) Algorithm has been changed to the following:

CodeCogsEqn
Where x is equal to the current level.
- Here are the XP values required to progress to the next level for the first 20 levels:
  <table border=1>
  <tbody>
    <tr>
      <td>Level</td>
      <td>XP</td>
      <td>Level</td>
      <td>XP</td>
    </tr>
    <tr>
      <td>1</td>
      <td>100</td>
      <td>11</td>
      <td>1400</td>
    </tr>
    <tr>
      <td>2</td>
      <td>140</td>
      <td>12</td>
      <td>1640</td>
    </tr>
    <tr>
      <td>3</td>
      <td>200</td>
      <td>13</td>
      <td>1900</td>
    </tr>
    <tr>
      <td>4</td>
      <td>280</td>
      <td>14</td>
      <td>2180</td>
    </tr>
    <tr>
      <td>5</td>
      <td>380</td>
      <td>15</td>
      <td>2480</td>
    </tr>
    <tr>
      <td>6</td>
      <td>500</td>
      <td>16</td>
      <td>2800</td>
    </tr>
    <tr>
      <td>7</td>
      <td>640</td>
      <td>17</td>
      <td>3140</td>
    </tr>
    <tr>
      <td>8</td>
      <td>800</td>
      <td>18</td>
      <td>3500</td>
    </tr>
    <tr>
      <td>9</td>
      <td>980</td>
      <td>19</td>
      <td>3880</td>
    </tr>
    <tr>
      <td>10</td>
      <td>1180</td>
      <td>20</td>
      <td>4280</td>
    </tr>
  </tbody>
  </table>
- The base XP gain for Tasks, Habits and Todos has been changed to 10 XP.
# Habit and Task Changes
- Habit degradation is now enabled for purely Up and Down Habits
- Habit degradation is now uniform for both directions (up and down). The formulae for both are as follows:

CodeCogsEqn 2
- Positive Habits are capped at 0.25s
- Negative Habits are capped at -5 HP
- Gold gained from, Todos, Habits and Dailies is no longer dependant on Strength from the Level and Weapon. This is to align the game with RPG elements but will facilitate Gold gaining mechanics in the future.
# Notifications
- Gold notifications now show Gold and SIlver earnings:
- Death notifications!

Screen Shot 2013-03-02 at 22 20 07
# Fixes
- XP bars should not longer show rounded up values (i.e. no 100/100 XP exception through API triggered habits)
- Checking and Unchecking a Todo or Daily should add and remove the same amount of Gold and XP
# Code Changes
- Ported some algorithms to algos.coffee
- Swapped some functions in scoring.coffee
- Items are now based on Strength and Defense

### CODE REVIEW

**Comment by Pandoro** [comment]
Wow! Just saw this, great stuff :)

**Comment by lefnire** [comment]
Let's do it!

**Comment by switz** [comment]
Love this. Nice job.

**Comment by PhilipHow** [comment]
@ruddfawcett they were, apologies.

**Comment by reallux** [comment]
Would it be possible to turn off habit degradation for some purely Up and Down Habits? My problem is the following: let's say you have the habit "work for 1 hour". Now it will degrade an won't be worth much at some point, which in my opinion doesn't make sense for some tasks.
Best regards.

**Comment by PhilipHow** [comment]
The idea behind HabitRPG is that, as you do well in habits, the amount of Gold you receive lessens over time as it actually becomes a habit. This should encourage you to focus on other habits.

This change makes the degradation slower, but is it still not slow enough? I think a balance needs to be found.

**Comment by Pandoro** [comment]
Personally I was never really thinking about changing my dailies to habits
:x Somehow stuff I do on a daily basis because I want them to do on a daily
basis should be dailies for me, no matter how bad or good they are
eventually :x

**Comment by lefnire** [comment]
Elevating to critical, many people are experiencing this: #564 (Some users getting way too much GP / Exp with new algos)

**Comment by Pandoro** [comment]
Oooh shit :-/ I feel a bit like it would be the safest to revert the
changes for now and rather test it on the test server first?

These errors to me seem a bit random though, maybe an uninitialized
variable which the new algos need?

**Comment by lefnire** [comment]
@MrConcept do the changing plus/minus-only values go back to 0 over time? If not, we should probably restore that to what it was before - quite a few people chiming in about that bit

**Comment by lefnire** [comment]
was updated just now

**Comment by derekantrican** [comment]
Could we change the minimum from .25 gp to .5 gp (per my post here: #326 )?

**Comment by checarlos87** [comment]
@MrConcept Is there a typo in the min function in the delta(down) computation?

0.95^x < 5 for all positive x

so 5 would never be selected as a minimum.  Maybe you meant .5?  But even so, because it is a min function rather than a max function, the effect of .5 would be to cap the degradation _until_ 0.95^x <= .5, at which point it will degrade exponentially approaching 0.

**Comment by ghost** [comment]
All you have to do is have it start at 4 or what ever value you want because anything raised to the 0 is 1. So the equation should be y= .95^x+4 if you want to start the minimum at 5. If you eventually want to remove that 4 and stuff just make the 4(0) after the first go around.

**Comment by PhilipHow** [comment]
The algorithms have changed from these guys, I'll post an updated wiki
entry soon.

**Pull request merged**
