### PR TITLE
Removed unused I18N strings from the `settings.json` files (related to issue #9957)

### PR DESCRIPTION
**Pull request by RaitheOfDureya**
[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
This PR fixes part of issue #9957

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
I have identified the following unused strings in the `settings.json` file. No dynamically-generated strings found.

At the moment I only removed the strings from the `locales/en` folder to make it easier to revert if necessary. Once the strings are reviewed, I can delete them from other languages.

- showHeaderPop
- stickyHeaderPop
- newTaskEditPop
- restartTour
- classTourPop
- resetAccount
- changeCustomDayStart
- sureChangeCustomDayStart
- disabledWinterEvent
- enterNumber
- fillAll
- passwordSuccess
- usernameSuccess
- exportData
- usernameOrEmail
- loginNameDescription
- giftedSubscriptionWinterPromo
- subscribeUsing
- recurringText
- couponPlaceholder
- resubscribe
- invalidEnabled
- missingWebhookId
- invalidWebhookType
- invalidPushClient
- pushDeviceAlreadyAdded
- buyGemsGoldCapBase
- mysticHourglassText
- purchasedPlanId
- mentioning
- suggestMyUsername
- everywhere
- onlyPrivateSpaces

`remindersToLogin` is in a commented block in `schema.js`, Do you wanna keep it?
// remindersToLogin: {$type: Boolean, default: true}

I also found a duplicate string, which one should I keep?
- "couponText": "We sometimes have events and give out promo codes for special gear. (eg, those who stop by our Wondercon booth)",
- "couponText": "We sometimes have events and give out coupon codes for special gear. (eg, those who stop by our Wondercon booth)",

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 6544e17f-237b-4915-ae7e-47744c0dc1bd

### CODE REVIEW

**Comment by paglias** [comment]
thanks @RaitheOfDureya ! This is looking good, 

> remindersToLogin

I'd keep it, we might re-activate it in a near future

> couponText 

I'd keep the first one

```
We sometimes have events and give out promo codes for special gear. (eg, those who stop by our Wondercon booth)
```

**Comment by RaitheOfDureya** [comment]
Right away, @paglias

**Comment by paglias** [comment]
thanks @RaitheOfDureya ! noted towards your 5th tier!

**Comment by RaitheOfDureya** [comment]
Thanks you, @paglias :smile:

I have some questions, if you have time could you help me clarify them? 

- How many "points" does a person need to get up to the next tier (*for example, in my case from 4 to 5*)? 
- Only Pull Requests that have been merged with the main repository count towards that? 

I am asking that, because a lot of the work done in this particular issue doesn't become a PR. For example, in at least four files all strings were manually investigated if they were in use, but although a lot of time was invested they did not originate a new PR :confused:

*please don't take this as a complaint or anything, I'm just trying to understand how the system works to manage my expectations* :sweat_smile:

Cheers

**Comment by paglias** [comment]
@RaitheOfDureya 

> How many "points" does a person need to get up to the next tier (for example, in my case from 4 to 5)?

Unlike other tiers like Linguists ones it's almost impossible to give a "point" value to a PR so there isn't really a number of PRs or lines of code that trigger a new level. Usually it's 1 PR (no matter the size) for the 1st tier and then the requirements grow.

> Only Pull Requests that have been merged with the main repository count towards that?

Usually yes, but I do realize this case is quite different.

------------

> please don't take this as a complaint or anything, I'm just trying to understand how the system works to manage my expectations 😅

no worries :) it's totally reasonable to ask the about it

I'm aware that this case is different and that there's work involved with the the files that don't result in a merged PR and I'm considering that, but there's also the fact that you're starting from a 4th tier which is quite high and usually require more work before progressing to the next one. If you look at the Hall of Heroes in some cases it took almost 10 PRs to go from one tier to the next, but it really depends on the size of the PR and other factors. Unfortunately without a precise benchmark of what's needed to go from one tier to another it's possible that depending on who awarded the tier or when it was done someone received a tier either earlier or later.

Anyway for now my idea was to list only the PRs that got merged but when the issue is closed to also link it since there's a lot of extra work involved :)

I hope to have clarified a bit but let me know if I missed something!

**Comment by RaitheOfDureya** [comment]
@paglias, thank you very much for taking the time to give me this detailed explanation.
 I understood better how things work :blush:

**Comment by paglias** [comment]
I'm adding back `resetAccount` as it's used in several places 
Schermata 2020-09-19 alle 15 43 49

**Pull request merged**
