### PR TITLE
Tightened up spacing

### PR DESCRIPTION
**Pull request by AnitaYCheng**
Tightened up spacing (requires additional PR in CSS file), added news article links and image alt tags

### CODE REVIEW

**Comment by paglias** [comment]
@AnitaYCheng seems fine but the build is failing for a missing play-btn element https://travis-ci.org/HabitRPG/habitrpg/builds/60645179

**Comment by crookedneighbor** [comment]
Two things:

1) Is there a reason you made a second PR for the CSS changes? Usually, for a change like this, all the commits would be in a single PR. That makes it easier to review.

2) You'll notice the build is failing, that's because your jade file isn't up to date with the change I made to give an id to the play btn. Please merge in the changes from HabitRPGs version of develop.

**Comment by paglias** [comment]
@crookedneighbor 

1) the PRs are separate, probably, because she used the web interface which allow 1 file per PR
2) So when merging the develop build should be ok

**Comment by AnitaYCheng** [comment]
Yes, I used the web interface because I still haven't gotten my local install of HabitRPG working quite yet, so I figured updating the front.jade file separately would be most straightforward. (Not sure if it would work without the local install working, but just wanted to get things done.)

I've never worked on a project with branches in GH before, so sorry for my newbie question: How do I merge in the changes from the develop branch using the web interface?

**Comment by crookedneighbor** [comment]
Actually, just checked both these prs out and combined them, and the front page has jade errors throughout, so do not merge under any circumstances while the build is failing.

**Pull request closed without merging**
