### PR TITLE
Issue #14349 - Fixed group creation on Docker by updating to Mongo 4.2.8 replica set

### LINKED ISSUE #14349: Unable to create party or guild on local docker install
### General Info
  * Locally installed using Docker

### Description
When trying to create a party or guild the site just spills out Unexpected error has occurred on the top right of the page. What is odd is I could have sworn this worked earlier this week, but now on a fresh install it stopped working

#### Console Errors
when looking at the logs of the server,
```
  method: 'POST',
  originalUrl: '/api/v4/groups/',
  headers: {
  ...
  },
  body: { type: 'party', name: "booty's Party" },
  query: {},
  httpCode: 500,
  isHandledError: false,
  fullError: MongoError: This MongoDB deployment does not support retryable writes. Please add retryWrites=false to your connection string.
      at getMMAPError (/usr/src/habitica/node_modules/mongoose/node_modules/mongodb/lib/core/topologies/shared.js:413:18)
      at handler (/usr/src/habitica/node_modules/mongoose/node_modules/mongodb/lib/core/sdam/topology.js:955:15)
      at /usr/src/habitica/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection_pool.js:348:13
      at handleOperationResult (/usr/src/habitica/node_modules/mongoose/node_modules/mongodb/lib/core/sdam/server.js:565:5)
      at commandResponseHandler (/usr/src/habitica/node_modules/mongoose/node_modules/mongodb/lib/core/wireprotocol/command.js:120:25)
      at MessageStream.messageHandler (/usr/src/habitica/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection.js:272:11)
      at MessageStream.emit (events.js:400:28)
      at MessageStream.emit (domain.js:475:12)
      at processIncomingData (/usr/src/habitica/node_modules/mongoose/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
      at MessageStream._write (/usr/src/habitica/node_modules/mongoose/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
      at writeOrBuffer (internal/streams/writable.js:358:12)
      at MessageStream.Writable.write (internal/streams/writable.js:303:10)
      at Socket.ondata (internal/streams/readable.js:731:22)
      at Socket.emit (events.js:400:28)
      at Socket.emit (domain.js:475:12)
      at addChunk (internal/streams/readable.js:293:12)
      at readableAddChunk (internal/streams/readable.js:267:9)
      at Socket.Readable.push (internal/streams/readable.js:206:10)
      at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
      at TCP.callbackTrampoline (internal/async_hooks.js:130:17) {
    originalError: MongoError: Transaction numbers are only allowed on a replica set member or mongos
        at MessageStream.messageHandler (/usr/src/habitica/node_modules/mongoose/node_modules/mongodb/lib/cmap/connection.js:272:20)
        at MessageStream.emit (events.js:400:28)
        at MessageStream.emit (domain.js:475:12)
        at processIncomingData (/usr/src/habitica/node_modules/mongoose/node_modules/mongodb/lib/cmap/message_stream.js:144:12)
        at MessageStream._write (/usr/src/habitica/node_modules/mongoose/node_modules/mongodb/lib/cmap/message_stream.js:42:5)
        at writeOrBuffer (internal/streams/writable.js:358:12)
        at MessageStream.Writable.write (internal/streams/writable.js:303:10)
        at Socket.ondata (internal/streams/readable.js:731:22)
        at Socket.emit (events.js:400:28)
        at Socket.emit (domain.js:475:12)
        at addChunk (internal/streams/readable.js:293:12)
        at readableAddChunk (internal/streams/readable.js:267:9)
        at Socket.Readable.push (internal/streams/readable.js:206:10)
        at TCP.onStreamRead (internal/stream_base_commons.js:188:23)
        at TCP.callbackTrampoline (internal/async_hooks.js:130:17) {
      ok: 0,
      code: 20,
      codeName: 'IllegalOperation'
    }
  },
  level: 'error',
  message: 'MongoError: This MongoDB deployment does not support retryable writes. Please add retryWrites=false to your connection string.'
```

So it looks like the issue has something to do with,
`MongoError: This MongoDB deployment does not support retryable writes. Please add retryWrites=false to your connection string.`

I have tried appending ?retryWrites=false into docker-compose but when I do the build just fails

### PR DESCRIPTION
**Pull request by alexiswatson**
[//]: # (Note: See https://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #14349 

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

- Updated mongo image in docker-compose.dev to 4.2.8
- Converted Mongo instance from standalone to replica set
- Added mongo-init.js script to initialize replica set

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 973e45cb-ff63-40ae-ac99-9538871b0941

### CODE REVIEW

**Comment by alexiswatson** [comment]
Note that some of the linting doesn't really apply here, based on the execution environment of mongo-init.js (ex: `sleep()` is very much a thing). As the wiki mentions, other tests don't reliably run in Docker, so I'd be happy to review the results here (perhaps tackling that in a separate issue).

**Comment by alexiswatson** [comment]
It occurs to me that as a first-time contributor, an admin would need to approve running the workflows here. If one wouldn't mind kicking things off (with the above caveats), I'd be happy to help close this out!

**Comment by alexiswatson** [comment]
As mentioned above, this code runs in Mongo's execution context. `rs` and `sleep` are very much defined. This leaves:

`Error:   5:1   error  Expected an assignment or function call and instead saw an expression  no-unused-expressions`

If the expression conditional syntax is an issue here, happy to change it, but before I do I'd appreciate confirmation from a maintainer that we can either suppress or ignore the other linting here.

Looking forward to getting this merged!

**Comment by ychisbest** [comment]
help a lot,thanks very much!!!

**Comment by CuriousMagpie** [comment]
We're now using Mongo version 5.0.23, so I'm closing this. If you're still having a problem, please open a new issue. Thanks!

**Pull request closed without merging**
