### PR TITLE
Fixed issues with positioning of userlist

### PR DESCRIPTION
**Pull request by snicker**

### CODE REVIEW

**Comment by snicker** [comment]
Pull request now includes fixes for minification of the Angular-At-Directive code

**Comment by snicker** [comment]
Aaaaand the last commit should fix just about every issue with autocomplete.

**Comment by lefnire** [comment]
Dude. Fuck right. Will test asap

**Comment by lefnire** [comment]
Beta'd. Ps, you are one solid open source citizen - look at those PRs to other libs you made just for this ticket! Inspiring :)

**Comment by snicker** [comment]
yeehaw! hey, it's fun. Just trying to think of the next thing to do for HRPG... I figured this would be a good way for me to learn about AngularJS/Node/Jade/Bower/NPM... didn't know a blip about this app stack last week.

**Comment by lefnire** [comment]
You're a beast then my friend! most people start by tweaking a margin :) Well if it's features you're into, take your pick from the [Trello board](https://trello.com/b/EpoYEYod/habitrpg) - "Popular 75+ Votes" column is a solid starting point. If it's bugs (who wants to do that...), there's a world of crits on this issue queue.

**Pull request merged**
