### PR TITLE
Dailies new subheading and summary change

### PR DESCRIPTION
**Pull request by Sylvir9**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Issue #8752 
Fixes put_issue_url_here

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
This is the same as #8780 and is only here due to my git-related ineptitude.  
Also, moved "Repeats never." to tasks.json which I'm assuming makes it translatable probably.
1. Summary for zero repeats now says "Repeats never."
2. New subheading for "Repeat Type"
untitled

[//]: # (Put User ID in here - found in Settings -> API)

----
UUID:

### CODE REVIEW

**Comment by SabreCat** [comment]
This looks pretty good! I'm not sure I agree with the conversation on the original issue ticket about the suggested phrasing, though. "Repeats never" is rather awkward English for this scenario. @Alys @Lalaitha, what would you think about one of the following instead?

"Does not repeat."
"Daily is inactive."
"Daily is disabled."

**Comment by Alys** [comment]
"Daily is never due"

Maybe even something like "Daily is never due (it's a [Grey Daily](http://habitica.wikia.com/wiki/Dailies#Grey_Dailies))" since that's a specific term for it and it has uses as listed on that wiki page.

Disabled / inactive imply that it can't be used.

**Comment by SabreCat** [comment]
Let's go with "Daily is never due." @LlamaLad, care to make that quick change?

**Comment by Lalaitha** [comment]
Sounds good to me. Makes it very clear. :)
Maybe the wording should be adjusted in the apps as well, then? It says "repeats never" there.

**Comment by Sylvir9** [comment]
Yup it's been changed to "Daily is never due"

**Review by SabreCat — APPROVED** [review]

**Comment by SabreCat** [comment]
Thanks, @LlamaLad! What's your User ID from https://habitica.com/#/options/settings/api ? Let me know and I can give you contributor credit on the site!

**Pull request merged**
