### PR TITLE
Replaced Bootstrap "Add to Homescreen" icons

### PR DESCRIPTION
**Pull request by ruddfawcett**

### CODE REVIEW

**Comment by lefnire** [comment]
can't merge automatically, do:

```
git pull origin develop
git checkout public --ours
git commit
git push
```

**Comment by ruddfawcett** [comment]
@lefnire no problem

**Comment by ruddfawcett** [comment]
@lefnire just did that... any difference?

**Comment by lefnire** [comment]
hmm, no difference. try `git push origin develop`, if no cigar i'll manually merge this in. I just like to get it sorted so you get credit for the merge

**Comment by ruddfawcett** [comment]
Oh ok thanks.  I'll try that now.

**Comment by lefnire** [comment]
merged, thanks!

**Comment by ruddfawcett** [comment]
uhh ohh....

@lefnire I think when you merged you added all of the spirites and changed some files??!!! :anguished:

**Comment by lefnire** [comment]
tmk that's just my https://github.com/lefnire/habitrpg/commit/e7ddfb889208db336a3e2785c00f6034817e760c - a commit before you, should be fine

**Comment by ruddfawcett** [comment]
Ok -- sounds good.

**Comment by lefnire** [comment]
oh.. it indeed did revert a few commits, i wonder why that happened. Well, I cherry-picked them back in to be sure

**Pull request closed without merging**
