### PR TITLE
feat(difficulty): Add difficulty settings to user schema

### PR DESCRIPTION
**Pull request by SabreCat**
Lays the initial groundwork for the difficulty settings described at https://trello.com/c/C7CXSo02/428-difficulty-settings-v1. No functional changes at this time, just creating an object in the user schema for later manipulation as these features are implemented. @deilann

### CODE REVIEW

**Comment by SabreCat** [comment]
Something wrong with the Karma build...?

**Comment by lefnire** [comment]
I'd say don't merge this yet till the rest of the feature fleshes out. Partial features often change schema before finalizing implementation

**Comment by SabreCat** [comment]
Yup, works for me!

**Comment by SabreCat** [comment]
Oh, hey, this is as good a place to ask as any: given the current UI overhaul, what do you recommend I do with respect to setting up a new page under Settings? The tabs are going away soon, yeah? Should I create a fresh .jade file rather than building a tab into settings.jade?

CC @benmanley

**Comment by deilann** [comment]
This may also be able to solve #2493 if we included a no damage setting.

**Comment by benmanley** [comment]
@SabreCat My idea was to get rid of the top level tabs (Profile, Social etc.), but keep the second level tabs and restyle them to something like this.

subnavigation

So I would say build the tab into settings.jade.

**Comment by wc8** [comment]
BTW, @benmanley I like that Stable arrangement.

**Comment by SabreCat** [comment]
Very cool. I'll lay it out according to the current scheme, then, and we can adapt it to the new model when the time comes.

**Comment by crookedneighbor** [comment]
@SabreCat What's the status on this? Can it be closed?

**Comment by Alys** [comment]
The `difficulty` branch will need to have the habitrpg-shared changes applied to it before it can be merged, and the initial difficulty settings will need to be finished. That won't be soon.

**Comment by SabreCat** [comment]
We can probably dump the pull request. It's stale enough, and early enough
a WIP, that starting over wouldn't be a bad idea.

**Pull request closed without merging**
