### PR TITLE
Fixes #15038 -- Sorting options in party member list during use of transformation item.

### LINKED ISSUE #15038: Sorting options in party member list fail during use of transformation item
### Description
The dropdown menu with sorting options for the party member list doesn't work when the member list is summoned via the transformation item workflow.

Steps:
1. Purchase some transformation items (Spooky Sparkles, Snowballs, etc.)
2. Have a party with 2+ members
3. Use one of the transformation items, bringing up the party member list
4. Attempt to use the dropdown options to change the sort order

image(1)

### PR DESCRIPTION
**Pull request by leonardochappuis**
Fixes #15038

### Changes
Fixes dropdown menu with sorting options on modal that appears when selecting a party member to use a transformation item.
The original sorting method returned the unmodified array. Changes it to return the sorted one.
Also copies the search function from the "View Party" modal so the search field works in the party member selection modal that appears when using a transformation item.

### CODE REVIEW

**Comment by leonardochappuis** [comment]
I'm a first time contributor so the workflow for tests hasn't run automatically. Please may a mantainer start it? 👉👈

**Comment by leonardochappuis** [comment]
Can someone pls review this

**Comment by MohitBansal321** [comment]
@negue @CuriousMagpie I saw you have access to merge this PR kindly review and merge it

**Comment by negue** [comment]
I'm on it to try it locally - but weird vue gives me some errors (in files you didn't change 😅 ) once that works I can get back to testing the PR ^^

**Comment by leonardochappuis** [comment]
So, did yiu get a chance to try it?

**Comment by negue** [comment]
Once I had it working again, other things took my time 😅, fast forward, tested it now - it works :)

Thank you for the first contribution :)

@SabreCat LGTM

**Comment by leonardochappuis** [comment]
No worries, thank you for reviewing this and for the welcome!

**Comment by SabreCat** [comment]
@leonardochappuis Thanks for this! We'll get this live next deploy. Are you a user of Habitica? If so, let us know your @-username or user ID and we'll give you contributor credit there!

**Comment by leonardochappuis** [comment]
> @leonardochappuis Thanks for this! We'll get this live next deploy. Are you a user of Habitica? If so, let us know your @-username or user ID and we'll give you contributor credit there!

Hey, no problem,
I was looking forward to my first contribution so thank you for merging it!
I actually didn't get much of a chance to use the app other than locally but my username is beuz.

**Comment by SabreCat** [comment]
All right! Well, if you should ever return, you've got your Blacksmith title now at tier 1!

**Pull request merged**
