### PR TITLE
Flagging challenges

### LINKED ISSUE #5557: challenges need a "Report" button to flag violations of the Community Guidelines
_Edit by Alys 2021-09-15_: **There is a mostly-complete PR at https://github.com/HabitRPG/habitica/pull/11920 which another Blacksmith could finish to resolve this issue.**

_In this issue "mod" means moderator or staff member. In the codebase, they can be identified by `user.contributor.admin` being set to `true`._

Players sometimes create Challenges that contain violations of the Community Guidelines. There needs to be a "Report" button for other players to flag such Challenges as needing attention from mods.

The "Report" button should appear when:
- seeing the Challenge in the My Challenges page
- seeing the Challenge in the Discover Challenges page
- viewing the individual Challenge's page (i.e., pages with links like this: habitica.com/challenges/2def5ee7-291b-4ec0-860e-33c2d3d09551)

The button should work in much the same way as it does for chat messages. When you click the button, a confirmation modal appears with two buttons, "Cancel" and "Report". If you click "Cancel", the modal closes and no flag is made. When you click "Report", a report is made (see below for details). When mods view that modal for a Challenge that has already been flagged, they see an additional button, "Reset Flag Count" (see below for details).

The screenshot at the bottom of this post shows the modal a mod sees when they click the "Report" button on a chat message. The chat report modal that a non-mod sees is identical except that the "Reset Flag Count" button is not there.
The modal for reporting a Challenge should look the same except:
- The text of the post ("A test post for flagging." in the screenshot) is replaced with the Challenge's name.
- The "Why are you reporting this post?" subheading should have every "post" changed to "Challenge".
- The "Please help our moderators..." sentence should have "post" changed to "Challenge".
- The "Are you sure..." paragraph should have every instance of "post" changed to "Challenge".
- The "Reset Flag Count" button should appear for only mods.

When the "Report" button is clicked, the following actions need to occur:
- an email is sent to the same recipients who receive notifications about flagged chat messages
- a message is sent to the moderator Slack channel, as is done for flagged chat messages
- the Challenge's document in the database is modified to contain details like these:
```
"flags": {
	"d904bd62-da08-416b-a816-ba797c9ee265": true,
	"3e595299-3d8a-4a10-bfe0-88f555e4aa0c": true
},
"flagCount": 2,
```
Those UUIDs are the User IDs (not Usernames!) of the people who have clicked the "Report" button. The `flagCount` increases by 1 for each non-mod who clicks the button. If a mod clicks the button, the flagCount is immediately set to 5. Those details are the same as for chat messages, so the contributor who works on this can copy what's in the chat schema and code.
When a Challenge has never been flagged, that data looks like below (again, this is the same as the [default data for chat messages](https://github.com/HabitRPG/habitica/blob/d9830950aacc3343d708eccd1a2a33c585e797de/website/server/models/group.js#L450-L451)):
```
"flags": {},
"flagCount": 0,
```

When a mod clicks the "Reset Flag Count" button, these things must happen (they are all the same as is done when resetting flags on a chat message):
- an email is sent to the same recipients who receive notifications about un-flagged chat messages
- the Challenge's `flagCount` is set to `0`
- if the mod's User ID is currently recorded as `true` in the `flags` object, then it's changed to `false`
- _no other changes are made to the `flags` object_
- _no Slack notification is made for unflagging_

When a Challenge has a `flagCount` greater than zero, mods should see a message on the Challenge saying that it's been flagged (e.g., just the word "Flagged"). That message will never need to be seen by non-mod players so it doesn't really matter what it looks like as long as it's clearly visible (e.g., close to the challenge's name). I suggest red text, as is done for a similar message for mods on [flagged chat messages](https://github.com/HabitRPG/habitica/blob/d9830950aacc3343d708eccd1a2a33c585e797de/website/client/components/chat/chatMessages.vue#L23-L24). I'm happy for the contributor who works on this to make a decision about it and show us a screenshot in your PR. It's not worth spending time designing that carefully. The message should appear in these three places:
- seeing the Challenge in the My Challenges page
- seeing the Challenge in the Discover Challenges page
- viewing the individual Challenge's page (i.e., pages with links like this: habitica.com/challenges/2def5ee7-291b-4ec0-860e-33c2d3d09551)

For the first version of this feature, there is no need for flagged Challenges to be hidden from any players, however that is a desired feature and can be added later. See https://github.com/HabitRPG/habitica/issues/9725 for details. For simplicity and to get this feature done more quickly, I suggest that both issues are not worked on at the same time. ~_Previous text: If the contributor who wants to work on this feature also wants to work on that issue at the same time, that's fine, but this first issue is more important and the details of hiding challenges are still being sorted out so that other issue isn't currently ready to be actioned._~

On a local install, the contributor who works on this can turn one of their test accounts into an admin account by using the "Make Admin" button in the Debug menu in the footer of the website, then reload the website. Comment in this issue if that doesn't seem to do what you need - it's been a while since I used that Debug feature. :)

image

### PR DESCRIPTION
**Pull request by matchajune**
Fixes #5557 and #9725 

### Changes
- [ ] report button shows in three places: 'my challenges', 'discover challenges', and an individual challenge page
  - 
  - Screenshot 2023-03-23 at 7 56 39 PM
- [ ] confirmation modal in order to submit a report
  - Screenshot 2023-03-23 at 7 58 01 PM
- [ ] admins should be able to see which challenges are flagged in the three places
  - Screenshot 2023-03-23 at 8 01 57 PM
  - Screenshot 2023-03-23 at 8 02 08 PM
- [ ] hiding behavior for challenges should work if `flagCount` is greater than 1 for non-admin users that aren't participating in the challenge, or for non-admin users that initially created the challenge
- [ ] flagged challenge cannot be ended
  -  Screenshot 2023-03-23 at 8 08 59 PM
- [ ] flagged challenge cannot be cloned
  - Screenshot 2023-03-23 at 8 09 43 PM

----
UUID: b017da59-5635-4994-bf5c-fa7261319ad1

### CODE REVIEW

**Comment by Tressley** [comment]
Hi @matchajune, thanks for your hard work on this. I'd like to request a small change -- Can you remove the "Report" button from the "My Challenges" and "Discover Challenges" views? It only need to exist on the Challenge detail page. Thanks!

**Comment by matchajune** [comment]
Hey @Tressley! Thanks for the review. I've removed the report button on the 'my challenges' and 'discover challenges' views.

**Comment by Tressley** [comment]
@matchajune -- Thanks for your work on this! The team has had a chance to test and we have some feedback:

- The “Report a Challenge” modal is appearing twice
    - To reproduce: Click “Report” on the Challenge and dismiss the modal
- The general experience does not seem to be working as intended:
    - Reporting a Challenge seems to hide other Challenges from the list
    - Reporting a Challenge does not hide it from the list
    - Newly created public Challenges are not displaying in the list
- “Challenge cannot be closed” modal:
    - Update copy to: ”This Challenge cannot be closed because it has been reported as inappropriate and hidden. Please contact admin@habitica.com if you have questions about this or would like more information.”
    - Add close icon
- “Challenge cannot be cloned” modal:
    - Update copy to: ”This Challenge cannot be cloned because it has been reported as inappropriate and hidden. Please contact admin@habitica.com if you have questions about this or would like more information.”
    - Add close icon

We look forward to testing your next round of updates!

**Comment by matchajune** [comment]
Thank you for the testing. Will take a look and make the appropriate changes!

**Comment by Tressley** [comment]
Hey @matchajune -- Thanks for all of your hard work on this. Our developers have recently found time to take this on in addition to some other Challenge-related projects. If you'd like to submit a PR with your current work by Monday, June 26, we'll be rewarding you with a Habitica contributor tier.

Again, we appreciate you taking time to kickstart this. Hopefully we get to see more of your contributions in the future!

**Comment by matchajune** [comment]
Hey @Tressley -- It was fun working on the challenge feature! Unfortunately, I won't be able to complete the feedback given by June26th. The developers that found time can pick this PR up in order to bring it to the finish line if they would like!

Thank you for your patience and feedback so far! Please tag me if there is a new PR created for this feature as I would love to see the finished implementation!

**Comment by CuriousMagpie** [comment]
Thank you for all your work on this, @matchajune! We're pulling your work into another PR so I'll be closing this.

**Pull request closed without merging**
