### PR TITLE
Max HP is now 500; Potion heals for 150; HP is always an integer

### PR DESCRIPTION
**Pull request by tmrotz**
Associated with https://trello.com/c/W46gHos0
My first pull request. Looking for feedback.

### CODE REVIEW

**Comment by Alys** [comment]
@tmrotz I'm very sorry, but we probably won't be able to accept this, or at least not without many other, related changes and significant discussion and advance notice to all of the users. Increasing the health alone will dramatically change the balance of the game, and so we would also have to change task earnings and punishments, skill effects, boss stats, etc.

The trello card containing that suggestion was not approved; it's in the "new/icebox" category which means it's there to collect feedback and for future consideration and planning. I realise that's not obvious, and I'm sorry that caused you to spend time on this that might end up being wasted. We'll modify the blacksmiths documents on the wiki to explain trello processes more clearly.

**Comment by tmrotz** [comment]
@Alys I fully understand the premature nature of my pull request. I'm actively working to get the card resolved, whatever that may mean. I thought this would be a good place for someone brand new to the code base to start, even though there is only a small chance it will ever be approved.

I would love a critique of my work. How will it dramatically change the balance of the game? All it does is multiply everything related to HP by 10. Is there anything else I'm missing?

**Comment by Alys** [comment]
One big change is that with maximum health being 500 instead of 50, there is a much less chance that damage from missed Dailies and quest bosses will kill a player before they can level up. This will remove a large portion of HabitRPG's motivational features. To balance this, we'd need to increase the damage that Dailies and bosses do, and we'd also have to rebalance the items in the game that grant health and provide protection. That rebalancing would take a lot of work, and I'm not sure that it's worth it for the sake of removing decimal places. There are many other changes and bug fixes that are needed for HabitRPG and it would be better for us to focus on them.

Please note that not all cards in Trello are currently suitable for the requested features to be created. For some cards, more planning or adjustments to the features are needed. For others, the best resolution might be to decide that the requests should not be fulfilled (e.g., if it would significantly complicate the game for players, or unbalance it in ways that cannot be easily compensated for). 

We do appreciate that you're willing to work on the site, and we'd love to see more changes from you, but for Trello cards, I recommend that you first post in the card to ask if its suitable for you to work on it, and wait until the HabitRPG staff respond.

If you'd like some easy fixes to start with, several small bug fixes and feature improvements are listed in Trello under the [entry level coding](https://github.com/HabitRPG/habitrpg/labels/entry%20level%20coding) label. We would definitely like to see pull requests for them, if any of them look interesting to you! You're welcome to comment in those issues if you have questions about them or would like advice about how to proceed.

**Comment by crookedneighbor** [comment]
Closing this since it is not a desired change to the code base, but please do open more PRs. We love contributions!

**Pull request closed without merging**
