### PR TITLE
make vertical dividing line in Market extend all the way - fixes #4556

### LINKED ISSUE #4556: Vertical dividing line in Market doesn't extend all the way
In the Market, the dividing line between the player's inventory and Alexander's items for sale doesn't extend all the way through the page:

image

It's somewhat resolution-dependent. The above was on my 4:3 monitor; if I move it to my widescreen, the line makes it past the first row of Food items.

### PR DESCRIPTION
**Pull request by ghost**
Hi! 

I moved the border from the left div to the right so the dividing line goes all the way to the bottom. This is my first pull request on GitHub, so hopefully I am doing this right.

screen shot 2015-01-26 at 23 12 46
screen shot 2015-01-26 at 23 13 22

### CODE REVIEW

**Comment by Alys** [comment]
I've tested locally and it definitely fixes https://github.com/HabitRPG/habitrpg/issues/4556

The code looks consistent and clean to me, but I'm just waiting a day to hear if there's any comments from our CSS experts, and then I'll merge this and award a tier.

**Comment by crookedneighbor** [comment]
The only situation (that I'm aware of) where this method fails is if the user has a ton of items, then the user items pane is longer than the merchant:

screen shot 2015-01-27 at 9 26 21 am

But to illustrate that screenshot, I had to load up my local user with all the drop and quest eggs, all the quest scrolls, and most of the food. Not impossible, but highly unlikely for most users. Even then, it's only like 2 rows longer. So, I think it's fine to do it this way. It'll look perfect in 99% of use cases.

**Comment by crookedneighbor** [comment]
@matttelliott This will count towards a contributor tier. Can you post your user id here? It can be found in [settings > api](https://habitrpg.com/#/options/settings/api)

**Comment by ghost** [comment]
My User ID is: ad3efbbe-6bc1-4103-9deb-b8fe6d2f7701

**Pull request merged**
