### PR TITLE
fix(task list): update todo due date on every save (#12254)

### LINKED ISSUE #12254: changing due date twice on a new To-Do does not update the view
If you create a To-Do, then set a due date, the due date appears correctly. If you immediately change the due date, the new date does not appear (you still see the first one). When you sync, you see the second date, so this is merely a display problem, not a problem with the date being saved to the database. After you have synced, the problem no longer occurs.

Steps to reproduce:
1. Create a To-Do using the "Add a To-Do" box at the top of the To-Dos column.
1. Click the To-Do to open its edit screen.
1. Set a due date (any date will be fine for this, including one in the past).
1. Click the save button (either the top or bottom save button is fine - they work the same for all steps here).
1. Observe that the date you selected is accurately represented in the text at the bottom left of the task.
1. Click the To-Do to open its edit screen.
1. Change the due date (any date different from the first one).
1. Click the save button.
1. Observe that the date represented in the text at the bottom left of the task has NOT changed. It still indicates the original date you set, not the new one.
1. Click the sync button in the header. 
1. Observe that the second date you selected is now accurately represented in the text at the bottom left of the task.
1. Click the To-Do to open its edit screen.
1. Change the due date (any date different from the previous two dates).
1. Click the save button.
1. Observe that the third date (the one you just selected) is accurately represented.
1. Repeat the date edits if desired; observe that each new date is accurately represented immediately - no further syncs are needed.

_Thanks to Jubineo / crThiago (12601b79-cf8e-44b7-94b9-2bafc97adc16) for reporting this._

### PR DESCRIPTION
**Pull request by bigsee**
Fixes #12254 

### Changes
Listens for the @taskEdited event in the user page and then syncs user data if task.type is 'todo'.

----
UUID: 7e694dc6-6c80-4d4a-bc7d-264b6d5022a0

### CODE REVIEW

**Review by paglias — CHANGES_REQUESTED** [review]
Hi @bigsee , thanks for the PR! This way every time a todo is edited the entire user object and tasks will be fetched from the server which should not be necessary. I've not looked into the issue but this seems to be a problem with data not refreshing correctly on the client, not a lack of data that requires an API call to the server

**Comment by bigsee** [comment]
@paglias thank you for your helpful feedback!

I tried a few different options instead, including re-rendering of components. The issue seems to be with the reactivity of computed properties. Disabling the caching of the props in question fixes the issue.

I tried looking at how to restructure the store action that mutates the data to perhaps fix there but didn't find anything obvious. I didn't want to dig around too deeply and mess something else up.

**Comment by bigsee** [comment]
P. S. A previous comment in the code seems to suggest there was already an issue of reactivity here. The previous workaround didn't seem to work for this use case so perhaps a bigger issue to eventually look into...?

**Comment by paglias** [comment]
> P. S. A previous comment in the code seems to suggest there was already an issue of reactivity here. The previous workaround didn't seem to work for this use case so perhaps a bigger issue to eventually look into...?

Yeah I remember something similar happened a few months ago but it got fixed, I tested this issue and it's quite weird, it only happens if you change the due date twice the first time the task is created (if you create the task and then refresh the page it'll work fine). I'm going to give a look at it better in the next few days, thanks for the PR!

**Comment by paglias** [comment]
Sorry for the delay @bigsee , the code looks good but the Vue docs mention that `cache: false` is deprecated and methods should be used instead https://vuejs.org/v2/guide/migration.html#cache-false-deprecated

**Comment by bigsee** [comment]
@shanaqui this is the latest status, FYI... :)

**Comment by bigsee** [comment]
@paglias thank you for the feedback. My turn to apologise for the delay! I ended up very busy with work the last couple of weeks. I will leave some time for revising this over the weekend.

**Comment by SabreCat** [comment]
@bigsee Are you still looking to take this over the finish line? If not, we at Habitica HQ are thinking of knocking this out with some other task fixes coming up!

**Comment by bigsee** [comment]
@SabreCat I'm really sorry for the delay! I would be very happy to make another pull request but please don't let me block it if you guys have a fix already. Just let me know what you'd prefer.

**Comment by SabreCat** [comment]
@bigsee If you think you'll have a chance to try the method-based fix in the next few days, we'd love to see your contribution! But if you're still swamped this week/next, we can pick it up.

**Comment by bigsee** [comment]
@SabreCat OK great. I should get to this over the weekend.

**Comment by bigsee** [comment]
@SabreCat implemented the method-based fix following the advice from @paglias. Let me know if you need anything else.

**Comment by paglias** [comment]
thanks @bigsee , looks like some extra commits got added to the PR, it happens sometimes when merging branches in a local copy that is not fully updated. Could you try to fetch the most recent develop locally and make a new branch from there?

**Comment by bigsee** [comment]
@paglias I did _try_ to do that, by fetching first. I think I might be gotten confused and perhaps unnecessarily ran the commands and rebase from [here](https://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API).

Will try to fix now.

**Comment by bigsee** [comment]
@paglias apologies for my ignorance. This is what I see at my end after creating the new branch:

Screen Shot 2020-07-27 at 10 24 02

Should I make a new PR with this other branch?

**Comment by paglias** [comment]
@bigsee that looks good but it's a bit difficult to be sure without seeing the actual PR, so yes I'd try to make a new PR and hopefully no extra commits have been included, if it's not solved yet after the new PR we can look into a different solution

**Comment by paglias** [comment]
@bigsee I've opened #12420 to include only the necessary commit

**Comment by paglias** [comment]
merged in #12420

**Comment by paglias** [comment]
@bigsee  thanks for this! I'm merging the PR and awarding your contributor tier.

Note that further tiers require increasing amounts of work from one to the next, so Tier 2 may require a couple of PRs or a larger PR to attain. But keep helping out and we'll express our gratitude accordingly!

**Comment by bigsee** [comment]
@paglias thank you! Very happy to get my first ever contribution under my belt.

I'll be looking for more tasks I can contribute on but I will focus on delivering a bit faster for future ones hopefully. Apologies again for the delays on my side and thank you, again, for your patience and guidance! 🙏🏽😁

**Comment by paglias** [comment]
@bigsee no worries about the delays and thanks again for helping with a PR

**Comment by SabreCat** [comment]
@bigsee The first one always takes a bit of extra time as you work out the logistics! Looking forward to seeing what else you come up with!

**Pull request closed without merging**
