### PR TITLE
Settings: Add missing margin to settings checkboxes - Fixes #12794

### LINKED ISSUE #12794: missing margin on checkboxes at User Icon > Settings
The checkboxes at User Icon > Settings ("Site" tab) have no margin between them and the text.

image

I'm labelling this as "on hold - needs design" for a design-related decision about how much margin should be there.

_Thanks to @tripplehelix (874e648a-2df7-4312-a9e6-7217be462204) for reporting this._

### PR DESCRIPTION
**Pull request by he1d1**
[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #12794

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
I added a `class="mr-2"` to the checkboxes so they have the correct margin discussed in #12794 

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 12311c76-5892-4fc6-b48a-28b45b644d36

### CODE REVIEW

**Comment by he1d1** [comment]
image
This is what it looks like.

**Comment by he1d1** [comment]
#11260 this hasn't been fixed in this pr so i should do that aswell (ty @codemicro)

**Review by he1d1 — COMMENTED** [review]
The checkboxes in the notifications page had the same issue.

**Comment by SabreCat** [comment]
Thanks for this, @hiluw, and welcome to the ranks of the Blacksmiths at tier 1! Further tiers require multiple or larger PRs to attain, but keep helping out and we'll express our gratitude accordingly!

**Pull request merged**
