### PR TITLE
Add ability to hide completed dailies.

### PR DESCRIPTION
**Pull request by Gaelan**
While I was at it, I also did a bit of refactoring in general around the hiding
of completed todos/dailies.

### CODE REVIEW

**Comment by Gaelan** [comment]
FYI my UUID is `4d286073-0a32-43fd-aad8-40ea713510d7`.

**Comment by Gaelan** [comment]
companion shared pr ^^

**Comment by Gaelan** [comment]
What needs to be done for this to be merged?

**Comment by deilann** [comment]
@lefnire needs to look over this one. It's just a time thing.

**Comment by Gaelan** [comment]
@deilann Cool. Thanks so much for the response.

**Comment by Gaelan** [comment]
Yuck, merge conflicts. Should I merge or rebase?

**Comment by lefnire** [comment]
`git rebase upstream/develop hide_completed_dailies`. Rebasing is always the better option when working on an un-merged feature branch _unless_ you have so many commits on that feature branch that a rebase triggers conflict resolution for most commits, in which case a merge isn't the end of the world. Merges just create dirty/duplicate history when merging back into the main branch

**Comment by Gaelan** [comment]
Thanks.

**Comment by Gaelan** [comment]
:white_check_mark:

**Comment by crookedneighbor** [comment]
@Gaelan thanks for your work on this. I wrote a Chrome plugin to do something similar, but it'll be nice to have it baked in from the start.

**Comment by Gaelan** [comment]
@crookedneighbor You're welcome!

**Comment by Alys** [comment]
To help test this, I pulled it down to my local install and merged it with a fresh copy of habitrpg/develop. 

The tabs work nicely for Dailies, although they're spread over two rows in my browser, which makes them a bit harder to use than if they were in one row.
screen shot 2014-09-16 at 8 35 14 pm
If "Remaining" was changed to "Due" would they fit in one row? I think that might be worth considering, although it might only be a fix for English users. 

It might also help to change "Complete" to "Grey", because the Complete tab does contain Grey Dailies that haven't been literally completed. The term [Grey Daily](http://habitrpg.wikia.com/wiki/Dailies#Grey_Dailies) is used to mean both completed and not-due-today Dailies, so it might fit better here than Complete.

I did notice one problem with Dailies: If I'm on the Remaining tab, and I edit one Daily to make it grey for the current day, it disappears immediately. I have to find it on the Complete or All tabs to save it. There was a fix for similar behaviour in https://github.com/HabitRPG/habitrpg-shared/pull/280/files (the `task._editing` code). It would be nice if something similar could be done here, although I don't think that's a show-stopper.

The three tabs also appeared in my To-Dos column, however only the Remaining tab worked there. I was unable to see completed To-Dos at all.

**Comment by Alys** [comment]
@Gaelan : I'm really keen to see your buttons for hiding completed Dailies go live. I'd use them often and I know many others would - it would be an immensely popular feature. I was wondering if you'd like some help finishing this off? If I do work on it, it would be only relatively small changes to fix the problems that are preventing us from making it live now. You'd still get the credit for creating the feature, and the contributor tier and gems.

If you agree, here's what I'd do:
- temporarily remove or comment-out the code that adjusts the To-Dos section
- rename the Dailies tabs to make the labels smaller
- fix the merge conflicts
- test

I think that would be enough to allow us to merge your change and it would go live in a few days. What do you think? If you'd prefer that you did this yourself, I'd understand completely, but if you don't have the time or the inclination, I have a bit of time free over the next day or two. :)

**Comment by Gaelan** [comment]
@Alys Please do.

**Comment by Alys** [comment]
@Gaelan , I've made [this PR](https://github.com/HabitRPG/habitrpg/pull/4129) which contains your work with the three minor fixes I wrote about in my previous comment. Tell me if you don't like what I've done or if you see any problems with it! If you have no objections and if no one else points out anything wrong with it, then I'll merge it tomorrow and give you the contributor tier. My testing for the Dailies tabs went well and it was SO NICE to see the completed Dailies disappear! I think your change is going to be really popular.

For the To-Do code, I've uncoupled it from the Dailies code so that we can do separate things with the two task types (e.g., a "Dated" column for To-Dos only, which I've been planning to create for a while now - your code will make that easier!).

**Comment by Alys** [comment]
@Gaelan I've made one last change to make the "All" view the default one, instead of the "Remaining/Due" view. For most people, it would make sense to have Due as the default, but since this is such a new feature, I think it's best to keep the previous behaviour as the default. People with long Dailies lists won't notice the new tabs immediately, but they would notice their completed Dailies disappearing, and we would get bug reports saying that their Dailies had been deleted. :-/ 

After people have got used to the new tabs, then we could consider making Due the default. We might want to do a poll to ask people what they think about that.

**Comment by crookedneighbor** [comment]
@Alys @Gaelan In the remaining/due tab, the dailies that are not assigned for that day will not be present, correct? A few comments ago, @Alys mentioned that there was a bug with editing the day while on the due tab. Did that get solved?

**Comment by Alys** [comment]
@crookedneighbor : 1. Correct. 2. I'll submit a patch for it as soon as Gaelan's PR is merged.

**Comment by Alys** [comment]
https://github.com/HabitRPG/habitrpg/pull/4129 is merged.

@Gaelan I've given you another tier. :)

**Comment by crookedneighbor** [comment]
@Alys I was about to explore the option of adding a setting beneath the "Open new tasks in edit mode" to make "Due" the default setting for dailies, but I quickly found out that it would require editing habitrpg-shared to make it possible, including the locale json files. 

So, my first question is, is that a feature that would be considered for merging? 

Second, if so, how would I handle the many locale files? Do I just do the english one and let other contributors patch the language problem as they notice it, or what?

**Comment by Alys** [comment]
That's a lovely idea and would most certainly be considered for merging!

"Do I just do the english one ..." - Yes, exactly as you describe. There are readme files in the top-level locale directory that describes this in more detail.

**Comment by crookedneighbor** [comment]
Awesome. I will look those over. Then, as far as submitting the PR goes, would I just submit the two in tandem and reference each in the other PR?

**Comment by Alys** [comment]
Correct! :)

**Pull request closed without merging**
