### PR TITLE
Fixed stats points allocation issues

### LINKED ISSUE #10334: Stats Points allocation problems (negative points occur, loading button remains, etc)
It's now possible to have negative Stat Points. For example:
```
{
    "_id": "8bd2ae53-18c1-445d-8e49-af67eac9dc28",
    "profile": { "name": "Syraxis" },
    "stats": {
        "per": -20,
        "int": 25,
        "con": 8,
        "str": 0,
        "points": 0,
        "lvl": 13,
    },
    "preferences": {
        "allocationMode": "flat",
        "disableClasses": false
        ["automaticAllocation" is not set] 
    },
    "flags": {
        "classSelected": true
    },
    "auth.timestamps.created": "2018-02-14T16:58:09.867Z"
}
```

Syraxis: _"My perception keeps going negative. It has done it twice now. Both times it shows that I have negative points allocated to that stat. First time was -10, how is -20. I believe this started after I joined a guild and they were using buffs on the party but I am not sure."_

citrusella, the serving wench: _"@Syraxis This is just a guess at part of the issue since I also can't replicate it (and also know nothing about it), but did you ever used to be level 33? Your allocated points *technically* total to your current level of 13, but not in a way that you should have been able to allocate them that way, since you, well, can't allocate points negatively (and shouldn't have points to allocate higher than your current level). (The math: 25+8+(-20)=33-20=13)"_

Syraxis: _"No, this is a brand new account."_

Syraxis's first report was 13 hours ago and I don't recall seeing this before so I believe it's a new bug. I've fixed Syraxis's Stat Points.

### PR DESCRIPTION
**Pull request by TheHollidayInn**
Fixes #10334
- Fixes update stats state
- Fixes layout issue
- Prevent deallocation when user has no points to allocate

### CODE REVIEW

**Comment by Alys** [comment]
On staging now when you change class then assign all points to one stat, then click save, you're told you don't have enough stat points and your change doesn't get saved

**Comment by TheHollidayInn** [comment]
I've just tried with each class and haven't been able to recreate

**Comment by Alys** [comment]
It's still happening for me. I changed from Warrior to Mage, put all points in INT, got the error message.  Also the "loading" button froze on loading again. This appeared in the console:

```

Unhandled promise rejection 
Error
​
columnNumber: 128641
​
config: Object { timeout: 0, xsrfCookieName: "XSRF-TOKEN", xsrfHeaderName: "X-XSRF-TOKEN", … }
​
fileName: "https://habitrpg-staging.herokuapp.com/static/js/vendor.36897eb8b59d2fd1dbc0.js"
​
lineNumber: 6
​
message: "Request failed with status code 401"
​
request: XMLHttpRequest { readyState: 4, timeout: 0, withCredentials: false, … }
​
response: Object { data: {…}, status: 401, statusText: "Unauthorized", … }
​
stack: "t.exports@https://habitrpg-staging.herokuapp.com/static/js/vendor.36897eb8b59d2fd1dbc0.js:6:128641\nt.exports@https://habitrpg-staging.herokuapp.com/static/js/vendor.36897eb8b59d2fd1dbc0.js:12:1220\nt.exports/</h[p]@https://habitrpg-staging.herokuapp.com/static/js/vendor.36897eb8b59d2fd1dbc0.js:6:127655\n"
​
__proto__: Object { … }
vendor.36897eb8b59d2fd1dbc0.js:6:212942
P/</e<
https://habitrpg-staging.herokuapp.com/static/js/vendor.36897eb8b59d2fd1dbc0.js:6:212942
t.exports
https://habitrpg-staging.herokuapp.com/static/js/vendor.36897eb8b59d2fd1dbc0.js:6:120977
P/<
https://habitrpg-staging.herokuapp.com/static/js/vendor.36897eb8b59d2fd1dbc0.js:6:212819
t.exports
https://habitrpg-staging.herokuapp.com/static/js/vendor.36897eb8b59d2fd1dbc0.js:6:118770
<anonymous>
https://habitrpg-staging.herokuapp.com/static/js/vendor.36897eb8b59d2fd1dbc0.js:6:74113
y
https://habitrpg-staging.herokuapp.com/static/js/vendor.36897eb8b59d2fd1dbc0.js:6:73971
b
https://habitrpg-staging.herokuapp.com/static/js/vendor.36897eb8b59d2fd1dbc0.js:6:73991
```

**Comment by TheHollidayInn** [comment]
Can you send me your UUID?

**Comment by Alys** [comment]
Sure, sorry! d904bd62-da08-416b-a816-ba797c9ee265

Loggly link: https://habitica.loggly.com/search#terms=d904bd62-da08-416b-a816-ba797c9ee265&from=2018-05-07T00:00:00.000Z&until=2018-05-09T22:22:28.047Z&source_group=
but nothing relevant appears

**Pull request merged**
