### PR TITLE
Move overview to website

### PR DESCRIPTION
**Pull request by AminArria**
#6168 Early PR  to seek guidance.

Is it better to have one giant string like "step3Text", a bunch of little strings like all the "step1*", or it just depends of how I prefer to implement it? 

Any other input/critic/suggestion is appreciated.

Thanks

### CODE REVIEW

**Comment by SabreCat** [comment]
I'd model it after how we laid out strings for the FAQ: https://github.com/HabitRPG/habitrpg/blob/develop/common/locales/en/faq.json . What you've got looks like the right idea!

**Comment by AminArria** [comment]
Any idea why the test failed?

**Comment by Alys** [comment]
There's a good chance it's an unrelated once-off glitch. I'm restarting the test.

**Comment by crookedneighbor** [comment]
Travis has been a little bit flaky today.

**Comment by AminArria** [comment]
Look like it was that glitch.

Any other suggestions or things I'm missing?

**Comment by SabreCat** [comment]
@AminArria: Looking good! I've PRed some tweaks to your branch. Next up I'll see about resolving the merge conflicts.

**Comment by SabreCat** [comment]
@AminArria: OK, all set. Merge my PR into your branch, and I'll get this into `develop`!

Once that's done, this will count toward a contributor tier! What's your [user ID](https://habitica.com/#/options/settings/api)?

**Comment by AminArria** [comment]
@SabreCat Done

Thanks for the contributor tier! 
user ID: d1c621be-418e-479d-8892-95a962533ca9

**Pull request merged**
