### PR TITLE
Hide "Delete Completed" To-Dos button on Challenge or Group Task Board - fixes #9935

### LINKED ISSUE #9935: "Delete Completed" To-Dos button should not appear in Challenge page or Group Plan Task Board
The "Delete Completed" button for removing To-Dos should not appear in a Challenge's page:

screenshot_2018-02-03_20-09-32

Nor in the Task Board of a group with a Group Plan:
screenshot_2018-02-03_20-10-39

The only place it should appear in on the user's Task page when you click on the "Complete" tab for To-Dos (it currently does appear there correctly so that does not need to be changed).

### PR DESCRIPTION
**Pull request by srhboo**
Checks the prop `isUser` in a task column to determine whether the "clear completed to-dos" component is shown (including "Delete Completed" button and info text). It will only display in the User task board and is hidden for the Challenges and Group task board.  

### Before
screen shot 2018-03-11 at 7 39 30 pm
Challenges

screen shot 2018-03-11 at 7 39 38 pm
Group

### After
screen shot 2018-03-11 at 7 39 05 pm
Challenges

screen shot 2018-03-11 at 7 37 17 pm
Group

fixes #9935 

UUID: 375b8855-d745-4b9f-abdb-ccfa5043415e

### CODE REVIEW

**Comment by srhboo** [comment]
An integration test is timing out for some reason causing CI build to fail

**Comment by Alys** [comment]
Test timeouts tend to take place. It's often not connected with the code changes. I'm restarting the tests.

**Comment by srhboo** [comment]
@Alys thank you! seems to pass now :) this one is ready for review

**Comment by paglias** [comment]
this is working great, thanks @srhboo . It'll be merged next week

**Comment by srhboo** [comment]
awesome! thanks @paglias

**Comment by paglias** [comment]
@srhboo  thanks for this! I'm merging the PR and awarding your contributor tier.

Note that further tiers require increasing amounts of work from one to the next, so Tier 2 may require a couple of PRs or a larger PR to attain. But keep helping out and we'll express our gratitude accordingly!

**Comment by srhboo** [comment]
@paglias sounds good to me :)

**Pull request merged**
