### PR TITLE
Fixes CSV challenge data unable to be exported (Fixes #8350)

### LINKED ISSUE #8350: Unable to Export to CSV Challenge Data
## General Info

bc10ec41-4213-4482-bbb8-558e3c3ea8d5
Opera 42.0.2393.85
Windows 10 32-bit

## Description

When export CSV challenge data receiving error message on screen:
{"success":false,"error":"InternalServerError","message":"An unexpected error occurred."}

Example Challenge:
[Clean the Dungeon (dailies slayer) – December – Winter Wonderland (Snowball all the monsters of the day) ID: 3f0be455-990c-49b0-90cc-2ef3b9214949](https://habitica.com/#/options/groups/challenges/3f0be455-990c-49b0-90cc-2ef3b9214949)

No Console error messages,

----

**edit by Alys 2017-08-10:**

## Suggested Fix

**The explanation for this bug and a suggested fix is in [this comment below](https://github.com/HabitRPG/habitica/issues/8350#issuecomment-321517442).**

----

## What to do if this happens to you

Post to the Report a Bug guild and copy the URL of the challenge into your post. An admin will probably be able to make the CSV file available.

### PR DESCRIPTION
**Pull request by jonathanly**
[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
(Partially?) fixes [#8350](https://github.com/HabitRPG/habitica/issues/8350)

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
* Checks if `resArray[index]` exists before executing
```
resArray[index].push(`${task.type}:${task.text}`, task.value, task.notes);
```

P.S. Sorry about the multiple commits, I can fix it and resubmit the PR if it is an issue!

----
UUID: 6b256fd5-de32-4db6-9d88-9b5bf38a20a5

### CODE REVIEW

**Comment by librarianmage** [comment]
What is the status of this?

**Comment by jonathanly** [comment]
Hey @MathWhiz, this PR is waiting for help/review from one of the maintainers (:
However, I believe reviewing PRs are on the backburner at the moment as they move from angular to vue.

**Comment by SabreCat** [comment]
@jonathanly Thanks for your patience as we work around to reviewing this! The functional change on this PR looks good, but would it be possible to write a test for it? It'd involve adding the old failure condition to https://github.com/HabitRPG/habitica/blob/develop/test/api/v3/integration/challenges/GET-challenges_challengeId_export_csv.test.js and confirming the route continues without error.

**Comment by SabreCat** [comment]
@jonathanly Will adding tests to this PR be feasible? Do you need any help or advice?

**Comment by jonathanly** [comment]
Hey @SabreCat, sorry I only just came across the notifications.
I'll take a look and have a shot at adding tests in the next few days. Will probably need a bit of advice as I'm quite unfamiliar with integration tests 😃

**Comment by paglias** [comment]
@jonathanly let me know if you need any help writing those test :)

**Comment by lemoness** [comment]
@jonathanly Hi there! Just checking in -- how is this going?

**Comment by lemoness** [comment]
Since we haven't had any response since December, I'm going to say that this PR needs to be closed or taken over @paglias @thehollidayinn @SabreCat

**Comment by lemoness** [comment]
I've updated the labels to indicate that this PR has been abandoned and needs to be reviewed by our devs.

**Comment by Alys** [comment]
I'm going to test this locally and write a test for it.

**Comment by Alys** [comment]
Actually, @asherdale is working on the issue now so I'll close this PR.

**Pull request closed without merging**
