### PR TITLE
Issue #3477 (again) - Fixed admin email address display text from admin@gmail.com 

### PR DESCRIPTION
**Pull request by ebiagogo**
to admin@habitrpg.com.

### CODE REVIEW

**Comment by paglias** [comment]
@ebiagogo thanks! UUID?

**Comment by ebiagogo** [comment]
My pleasure.

ebe34b97-b3f0-4dc6-8987-0db414042619

**Comment by paglias** [comment]
@ebiagogo hey I've viewed your profile and since you already received a level for this change in an older pull request I'm not going to award a third level for this only. You'll get it with the next contribution

**Comment by ebiagogo** [comment]
@paglias yup, that seems fair enough to me.

**Pull request merged**
