### PR TITLE
E2E test suit for protractor - User pages

### PR DESCRIPTION
**Pull request by Jarda8**
Bunch of e2e tests for pages under the "User" menu item. The tests don't cover that much now. I want to see your opinions on this before I add more of them. The tests are working correctly on Chrome, not so much on Firefox (getting some weird errors there). The style of tests is described in PR #6868 , we work together on this.

### CODE REVIEW

**Comment by Jarda8** [comment]
There are some selections based on a visible element text (linkText). Because of this the tests work only for the English version of Habitica.

**Comment by crookedneighbor** [comment]
See this comment: https://github.com/HabitRPG/habitrpg/pull/6868#issuecomment-196058272

**Comment by Jarda8** [comment]
OK. I hope it will be soon, so I can continue with the testing. :)

**Comment by crookedneighbor** [comment]
Update is done.

**Comment by Jarda8** [comment]
These tests need another test before them to log in and go through the welcome tour. (e.g. the static-pages/front-page.test and tasks/test, without the log off at the end).

**Comment by Jarda8** [comment]
I am not sure, why "protractor" is not defined. Works fine on my computer.

**Comment by khipkin** [comment]
The error is from linting.  I think `protractor` is in the global namespace, which is why eslint is saying it's undefined.

From [the eslint documentation](http://eslint.org/docs/rules/no-undef), you need to put the following before the "undefined" function:

```
/*global someFunction*/
/*eslint no-undef: 1*/
```

**Comment by Jarda8** [comment]
You are right, it is ESLint. But I think that better solution will be to add the whole protractor environment to the ESLint config file. Or at least "protractor" to the globals.

**Comment by khipkin** [comment]
Oh yeah, that's much better.  I didn't know about that!

**Comment by crookedneighbor** [comment]
I would add it to the eslintrc in test/e2e since its specific to those tests.

**Comment by crookedneighbor** [comment]
See this comment. It applies to this PR as well: https://github.com/HabitRPG/habitrpg/pull/6868#issuecomment-199828156

**Comment by crookedneighbor** [comment]
See https://github.com/HabitRPG/habitrpg/pull/6868#issuecomment-207889557

**Pull request closed without merging**
