### PR TITLE
Fix issue #9534 - changed the character-name

### PR DESCRIPTION
**Pull request by aalsehly86**
Fixes https://github.com/HabitRPG/habitica/issues/9534

### Changes
Changed the colors for character-name and level details.

----
UUID: 4998c3fd-1c32-4ad2-bd2d-cc09823d83c2

### CODE REVIEW

**Comment by negue** [comment]
@aalsehly86 thanks for your contribution 👍 , as for the party member modal this sure fixes the problem, but the name in the page header (of your own avatar name) would be too dark.

**Comment by aalsehly86** [comment]
@negue you're right, thanks for letting me know! My bad I didn't notice it. Changed now to `$header-color`. 

This is how it appears now in modal
modal

and in page header
header

Please let me know if this color is suitable. Thnaks.

**Comment by negue** [comment]
yeah now it does look good in the page, but I don't know about the modal haha

@Tressley what do you think? should we use different colors in the header / modal or use the old contributor level colors for the name?

**Comment by aalsehly86** [comment]
@negue this issue just got more complicated haha

I think this will make everybody happy though!

modal page `$gray-200`
modal

header page back to original `$white`
header

Please let me know if this works, I'll submit the changes for review.
Thanks

**Comment by Tressley** [comment]
@negue / @aalsehly86 -- Can you update the "Character Name" color to `#4e4a57` and "Level X Class" color to `#878190`? Thank you for your hard work on this!

**Comment by aalsehly86** [comment]
@Tressley / @negue I'm so sorry for my delayed response, does this look good?
modal-edit

**Comment by Tressley** [comment]
@aalsehly86 -- Looks great! Thank you for all of your hard work.

**Comment by aalsehly86** [comment]
You're welcome @Tressley.

**Comment by negue** [comment]
Looks good now :+1:

**Comment by SabreCat** [comment]
Merged! @aalsehly86 , we will use this in a staging environment for a bit to ensure no unexpected side effects have occurred, but you will see this live in a few days. I've awarded you your first Blacksmith contributor tier for this effort, thank you! Note that subsequent tiers require increasing amounts of effort from one to the next, so tier 2 may require multiple PRs or a larger PR to attain. But keep helping out and we will express our gratitude accordingly!

**Comment by aalsehly86** [comment]
Great! @SabreCat, thank you so much for the awarded tier. I started helping on this repo as a part of a Computer Science class project and I wish those tiers count towards my grade haha! **Habitica** has a great team and I'm glad to help you all and share whatever I know. I've joined the Arabic translation team and hopefully we can get all strings translated soon. I just need to get the final exams out of the way next week, wish I can debug my luck on that!

**Comment by SabreCat** [comment]
@aalsehly86, that's fantastic! Was Habitica specifically recommended as a possible project, or did you find us on your own? If your teacher/professor mentioned us, we'd love to hear from them-- @lemoness, email leslie@habitica.com, would be the person to email.

**Comment by elementc** [comment]
Hi, I'm the lab instructor for their course, cdoran2011@my.fit.edu, and Keith Gallagher, kgallagher@fit.edu, is the instructor of record.

Our students select projects on their own that meet a few criteria. Projects that our students do well with (like yours) end up on a "go look at these first" list in subsequent semesters. We had never heard of Habitica prior to this semester, but we're glad to see our students making meaningful contributions. Email us if you want to talk offline, or have questions or feedback- thanks!

**Pull request merged**
