### PR TITLE
Mark todos and dailies as completed via api

### LINKED ISSUE #684: Suggestion: Provide 'Full API' access to mark tasks up and down.
Currently (at least according to the documentation) the only way to mark tasks as up/down is via the "extensions/scripts" API. This uses a different method of authentication, different path, and different calling method than the 'full' API.  The result is that clients (at least mine) have to implement the basics twice.

Proposed solution:

Add `/api/v1/user/task/:id/up` and `/api/v1/user/task/:id/down`. Since these are changing data, they should probably be POST requests, even though the body of the post is likely to be empty.

Ideally these return HP/XP/GP deltas as well as current HP/XP/GP, so clients can easily update their displays.  Any other info being returned is gravy. :)

(Also, if I _shouldn't_ tag my own tickets with API/suggestion tags, let me know!)

### PR DESCRIPTION
**Pull request by switz**
Fixes https://github.com/lefnire/habitrpg/issues/684

with specs!

(last PR was merging into master, sorry)

### CODE REVIEW

**Comment by pjf** [comment]
Huzzah! Have these hit the live servers yet? (If so, I may have to be double-checking code my end.)

**Comment by switz** [comment]
Not yet. Either I or @lefnire will update here when they're live.

**Comment by lefnire** [comment]
Give it a test, did it go live? Wanna make sure the cron update from git is
working properly, if not i'll do a manual pull

**Comment by switz** [comment]
Oh, it's live baby. (was live last night)

**Pull request merged**
