### PR TITLE
Allow including needsCron in userFields filter

### PR DESCRIPTION
**Pull request by tr4nt0r**
[//]: # (Note: See https://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes put_#_and_issue_number_here

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

needsCron is only returned if userFields is not set, but including needsCron in userFields was not possible. This allows to use userFields filters to explicitly include needsCron

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 4c4ca53f-c059-4ffa-966e-9d29dd405daf

### CODE REVIEW

**Comment by SabreCat** [comment]
Thanks for this, @tr4nt0r ! I've awarded you your first Blacksmith tier on the site. We'll do some testing in our internal staging environments, and you'll see this live soon.

**Comment by SabreCat** [comment]
Hi @tr4nt0r, during QA I'm seeing this, if I GET /user with `userFields=needsCron`:

```
2024-07-29T23:10:11.610198+00:00 app[web.1]: 2024-07-29T23:10:11.040Z - error TypeError: Cannot read properties of undefined (reading 'lvl')
2024-07-29T23:10:11.610211+00:00 app[web.1]:     at Function.addComputedStatsToUserJSONObj [as addComputedStatsToJSONObj] (/app/website/transpiled-babel/models/user/methods.js:288:62)
2024-07-29T23:10:11.610212+00:00 app[web.1]:     at Object.get (/app/website/transpiled-babel/libs/user/index.js:45:17)
2024-07-29T23:10:11.610213+00:00 app[web.1]:     at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
2024-07-29T23:10:11.610213+00:00 app[web.1]:     at async handler (/app/website/transpiled-babel/controllers/api-v3/user.js:87:5)
```

**Review by SabreCat — CHANGES_REQUESTED** [review]
functionality not working as intended?

**Comment by SabreCat** [comment]
Might help to write an integration test for this case as well!

**Comment by tr4nt0r** [comment]
Sorry, will try to do some more thorough testing. But as I don't have experience with nodejs this might take me some time..

**Comment by saraolson** [comment]
We're going to close due to inactivity. @tr4nt0r if you'd like to come back to this in the future, feel free to reopen with updates.

**Pull request closed without merging**
