### PR TITLE
Added meta image for social media sharing

### LINKED ISSUE #9192: Front page is missing Facebook (etc.) metadata
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found in Settings -> API)

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

We received a report in email that site metadata is empty for Habitica since the redesign, leading to social shares looking like this:

image

We should add back tags for the major platforms so shares of the site include relevant info! The reporting user provided this example code (we can use similar, but the image for one will need to be changed):

```
Sample Code:
<meta property="og:url" content="https://habitica.com" />
<meta property="og:type" content="website" />
<meta property="og:title" content="Habitica: Gamify Your Life" />
<meta property="og:description" content="Habitica is a free habit-building and productivity app that treats your real life like a game. With in-game rewards and a strong social network to inspire you, Habitica can help you achieve your goals." />
<meta property="og:image" content="http://habitica.com/your-image-path/image.png" />

Note: image should be 1200x630 for best results. More info here: https://www.h3xed.com/web-and-internet/how-to-use-og-image-meta-tag-facebook-reddit
```

### PR DESCRIPTION
**Pull request by theIsaacLim**
Fixes #9192

### Changes
[//]: # Added a meta tag image for social media sharing

[//]: #  013d3aaa-f9ff-406e-b4ee-2d04388b674c

----
UUID: 013d3aaa-f9ff-406e-b4ee-2d04388b674c

### CODE REVIEW

**Comment by theIsaacLim** [comment]
Whoo! First PR

**Comment by Alys** [comment]
Thank you! :) Can you edit the top post to put your Habitica User ID there so that acceptance of this PR would give you contributor credit? :) Also if you add the URL of the issue to the "Fixes" line then the issue will be automatically closed if this is merged, which is a nifty github trick!

**Comment by theIsaacLim** [comment]
Alright addded the UID

**Comment by theIsaacLim** [comment]
@Alys

**Comment by theIsaacLim** [comment]
@Alys  what's the problem with the checks? I am new to Gtihub and don't get what's going on here

**Comment by Alys** [comment]
The tests sometimes fail for reasons not connected to the new code (e.g., timeouts). I've restarted them.

Can you please edit the top post to put the URL of the issue in the "Fixes" line?

**Comment by theIsaacLim** [comment]
Just added the URL

**Comment by paglias** [comment]
Hi @theIsaacLim, the PR is looking good but there's a small issue, instead of linking the image from Github you should add it to `website/static/images` and use as link `https://habitica.com/static/image/IMAGE_NAME`

**Comment by theIsaacLim** [comment]
I think I've fixed the problem @paglias

**Comment by theIsaacLim** [comment]
Are there any more problems I have to fix @paglias ?

**Comment by theIsaacLim** [comment]
Any updates on this? Is there any real reason that this hasn't been pulled yet?

**Comment by paglias** [comment]
@thelsaacLim we usually review and merge PRs on Friday, so that's why you haven't heard anything from us :) will get to this one later today

**Comment by paglias** [comment]
@theIsaacLim thanks for this! I'm merging the PR and awarding your contributor tier.

Note that further tiers require increasing amounts of work from one to the next, so Tier 2 may require a couple of PRs or a larger PR to attain. But keep helping out and we'll express our gratitude accordingly!

**Pull request merged**
