### PR TITLE
Note about weekly progress update (fixes #6884)

### LINKED ISSUE #6884: Not receiving Weekly Progress Update
Hi all,

I haven't gotten a Weekly Progress Update in my inbox since January 21st. I was getting them weekly before that. I only noticed today because I needed to reset my longest streak and I use those emails as a reference for it. I checked my settings, and all of the boxes are still checked (except the Unsubscribe one, of course), including the weekly summary. The summary emails aren't in my spam folder, either.

User ID: d1b80ee0-2506-4f2d-b78a-e361d3929972

Thanks!

### PR DESCRIPTION
**Pull request by doyler**
Added a note about the weekly progress updates not currently sending (re: issue #6884).

Before - http://i.imgur.com/dLWIoxk.png

After - http://i.imgur.com/7fKhYs3.png

UserID - 98caa20c-b3ed-45a8-bd7a-a3e177549e46

### CODE REVIEW

**Comment by doyler** [comment]
The actual text if people don't want to view/can't view the screenshots:

Summaries of your account activity in the past week (Note: this is currently disabled due to performance issues, but we hope to have this back up and sending e-mails again soon!)

**Comment by Alys** [comment]
@lemoness Are you happy with that text?

**Comment by crookedneighbor** [comment]
Talked with @lemoness separately. She said the text was fine.

**Comment by crookedneighbor** [comment]
Tier awarded! You can read more about [contributor tiers and rewards here](http://habitrpg.wikia.com/wiki/Contributor_Rewards).

Note that as your tier increases, it takes progressively more work to achieve the next one, so for the higher tiers, larger PRs or a few PRs are required. There's some information about that at Contributor Rewards, but feel free to ask here if you have questions!

**Comment by marcooosd** [comment]
Will this summary email be coming back?

**Pull request merged**
