### PR TITLE
Gimp files for Iron, Red Robes and Rogue armor sets.

### PR DESCRIPTION
**Pull request by Orangyfresh**
Gimp .xcf files for Pandora. Contains Iron Armor (armor6_m.xcf) , Red Robes Armor (armor7_m.xcf) and Rogue Armor (armor8_m.xcf).

### CODE REVIEW

**Comment by StanLindsey** [comment]
Cheers! You guys rock.

**Comment by Pandoro** [comment]
Weird, I commented by mail but it never arrived :-/

This is looking good :+1:  :) 
I haven't tested it myself yet, but I will try to get it integrated into the system over the next few days!

Meanwhile you can checkout my latest commit. (See #343 ) The development.xcf might be useful when creating new stuff as it contains a BASIC model of the characters which your gear should checkout against. If there are still blank pixels, or weird overlaps there, there might be something wrong.

**Comment by Orangyfresh** [comment]
Ok, thanks. I was previously using the full.xcf file to check my art against, but this one is a lot more manageable and quicker to check.

**Comment by Pandoro** [comment]
Keep in mind it is not a fool proof check, but it should work out for the
biggest part :-)

**Pull request merged**
