### PR TITLE
Added previous state tracker and a filter for challenges by a guild if the user has clicked that guilds challenge link.

### PR DESCRIPTION
**Pull request by TheHollidayInn**
...he user has clicked that guilds challenge link.

This should address functionality described in https://github.com/HabitRPG/habitrpg/issues/4602 comment by deilann. 

I'm not sure if this is the best way to handle the functionality, since I have added quite a bit, but it seems to be working. 

Here is an issue detailing more about tracking the states in Angular: https://github.com/angular-ui/ui-router/issues/92 which is the technique I used.

### CODE REVIEW

**Comment by Alys** [comment]
Nifty! This is really quite convenient! 

Partial credit for tier 5. I'll talk to the staff and other admins about how close you are to tier 5 now.

**Comment by Alys** [comment]
Sorry @TheHollidayInn, I've had to temporarily revert this change because it was causing one of our automated tests to fail. I'm not sure why yet.

Reversion PR: https://github.com/HabitRPG/habitrpg/pull/4978

Failed test build: https://travis-ci.org/HabitRPG/habitrpg/builds/57240174

**Comment by Alys** [comment]
I think this has been superseded by https://github.com/HabitRPG/habitrpg/pull/3319 / https://github.com/HabitRPG/habitrpg/pull/4934 which shows only the challenge you've clicked on. That will go live in a couple of days, along with a lot of other challenge changes, so after that we'll see if this PR is still needed.

**Comment by TheHollidayInn** [comment]
@Alys  Sounds good. For future reference, is there a way to run my branch using the Travis CI build without submitting a new PR?

**Comment by gisikw** [comment]
@TheHollidayInn Absolutely - if you log into Travis, you should be able to click the "+" button here:

screenshot 2015-04-06 14 42 57

Once you add your forked repository, Travis will automatically run against any new branches/commits you push up to it :)

**Comment by TheHollidayInn** [comment]
@gisikw Perfect, thanks!

**Pull request merged**
