### PR TITLE
Make quest completion modal always display before quest invite modal

### LINKED ISSUE #5229: New quest modal pops up before notification of old quest completion
My party is extremely quest-happy as of late, and someone offered a new quest immediately after we defeated the previous boss, when I wasn't online. Due to the order of notification priority (I presume), the alert for a new quest invitation popped up before "You've defeated X boss!" modal. Once I accepted the new quest, the "You've defeated X boss!" modal was underneath. 

To minimize confusion, I propose the "You've defeated X boss!" modal take precedence over the new quest notification.

### PR DESCRIPTION
**Pull request by hairlessbear**
Fixes #5229. I haven't fully tested this yet, but it should work. As soon as I figure out how to trigger quest completion via mongodb, I'll know for sure.

### CODE REVIEW

**Comment by Alys** [comment]
See the debug menu in the footer. It has a +1000 (or something) boss damage button, and then a +1 missed day button (which triggers cron, after you next sync). 

Unless that boss damage button is something I wrote locally and never committed.....

**Comment by hairlessbear** [comment]
_sigh_ I keep forgetting about the debug menu. That definitely worked. Unfortunately, my code didn't. Back to the drawing board. But at least I can properly test now. Thanks @Alys :)

**Comment by crookedneighbor** [comment]
I see you adjusted the check. Was going to suggest that exact thing based on this line: https://github.com/HabitRPG/habitrpg/blob/develop/website/views/shared/modals/quests.jade#L12

Did it work?

**Comment by hairlessbear** [comment]
@crookedneighbor I thought it did, but not quite. It works in the exact use case it was designed for (i.e., a user logs in after their party has completed a quest AND started a new one), but now it doesn't work when a user is invited to a quest, but a different quest wasn't just completed. The problem is that `user.party.quest.completed` is set to `""` right after a quest is completed, but is `null` otherwise.

**Comment by hairlessbear** [comment]
Done! It now checks whether `user.party.quest.completed` is `""` OR `undefined`, covering both cases. I tested it with just an invite, and with a completed quest + invite, and it worked in both cases.

**Comment by hairlessbear** [comment]
Hmm, I just realized that if this gets merged, my non-descriptive overly-excited commit message might be an issue :confused: Sorry about that.

**Comment by crookedneighbor** [comment]
Since you feel strongly about it, if I'm the one to merge it in, I'll squash your 3 commits into a single commit. 

One thing I noticed is that while the quest completed modal does appear first now, it now requires a page refresh before the new quest invitation modal appears.

**Comment by hairlessbear** [comment]
Oh I don't mind everyone seeing how excited I got, but I thought the
undescriptive nature might be an issue for you guys. If the commit message
doesn't bug you, I have no problem with it being in the merge.

That's interesting that you're having that issue, because I expected it to
occur for me, but it didn't. As soon as I hit OK on the quest complete
modal, the quest invite popped up immediately.  Than again, I only tried it
once. I'll do some more testing when I get the chance.

**Comment by hairlessbear** [comment]
If the user is logging in, then the modals display properly, but if the user is already logged in and has HabitRPG open, a refresh is required (i.e., sync brings up the quest complete modal, but the quest invite modal won't show up until refresh). That's definitely a big problem; I'll see if I can fix it.

**Comment by crookedneighbor** [comment]
I'd also like to see some unit tests on the watch.

**Comment by hairlessbear** [comment]
I figured out what the problem is. When sync runs, `User.sync()` is the function that's run, which updates the `user.*` settings, but not the `party.*` settings (`user.party.quest.completed` and `party.quest.*` settings are needed for the logic I wrote to work). The `party.quest.*` values are either updated on refresh, or when `Fetch Recent Messages` is pushed, which runs `sync(group)` (which runs [this code](https://github.com/HabitRPG/habitrpg/blob/develop/website/public/js/controllers/groupsCtrl.js#L390), I think). 

This also means that once you're invited to a quest, regardless of whether there's a previous one completed, the modal won't show up until you either refresh the page, or hit `fetch recent messages`. That in itself is an issue, and I'd like to fix it by adding party sync to `User.sync()`. @crookedneighbor, does that sound like a good solution to you? I'm still figuring out how to get it to work, but I wanted to get your input sooner rather than later just in case you think this is a bad method.

**Comment by Alys** [comment]
See https://github.com/HabitRPG/habitrpg/issues/4235 regarding adding party sync to user sync. If it's done, it shouldn't be done in a way that makes user sync be even slower than it is. Remember that user sync happens every time you complete a task or a checklist item or take any other small action.

**Comment by hairlessbear** [comment]
The fact that user sync occurs so often is exactly why I want to attach the behavior to it. That would make it likely that the party invite modal pops up as soon as possible after the quest invite is sent. I'll see if I can figure out a method of adding party sync without adding a lot of overhead. 

This PR has become _much_ more complex than I anticipated. I thought I'd just need to add some conditional logic in a single location, but now I'm looking into increasingly complex parts of the codebase that I've never seen and barely understand. Funny how things work out :smile:

**Comment by hairlessbear** [comment]
@Alys @crookedneighbor is there any chance this could be merged as is? It improves the current behavior and doesn't add any downsides (that I know of at least). The issue of the quest invite modal not showing up until a refresh is one that existed before this code, and fixing it seems like a different PR to me.

**Comment by hairlessbear** [comment]
@crookedneighbor I forgot about your unit test requirement. Once the tests are written, could this be merged?

**Comment by hairlessbear** [comment]
Closed because behavior now contained in #5298

**Pull request closed without merging**
