### PR TITLE
Revert "Made incorrect username and password show the same error, for se...

### PR DESCRIPTION
**Pull request by denis-sokolov**
...curity purposes."

This reverts commit 8d03cfc6b59b82900badbc9b4397f079e11ee2e1.

The security of obscuring usernames on the login form is useless
when the registration form interface is not protected.

The usability disadvantage of not showing a proper error is real, however.

### CODE REVIEW

**Comment by deilann** [comment]
@denis-sokolov The Hall/Challenges doesn't reveal usernames-- it reveals display names.

I'm not sure why we need to revert this -- I don't know what you mean "not showing a proper error." An error shows up-- Your username or password is incorrect.

**Comment by denis-sokolov** [comment]
@deilann, good point, I did not know that. So forget the challenges and the hall part.

The reasoning behind 8d03cfc was to improve security by not disclosing the correctness of the username entered. I argue that this does not improve security whatsoever.
The registration functionality of HabitRPG is as vulnerable as the login form was. If an attacker wants to test usernames for validity, he can use the registration form.
(The forgot-password functionality is similarly vulnerable for the email test.)

Given that the commit provides no security benefit, I suggest reverting it, as it is obvious that it is much more user-friendly to provide a particular error message (`Wrong username` or `Wrong password`) versus a combined one (`Wrong something`).

**Comment by deilann** [comment]
It's not exactly that simple.

Yes, the attacker can use the registration form to test usernames for
validity, but can't cross reference them against passwords.

I completely disagree that it provides no security benefit at all, and
almost every site does not tell you if a password is wrong as opposed to a
username, for those exact reasons.

**Comment by denis-sokolov** [comment]
But as soon as the attacker has a method to test for validity of usernames (registration form), he can use the login form to cross reference them against passwords. I mean, seriously, how do you see the situation any different? I refer you to the [discussion on this topic at security.stackexchange.com](http://security.stackexchange.com/q/13079).

"Almost every site" also uses Facebook Like button, sticky headers and stupid infinite scrolling, doesn't mean it's right. :)

**Comment by deilann** [comment]
I think my suggestion is not to revert the commit, but to add a captcha to
registrations & confirm password. Just not one of the stupid captchas that
are hell for colorblind users or I still strangle someone. That would make
username farming through the registration difficult and would prevent batch
registration at the same time.

**Comment by deilann** [comment]
...which is exactly what's suggested over there.

**Comment by denis-sokolov** [comment]
That would be a positive improvement, but I am unfortunately unable to present it.
I have added a note to the relevant source code to remember to undo this when the signup form is secured.

Until then, this pull request provides with two benefits:
1. Minor usability improvement;
2. Security benefit by preventing a false sense of security, (for example, it seems, you have been lulled into it).

**Comment by deilann** [comment]
I don't generally merge things, so I'm gonna leave this to the folks who actually know what's up. o7

**Comment by denis-sokolov** [comment]
Sure. Thanks for a useful discussion! :)

**Comment by deilann** [comment]
@denis-sokolov Thoughts? https://github.com/HabitRPG/habitrpg/pull/2868

**Comment by denis-sokolov** [comment]
Sure, this covers it, then!

**Comment by deilann** [comment]
Thanks for pointing out the security flaw! :thumbsup:

**Pull request closed without merging**
