### PR TITLE
Shirts

### PR DESCRIPTION
**Pull request by AdrienLemaire**
# To do
- Fix code broken by 16337c6 (adding shirts in profile)
- Add purchase logic
- Readd from develop hide/show gears
## Related pull request

[habitrpg-shared/shirts](https://github.com/HabitRPG/habitrpg-shared/pull/52)

### CODE REVIEW

**Comment by AdrienLemaire** [comment]
I'm afraid I'll need some help to finish that feature.

**Comment by lefnire** [comment]
Hope to visit this week, I'll keep you posted

**Comment by AdrienLemaire** [comment]
shirts

**Comment by Pandoro** [comment]
Could you maybe post these with an actual skin sprite inside? I find it
super hard to judge these like this. In general I really like some of the,
others not so much. As lemoness mentioned, the shading is really missing a
bit in certain cases. But I really think there is some potential here.

**Comment by AdrienLemaire** [comment]
@Pandoro I'm working on the logic for the moment. You should be easily able to test shirts with skins using gimp (just open the skin, then add the shirts as layers), and feel free to do any changes on the shirts :)

**Comment by AdrienLemaire** [comment]
Example avatar after buying fire shirt.

avatar

**Comment by AdrienLemaire** [comment]
@lefnire I think this feature is good to go now, you can review and merge it.

Art might get revised in habitrpg-shared, but I'm a bit tired now, maybe will do that another day if nobody else beats me to it.

Please don't forget to give me some gems and the Artisan title, thanks :)

**Comment by lefnire** [comment]
Fantastic. I'm gonna review and merge either tomorrow or next, I have some new mechanics coming into play that might require I massage this feature, I'll ping you of any changes. Thanks man!

**Comment by AdrienLemaire** [comment]
no problem :)

**Comment by lemoness** [comment]
The ones that I think are most hurting for shading are the cross, the convict, and the rainbow, but before we merge these, I'd really like to see all of them with the uniform shading established in the originals. @Fandekasp, check out the base sample shirts that Alex made - they have very minimal shading, but it makes a big difference. It looks like the only one where you followed this was for the purple - but for some reason, you made the "shading" around the neck lighter than the shirt itself! Maybe reverse the two colors for the purple one, or just pick new ones. Alex, other thoughts?

**Comment by lefnire** [comment]
i'm gonna hold off on merging this till near the end, gotta so some massaging. more soon

**Comment by lefnire** [comment]
Thanks Adrien! Merged via above two commits. Will keep you posted on G+ once I have a classes test server running (next week)

**Comment by AdrienLemaire** [comment]
no problem @lefnire . But it would feel nice to get some gems and the Artisan/Pixelist badge (3rd time I ask for it ^^' )

**Comment by AdrienLemaire** [comment]
wow, +20 gems ! That's generous, thank you :)

**Comment by lefnire** [comment]
80 more!

**Pull request closed without merging**
