### PR TITLE
Added triumphTheme files - merged in https://github.com/HabitRPG/habitica/pull/9323

### PR DESCRIPTION
**Pull request by ghost**
### Changes
Added a new theme called Triumph.

### Notes
In 'Guidance for Bards' on the Wiki, it said to open website/views/shared/header/menu.jade. I was unable to locate this file, and edited no file to follow the given instructions.

Accio BooOOOooks gave the following instructions to Pizilden in the Aspiring Blacksmith's guild, which I ended up following:
1. Add music to website/static/audio/themeNameTheme
2. Add the line themeNameTheme into the array at line 49 of website/common/script/content/index.js (api.audioThemes = ...)

User ID: 0f428943-2414-443e-b719-d8be47b95359 

- I did the coding and created the theme.

### CODE REVIEW

**Comment by SabreCat** [comment]
Cool, thanks for this! Can you remove `package-lock.json` from the commit? That's more of a repo maintenance file, not relevant to this PR.

**Comment by ghost** [comment]
How do I remove the file from the commit?

**Comment by SabreCat** [comment]
@anastasiagaskamp Sorry, I said "commit" when I meant "PR", oops. But this series of commands should do it! With your branch checked out:

```
git checkout f2fed7e package-lock.json
git add package-lock.json
git commit
git push
```

The file will be modified on your first commit, but the new commit will revert it to be identical to the commit before you edited it, effectively taking it out of the pull request.

**Comment by ghost** [comment]
Okay, I did that.

**Comment by SabreCat** [comment]
Bah, that didn't work. And I tried a couple other ways to try to fix it cleanly, but no dice. I've created a new branch over at #9323 with the correct files, and will review and merge it from there!

**Pull request closed without merging**
