### PR TITLE
Optimizations

### PR DESCRIPTION
**Pull request by paglias**
This add:
- manage local js with connect-assets, I tried to use it also to manage habitrpg-shared.js but I wasn't able to, anyway we should give a look to it because it's not minimized together with some other script from `bower_components`
- remove lodash and moment, as discussed in #1414, before merge HabitRPG/habitrpg-shared#17

This time I've tested it and it works!

### CODE REVIEW

**Comment by lefnire** [comment]
Ah yes! I've been meaning to get around to connect-assets concat, thanks man!

**Comment by paglias** [comment]
I've not been able to use connect-assets for any vendor script even after moving `bower_components` outside of /public. Since it's working very well on mobile we could move everything client-side to `/public/` and use Grunt (with yeoman maybe). What do you think?

**Comment by lefnire** [comment]
Yeah,that's probably better since we'd be re-using the same efforts. I just did it this way to get up and running faster. Is there a method of running `grunt build` when production server is initially run, so we don't have to remember to build before pushes?

**Comment by paglias** [comment]
I think it's possible, create a shell script that check if NODE_ENV is production, if yes then run grunt build with minification and everything else, if it isn't well do nothing.

I can do this in the next days, it's ok pure grunt, no yeoman (i'll use more or less the same tasks anyway)?

**Comment by lefnire** [comment]
Yeah, we're not _really_ using yeoman on mobile anyway. We used it to
initialize the app, and it comes in handy for it's generators (quickly
generate new controllers, specs, etc). But we can nix it for web.

**Pull request merged**
