### PR TITLE
Sorted dated todos by date.

### PR DESCRIPTION
**Pull request by gisikw**
This tooltip was staring at me.

screenshot 2015-04-06 03 45 10

I stared back!

screenshot 2015-04-06 03 51 41

screenshot 2015-04-06 03 52 16

I think I won the staring contest.

### CODE REVIEW

**Comment by Alys** [comment]
DARNIT!  **_I**_ wrote that tooltip! SECONDS of my life wasted! 

Testing...

**Comment by gisikw** [comment]
:smiling_imp:

**Comment by Alys** [comment]
omg, looking at the code... It was THAT easy? :anguished: :confounded: :grimacing:

_Tiny_ credit towards tier 6. ;)

Thank you for this! It will make dated To-Dos much easier to use. I'm especially impressed because I have just started making heavy use of dates, so this is extra good! :)

**Comment by gisikw** [comment]
No worries - the orderBy syntax is a bit weird, and documentation is really hit-and-miss with angular. :)

**Comment by Alys** [comment]
@crookedneighbor is reverting this at my request (I'm not home to do it myself). https://github.com/HabitRPG/habitrpg/pull/4995/files
Sorry, @gisikw, I missed something in testing. When you delete a To-Do in the dated To-Dos column, the wrong To-Do is removed because the "array" index that the browser thinks is the correct one for the To-Do is different than the actual one on the server.

**Comment by gisikw** [comment]
ACK!!! So sorry, I didn't think of that >.< I'll revise over the next few days.

**Comment by Alys** [comment]
Don't let yourself worry about it. I missed it in testing. It's not an obvious bug to exist; the code should have be able to handle this situation.

**Pull request merged**
