### PR TITLE
Update maintenance.json for a "frenchier" version

### PR DESCRIPTION
**Pull request by remimarenco**
### edit by Alys: see comments below about suggested change to CONTRIBUTING.md

---
### Changes

Two minor fixes:
- Typo accent error
- Name inversion from english => french

---

UUID: 93374253-abfd-43ad-ba27-c420e66e259f

### CODE REVIEW

**Comment by crookedneighbor** [comment]
Translations are managed through Transifex. Please see the README https://github.com/HabitRPG/habitrpg/blob/develop/common/locales/README.md

**Comment by remimarenco** [comment]
Thanks!

**Comment by ghost** [comment]
@remimarenco hi! Thanks for your willingness to contribute! Come join [the guild](https://habitica.com/#/options/groups/guilds/7732f64c-33ee-4cce-873c-fc28f147a6f7) if you'd like to discuss translations with fellow contributors.

By the way, we also have more detailed instructions on the [Guidance for Linguists](http://habitica.wikia.com/wiki/Guidance_for_Linguists) on the Wiki. However it may be not an optimal place... Could you please give me a hint: where would you personally expect such instructions to be found?

**Comment by remimarenco** [comment]
Hi @GitHubSphinx!

Sure with pleasure :). I think a good place would be in [CONTRIBUTING.md](https://github.com/HabitRPG/habitrpg/blob/develop/.github/CONTRIBUTING.md), to simply add a:

> # Contributing Translation
> 
> See [Guidance for Linguists](http://habitica.wikia.com/wiki/Guidance_for_Linguists)

Because we (hopefully) read this when we are going to do the PR.

I can do the PR if you are ok with that :)

**Comment by Alys** [comment]
@remimarenco That's a good change to make, and you're welcome to do a PR for it. However, could you please hold off for a few days? We aren't currently read to accept submissions into the `develop` repository. When we are, I'll be updating [Guidance for Blacksmiths](http://habitica.wikia.com/wiki/Guidance_for_Blacksmiths) with information about how to update your local install (if you already have one - see the "API Changes" section) and updating [Setting up Habitica Locally](http://habitica.wikia.com/wiki/Setting_up_Habitica_Locally) with tips for a new install. I'll also remove the warning messages from the tops of those pages, and I'll post to the Aspiring Coders guild. When you see that, then a new PR would be welcome!

**Comment by remimarenco** [comment]
Sure! Just let me know :). Thanks for all these changes!

**Comment by Alys** [comment]
@remimarenco I've just posted to Aspiring Coders about how we're accepting PRs now, but see the notes in the wiki pages that I referred to in my post.

**Pull request closed without merging**
