### PR TITLE
Allocate stats on level

### LINKED ISSUE #10795: Allocate stat points from level up dialog
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: 6d7d6651-604d-4e7c-adff-a040770a6768

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
In an otherwise superbly designed application, it has always been a point of annoyance that it takes six clicks and three dialogs to allocate the stat point I've earned by leveling. 

I'm compulsive enough that I always want to assign stat points as soon as I've earned them _and_ am dissatisfied with the available auto-allocation schemes. As such, navigating to my stats overview by means of the notification menu always seems like a needlessly roundabout route. The app seems to ignore the obvious link between earning and expending the point. 

The most straightforward solution seems to be tacking the 'stat points' section of the stats overview to the level up dialog. You probably want to hide it for users that have auto-allocation turned on. Even people who only assign points once every few levels are going to appreciate the simplification, even if they aren't exactly clamoring for it right now. 

For a less intrusive option you could also consider adding a link to the stats overview at the bottom of the level up dialog. Personally, I feel the incorporated component is more elegant, but a shortcut would still be a significant improvement over the current set-up. 

I'd love to hear what you guys think. I don't mind taking a stab at implementing this myself, but obviously not without an expert opinion on what the finished product should look like. 

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

### PR DESCRIPTION
**Pull request by probaton**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #10795

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
I duplicated the stat allocation section of the stats overview page in the level up pop-up. 
levelupstatallocation
Step-by-step overview:
- Extracted stat allocation section into it's own component. 
- Externalized the functionality that commits the changes so that each parent component can implement a different save action. 
- Wired save functionality into the 'Onwards' button. 
- Made it so that the component is only displayed in the level up dialog if `autoAllocation === false`.
- Externalized most of the styling of the new component so that each parent can apply its own CSS. 
- Tweak/implement style sheets for both parents that use the new component.

Miscellaneous fixes/changes I made on the way:
- Rooted out `showAllocation`, which was passed as a parameter to `profileStats` to cover what seemed like a corner case to me. It's entirely possible I'm wrong though, in which case I'd be glad to reinstate it. 
- Removed a number of redundant `style`s and `div`s. 
- Replaced hard-coded hex colors with variables from `colors.scss` in every file I touched. 

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 6d7d6651-604d-4e7c-adff-a040770a6768

### CODE REVIEW

**Comment by paglias** [comment]
Thanks @probaton, pinging @Tressley for the design part

**Comment by paglias** [comment]
@probaton I'm marking this as `on hold` until the designers will have had time to give it a look!

**Comment by probaton** [comment]
Hope this is still on someone's backlog somewhere. After today I'll be off on holiday for the next week and a half, so if there's any feedback I might still be able to pick it up if it's not too drastic.

**Comment by paglias** [comment]
@probaton we discussed this internally and we like the idea but right now we're not ready to add a new feature right now, so we'll revisit it later after the username changes have been completed

**Comment by probaton** [comment]
Check. Sounds entirely reasonable. Let me know if and when you guys ever find the head-space and I'll be glad to take a stab at re-basing.

**Comment by probaton** [comment]
Is now a good time to give you guys a nudge to take a second look at this? This feature would definitely make me a happy little camper, especially since I started leveling like crazy after after respeccing back to mage. 

I rebased the branch, so it's up to date with `develop`. Surprisingly, the rebase was conflict free, although I'm afraid I wasn't able to re-test the changes as I can't seem to get my dev environment to work on my new laptop. `npm start` keeps borking, for some obscure reason. I posted some debugging info in a [google doc](https://docs.google.com/document/d/1YaYeG6m7texdtmtz2eeMXWYTR0TMyp55awk6VRlAv_c/edit?usp=sharing), in case someone here can spare a couple minutes to help out. If not, I'm sure someone in Aspiring Blacksmiths will get back to me sometime soon.

**Comment by probaton** [comment]
Fixed my dev build! ~~The new feature broke down somewhere along the line though, so you can leave this on hold until I patch things up. I'll let you know when I get everything up and running again.~~

I spoke too soon; I thought my feature was bugging out but apparently the level up debug button doesn't work exactly the way I'd expect it to. I clicked around for a while and everything seems to be working dandy! 

Hope you guys have a bit more breathing space to take a look around. As always, if there's anything I can do to accommodate you I'd be more happy to give it a shot.

**Comment by SabreCat** [comment]
Closing for now as this is definitely the sort of thing that we'd want UI design input on before diving into a PR implementation. We can revisit depending on how the evaluation of the source ticket shakes out!

**Pull request closed without merging**
