### PR TITLE
fix?

### PR DESCRIPTION
**Pull request by SabreCat**

### CODE REVIEW

**Comment by SabreCat** [comment]
Apologies for that. Trying to get my fork straightened out, and GitHub is fighting me every step of the way.

**Comment by lefnire** [comment]
Just a note - I'm merging your PRs on `develop`, which is the right way to go. Eventually I merge batches of battle-tested commits into `master` and push. Yours are non-code commits, so I'll do the merge sooner-than-later, but just in case you're wondering why nothing's showing on production.

If things aren't showing on beta, something's up in my deploy script

**Comment by SabreCat** [comment]
Gotcha. I'm actually planning to email you later to get clear on some of those best-practices (there doesn't seem to be a direct message function here or on the community forum), got a few related questions there.

This pull request was totally a flub, though. I'd meant to go the other way around, refreshing my stuff from yours, but the GitHub UI confused me. For the time being I deleted my repo and re-forked, and I think I have a better idea of the workflow now!

**Comment by SabreCat** [comment]
...and now it has become entirely impossible for me to set up pull requests from my fork. It doesn't show up as an option, as if it weren't even there. Frell me.

Time for me to learn my way around the Git bash console thing? This web UI is for the birds.

**Comment by lefnire** [comment]
naw, they're two separate worlds really. What I'd do is delete your fork, re-fork, delete your local branch, re-clone

**Comment by lefnire** [comment]
feel free to pop into IRC too if you have any questions, freenode #habitrpg . litenull, me (lefnire), and wizonesolutions are the barflies

**Comment by SabreCat** [comment]
Will do! Been ages since I've done anything on IRC.

For now I've got a clean pull request sent in via a fresh branch. Phew...

**Pull request closed without merging**
