### PR TITLE
WIP Emails unsubscription page

### PR DESCRIPTION
**Pull request by paglias**
Don't merge

### CODE REVIEW

**Comment by crookedneighbor** [comment]
Hmmm... Not sure what's causing the build to fail exactly, but I think it's freaking out about this line: https://github.com/HabitRPG/habitrpg/blob/develop/test/api.mocha.coffee#L100

**Comment by paglias** [comment]
Hmm... https://github.com/HabitRPG/habitrpg/commit/cb56b41c9407587d1c18e3fd255e25c6bd6331ec seems to have fixed it, probably it was something related to the `async` library but I'm really not sure about the use of `this`...

**Comment by crookedneighbor** [comment]
Yeah, this is beyond my expertise...

**Comment by paglias** [comment]
@lefnire what do you think of this change? https://github.com/HabitRPG/habitrpg/pull/4968/files#diff-201c48882b4ce1170c68802c6b3c53ffR115 I'm not sure about passing `this` as a context but `null` would make it use the global context and I read that using `this` is the like a normal call so I hope it's ok

**Comment by gisikw** [comment]
@paglias If you need to bind `this` to an isolated context, you can use `cb.apply({},args)`

**Comment by paglias** [comment]
@gisikw I'm just unsure about the arguments that are being passed so i would like to use `apply` that adapts well to this situation. I'm just unsure about the context to pass, it should work like if we were doing `user.save(cb)`

**Comment by gisikw** [comment]
Oh! Then you want `cb.apply(cb, args)` I believe. That's effectively the same as `cb(arg1, arg2, ...)`, as you're passing the original `this` as the rebound `this`.

**Comment by paglias** [comment]
@gisikw that makes sense and the build is passing, thank you

**Comment by paglias** [comment]
@lefnire had to revert the password resets part because of problems with Mandrill, so we'll stick to nodemailer for it.

I'm merging and deploying, if you notice any problems with emails, ping me!

**Pull request merged**
