### PR TITLE
Grunt v2

### PR DESCRIPTION
**Pull request by paglias**
This is an update of the Grunt workflow that should solve some problems.
- Remove shell script
- Use nodemon for restarting the server, grunt-contrib-watch for compiling stylus files
- Update README.md (please check for english!)

Locally just run `grunt run:dev` to have the server restarting automatically & stylus files to be compiled when they change.

In production, I leave this to @lefnire but I don't think that running grunt-contrib-watch to recompile stylus & js is anything useful on Heroku since the app is restarted when new code is pushed. I understand using `nodemon` in case the server crash to restart it.

So I would advise using this command on Heroku:

`grunt build:prod && grunt nodemon` so that the assets are built only once but the server restarts in case it crashed.

### CODE REVIEW

**Comment by lefnire** [comment]
Yeah, we don't want grunt-contrib-watch on prod - and actually, I don't think nodemon is our guy for crashed server either; I think we'll want [forever](https://github.com/nodejitsu/forever) (which is what we were using for Grey, but I've forgotten to add to White). nodemon is really just for devving.

So in otherwords - this is perfect :)

**Comment by lefnire** [comment]
beta.habit, works like a charm. I'll merge this stuff into prod now

**Comment by lefnire** [comment]
`102 requests  ❘  907 KB transferred  ❘  10.06 s (load: 6.97 s, DOMContentLoaded: 952 ms)`

That used to be 3.5 MB I my end, you've gotten it down to 907 KB!! What a difference!

**Comment by paglias** [comment]
cool! but 102 requests and 10.06s? wow that's a lot....

**Pull request merged**
