### PR TITLE
Added Vagrant for unified, portable dev environment

### PR DESCRIPTION
**Pull request by thepeopleseason**
Created a vagrant file and some supporting documentation. I've gotten `npm start`/`grunt run:dev` up and running, and I'm hoping I can pass the baton off to folks with more experience in the actual HabitRPG code. 

I've uploaded the vagrant box to my dropbox, which totals about 745MB. Ideally, we'd host the file elsewhere.

### CODE REVIEW

**Comment by paglias** [comment]
what is the advantage of using vagrant for habitrpg?

**Comment by thepeopleseason** [comment]
@paglias It's a unified development environment: Right now, the process of setting up HabitRPG locally is: 
1. Install MongoDB. If on Windows, do extra Mongo setup
2. Install Node
3. Install Git (if necessary) 
4. Fork and Clone Git Repo
5. Install Grunt
6. Install Bower
7. Update Configs
8. Seed Mongo
9. Run via npm or grunt. 

With Vagrant these instructions become: 
1. Install Git (if necessary)
2. Fork and Clone Git Repo
3. Download vagrant virtual machine image
4. Start up vagrant vm
5. Update Configs.
6. Run via npm or grunt.

It's running on an ubuntu vm, so extra Windows setup isn't necessary, and any issues/discrepancies in developers' local environments are eliminated.

**Comment by lefnire** [comment]
Oh, super bad ass! @SabreCat @wizonesolutions - I know you two were looking into this, how does this look? Since it's non-destructive I'm gonna go ahead and merge, let @thepeopleseason if there's any additions you'd like to see

**Comment by wizonesolutions** [comment]
@lefnire @thepeopleseason Awesome start! This can become even simpler; use the `box_url` configuration parameter and you can skip the download step. Implement provisioning and you can eliminate steps 5 and 6. A simple shell script might be good enough for provisioning to start if you already know the commands.

Update: Worth mentioning that provisioning would be REALLY trivial since you already have a box image. You just update configs and run npm/grunt with a shell script. Updating configs I realize might need to be a manual process, so maybe that step can't be eliminated. But if you can automate it with some sane defaults (e.g. turn off stuff that doesn't make sense in dev) then you could just provide instructions for edge cases.

**Comment by thepeopleseason** [comment]
@wizonesolutions I had a provisioning script initially with the full "Setting up HabitRPG locally" details in it, but then opted to package that box up into a new box. I'll update. 

Update: I have a feeling that Dropbox is throttling any downloads of the vm that I created, so I think alternate hosting for the file is in order.

**Comment by thepeopleseason** [comment]
@wizonesolutions: I've got a basic provisioning script down, but when I try to run `npm start &` via the script, it seizes control of `vagrant up` and never returns to the user. This is likely because I am crap at bash scripting, but it occurs to me that some developers may not wish to start the HabitRPG system as a whole whenever they invoke vagrant (I, for one, am interested in contributing to unit tests). Thoughts? 

Here's the provisioning script: 
https://gist.github.com/thepeopleseason/9457078

Updated branch:
https://github.com/thepeopleseason/habitrpg/tree/vagrant-setup

**Comment by paglias** [comment]
@thepeopleseason let's say I'm already using Ubuntu and have everything set up and working, willI have to use vagrant anyway?

Or, for new devs already on Ubuntu the default would be to use Vagrant?

**Comment by wizonesolutions** [comment]
@thepeopleseason Hmm, I'd say that's your call. As for `npm start` seizing, that is hard to say. I encountered that problem with Ruby, and I think the solution had something to do with how I wrote output to the terminal. Sometimes it was really subtle. I'd say skip it for now if it's a pain.

**Comment by thepeopleseason** [comment]
@paglias: Anyone who has their development environment already set up can continue using it, and anyone on Ubuntu can set it up locally. The vagrant virtual machine just makes it easy for anyone new coming in to get HabitRPG up and running without the overhead of getting all of the items downloaded, installed, and configured. 

@wizonesolutions: I'm going to opt to not run the system via the provisioning script. I'll keep the script in the repo, however, and update the docs to indicate that the possibility is there to automatically start the system.

**Pull request merged**
