### PR TITLE
Overhauled automatic attribute allocation logic

### PR DESCRIPTION
**Pull request by SabreCat**
I spent all day trying to get a backfill button to work, but while the logic seems to be working OK--the numbers fill in just fine--I'm not getting it to pass the right data to and from the server to get it to stick. So for now I'm submitting this PR, which at least gets the process working at levelup time. Synopsis:
- The "Automatic Allocation" preference now has three user-preference modes: `flat`, `classbased`, and `taskbased`.
- `flat`, or "Distribute attribute points evenly", will assign a levelup point to the attribute with the fewest points assigned to it so far, breaking ties INT > PER > STR > CON.
- `classbased`, or "Distribute attribute points based on Class", is the "3:2:1:1" setup discussed [here](https://github.com/HabitRPG/habitrpg/issues/2063), though it does favor class attributes first rather than following the "build the foundation" approach suggested there. The algorithm works by establishing what an "ideal" character build would look like at the player's level, if their class's primary attribute got 3 points per 7 levels, secondary got 2, and the others got 1. It then assigns the levelup point to the attribute furthest behind par according to that scheme.
- `taskbased`, or "Distribute attribute points based on task activity", is an overhaul of the current Automatic Allocation logic. Instead of tallying the user's task values at time of levelup and assigning an attribute point based on the biggest value (including, I suspect though have not confirmed, a bug where it counts Rewards as STR value), the user accumulates "training" points for each attribute behind the scenes as they act on tasks. It uses the same `delta` formula that scoring does, adding the new delta for a task into the `training` variable corresponding to the task's attribute. Then at levelup time, it finds the most-trained attribute that level, assigns it a point, and zeroes out the training.
- Misc: Added a debug button to give the user a single level's worth of Experience. You can probably guess how that was useful during this development. :smile_cat: 

I think the task-based allocation holds the greatest promise for real-life motivation: if you want to beef up your character's Intelligence, you need to do well on your Mental tasks. If you instead end up doing best on your exercise and wellness goals, your character will reflect that, growing in Strength. (At present, even discounting the Rewards bug, you can end up scoring points in an area you haven't touched, because the value of neglected Dailies and To-Dos increases over time while oft-hit positive Habits become less valuable.) The other two options are best for users who don't want to deal with assigning attributes to their tasks, but want a well-rounded character (`flat`) or one who will excel at class abilities (`classbased`).

Still to do:
- Implement a "Distribute points now" button that will backfill any accrued attribute points according to the selected auto-allocation scheme. I made a valiant attempt at this, but couldn't get it done in time.
- Issue #2098: for task-based auto-allocation, provide feedback to the user on how they're doing over the course of the level. Show them what attribute is likely to level up when they next fill their XP bar, so they can adjust their focus accordingly.

### CODE REVIEW

**Comment by jimcullenaus** [comment]
OK, so I don't know if this is the most appropriate place to suggest this, but wouldn't it be better if the taskbased distribution used a slightly more intelligent proportional system for the allocation? Instead of just going on the skill used most at that level, it would attempt to get your allocated stats as close as possible to your long term usage of each skill — kinda like how the MMP voting system works.

I've got a quick script I could share that shows how this could be done if anyone's interested.

**Comment by SabreCat** [comment]
@jimcullenaus: Hmm! It's an idea... I like having each level be a fresh start, though. That way you have less inertia to overcome when changing direction.

I'd still be interested in seeing the script, in any case!

**Comment by jimcullenaus** [comment]
@SabreCat the reason I'd rather it held over is I know for me, it'll nearly always be a single attribute, _maybe_ having a second that comes in every now and then. I imagine that that is true for many people. It could be an extra option, perhaps.

I'd love to share the script, but I'm not sure how exactly. Would pastebin be the best way?

You know what. Here it is. I'm not a very strong coder, and there are definitely some bits in here where I know it's not done as well as it could be. The way it's set up currently is for a user to interact with it and manually enter how much they've trained each of the attributes. The values in the dictionary with the key "social", "physical" etc. seem to be the same kind of thing as the "training" mentioned in the initial post. The "int", "str" etc. values are the number of points currently allocated to each of the stats, and "points" is the number of unallocated points.
http://pastebin.com/dNCHKdq4

**Comment by SabreCat** [comment]
@jimcullenaus Perhaps a [gist](https://gist.github.com/)?

**Comment by SabreCat** [comment]
Oh, whoops, you went ahead with Pastebin--I came from an email notification and didn't see you'd updated. I'll have a look!

**Pull request merged**
