### PR TITLE
Ensured leader doesn't change with group plans

### LINKED ISSUE #10474: leader changed in guild with an active group plan
oakfernmama (0917fecb-cce2-4204-94be-c03f0a53f07c) reported: "I just signed up for the Group feature... somehow without my OK, the system changed my son to the group leader. I can't assign him tasks, nor can I change the group leader. Is there a way to fix this - and prevent the behavior in the future?"

I confirmed that they did pay for the group subscription (this is from our records in Slack):
```
oakfernmama 0917fecb-cce2-4204-94be-c03f0a53f07c xxx@xxx.xxx bought a 1-month recurring group-plan for 6ee57108-c276-478c-865d-0eacde01146d using [payment method] on Sat Jun 23 2018 21:03:58 GMT+0000 (UTC)
oakfernmama 0917fecb-cce2-4204-94be-c03f0a53f07c xxx@xxx.xxx bought a 0-month recurring subscription using Group Plan on Sat Jun 23 2018 21:03:58 GMT+0000 (UTC)
[other guild member] 0971bf46-ae4a-4fa2-890d-06f9e03d5d36 yyy@yyy.yyy bought a 0-month recurring subscription using Group Plan on Sat Jun 23 2018 21:05:36 GMT+0000 (UTC)
```

Here's the current guild data (irrelevant parts removed):
```
{
    "_id": "6ee57108-c276-478c-865d-0eacde01146d",
    "purchased": {
        "plan": {
            "consecutive": { },
            "quantity": 3,
            "extraMonths": 0,
            "gemsBought": 0,
            "mysteryItems": [],
            "customerId": ".........",
            "dateCreated": "2018-06-23T21:03:57.760Z",
            "dateTerminated": null,
            "dateUpdated": "2018-06-23T21:03:57.760Z",
            "owner": "0917fecb-cce2-4204-94be-c03f0a53f07c",
            "paymentMethod": ".......",
            "planId": "group_monthly"
        }
    },
    "memberCount": 3,
    "balance": 0,
    "type": "guild",
    "name": "...",
    "managers": {},
    "categories": [],
    "leader": "0971bf46-ae4a-4fa2-890d-06f9e03d5d36",
}
```

It's not supposed to be possible for a guild leader to be changed in any way (or for the guild leader to leave the guild) while the guild  has an active group plan.

Note that `memberCount` is 3 but it should be 2 (I've checked and there's only 2 members) so that's likely related.

I've asked oakfernmama for more information such as whether any error messages were seen or any guild leave/join events occurred. (Based on the timestamps in Slack, we already know that the son was invited to the guild after the group plan was created.) 

I can't find anything obviously relevant in Amplitude or Loggly. It wouldn't hurt for someone else to check in case I missed something.

I'm marking this as important priority, at least until we know what caused it and whether it's likely to happen again for this or other groups.

I'm about to change the guild leader back to oakfernmama.

### PR DESCRIPTION
**Pull request by TheHollidayInn**
Fixes #10474

This will fix for group plans, but we should review this for other groups as well.

### CODE REVIEW

**Comment by paglias** [comment]
Does this need some changes or it's ready?

**Comment by Alys** [comment]
IMO it's worth pushing as a temporary hot fix to prod until the memberCount problem is fixed.

**Comment by TheHollidayInn** [comment]
Agreed

**Comment by paglias** [comment]
Merging in release

**Pull request merged**
