### PR TITLE
Adds Dutch Translations.

### PR DESCRIPTION
**Pull request by jbnicolai**
These are a rudimentary first pass, as according to
https://github.com/lefnire/habitrpg/wiki/Translations the localization
implementation is still in a state of flux. Hopefully these can serve
a temporary use in the meanwhile.

### CODE REVIEW

**Comment by ghost** [comment]
If/when I have time I'll check these out and see if I can find anything to improve.

**Comment by switz** [comment]
I merged this manually. Thank you so much!

**Comment by ghost** [comment]
I also added a pull requests on his branch with some changes might want to
check those out too. Should I add a pull request here?

**Comment by switz** [comment]
which pull request are you talking about?

**Comment by ghost** [comment]
This one https://github.com/jbnicolai/habitrpg/pull/1

**Comment by switz** [comment]
No need, I merged it in. Thanks! In the future, please open them against `lefnire/habitrpg`.

**Comment by ghost** [comment]
Well the issue was it was on top of his changes but considering the author
stays preserved not a big deal if I put the pull request here

**Comment by switz** [comment]
Since yours is based off of his, it should have included his changes. All he would have to do is sync back up with upstream and everyone is good to go.  

If this didn't happen, let me know and we'll get it sorted out.

**Comment by jbnicolai** [comment]
Ah, my apologies, @xeross his pull request went completely unnoticed. I will synch back with upstream and all will be good.

**Comment by StanLindsey** [comment]
The latest template is updated on at on the develop branch by the by. There is many more keys added that would be great to have translated. 

[Take a Gander Here](https://github.com/lefnire/habitrpg/blob/develop/locales/en/app.json)

**Comment by Noeska** [comment]
Hi guys. I'm new to GitHub, but tried to help by translating everything that was in the current translations branch to Dutch using the existing stuff as a reference. I hope I did this right and if not, please let me know so I can do better in the future. Here's my contribution: https://github.com/lefnire/habitrpg/pull/1111

**Pull request closed without merging**
