### PR TITLE
Add Completion Text to Older Quests #10066

### LINKED ISSUE #10066: Add Completion Text to Older Quests
Some of the older quest-lines lacked completion text, with their endings instead chaining into the beginning of the following quest. I've gone through and written some short completion text sentences for those quests. In some cases, the main quest text also needs some small edits.

The following changes should be made:

atom1 (Attack of the Mundane, Part 1: Dish Disaster!)

Completion Text: After some thorough scrubbing, all the dishes are stacked safely on the shore! You stand back and proudly survey your hard work.

atom2 (Attack of the Mundane, Part 2: The SnackLess Monster)

Completion Text: With a deafening cry, and five delicious types of cheese bursting from its mouth, the Snackless Monster falls to pieces. Well done, brave adventurer! But wait... is there something else wrong with the lake?

The beginning of atom3 (Attack of the Mundane, Part 3: the Laundromancer) should then be changed to the following:

Just when you thought that your trials had ended, Washed-Up Lake begins to froth violently. “HOW DARE YOU!” booms a voice from beneath the water's surface. (The rest of the quest text continues normally from there.)

vice1 (Vice, Part 1: Free Yourself of the Dragon's Influence)

Completion Text: "With Vice's influence over you dispelled, you feel a surge of strength you didn't know you had return to you. Congratulations! But a more frightening foe awaits..."

The beginning of vice2 (Vice, Part 2: Find the Lair of the Wyrm) should then be changed to the following:

Confident in yourselves and your ability to withstand the influence of Vice the Shadow Wyrm, your Party makes its way to Mt. Habitica. (The rest of the quest text continues normally from there.)

Completion Text: 

As you lift the final crystal aloft, the shadows are dispelled, and your path forward is clear. With a quickening heart, you step forward into the cavern.

goldenknight1 (The Golden Knight, Part 1: A Stern Talking-To)

Completion text: Look at all these testimonies! Surely this will be enough to convince the Golden Knight. Now all you need to do is find her.

goldenknight2 (The Golden Knight, Part 2: Gold Knight)

Completion text: The Golden Knight lowers her Morningstar in consternation. “I apologize for my rash outburst,” she says. “The truth is, it’s painful to think that I’ve been inadvertently hurting others, and it made me lash out in defense… but perhaps I can still apologize?”  

moonstone1 (Recidivate, Part 1: The Moonstone Chain)

Completion text: At last, you manage to pull the final moonstone from the swampy sludge. It’s time to go fashion your collection into a weapon that can finally defeat Recidivate!

moonstone2 (Recidivate, Part 2: Recidivate the Necromancer)

Completion text: Recidivate staggers backwards under your final blow, and for a moment, your heart brightens – but then she throws back her head and lets out a horrible laugh. What’s happening?

Beginning of moonstone3 (Recidivate, Part 3: Necro-Vice)

Laughing wickedly, Recidivate crumples to the ground, and you strike at her again with the moonstone chain. (The rest of the quest continues normally from here.)

### PR DESCRIPTION
**Pull request by EthanEFung**
Adding Translatable Strings

Fixes  #10066

### Changes
Added Completion strings in /website/common/locales/en folder
And added completion attributes to multiple quests in the quests map -> /websit/common/script/content/quests.js

Completion content was created for:
(1) Vice1
(2) Vice2
(3) Moonstone1
(4) Moonstone2
(5) Goldenknight1
(6) Goldenknight2
(7) Atom1
(8) Atom2

Edited notes for:
(1) Vice2
(2) Moonstone3
(3) Atom3

----
UUID: 5892b9b6-8775-474b-ad0c-9d72f7fc24b6

### CODE REVIEW

**Comment by EthanEFung** [comment]
Hi @paglias , just curious to see if there is something I need to do in order to have this ready for merge

**Comment by paglias** [comment]
Hi @EthanEFung, sorry for the delay but the team is a bit busy this week so it might have to wait until next week, but we'll get to it :)

**Comment by EthanEFung** [comment]
@paglias no rush! Just eager to help.

**Comment by EthanEFung** [comment]
@Alys , having a little trouble with the ticket I was working on #10069. It seemed to merge with this Issue, because I wrote them both on the same branch. Do you know how I can separate these tickets from this point?

**Comment by paglias** [comment]
@EthanEFung  thanks for this! I'm merging the PR and awarding your contributor tier.

Note that further tiers require increasing amounts of work from one to the next, so Tier 2 may require a couple of PRs or a larger PR to attain. But keep helping out and we'll express our gratitude accordingly!

**Comment by EthanEFung** [comment]
@paglias - Thanks for this! I'm glad and excited to be helping!

**Pull request merged**
