### PR TITLE
start japanese translations

### PR DESCRIPTION
**Pull request by AdrienLemaire**
Start japanese translations

### CODE REVIEW

**Comment by AdrienLemaire** [comment]
My UID for the translator achievement: 84497c76-4028-4dd5-8403-69b4f5b12575  :)

**Comment by lefnire** [comment]
You're coming in strong Adrien! Thanks so much for all the PRs, absolutely fantastic. We'll hit translations in next few weeks, will let you know soon

**Comment by AdrienLemaire** [comment]
yes, I saw your message in the tavern. I'll improve the translations by next week, but we'll need someone else to review and translate the hardest parts, I'm far from fluent :)

**Comment by nafoster** [comment]
I am in no way fluent, but I would be willing to help.

**Comment by AdrienLemaire** [comment]
Feel free to fork my branch and pull request there then :) Thanks

**Comment by nafoster** [comment]
I'm still relatively new at using Git/GitHub, so once I figure out how to fork your branch, I will!

**Comment by AdrienLemaire** [comment]
might want to read that: https://help.github.com/articles/using-pull-requests :)

**Comment by nafoster** [comment]
It is very late here, so it might just be my tiredness, but I'm not sure if I understand what I need to do. I will re-read it in the morning.

おやすみなさい！

**Comment by lefnire** [comment]
Fantastic! Adrien, what's your UUID again?

**Comment by AdrienLemaire** [comment]
Thanks @lefnire :)
I gave my uuid at the beginning of this thread. Here it is: 84497c76-4028-4dd5-8403-69b4f5b12575

**Pull request merged**
