### PR TITLE
Added trasnparent class to seasonal items already owned

### PR DESCRIPTION
**Pull request by crookedneighbor**
Added transparent class to gear that has already been purchased in the seasonal shop:

screen shot 2014-12-25 at 9 32 48 pm

### CODE REVIEW

**Comment by crookedneighbor** [comment]
@SabreCat Does this look good to you?

My first approach was to hide the items if purchased, but then the logic became complicated to also hide the labels, and it looked messy to leave the labels with no items, so I settled for this. I like being able to tell, at a glance, what gear I've already purchased.

**Comment by SabreCat** [comment]
Cool! CC @Alys, she had a similar suggestion.

**Comment by lemoness** [comment]
I like this a lot - does it also apply if you already have this equipment
from last year's event?

**Comment by crookedneighbor** [comment]
@lemoness It does. It just checks if the user has it already.

Going to merge this in. If anyone wants to do something different, should be easily reversible.

**Pull request merged**
