### PR TITLE
Change Menu Names 

### PR DESCRIPTION
**Pull request by nrbunn**
Changed menu names based off requirements of  #6783

### CODE REVIEW

**Comment by Alys** [comment]
Thank you, @Sinble! What's your User ID from Settings > API?

**Comment by nrbunn** [comment]
25479d8c-45e1-482c-877e-6af2ccaba643

**Comment by Alys** [comment]
Tier awarded! Congratulations! :)

Note that the higher tiers require more effort than the lower ones, so if you make any small changes from now on, you might find that they won't grant you an extra tier immediately, but they will be noted as partial credit towards a tier. There's a bit of information about that at [Contributor Rewards](http://habitrpg.wikia.com/wiki/Contributor_Rewards) but do ask if you have questions.

**Comment by taldin** [comment]
Grats on your new tier!  :D

**Pull request merged**
