### PR TITLE
Allow admins to edit challenge tasks - fixes #8149

### LINKED ISSUE #8149: moderators can't edit challenge tasks
This issue relates to editing the tasks belonging to a challenge itself (i.e., in the challenge's own page under Social > Challenge). It does not relate to editing any copies of challenge tasks that are added to any player's own list when the player joins a challenge.

Moderators must be able to edit a challenge to change or add or delete any of the challenge's tasks, in the same way that the owner of the challenge can.

Currently, moderators can't do this - they receive the error "Tasks belonging to a challenge can only be edited by the leader."

A moderator is defined as anyone with `contributor.admin` set to true.

An easy way to find the code that needs to be changed for this is to search for `onlyChalLeaderEditTasks`. You'll find code like this:
https://github.com/HabitRPG/habitica/blob/1eb1fe76a8917cf5cd67d317fb91f577e7470d51/website/server/controllers/api-v3/tasks.js#L1344

Instead of using a leader ID check, the `canModify` method could be used:
https://github.com/HabitRPG/habitica/blob/1eb1fe76a8917cf5cd67d317fb91f577e7470d51/website/server/models/challenge.js#L75-L77

Note there's no need to change the `onlyChalLeaderEditTasks` string to make it say that mods can edit too. It's best to leave it as it is now for simplicity. Mods don't edit challenge tasks often enough for it to matter that the message is a little inaccurate and we'd typically inform the challenge owner that we've done it.

_FYI for anyone curious: Moderators occasionally need to edit challenges if the challenge owner has put a swear word or other inappropriate content into one of the challenge's tasks, or under other rare special circumstances. Under normal circumstances, they do not edit other player's challenges._

### PR DESCRIPTION
**Pull request by flhat**
Fixes #8149

### Changes
- Rather than checking if the user is the owner of the challenge, check canModify(user) instead

----
UUID: 495eed5c-2828-4e24-a19d-755ac5e95295

### CODE REVIEW

**Comment by paglias** [comment]
@BlkStormy the code is looking good, can you add a test for this functionality? One test per route will be enough. Let me know if you need help about writing tests

**Comment by flhat** [comment]
@paglias Thanks - yes, can you help me figure out how to write a test for this?  I'm new to writing tests for this codebase.  I read the instructions on the wiki, but perhaps I could see an example to start with?

**Comment by paglias** [comment]
@BlkStormy sure, taking `api.createChallengeTasks` as an example, but it's more or less the same with the other routes, the integration tests for that route can be found here https://github.com/HabitRPG/habitica/blob/develop/test/api/v3/integration/tasks/challenges/POST-tasks_challenge_id.test.js

as you can see there's a test https://github.com/HabitRPG/habitica/blob/develop/test/api/v3/integration/tasks/challenges/POST-tasks_challenge_id.test.js#L42 to check that a leader can add tasks even if not a member, you want to add a new test that checks the same thing but for an user with admin properties. So you should create a new user with the properties `contributor.admin` set to true and use that user to check for the same thing:

Something like this

```
  it('allows admin to add tasks to a challenge when not a member', async () => {
    const admin = await generateUser({'contributor.admin': true});
    let task = await admin.post(`/tasks/challenge/${challenge._id}`, {
      text: 'test habit',
      type: 'habit',
      up: false,
      down: true,
      notes: 1976,
    });

    let {tasksOrder} =  await admin.get(`/challenges/${challenge._id}`);

    expect(tasksOrder.habits).to.include(task.id);
  });
```

**Comment by paglias** [comment]
Any update on this one?

**Comment by Alys** [comment]
I've written a test for this and I'm pushing it to the moderators-edit-challenge-tasks branch on BlkStormy/habitica to update this PR, but the push is running very slowly. I'm going to leave it to do its thing and go to bed. I'll check on it tomorrow. If it turns out I've messed up the PR, I'll fix it tomorrow or on the weekend. 
@BlkStormy Git's version control means that your work can't be lost so don't worry if things seem to go a bit wonky for now. :)

**Comment by Alys** [comment]
Right, so that's every commit ever added to this PR. :roll_eyes: Sorry. I shouldn't have made a new branch based on `develop` and merged in this PR. Let me see if I can fix this. If I can't, I'll make a new PR with @BlkStormy's edits and my test, and I'll link it back to this one so @BlkStormy's credit is clear.

**Comment by Alys** [comment]
That's all fixed and pretty now. :) Tests are passing, including the new one. It's ready for review again.

I have not tested this manually on a local install because I'm guessing it was tested manually during the previous review, but if it wasn't, let me know and I'll test it.

**Comment by paglias** [comment]
merged! thanks @Alys and @BlkStormy ! @BlkStormy this has been added to your list of contributions

**Pull request merged**
