### PR TITLE
Fix for sending chat with ctrl enter for windows chrome/firefox. Fixes https://github.com/HabitRPG/habitica/issues/9380

### LINKED ISSUE #9380: Can't send message with Ctrl-Enter on Windows/Chrome
We've received reports that some users using Windows/Chrome cannot automatically send messages using Ctrl-Enter. Sending messages using Cmd-Enter appears to work on Macs, at least in Safari.

### PR DESCRIPTION
**Pull request by Feywood**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes https://github.com/HabitRPG/habitica/issues/9380

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
Added a keyup event in the tavern and group vue files, tacked it onto the textarea.
Event listens for ctrl.enter and sends the sendMessage, same as with the send button click

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 9c4776eb-7330-465b-85cc-e4ccef6c1ad1

### CODE REVIEW

**Comment by negue** [comment]
`keyup.ctrl.enter` works even on mac 😋 .

@Feywood could you remove obsolete check inside `_updateCarretPosition` ? (because your fix is fired before)

**Comment by Feywood** [comment]
@negue I'm assuming this is what you meant :crossed_fingers:

**Comment by negue** [comment]
yes, thank you :)

**Comment by negue** [comment]
could you fix the lint issues ? https://travis-ci.org/HabitRPG/habitica/jobs/311410427#L903   after that this PR is ready to merge

**Comment by Feywood** [comment]
Should be good now.
It's certainly been a learning experience :sweat_smile:

**Comment by negue** [comment]
hehe, you did well :+1:

**Comment by SabreCat** [comment]
Thank you for this, @Feywood, and welcome to contributor tier 2! We'll use this in a staging environment for a bit, but you should see it live in a few days.

**Pull request merged**
