### PR TITLE
Only notify if pushedItems isn't empty - fixes #10496

### LINKED ISSUE #10496: Newly subscribed accounts receive erroneous notification that they have Mystery Items
If an account is newly subscribed, in at least some cases a notification appears that they have Mystery Items available, even though they do not. 

This one is verified by me. In this specific case the account (which did not have a subscription) was invited to a group plan (thus receiving a 'free' subscription).

### PR DESCRIPTION
**Pull request by flhat**
Fixes #10496

### Changes
- Checked to make sure pushedItems wasn't empty before user.addNotification() is called

----
UUID: 495eed5c-2828-4e24-a19d-755ac5e95295

### CODE REVIEW

**Comment by TheHollidayInn** [comment]
Thanks @BlkStormy! Can you add a test around this?

@paglias could this have caused empty notifications?

**Comment by paglias** [comment]
@TheHollidayInn no, I don't think so this would just cause a mystery items notification with no items inside, but the remaining data is still there

**Comment by flhat** [comment]
I haven't written a test yet.  Let me look into how to do that and I'll give it a shot.

**Comment by paglias** [comment]
Any update on this one?

**Comment by paglias** [comment]
Closing for lack of updates

**Pull request closed without merging**
