### PR TITLE
Add docker file

### PR DESCRIPTION
**Pull request by titilambert**
Just add a Docker file to quickly get a HabitRPG production instance ;)

### CODE REVIEW

**Comment by lefnire** [comment]
Not knowing Docker, I'll take your word for it ;)

**Comment by lefnire** [comment]
UUID?

**Comment by titilambert** [comment]
UUID ? what is it ?

**Comment by lefnire** [comment]
[User ID](http://habitrpg.wikia.com/wiki/API_Options), if you'd like a "thank you" contrib reward

**Comment by titilambert** [comment]
HO !
It's titilambert .
Thanks !

**Comment by Alys** [comment]
@titilambert Please read the link that lefnire put in his latest comment. That will show you how to find your unique User Id. It's different than your name, because people can choose the same name.

**Comment by titilambert** [comment]
@Alys Thanks ! @lefnire 572ccecf-e99b-40dd-9595-47a387449ba7

**Comment by lefnire** [comment]
√

**Pull request merged**
