### PR TITLE
fix Stable sidebar width and center inventory drawer (fixes #9263)

### LINKED ISSUE #9263: Quick inventories should be centered
The Quick Inventory is not centered, compared to the one in the Market. See http://recordit.co/uHUtzsqSlv for an example. Note that there may be other discrepancies with Quick Inventories across the site.

### PR DESCRIPTION
**Pull request by trvrfrd**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #9263 

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
Removed the .col-3 class from the Stable sidebar to get it to match the width of the .standard-sidebar on the Equipment page. Also updated the width on the quick action drawer to correctly account for the width of the sidebar on both pages (as described in the issue) and removed the column-related classes from the main page container of the Stable.

I'm concerned that removing those CSS classes may cause unintended behavior or break something elsewhere in the application, so if someone more familiar with the codebase than me could weigh in and take a look, I'd definitely appreciate it. I did some quick manual testing after making the changes and all the Stable functionality seems to be working as expected.

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 7620c72a-bb5a-4798-b3c0-846dacb2b44d

### CODE REVIEW

**Comment by negue** [comment]
@trvrfrd thanks for your contribution!  the code looks to me 👍 

Sorry but could you please add two things to this PR?

- could you update the `hidden-xs-down` according to the new bootstrap version http://getbootstrap.com/docs/4.0/utilities/display/#hiding-elements   - I guess `d-none d-sm-block` should work fine for this
- add the same hiding to the other `standard-sidebars` so that on a mobile browser those are hidden away

**Comment by trvrfrd** [comment]
@negue no problem! That's exactly the kind of omission I was afraid of making and hoping someone else would catch. I'll go ahead and update the other sidebars.

**Comment by SabreCat** [comment]
Gonna see if a fresh merge of `develop` straightens out that random CI failure.

**Comment by SabreCat** [comment]
Boom! Noted in your progress toward Blacksmith tier 2!

**Pull request merged**
