### PR TITLE
More Gem Sizes

### PR DESCRIPTION
**Pull request by Shaners**
- Added two new gem sizes to egg sprite sheet and CSS

### CODE REVIEW

**Comment by lefnire** [comment]
perfect, thanks dude!

**Comment by Shaners** [comment]
@lefnire Are we still planning on using these or do you think people are now too set with how things are currently? Maybe I could make a more token like icon? Worried that it'll look too much like the gold and silver icons though.

**Comment by lefnire** [comment]
I may have pulled a bad stunt waiting as long as I did, but I still had in the back of my mind "implement those icons for tokens". the word "Gems" is more familiar, I'm starting to realize, from other games. Guild Wars for example. But people are so established at this point. pros / cons, what do you think personally Shane?

**Comment by Shaners** [comment]
@lefnire my opinion is just to pull the trigger, i.e. rename all instances of tokens to gems and put the graphic up beside the count of user's tokens. I think most people will adjust fine since things will function exactly the same. I see a couple people getting confused if they first take a look at the pet egg and potion cost and may think "hey wtf now I have to buy gems too??" but that should be resolved as soon as they look up (which they should because there will be a new image there.) I also really doubt there are people that feel a special connection to tokens since it's so abstract right now and no imagery connected to them.

**Comment by StanLindsey** [comment]
I think its a good change, gems are more dissimilar to coins than tokens are. Can always have a one off tooltip & bailey shout out.

**Comment by Shaners** [comment]
@lefnire @SlappyBag Should we put this to a vote for the final decision?

**Comment by wc8** [comment]
Just adding my 2¢ here, I don't think it's too late. I agree with @SlappyBag just change all the names, have a Town Crier update, update the tour, etc.. We can have a FAQ ready about Tokens/Gems and just direct any questions to that link. If you want, for a while use "Gems (Tokens)" for the main description.

**Comment by StanLindsey** [comment]
+1 

Had a convo with @lefnire about this today and he agrees, I'll implement this tomorrow.

**Pull request merged**
