### PR TITLE
Remove apdex check from middleware until NR is back

### PR DESCRIPTION
**Pull request by gisikw**
Apdex check was incorrectly throwing errors, since we took NR out of the mix.

//cc @paglias

### CODE REVIEW

**Comment by paglias** [comment]
memoryHigh is set to false?

**Comment by gisikw** [comment]
Yeah, noticed that too. Did a git blame, but history's messed up, so I don't know why it was disabled.

**Comment by crookedneighbor** [comment]
I tracked down the commit; https://github.com/HabitRPG/habitrpg/commit/623175c312065bf0fa039f00c17e043d2c402d74

**Comment by paglias** [comment]
@crookedneighbor @gisikw merging and deploying, anyway if the memory leak is fixed it shouldn't be necessary anymore

**Pull request merged**
