### PR TITLE
Improve help button visibility

### LINKED ISSUE #5283: Make Help Button More Obvious
It would be nice to make the help button in the header more obvious, perhaps by changing its color. 

Would this be a suitable project for an aspiring coder?

### PR DESCRIPTION
**Pull request by excentris**
Fixes #5283

Improve the help button visibility by styling it with the colours of
the subscribe button (for consistency) and adding a ‘?’ icon.

### CODE REVIEW

**Comment by deilann** [comment]
Can you post screenshots?

Whenever you're doing a very visual fix (or actually, it's just good in
general) you should post screenshots.

**Comment by excentris** [comment]
@deilann sure! It is my first contribution, so I need to get used to the workflow. Here it goes:

help_button

**Comment by deilann** [comment]
Oh, I like that! @lemoness @alys @crookedneighbor

**Comment by excentris** [comment]
@deilann I'm sorry I pushed a fix for another issue to the same branch I used to fix this issue. I reverted the commit on the next commit.

**Comment by lemoness** [comment]
It looks great. Thanks so much!

**Comment by excentris** [comment]
@lemoness You are very welcome!

**Comment by crookedneighbor** [comment]
@excentris Since we're duplicating the subscribe styles, can we instead refactor it so that both are using the same styling? Rather than having to change both when we want to make a change to the styling. 

I'm thinking that any of the menu buttons should like the subscribe and help buttons when they have the highlight class.

**Comment by excentris** [comment]
@crookedneighbor I totally agree. I seem to recall that I tried doing so, but I can't remember why didn't I do it in the end. I will take a look at it this evening, after work. Thanks for the feedback!

**Comment by excentris** [comment]
@crookedneighbor I am getting an error when trying to run habitrpg locally (grunt run:dev) that I have no idea how to solve. I have updated my fork, run npm install and bower update but keep getting the following error:

```
[nodemon] starting `node ./website/src/server.js`
/[...]/habitrpg/node_modules/mixpanel/lib/mixpanel-node.js:19
        throw new Error("The Mixpanel Client needs a Mixpanel token: `init(tok
              ^
Error: The Mixpanel Client needs a Mixpanel token: `init(token)`
    at Object.create_client [as init] ([...]/habitrpg/node_modules/mixpanel/lib/mixpanel-node.js:19:15)
    at Object.module.exports.setupConfig ([...]/habitrpg/website/src/utils.js:183:38)
    at Object.<anonymous> ([...]/habitrpg/website/src/server.js:6:7)
    at Module._compile (module.js:460:26)
    at Object.Module._extensions..js (module.js:478:10)
    at Module.load (module.js:355:32)
    at Function.Module._load (module.js:310:12)
    at Function.Module.runMain (module.js:501:10)
    at startup (node.js:129:16)
    at node.js:814:3
[nodemon] app crashed - waiting for file changes before starting...
```

**Comment by Alys** [comment]
@excentris Update your local copy of config.json with the new items that have been added to the example config.json. That should fix it.

Note also that new software has been added to package.json so you might also need to run "npm install" again.

**Comment by excentris** [comment]
@Alys Thanks! I'll try that and update the wiki with the tip.

**Comment by crookedneighbor** [comment]
It'd be good to have a section there with a heading that says something like: "What to do when it worked before, but now it doesn't" (better title's welcome) with the troubleshooting steps Ays listed.

**Comment by excentris** [comment]
@crookedneighbor Regarding your suggested refactoring, what do you think of the code now? I have moved things around to make the highlight class reusable by other buttons. Both the help and subscribe button use now the highlight class.
@crookedneighbor Regarding the documentation changes, I can add @Alys tip under a Post Installation troubleshooting section.

**Comment by crookedneighbor** [comment]
@excentris Looks like you did a rebase and it pulled in a lot of extraneous commits. I'll squash them when this gets merged in.

**Comment by crookedneighbor** [comment]
The way you've done the styling, it applies the blue outline and text to the sub-menu.

**Comment by excentris** [comment]
@crookedneighbor Sorry about to rebase. Still learning all this :)
About the styling, I thought it was meant to be that way, since I am using the generic hrpg-button-color-mixin, but after your reaction and clicking a bit around I do not see any other hrpg-button-toggle with a different color than the standard gray so the blue coloring is just a side effect of such mixin applied to a button-toggle. I will take a look at it this evening.

**Comment by excentris** [comment]
@crookedneighbor It was harder than I thought, but I managed to refactor the code to avoid the sub-menu styling issue. What do you think?

**Comment by crookedneighbor** [comment]
The rebasing was so intense, I had to check out the files and re-commit the changes. 

Merged in here: https://github.com/HabitRPG/habitrpg/commit/41b1abba3a089014ce1fa81929e5934527510a46

This will count towards a contributor tier! What's your User ID? You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api). Be sure to only copy the User ID and _not_ your API Token.

**Comment by excentris** [comment]
@crookedneighbor I'm sorry about all the extra work you had to do... But thanks for all your help! 
I'm happy my contribution was accepted :)
My User ID is: 34c0ab62-863e-49dc-9316-a48170633359

**Comment by crookedneighbor** [comment]
Tier awarded!

You can read more about [contributor rewards here](http://habitrpg.wikia.com/wiki/Contributor_Rewards)

**Comment by excentris** [comment]
Great! Thanks!

**Pull request closed without merging**
