### PR TITLE
Onboarding guide and initial achievements refactoring (WIP)

### PR DESCRIPTION
**Pull request by paglias**
TODO

- [x] start achievement refactoring
    - [x] Requires sync after getting achievement
    - [ ] update issue with necessary next steps
    - [x] checkOnboardingStatus, should it run on the client? Otherwise how to award 100 gold?
    - [x] remove old notifications from delta
    - [x] Change notification for achievements to add data directly there instead of on client side
- [x] Migration existing users
    - [x] completedTask
    - [ ] test/run/move to archive 
- [x] Clean Achievements Modal
- [x] Date check to never show the panel for everyone who signed up before the rollout (with tests)
    - [x] Tweak date based on launch

### CODE REVIEW

**Comment by Tressley** [comment]
Moved to main comment

**Comment by Tressley** [comment]
Moved to main comment

**Comment by Tressley** [comment]
Notifications panel is scrolling within the container.
image
*Note how the Notifications heading is cut (I scrolled down.)

**Comment by Tressley** [comment]
"Let's Go" button text is now gray instead of white.
image

**Comment by paglias** [comment]
Should It scroll insider it's own container?

Il Gio 5 Dic 2019, 14:47 Tressley Cahill <notifications@github.com> ha
scritto:

**Comment by Tressley** [comment]
Nope! Should grow to accommodate.

**Comment by paglias** [comment]
Oh I see, I think right now it might have an height limit but I'll remove that

**Comment by Tressley** [comment]
In the achievements panel, the name of the achievement name should be updated to title case.

Create a Task
Complete a Task
Hatch a Pet
Feed a Pet
Purchase Equipment

**Comment by Tressley** [comment]
Initial testing looks good to me. 👍

**Comment by Tressley** [comment]
This LGTM. I think it should be ready to go for this week. 👍

**Pull request merged**
