### PR TITLE
Match tavern sidebar UI to party and guild page changes

### LINKED ISSUE #9932: Tavern UI changes needed to match recent Guild and Party changes
In PR https://github.com/HabitRPG/habitica/pull/9892, changes were made to the Guild and Party pages. 

Those changes should also be made to the Tavern, where appropriate.  E.g., member list changes are not needed, changes to the buttons are.

_(Thanks to sonnet73 for pointing this out in the Report a Bug guild.)_

### PR DESCRIPTION
**Pull request by dominictwlee**
Fixes #9932

Before: 
screenshot_2018-05-27 habitica - gamify your life

After: 
screenshot_2018-05-27 habitica - gamify your life 1

Added some spacing for the header image in the sidebar to match party and guild pages. 

It seems the buttons in the main section were already fixed by someone else so I didn't touch them.

### CODE REVIEW

**Comment by paglias** [comment]
Thanks @dominictwlee ! 

@Tressley I think here the issue might be that the guilds have too much space while the tavern has the correct one:

schermata 2018-05-27 alle 17 57 26

^ guild

schermata 2018-05-27 alle 17 58 26

^ tavern

**Comment by Tressley** [comment]
@paglias -- Yeah. It looks like the right column isn't placing content flush with the top.

**Comment by paglias** [comment]
@dominictwlee sorry about this but it looks like that bug report was wrong and actually the only change to do is to remove the extra space at the top of the guilds' sidebar instead of adding space to the tavern. Can you change that?

**Comment by dominictwlee** [comment]
@paglias Sure, I'll tend to it sometime this week.

**Comment by dominictwlee** [comment]
Before: 
screenshot_2018-06-02 habitica - gamify your life 1

After: 
screenshot_2018-06-02 habitica - gamify your life 2

Tavern reverted back to normal: 
screenshot_2018-06-02 habitica - gamify your life 3

New modifications to guild sidebar doesn't affect party page sidebar:
screenshot_2018-06-02 habitica - gamify your life

**Comment by paglias** [comment]
thanks for this @dominictwlee ! If you have an Habitica UUID I'll be happy to award you a contributor tier!

**Pull request merged**
