### PR TITLE
convert eyepatches and masks from headAccessory to eyewear - fixes https://github.com/HabitRPG/habitrpg/issues/3645

### PR DESCRIPTION
**Pull request by Alys**
@lefnire This requires `migrations/20140829_change_headAccessory_to_eyewear.js` to be run. Note the comment saying "UNCOMMENT ONE OF THESE LINES"

Goes along with https://github.com/HabitRPG/habitrpg-shared/pull/291
- modifies code to treat eyepatches and wondercon masks as new eyewear gear type instead of headAccessory
- updates database_reports/count_users_who_own_specified_gear.js since that reports on wondercon masks

### CODE REVIEW

**Comment by lefnire** [comment]
Awesome, thanks @Alys! Keep these PRs open, I'll merge & migrate together

**Comment by lefnire** [comment]
I've merged this. There were [conflicts](https://github.com/HabitRPG/habitrpg/commit/e63f2b6d977b1030c61223c7a58f1f9b1beb7449) on `database_reports/count_users_who_own_specified_gear.js` (as seen [here](https://gist.github.com/lefnire/167dd572720c33210bf1)). I resolved them as:
- `git checkout database_reports/count_users_who_own_specified_gear.js --ours`
- find/replace `headAccessory`=>`eyewear`

Let me know if that's no good. I'll be working on the migration soon

**Comment by lefnire** [comment]
@Alys migration has been run

**Comment by Alys** [comment]
Thanks @lefnire.

"find/replace headAccessory=>eyewear" is good.

**Pull request merged**
