### PR TITLE
More elegant show/hide setup for attribute bonuses

### PR DESCRIPTION
**Pull request by SabreCat**
Rather than show based on feature unlocks, hide each element if it's 0. Ends up making a much shorter, tidier Attributes section.

### CODE REVIEW

**Comment by lefnire** [comment]
merge conflicts, might be translations stuff. wanna take a gander? else I will in a few days

**Comment by SabreCat** [comment]
I can take a stab. I've only done conflict resolution once before, but I might be able to figure it out.

**Comment by SabreCat** [comment]
@lefnire: Crap. I tried. Maybe I merged the branches the wrong way around? I think this is good if you can just pluck the changes to `stats.jade`, which now has the new show/hide logic on top of the I18N-enabled strings...

**Comment by SabreCat** [comment]
Hey cool, Travis builds are passing now xD

**Comment by lefnire** [comment]
Shoot, I'm sorry man! should I just copy/paste in `stats.jade` then?

**Comment by SabreCat** [comment]
Yeah, that's all that's relevant to this PR. If you need me to kill this off and try again, I can do that too.

**Comment by lefnire** [comment]
commited, thanks man!

**Pull request closed without merging**
