### PR TITLE
[API v3] Port groups, challenges and members

### PR DESCRIPTION
**Pull request by paglias**
WIP

### CODE REVIEW

**Comment by TheHollidayInn** [comment]
If you need help porting the other routes and tests for groups, I would like to help. I ran into a stopping point while working on a challenge port because I need the group endpoints.

**Comment by crookedneighbor** [comment]
@TheHollidayInn state specifically what you are going to work in and then PR into this branch.

**Comment by crookedneighbor** [comment]
That is to say, yes! We welcome the help.

**Comment by SabreCat** [comment]
@TheHollidayInn I've just started on chat routes here: https://github.com/HabitRPG/habitrpg/tree/sabrecat/api-v3-chat. Maybe you can nab the routes for flagging and liking chat posts, and we'll meet in the middle?

What is it you're working on for v3 challenges, btw?

**Comment by paglias** [comment]
@TheHollidayInn as @crookedneighbor said we would really welcome the help but as you can see in the `api-v3` branch the code is quite a bit different. I think @SabreCat 's proposal for flagging and liking chat messages is a good point to start from. I'd start from the like route since it's easier to implement and maybe then the delete chat message route before the flag chat message one. 

You should try to follow the style we used for other api-v3 routes (can be found in the branch). This is a good example https://github.com/HabitRPG/habitrpg/commit/1d476c4b4e6d00267784c3ea8a017c0f2ef4ccdf. When working on groups methods you should fork the api-v3-groups branch since it's where I'm porting the group model (still to be finished). When you have a PR ready (if you can with integration tests), ping me and I'll review it

Let me know if you have any question!

And thanks!

**Comment by crookedneighbor** [comment]
@TheHollidayInn Also, just an FYI, the challenges code in particular is one of the big reasons for writing V3, so we'll likely want to rewrite it entirely, so porting the v2 code for challenges to v3 is probably not the best use of your time.

**Comment by TheHollidayInn** [comment]
Sounds great. I don't mind where I work; I'd just like to help. Quite a few of my API PRs were closed because of API V3, and I don't really know what the goals are. So, it seems hard to start.

@SabreCat Here is some code I was starting with Challenge: https://gist.github.com/TheHollidayInn/31a7957c5e1514524c5a . I was stuck when I realized I needed the groups post route and/or to alter the Challenge model. Feel free to disregard the code altogether if it is no use. 

Also, I see many TODO marks for array data on the model, and I was working on making the arrays more efficient before we stopped V2. I read some about large array data and how to arrange it with Mongo.

And finally, @SabreCat, I will definitely work on those routes. I'll submit some progress by Friday.

**Comment by paglias** [comment]
@SabreCat @TheHollidayInn fyi, I removed the invitations and members arrays from the group model and moved them to the user model

**Comment by TheHollidayInn** [comment]
Awesome!

**Comment by paglias** [comment]
I've refactored the process to load a group to account for the changes I made to the model and moved it to a static method of the model

**Comment by TheHollidayInn** [comment]
Are the createAndPopulateGroup and generateGroup functions working right now?

**Comment by paglias** [comment]
No, they're broken. They rely on some routes we don't have yet. I'm working
on listing groups and then will move on to creating groups

2015-12-18 16:53 GMT+01:00 Keith Holliday notifications@github.com:

> Are the createAndPopulateGroup and generateGroup functions working right
> now?
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/HabitRPG/habitrpg/pull/6374#issuecomment-165813048.

## 

Matteo Pagliazzi - paglias.net

**Comment by TheHollidayInn** [comment]
Good call on abstracting that function.

And okay, then I will just use the global Habit group for testing chat messages. Because, chats depend on a group created right now, I believe.

**Comment by paglias** [comment]
@TheHollidayInn for tests, better if we write them failing and wait for the helpers to work

**Comment by TheHollidayInn** [comment]
Okay, can do.

**Comment by paglias** [comment]
I added basic implementations of methods for creating a group, getting a group and getting the user's group. So we can start writing tests starting from the create group method. Population is still missing.

Whoever starts testing the create group method, write it here so we don't overlap

**Comment by TheHollidayInn** [comment]
Okay, I'm going to start testing the create group method, since it is hard for me to visualize progress without it.

**Comment by TheHollidayInn** [comment]
So, I have made some progress on the chat like/favorite, but I was also working on the chat POST route to get my tests to work.

Here is my gist: https://gist.github.com/TheHollidayInn/186e4f00a5d6c92d0fad . The chat gets created, but I'm not seeing the message, and I am unsure of how the message gets attached. I think I need to just query the group, but I wanted to post this to get some early feedback. 

Also, when I uncomment this line, `req.checkParams('message', res.t('messageGroupChatBlankMessage')).notEmpty();` I get an invalid params error, but I believe I am passing the parameter correctly. 

I'm will do some more work on this tomorrow, but let me know what you guys think :)

**Comment by paglias** [comment]
@TheHollidayInn it's better if you create a PR so I can leave comments directly on the code:
- at line 63: you're passing the message in req.query but validating a parameter like /ur/:parameter that's why the validation is failing. you should use req.checkQuery https://github.com/ctavan/express-validator. But honestly it's better if you move the message from req.query to req.body, passing it in the query is very odd.
- at line 69, you're selecting only the 'chat' field from the group document, so all other fields (group.type, ...) will be undefined. You should fetch the whole group in this case
- line 73 should use the new errors, in this case a NotAuthorized error
- at line 77 there's no need for parenthesis
- line 90 should be deleted

**Comment by paglias** [comment]
I've ported join and leave routes

**Comment by paglias** [comment]
I've ported removing a member and started working on invites

**Comment by TheHollidayInn** [comment]
Thanks for the comments, @paglias . How do I send to the body? The `send()` function is undefined now, and I am using the same calls as in the Tasks tests. I'll post a PR in a bit. Almost done.

**Comment by paglias** [comment]
@TheHollidayInn you can pass the body as the second parameter: `api.post(url, body object)`

**Comment by TheHollidayInn** [comment]
Thanks! I thought from your comment above that I was passing the parameters incorrectly, but I see now you were just saying in general.

**Comment by paglias** [comment]
Ported challenge model

**Comment by paglias** [comment]
Ported list and create routes for challenges

**Comment by paglias** [comment]
Ported update group route and started working on quests routes

**Pull request merged**
