### PR TITLE
Separate mocha tests

### PR DESCRIPTION
**Pull request by crookedneighbor**
Part 1 to making the api tests manageable: Separate them into separate files that can be run individually, or as a group

@lefnire Can I get your :eyes: on this before I merge it in.

@theHollidayInn You may also be interested in this.

### CODE REVIEW

**Comment by crookedneighbor** [comment]
Next steps:

### API
- Convert request to use [supertest](https://github.com/visionmedia/supertest)
- Review each test and see if any cleaning up can be done
- Attempt to reduce non-test noise. Being able to register 15 users at once is awesome, but the flood of 200 responses in the middle of the test is not.
- Use chai expect instead of expect.js
- Fix and unpend tests
- Fill in missing tests

### Common
- Fix and unpend tests
- Fill in missing tests

### E2E
- Solve E2E misbehavior

### Unit
- Fill in missing tests
- Refine controllers and existing tests

**Comment by crookedneighbor** [comment]
A downside of this PR is that, as far as git is concerned, I am the writer of all these tests :grimacing:

Oh yeah, [here is a brief overview of how the api tests are set up](https://github.com/crookedneighbor/habitrpg/blob/separate_mocha_tests/test/api/README.md)

**Comment by crookedneighbor** [comment]
In terms of organization, I was thinking one test per API grouping, with the exception of User, which should be split up more. That said, we could split them up even further, put guilds and parties and quests in separate test files. If there's shared behavior (like parties, public guilds, private guilds, tavern), we could use [Mocha's use of this](https://github.com/mochajs/mocha/wiki/Shared-Behaviours)

**Comment by crookedneighbor** [comment]
@gisikw if you have a moment, I'd value your feedback and :eyes: on this as well.

**Comment by TheHollidayInn** [comment]
This is great! I'm catching up on some of my lingering PRs, then I will focus on helping with the tests.

**Pull request merged**
