### PR TITLE
Add script that let's you manually run cron form the command line

### PR DESCRIPTION
**Pull request by colegleason**
(This is a continuation of #2346.)

As mentioned in #2344, #2126.

To use:

```
node ./src/server.js --cron
```

You can also specify the current hour to run it manually for other users. `--cron-hour` is the hour in the server's timezone.

```
node ./src/server.js --cron --cron-hour 14
```

I think it may need a database migration to add user.cronTime. Not sure how defaults work and all that.

Once vetted, you would probably want this setup with  [Heroku Scheduler](https://devcenter.heroku.com/articles/scheduler).

Other things to be done:
- [x] Port all cron tests from habitrpg-shared over here.
- [x] Remove the daysMissed check from user.fns.cron
- [x] Remove api.cron from all routes.
- [ ] Setup heroku scheduler.
- [ ] Test with a large number of active users.
- [x] Should we perhaps get an email with any errors encountered during cron?
- [x] Decide on a batchSize to use (maybe dynamic based on count?).

batchSize performance numbers on 4f95bbf.

| Users | batchSize | MB | Seconds |
| --- | --- | --- | --- |
| 2238 | 2 | 172 | 25 |
| 2238 | 5 | 171 | 22 |
| 2238 | 10 | 193 | 23 |
| 2238 | 100 | 321 | 24 |
| 2238 | 1000 | 619 | 37 |

### CODE REVIEW

**Comment by lefnire** [comment]
I created a `cron-script` branch on habitrpg-shared, wasn't sure if you had one going on (couldn't find one). I started gutting the old cron code, will update your checklist

**Comment by lefnire** [comment]
> Decide on a batchSize to use (maybe dynamic based on count?).

I think 100-200 could be a safe bet. DB shows avgObjSize as 100kb or so, but I've often worked with accounts 1-2MB. You can't really get much larger than that, since the app (at least Angular & Mobile) will overload and freeze your browser/app. 512(heroku max)/2(safe-side max) = 256, knock it down a bit and we could reasonably work with 200. Thoughts? "Tyler you're dumb"?

**Comment by colegleason** [comment]
We need to remember that the node process will use some memory too, so
subtract that out.

On Sat, Jan 18, 2014 at 1:14 PM, Tyler Renelle notifications@github.comwrote:

> Decide on a batchSize to use (maybe dynamic based on count?).
> 
> I think 100-200 could be a safe bet. DB shows avgObjSize as 100kb or so,
> but I've often worked with accounts 1-2MB. You can't really get much larger
> than that, since the app (at least Angular & Mobile) will overload and
> freeze your browser/app. 512(heroku max)/2(safe-side max) = 256, knock it
> down a bit and we could reasonably work with 200. Thoughts? "Tyler you're
> dumb"?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/pull/2467#issuecomment-32690170
> .

## 

## Cole Gleason

Student, University of Illinois at Urbana-Champaign
Email: cg@colegleason.com
Website: colegleason.com

**Comment by colegleason** [comment]
@lefnire I'm working on migrating tests. Should everything related to cron be moved, or just stuff that would break? An example is `preenHistory` tests. I actually already moved that, but I'm not sure if we may want that in habitrpg-shared still.

**Comment by wc8** [comment]
If you have a test to copy/paste in the command line (I can add api keys) in the next 2-3 days, I'll try to see if I can get to it. My account and party member's account can be tested. (The latter is affected by no cron.)

**Comment by colegleason** [comment]
@lefnire Just updated this branch to be rebased off master. I should have merged instead, sorry! You'll probably need to re-checkout or whatever.

**Comment by colegleason** [comment]
@lefnire, Also, what are your thoughts on this? Want to try it out on some sort of test instance on Heroku? Looking at the checklist above, we covered most of the major concerns except for actually running the thing.

Also, if we are going to need to tune cluster and batchSize to make it optimal based on memory usage.

**Comment by colegleason** [comment]
To load test this I think the best option might be to create a copy of the DB in another mongoose instance and run it on that. We could then delete the test DB when we throw it in production.

**Comment by lefnire** [comment]
@colegleason you awesome dev you! I was worried this was gonna get too far behind. I hope to jump into tomorrow or next, I'll ping back when

**Comment by Alys** [comment]
I've checked with @paglias and he says that this was from a completely different approach to cron than the one we are using now, so this and any related PRs can be closed. Sorry @colegleason!

**Pull request closed without merging**
