### PR TITLE
Debounce `$scope` updates when typing in chat.

### LINKED ISSUE #6462: Tavern / Guild / Party chat lag / slowness
Platform: Win10, Chrome 47.0.2526.106 m

Take a look at this example of the tavern's chat:
image
The Ss were typed one at a time and the Js were typed 5 at a time.

It seems that there is a listener happening every time that the content of the textbox changes. While this doesn't seem to be a problem in-of-itself, It appears that the digest function it is calling is quite expensive.(I'm not sure if this is an AngularJS problem, or something regarding your backend). For reference, my account has ~20 tasks.

It seems that the lag is present throughout the site, (probably on some task iteration logic), and other Issue threads have tried to address it. #6215 #3486 However, I'd recommend fixing the issue at the chat level.  The entire autocomplete feature could be disabled, or perhaps changing it so that it waits a few seconds from last input before it calls the digest handler. ( I think it already works this way? but the delay is really short?)

I know @lefnire mentioned addressing the chat system in another performance thread, but I'm not sure if it came through. Some good places to start would probably be:
habitrpg/website/public/js/controllers/autoCompleteCtrl.js

I would try to fix it myself, but I'm unfamiliar with the software stack. (As of now)

### PR DESCRIPTION
**Pull request by applmak**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #6462.

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
Debounce `$scope` updates when typing in chat. Saves a bunch of time per frame when the user is typing, making the chat widget feel more responsive.

Profile before:

Profile after:

[//]: # (Put User ID in here - found in Settings -> API)

----
UUID: 
912546cc-28cf-4c3a-b01e-c8dccfd6cbd9

### CODE REVIEW

**Comment by paglias** [comment]
@applmak I have a question about this, what happens if a) debounce runs and save the value in the model variable b) user types more chars c) user press enters 

will the chars entered between the end of a) and the start of c) be lost?

**Comment by applmak** [comment]
@paglias According to the [docs on NgModelOptions](https://docs.angularjs.org/api/ng/directive/ngModelOptions#triggering-and-debouncing-model-updates), a `submit` event will force the model to sync with the view. This means that the action attached to the form via `ng-submit` will work, but as currently implemented the `keyDownListener` will not. I'll update this PR to include a test for this case, while changing the `keyDownListener` to submit the form, which should address your concern.

**Comment by applmak** [comment]
@paglias Updated with test that shows that data is not lost when requesting the form to submit. I introduced a new directive submit-on-meta-enter to encapsulate this behavior. PTAL.

**Comment by TheHollidayInn** [comment]
This is pretty awesome. The profile report looks great.

**Comment by paglias** [comment]
this look good to me, @TheHollidayInn feel free to merge if it's good for you

**Comment by TheHollidayInn** [comment]
The integration test can be ignored, but there are failing builds on the common and karma.

**Comment by applmak** [comment]
Those errors seem to be related to the test environment, rather than the test or code itself. Is there some way to punch the build to get it to retry?

**Comment by TheHollidayInn** [comment]
Restarted!

**Comment by applmak** [comment]
Strict mode failure reported in the karma test. Fixed, presubmit checks are running.

**Comment by applmak** [comment]
Okay, tests are green. Is there any manual QA that happens before this goes live?

**Comment by TheHollidayInn** [comment]
We will add this to our release branch. After some testing it will go live! Thanks. :D

**Comment by applmak** [comment]
No problem. I know you're re-writing your frontend, but if there are other quick performance improvements I could do, lmk.

**Comment by TheHollidayInn** [comment]
We are actually hoping to improve the test coverage of the current front end if you would like to help.

**Comment by TheHollidayInn** [comment]
Noted towards your tier! Congrats on Tier 1 :D

**Comment by Alys** [comment]
Just FYI for the record:

We're having some trouble on our test server with the PRs that have been merged in recently, so I've started testing each one individually. I tested this one on my local install by fetching upstream, then checking out 705a78e835ded7643ed6655d61d9c1fe3d555f4a and doing `npm start` My testing has been VERY brief but everything looks good here so far. My tests show:

- Chat messages can be posted in the Tavern
- People's names can be selected in Tavern chats by typing @ then selecting from the list
- Habits can be scored up and down (with the new counters incrementing correctly https://github.com/HabitRPG/habitica/pull/8198)
- Tasks can be edited
- Tasks can be deleted
- Tasks can be added, and if the "edit mode" setting is turned on, the edit modal appears as soon as you add the task

**Pull request merged**
