### PR TITLE
Replaced collar icons

### LINKED ISSUE #6336: Collar Icon Fix
The Unconventional Armor collar icons were the incorrect size.

Here are the fixed files:

conventioncollarblackicon
conventioncollarredicon
conventioncollaryellowicon

### PR DESCRIPTION
**Pull request by NathanMaton**
Collar Icon Fix #6336

### CODE REVIEW

**Comment by NathanMaton** [comment]
Not sure why the .css file is showing up here as I don't see any changes to it if you have any advice on that.

**Comment by SabreCat** [comment]
@NathanMaton: `habitrpg-shared.css` is built automatically when the server starts up. It doesn't need to be (and probably shouldn't be) included in pull requests.

Also, this PR has the same issue as the parallel PR #6369, in that the changes were made to the wrong sprites. You want the files starting with `shop_`, which are the resized versions of the items displayed on the Equipment screens and the Rewards column, not the base sprites that attach to the avatar.

**Comment by NathanMaton** [comment]
Ok swapped the files. still having issues getting that .css file out of the PR as it isn't showing up in my changes when I do git status and it didn't stay excluded even though I added it to .git/info/exclude if you have any other tips to investigate.

**Comment by crookedneighbor** [comment]
Merged in with https://github.com/HabitRPG/habitrpg/commit/b26d3bef40775b41a5b044e1f5fcbc0493a38921

This will count towards a contributor tier! What's your User ID? You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api). Be sure to only copy the User ID and _not_ your API Token.

**Comment by crookedneighbor** [comment]
Never mind about the user id, I found it on another PR. I've notated this toward your next tier.

**Pull request closed without merging**
