### PR TITLE
Make export to csv button on challenges export all tasks (issue #2947)

### PR DESCRIPTION
**Pull request by Verabird**
This time without the line end problems.

### CODE REVIEW

**Comment by lefnire** [comment]
Awesome! This is per https://github.com/HabitRPG/habitrpg/commit/632726fe0273ad507138ae9c30a8a890659e8a0f I presume? I need to upgrade our server to mongod 2.6 (currently 2.4) which may take some time, then I'll merge. Thanks!

**Comment by Verabird** [comment]
Actually, I hadn't seen your https://github.com/HabitRPG/habitrpg/commit/632726fe0273ad507138ae9c30a8a890659e8a0f  before I sent this PR. This just uses $unwind, $match, $sort, and $group but first projects all the tasks into one group (tasks). The ordering is not ideal either. But as far as I can tell it is usable.

**Comment by lefnire** [comment]
Whatevs re: ordering, $elemMatch only shows 1 row so this is bounds better than previous code, _plus_ it uses agg framework which vastly improves perf (vs server-side filtering) and the direction I want to take challenges code as much as possible. Just upgraded to 2.6, i'm gonna test this PR some and get back to you. What's your UUID for contrib.lvl++? (you deserve two, I missed the other PR)

**Comment by Verabird** [comment]
850cbb7e-4837-41ac-8d32-58d09d97c5bc

**Comment by deilann** [comment]
Levels applied!

**Pull request merged**
