### PR TITLE
Added MAFL Theme

### PR DESCRIPTION
**Pull request by SalethiNat94**
### Changes
*Added audio files and modified relevant files to add MAFL's Theme. [Here's a link to the audio files used!](https://drive.google.com/file/d/0Bz27m8ajKyNZMHpEMUpSQXBIZFU/view)

----
Audio theme created by MAFL/Noxial (UUID: 15ba83b4-4d7c-4815-b59d-12b82ba01505)
Submitted to GitHub by Pizilden (UUID: 7a1b0a51-0221-4542-b09f-c5e27ba83f31)

### CODE REVIEW

**Comment by negue** [comment]
I like Boss Battles Music :>, my only issue is that `Level_Up` needs to be trimmed at the end, around 8 seconds are without any sound. 

Once that is fixed, its ready to be merged

**Comment by SalethiNat94** [comment]
Similar merge conflicts needed to be resolved here, but the Level_Up sounds should be trimmed now

**Comment by paglias** [comment]
@Pizilden can you remove the extra commits? The easiest thing might be to create a new clean branch and reapply your changes there

**Comment by SalethiNat94** [comment]
Created the new clean branch and a new PR to go with it

**Pull request closed without merging**
