### PR TITLE
reward:gold field is now a number instead of text. 

### PR DESCRIPTION
**Pull request by pironic**
changing the field type will validate the input from user before submitting form... we should check the input once received as well, but this is good enough for now...

this is to address https://github.com/lefnire/habitrpg/issues/50

### CODE REVIEW

**Comment by superlikelikes** [comment]
i put "vacation" as the value and got a free level up when i clicked it!

**Comment by superlikelikes** [comment]
it doesn't work now, though. i did it yesterday.

**Comment by pironic** [comment]
Sorry, I'm confused, I you put vacation yesterday, and and with this new validation it won't accept that any more? Or, you fixed the error yesterday, and now with this new validation, the code you submitted previously doesn't work anymore? Your two sentences could be taken either way... 

The code I'm submitting here doesn't handle the error checking at the server, which means that people can still 'game' the the value or force the page to accept negative numbers... But for the majority of the Web users, this is an immediate fix. Plus it makes the field have a little up/down arrow on the side of it...

**Comment by superlikelikes** [comment]
habit rewards vacation

I clicked vacation and it gave me an instant level up. 
I just thought it was cool. 

I'm sorry if I confused you. I'm new.

**Comment by superlikelikes** [comment]
Now if i click it, it just takes my coins. Not joking. 
Try it :)

**Comment by StanLindsey** [comment]
This hasn't been committed yet though has it so it shouldn't take any effect on the live site? (Unless you're using dev tools to edit the files live)

**Comment by lefnire** [comment]
will deploy with next batch of pushes. Awesome awesome @pironic, keep em coming!

**Pull request merged**
