### PR TITLE
Correct add task icon alignment

### LINKED ISSUE #5148: Add Task plus not vertically centered
On Chrome, the plus sign for adding a new task to one of the four main columns is not vertically aligned in its button. It's substantially higher than center:

image

Note that the screenshot above also features the "cross" look from #4539, which may or may not be related. 
## <bountysource-plugin>

Want to back this issue? **[Post a bounty on it!](https://www.bountysource.com/issues/13110983-add-task-plus-not-vertically-centered?utm_campaign=plugin&utm_content=tracker%2F68393&utm_medium=issues&utm_source=github)** We accept bounties via [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F68393&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by excentris**
Fixes #5148

### CODE REVIEW

**Comment by excentris** [comment]
The mess above is the result of trying to fix a messy pull request. In order to fix this issue I created a new branch on my fork, but based on the develop branch where I had fixes for another issue. After opening this pull request I saw that my fixes from the develop branch came along (learning the hard way...). I'm sorry about the mess, but I am not sure what's the best way to proceed. Any help would be appreciated...

**Comment by excentris** [comment]
I'm closing this pull request and will open a new clean one without the mess.

**Comment by crookedneighbor** [comment]
I can help you clean up this one if you want.

**Comment by excentris** [comment]
@crookedneighbor After some google work I managed to open a new clean pull request (#5327) with only the relevant changes. Lesson learned: branch before starting on a new fix :)
Thanks, and again, sorry for the mess! Just finding my way around here...

**Pull request closed without merging**
