### PR TITLE
added debounce option of 1000ms to delay digest()

### PR DESCRIPTION
**Pull request by nrbunn**
#6462
### Changes

Added 500+ users and 500+ messages to tarvern chat to reproduce slowness when typing. Found that angular was spending a lot of time in digest. Found article related to slowness [http://www.aaron-gray.com/delaying-the-digest-cycle-in-angularjs/](url). Added 1000ms delay and saw improvement might need to play around with number some more.

---

UUID: 25479d8c-45e1-482c-877e-6af2ccaba643

### CODE REVIEW

**Comment by crookedneighbor** [comment]
Seems reasonable to me.

**Comment by crookedneighbor** [comment]
While this fixes the textarea delay, it also adds a little delay between when someone can type a message and press enter to send it so that it creates a blank line _instead_ of sending it. Kind of an edge case, as someone would have to be typing fast and have very little delay between typing a message and pressing enter, but I would find that change confusing.

**Comment by Redmega** [comment]
I type >100wpm when I'm not being lazy so I can see this happening quite often for me.

**Comment by nrbunn** [comment]
Interesting... Thanks for testing. Didn't even think that was a use case since I type then hit the send button. Didn't know enter was also send. Not sure of a quick fix for that. Thoughts?

**Comment by Alys** [comment]
There is this: https://github.com/HabitRPG/habitrpg/issues/4460 "return key causes chat messages to be submitted - should we change that?"  The consensus was that Enter to send the message is not desirable. Maybe we could change that at the same time as fixing the chat delay? Faster chat would be popular and would help to smooth over any complaints about the new behaviour for Enter.

**Comment by nrbunn** [comment]
I updated my pull request with the comments from @Alys. If we change are minds no big deal. Also, when testing i had to add ctrl-enter to the meta-enter line i'm not sure if that was a issue on my side or just my limited knowledge. @crookedneighbor thoughts?

**Comment by crookedneighbor** [comment]
It still has the same problem. There's a delay between when you type and when you can press "meta - enter" to send the message.

**Comment by nrbunn** [comment]
Closing this pull request as I believe I found the root of the issue for #6482 and will need a different fix

**Pull request closed without merging**
