### PR TITLE
Set image-rendering to pixelated

### LINKED ISSUE #5846: Pixel art images should use image-rendering:pixelated
https://developer.mozilla.org/en/docs/Web/CSS/image-rendering

Basically, whenever you zoom in, the browser tries to "correct" the image without knowing it's pixel art, meaning that the image looks kinda jpegy or something. Apparently image-rendering is a new thing that allows you to specify "hey, this is pixel art, don't do any of that magic" and preserves the pixel-artiness of it.

First image is "normal", second is with image-rendering set to pixelated.

nonpixelated
pixelated

### PR DESCRIPTION
**Pull request by RossBrunton**
Closes #5846 , see there for more details.

### CODE REVIEW

**Comment by crookedneighbor** [comment]
Would it make more sense to add this style to the spritesmith css template?

**Comment by RossBrunton** [comment]
Maybe? I'm sorry but I don't quite know my way around your codebase. >_<

I only put it in index.styl because I couldn't find anything more appropriate in website/public/css.

**Comment by crookedneighbor** [comment]
Why don't you just try adding it here and see what happens: https://github.com/HabitRPG/habitrpg/blob/develop/common/css/css.template.mustache

**Comment by RossBrunton** [comment]
Okay, I added them to the "item blocks" or whatever, and it seems to work. However, this does seem to result in a lot of "image-rendering" properties rules in the file, which could be a problem. But anyway, I guess it's your call where best to put it.

**Comment by crookedneighbor** [comment]
I think you're right, it makes more sense to use the `*` version.

There are a bunch of pixel art images in the community guidelines, so instead of applying `image-rendering: auto` to all `img` tags, I created a class to override it where needed and applied it to those images that are not pixel art. 

An alternative solution would be to apply it all img tags, and then have a `img.pixelated` rule that overrides that.

This will count towards a contributor tier! What's your User ID? You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api). Be sure to only copy the User ID and _not_ your API Token.

**Comment by RossBrunton** [comment]
5c84b8fa-8744-4604-9b26-cc90ffcddfbf , thanks.

**Comment by Alys** [comment]
Tier awarded. Thank you @RossBrunton! You can read more about [contributor tiers and rewards here](http://habitrpg.wikia.com/wiki/Contributor_Rewards).

**Pull request merged**
