### PR TITLE
replaced an outdated link //habitrpg.wikia.com

### PR DESCRIPTION
**Pull request by alfill**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
Since http://habitica.wikia.com is the official link, so should not leave outdated links, because some devices may fail to redirect.

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

### CODE REVIEW

**Review by Alys — APPROVED** [review]
Thank you! Well spotted!

**Comment by alfill** [comment]
Well, now the tests have passed.
   So, what will become of all translations /ru /de /es .. /lang (at us faq.json section is fully translated) - the translation of this line on transifex and on the site will be reset due to a small fix changes in the link or there present a smarter algorithm ?

**Comment by paglias** [comment]
>     So, what will become of all translations /ru /de /es .. /lang (at us faq.json section is fully translated) - the translation of this line on transifex and on the site will be reset due to a small fix changes in the link or there present a smarter algorithm ?

I'm not 100% sure but I think if the change affects only a non translatable part of the string Transifex should not invalidate the previous translations but I haven't checked in a long time

**Comment by alfill** [comment]
Ok, I have access to transifex and can report if this happens.

**Comment by SabreCat** [comment]
Thanks much, @alfill! I've noted this toward your next contributor tier and added the Blacksmith title to your account!

**Pull request merged**
