### PR TITLE
[Input Needed] Filter out owned items from User Rewards

### LINKED ISSUE #10049: equipment does not become unpinned when purchased; next gear does not become pinned
As posted by Kajakas (40e9985b-8acb-4110-aeb9-a5946a83a229) in the Report a Bug guild:

**When I buy a piece of class equipment, it stays pinned in the rewards column (and looks as if it's locked) while the next piece of equipment in the series does not automatically get pinned.**

I've confirmed that. If you reload, the bought item disappears and the next one becomes pinned, however the expected behaviour is that as soon as you've bought it, it should become unpinned and then next one should appear without a reload being needed.

### PR DESCRIPTION
**Pull request by Hus274**
Adding an if statment to user rewards to filter out any already owned rewards from the Rewards section of the page when an item is purchased.

[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #10049
### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
I've added an additional condition to the loop of items displayed in the rewards section to filter out any items that are already owned.

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 2a4d30ee-4833-420e-be7c-ad6a6e261c5f

### CODE REVIEW

**Comment by Alys** [comment]
Does this also result in the next item in the sequence appearing?

**Comment by Hus274** [comment]
Ahh it does not. I apologize, I've been struggling to get everything up to date a running and overlooked that section. I'll take a look at that and make the addition here when I'm done.

Sorry for the unneeded back and forth here.

**Comment by Alys** [comment]
No worries, it's cool. :)

**Comment by Hus274** [comment]
So after scratching my head over this for a good chunk of time, it looks like the root of the problem is surfacing from here:
https://github.com/HabitRPG/habitica/blame/develop/website/client/store/actions/shops.js#L21-L24 and is looks like an extension of the issue reported in #9797. 

From my research, it actually looks like the core of the problem is that the API isn't returning the new view of the user.pinnedItems from the server to the client. I can only see three options remaining at the moment:
1. Duplicate [this server side logic](https://github.com/HabitRPG/habitica/blob/develop/website/common/script/ops/buy/buyGear.js#L55) on the client side to keep the client view in sync
2. Force a refresh of the page after a purchase
3. Update the server to returned the pinnedItems view [here](https://github.com/HabitRPG/habitica/blob/develop/website/common/script/ops/buy/buyGear.js#L79)

I think that option three is the right solution here to minimize the code duplication and prevent the client view and client code from getting out of sync with the server but I wanted to make sure there weren't any major concerns with adding an additional value to the return of the request on the API before I moved forward with that.

Let me know your thoughts!

**Comment by Hus274** [comment]
I've reworked this problem in #10085. Closing this one in favor of the other. Had to close this because I needed to get a clean clone from github.

**Pull request closed without merging**
