### PR TITLE
[API v3] rename buyPotion / buy-potion to buyHealthPotion / buy-health-potion

### PR DESCRIPTION
**Pull request by Alys**
### Changes
- renames buyPotion to buyHealthPotion 
- renames buy-potion to buy-health-potion
- fixes an apidoc error (it listed a param for buy-health-potion)

The renaming is to avoid confusion with other types of potions.

If there's conflicts by the time this is reviewed and accepted, I'm happy to fix them.

### CODE REVIEW

**Comment by Alys** [comment]
Renamed to add [API v3] to title

**Comment by paglias** [comment]
@Alys just to be sure, buyPotion was not used anywhere in the client?

**Comment by crookedneighbor** [comment]
More importantly, it's not used in v2 anywhere?

**Comment by paglias** [comment]
@crookedneighbor I _think_, but I'm not sure, that it could have been introduced in v3 while v2 used `buy` for everything

**Comment by crookedneighbor** [comment]
That's true. Forgot about that.

**Pull request merged**
