### PR TITLE
changed gemCost to include the amount of gems

### PR DESCRIPTION
**Pull request by dumindux**
Fixes https://github.com/HabitRPG/habitica/issues/8115
### Changes

Added amount of gems instead of item.value when sent to amplitude.

---

UUID:

### CODE REVIEW

**Comment by lynxlynxlynx** [comment]
Looks good to me, all the code paths quarter the price before.

**Comment by crookedneighbor** [comment]
What's your User ID? You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api). Be sure to only copy the User ID and _not_ your API Token.

**Comment by dumindux** [comment]
my user id is 5fc49b3a-752c-4d35-9f73-287e19fdc96b

**Comment by crookedneighbor** [comment]
Notated toward your next tier.

**Pull request merged**
