### PR TITLE
Fixes Purchase contributor equipment (fixes #9179)

### LINKED ISSUE #9179: new Contributor equipment is not able to be purchased after a contributor tier is awarded
When a contributor is given Tier 2, 3, 4, or 5, one of their [Contributor Rewards](http://habitica.wikia.com/wiki/Contributor_Rewards) is a piece of equipment, which they need to buy for gold.

They should be able to buy it by going to Shops > Market and selecting "None" from the 'Class" drop-down list. The equipment should appear there for purchase with gold because of this `canOwn` code:
https://github.com/HabitRPG/habitica/blob/5ced47f590a042e183de2ebf8770be77f730c039/website/common/script/content/gear/sets/special/special-contributor.js#L43
(and of course similar code for the other contributor gear pieces).

However that's broken. There is currently no way that a contributor can buy the contributor gear they've earned.

----

_Any Blacksmith who works on this issue can ignore the paragraph below._

_I believe this has been broken since the new website went live and we've given several players contributor tiers since then so they're all missing their gear. Admins can fix that by doing a database search/repair for all contributors, but until we have time to do that, anyone who's missing equipment they've earned can report it in the Report a Bug guild and we'll fix it for them. That fix will be done by giving them the gear with a `false` value, as if they'd previously bought it and then lost it due to death, so they'll then be able to buy it with gold as normal._

### PR DESCRIPTION
**Pull request by pineapple-joe**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes https://github.com/HabitRPG/habitica/issues/9179

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
Add functionality for the user to purchase contributer and backer gear, while
keeping the current functionality that shows the lost items due to death in the None category.

[//]: # (Put User ID in here - found in Settings -> API)

----
UUID: f011fa04-2a3a-454f-a048-1b41ba66b340

### CODE REVIEW

**Comment by paglias** [comment]
@borisabramovich86 the code looks great, could you add some tests for the functionality? Let me know if you have any question or need help. And sorry for the delay!

**Comment by pineapple-joe** [comment]
sure, I'll add some tests, no problem

**Comment by pineapple-joe** [comment]
@paglias 
Hey, I added the test.
I think it reflects the changes made.

I also wanted to add an expect to check that the previously owned gear lost due to death
also appears in this category, but I couldn't get around the lint check:

**error  Identifier 'weapon_armoire_basicCrossbow' is not in camel case**

when trying to add the item to items.gear.owned.

**Comment by paglias** [comment]
@bobbyroberts99 regarding

> error Identifier 'weapon_armoire_basicCrossbow' is not in camel case

you can disable that error by writing a comment next to the affected line with `//eslint-disable-line camel-case`

**Comment by Alys** [comment]
@borisabramovich86  How are you going with this? Do you have any other questions for us or need any more advice?

**Comment by pineapple-joe** [comment]
Hey,
added the addition to the test that checks that previously owned 
items lost due to death will also show in this category (using the eslint line disable).

**Comment by negue** [comment]
@borisabramovich86 could you pull latest changes from `develop` and ping me once you did, then I'll test it asap

**Comment by paglias** [comment]
hey @borisabramovich86 how are you doing on this?

**Comment by pineapple-joe** [comment]
@paglias @negue  Hey, did a merge from develop.

**Comment by TheHollidayInn** [comment]
Sorry for the delay on this! So, I've tested this locally and the crystal items are showing. However, when I click and item, the buy button is disabled. Is that happening for you as well?

screen shot 2018-01-04 at 11 20 43 am

**Comment by Alys** [comment]
@TheHollidayInn The Crystal gear costs 200 GP each so the problem there might be that you don't have enough gold.

**Comment by TheHollidayInn** [comment]
Emarassing.... lol thank you. This looks good then!

**Comment by SabreCat** [comment]
Added as credit toward Blacksmith tier 3! Thanks @borisabramovich86 !

**Comment by Alys** [comment]
I'm testing this on our staging server and it does let you buy the contributor gear but the item doesn't disappear from the Shop until you reload. I've logged it here: https://github.com/HabitRPG/habitica/issues/9797
However this bug might come from different code than in this PR because we've merged quite a few PRs recently. @SabreCat or @borisabramovich86 Did you notice this behaviour in local testing for this PR? If not, we can look elsewhere for the source of it.

**Comment by SabreCat** [comment]
@TheHollidayInn would be the one who did the local testing. Definitely something we'll want to address before sending things live, regardless.

**Comment by TheHollidayInn** [comment]
From Alys' notes it seems that the issue is she  purchasing for the first time rather than after death (this PR is the death use case). I'll review her issue again and post a fix.

**Pull request merged**
