### PR TITLE
Make eyewear re-purchaseable if lost

### PR DESCRIPTION
**Pull request by Ozzystrasza**
Fixes https://github.com/HabitRPG/habitrpg/issues/7714
### Changes

Following @SabreCat 's comment on the issue, I added:
`canOwn: ownsItem('eyewear_special_*color*TopFrame')` to each of the eyewear so they can be re-purchaseable in case they are lost.

---

UUID: 8389891a-ba52-4580-b08b-2cb706c7e0b4

### CODE REVIEW

**Comment by crookedneighbor** [comment]
I wonder why this doesn't cover that: https://github.com/Ozzystrasza/habitrpg/blob/944d7f9262b0f87cd1cf4ad32c9e03a6d1dc938b/common/script/content/gear/index.js#L75

**Comment by Ozzystrasza** [comment]
Won't that cover only Take This items, and items in the mystery category?

**Comment by crookedneighbor** [comment]
You are right, I misread the `if` there.

**Review by crookedneighbor — APPROVED** [review]
:+1:

**Comment by crookedneighbor** [comment]
Tier awarded! You can read more about [contributor tiers and rewards here](http://habitrpg.wikia.com/wiki/Contributor_Rewards).

Note that as your tier increases, it takes progressively more work to achieve the next one, so for the higher tiers, larger PRs or a few PRs are required. There's some information about that at Contributor Rewards, but feel free to ask here if you have questions!

**Comment by Ozzystrasza** [comment]
Thank you! :smile:

**Pull request merged**
