### PR TITLE
new audio theme from LuneFox

### PR DESCRIPTION
**Pull request by Alys**
This adds LuneFox's new audio theme (quiet version).
Ref: https://trello.com/c/tljx8gKC/18-music-sound-effects-v3 (2015 Sep 6 entries)

It also sorts the themes alphabetically in the drop-down list (and in other backend code for consistency), and removes unnecessary permissions from the Watts' Theme files.

screen shot 2015-09-12 at 10 48 23 am

### CODE REVIEW

**Comment by LuneFox** [comment]
And here I am! Just figured out how some things work here. If you have any questions (aside from those that I answered on Trello), we can discuss them :)

**Comment by Alys** [comment]
@LuneFox I've awarded you a contributor tier for this.

**Comment by LuneFox** [comment]
@Alys Thanks! I'll gladly help with something else later.

**Comment by Alys** [comment]
@LuneFox Fantastic! Drop in to the Aspiring Coders guild if you ever have any questions.

**Comment by LuneFox** [comment]
@Alys Alright :) I think I'll go help with some translations on Transifex meanwhile. At first I thought that I can directly pull my translations here but then noticed the translations trello card.

**Comment by LuneFox** [comment]
By the way, I meant the Chat sound to be the Bailey's announcement sound, cause it was described so on the wiki. ( http://habitica.wikia.com/wiki/Audio ). I guess we'll need to do some fixes after more general sound patterns are added. Maybe I need to make a really short "Chat" sound.

**Comment by Alys** [comment]
Thanks for that comment about the Chat sound, LuneFox. I've fixed the wiki page and dropped a note into Trello.

**Pull request merged**
