### PR TITLE
moving developer-only strings to api/common messages

### PR DESCRIPTION
**Pull request by negue**
Splitting the messages lib between api and common

based on #10188 
ref #8574

### CODE REVIEW

**Comment by paglias** [comment]
This look good, can you add an explanation of why the strings are split with comments on apiMessages and commonMessages? I think people will find it a bit confusing that some

**Comment by paglias** [comment]
Can you fix the conflicts here?

**Comment by negue** [comment]
@paglias fixed

**Comment by paglias** [comment]
@negue I think this needs one last change to account for your PR that refactored purchasing gems :) after that we can merge

**Pull request merged**
