### PR TITLE
HabitRPG Docs Project

### PR DESCRIPTION
**Pull request by AndreCaseyScott**
Initial commit that explains a little about the HabitRPG Docs Project and how to get involved. 

Was going to have folks submit pull requests to my fork, but submitting to this branch seems cleaner and less confusing.  

@lefnire If you can merge this one, I will treat that as "sign off" to commit future pull requests to this branch myself. Figuring this out as I go.

### CODE REVIEW

**Comment by lefnire** [comment]
this looks great. I noticed you're PR-ing against lefnire:docs-project, is the plan to hit that branch until it's beefed up enough to stand substantially on it's own, and then merge to develop? When that time comes, we'll want to move everything out of the Github wiki and into the codebase, so there's not multiple locations for things. We'll also need to deploy this documentation online somewhere since people will need to access the docs publicly (as they do the API information in the wiki currently)

**Comment by lefnire** [comment]
oh wait, maybe i'm wrong - this is just for generating the documentation _on the code_, eh? got it.

**Comment by AndreCaseyScott** [comment]
@lefnire It **would** be possible to move all the wiki content _and_ code documentation to one place. 

If we move the wiki content to markdown files, they could be stored (and version controlled) in the repo. They would be generated along with the code documentation automatically via Grunt. The other benefit of this is that all wiki content could be edited on GitHub, simplifying account management. @paglias mentioned in #1558 that anything put under /public can be reachable by habitrpg.com. The generator would simply output the html files to subfolders under /public and make them live.

And yes, I want to work under the `docs-project` branch for now. Especially since me and whoever else will be editing the actual .js files served, I don't want to risk anything breaking on the live master/develop branches due to a misplaced /\* . We can merge whenever a quick test of the branch checks out. Sound good?

Curious, how often does `grunt build` get ran on habitrpg? #noob

**Comment by paglias** [comment]
About grunt build, it is run every time new code is deployed to the server
but it's not grunt build it's grunt build:dev or grunt build:prod for the
server
Il giorno 24/set/2013 06:09, "onduhray" notifications@github.com ha
scritto:

**Comment by AndreCaseyScott** [comment]
Oh okay! When I get the grunt task set up, I'll look into whether the docs should be generated only on dev or on both.

**Comment by paglias** [comment]
I would go with production only but if it's fast enough and doesn't slow
the build process too much it's OK also to add it to build:dev

**Pull request merged**
