### PR TITLE
Flagged chat messages are visible to the users that posted them

### LINKED ISSUE #8639: flagged chat messages need to remain visible to the person who posted them
When a chat message is flagged by two players or by one moderator, the current behaviour is:
- the message is hidden from the player who posted it **(this needs to change)**
- the message remains visible to moderators
- the message is hidden from all other players

The desired behaviour is:
- **the message remains visible to the player who posted it**
- the message remains visible to moderators (as currently)
- the message is hidden from all other players (as currently)

The player who posted the message should see no indication that it has been flagged.

_FYI, this is a change that moderators have discussed and decided is desirable. In most cases, we'll be explaining to the poster that their message has been hidden from other users and explain why, as we do now. In rare cases though, it's best that the user doesn't realise their message is hidden._

### PR DESCRIPTION
**Pull request by librarianmage**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #8639

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

Images incoming

[//]: # (Put User ID in here - found in Settings -> API)

----
UUID:

### CODE REVIEW

**Comment by librarianmage** [comment]
Ping!

**Comment by TheHollidayInn** [comment]
Works great! 

However, we do need the transparent class to show to the user who has been flagged as well: https://github.com/HabitRPG/habitica/blob/develop/website/views/options/social/chat-message.jade#L10.

**Comment by MathWhiz** [comment]
> In rare cases though, it's best that the user doesn't realise their message is hidden.

Am I misunderstanding this?

**Comment by librarianmage** [comment]
@TheHollidayInn It seems that there should be no indication that it has been hidden to the user:

> In rare cases though, it's best that the user doesn't realise their message is hidden.

Am I misunderstanding this?

**Comment by TheHollidayInn** [comment]
Okay, I spoke with Alys and Lemoness and they corrected me. This looks good then. Thanks :D

**Comment by librarianmage** [comment]
Yay!

**Comment by TheHollidayInn** [comment]
Congratz on Tier 6!

**Comment by librarianmage** [comment]
ヽ(⌒∇⌒)ﾉ

**Pull request merged**
