### PR TITLE
Improved Party and Guild page UI

### LINKED ISSUE #9877: Party's page improvement
Small improvements in the design, you can accepts them? I showed on the screenshots.

Before:
image

After:
image

### PR DESCRIPTION
**Pull request by lex111**
Fixes #9877

### CODE REVIEW

**Comment by lex111** [comment]
Why Travis fails?

**Comment by paglias** [comment]
It happens sometimes, don't worry about it. Can you post a screenshot of the before and after?

**Comment by lex111** [comment]
Before

image

After
image

**Comment by paglias** [comment]
Thanks, we'll review it in the next few days

**Comment by negue** [comment]
LGTM 👍

**Comment by SabreCat** [comment]
Awesome! This was part of your tier 2 Blacksmith credit.

**Pull request merged**
