### PR TITLE
Add tooltip to character buff icon

### PR DESCRIPTION
**Pull request by ESWAT**
### Changes
Add tooltip to character buff icon. Makes it clearer what this icon is if the user hovers over it.

----
UUID: ffee6b77-0bf8-422a-a65c-c20de17f2b32

### CODE REVIEW

**Comment by paglias** [comment]
Hey @ESWAT, thanks for the PR but I'm going to ping our designer to see if this is wanted and in case it's maybe we want to apply it to more than a single icon? @Tressley

**Comment by paglias** [comment]
Can you also post a screenshot of how this looks? Thanks

**Comment by ESWAT** [comment]
@paglias I revised this branch to use a `tooltip` instead of `title` attribute, the intention is to display a clearer explanation of what this icon is.

screen shot 2018-03-24 at 20 54 47

**Comment by Tressley** [comment]
@ESWAT -- Awesome work on this! Is it possible to add this to Task icons? Icons that need this are:

- Options
- Streak
- Due Date
- Challenge
- Broken Challenge

cc @paglias

**Comment by ESWAT** [comment]
@Tressley I added tooltips for Streak, Challenge and Broken Challenge, however:

- I’m not sure what you mean by _Options_
- I don’t believe Due Date needs a tooltip… seems the text itself makes it clear what it is
- We might need new locale strings for Challenge and Broken Challenge (I’m using _Challenge_ and _Broken Challenge Link_ currently)

**Comment by Tressley** [comment]
@ESWAT -- Great! Let me see if I can help. "Options" is the three dot icon that appears when you hover a Task. While you're correct in "Due Date" being fairly intuitive, we're aiming to establish a UX pattern with these tooltips. If all of the icons but the Due Date has a hover state on a Task, a user may perceive this as an error.

**Comment by ESWAT** [comment]
@Tressley OK added those. I used _Show More_ for the text for the options icon since there isn’t an existing one for the word _Options_.

**Comment by paglias** [comment]
@ESWAT in that case it's fine to add a new string for "Options" in common/locales/en unless @Tressley thinks that Show more is fine.

Also the show more is appearing at the top, not sure if this is okay @Tressley 

schermata 2018-03-31 alle 13 15 02

**Comment by ESWAT** [comment]
@paglias @Tressley I decided to put it up top because it would block the display of the options menu a bit if the player didn’t move their pointer. Admittedly it does looks a bit weird like this.

**Comment by negue** [comment]
@Tressley we could also show the challenge name and not just "challenge" , what do you think?

If `challenge` should be kept then its ready to be merged 👍

**Comment by ESWAT** [comment]
FWIW I tried looking at moving the _Show More_ tooltip to the bottom and dismissing it when you click on the menu, but it doesn’t seem emitting `bv::hide::tooltip` does anything when the tooltip to hide is invoked by hover?

**Comment by ESWAT** [comment]
@negue @Tressley I like the idea of putting the challenge name in the tooltip, so will explore that today or tomorrow.

**Comment by Tressley** [comment]
@ESWAT -- Love the idea of using the Challenge name. Good idea! I think the tooltip appearing above is fine. We have some tooltip positioning hiccups currently. 👍

**Comment by SabreCat** [comment]
Thanks for this, @ESWAT! Noting toward your next contributor tier!

**Pull request merged**
