### PR TITLE
Remove Docker from Gruntfile. Also rename Docs Readme.

### PR DESCRIPTION
**Pull request by AndreCaseyScott**
Last bit that wasn't supposed to make it to develop yet. The docker config in the gruntfile had the potential to not only slow down builds, but fail if docker was not installed. removed until further testing is done.

### CODE REVIEW

**Comment by AndreCaseyScott** [comment]
Ahh, just noticed that both docker and grunt-docker made it into the package.json. Should be fine, especially since it won't be run on each build with the gruntfile config removed.

**Comment by paglias** [comment]
Docker also requires python pygments to be installed.

Also, I'm not following why some pull requests are for the develop branch and others for the docs-working branch. All the docs related files can be removed from the develop branch?

**Comment by AndreCaseyScott** [comment]
### Branches

This pull request removed the Docker config from Develop, which is still lingering. It may cause issues or long build times. None of the doc stuff should be in develop, but the comments in User.js are benign. The rest of the work has been in the `docs-project` branch. My fork is `docs-working` simply because there was already a `docs-project` and I didn't want to bother with it since git was complaining at me about it.

### Eff Pygments

Arrrg. I must have installed pygments locally at sometime, which is why I didn't notice that requirement. I noticed a node module for pygments, but Docker looks specifically for the `pygmentize` cli app. Seems Groc also uses pygments. Not having a requirement on pygments would be ideal, as the primary documentation is generated on the server.  

Aside from attempting to hack Highlight.js into Docker, our other options are [Citare Scriptum](https://github.com/druide/citare-scriptum) (a fork of groc, seems promising), hacking a Table of Contents into [Docco](http://jashkenas.github.io/docco/), or attempting to use something like YUIDocs. There might be others, but most of the other projects I've found are orphanware. Hell, they all seem pretty alpha. _**sigh**_

It seems my initial fear of spending more time on the _tools_ instead of actually _working_ on learning and documenting the code has been actualized. I'm starting to wonder if trying to generate documentation from the code comments [is even the right approach to take](http://blog.millermedeiros.com/inline-docs/)...

Maybe utilizing GitHub Pages/Jekyll is an option? Or an official wiki? Something that can be pointed to via the habitrpg.com domain. Github seems like a good central place, especially since it can be versioned right along side the code. There are some markdown generators for grunt, [this one](https://github.com/treasonx/grunt-markdown) was the best I found so far. 

Being a newbie to javascript myself, the biggest challenge I have is trying to understand the structure of the app, and where each file/function is used and how. I'm imagining a flow chart, but I think the same effect could be done by providing links to where each thing is called. 

**Goal of Documentation:** Provide a reference for developers to easily understand the structure the app, thus easing the onboarding of new developers.

I'm trying to keep this goal in mind while figuring out a solution to this.

**Comment by AndreCaseyScott** [comment]
I'm leaning towards a more abstracted approach, given some of the arguments of that link before. It had the potential to overly bloat the code, requiring larger downloads. Plus anyone developing with already have the code anyways.

Thus using github pages and Jekyll is a very attractive option. I'm already familiar with some yaml and markdown, and could tweak the frontend however needed. One less account and site to manage, since it will all be on github.

@lefnire is habitrpg using github pages at already? Anyway we could point something to them, if we use them? Thinking we could have the option of editing the files directly, or using prose.io for less techy folk.

**Comment by paglias** [comment]
no it's not using github pages.

But I don't see the need to use them, you can just generate the site locally via jekyll (maybe a node alternative would be better) and upload it to /public folder.

As for my previous comments, yes it removes docker from grunt but it's still being installed in the develop branch.

**Comment by paglias** [comment]
and also it adds that DOCS-README file on the develop branch, why?

**Comment by AndreCaseyScott** [comment]
I figured adding the DOCS-README to develop would be nice, since someone who checks out the develop branch might stumble upon it and pitch in.

As to the github pages, I have a few reasons why using GitHub pages would be preferred:
1. GitHub Pages has the benefit of non-techie friendly editing (via Prose.io), which would mean non-techies could edit and update the pages easily. (The docs will be developer centric for now, but the same setup could also be used for the official generalized docs for HabitRPG.)
2. One less dependency requirement for HabitRPG, since all the compiling would be done by GitHub.
3. GitHub Pages are stored in a separate branch (gh-pages) with no other code in that branch. Cleaner separation between the App and the Docs.

The downsides:
1. Extra domain pointer setup in GitHub
2. Doesn't integrate with node (but does it need to?)

Either way, the content will be in markdown (as I see it) so it is pretty system agnostic. At this point, I'm going to focus on actually documenting stuff over in #1318 which (since its markdown) can just me copied over to whatever system we use. A lot of this depends on whether Habit plans to have an officially hosted docs/wiki, because developers are more tolerant of installing extra stuff and working cli than non-tech folk. If it's just for JS and CSS files then whatever requires less work for @lefnire :P 

That said, I did find [Wintersmith](http://wintersmith.io/), which has a couple of benefits:
1. Node based
2. It's a production version ([2.0.7 as of writing](https://npmjs.org/package/wintersmith)) 
3. Uses stylus and jade, which Habit is already using.

**Comment by AndreCaseyScott** [comment]
I totally forgot about the dependencies, my bad. Removed.

**Pull request merged**
