### PR TITLE
fix(vagrant): add graphicsmagick to vagrant provisioning

### PR DESCRIPTION
**Pull request by thepeopleseason**
See #3700 for more details.

### CODE REVIEW

**Comment by Alys** [comment]
This is likely failing because it's expecting y/n input, which of course it can't get when it's being run automatically. I'm sorry - I should have realised that would happen. :(

I'm working on the vagrant.sh script on my machine to try to remove many of the warnings, errors, and timeouts, with a fair bit of success so far, and I think the graphicsmagick and phantomjs warnings are amongst the ones I'm having success with. I'm hoping to make some suggestions for script changes in a few days at most.

**Comment by thepeopleseason** [comment]
Hmmm... The -qq should take care of that issue.

**Comment by Alys** [comment]
I think -qq just suppresses non-error output. I'm having success with
"--assume-yes --force-yes" but am still testing to see if both are needed.

**Comment by thepeopleseason** [comment]
@Alys: -q suppresses output. With a second q, it implies -y.

**Comment by lefnire** [comment]
Should I merge this? (sorry, I don't use the vm - can't gauge the merge status from y'all's convo)

**Comment by thepeopleseason** [comment]
Given that Alys is working through a lot of the error messages, I think we can hold off on this one until she's done.

**Pull request closed without merging**
