### PR TITLE
Make text in options/settings translatable

### PR DESCRIPTION
**Pull request by ksami**
Make some of the strings in #4522 translatable

### CODE REVIEW

**Comment by ghost** [comment]
@ksami I'm glad you've figured everything out. Seems like nice job! It's usually a good idea to post a screenshot before changes and a screenshot after changes to show there are no visual changes and everything works as expected. I'm not a mod but they usually do ask for such screenshots before merging a commit that can introduce visual changes...

**Comment by crookedneighbor** [comment]
Screenshots are helpful because we have some non-developers on staff who review changes.

**Comment by ksami** [comment]
Got it, here are the screenshots.

old
new

**Comment by crookedneighbor** [comment]
Looks great. Made two adjustments:

https://github.com/HabitRPG/habitrpg/commit/1a2510e4daf73dcee3595edc7762f80d246197e1
https://github.com/HabitRPG/habitrpg/commit/9ad1dbd8ceb0fce9ab3df70e41f3fba7923f7854

This will count towards a contributor tier! What's your User ID? You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api). Be sure to only copy the User ID and _not_ your API Token.

**Comment by ksami** [comment]
Nice thanks! My User ID is 038446f8-face-4366-94b3-0114fde7d5c3

**Comment by crookedneighbor** [comment]
Tier awarded! You can read more about [contributor tiers and rewards here](http://habitrpg.wikia.com/wiki/Contributor_Rewards).

Note that as your tier increases, it takes progressively more work to achieve the next one, so for the higher tiers, larger PRs or a few PRs are required. There's some information about that at Contributor Rewards, but feel free to ask here if you have questions!

**Pull request merged**
