### PR TITLE
update user and group in a transaction when creating a group. fixes #12124

### LINKED ISSUE #12124: guild creation failing, gems being taken
Recently we've seen two reports of people trying to make a guild, having their Gems removed, but the guild not existing.

This one from @Muamua_ (1039bae3-1101-4c9f-8ad1-416b04ecd93d) was 15 hours before now:
_"Then I logged in on website version and create guild but it occur error. After that, my gems disappeared but my guild didn't created.."_

This one from @tymeczekxpompa (1e3a7b23-5fde-44d5-b742-12e848f93f4d) was from 10 days ago:
_"When I was creating the private guild and clicked "create a guild" button an error happened which took my 4 gems but hasn't created any guild."_

In both cases I found a group ID in their `guilds` array that did not correspond to a guild that currently exists (ca200a70-1f0f-48f3-8423-4ed02c8b05bb and 2d69ff05-e763-488a-9706-b3a0f9bed748 respectively). Those IDs are still there but we should remove them eventually.

The Amplitude/Loggly event type for creating a guild is `json.event_type:"join group"` ([code ref.](https://github.com/HabitRPG/habitica/blob/d03e5e93b09f5a16598ed63b911c074d28c62368/website/server/controllers/api-v3/groups.js#L167)), i.e., the same as for joining a guild, however it would have `json.event_properties.owner:"true"` (true rather than false). I haven't found such a record in Loggly for @Muamua_, except for one from a few minutes ago (2020-04-26 04:00:12.240) which was after I gave them Gems and told them to true again. Either their failed attempt happened before that data started to go into Loggly, or (more likely) the guild creation failed before it got to the point where analytics were recorded.

I haven't found Loggly errors associated with this but I have **not** searched thoroughly. We probably should, I'm just a bit short of time today.

I've given 4 Gems to both of those people.

----

With PR #12335 the Habitica codebase has been updated to support MongoDB 4.2 and transactions making it possible to fix this issue. 

Transactions allow operations on multiple documents to be executed ensuring that either all of them are executed correctly or none, making it possible to fix this issue.

An example on using transactions can be found at https://mongoosejs.com/docs/transactions.html while more info at https://docs.mongodb.com/manual/core/transactions/. If you want to work on this issue and have any question please leave a comment!

### PR DESCRIPTION
**Pull request by Cred1Tor**
fixes the issue when the user might lose gems even if the group creation fails

[//]: # (Note: See https://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #12124

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

added a transaction in POST /groups route for updating the user and the group as a single op. i didn't use session.withTransaction() or mongoose's connection.trasaction() helpers because they won't work for me for some reason. i tried the code from https://github.com/HabitRPG/habitica/pull/12986 and it's not working, the user is still getting updated if you throw inside a transaction

also replaced Promise.all with two separate awaits because otherwise it's not working for some reason. e.g. this code:

```const results = await Promise.all([user.save({ session }), group.save({ session }), Promise.reject(new Error('boom'))]);```

won't work, even though it goes to the catch block before reaching `session.commitTransaction()`, but the changes aren't reverted for some reason, the gems will deplete and the group will get created anyway. maybe someone can shed some light on it, because i don't know what's going on here

also it seems like the previous PR for this was declined due to no unit test, but i don't know how to write one for a failing transaction, you'll have to simulate an error when saving a group somehow. but i tested it manually on a local setup and it works, including aborting transaction if i throw an error before udating the group, so the gems don't disappear

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: ad0e2e64-91bf-4c50-9b46-2f24ca06abe1

### CODE REVIEW

**Comment by Cred1Tor** [comment]
so this manual method wasn't retrying the transaction in case of Transient Transaction errors hence the failed test.
i used mongoose transaction helper to deal with those and it seems to be working fine, but there are a two problems:
the test now takes too long to run, as a temporal solution i increased the test timeout to 30s, but it's still failing and i have no idea what's going on there, i added some console.log outputs, mb someone can tell what's going on there?

edit: actually, i just checked and that test is failing even on the develop branch so it shouldn't be related with this fix

**Comment by Cred1Tor** [comment]
nvm, i just realized that the failing test was dependent on other tests and it was failing because i was running it with .only
otherwise it passes

**Comment by Cred1Tor** [comment]
is this getting reviewed?
also i wanted to add: i found a way  to save both a user and a group in parallel, you just have to use Promise.allSettled instead of Promise.all and normally it works, but just in that tests where a lot of groups are created quickly it puts out WriteConflicts, i don't know what's up with that
otherwise, if we're updating group and user one after another, then that tests times out, i can increase the timeout period and it'll pass

**Comment by SabreCat** [comment]
hmm, it does seem that one test is consistently timing out on this branch... we do have a few things that error sporadically and are OK on a re-run of the workflow, but if it never runs clean that does mean the PR's not mergeable. If you try your `allSettled` approach and space out the group creation with a small delay, can you dodge the WriteConflicts that way? That should just be part of the data prep for the test, it's not an important test case in itself..

The prior PR was dropped less because of no unit test than that the contributor said "I'd like to write a unit test, where should I put that" but stopped responding, ha. That said, for simulating an error in a unit test, I'd look to `sinon.stub().throws`!

**Comment by SabreCat** [comment]
Also, is there documentation of the `db.transaction` pattern without `startSession` I can peek at? Looking at the Mongoose docs, I thought manually starting a session was mandatory, but maybe not!

**Comment by Cred1Tor** [comment]
> Also, is there documentation of the `db.transaction` pattern without `startSession` I can peek at? Looking at the Mongoose docs, I thought manually starting a session was mandatory, but maybe not!

[here](https://mongoosejs.com/docs/transactions.html) you can see some examples of `session.withTransaction()` and `db.transaction()`

[here](https://mongoosejs.com/docs/api/connection.html#connection_Connection-transaction) is the doc reference for the method itself

in [this article](https://docs.mongodb.com/manual/core/transactions-in-applications/) you can see an example of manually retrying transactions, i tried copying that code but it didn't work for some reason, i didn't dig to deep into that since the helpers are working and it'd probably lead to the same issues anyway

i'll work on the code tomorrow

**Comment by SabreCat** [comment]
Right, those are the same docs I was looking at, which say

> To create a transaction, you first need to create a session using or [sic] `Mongoose#startSession` or `Connection#startSession()`.

...which it looks like the prior PR did, but not in your code? Maybe I'm misunderstanding something, I am not a smrt codr sometimes >.<

**Comment by Cred1Tor** [comment]
> Right, those are the same docs I was looking at, which say
> 
> > To create a transaction, you first need to create a session using or [sic] `Mongoose#startSession` or `Connection#startSession()`.
> 
> ...which it looks like the prior PR did, but not in your code? Maybe I'm misunderstanding something, I am not a smrt codr sometimes >.<

this is the manual method using which you'd have to implement additional logic for dealing with transient transaction errors, you can read about them [here](https://stackoverflow.com/questions/52153538/what-is-a-transienttransactionerror-in-mongoose-or-mongodb). there's information about the helpers that deal with that under the hood in same doc you're referring to:

> In practice, you should use either the session.withTransaction() helper or Mongoose's Connection#transaction() function to run a transaction. The session.withTransaction() helper handles:
> 
> Creating a transaction
> Committing the transaction if it succeeds
> Aborting the transaction if your operation throws
> Retrying in the event of a transient transaction error.

and afair i was getting those errors when manually creating a session and commiting a transaction

also there's some more info on transaction error handling [here](https://docs.mongodb.com/manual/core/transactions-in-applications/#transaction-error-handling)

**Comment by Cred1Tor** [comment]
so i tried this code with various delays:

```
    const delay = () => new Promise(resolve => setTimeout(resolve, 100));

    try {
    await Group.db.transaction(async session => {
      const promises = [user.save({ session })];
      await delay();
      promises.push(group.save({ session }));
      const results = await Promise.allSettled(promises);

      results.forEach(result => {
        if (result.status === 'rejected') {
          throw new Error(result.reason);
        }
      });

      savedGroup = results[1].value;
    });
  } catch (e) {
    console.log(e);
    throw e;
  }
```

it's still generating WriteConflicts:

```
    public guilds pagination
Error: MongoError: WriteConflict
    at /home/creditor/projects/habitica/website/server/controllers/api-v3/groups.js:1:71339
    at Array.forEach (<anonymous>)
    at /home/creditor/projects/habitica/website/server/controllers/api-v3/groups.js:1:71192
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at handler (/home/creditor/projects/habitica/website/server/controllers/api-v3/groups.js:1:70855)
Error: MongoError: WriteConflict
    at /home/creditor/projects/habitica/website/server/controllers/api-v3/groups.js:1:71339
    at Array.forEach (<anonymous>)
    at /home/creditor/projects/habitica/website/server/controllers/api-v3/groups.js:1:71192
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at handler (/home/creditor/projects/habitica/website/server/controllers/api-v3/groups.js:1:70855)
Error: MongoError: WriteConflict
    at /home/creditor/projects/habitica/website/server/controllers/api-v3/groups.js:1:71339
    at Array.forEach (<anonymous>)
    at /home/creditor/projects/habitica/website/server/controllers/api-v3/groups.js:1:71192
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at handler (/home/creditor/projects/habitica/website/server/controllers/api-v3/groups.js:1:70855)
Error: MongoError: WriteConflict
    at /home/creditor/projects/habitica/website/server/controllers/api-v3/groups.js:1:71339
    at Array.forEach (<anonymous>)
    at /home/creditor/projects/habitica/website/server/controllers/api-v3/groups.js:1:71192
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at handler (/home/creditor/projects/habitica/website/server/controllers/api-v3/groups.js:1:70855)
Error: MongoError: WriteConflict
    at /home/creditor/projects/habitica/website/server/controllers/api-v3/groups.js:1:71339
    at Array.forEach (<anonymous>)
    at /home/creditor/projects/habitica/website/server/controllers/api-v3/groups.js:1:71192
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at handler (/home/creditor/projects/habitica/website/server/controllers/api-v3/groups.js:1:70855)
Error: MongoError: WriteConflict
    at /home/creditor/projects/habitica/website/server/controllers/api-v3/groups.js:1:71339
    at Array.forEach (<anonymous>)
    at /home/creditor/projects/habitica/website/server/controllers/api-v3/groups.js:1:71192
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at handler (/home/creditor/projects/habitica/website/server/controllers/api-v3/groups.js:1:70855)
Error: MongoError: WriteConflict
    at /home/creditor/projects/habitica/website/server/controllers/api-v3/groups.js:1:71339
    at Array.forEach (<anonymous>)
    at /home/creditor/projects/habitica/website/server/controllers/api-v3/groups.js:1:71192
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at handler (/home/creditor/projects/habitica/website/server/controllers/api-v3/groups.js:1:70855)
Error: MongoError: WriteConflict
    at /home/creditor/projects/habitica/website/server/controllers/api-v3/groups.js:1:71339
    at Array.forEach (<anonymous>)
    at /home/creditor/projects/habitica/website/server/controllers/api-v3/groups.js:1:71192
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at handler (/home/creditor/projects/habitica/website/server/controllers/api-v3/groups.js:1:70855)
Error: MongoError: WriteConflict
    at /home/creditor/projects/habitica/website/server/controllers/api-v3/groups.js:1:71339
    at Array.forEach (<anonymous>)
    at /home/creditor/projects/habitica/website/server/controllers/api-v3/groups.js:1:71192
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at handler (/home/creditor/projects/habitica/website/server/controllers/api-v3/groups.js:1:70855)
Error: MongoError: WriteConflict
    at /home/creditor/projects/habitica/website/server/controllers/api-v3/groups.js:1:71339
    at Array.forEach (<anonymous>)
    at /home/creditor/projects/habitica/website/server/controllers/api-v3/groups.js:1:71192
    at runMicrotasks (<anonymous>)
    at processTicksAndRejections (internal/process/task_queues.js:95:5)
    at handler (/home/creditor/projects/habitica/website/server/controllers/api-v3/groups.js:1:70855)

...and so on
```

if i make a single change of commenting the `{ session }`, like so
```
const promises = [user.save(/* { session } */)];
      await delay();
      promises.push(group.save(/* { session } */));
```

then it works. and obviously it works without the transaction at all, like it is now on the production. so the issue is within the mongoDB itself. i don't know why, but it doesn't like concurrent writing into different collections withing a single session, maybe it's the problem with configuration or something?

again, it does work when waiting for each saving, but then it takes too long and the test's timing out and i'm assuming it wouldn't be the most desirible solution to this

**Comment by Cred1Tor** [comment]
i've implemeted the delay between `generateGroup` calls in the test itself (didn't commit it, just experimenting):

```
it.only('returns 30 guilds per page ordered by number of members', async () => {
      await user.update({ balance: 9000 });
      const delay = () => new Promise(resolve => setTimeout(resolve, 40));
      const promises = [];

      for (let i = 0; i < 60; i += 1) {
        promises.push(generateGroup(user, {
          name: `public guild ${i} - is member`,
          type: 'guild',
          privacy: 'public',
        }));
        await delay();
      }

      const groups = await Promise.all(promises);
```

and it passes in this case, when the delay is high enough. so these write conflicts only occur when there are several threads trying to write to multiple collections under the same session at the same time. and i think this is the only test where it happens?

**Comment by SabreCat** [comment]
All right, let's give this a try in the staging environment at least--I'm curious if this will help!

Added your contributor credit on Habitica. Welcome to the ranks of the Blacksmiths at tier 1!

**Pull request merged**
