### PR TITLE
Grey out skill when insufficient mana fixes #13286

### LINKED ISSUE #13286: Skills are not greyed out when you don't have enough mana
Previously(?) as far as I and the user reporting it remember, tasks used to be greyed out when you didn't have enough mana to cast them. That is no longer the case: I have only 30 mana, but all these skills look usable:

image

This can be confusing for users, though the correct error message does appear.

### PR DESCRIPTION
**Pull request by jasonmishi**
[//]: # (Note: See https://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #13286 

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
Grey out skills when there is insufficient mana.
Before:
image
After when sufficient mana but skill not available:
image
After when not enough mana:
image

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID:4591b9fd-9f56-4a02-b5f0-411ab0dcda8d

### CODE REVIEW

**Comment by SabreCat** [comment]
Code work looks solid! @Tressley what do you think, about the text colors of the mana numbers in particular? Do we want that differentiation between "disabled due to insufficient level" vs "disabled due to insufficient mana", and if so, is this the right way to do it?

**Comment by jasonmishi** [comment]
Hello, just a small clarification, the skill is not "disabled due to insufficient level" in the second picture, but it's disabled because, if I remember correctly, all dailies have been checked off(that skill requires some dailies unchecked I think). A bit nit-picky but might avoid future confusion, thanks!

**Comment by Tressley** [comment]
@jmlcarvalhotech -- This is looking great! Thanks for your work on it. I actually have some designs to account for the states you've outlined above.

**If the user doesn't have the skill due to level:**
- Mana cost is replaced with the level the skill is unlocked
- Tooltip should only say when the skill is unlocked

**If the user doesn't have the skill due to mana:**
- The entire button is visible, but has an opacity of 50%
- The skill should also have the associated tooltip, but not have a hover state (no outline, increased shadow)

image

**Comment by jasonmishi** [comment]
Hello @Tressley apologies because I think my previous comment wasn't very clear, there are 3 states in which skills are disabled, I have put an image below as to how the 3 states look with the changes I've made (I'm hovering over the stealth skill even though you don't see my cursor). The "skill not available" is not changed by this PR. 
habitica skills

Please let me know if any additional changes need to be done, thanks!

**Comment by Tressley** [comment]
No apology necessary! That was a slight oversight on my part.

My only feedback is that when the skill is unavailable, due to not having an effect, the color of the mana cost should be blue-500 (#a9dcf6)

**Comment by SabreCat** [comment]
Should be a simple update to wrap this up, it sounds like--thanks for your patience, @jmlcarvalhotech!

**Comment by jasonmishi** [comment]
Oops forgot about the draft thing, was a bit busy this week, will make the change by Monday, thanks.

**Comment by SabreCat** [comment]
Looks good @jmlcarvalhotech and thanks again for your patience (we were really focused on getting that Teams update out!)

It doesn't look like 4591b9fd-9f56-4a02-b5f0-411ab0dcda8d is a current Habitica user ID, but if you do have a user on the site, let us know and we can get you contributor credit!

**Comment by jasonmishi** [comment]
@SabreCat My user id is 714f488d-1389-4f3c-ad35-bcf97e38ce2d . I think I had put up the user ID of my local by mistake.

**Comment by SabreCat** [comment]
Added to your contributor credit for tier 2! And it looked like you were lacking the "Blacksmith" title before, that should be fixed now.

**Pull request merged**
