### PR TITLE
chore(changelog): add commit-msg hook to verify commit messages

### PR DESCRIPTION
**Pull request by colegleason**
This adds a Git commit-msg hook which runs after a commit message is written. It verifies that is matches a certain spec as defined by the AngularJS document [here](https://docs.google.com/document/d/1QrDFcIiPjSLDn3EL15IJygNPiHORgU1_OOAqWjiDU5Y/edit#). This will allow for automated generation of Changelog.md in the future.

Migration notes: Please run `ln -sf ../../validate-commit-msg.js .git/hooks/commit-msg` to install the commit hook.

### CODE REVIEW

**Comment by colegleason** [comment]
@lefnire @SabreCat @paglias You guys will want to weigh in on this. This would enforce commit messages to fit a certain spec in order to let a script automatically generate CHANGELOG.md. The updates to CHANGELOG.md will be used to generate update to Bailey for users.

This makes it potentially harder to contribute, as we have to tell users to install the git hook. Thoughts?

**Comment by snicker** [comment]
Why don't we restrict generation of CHANGELOG.md to commits only by repo admins as defined by Github? This keeps the barrier to entry low because the average contrib doesn't need to conform, we only have to adjust our commit messages when we merge a PR.

**Comment by colegleason** [comment]
Okay, that will be supported by this current workflow, as you must link the commit-msg hook before it gets used. We just need to remember that commits merged via Github's PR system won't be validated. So if we want those to count, we must be careful to get the spec right. Editing commits after the fact probably won't be ideal as it makes rebasing hell.

The changelog is currently not automatically generated on every commit, although that could be added in another hook.

**Comment by SabreCat** [comment]
I'm not as well versed in this sort of thing as my reputation would lead you to believe--I'm an up-by-the-bootstraps newb who took his first stab at JavaScript on Codecademy less than a year ago--so I don't entirely grok this. Can you lay out what the (new) steps would be for somebody to make a commit or PR if this were implemented?

**Comment by colegleason** [comment]
The idea here (assuming you have the commit hook linked) is that after every time you committed it would check to make sure your commit message looks like the following:

```
type(scope): message title here

The body of the message goes in this section.

BREAKING CHANGE: The footer tells you about breaking changes or Github issues
that this commit closes.
```

Full commit guidelines [here](https://github.com/angular/angular.js/blob/master/CONTRIBUTING.md#git-commit-guidelines).

If it doesn't look something like that it won't commit and you'll have to try again (although the commit message should still be saved so you don't have to retype it).

If you don't have the hook linked, then none of this occurs. That's why @snicker suggests that just the main contributors are required to use it and other people won't have to worry. We would just change their commit message when merging PRs in to fit the spec above.

The motivation for this is that we have another script that goes through and looks at all the commit messages. Any commit message that looks like that gets sorted into the appropriate section and a file called CHANGELOG.md is created. That files tells people what has changed recently. It might look like this:

# Changelog

## 2014-01-17

New Features:
- Added quest system

Bug Fixes:
- Drops are random again (#123456)

Documentation:
- Added docs for new API routes

This is something that is useful when @lemoness is writing blog posts for the Tumblr or @lefnire is adding news to Bailey. Users may want to know about new features (or even bug fixes if they are relevant).

**Comment by SabreCat** [comment]
Ah! Cool, thanks for the clarification. I wouldn't mind using this, assuming I can get the hook link to work (linking has not been kind to me elsewhere). Gives me some habituation to good documentation practice I wasn't aware of.

Couple of questions for the specific implementation in Habit. What would you call content stuff like translations and help text? "style"? And what would be some examples of "scope" that we would use here?

**Comment by colegleason** [comment]
These standards are actually new to me, as I haven't seen these specific ones before.

I'm not entirely sure on what translations count as, that is really up to us. We don't have to stick to those types, I'm happy to add more like `translate()` if needed.

As for scopes, It's really whatever will give everyone else instant context on what it relates to. So when I fix a bug in the Ultimate Gear achievement I used `ultimateGear`. Anything related to CDS might be `dayStart`.

**Comment by colegleason** [comment]
Oh, and to link you just need to be careful about relative stuff. Since you
are linking to the .git/hooks directory, the link is `../../FILENAME` since
you are jumping up two dirs.

On Thu, Jan 16, 2014 at 8:00 PM, Sabe Jones notifications@github.comwrote:

> Ah! Cool, thanks for the clarification. I wouldn't mind using this,
> assuming I can get the hook link to work (linking has not been kind to me
> elsewhere). Gives me some habituation to good documentation practice I
> wasn't aware of.
> 
> Couple of questions for the specific implementation in Habit. What would
> you call content stuff like translations and help text? "style"? And what
> would be some examples of "scope" that we would use here?
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/pull/2424#issuecomment-32573909
> .

## 

## Cole Gleason

Student, University of Illinois at Urbana-Champaign
Email: cg@colegleason.com
Website: colegleason.com

**Comment by snicker** [comment]
There is another issue to address here: we are not really tagging site
versions, so we need to determine what time period a particular
CHANGELOG conforms to. Unless we are just generating the file upon a
move to production.

**Comment by colegleason** [comment]
Right now the creation of CHANGELOG must be manually invoked by `grunt git_changelog`. I would vote that it be updated whenever (perhaps even with every commit) so that it stays up to date with develop.

In order to push news to users via Tumblr or Bailey we might add a Heroku Deploy Hook that email @lefnire and @lemoness with"

```
The site has been updated! Please check over what's new on the [CHANGELOG](https://github.com/HabitRPG/habitrpg/blob/develop/CHANGELOG.md).
```

Or something like that.

**Comment by snicker** [comment]
Will CHANGELOG carry a history? Or just the most recent generation?
Forgive me, I don't know much about the package and haven't had much
time to look. I'd think that users could miss something with how often
we push to live

**Comment by colegleason** [comment]
@snicker: Not sure honestly. I'll take a look.

What would you like it to do? This is already using my fork of the package,
so I can modify the way it makes the changelog.

On Thu, Jan 16, 2014 at 8:58 PM, snicker notifications@github.com wrote:

> Will CHANGELOG carry a history? Or just the most recent generation?
> Forgive me, I don't know much about the package and haven't had much
> time to look. I'd think that users could miss something with how often
> we push to live
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/pull/2424#issuecomment-32576260
> .

## 

## Cole Gleason

Student, University of Illinois at Urbana-Champaign
Email: cg@colegleason.com
Website: colegleason.com

**Comment by snicker** [comment]
Ideally a changelog will carry a complete history for a major version, in
reverse chronological order. That might be too much to contain in one file
and too much to deliver to users. Maybe the most recent three updates to
CHANGELOG are in CHANGELOG.md and the history beyond can be found in
CHANGELOG.archive.md or something. Sorry, my phone seems to think that
CHANGELOG should always be uppercase

On Jan 16, 2014, at 21:40, Cole Gleason notifications@github.com wrote:

@snicker: Not sure honestly. I'll take a look.

What would you like it to do? This is already using my fork of the package,
so I can modify the way it makes the changelog.

On Thu, Jan 16, 2014 at 8:58 PM, snicker notifications@github.com wrote:

> Will CHANGELOG carry a history? Or just the most recent generation?
> Forgive me, I don't know much about the package and haven't had much
> time to look. I'd think that users could miss something with how often
> we push to live
> 
> —
> Reply to this email directly or view it on GitHub<
> https://github.com/HabitRPG/habitrpg/pull/2424#issuecomment-32576260>
> .

## 

## Cole Gleason

Student, University of Illinois at Urbana-Champaign
Email: cg@colegleason.com
Website: colegleason.com

—
Reply to this email directly or view it on
GitHubhttps://github.com/HabitRPG/habitrpg/pull/2424#issuecomment-32577859
.

**Comment by colegleason** [comment]
Yeah, the tool already almost supports that. I'll try to modify it to make
that work. Since we don't have versions, what should I limit CHANGELOG to?

On Thu, Jan 16, 2014 at 9:44 PM, snicker notifications@github.com wrote:

> Ideally a changelog will carry a complete history for a major version, in
> reverse chronological order. That might be too much to contain in one file
> and too much to deliver to users. Maybe the most recent three updates to
> CHANGELOG are in CHANGELOG.md and the history beyond can be found in
> CHANGELOG.archive.md or something. Sorry, my phone seems to think that
> CHANGELOG should always be uppercase
> 
> On Jan 16, 2014, at 21:40, Cole Gleason notifications@github.com wrote:
> 
> @snicker: Not sure honestly. I'll take a look.
> 
> What would you like it to do? This is already using my fork of the
> package,
> so I can modify the way it makes the changelog.
> 
> On Thu, Jan 16, 2014 at 8:58 PM, snicker notifications@github.com
> wrote:
> 
> > Will CHANGELOG carry a history? Or just the most recent generation?
> > Forgive me, I don't know much about the package and haven't had much
> > time to look. I'd think that users could miss something with how often
> > we push to live
> > 
> > —
> > Reply to this email directly or view it on GitHub<
> > https://github.com/HabitRPG/habitrpg/pull/2424#issuecomment-32576260>
> > .
> 
> ## 
> 
> ## Cole Gleason
> 
> Student, University of Illinois at Urbana-Champaign
> Email: cg@colegleason.com
> Website: colegleason.com
> 
> —
> Reply to this email directly or view it on
> GitHub<
> https://github.com/HabitRPG/habitrpg/pull/2424#issuecomment-32577859>
> .
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/pull/2424#issuecomment-32577975
> .

## 

## Cole Gleason

Student, University of Illinois at Urbana-Champaign
Email: cg@colegleason.com
Website: colegleason.com

**Comment by lemoness** [comment]
Hmmm, I'd actually say that we don't want to LINK users to the changelog in
lieu of more personal Bailey updates - it's a little colder. But yes, I
would love to have the changelog to help me write the Bailey announcements
etc. Unless you were saying that we'd link to the changelog at the end of
the posts, in which case, totally fine!

 Thanks so much, Cole!!!

**Comment by colegleason** [comment]
Sorry @lemoness, I should have been more clear. The email I mentioned was just a notification to you that there are new features for the blog. Users won't see the changelog unless they come here. I do like the idea of linking it at the end of Bailey updates though. (Want to see all changes and bug fixes in progress? Click here to see what the blacksmiths are working on in their forge!)

**Comment by lemoness** [comment]
Ahh, exactly what I had in mind!! Perfect.

**Comment by colegleason** [comment]
Since this doesn't affect any other code and is completely optional, I'm going to merge this in.
- To enable the commit-msg hook: `ln -sf ../../validate-commit-msg.js .git/hooks/commit-msg`
- To enable the grunt task: `npm install`
- To run the grunt task: `grunt git_changelog`

**Comment by lefnire** [comment]
Sorry I'm so late to the game. K cool, this is rad. I setup the `ln` and I'll try to be good about running `grunt git_changelog` any time I push a major batch of updates. And as mentioned, it may be time we start tagging. I'll keep that on my mind-grapes. Great work with all this @colegleason! I think we're all new to Angular-style git commit messages, but hey it'll be good for us. 

Only thing I want to make sure I'm understanding correctly: people who aren't linking (PRs, etc) - we're basically just ignoring that, yea? Rebasing crazyness and all, so this is just for us? (Maybe a note in CONTRIBUTING.md or something simple)

**Comment by colegleason** [comment]
Yeah, right now we can't cover them unless you merge PRs from the command
line. We should put it on the wiki too.

On Sat, Jan 18, 2014 at 12:26 AM, Tyler Renelle notifications@github.comwrote:

> Sorry I'm so late to the game. K cool, this is rad. I setup the ln and
> I'll try to be good about running grunt git_changelog any time I push a
> major batch of updates. And as mentioned, it may be time we start tagging.
> I'll keep that on my mind-grapes. Great work with all this @colegleasonhttps://github.com/colegleason!
> I think we're all new to Angular-style git commit messages, but hey it'll
> be good for us.
> 
> Only thing I want to make sure I'm understanding correctly: people who
> aren't linking (PRs, etc) - we're basically just ignoring that, yea?
> Rebasing crazyness and all, so this is just for us? (Maybe a note in
> CONTRIBUTING.md or something simple)
> 
> —
> Reply to this email directly or view it on GitHubhttps://github.com/HabitRPG/habitrpg/pull/2424#issuecomment-32675844
> .

## 

## Cole Gleason

Student, University of Illinois at Urbana-Champaign
Email: cg@colegleason.com
Website: colegleason.com

**Comment by SabreCat** [comment]
Wait, so if I submit a PR instead of committing first, this doesn't do anything? 'Cos that's my usual workflow, unless my change is really trivial...

Also, do we need something similar for habitrpg-shared?

**Comment by SabreCat** [comment]
Also, CHANGELOG.md should probably be in nodemonignore, or else doing `grunt run:dev` causes several server bounces.

**Comment by lefnire** [comment]
@SabreCat i think it doesn't do anything even if you do it from local, we have to run `grunt git_changelog` manually before deployments (which IMO is just fine)

**Pull request merged**
