### PR TITLE
minor text fixes: accurate flavour text for Golden Knight testimonies collection quest, etc

### PR DESCRIPTION
**Pull request by Alys**
This PR does three small, unrelated things:

- Adjusts the flavour text for the Golden Knight collection quest so that it mentions dozens of Testimonies not hundreds (thanks to Atanasi for reporting that in the Report a Bug guild).
- Improves accuracy of a couple of comments in the code for removing group members (members are removed, not banned, because they can always rejoin with an invitation in a private group or at any time in a public group).
- Standardises line breaks in a few files (view with ?w=1 in the URL to remove those whitespace fixes)

EDIT: See my comments below for a couple more things.

### CODE REVIEW

**Comment by mandyzhou** [comment]
Should it also be "Habiticans'", not "Habitican's"?

**Comment by Alys** [comment]
@mandyzhou Great point, well spotted, thank you! I've added a fix for that.

I've also made another unrelated change and added it to this PR. When you try to send a PM to a user who has either opted out of PMs or blocked you specifically, you used to see the message:
"Can't send message to this user."
We fairly often saw people report this as a bug. I've changed it to:
"You can't send a message to this player because they have chosen to block messages."
I kept it vague about whether they'd blocked all messages or just you for politeness.

**Comment by Alys** [comment]
I've added one more change to update the instructions for unsubscription from Google subscriptions.

**Comment by Alys** [comment]
I'll merge this in a day if there's no complaints.

**Comment by Alys** [comment]
I've added a fix for #8598 (improves the Delete Completed on-hover message)

**Comment by Alys** [comment]
Also added an improvement to the Orb of Rebirth text.

**Pull request merged**
