### PR TITLE
Fix/mana bar unselected class - fix: #10026

### LINKED ISSUE #10026: mana bar should not show in profile when user has not yet selected a class
When a user has not yet selected a class, currently if you view their profile you see a mana bar. The correct behaviour is that no mana bar should be shown (the same as for a user who has opted out of the class system).

Below is data showing the problem. `flags.classSelected` is `false` when a player has not yet selected a class so that is what you can use to prevent the mana bar being displayed.
```
{
    "stats": {
        "class": "warrior",
        "lvl": 13
    },
    "flags": {
        "classSelected": false
    },
}
```
screenshot_2018-02-20_09-26-24

### PR DESCRIPTION
**Pull request by tmkuba**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

Fixes #10026

### Changes
[//]: # updates members.hasClass() to account for users who have not selected a class

[//]: # 
----
UUID: b1cf5a63-61c5-46e5-807d-656415fde46b

### CODE REVIEW

**Comment by paglias** [comment]
This works @tmkuba  but I noticed that the same check is used in several places in the code and it would be great if we could use the getter everywhere, for example https://github.com/HabitRPG/habitica/blob/4108a22d7822027c29a1b5ed9843cc3844caae63/website/client/components/achievements/levelUp.vue#L152 (but there are other places too)

**Comment by tmkuba** [comment]
Just an update, I am currently investigating the other places in the code that refers to the referenced flags

**Comment by tmkuba** [comment]
Hi @paglias , I have updated the PR and used the hasClass() getter where similar checks are made.  Please review when you have a chance.

**Comment by SabreCat** [comment]
Thanks for this, @tmkuba! Noted toward your second contributor tier!

**Pull request merged**
