### PR TITLE
create a "Dated" To-Dos tab

### PR DESCRIPTION
**Pull request by Alys**
Requires https://github.com/HabitRPG/habitrpg-shared/pull/350

This PR adds a "Dated" tab to the To-Dos column, which displays all uncompleted To-Dos that have due dates assigned (both in the future and past). It does NOT sort the To-Dos by date because that's significantly harder. 

Dated To-Dos are ALSO shown in the "Remaining" tab, just as they are now. The "Completed" tab also works just as now (shows all completed To-Dos regardless of whether they have due dates).

Other changes in this PR:
- rename "Remaining" To-Dos tab to "Active" to save space
- rename "Completed" To-Dos tab to "Done" to save space
- allow the form for adding new To-Dos to be visible even when completed To-Dos are being viewed (consistent with other columns)
- make the hide/show code for To-Dos consistent with the code for Dailies and Habits (i.e., use @Gaelan's code from https://github.com/HabitRPG/habitrpg/pull/3574)
- remove some unnecessary commented-out code

I've tested this without finding problems, but the last time I did something like this I broke Challenges...   **Would someone be able to test this locally, or can we put it on beta first?**

screen shot 2014-11-01 at 9 08 38 pm
screen shot 2014-11-01 at 9 08 51 pm
screen shot 2014-11-01 at 9 15 20 pm

### CODE REVIEW

**Comment by Alys** [comment]
I've added a tooltip to the Dated To-Dos tab to forestall the questions and bug reports we would get about it: _"Dated To-Dos are NOT sorted by date. Sorting will probably be implemented in future."_  Wording changes welcome. Ping @lemoness 

screen shot 2014-11-02 at 6 02 32 am

**Comment by taldin** [comment]
How would I download your branch to my version?

**Comment by Alys** [comment]
@taldin:

```
git remote add Alys git://github.com/Alys/habitrpg.git
git fetch Alys
git checkout -b your_name_for_my_branch Alys/todos-dated-tab-2014-11-01
```

The "todos-dated-tab-2014-11-01" branch name can be found on this page in a few places (search now so you know where to find branch names for other branches in future). The first command "git remote add ..." needs to be done only once per person, so if you ever want to download a copy of one of my other branches, you don't need to repeat that step (and in fact you would get a non-dangerous error if you did). The `git fetch Alys` command should be repeated each time you want to get a new branch, because it is what fetches the latest data from github. The checkout command creates a new branch (you choose any name) that is based on (i.e., initially identical to) my "todos-dated-tab-2014-11-01" branch.

Whenever you're doing this, be careful to not merge someone else's branch into one of your own branches, or to not accidentally make your own, unrelated changes in your copy of someone else's branch, because that could corrupt the changes you are making and would make your pull request a nightmare. :)  (Unless of course you are deliberately wanting to add to someone else's unapproved work, but it can be unsafe to do that because you don't know if their work ever will be approved, or if it will be changed before approval.) If you always check what local branch you are on before starting to make changes, you should be safe.

**Comment by taldin** [comment]
Also, now that I've managed to fix my unstable Habits fork, I can actually try testing this.  Haven't forgotten. :)

**Comment by taldin** [comment]
I'm not able to get this to run now that I have a branch for it.  I keep getting a recurring message 'cannot find module paypal-recurring'.    I'm guessing it's because of the fix further upstream.  Is it safe to rebase the branch off of upstream/develop or will that ruin the experiment?

**Comment by Alys** [comment]
Yes rebase should be safe, and if it messes up, you can delete the branch and try again. However the module thing is probably a new module that needs to be installed with npm. After rebasing, examine any differences to package.json (`git log -p package.json`, or just make a backup copy of the file first and then diff it with the new one) and that will show you any new modules to install (`npm install modulename`). All this is from memory since I'm at work at the moment, so cross your fingers as you do this. :)

**Comment by taldin** [comment]
Rebasing to upstream/develop got it running, but now I'm getting an error showing on my To-Dos:
image

Oh, I bet I have to get the branch for habitrpg-shared over too.  :)  Hang on.

**Comment by Alys** [comment]
Merge the matching PR on habitrpg-shared (see the link at the top of this page) then run grunt in your habitrpg-shared directory, then restart npm (same process as for "Translatable strings" http://habitrpg.wikia.com/wiki/Guidance_for_Blacksmiths#Translatable_strings )

**Comment by taldin** [comment]
Whuff.   Trying to bring in the habitrpg-shared half is not working right.  If I don't do an upstream/develop rebase, I get this:
image
and then after I npm install all of those and run grunt again, I get 'Task default not found.  Use --force to continue.'

However, if I try using upstream/develop, it tries to apply over a hundred old commits for some reason, giving me lots of conflicts, and I wind up just aborting the rebase. 

Running 'as is' just returns a bunch of fork errors.

**Comment by Alys** [comment]
Try a merge instead of a rebase. There are reasons for and against each option, but for what you're doing (testing someone else's change), it shouldn't make any difference and merge will give you just one set of conflicts to deal with at the end.

When grunt says "Task _whatever_ not found" it often means that there is no Gruntfile.js in the directory you are in (i.e., you're in the right directory but Gruntfile.js has been deleted, or you need to cd to the directory containing Gruntfile.js). It can also mean that grunt should be run with `grunt <name_of_a_task>` rather than just `grunt` (not the case for habitrpg-shared).

**Comment by taldin** [comment]
Doing a merge seems to have done the trick, but I'm still getting the String 'dated' not found error.  It's at least up and running again.  It's possible that I didn't do the merge right - there were conflicts, and in all cases I took the upstream/develop code in favor of the Head code.

The following files had conflicts:
image

**Comment by Alys** [comment]
If those are the only files that had conflicts and you still don't have the 'dated' string, I'm wondering if your initial fetch of my habitrpg-shared PR didn't take. Try `git pull https://github.com/Alys/habitrpg-shared.git todos-dated-tab-2014-11-01` from within your local branch in habitrpg-shared. I think that will do it.

**Comment by taldin** [comment]
Oof. More conflicts.  Do I take the Head this time or the commit number?

**Comment by taldin** [comment]
Aha!  I got it working!  Taking out the non-Head ones did the trick.  It seems to work reasonably okay for the most part from basic tests (add task, add dates, show/hide, remove dates, show/hide, etc.)

**Comment by Alys** [comment]
I've pulled in the latest code from `develop` and flxed conflicts. To-Do column now has the new appearance. If nobody sees anything wrong with this PR in a day or so, I'll merge it and https://github.com/HabitRPG/habitrpg-shared/pull/350

screen shot 2015-01-11 at 2 54 24 pm

**Pull request merged**
