### PR TITLE
Fixed formatting of modal strings to correctly display message #9818

### LINKED ISSUE #9818: two contributor reward modal strings should be merged into one
We have these two strings in `website/common/locales/en/contrib.json` :
```
  "contribModal": "<%= name %>, you awesome person! You're now a tier <%= level %> contributor for helping Habitica. See",
  "contribLink": "what prizes you've earned for your contribution!",
```
and this code that uses them in `website/client/components/achievements/contributor.vue` :
```
| {{ $t('contribModal', {name: user.profile.name, level: user.contributor.level}) }}
a(:href="$t('conRewardsURL')", target='_blank') {{ $t('contribLink') }}
```

That's bad because translators can't do proper translations when a sentence is split into two strings, and because it causes words to be run on in the modal:

screenshot_2018-01-18_19-30-16

Those two strings should be merged into one and the Vue code changed to match.

@vIiRuS Will matching changes be needed in the iOS and/or Android apps? I.e., do the apps also use those strings to tell users about their new contributor tiers? If so, we should leave those two strings exactly as they are now and create a third string to merge the two texts into one. The website can use the third string. The apps can continue to use the two old strings until the apps have been updated. I can create app issues for this when the website has been changed. Please let me know if that will be needed.

_Thanks to Kent the Amateur (b82b7aa8-161f-4b02-aef9-4a319e47f7b2) for reporting this._

### PR DESCRIPTION
**Pull request by Kiwilicious**
Fixes #9818 

screenshot from 2018-01-24 13-36-27

### CODE REVIEW

**Comment by Alys** [comment]
That looks much better! I'd be happy for this to be merged if the staff are fine with it. Thanks @Kiwilicious!

**Comment by SabreCat** [comment]
Thanks for this, @Kiwilicious! Do you have a Habitica UUID (see https://habitica/user/settings/api)? If so, post it here and we can get you contributor credit!

**Comment by Kiwilicious** [comment]
@SabreCat Here you go: User ID:8e46a2b3-945b-45cc-b3f0-21c2b72f240b

**Comment by SabreCat** [comment]
Great! Welcome to the ranks of the Blacksmiths at tier 1, and thanks again!

Note that further tiers require increasing amounts of effort from one to the next, so Tier 2 may require multiple PRs or a larger PR to attain. But keep helping out and we'll express our gratitude accordingly!

**Pull request merged**
