### PR TITLE
Removed unused I18N strings from the `quests.json` files (related to issue #9957)

### PR DESCRIPTION
**Pull request by RaitheOfDureya**
[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
This PR fixes part of issue #9957

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
I have identified the following unused strings in the `quests.json` file. 

At the moment I only removed the strings from the `locales/en` folder to make it easier to revert if necessary. Once the strings are reviewed, I can delete them from the other languages.

- questsForSale
- questOwnerReceived
- youWillReceive
- questOwnerWillReceive
- youReceived
- dropQuestCongrats
- questSend
- questSendBroken
- questInvitationTitle
- questLater
- questStart
- questStartBroken
- collectionItems
- itemsToCollect
- bossDmg1
- bossDmg2
- bossDmg1Broken
- bossDmg2Broken
- tavernBossInfo
- tavernBossInfoBroken
- bossColl1
- bossColl2
- bossColl1Broken
- bossColl2Broken
- questOwner
- questTaskDamage
- questTaskCollection
- questOwnerNotInPendingQuest
- questOwnerNotInRunningQuest
- questOwnerNotInPendingQuestParty
- questOwnerNotInRunningQuestParty
- questParticipants
- scrolls
- noScrolls
- scrollsText1
- scrollsText2
- scrollsPre
- alreadyEarnedQuestLevel
- alreadyEarnedQuestReward
- completedQuests
- mustLevel
- mustInviteFriend
- questWarning
- questWarningBroken
- whichQuestStart
- unlockedAQuest
- leveledUpReceivedQuest
- createAccountReward
- loginIncentiveQuestObtained
- createAccountQuest
- buyQuestBundle
- whereAreMyQuests
- yourQuests
- getMoreQuests

I am not sure if the following strings are being generated dynamically, could you please tell me if it is okay to remove them?

in `website/common/script/libs/shops.js`:
```javascript
... .t(`${type}Quests`, language) ...
```

- petQuests
- unlockableQuests
- goldQuests
- hatchingPotionQuests

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 6544e17f-237b-4915-ae7e-47744c0dc1bd

### CODE REVIEW

**Comment by paglias** [comment]
@RaitheOfDureya these ones are generated dynamically

```
petQuests
unlockableQuests
goldQuests
hatchingPotionQuests
```

**Comment by RaitheOfDureya** [comment]
Thank you, @paglias. I updated the list of removed strings.

**Comment by paglias** [comment]
@RaitheOfDureya could you remove the strings from the other locales as well? Thanks!

**Comment by RaitheOfDureya** [comment]
@paglias, as requested I removed the strings from the other locales.

**Comment by paglias** [comment]
thanks, noted in your profile

**Pull request merged**
