### PR TITLE
autocomplete: sort usernames by indexOf then length

### PR DESCRIPTION
**Pull request by colegleason**
Fixes 1866.

Theres another odd bug (?) where autocomplete doesn't seem to filter properly until you've typed at least two characters. Not sure why.

### CODE REVIEW

**Comment by colegleason** [comment]
Fixes #1866

**Comment by snicker** [comment]
What is the default way of ordering right now? 

Without actually testing the performance, I have a hunch that it's going to be more computationally efficient client-side to sort the array of usernames when it's first built rather than in the Angular filter. My gut feeling is that the `indexOfQuery` function is going to be executed upon every single keystroke in the chat box... so if we order the array of usernames upon construction in `chatChanged`, it will be a more efficient solution.

Sorry to jump in about that, it's just that client performance in chat is already horrendous, and we need to have an eye for optimization where ever possible (though this seems to be the most logical solution)

**Comment by colegleason** [comment]
Yeah, you are probably right. We shouldn't just stick AngularJS magic everywhere :-)

I'll work on updating this soon.

**Comment by colegleason** [comment]
@snicker I'm actually not sure how to do that since the controller doesn't seem to have access to the query text. That's in a separate dependancy.

**Comment by negue** [comment]
@lefnire should it fixed like in this pullrequest during ng-repeat OR should the $scope.response already sorted by name ?

**Comment by lefnire** [comment]
@negue in groupsCtrl.js `AutocompleteCtrl`, TMK this "response" (misleading) isn't coming from the server directly. The code is sifting through users loaded on the client, and does so once you've typed a key. Eg, typing "neg" will continue to sort from there. So sorting from the server wouldn't be feasible in this case.

This is how I _think_ the code works, I'm a bit shaky on Angular-At-Directive, so correct me if I'm wrong. Also, I wonder if there's a more popular/supported library out there we can't use for autocomplete. Angular-At has few stars, and sparse activity

**Comment by negue** [comment]
Yes , angular-at-directive should be replaced by something else.

Just did a small search, and https://github.com/jeff-collins/ment.io looks promising.

This could replace the User Autocompletion and may also the an emoji autocompletion :)

**Comment by lefnire** [comment]
Ooo, looks promising!

**Comment by crookedneighbor** [comment]
What's the status of this, can it be closed?

**Comment by negue** [comment]
I'll try a ment.io implementation this weekend, then if everything works I'll close all issues.^^

**Comment by Alys** [comment]
@negue Did you have any luck with men.io?

**Comment by negue** [comment]
@Alys I was able to get ment.io running with only users but not if I want to have two completions (user & emoji)

**Comment by crookedneighbor** [comment]
Looks like this is out of date, especially since the autocomplete controller has been worked on recently. Going to close this now, but re-open it if I'm wrong.

**Pull request closed without merging**
