### PR TITLE
Backer Only Gear and Pet

### PR DESCRIPTION
**Pull request by Shaners**
Features
- Animated GIF versions of all backer only assets
- Sprite Sheet version to test out CSS animating, if desired

Notes
- Does not contain any CSS
- Crystal Armor is included as an alternative to the darker armor
- Feel free to ignore the crystal armor for now

### CODE REVIEW

**Comment by lefnire** [comment]
Woo, thanks man! I'll merge this in (have to on cli for some reason) and play with it. initial thought - will 105x105 mess with the standard 90x90 positioning?

**Comment by Shaners** [comment]
@lefnire sorry forgot to mention the adjusted size here ( I meant to! ) It will break things, in that the art will be misaligned, but could still start on implementation of the feature. I think I'll work on a 105 x 105 revision to the previous assets and upload it as a secondary sprite sheet for you to experiment with. I'm also going to need to adjust the timing on the GIFs so they aren't looping as fast.

**Comment by lefnire** [comment]
They do indeed work as 105x105, with some css margin updates - Do you want
to G+ to take a peak at the results? Also, could you shoot me a
sprite-sheet of smaller gear for the shop (40x40 i believe it was, I don't
have the xcf m'self and would probably ruin everything anyway :)

**Comment by Shaners** [comment]
@lefnire Is the css margin modification an ideal solution? Should I bother with a 105x105 sheet of previous assets? Yea go for it on G+, always good to get feedback.Will update the shop sprite sheet with the shade helmet, shade armor, tormented shield, and dark souls blade asap but won't be able to push the update to dev until later tonight.

**Pull request merged**
