### PR TITLE
Add text alternatives for navbar items

### PR DESCRIPTION
**Pull request by ianoxley**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
See #10008 

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
Add `aria-label` to navbar icons to provide text alternatives, using the same strings used for the tooltips.

Add ARIA attributes to the notification and user dropdown menu toggles, add `tabindex="0"`, and add keydown handlers for the `<Enter>` and `<Space>` keys so that those menus can be activated via the keyboard.

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: c5085c21-2d4a-4707-a178-0d547329095a

### CODE REVIEW

**Comment by paglias** [comment]
thanks @ianoxley, as the other PR this is almost ready to go except for the selection style issue  on the user and notifications dropdown
schermata 2018-12-04 alle 10 05 42
schermata 2018-12-04 alle 10 05 47

**Comment by ianoxley** [comment]
I've added the `:focus` changes for `.habitica-menu-dropdown` from #10819. This should fix the issue above.

**Comment by Tressley** [comment]
Hmm. I'm not able to toggle the dropdown menu using `Enter` or `Space`. `Enter` navigates to the top level and `Space` scrolls down the page.

**Comment by Tressley** [comment]
LGTM 👍

**Comment by paglias** [comment]
@ianoxley sorry this took longer than expected! But it'll go live next week, thanks!

Notated towards your 3rd tier

**Pull request merged**
