### PR TITLE
chore: upgrade express to version 4

### PR DESCRIPTION
**Pull request by crookedneighbor**
This does the minimal work needed to upgrade to express 4. 

There are some deprecation warnings being logged, but everything _should_ work just fine. 

Will do some work to clear out the deprecated methods before merging in.

### CODE REVIEW

**Comment by crookedneighbor** [comment]
Found bug. Cannot export csv history.

**Comment by Alys** [comment]
I just received the "entity too large" error when trying to start a quest in a party of four. I don't recall getting that error before in that situation and I start quests a lot.

I reloaded and it happened again. I cleared local storage and logged back in, and it happened again.

I went to the `upstream/develop` version of the site and the error did not happen.

**Comment by crookedneighbor** [comment]
@Alys Should be fixed now. Care to doublecheck?

**Comment by Alys** [comment]
It's good now. Worked first time with the new code.

**Comment by crookedneighbor** [comment]
As far as I know, this is ready to be merged in. Will let us do some further QA testing before merging in though.

**Comment by crookedneighbor** [comment]
Merge in on the command line

**Pull request closed without merging**
