### PR TITLE
Pet Egg Sprite Sheet and CSS

### PR DESCRIPTION
**Pull request by Shaners**
This will eventually be merged with the pet sprite sheet and CSS but here is a version that can be worked with. The CSS is a bit different than the other ones used for sprites: use id="PetEggs" to call and class="<specific egg>" to get a specific egg. Not very well versed with CSS and structure of Habit so let me know if this just doesn't work.

### CODE REVIEW

**Comment by Shaners** [comment]
Is there a way to get rid of these unrelated commits?

**Comment by switz** [comment]
Why are you using an id? That should be a class.

**Comment by lefnire** [comment]
@Shaners don't worry about the unrelated commits, that's fine. Next commit let's do the PR against `develop` branch instead of `master`, and use classes instead of ids. @switz aint no thang, we'll change that. 

This is great! Thanks a ton, absolutely love your work sir!

**Comment by lefnire** [comment]
(note: merged into master because this is benign/additive commit, we'll be very strict on `develop` for code-related commits)

**Comment by switz** [comment]
What do you want me to merge into inventory? Is `master` fine? Usually I only merge in `develop`.

**Comment by lefnire** [comment]
master gets merged into develop, so 2 birds 1 stone if you merge in develop
(i merged this commit to develop)

**Pull request merged**
