### PR TITLE
fix(styles): center avatar in the editing modal

### LINKED ISSUE #11221: Avatar edit window layout mangled
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

Something appears to have thrown off the layout of the edit avatar window:

image

* The z-index is wrong, landing the modal beneath the navigation bar.
* (Possibly) The modal is too high on the page.
* There is much more whitespace below the avatar than needed.

### PR DESCRIPTION
**Pull request by SebastiaanNijland**
[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #11221 

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
- Uses `calc()` to center the avatar on the x-axis
- Updates the value of `top` (fixes https://github.com/HabitRPG/habitica/issues/11221)

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 2f3f22af-3abf-4236-bf9e-67ff88051df9

### CODE REVIEW

**Comment by paglias** [comment]
thanks @SebastiaanNijland ! Locally for me the avatar is a bit too centered now :) It covers the hairs style tab 

Schermata 2019-08-14 alle 12 22 58

**Comment by SebastiaanNijland** [comment]
You're right, I get that locally as well! If I apply the changes on the prodcution site using DevTools, this PR does seem to work:

Screenshot 2019-08-14 at 14 12 49

What do you advise me to do in this case?

**Comment by paglias** [comment]
Hmm I guess the same thing that @SabreCat was reporting in the original issue about the behavior being different on prod/locally is happening here. I'll give it a look, it's probably due to some priority rule

**Comment by paglias** [comment]
Fixed the conflicts

**Comment by SabreCat** [comment]
The related issue appears to have been incidentally fixed by some other work. If there's further improvements this PR can make, we can reopen it, but closing for now!

**Pull request closed without merging**
