### PR TITLE
Removed unused I18N strings from the `groups.json` files (related to issue #9957)

### PR DESCRIPTION
**Pull request by RaitheOfDureya**
[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
This PR fixes part of issue #9957

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
I have identified the following unused strings in the `groups.json` file.  No dynamically generated strings were found.

At the moment I only removed the strings from the `locales/en` folder to make it easier to revert if necessary. Once the strings are reviewed, I can delete them from other languages.

- innCheckOut
- innCheckIn
- innText
- innTextBroken
- lfgPosts
- wikiLink
- reportAP
- community
- askQuestionNewbiesGuild
- tavernAlert1
- tavernAlert2
- moderatorIntro1
- communityGuidelinesRead1
- communityGuidelinesRead2
- createAParty
- updatedParty
- errorNotInParty
- noPartyText
- LFG
- wantExistingParty
- joinExistingParty
- needPartyToStartQuest
- partyInvitationsText
- joinPartyConfirmationText
- joinNewParty
- declineInvitation
- partyLoading1
- partyLoading2
- partyLoading3
- partyLoading4
- toolTipMsg
- sendChatToolTip
- syncPartyAndChat
- guildBankPop1
- guildBankPop2
- guildGems
- editGroup
- newGroupName
- groupDescr
- logoUrl
- assignLeader
- partyList
- banTip
- moreMembers
- leaderMsg
- guildsLink
- foreverAlone
- leaveGroupCha
- leavePartyCha
- sendPM
- messageSentAlert
- pmHeading
- clearAll
- confirmDeleteAllMessages
- PMReceive
- privateMessageGiftSubscriptionMessage
- abuseFlag
- abuseFlagModalButton
- abuseAlreadyReported
- needsText
- messageWroteIn
- msgPreviewHeading
- partyMembersInfo
- inviteByEmailExplanation
- inviteFriendsNow
- inviteFriendsLater
- inviteAlertInfo
- inviteExistUser
- byColon
- inviteNewUsers
- inviteAlertInfo2
- startPartyWithFriends
- addToParty
- likePost
- partyExplanation1
- partyExplanation2
- partyExplanation3
- wantToStartParty
- exclusiveQuestScroll
- nameYourParty
- partyEmpty
- partyChatEmpty
- guildChatEmpty
- requestAcceptGuidelines
- inviteMissingUuid
- confirmClaim
- confirmApproval
- newChatMessagePlainNotification
- newChatMessageTitle
- exportInbox
- exportInboxPopoverTitle
- exportInboxPopoverBody
- desktopNotificationsText
- confirmAddTag
- confirmRemoveTag
- groupHomeTitle
- approvalTitle
- confirmTaskApproval
- groupAdditionalUserCost
- groupBenefitTwoDescription
- groupBenefitThreeTitle
- groupBenefitThreeDescription
- groupBenefitFourTitle
- groupBenefitFourDescription
- groupBenefitFiveTitle
- groupBenefitFiveDescription
- groupBenefitSixTitle
- groupBenefitSixDescription
- groupBenefitSevenTitle
- groupBenefitEightTitle
- groupBenefitEightDescription
- groupBenefitMessageLimitTitle
- groupBenefitMessageLimitDescription
- groupBenefitsTitle
- groupBenefitOneTitle
- groupBenefitOneDescription
- groupBenefitTwoTitle
- specializedCommunication
- funExtras
- enterprisePlansButton
- enterprisePlansDescription
- familyPlansButton
- familyPlansDescription
- createAGroup
- getAGroupPlanToday
- assignFieldPlaceholder
- approvalsTitle
- upgradeTitle
- blankApprovalsDescription
- refreshApprovals
- refreshGroupTasks
- claimedBy
- confirmGuildPlanCreation
- guildMembers
- joinGuild
- guildOrPartyLeader
- upgradeParty
- startYourOwnPartyTitle
- startYourOwnPartyDescription
- pm-reply

This file was absolutely insane, it took me at least 4 attempts to clean it :sweat_smile:

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 6544e17f-237b-4915-ae7e-47744c0dc1bd

### CODE REVIEW

**Comment by paglias** [comment]
Schermata 2020-09-22 alle 22 23 08

```
inviteToGuild
inviteToParty
```

these two are used (see the screenshot)

**Comment by RaitheOfDureya** [comment]
I cherry-picked these two out of the previous commit. Thanks, @paglias

**Comment by RaitheOfDureya** [comment]
@paglias, I have finished removing the strings from the other files.

**Comment by paglias** [comment]
Thanks @RaitheOfDureya ! Merged this and #12589

**Pull request closed without merging**
