### PR TITLE
fix Stable component to correctly count pets

### LINKED ISSUE #9151: Stable Count Incorrect
We've received the following report:

"In the Stable, my count of how many pets I have no longer counts ones I have turned to mounts. I should have 46/90 pets. I now show 39/90 I currently have 7 pets turned to mounts that are greyed out."

### PR DESCRIPTION
**Pull request by trvrfrd**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #9151

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
update the `countOwnedAnimals()` method in the Stable component (`website/client/components/inventory/stable/index.vue`) to still count pets that have been raised into mounts, but not yet hatched again. This is accomplished by checking if each pet is either currently owned, or the mount version of that pet is currently owned (which implies the pet was previously owned).

Another approach might be to import the `beastMasterProgress()` and `mountMasterProgress()` functions from the Count module (`website/common/script/count.js`), since those accomplish basically the same thing. I don't have a good sense of how the whole app hangs together yet, though, so I don't know if that might have some drawbacks I'm missing.

[//]: # (Put User ID in here - found in Settings -> API)

----
UUID: 7620c72a-bb5a-4798-b3c0-846dacb2b44d

### CODE REVIEW

**Comment by trvrfrd** [comment]
hmmmmmmm, looks like the build is breaking on something Mongo-related. Anybody have thoughts?

**Comment by SabreCat** [comment]
A random glitch, no doing of yours. We'll review this ASAP, thanks for submitting!

**Comment by SabreCat** [comment]
Works great! Thanks much for this, @trvrfrd. I've added it to your contributor credit toward Tier 2 Blacksmith!

**Comment by trvrfrd** [comment]
Awesome! Thanks so much!

**Pull request merged**
