### PR TITLE
Removes video from presskit.zip

### LINKED ISSUE #9994: Press Kit Zip needs updating
Currently, when you download the press kit, you only get the boss images and the Habitica video. The video should be removed, and all the listed logos and screenshots should be added as well, so that you get a copy of all the still images that are on the Press Kit page when you download the zip.

### PR DESCRIPTION
**Pull request by alfill**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes 'Press Kit Zip needs updating' #9994

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
  As requested by @lemoness, removed "Habitica ... .mp4" video from presskit.zip.    
The zip package was tested, because the previous was broken.

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: e98e3a47-d06a-49d7-9a74-2a8b5deb9595

Fixes #9994

### CODE REVIEW

**Comment by paglias** [comment]
Thanks @alfill have you also added the logos and screenshot?

**Comment by alfill** [comment]
Yes, I used the same images from the [github](https://github.com/HabitRPG/habitica/tree/develop/website/static/presskit) folder
```
/PressKit $ ls -R
.:
Boss  Logo  Promo  Samples
./Boss:  Basi-List.png Dread Drag'on of Dilatory.png  Necro-Vice.png         Stagnant Dishes.png  Battling the Ghost Stag.png  Laundromancer.png SnackLess Monster.png
./Logo:  Android.png  Habitica Gryphon.png  Icon.png  Icon with Text.png  iOS.png  Text.png
./Promo:  Promo.png  Promo - Thin.png
.:
./Samples:  Android  iOS  Website
./Samples/Android: Add_Tasks.png  Login.png  Party.png  Shops.png  Stats.png  Tasks Page.png  User.png
./Samples/iOS:  LevelUp.PNG  Market.png  Party.png  QuestBoss.png  TasksPage.png
./Samples/Website:  Challenges.png  CheckInIncentives.png  Equipment.png  Guilds.png  Inventory.png  Market2.png  Market.png  Tavern.png
```

**Comment by paglias** [comment]
@lemoness can you give a look at the files and let me know if they're what you need?

**Comment by lemoness** [comment]
Hm, it looks like some of these images are broken, unfortunately.

**Comment by alfill** [comment]
updated the pictures broken by previous contributors

**Comment by paglias** [comment]
What about now @lemoness ?

**Comment by saraolson** [comment]
[party.zip](https://github.com/HabitRPG/habitica/files/1769204/party.zip)
Can we switch out the android party screen with this screenshot please? the old one has an avatar with 'fakelemoness' as their name that we don't want :)

**Comment by lemoness** [comment]
Most of these are looking good, but three of the icons are out of date. We're working on a fix for those now!

**Comment by lemoness** [comment]
Here are the three fixed icons! Once these are swapped in, as well as the Android party screenshot listed above, this Press Kit should be good to go. 

iosnew
iconnew
androidnew

**Comment by paglias** [comment]
@alfill  thanks for this! I'm merging the PR and awarding your contributor tier.

Note that further tiers require increasing amounts of work from one to the next, so Tier 2 may require a couple of PRs or a larger PR to attain. But keep helping out and we'll express our gratitude accordingly!

**Pull request merged**
