### PR TITLE
Updated bossColl1, bossColl1Broken

### PR DESCRIPTION
**Pull request by DrStrangepork**
https://github.com/HabitRPG/habitica/issues/8123
### Changes

Updated only `locales/en/`

---

UUID: 30983c37-52c3-415d-977c-38af6c7db91c

### CODE REVIEW

**Comment by DrStrangepork** [comment]
Any timeframe for merging this?

**Comment by Alys** [comment]
Can you show us screenshots of the new text? Once we've seen them we can probably merge it straight away.

**Comment by DrStrangepork** [comment]
quest

**Comment by Alys** [comment]
Thanks! I have noted this as credit towards your next tier.

**Pull request merged**
