### PR TITLE
Update user pinned items on purchasing gear

### LINKED ISSUE #10049: equipment does not become unpinned when purchased; next gear does not become pinned
As posted by Kajakas (40e9985b-8acb-4110-aeb9-a5946a83a229) in the Report a Bug guild:

**When I buy a piece of class equipment, it stays pinned in the rewards column (and looks as if it's locked) while the next piece of equipment in the series does not automatically get pinned.**

I've confirmed that. If you reload, the bought item disappears and the next one becomes pinned, however the expected behaviour is that as soon as you've bought it, it should become unpinned and then next one should appear without a reload being needed.

### PR DESCRIPTION
**Pull request by Hus274**
Currently when buying gear, the purchased item simply shows as locked and the next item in the sequence doesn't appear until reloaded. This change makes the gear purchase reset the user.pinnedItems to show remove the purchased item and display the next item available in the set.

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #10049 

Replaces PR #10064 

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 2a4d30ee-4833-420e-be7c-ad6a6e261c5f

### CODE REVIEW

**Comment by Hus274** [comment]
I merged into upstream/develop just before I pushed and tests that are failing here are passing locally:

```
  787 passing (3m)
  6 pending


=============================== Coverage summary ===============================
Statements   : 47.24% ( 4800/10161 )
Branches     : 29.96% ( 2123/7086 )
Functions    : 35.37% ( 630/1781 )
Lines        : 48.23% ( 4581/9499 )
================================================================================
[07:13:16] Finished 'test:api-v3:unit' after 3.52 min
```

**Comment by Hus274** [comment]
Looks like the tests are passing and there was a different type of failure:

```
/home/travis/build/HabitRPG/habitica/node_modules/coveralls/bin/coveralls.js:18
        throw err;
        ^
Bad response: 422 {"message":"Couldn't find a repository matching this job.","error":true}
```

Could the admins restart the test?

**Comment by Alys** [comment]
Tests restarted.

**Comment by Hus274** [comment]
Thanks @Alys! The tests failing appear to all be different than the ones that were failing before and these ones are all related to checkout and subscriptions which shouldn't be impacted by the changes above. I believe this should be ready for review. Let me know if I should try to investigate the failing tests.

**Comment by Alys** [comment]
@Hus274 Thanks for looking at that. I don't think you need to investigate the tests since they aren't related. I've marked this as ready for review.

**Comment by Hus274** [comment]
Thanks @Alys!

**Comment by negue** [comment]
LGTM 👍

**Comment by SabreCat** [comment]
Thanks for this, @Hus274! Noted toward tier 7!

**Pull request merged**
