### PR TITLE
Repair Broken Test Suite - Full Passing Tests

### PR DESCRIPTION
**Pull request by gisikw**
- Repair broken e2e test introduced in 8d03cfc (copywriting change was not
  reflected in the spec)
- Updated i18n.coffee code to be more cautious (it expected the 'en' locale
  would always be available, but provides appropriate error handling as-is).
- Extended timeout duration for protractor, as registration was slightly above
  30s.
- Added karma-mocha-reporter as a dev dependency to ensure test visibility.

### CODE REVIEW

**Comment by crookedneighbor** [comment]
Very relieved to see this PR :tada: 

Was wondering what undid my hard work to make the travis ci build pass. Thanks for figuring it out!

Looks sound to me. @paglias can you review the i18n stuff?

**Comment by gisikw** [comment]
Cheers :-)

I took a look at the other specs that had been marked as pending in the past - it seems that one of the biggest issues hampering those specs (along with making it difficult to write new specs), is that no locales are loaded within the test framework.

I've been pouring through the codebase, and I can't figure out where the `translations` property of the i18n lib is actually seeded from the JSON files. @crookedneighbor, @paglias if either of you can point me in right direction, I can work on reinstating some of the remaining tests, plus write some new ones.

Though I suppose in the worst case, I can write a loader inside the spec helpers, since presumably locale data is loading just fine in production.

**Comment by paglias** [comment]
@gisikw the i18n seems fine. As for the `translations` property of the i18n lib it's filled at server startup by this module https://github.com/HabitRPG/habitrpg/blob/develop/website/src/i18n.js that is loaded here https://github.com/HabitRPG/habitrpg/blob/develop/website/src/server.js#L31

**Comment by gisikw** [comment]
Ahhh, there it is :) I was looking all over common/ for that. Cool cool - soon as this is merged in, I'll get to work on reinstating more of the tests.

**Comment by gisikw** [comment]
Went ahead and rebased against develop while waiting for this to be merged in. Please advise if there's anything else needed on my end :)

**Comment by paglias** [comment]
@gisikw if @crookedneighbor is ok I think we can merge

**Comment by crookedneighbor** [comment]
I'm :+1: with the caveat that I have not had a chance to pull it down and test it locally. But, Travis is happy so I am happy.

**Comment by gisikw** [comment]
While waiting for this to get merged in, I hacked together a small Grunt task that generates a `test/spec/translations.js` file which contains

``` js
window.env = window.env || {};
window.env.translations = {/* All the en translations */};
```

Set that up to load in the Karma suite, so a bunch of the specs that were commented out due to absent translations could be reinstated. The only changes in the new commit are to specs, Gruntfile, Karma.conf.

Anyway, the gist of it is, now we've got 20 passing Karma specs up from 16 :)

**Comment by crookedneighbor** [comment]
You are my hero. I'm hoping to merge this in today.

**Comment by gisikw** [comment]
Repaired a few more :)

**Comment by gisikw** [comment]
...and the last remaining ones. All Karma specs now un-pending and passing. Cheers!

**Comment by crookedneighbor** [comment]
I'd like to change the grunt file to have a `build:test` task that runs the `build:dev` task and adds the prepare translations task. Then, on the [run_tests.sh](https://github.com/HabitRPG/habitrpg/blob/develop/test/run_tests.sh#L8) file, change `build:dev` to `build:test`.

```
grunt.registerTask('build:dev', ['browserify', 'stylus']);
grunt.registerTask('build:test', ['test:prepare:translations', 'build:dev']);
```

Does that make sense?

Also, is there a reason the compiled `/test/spec/translations.js` file needs to be checked into version control? Since it gets recompiled every time the tests are run, couldn't it be added to the .gitignore file?

**Comment by gisikw** [comment]
@crookedneighbor Makes sense on both counts - I'll have those pushed up momentarily.

**Comment by gisikw** [comment]
@crookedneighbor Made both adjustments. Also added some additional logic to `test/run_tests.sh` to allow for an optional argument ('mocha', 'karma', 'protractor'), to easily run a subset of the full test suite, so syntax such as `npm test karma` will now work. All tests still run by default.

**Comment by gisikw** [comment]
Rebased :)

**Comment by crookedneighbor** [comment]
Looks good to me, but I don't feel good about merging it in when I don't have access to a local install to test it on.

Could someone look it over and merge it in? I'm anxious to get these tests working again.

**Comment by Alys** [comment]
@blade or anyone:  If you give me some brief pointers about how to run it, I can test the tests.

**Comment by gisikw** [comment]
Hi @Alys - you should be able to run the tests simply via `npm install && npm test`. That'll run through the mocha, karma, and protractor tests in sequence.

Also, the only changes to non-test code are minor safety checks in `common/script/i18n.coffee` (seen [here](https://github.com/HabitRPG/habitrpg/pull/4873/files#diff-e13557fa7f5caa75169b3bf9de04edc0R3)), but @paglias already did a review of those adjustments.

Let me know if you encounter any issues!

**Comment by Alys** [comment]
Okay... Firstly note that I upgraded npm to 2.7.4 with `npm -g install npm@next` because I got sick of the constant EEXIST race condition errors I was getting. Npm install doesn't always do them, but it was consistently doing them today and I've had enough. I hope that doesn't invalidate my testing.

After that was done, `npm install` ran with only warnings. I can show you the full log if you wish.

`npm test` did this:

```
vagrant@habitrpg:/vagrant$ npm test

> habitrpg@0.0.0-152 test /vagrant
> ./test/run_tests.sh

Running "test:prepare:translations" task

Running "browserify:dist" (browserify) task

Running "stylus:build" (stylus) task
File website/build/app.css created.
File website/build/static.css created.

Done, without errors.
= Recreating test database
MongoDB shell version: 2.6.4
connecting to: habitrpg_test
[object Object]
Updating selenium standalone
downloading https://selenium.googlecode.com/files/selenium-server-standalone-2.37.0.jar...
Updating chromedriver
downloading https://chromedriver.storage.googleapis.com/2.7/chromedriver_linux64.zip...
chromedriver_2.7.zip downloaded to /vagrant/node_modules/protractor/selenium/chromedriver_2.7.zip
selenium-server-standalone-2.37.0.jar downloaded to /vagrant/node_modules/protractor/selenium/selenium-server-standalone-2.37.0.jar

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
Waited 30 seconds, but Selenium never responded
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
curl: (7) couldn't connect to host
npm ERR! Test failed.  See above for more details.
vagrant@habitrpg:/vagrant$ 
```

Running `npm test` a second time (and a third time) gives:

```
vagrant@habitrpg:/vagrant$ npm test

> habitrpg@0.0.0-152 test /vagrant
> ./test/run_tests.sh

Running "test:prepare:translations" task

Running "browserify:dist" (browserify) task

Running "stylus:build" (stylus) task
File website/build/app.css created.
File website/build/static.css created.

Done, without errors.
= Recreating test database
MongoDB shell version: 2.6.4
connecting to: habitrpg_test
[object Object]
selenium standalone is up to date.
chromedriver is up to date.

events.js:72
        throw er; // Unhandled 'error' event
              ^
Error: spawn ENOENT
    at errnoException (child_process.js:1011:11)
    at Process.ChildProcess._handle.onexit (child_process.js:802:34)
Waited 30 seconds, but Selenium never responded
kill: usage: kill [-s sigspec | -n signum | -sigspec] pid | jobspec ... or kill -l [sigspec]
curl: (7) couldn't connect to host
npm ERR! Test failed.  See above for more details.
vagrant@habitrpg:/vagrant$ 
```

I'm happy to do more, just let me know.

**Comment by gisikw** [comment]
Hi @Alys 

It looks like your tests are choking on the Selenium integration (where a Firefox browser gets spun up, and runs through actual page loads). None of that code is actually run on Travis, because of similar issues getting Selenium working in that environment.

I'm not sure what your vagrant environment looks like, but if you're running headless (without a windowing environment), there's gonna be some additional craziness. If you have a windowing environment, I'd check that Firefox is installed.

That said, none of these changes affect those end-to-end tests. So you could also simply run `TRAVIS=true npm test`, which will skip those, as is done with Travis.

For reference, there are only three end-to-end tests:
- Load the front page
- System doesn't log in with invalid credentials
- User registration works

Let me know if this works for you, and if I can be of any more help!

**Comment by Alys** [comment]
That's very useful information, thank you! My VM is headless. `TRAVIS=true npm test` produces many pretty tick marks! :)  Full output below. No errors.

I'm happy to merge this. @gisikw Can you think of any reason not to?

```
vagrant@habitrpg:/vagrant$ TRAVIS=true npm test

> habitrpg@0.0.0-152 test /vagrant
> ./test/run_tests.sh

Running "test:prepare:translations" task

Running "browserify:dist" (browserify) task

Running "stylus:build" (stylus) task
File website/build/app.css created.
File website/build/static.css created.

Done, without errors.
= Recreating test database
MongoDB shell version: 2.6.4
connecting to: habitrpg_test
[object Object]
= Running mocha specs


info: Express server listening on port 3000
  API
info: Connected with Mongoose
    Without token or user id
      ◦ /api/v2/status: GET /api/v2/status 200 26.740 ms - 15
      ✓ /api/v2/status (54ms)
      ◦ /api/v2/user: GET /api/v2/user 401 7.889 ms - 68
      ✓ /api/v2/user 
    With token and user id
[ { name: 'BASE_URL', content: 'http://localhost:3000' },
  { name: 'RECIPIENT_NAME',
    content: 'f141246e-5760-41fe-969c-a5cf32777849' } ] 'welcome' [ { name: 'f141246e-5760-41fe-969c-a5cf32777849',
    email: 'f141246e-5760-41fe-969c-a5cf32777849@gmail.com',
    canSend: true } ]
POST /api/v2/register 200 2151.974 ms - -
      Todos
        ◦ Archives old todos: POST /api/v2/user/batch-update?_v=999 200 125.317 ms - -
POST /api/v2/user/batch-update?_v=998 200 174.679 ms - -
POST /api/v2/user/batch-update?_v=997 200 87.778 ms - -
        ✓ Archives old todos (436ms)
      Groups
        Challenges
          - Creates a challenge
          - User updates challenge notes
          - Change challenge daily
          - Shows user notes on challenge page
          - Complete To-Dos
          - Challenge deleted, breaks task link
          - Admin creates a challenge
        Quests
          - Casts a spell
          - Doesn't include people who aren't participating
          - Hurts the boss
      Subscriptions
        - Handles unsubscription


  3 passing (5s)
  11 pending

= Running karma specs
Running "karma:continuous" (karma) task
INFO [karma]: Karma v0.10.10 server started at http://localhost:8080/
INFO [launcher]: Starting browser PhantomJS
INFO [PhantomJS 1.9.8 (Linux)]: Connected on socket _UbxNufeQE_8LcMsRNhE

Start:
  Auth Controller
    AuthCtrl
      ✔ should log in users with correct uname / pass
      ✔ should not log in users with incorrect uname / pass
  Filters Controller
    ✔ creates a tag
    ✔ toggles tag filtering
  groupServices
    ✔ calls party endpoint
    ✔ calls tavern endpoint
    ✔ calls public guilds endpoint
    ✔ calls my guilds endpoint
  Inventory Controller
    ✔ starts without any item selected
    ✔ chooses an egg
    ✔ chooses a potion
    ✔ hatches a pet
    ✔ sells an egg
    ✔ sells a potion
    ✔ sells food
    ✔ chooses a pet
    ✔ purchases an egg
  memberServices
    ✔ has no members at the beginning
    ✔ populates members
    ✔ selects a member
  notificationServices
    ✔ notifies coins amount
  Root Controller
    ✔ shows contributor level text
  userServices
    ✔ checks online status
    ✔ saves user data to local storage
    ✔ alerts when not authenticated
    ✔ puts items in que queue

Finished in 2.58 secs / 0.102 secs

SUMMARY:
✔ 26 tests completed

Done, without errors.
vagrant@habitrpg:/vagrant$ 
```

**Comment by gisikw** [comment]
@Alys nope, this should be set to go. I rebased my local against the latest upstream develop branch, and all the tests pass including the e2e stuff. :)

Merge away!

**Comment by gisikw** [comment]
Wheee! My first PR! :grinning:

**Comment by Alys** [comment]
Someone should probably get a contributor Tier for this. We'll see to that just as soon as we stop screaming excitedly. :)

@gisikw UUID?

**Comment by gisikw** [comment]
@Alys `ad0bb2e4-28d0-41c9-83bd-617b8b032445`, with my thanks :)

**Comment by Alys** [comment]
No, thank YOU!

Tiers 1 and 2 awarded because this involved more effort than a normal first contribution.

**Comment by crookedneighbor** [comment]
:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Pull request merged**
