### PR TITLE
Change "Wizard" to "Mage" in member modal & inventory

### PR DESCRIPTION
**Pull request by deilann**
Fixes displays so that member modal correctly displays mage class as "Mage" and in the inventory mage armor is under "Mage."

### CODE REVIEW

**Comment by DanielTheBard** [comment]
Oh awesome! I was just looking through the code to see if I could fix this myself. Awesome! aha. I'll close my issue now then.

**Comment by deilann** [comment]
It's because I'm a ~~wizard~~ mage now.

**Comment by deilann** [comment]
Okay, so the build failed, and I have no idea why. Something to do with API, which I didn't touch? Quite literally swapped the word "Wizard" for the word "Mage"

It runs perfectly on my local. No idea.

**Comment by lefnire** [comment]
the e2e tests were borked with the front page redesign, unrelated. Still trying to figure out how to handle that

**Pull request merged**
