### PR TITLE
Group title on route fix

### LINKED ISSUE #12739: HTML page Title tag for Guild contains the previous Guild's name
When you go from one Guild directly to another, the page title does not update itself. 

Steps to reproduce:

1. Wait until you have a notification for new messages from any Guild. Do not dismiss the notification!
1. Go to Tasks and reload the website to clear any old data.
1. Go to Guilds > Discover Guilds.
1. Click any Guild.
1. Observe that the page title correctly displays the name of the Guild. (NB the title will say "Group Plans" instead of "Guilds" but that's logged separately: #12738).
1. Visit a different Guild by using the link in your notification about a new message. 
1. Observe that the previous Guild's name is still shown in the page title. See the screenshot below from Nakonana.

This was reported by @Nakonana (her post is below for posterity :smiley:) and by @citrusella (who says it may be intermittent) and reproduced by me a few times (with my Habitica-related extensions and styles disabled).

image

---

@Nakonana wrote:
_"Ahoy, Admirals! It appears, th' squirrels' ship be sailin' under th' pirates' flag recently. I be knowin' fer bein' a navigator on th' pirates' ship me sense o' orientation be all but great, yet I did not expect I would board th' wrong ship! Aarrrr! xDDD_

_Jokes aside: there seems t' be a small bug with th' new feature that names tabs in accordance t' one's current location in th' Habitican seas, but it looks like th' GPS system be a bit broken (or just slow, because 'tis not 2020 in Habitica yet, right? xD). As a result, th' tab name be displayin' th' previous location instead o' th' current location. Th' problem can be solved by reloadin' th' tab._

_Now, that certainly won't help with me sense o' orientation, aarrr!_

_(Win 10, Firefox 82.0.2, see screenshot above for possible Extensions interference)_

### PR DESCRIPTION
**Pull request by jbusa22**
Fixes #12739

### Changes

Added setTitle to fetchGuild function so that in places like notifications where it can call router.push from the guild page, should be updated correctly

----
UUID: 7f566b3a-3b43-4035-b712-8ddef3e82a71

### CODE REVIEW

**Comment by jbusa22** [comment]
Not sure how to fix this I tried git fetch and git pull upstream with no luck

**Comment by jbusa22** [comment]
I have no idea why there are so many commits. I tried pulling upstream with no luck

**Comment by paglias** [comment]
@jbusa22 I'd suggest to maybe use an UI for git / github to make it easier to work with PRs, something like Github Desktop

**Comment by paglias** [comment]
@jbusa22 I'm merging the PR and noting in your profile, I merged it anyway because we're squashing commits and only 1 is ending up in `develop` but for the next time I'd suggest to use a GUI software to make sure only the necessary commits are included, thanks!

**Pull request merged**
