### PR TITLE
Challenges spacing fix 

### PR DESCRIPTION
**Pull request by thepeopleseason**
Previously referenced in issue #2776, this code fixes spacing issues in the display of challenges.

### CODE REVIEW

**Comment by thepeopleseason** [comment]
Closing: These changes should be added in the locales files under habitrpg-shared.

**Comment by paglias** [comment]
We like to avoid spaces at the end or at the beginning of strings in locales because they are not supported by our translation management software and are easy to forget.

**Comment by thepeopleseason** [comment]
Ah! Good to know. Thanks.

**Comment by thepeopleseason** [comment]
Reopening to use jade to render spaces instead of locale strings. Added another fix for contrib Modal.

**Comment by paglias** [comment]
Another option is to use the html entity for spaces `&nbsp;`

But that's ok, merging

**Pull request merged**
