### PR TITLE
making export to csv export everything (issue #2947)

### PR DESCRIPTION
**Pull request by Verabird**
changed the api.csv function only

### CODE REVIEW

**Comment by negue** [comment]
Is it just my browser or is there something wrong with the pullrequest (I'm not talking about your code changes, which I can't see right now)

But I have " +1 −402 " (Lines Changed)

Is it a line-ending problem? But this shouldn't this be handled by github?

**Comment by Verabird** [comment]
Yes, it does say that. I don't know why that happened-it says that in the git commit in my local version too. Do you (or anybody else) happen to know how I can fix this or prevent it in the future?

**Comment by negue** [comment]
At first I thought it was a CRLF Bug, but I opened both raw files in editor, in both files I saw "CRLF" ... so i guess no error there :(

Sorry, but I hope someone else knows more about this.

**Comment by lefnire** [comment]
If you look at the commits, it shows you (1) deleted a file, (2) then reverted that deletion commit, bringing us back to 0. You may wanna close this PR and open a new one

**Pull request closed without merging**
