### PR TITLE
Add <button> and focus styles for keyboard users

### LINKED ISSUE #9796: keyboard (tab button, etc) can no longer be used to complete tasks, buy Rewards
_I have a feeling we have this recorded or being worked on elsewhere but I can't find it. If anyone knows it's a duplicate or in progress, please add a comment._

As described in the "Use of Tab" section in [Accessibility](http://habitica.wikia.com/wiki/Accessibility), the old website had more features that were accessible through the keyboard than the new one. citrusella, the serving wench wrote in the Report a Bug guild:

"Out of the things listed in the article, the elements for checking off a task/reward can't be tabbed onto."

"(For extra reference, they also can't be accessed using the "show numbers" command in my computer's stock speech recognition software (a command that displays the "number" of each selectable piece on a page for easy voice selection), which I believe uses the same logic for choosing what's selectable; I know in the past that "show numbers" did include the checkoffs/plus/minus/etc. (though it was unmanageable because there were too many in that case) but in the new interface there is very little of the task area available for selection that manner.)"

"The accessibility Trello card has had what feels like an uptick in people asking keyboard accessibility, so while it's not clear they've run into this change specifically, there's definitely demand for keyboard navigation, both for people who just want it and those who need it."

### PR DESCRIPTION
**Pull request by ianoxley**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #9796 

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
Use the `<button>` tag instead of a `<div>` for:

- The habit +/- buttons
- Reward controls
- Dropdown toggle menus

This makes the HTML more semantic, and allows the element to naturally:

1. Receive focus via the keyboard
2. Be activated via the `<space>` key

Update the CSS to align the icons in the centre of the habit +/- `<button>`.

Add `:focus` styles to match the `:hover` styles for the dropdown toggle menus.

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: c5085c21-2d4a-4707-a178-0d547329095a

### CODE REVIEW

**Comment by paglias** [comment]
@ianoxley thanks for this!

It works well but there are some UI issues

schermata 2018-11-17 alle 10 56 34

^ gray area around the options dropdown

schermata 2018-11-17 alle 10 56 15

^ wrong positioning of some options in the edit screen

**Comment by ianoxley** [comment]
@paglias OK, I'll look into those. Which browser are your screenshots from?

**Comment by paglias** [comment]
@ianoxley sorry, I forgot to specify the browser: it's Firefox on mac os

**Comment by ianoxley** [comment]
@paglias I've added some fixes for those couple of issues you highlighted above. Let me know if there's anything else I've missed.

**Comment by paglias** [comment]
@ianoxley sorry for the delay! I tested this again and the initial issues have been fixed, but there's a small problem with the user and notifications button on the top right. I've reproduced the issue in both Chrome and Firefox.

schermata 2018-11-26 alle 10 50 35

**Comment by ianoxley** [comment]
@paglias I noticed some issues with using a `<button>` tag here when working on #10865 (you could end up with invalid, incorrectly nested HTML), so I've used ARIA role and keypress handlers instead. The default button styles no longer show up.

**Comment by paglias** [comment]
@ianoxley it's almost ready :)

There are two small remaining issues (at least on Firefox): The menus get a weird border around them when opened (probably something to do with selection styles) and the notifications have some positioning issue on the right, I'll attach screenshots

schermata 2018-12-04 alle 10 02 07
schermata 2018-12-04 alle 10 01 45
schermata 2018-12-04 alle 10 01 25
schermata 2018-12-04 alle 10 01 33

**Comment by ianoxley** [comment]
@paglias I've added fixes for these couple of issues. Let me know if there's anything else untoward.

**Comment by paglias** [comment]
@ianoxley sorry about this and for the delay but there are still some outlines appearing 
schermata 2018-12-23 alle 19 58 08
schermata 2018-12-23 alle 19 57 50
schermata 2018-12-23 alle 19 57 46

**Comment by ianoxley** [comment]
@paglias I think we'd need the outline around the actual buttons themselves. That lets keyboard users know when those elements have focus, so they can still open the menus, etc.

**Comment by paglias** [comment]
Pinging @Tressley on this but unless we can distinguish between tab-selection and opened-by-click scenarios I don't think we want to show the outline as it'll be shown for every user even when using the mouse. The outline isn't shown for dailies checkboxes and other elements and there we rely on the hover state that is also used when a dropdown menu is selected using the tab

**Comment by Tressley** [comment]
@paglias -- That's actually pretty common as clicking on an object naturally invokes the focus/active state. With that being said, I'd prefer the outline be a bit more subtle, similar to the states I've outlined here: https://zpl.io/VQXq0W2

**Comment by ianoxley** [comment]
@Tressley Any chance I could get access to that Zeplin? If not, could you post some screenshots on here please?

**Comment by Tressley** [comment]
Hey @ianoxley, sorry for the delay in getting back to you! I spoke with @paglias a bit more about the changes and I agree that we want to remove the dotted outline. With your changes, the focus state will continue to look similar to the hover state, but that's something we're aware of and can start to design for (increased accessibility is definitely on our radar.) Unfortunately, the Zeplin artboard I linked above only references button styles, not icons.

Here's a quick screenshot:

image

If you're still interested in being a part of our Zeplin project, can I send an invite to ian.oxley@sage.com?

**Comment by ianoxley** [comment]
@Tressley That'd be useful, thanks 👍

**Comment by ianoxley** [comment]
I'm not sure how to take this forwards now. We need some visual indication for which element has focus, otherwise keyboard users will have a hard time knowing where they are on the page.

One idea is to do something similar to what GitHub do. They appear to attach a class `intent-mouse` to the `<body>` element when the mouse first clicks on a page element. This class is then used as hook to remove the visual `outline` CSS for mouse users for the element that has focus. If a `<Tab>` keypress is detected then that `intent-mouse` class is removed and the `outline` CSS reappears for keyboard users.

@paglias @Tressley What do you think about implementing something similar to this?

**Comment by paglias** [comment]
@ianoxley sorry for the delay, I think that the decision was that for now we would like the outline to be removed and the visual indication for the element being selected would come from the `focused` state that already exists and is similar to the `hovered` state for the various buttons, then we have planned on increasing accessibility and would like to make it more clear but as a future update

**Comment by ianoxley** [comment]
@paglias Sorry for the delay, but I've made the changes you requested: the focus style should now match the hover style.

If there's any more issues let me know.

**Comment by paglias** [comment]
@ianoxley no worries for the delay!

I know I'm being annoying but it looks like there are a couple of remaining issues:

Schermata 2019-03-21 alle 16 07 55
Schermata 2019-03-21 alle 16 08 04

**Comment by ianoxley** [comment]
@paglias OK, no problem, I'll investigate that once I've got my local install working again.

I pulled down the `merge from 'develop'` commit but now I get the following error when I run `npm start`:

```
Error: Mode must be "sandbox" or "live"
    at Object.configure (/usr/src/habitrpg/node_modules/paypal-rest-sdk/lib/api.js:26:15)
    at Object.configure (/usr/src/habitrpg/node_modules/paypal-rest-sdk/lib/paypal-rest-sdk.js:10:13)
    at Object.<anonymous> (/usr/src/habitrpg/website/server/libs/payments/paypal.js:34:8)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at loader (/usr/src/habitrpg/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/src/habitrpg/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/src/habitrpg/website/server/models/user/methods.js:22:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at loader (/usr/src/habitrpg/node_modules/babel-register/lib/node.js:144:5)
    at Object.require.extensions.(anonymous function) [as .js] (/usr/src/habitrpg/node_modules/babel-register/lib/node.js:154:7)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:22:18)
    at Object.<anonymous> (/usr/src/habitrpg/website/server/models/user/index.js:6:1)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
```
Any ideas what I might be missing?
AFAIK my config.json hasn't changed.

**Comment by paglias** [comment]
We have recently updated our config file so if you copy the content of
config.json.example to your config.json file it should work

Il Ven 22 Mar 2019, 00:03 Ian Oxley <notifications@github.com> ha scritto:

**Comment by paglias** [comment]
thanks @ianoxley ! It's working great and it'll go live next week. Welcome to the 2nd tier :)

**Comment by paglias** [comment]
After some live testing we decided to take this down as we'd like to first optimize the order of items accessed by using TAB. We'll use your PR as a base and will merge it when some changes have been made

**Comment by ianoxley** [comment]
OK, no worries. Let me know if I can help with anything.

**Pull request merged**
