### PR TITLE
Turtleheads (Fixes #8560)

### LINKED ISSUE #8560: columns on mount page are too narrow for Turtle flippers
The "heads" of the Turtle mounts are wider than of the other mounts and the columns on the Mounts page haven't been sized to accommodate them neatly (see screenshot below).

This is probably just a simple CSS fix, but if for some reason it turns out to be at all complex, it would be best to leave this to be fixed in a website improvement project that we're part way through.

image

### PR DESCRIPTION
**Pull request by kvsm**
Fixes #8560

### Changes
Added new turtle head icons and recompiled sprites.

----
UUID: 176cc46d-af71-4a98-a89b-8bc4babfbaf5

### CODE REVIEW

**Comment by kvsm** [comment]
Huh, that's a bunch of conflicts.  When submitting a PR with new sprites, is it standard practice to not bother recompiling the spritesheets and just commit the new source sprites, and for these to be recompiled later?

**Comment by TheHollidayInn** [comment]
When adding sprites you do want to recompile. To fix these merge conflicts, just recompile them again.

**Comment by TheHollidayInn** [comment]
This works locally, and looks great :D. If you fix the merge conflicts, I'll merge this.

**Comment by kvsm** [comment]
Done!

**Comment by TheHollidayInn** [comment]
Congratz on Tier 2!

**Pull request merged**
