### PR TITLE
Adjust error messages on home page to prompt user to use facebook login

### LINKED ISSUE #5103: facebook login is too hard to remember - add reminders for failed logins
Surprisingly often, people report that they can't log in (e.g., username or email not accepted) and it turns out that they registered with Facebook but had forgotten they'd done that.

Can we have reminders in a couple of places? For example, in each of the dialog boxes below, could we have a new message under the current message that says something like "Perhaps you registered with Facebook? If you might have, please try logging in with Facebook."

@lemoness @anitaycheng What do you think?

screen shot 2015-04-16 at 10 26 01 am

screen shot 2015-04-16 at 10 25 46 am

### PR DESCRIPTION
**Pull request by cavejay**
fixes #5103
Altered the error messages that are part of the login and forgotten password processes.
These messages now remind the the user that they may have created an account through facebook.

Screenshots:
screenshot from 2015-05-01 13 05 25
screenshot from 2015-05-01 13 06 03

### CODE REVIEW

**Comment by crookedneighbor** [comment]
This integration test needs to be updated with the new wording: https://github.com/HabitRPG/habitrpg/blob/develop/test/e2e/e2e.js#L40

**Comment by crookedneighbor** [comment]
Beautiful!

This will count towards a contributor tier! What's your User ID? You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api). Be sure to only copy the User ID and _not_ your API Token.

**Comment by cavejay** [comment]
Awesome! :D 
My user is: d4202f2f-0177-4c32-b115-09e1b64240bf

**Comment by crookedneighbor** [comment]
Tier awarded!

**Pull request merged**
