### PR TITLE
Checked off Task Achievement [WIP]

### LINKED ISSUE #8663: New Achievements and Badges: Checked off X Tasks
These new achievements and badges are ready to be implemented! These should be received when a player checks off the number of tasks indicated by each badge. The badge images and the names/mouseover text for the user achievement page can be found here:

https://trello.com/c/PMBVCiyv/4-checked-off-x-tasks-badges

### PR DESCRIPTION
**Pull request by librarianmage**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #8663 

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

Adds the "Checked off X Tasks" achievement specified in #8663 

#### Required:
* [ ] Display of achievement
* [ ] Tests

[//]: # (Put User ID in here - found in Settings -> API)

----
UUID:

### CODE REVIEW

**Comment by SabreCat** [comment]
Flagging this with the "needs work" label because you listed it as a WIP, @MathWhiz -- be sure to let us know once you feel it's ready for review!

**Comment by librarianmage** [comment]
Will do! I should probably wait until the website design update, to make
sure it works.

**Comment by SabreCat** [comment]
OK, I'm going to close this PR for the moment, then. Feel free to open it back up if you feel it's getting closer to completion!

**Comment by librarianmage** [comment]
Ok, will do. Do you have any idea on approximately when the update will
come out?

**Pull request closed without merging**
