### PR TITLE
Fixed a task tag tooltip position

### LINKED ISSUE #9905: Task tag tooltip has incorrect margins
The tooltip for displaying tags on a Task is being pushed down by an incorrect margin.
  * Browser: Chrome Version 64.0.3282.119 (Official Build) (64-bit), Firefox Quantum 58.0 (64-bit), Safari Version 11.0.2
  * OS: macOS High Sierra 10.13.2

image

### PR DESCRIPTION
**Pull request by lex111**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #9905 

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

Before
image

After
image

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 2d57fd14-0fd1-4bf5-abe9-d65bb42fbc6f

### CODE REVIEW

**Comment by negue** [comment]
LGTM 👍

**Comment by Tressley** [comment]
Looks good! 👍

**Comment by paglias** [comment]
@lex111 can you post your UUID so i can record this in your contribution notes? Thanks!

**Comment by lex111** [comment]
@negue my UUID - 2d57fd14-0fd1-4bf5-abe9-d65bb42fbc6f

**Pull request merged**
