### PR TITLE
Removed unused I18N strings from the `subscriber.json` files (related to issue #9957)

### PR DESCRIPTION
**Pull request by RaitheOfDureya**
[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
This PR fixes part of issue #9957

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
I have identified the following unused strings in the `subscriber.json` file.  I also checked if the strings were being generated dynamically, but I didn't find any cases in this file.

At the moment I only removed the strings from the `locales/en` folder to make it easier to revert if necessary. Once the strings are reviewed, I can delete them from other languages.

- subDescription
- buyGemsGoldText
- retainHistory
- retainHistoryText
- doubleDrops
- doubleDropsText
- supportDevs
- supportDevsText
- exclusiveJackalopePetText
- giftSubscriptionText1
- giftSubscriptionText2
- giftSubscriptionText3
- monthUSD
- organization
- indivPlan1
- indivPlan2
- groupText1
- groupText2
- planFamily
- planGroup
- dedicatedHost
- dedicatedHostText
- individualSub
- subscribed
- manageSub
- cancelSubInfoGoogle
- cancelSubInfoApple
- canceledSubscription
- adminSub
- morePlans
- organizationSub
- organizationSubText
- hostingType
- hostingTypeText
- dedicated
- customDomain
- customDomainText
- maxPlayers
- maxPlayersText
- unlimited
- priSupport
- priSupportText
- timeSupport
- timeSupportText
- gameFeatures
- gold2Gem
- gold2GemText
- infiniteGem
- infiniteGemText
- notYetPlan
- subCanceled
- buyGemsGoldTitle
- becomeSubscriber
- freeGemsTitle
- buyGemsAllow1
- buyGemsAllow2
- purchaseGemsSeparately
- subFreeGemsHow
- seeSubscriptionDetails
- timeTravelersTitleNoSub
- timeTravelersTitle
- timeTravelersPopoverNoSub
- mysticHourglassPopover
- hourglassBuyEquipSetConfirm
- hourglassBuyItemConfirm
- earnGemsMonthly
- receiveMysticHourglass
- receiveMysticHourglasses
- everyMonth
- everyXMonths
- everyYear
- subscribeSupportsDevs
- subscriptionBenefitLeadin
- subscriptionBenefit2
- haveCouponCode
- subscriptionAlreadySubscribed1
- petsNotAllowedHourglass
- mountsNotAllowedHourglass
- timeTravelersAlreadyOwned

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 6544e17f-237b-4915-ae7e-47744c0dc1bd

### CODE REVIEW

**Comment by paglias** [comment]
This is looking good, thanks @RaitheOfDureya

**Comment by paglias** [comment]
Could you also remove these two extra strings?

```
gemsPurchaseNote
subscriptionAlreadySubscribedLeadIn
```

They're going to be removed in an upcoming PR

**Comment by RaitheOfDureya** [comment]
@paglias done!

**Comment by paglias** [comment]
thanks @RaitheOfDureya ! noted towards your 5th tier!

**Comment by RaitheOfDureya** [comment]
After seeing @shanaqui 's [comment](https://github.com/HabitRPG/habitica/issues/9957#issuecomment-695835018) I found the following piece of code (in: `website/client/src/components/settings/subscription.vue`) which indicates that not only `cancelSubInfoApple` is being used, but also `cancelSubInfoGoogle`

```javascript
getCancelSubInfo () {
      let payMethod = this.user.purchased.plan.paymentMethod || '';
      if (payMethod === 'Group Plan') payMethod = 'GroupPlan';
      return this.$t(`cancelSubInfo${payMethod}`);
```

Looking in detail and redoing my searches I found that these keys were passed dynamically and could be found using the regex `\$t\((?!')`. I must have overlooked, sorry for that.

**Comment by paglias** [comment]
No worries @RaitheOfDureya ! I will add back the strings

**Pull request merged**
