### PR TITLE
[WIP] Block or whitelist specific banned word lists, fixes #8813

### LINKED ISSUE #8813: certain kinds of swear words / oaths should be blocked in guilds
~This is on hold until the PR for https://github.com/HabitRPG/habitica/issues/8062 is completed (automatic muting of slurs), since there'll probably be code in that PR that can be repurposed for this issue.~ EDIT: We're now considering which words to block where.

In https://github.com/HabitRPG/habitica/pull/8197 , we prevented swear words, slurs, etc being posted to the Tavern and that's been working very well. We want it extended to public guilds, although with a more limited set of words. For example, in the Tavern, it's not permitted to mention legal addictive substances such as certain drinks, however those words would not be blocked in public guilds. 

We'll give more details about what should be blocked elsewhere after https://github.com/HabitRPG/habitica/issues/8062  is fixed. For now, this is just a placeholder issue so that we don't forget about this.

### PR DESCRIPTION
**Pull request by abatula**
Fixes #8813

### Changes
Work in progress. 

Allow guilds to whitelist specific sets of banned words.

Functionality: 
[ ] Change chat to use new banned word file
[ ] Add list of whitelisted categories to guilds
[ ] Check for whitelisting before blocking a post

Tests:
[x] Block all categories in Tavern
[x] Check whitelisting in public guild

----
UUID: f5a68145-b375-4b99-8fb4-f9ff7a2c52b5

### CODE REVIEW

**Comment by librarianmage** [comment]
Hi @abatula! How are you doing on this?

**Comment by abatula** [comment]
@MathWhiz I think I finally fixed my local install of Habitica, so I'm hoping to be able to get back to it soon.

**Comment by librarianmage** [comment]
Hello @abatula! Were you able to fix your local install of Habitica?

**Comment by abatula** [comment]
@MathWhiz I did, but shortly after my MongoDB stopped working. Given the number of system problems I'm having, I don't mind if someone else wants to finish this.

**Comment by lemoness** [comment]
I've updated the labels to indicate that this PR has been abandoned and needs to be reviewed by our devs.

**Pull request closed without merging**
