### PR TITLE
 #4618 Use new icons for mounts

### PR DESCRIPTION
**Pull request by joyheron**
Working on  #4618 to use new mount icons instead of the old Mount_Head images.

### CODE REVIEW

**Comment by joyheron** [comment]
My local installation is currently extremely out of date and not working, so I haven't generated the new css files yet. I will try to get it working to test the fix out and to get some screenshots.

**Comment by joyheron** [comment]
Ok, I managed to generate the css files and sprite sheets, but my local installation still doesn't work. Or rather, I can start the application, but I can't log into any account (I get a 401 Unauthorized) when I hit 'Join For Free' so I can't even view the files.

**Comment by SabreCat** [comment]
@joyclark: Have you created a new account on the local site? Local installs of Habitica don't use the same database as the official server, so the account you use on Habit day-to-day won't exist there. You can also get help with running a local instance in the [Aspiring Coders guild](https://habitica.com/#/options/groups/guilds/68d4a01e-db97-4786-8ee3-05d612c5af6f)!

**Comment by joyheron** [comment]
@SabreCat I wasn't able to create a local account. I used to have a working local installation (about 6 months ago), but when I updated my branch I also reset the database (which I now realize might not have been the smartest decision). Unfortunately, I get the error before I can create a user. I am trying to set up an installation on another computer now, and I have asked the Aspiring Coders guild for help since I got a (different) error there. :S

**Comment by Alys** [comment]
@joyclark try deleting local storage in your browser for the localhost domain. That has a good chance of fixing it.

Deleting the database won't have had any serious affects, except that you need to set up new test users again. Best to delete it anyway after a break because the user model changes over time and old users can have missing features that can cause bugs.

**Comment by joyheron** [comment]
mounts1

**Comment by joyheron** [comment]
mounts2

**Comment by joyheron** [comment]
mounts3

**Comment by joyheron** [comment]
mounts4

**Comment by joyheron** [comment]
mounts5

**Comment by joyheron** [comment]
mounts6

**Comment by joyheron** [comment]
Clearing my browser cache worked, so I was able to create a new test environment. I uploaded the screenshots of the new images.

As stated before, we still need:
- some gryphons (Red, RoyalPurple, Shade, Skeleton, White, Zombie)
- frogs
- spooky and peppermint animals
- the Phoenix
- the JackOLantern

And also...the tiger heads are still too wide so they aren't in alignment with the other artwork.

**Comment by SabreCat** [comment]
Ping @lemoness so she can take a look at what we've got so far!

**Comment by crookedneighbor** [comment]
I've fixed the gryphons, tigers, spooky and peppermint mounts and merged it in.

Still needed: 
- frogs
- phoenix
- jackolantern

I also noticed that many of the mount icons did not have transparent backgrounds :disappointed: Will work for now, but in the long haul, that should be fixed.

**Comment by crookedneighbor** [comment]
I've notated this toward your next tier. Thanks for the hard work on this!

**Pull request merged**
