### PR TITLE
chore(travis): remove travis config until the issues are resolved

### PR DESCRIPTION
**Pull request by denis-sokolov**
Travis builds have not succeeded since forever.
Keeping that badge and cross only confuses people and scares contributors away.

### CODE REVIEW

**Comment by deilann** [comment]
I agree with this. If we know they are going to fail at the moment, it's a big problem.

**Comment by colegleason** [comment]
I would rather disable/remove/rewrite the failing tests than remove Travis.

**Comment by denis-sokolov** [comment]
@colegleason, it's not that some tests are failing, but the environment in Travis is has setup problems. [See an example](https://travis-ci.org/HabitRPG/habitrpg/builds/18978428).
It seems that perhaps there's an API limit somewhere, or Selenium is not installed properly, or whatever. There is no useful information in those build messages at all, if I am correct.

**Comment by lefnire** [comment]
Seems to be the client stuff - selenium / e2e. Can we keep int he API tests?

**Comment by denis-sokolov** [comment]
I will experiment with it, then.

**Comment by denis-sokolov** [comment]
**Do not merge yet, this is an experiment**.

My first experiments led to an advance - a first green build in forever, it runs API tests, even though one of them fails. The main problem was relying on a setTimeout instead of a proper callback for the server to start. This will need to be fixed properly.

I will continue research some other day.

**Comment by denis-sokolov** [comment]
This passes! Please accept the pull request.

**Comment by lefnire** [comment]
@djuretic signoff?

**Comment by djuretic** [comment]
I'm ok with disabling Selenium tests on Travis, those are only basic tests so they aren't very important yet.

**Comment by lefnire** [comment]
Sounds good! TBH, this stuff has always been over my head - so let me know if any issues @djuretic, merging now. Thanks @denis-sokolov, UUID?

**Comment by denis-sokolov** [comment]
Yeay, thanks for merging! Green build is important.

@lefnire, `b1ca8a94-d649-4ca5-8daa-764a79e04a05`.

**Comment by paglias** [comment]
@denis-sokolov now even with 1 failing test https://travis-ci.org/HabitRPG/habitrpg#L2968 it says the build passes

**Comment by lefnire** [comment]
@denis-sokolov √

**Pull request merged**
