### PR TITLE
Fixed subscription popup too narrow in Japanese

### LINKED ISSUE #8581: Subscription popup is too narrow in Japanese
General Info
  * UUID: 203f208a-e0f0-4442-bf16-d4f19e553e8a
  * Browser: Chromium 56.0.2924.76
  * OS: Ubuntu 16.04 (64-bit)

### Description
[//]: # (Describe bug in detail here. Include pictures if helpful.)
As I changed my user language to Japanese (Settings -> Site -> Language -> 日本語), I noticed that the text of the subscription button popup is near illegible.
Here an image showing how it appears:

Image of bug

I would like to try resolving this bug myself, may I? I already have set up habitica locally.
I'm starting now so tips are very welcome.

(I searched on the current issues but didn't find anything about this, sorry if it is a known issue...)

### PR DESCRIPTION
**Pull request by Yutsuten**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #8581 

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
The best approach to resolve the problem I found was to add a minimum width to the subscription button. I hope its okay.

Before:
Image of bug

Now:
Image of fix

[//]: # (Put User ID in here - found in Settings -> API)

----
UUID: 203f208a-e0f0-4442-bf16-d4f19e553e8a

### CODE REVIEW

**Comment by Yutsuten** [comment]
Sorry for the question, but may I know what this PR and #8584 are waiting for? They're ready for review or merge, but no one in the staff showed intention to do anything with them until now.
I do want to make the difference to Habitica, but I'm feeling that my PRs are being ignored...

If I'm doing anything wrong, please tell me.
Anyway, I hope I'm just over-worried...

**Comment by paglias** [comment]
@mateus-etto you're not doing anything wrong but we're a small team and it's possible that you'll have to wait a bit before your PRs are reviewed. Also we've started adopting a 2 weeks release cycle   that means one week is dedicated to testing and the other to merging PRs and new code

**Comment by TheHollidayInn** [comment]
This change looks fine to me.

**Comment by TheHollidayInn** [comment]
Credited towards your Tier progress. Congratz on Tier 2!

**Pull request merged**
