### PR TITLE
fix(locales/ru): missed translations

### PR DESCRIPTION
**Pull request by pleshevskiy**
[//]: # (Note: See https://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
Fixed missing translations for the RU locale.

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)
----
UUID: 0d4cd566-cece-4507-84ea-807a9eb23499

### CODE REVIEW

**Comment by CuriousMagpie** [comment]
Hi there, @pleshevskiy! Thanks for your contribution. However, for translations we use a service called Weblate. You can make an account at [https://habitica.weblate.com ](https://habitica.weblate.com) and update the missing strings there. You may also be interested in [Commonwealth of i18n (Aspiring Linguists)](https://habitica.com/groups/guild/52f49529-58c1-4020-a59b-8bb8579e941f) in Habitica itself.

**Comment by pleshevskiy** [comment]
@CuriousMagpie understood. The website at the link (https://habitica.weblate.com/) doesn't open :cry:

**Comment by CuriousMagpie** [comment]
Sorry about that--try [translate.habitica.com](https://translate.habitica.com/)!

**Comment by Alys** [comment]
@pleshevskiy Please also see [Guidance for Linguists](https://habitica.fandom.com/wiki/Guidance_for_Linguists) on the wiki - that will give you a lot of important detail about the translation process.

**Pull request closed without merging**
