### PR TITLE
Align both achievement popups (hover vs. click) { Continued in #8798 }

### LINKED ISSUE #8510: Alignment issue with popovers on profile -> achievements
General Info
  * UUID: ff7a63c1-0026-4bc3-9e72-478761ce0021
  * Browser: Chrome 56
  * OS: Windows 10 x64

### Description
When hovering over achievements in the relevant profile tab, if you click on an achievement to make the popover stay, it is a few pixels out of alignment with the on-mouseover version, causing a slight shift on animating in/out.

Sorry for the gif quality.
repro

### PR DESCRIPTION
**Pull request by liamdawson**
Fixes #8510

### Changes
Adjusted heights (via style tags - open to suggestions on better ways) of the div and button sequence for the achievement visuals to fix an alignment issue that occurs between showing the popover using mouse-over vs click.

----
UUID: ff7a63c1-0026-4bc3-9e72-478761ce0021

### CODE REVIEW

**Comment by TheHollidayInn** [comment]
Thanks for submitting!

Two things:
1. Can you post screenshots of before and after so it is easier to see the fix
2. Can you move the inline styles to stylus?

**Comment by khipkin** [comment]
Thanks for fixing this, @liamdawson! I knew it was an issue with my original PR, but it was too low-priority to spend time fixing since the PR was blocking the mobile apps.

**Comment by SabreCat** [comment]
Continued in #8798. Closing this one!

**Comment by SabreCat** [comment]
Welcome to Blacksmith tier 1, btw @liamdawson!

**Pull request closed without merging**
