### PR TITLE
update translatable strings

### PR DESCRIPTION
**Pull request by matheusvictor**
### Changes
[//]: # I want contribute with Habitica translation. So, I did try add some strings to translatable

[//]: # UUID: 8eb82b0c-14c4-4c1e-81a8-99f634104e6a

### CODE REVIEW

**Comment by Alys** [comment]
@matheusvictor Thanks for looking into this!

For `hideBackground` and `groupPlanSubTitle`, would you like to make changes to the code so that those strings are used? It's often best to have the code changes made at the same time that the strings are added to ensure the strings do get used. If someone makes the code changes later, they might not realise that the strings already exists and they might create duplicates.

FYI for the staff to make sure this is noticed:
This pull request also edits "Need more for your crew?" (the `groupPlanTitle` string), to change "crew" to "Group", so that would need to be considered for approval.

**Comment by paglias** [comment]
Hi @matheusvictor , do you have any update on this PR?

**Comment by matheusvictor** [comment]
> Hello, @paglias. I did not any updates on this PR because I'm no sure if I follow correctly all steps to translatable strings, so I decided wait for a analysis by Staff 😺

**Comment by paglias** [comment]
@matheusvictor currently the PR adds two new strings, `hideBackground` and `groupPlanSubTitle` but they're not used anywhere in the code base so they won't appear on the website untile the code is changed to use them

**Pull request closed without merging**
