### PR TITLE
Fixed double scrollbar when modal is called

### LINKED ISSUE #9863: Double scrollbar when using modals
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
UUID: 2d57fd14-0fd1-4bf5-abe9-d65bb42fbc6f
Browser: Google Chrome 63.0.3239.132
OS: Ubuntu 17.04

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)
When you open any modal window, a second vertical scroll appears. It seems to me to remove the scrolling of the page and leave only the scrolling of the modal window.

image

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

### PR DESCRIPTION
**Pull request by lex111**
Fixes #9863

### CODE REVIEW

**Comment by TheHollidayInn** [comment]
Thanks! This PR does fix, but as I said in the issue, we do need to verify the modals don't prevent the body from scrolling before merging this.

**Comment by lex111** [comment]
Scrolling will be if the modal does not fit in the screen, for example, if with large content.

**Comment by TheHollidayInn** [comment]
Yea, that's fine. I'm saying we had an issue where when a modal is dismissed scrolling is prevented. This happens because bootstrap modals put a class on the body tag, but if the modal is dismissed incorrectly, that class stays. I mentioned it in the issue comments.

**Comment by negue** [comment]
with this PR I only had the modal scrollbox (only with larger content) instead of the page scrollbar (and the modal one). so 👍  thanks for the PR ^^

**Comment by TheHollidayInn** [comment]
@negue Please see my.comment at the top and in the issue. We should not merge this until we can verify modals are working.

**Comment by negue** [comment]
Well I opened multiple modals, and they opened. What else should be tested?

**Comment by TheHollidayInn** [comment]
In the issue I mentioned that the dismiss problem may come from our modals being dismissed incorrectly. I think it is related to another PR that is trying to fix the modal stacking for challenges.

For history, this issue appeared during the initial design but we couldn't recreate reliably. You can see my comment in the diff of this PR

**Comment by negue** [comment]
So...

- having the normal scrollbar visible
- open a modal
- the normal scrollbar disappears / the modal's scrollbar is visible (and only this one "works")
- once the modal is closed, the normal scrollbar is back

and in the other PR the problem you are mentioning is about the modal-stack which has nothing to do with the scrollbar or did I misread something ?

**Comment by TheHollidayInn** [comment]
In the other issue I mentioned the modal adding and not removing a class. It's a bootstrap thing mixed with an issue on us dismissing modals. Not every modal, just some. Hence why it is hard to replicate. For now, this is on hold. I'll handle checking it.

**Comment by lemoness** [comment]
@lex111 Hi there! How are things going with this fix?

**Comment by lex111** [comment]
Hi @lemoness, so already fixed, is not it? @TheHollidayInn

**Comment by paglias** [comment]
Going to close this as it seems it's been resolved

**Pull request closed without merging**
