### PR TITLE
feat(readme): code climate badge

### PR DESCRIPTION
**Pull request by denis-sokolov**
This badge is not just a meaningless statistic, it actually motivates people to write cleaner code and to clean existing code.

### CODE REVIEW

**Comment by deilann** [comment]
I am more than game.

@lefnire?

**Comment by lefnire** [comment]
It's a [paid service](https://codeclimate.com/pricing). Until we get some more demand here validating it's ROI, let's punt this or find an open source equivalent

**Comment by denis-sokolov** [comment]
Uh, it's ‘100% free for Open Source, forever’.

Same as Travis and most other services of this kind, @lefnire.

**Comment by lefnire** [comment]
Ah! Missed that, I apologize. Yes you're correct, let's give it a whirl

**Comment by denis-sokolov** [comment]
Cool, thanks!

**Pull request merged**
