### PR TITLE
Set cache to private for the language resources

### LINKED ISSUE #13629: Language is not correct on habitica webpage
[//]: # (Before logging this issue, please contact site administrators from "Report a Bug" in the Habitica website's Help menu. If a GitHub issue is needed, staff will let you know and will most likely log one on your behalf. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can be reported via Menu > About > Support.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitica website at User Icon > Settings > API)
### General Info
  * UUID: ef3f1e96-dcbd-4036-a8cd-3d5cb10b4edd
  * Browser: Microsoft edge/chrome
  * OS: windows/linux

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

Recently, I found my habitica webpage's language switch to Japanese somehow(it used to be English), and I cannot switch to English or Chinese anymore even though I set it in my setting.

### PR DESCRIPTION
**Pull request by ramonacat**
[//]: # (Note: See https://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #13629

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
This disables caching for the language resources, as discussed in #13629

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: d5bac4f7-afe1-479b-9f10-6e1a9ed35cdb

### CODE REVIEW

**Comment by SabreCat** [comment]
Alas, this doesn't appear to address the issue. :( Thank you for submitting the PR, though, that's one more thing ruled out!

**Comment by ramonacat** [comment]
I'm still pretty sure that's a caching issue. Is there maybe some cache in front of the web server, whose configuration is not the repo? I see the IP with which the API responds belongs to Google Cloud

**Comment by SabreCat** [comment]
It's running on Google Cloud's Kubernetes Engine, which has Cloud CDN at the load-balancing layer... maybe there's some way to tell it not to serve from cache for a specific resource.

**Comment by SabreCat** [comment]
https://cloud.google.com/cdn/docs/caching

We were set to `USE_ORIGIN_HEADERS`... maybe setting it to `CACHE_ALL_STATIC` will behave better?

**Comment by SabreCat** [comment]
No effect from what I could tell. hmm.

**Comment by ramonacat** [comment]
Hmm... maybe it has already cached the responses and is not even trying to get new ones until these expire?

**Comment by SabreCat** [comment]
I'm not seeing any difference even _turning off_ Cloud CDN.

**Comment by SabreCat** [comment]
Hrm. I turned Cloud CDN off entirely for the web server--not ideal!--but it seems maybe to have stopped the issue from occurring?

In which case... why didn't this PR work? Should we try the more dramatic `no-store`?

**Comment by ramonacat** [comment]
My suspicion is that google has already cached the responses on its cache servers (that would also explain why I was getting German a lot - I am in Germany right now), and wasn't even getting the responses with the corrected header. I'm not very familiar with Google's CDN, but there should be an option somewhere to flush the cache for a specific URL.

**Comment by ramonacat** [comment]
Found this, I unfortunately don't have the right environment to test it, but I believe together with this PR, it should help, if my understanding of the issue is correct: https://cloud.google.com/cdn/docs/invalidating-cached-content

**Comment by ramonacat** [comment]
So, is this fully resolved now? I see in the headers that this endpoint is getting `Cache-Control: private`, other things are cached and seems like nobody's complaining about wrong languages anymore :)

**Comment by SabreCat** [comment]
Yes! Thank you, @Agares! My "turning if off and back on again" approach with the Cloud CDN invalidated the cache, and from there your update to the API route kept things from going awry again. I'll be awarding you tier 1 Blacksmith for the PR, as well as access to the Critical Hammer of Bug-Crushing, because it closed a critical issue!

**Comment by ramonacat** [comment]
Wonderful, glad to hear it's solved! 🥳  And thank you for the awards!

**Pull request closed without merging**
