### PR TITLE
Fixing the date in the What's New

### PR DESCRIPTION
**Pull request by taldin**
It says 12/01/2014 and should be 11/01/2014.  
(Fixing to demo using Github for Windows to create a pull request.)
(I made a mess of the CHANGELOG.md file, though, and I'm not sure how to fix it.)

### CODE REVIEW

**Comment by Alys** [comment]
Huh, changelog. I never put any thought into that file.

<strike>@lefnire, is CHANGELOG.md updated automatically, or semi-automatically with a `git log` command (and if so, which options should be used), or manually? Do you want all devs to modify it (ideally), or leave it for staff to update? Is it for all changes or just big ones (and if so, how is big defined)?</strike>  [Edit: grunt does this]

**Comment by taldin** [comment]
I didn't actively touch it, m'self, but it kinda did funny things to itself whenever I ran grunt or something in my local copy, and then it wouldn't undo properly.

**Comment by Alys** [comment]
@taldin, okay, then grunt must be changing it automatically, which means it's okay and you can not worry about it. Although it's slightly odd that I can't find the grunt code that refers to that specific file, but I have too many other things to do to be able to look into it. :(

**Comment by taldin** [comment]
Not really a huge issue, and I just managed to nuke the commit that fixed this.  Made for good screencaps for a future Wiki page, but since it's no longer at the top of the news, I doubt anyone will notice.  Closing this pull request.

**Pull request closed without merging**
