### PR TITLE
do not show "Notification not found" error messages

### LINKED ISSUE #10391: do not show "Notification not found" error messages
For a while now it's been common to see "Notification not found" snack notifications (e.g., if you've already visited a guild that has new messages in another browser / app). The notifications now remain until you click on them (a side effect of the fix for https://github.com/HabitRPG/habitica/issues/9249), so they're more intrusive than they used to be.

Those messages aren't of any use to the user since there's no action the user needs to take due to the "error".

The "Notification not found" messages should be prevented from appearing in snack notifications.

### PR DESCRIPTION
**Pull request by paglias**
Fixes #10391

### CODE REVIEW

**Comment by paglias** [comment]
@Alys haven't had time to test this but it should work

**Comment by paglias** [comment]
In case of a Notification not found error, nothing is shown

**Comment by Alys** [comment]
Awesome, thanks! I'll test it locally.

**Comment by Alys** [comment]
When I run this change in my local install, the "notification not found" error messages no longer appear.

The error below still appears in the console in situations where the "notification not found" error messages used to occur
```
Unhandled promise rejection Error: "Request failed with status code 404"
	createError webpack-internal:///530:16:15
	settle webpack-internal:///1060:18:12
	handleLoad webpack-internal:///529:77:7
es6.promise.js:110
onUnhandled/</result<
es6.promise.js:110
module.exports
_perform.js:3
onUnhandled/<
es6.promise.js:104
module.exports
_invoke.js:5
<anonymous>
_task.js:35
run
_task.js:21
listener
_task.js:25
```
and at the same time this appears in the output of `npm start`:
```
2019-01-13T08:52:23.819Z - warn: NotificationNotFound: Notification not found.
    at handler (/home/alys/code/habitica/website/server/controllers/api-v3/notifications.js:182:15)
    at args (/home/alys/code/habitica/website/server/libs/routes.js:9:39)
    at Layer.handle [as handle_request] (/home/alys/code/habitica/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/alys/code/habitica/node_modules/express/lib/router/route.js:137:13)
    at _user.model.findOne.lean.exec.then.user (/home/alys/code/habitica/website/server/middlewares/language.js:84:16) 
{ method: 'POST',
  originalUrl: '/api/v4/notifications/see',
  headers:
   { connection: 'close',
     'content-length': '60',
     'content-type': 'application/json;charset=utf-8',
     'x-user-timezoneoffset': '-600',
     'x-api-user': '0232f68f-09da-40a3-b5ba-3b453d7534ba',
     'x-client': 'habitica-web',
     referer: 'http://localhost:8080/',
     'accept-encoding': 'gzip, deflate',
     'accept-language': 'en-US,en;q=0.5',
     accept: 'application/json, text/plain, */*',
     'user-agent':
      'Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:64.0) Gecko/20100101 Firefox/64.0',
     host: 'localhost:3000' },
  body:
   { notificationIds: [ '16a6ccda-40d8-4e6e-a528-34bf9635eb77' ] },
  httpCode: 404,
  isHandledError: true }
```

I'm guessing there's nothing that can reasonably be done about that though.

Can this be put on delta for some extra testing to make sure I haven't missed any problems? @sabrecat

**Comment by paglias** [comment]
@Alys The fact that the error keeps appearing in the console is normal, the error is still happening ì, it's just hidden on the client but it's still being logged as any other API error.

As I said, if you want to filter in loggly between API errors like this and unexpected errors like VersionError(s) there's the `isHandledError` property attached to any error.

I think this is fine to merge to staging as there's a lot of stuff on delta already, I've tested it and it works and it's quite simple

**Pull request merged**
