### PR TITLE
Changed hints style (and small quick fixes)

### PR DESCRIPTION
**Pull request by marcgenesis**
Changed the style of the hints to a dotted underline and removed the "?" icon. Some of them became "More info" when the question mark wasn't attached to any text and some of them just dropped the question mark entirely (Limited Edition and Other in Task -> Advanced Options).

Fixed a forgotten inline style from a previous commit.

See habitrpg-shared #132 (https://github.com/HabitRPG/habitrpg-shared/pull/132) for correction on a string of text.

### CODE REVIEW

**Comment by lefnire** [comment]
Thanks @marcgenesis! I'm gonna wait to merge this until [bs3](https://github.com/HabitRPG/habitrpg/pull/2636) is merged. ETA 3days?

**Comment by lefnire** [comment]
@marcgenesis hate to do this to you my friend... so BS3 has been merged, quite a few strings replaced with translated versions, etc - causing some major conflicts with this PR. Any chance you can rebase & resolve?

``` shell
$ git fetch upstream
$ git rebase upstream/develop
$ #resolve conflicts
$ git push marcgenesis develop --force
```

Also for https://github.com/HabitRPG/habitrpg-shared/pull/132 (thought should be much simpler)

**Comment by marcgenesis** [comment]
When I run grunt run:dev and go to localhost:3000, all I get is the following:

{
  "err": "d:\habitrpg\views\options\index.jade:4\n    2| html(ng-app=\"habitrpg\", ng-controller=\"RootCtrl\", ng-c='shortcut icon', href='#{env.getBuildUrl(\"favicon.ico\")}?v=3')\r\n    7| \r\n\nunexpected token \"indent\""
}

Am I missing something? I'm trying to figure out the problem but to no avail....

**Comment by lefnire** [comment]
You run `npm install` recently?

**Comment by marcgenesis** [comment]
I just did yeah, after doing fetch and rebase

**Comment by lefnire** [comment]
The error is showing that the jade file is indented incorrectly at that location. If this was after the rebase, then it's likely the merge-conflict-resolution ended up with a line tabbed incorrectly (jade being space-sensitive).

**Comment by marcgenesis** [comment]
Thanks.

So the error would lie in d:\habitrpg\views\options\index.jade:4?

2| html(ng-app=\"habitrpg\", ng-controller=\"RootCtrl\", ng-c='shortcut icon', href='#{env.getBuildUrl(\"favicon.ico\")}?v=3') seems to indicate it is on "views\index.jade".

**Comment by lefnire** [comment]
Hmm... after an attempted merge to see if I could see at a glance, maybe not (since that file didn't have merge conflicts). Sometimes it's difficult to tell, due to the way things are `include ...`ed. It's gonna be in one of the jade files anyway, you'll want to make sure the changes get in retaining the bs3 changset's indentation.

If this is proving to be too much (it's a pretty hefty conflict, sorry about that!) then (1) might be best to just redo it all, or (2) if it's burning you out I can take a crack at it when I get a moment (out n aboot tonight, can hit later)

**Comment by marcgenesis** [comment]
I think I've found the problem in the jade file. Now I get a white screen, hooray!

For this problem it seems like bower didn't install jquery (404 on D:\habitrpg\public\bower_components\jquery\jquery.min.js and it is indeed not there).

I'll look into more tomorrow...

**Comment by lefnire** [comment]
Oh, rebase again and re-bower. That was a recent issue

**Comment by marcgenesis** [comment]
Alright... finally fixed.

Working with rebase is a bitch when you don't know what you are doing!

**Comment by lefnire** [comment]
@marcgenesis beautiful! This looks so much better, thanks a million! contrib.lvl++

**Comment by marcgenesis** [comment]
With pleasure! Gotta find my next task now ;)

**Pull request merged**
