### PR TITLE
@lefnire => Highlight username in tavernchat

### PR DESCRIPTION
**Pull request by switz**
Fairly straightforward.

http://cl.ly/OkLQ

### CODE REVIEW

**Comment by switz** [comment]
@lefnire  why do we store timestamps as "epoch" time? 1367687661565

If we used timestamps we would retain timezone info. I'm trying to do relative dates, but if I'm in a different timezone it'll mark it as X hours ago (or X hours in the future!), depending on how far ahead I am of someone else.

**Comment by wizonesolutions** [comment]
@switz That's JS Date time. Pass it through moment("1367687661565").format() to see if it has any timezone data in it.

**Comment by switz** [comment]
Okay, I added in relative dates. Which looks like this: screen shot 2013-05-04 at 2 56 24 pm

But, I want some way to live bind those times so it continually updates as time passes. Anyone have any ideas? For example, every new post will be stuck at 'Just Now' instead of updating to '2 minutes ago' two minutes later.

**Comment by lefnire** [comment]
Wait, don't merge this yet I actually added this functionality locally, but
with more logic for developer and npm checking l. Will consolidate and push
soon

**Comment by lefnire** [comment]
My messaging isnt sending. I already pushed self user highlighting, as well
as backer and developer highlighting. As far as time stamps, I love the
time ago format, doooo it! Imo real time isn't worth it at present, just
roll with you static time ago, recalculate on refresh

**Comment by switz** [comment]
It's already in this pull request. Do you want me to send another one?

**Comment by lefnire** [comment]
Yeah, probably. Sorry, my git vs email got out of sync due to WiFi. So name
stuff is already pushed, probly separate out and send separate pr

**Comment by switz** [comment]
@lefnire, this doesn't highlight your own name when you post - it highlights someone else's post when they mention your name. Doesn't look like you implemented that yet.

**Comment by lefnire** [comment]
Oh snap, way cool! Ok , will look into merging soon

**Comment by switz** [comment]
This is good to go!

**Comment by switz** [comment]
Inside of `app.ready`, I `model.setNull '_currentTime', +new Date()` and then call a `setInterval` every 60 seconds to update that model with a `+new Date()`. The relative times in the chat are updated when that model changes and a new time is generated for each chat message.

So, yay for more "real-time".

**Comment by lefnire** [comment]
did manual merge & made small tweaks, good stuff man.

**Pull request merged**
