### PR TITLE
Fixing debug scripts

### PR DESCRIPTION
**Pull request by Hus274**
### Changes

The debug scripts were broken when the common package was moved into the website folder. This pull request simply fixes the path variables so the scripts work again.

### CODE REVIEW

**Comment by crookedneighbor** [comment]
Actually, I've been meaning to remove these since I added the functionality to the footer in dev mode.

**Comment by crookedneighbor** [comment]
screen shot 2016-10-04 at 8 39 44 pm

**Comment by Hus274** [comment]
Ahh sweet, that's way better. We should update the readme file to remove the references to those scripts and remove those then.

**Comment by crookedneighbor** [comment]
Done. 😄

**Comment by Hus274** [comment]
Awesome!

**Pull request closed without merging**
