### PR TITLE
Minor changes to modals/chooseClass.html

### PR DESCRIPTION
**Pull request by ghost**
Addressing https://github.com/HabitRPG/habitrpg/issues/5244 with respect to help and opinions from @Alys and @lemoness 

Screenshots before / after
 screenshot
 **Edit**: please see the final version in the comment below

Changes:
1. optOutText made more accurate
2. Modal heading in single translatable line with no link to wiki -
which looks nicer
3. Links to wiki articles about classes made translatable
4. New "Learn more about classes" translatable link to wiki article on classes system in the modal
footer

**Edit**
5. Walkaround for a strange bug: popover text gets misplaced vertically for the small optOut button. For the sake of walkaround and style consistency button is made normal sized.

Leaving as is:
- Old bug: the optOut button misbehaves a bit: on mouse_over it slides to the right by some pixels. This bug/feature is also present in online version currently. At the same time the Select button is OK. 
  I can't find what causes this (something from outside the modal?)

### CODE REVIEW

**Comment by ghost** [comment]
Screenshot with the proposed walkaround for misplaced popover:
Before - WIP misplaced popover - After walkaround with normal size button
Screenshot

The popover is placed right for the normal-sized buttons.
To be honest, the small opt out button seemed odd next to the normal button to the right.
I can see the point why it's been made small, but I believe it might as well be of normal-size - for the sake of style consistency and applying a walkaround for misplaced popover - while red color will make sure not many users may click it by mistake

**Comment by crookedneighbor** [comment]
I like them being the same size. :+1:

**Comment by ghost** [comment]
@crookedneighbor thank you for support! However I can't find a solution for an old bug causing a button with popover to jump to the right on mouse-over (not directly connected to this pull request). 

I've found some suggestion for seemingly similar cases: adding `container: "body"` in different variations: http://stackoverflow.com/questions/14364079/bootstrap-tooltip-causing-buttons-to-jump
I've tried adding `container='body',` `data-container='body',`  `popover-container='body',` inside the line
`button.btn.btn-danger(ng-click='user.ops.disableClasses({}); $close()', popover-placement='top', popover-trigger='mouseenter', popover=env.t('optOutText'))=env.t('optOut')`
but still no luck.

As the bug is not directly connected with this request, I'll create a separate ticket for this bug after/if this pull request gets merged.

**Comment by crookedneighbor** [comment]
Notated toward your next tier.

**Comment by ghost** [comment]
If it was a day here, you would make my day!
:) Thank you and have a wonderful day full of inspiration!

**Comment by crookedneighbor** [comment]
By the way, your button shift problem is an error in bootstrap. So, not much we can do about it. :cry:

**Comment by ghost** [comment]
@crookedneighbor Thank you! Yes I've found some comments about it being on bootstrap's side. However some of them mention this bug as fixed while some point out that adding `container: "body"` is a documented walkaround. Do you think I should create a separate issue providing more links to seemingly similar situations on other projects? Or should it be just ignored hoping bootstrap's side will be fixed soon?

**Comment by crookedneighbor** [comment]
We can't use the `container: body` "fix" because it's inside a modal. I figured out a workaround. I set the placement to "left" and put the popover in a span that surrounds the button.

https://github.com/HabitRPG/habitrpg/commit/097e1ff70bea76a6a96bbb4bd6900b58fa0d4d8d

**Comment by ghost** [comment]
Nice! Thank you!

**Pull request merged**
