### PR TITLE
First poke at #3324 - not working, just for review  ("Hide Row of Undiscovered Quest Pets Until One Is Owned")

### PR DESCRIPTION
**Pull request by nataliechan**
#3324

### CODE REVIEW

**Comment by crookedneighbor** [comment]
The main issue is you're trying to do the logic for if a pet row should be shown through the jade templating engine, but that doesn't have any access to the user object, that needs to be done on the client via angular.

**Comment by crookedneighbor** [comment]
I would write a function in the inventory controller, something like:

```
$scope.hasPetOfKind = function(pet) {
  // for instance: pet === 'dragon' 
  var potions = Content.hatchingPotions;

  var hasPetOfKind = false;

  _.each(potions, function(potionData, potion) {
    var thisPet = pet + '-' + potion;
    if(user.items.pets[thisPet]) hasPetOfKind = true;
  });

  return hasPetOfKind;
}
```

And then on each row, something like `ng-if='hasPetOfKind(#{egg})'`

**Comment by crookedneighbor** [comment]
Note, that was written without any testing, so don't trust that it _just works_ <sup>TM</sup>

**Comment by crookedneighbor** [comment]
@scribblypanda How's it going?

**Comment by nataliechan** [comment]
@crookedneighbor honest answer? haven't had time to look at this yet. hoping that I'll be able to have at least part of this functioning by Friday night though! taking a look at inventoryCtrl.js right now.

**Comment by crookedneighbor** [comment]
@scribblypanda No worries. Take as much time as you need.

I'm going to close this pull request for now, but as soon as you're ready for us to take a look please push your changes and re-open it!

**Pull request closed without merging**
