### PR TITLE
Adding checklist item drag and drop feature

### PR DESCRIPTION
**Pull request by gjoyner**
Figured out how to do the merging. :) Adds the ability to drag and drop checklist items. Keyboard manipulation will stay as is. Some of my indents are off in the taskCtrl file but doesn't appear to break things. Easy to fix if needed.

### CODE REVIEW

**Comment by Alys** [comment]
It is best to fix the indents (four spaces instead of one tab for each indent level). It will make the code easier to read if all sibling elements have the same indents, and it also sets a good example for other coders. There are some scripts where correct indentation is essential, so using consistent indentation everywhere ensures that it's always done where it's needed. If you commit to the same local branch and then push to the same remote branch, the change will be added to this PR.

The failing test is talking about something to do with challenges, and I'm pretty sure I've seen that exact fail on another PR recently. Regardless, it doesn't seem to have anything to do with your code, so we can probably ignore it.

**Comment by gjoyner** [comment]
I see what you mean. I did come across the indention issue when messing with stuff. Feels like Python. I see 4 space soft tabs for the initial indent, and then 2 for each indent after that within the code block. Is that standard?

**Comment by Alys** [comment]
Arrrgggh, sorry! I should have said "TWO spaces for each indent level". That's consistent across the file -- except for the case statement which is a special case ;) -- and it's the same on the other files I've seen. If you look near the top of tasksCtrl.js, you'll see there's one `function` line that has the initial two-space indent, and everything else is two spaces further under that. So, yes, definitely two spaces per indent.

**Comment by gjoyner** [comment]
Yeah that makes sense. I forgot everything was in a code block, as is good JS and Angular controller practices. The commit fixing the indentions is also in this PR.

**Comment by lefnire** [comment]
Tested, all checks out to me! Thanks @gjoyner, UUID? 

We should DRY up these sortable directives at some point incidentally

**Comment by gjoyner** [comment]
My HabitRPG UUID? That would be 3f1c7a39-0052-415b-a194-deeeade0c588

**Comment by lefnire** [comment]
lvl++, thx!

**Comment by gjoyner** [comment]
Thanks! I see it updated. Was there equipment for that level?

**Comment by Alys** [comment]
See here for rewards: http://habitrpg.wikia.com/wiki/Contributor_Rewards
Gear appears in your Rewards column to be bought with gold.
Let us know if something failed.

**Comment by gjoyner** [comment]
Oooooooohhhhh I see! We're good! May do party member HP bar next (and mana). :)

**Comment by Alys** [comment]
Hold off on the mana for now because there's been discussions in the past that indicate it might be best not to show it. I think the reason was that if your party sees that you have a lot of mana, they might pressure you to cast skills. I'll track down the conversation in a few hours (pretty sure it was on github).

**Comment by deilann** [comment]
And I think the consensus was that it should be shown because otherwise it
takes the teeth out of ethereal surge due to mages not knowing when to
cast. I've explained it like healers not knowing party hp and the healers
in the discussion agreed thinking about it that way that it was better
shown.

**Comment by gjoyner** [comment]
Oh I see. I saw the trello card but not the github stuff. Let me know of any must have features I can work on :)

**Comment by lemoness** [comment]
@gjoyner What you decide to work on is obviously up to you, but here are some of the most popular Trello cards:
1. Repeat Every X Days (at 500+ votes, our most-requested feature by far) https://trello.com/c/XuVokK2V/108-repeat-every-days-weeklies-monthlies
2. Google Calendar Integration: https://trello.com/c/vtJv2DyY/77-google-calendar-integration-due-dates
3. Due Dates: https://trello.com/c/i6kXvNY2/106-due-dates-urgency-due-start-expires-diseased-todos
4. Task Sorting https://trello.com/c/nytaY3gn/117-sorting-tasks-convert-item-type-by-drag-drop-sort-tasks-sort-columns
5. Trello integration https://trello.com/c/VCxdF9Ld/28-trello-g125﻿

**Pull request merged**
