### PR TITLE
Spell Images [WIP]

### PR DESCRIPTION
**Pull request by librarianmage**
Fixes https://github.com/HabitRPG/habitrpg/issues/4276
### Changes

Adds images to the spells/skills (for classes)

---

UUID: 95f16006-1504-4a9f-95b6-0c7314dbd7ee

### CODE REVIEW

**Comment by librarianmage** [comment]
**Note:** This is a _Work in Progress_. I don't have a computer that can run a local instance of Habitica (don't have admin rights), so I am unable to test it or compile the sprites, so if anyone can quick test it for me, that would be wonderful!

**Comment by crookedneighbor** [comment]
Looks like you accidentally rebased and duplicated commits from `develop`.

**Comment by crookedneighbor** [comment]
Guessing that you merged in Habit's version of `develop` and then rebased against your copy of `develop`, causing the commits that were on Habit's version to be replayed with new shas.

**Comment by librarianmage** [comment]
Oops! Yeah, that is probably what i did.

**Comment by librarianmage** [comment]
@crookedneighbor what should I do to fix this?

**Comment by crookedneighbor** [comment]
How familiar are you with git?

If you have the habitrpg repo set as your upstream remote, you could (comments for your reference):

``` bash
git fetch upstream develop # fetches latest changes from upstream
git reset upstream/develop # resets to those changes, setting anything that was not in that version in an uncomitted state
git add -A
git commit -m "Added spell sprites"
git push --force # overwrites your remote branch with your new version
```

**Comment by librarianmage** [comment]
@crookedneighbor Thanks! Followed your instructions.

**Comment by librarianmage** [comment]
@crookedneighbor Is there a way where someone could compile the sprites for me? I am not currently able to (no admin powers).

**Comment by crookedneighbor** [comment]
Admin powers?

**Comment by librarianmage** [comment]
I can't install Vagrant

**Comment by librarianmage** [comment]
So I can't run Habitica locally to comple the sprites or test it.

**Comment by librarianmage** [comment]
(I meant on the computer I use)

**Comment by Alys** [comment]
@MathWhiz If you're using Windows, you can install Virtual Box "only for the current user" - search for that phrase in https://www.virtualbox.org/manual/ch02.html#installation_windows . I would guess that that doesn't require admin permissions, but I'm not very familiar with Windows. It should be worth a try though because installing Virtual Box should be fast.

**Comment by librarianmage** [comment]
I actually use c9.io to work on Habitica, and it doesn't support Virtualbox.

**Comment by Alys** [comment]
Since it's Ubuntu, you don't need a virtual machine. You can install Habitica directly onto it. See the Unix section in [Setting up Habitica Locally](http://habitica.wikia.com/wiki/Setting_up_Habitica_Locally). c9.io gives you sudo rights.

**Comment by librarianmage** [comment]
I did try, but it quickly ran out of space.

**Comment by librarianmage** [comment]
Though that was during the npm pad-left panic, so I can try again.

**Comment by crookedneighbor** [comment]
I've finished this. I'll count this towards partial credit toward your next tier.

**Comment by librarianmage** [comment]
Ok!

**Pull request closed without merging**
