### PR TITLE
allow challenge tasks to be displayed on challenge page - fixes https://github.com/HabitRPG/habitrpg/issues/4150

### PR DESCRIPTION
**Pull request by Alys**
This might not be the best way to fix the problem described in https://github.com/HabitRPG/habitrpg/issues/4150 while still allowing Grey Dailies to be shown, but it does work on my local install.

### CODE REVIEW

**Comment by negue** [comment]
I think this could be added to "shouldShow" in https://github.com/HabitRPG/habitrpg/blob/56e2ec1bc4eeb9572dfac69d9146d27dda239f69/public/js/controllers/tasksCtrl.js#L200

I can post an example, after work.

**Comment by Alys** [comment]
I did try modifying shouldShow (including putting "return true" as the first line) but it had no effect on the challenges page. It's as if that function is not called for challenges. However I was working rather quickly and didn't stop to investigate why. :) I'll be interested to see what you can come up with!

**Comment by negue** [comment]
I think we took the wrong controller for this, we need to add shouldShow in challengectrl

``` diff
 public/js/controllers/challengesCtrl.js | 3 +++
 1 file changed, 3 insertions(+)

diff --git a/public/js/controllers/challengesCtrl.js b/public/js/controllers/challengesCtrl.js
index 979fa0e..d74382b 100644
--- a/public/js/controllers/challengesCtrl.js
+++ b/public/js/controllers/challengesCtrl.js
@@ -229,4 +229,7 @@ habitrpg.controller("ChallengesCtrl", ['$rootScope','$scope', 'Shared', 'User',
       $scope.search.group = _.transform($scope.groups, function(m,g){m[g._id] = false});
     }

+    $scope.shouldShow = function(task, list, prefs){
+      return true;
+    };
 }]);

```

You can revert your change and just add this function then it seems to work here.

**Comment by negue** [comment]
@Alys could you test my "fix" ? If it works on your side too, then I'd just add these lines via GitHub Web Interface

**Comment by Alys** [comment]
Yes, that worked. I've updated this PR by removing my original fix and adding your suggestion, so the bug can still be fixed by merging this PR.

**Comment by negue** [comment]
Can't be merged because of the "+" in each line, once they're gone, we can merge it.

**Comment by Alys** [comment]
?? It's exactly the code that was working on my local install and the Travis CI build is failing for only other, non-related reasons.

**Comment by negue** [comment]
Oh my... sorry :D, my bad!

**Pull request merged**
