### PR TITLE
Modify inventory fix

### LINKED ISSUE #10035: Debug inventory options not working
[//]: # (Before logging this issue, please post to the Report a Bug guild from the Habitica website's Help menu. Most bugs can be handled quickly there. If a GitHub issue is needed, you will be advised of that by a moderator or staff member -- a player with a dark blue or purple name. It is recommended that you don't create a new issue unless advised to.)

[//]: # (Bugs in the mobile apps can also be reported there.)

[//]: # (If you have a feature request, use "Help > Request a Feature", not GitHub or the Report a Bug guild.)

[//]: # (For more guidelines see https://github.com/HabitRPG/habitica/issues/2760)

[//]: # (Fill out relevant information - UUID is found from the Habitia website at User Icon > Settings > API)
### General Info
  * UUID: N/A
  * Browser: Chrome
  * OS: Windows 10

### Description
[//]: # (Describe bug in detail here. Include screenshots if helpful.)

Inventory options meant to award the user hatching potions, eggs, etc. don't actually award anything once you click "Apply Changes". Additionally, clicking the options meant to fill in fields with 999 etc. has no effect either.

#### Console Errors
[//]: # (Include any JavaScript console errors here.)

None that turned up for me.

### PR DESCRIPTION
**Pull request by toivomattila**
Fixes #10035 

### Changes

In modifyInventory.vue updated Angular-code to Vue:
  Replaced ng-* with Vue-equivalents (ng-for, ng-if, ng-value, ng-model)
  Vue doesn't have equivalet for ng-init, so to replace them:
    Declare data in data()
    Initialize data from user inventory in created()

----
UUID: 78649394-fdf4-4ba3-a0ef-cf4e294dfcdb

### CODE REVIEW

**Comment by negue** [comment]
I'm not able to open the modify inventory dialog

**Comment by toivomattila** [comment]
@negue The module isn't loaded:
@TheHollidayInn commented out line 4 in habitica/website/client/components/appFooter.vue (modify-inventory(v-if="isUserLoaded")) which loads the modifyInventory dialog, because it "was causing severe memory leaks".
I didn't know if it still causes the memory leaks, so I left it commented.
I kept it uncommented while developing and testing, so the module was loaded and I could open and test the dialog, and commented it back before commiting.

**Comment by negue** [comment]
Oh yeah I forgot it was commented out, once it was added back, I could modify all types, so yes this works! 👍 

@TheHollidayInn  how to reproduce the memory leaks ?

**Comment by TheHollidayInn** [comment]
If you open the modal in Firefox it causes memory issues with garbage collection. I can't recall the exact steps off the top of my head but I can check if simply uncommenting doesn't work.

**Comment by negue** [comment]
@TheHollidayInn  should I just check the tab `performance` (like in chrome) recording to look for GC calls ?

**Comment by paglias** [comment]
Any update on this one?

**Comment by paglias** [comment]
Closing for lack of updates

**Comment by toivomattila** [comment]
Hi!
This is already closed so I don't know if this useful anymore but yes, there's still problems with memory.
I got both Chromium and Firefox to use couple gigs of memory by clicking around between Tasks, Inventory, Shops etc.
I don't know how to debug or fix this.

**Pull request closed without merging**
