### PR TITLE
Removing level cap and free Rebirth (DONE AND TESTED)

### PR DESCRIPTION
**Pull request by deilann**
@lefnire this is what I have so far

The modal isn't actually added btw, that's a repeat of the regular rebirth modal.

### CODE REVIEW

**Comment by deilann** [comment]
kk, so this is done in theory -- just needs to b tested. I can't understand why the build is failing, though. It seems unrelated?

**Comment by deilann** [comment]
THIS BE DONE AND TESTED.

(Which is really good 'cause there was an infinite loop hidden in there. WHOOPS.)

It must be merged with https://github.com/HabitRPG/habitrpg-shared/pull/196

**Comment by deilann** [comment]
Build appears to be broken due to i18n stuff.

**Comment by deilann** [comment]
Actually, there's one thing that's not quite fixed yet -- the stats compute correctly, but the level text in stats.jade -- I can't figure out how to fix it.

**Comment by deilann** [comment]
But that's 100% visual.

**Comment by paglias** [comment]
@deilann but it works on your local maching? it's strange that is not working on travis, like if it was using an outdated version of habitrpg-shared

**Comment by deilann** [comment]
I had no issues on local, but it might be that I was getting lucky?

I can rebase again.

**Comment by paglias** [comment]
It works, otherwise it wouldn't have worked for me too, it's only travis I think

2014-05-11 15:26 GMT+02:00, deilann notifications@github.com:

> I had no issues on local, but it might be that I was getting lucky?
> 
> I can rebase again.
> 
> On Sun, May 11, 2014 at 6:23 AM, Matteo Pagliazzi
> notifications@github.comwrote:
> 
> > @deilann https://github.com/deilann but it works on your local maching?
> > it's strange that is not working on travis, like if it was using an
> > outdated version of habitrpg-shared
> > 
> > —
> > Reply to this email directly or view it on
> > GitHubhttps://github.com/HabitRPG/habitrpg/pull/3261#issuecomment-42770443
> > .
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/HabitRPG/habitrpg/pull/3261#issuecomment-42770499

## 

Matteo Pagliazzi - paglias.net

**Comment by paglias** [comment]
@deilann but there are a lots of commits here that are from different things...

**Comment by deilann** [comment]
...yeah, there are.

Lemme try something.

**Pull request closed without merging**
