### PR TITLE
File caching & better compression for css

### PR DESCRIPTION
**Pull request by paglias**
This can be merged immediately but I would like to explain what it does:
- build files moved from /public/build to /build
- minify all css, even vendor ones that weren't minified before

But the big one is:
- all files in /build are renamed with a md5 hash so that when they change the filename change

**This allows us to set caching for all files in /build!** I've set it to one year but it could be set to values even more far away in the future.

It should give a nice boost to loading times.

As you can see in static/layout.jade & index.jade I've added a small helper to make everythig automatic. File rename is handled by grunt.

Actually other than css & js files also the favicon is copied to /build (using grunt-contrib-copy). And like it everything can be copied except images referenced in css files.

### CODE REVIEW

**Comment by lefnire** [comment]
You are the optimizations king my friend! I'll merge this & start playing with it locally. To be honest, a bit over my head looking through the code - but I'll catch on.

**Comment by paglias** [comment]
Yeah the code is a bit repetitive especially the list of files, we should use a manifest file for everything...

**Comment by lefnire** [comment]
Having trouble following this new setup. So I want to add `bower_components/bootstrap-tour/build/css/bootstrap-tour.min.css` to the css pipeline. My assumption is (1) add it to Gruntfile cssmin section, (2) add it to index.jade - but I'm not sure about this step, because for example boostrap-responsive is in the Gruntfile but not in index.jade? And in index.jade, do I add it like this?: 

``` jade
link(rel='stylesheet', href='/#{env.getBuildUrl("bower_components/bootstrap-tour/build/css/bootstrap-tour.min.css")}')
```

I'm slightly concerned this setup is getting unwieldy. Does this grunt setup add a layer of optimization that Snockets + connect-assets didn't give us?

**Comment by paglias** [comment]
Well connect-cachify didn't worked for any vendor file, you can try and if
you are able to then we can switch but I wasn't able.

The cssmin is used to minify the CSS code, bootstrap responsive isn't
minified so I passed it to cssmin but since it do not reference any image
path it can be easily imported directly into index.styl so it's referenced
there.

The rule is: the CSS contains any image URL and it is in a subdirectory ?
Then we need it to stand alone or it will have wrong references to images,
otherwise just add it to index.styl and we'll have one less request to make
to the server. But if that is counter intuitive we can keep out of
index.styl
Il giorno 10/set/2013 23:30, "Tyler Renelle" notifications@github.com ha
scritto:

**Comment by paglias** [comment]
And if the file is already minified it's not needed to pass it to cssmin
but to copy task

If smth isn't clear let me know

**Comment by paglias** [comment]
And the code to add in the jade template you posted is OK, I'll remove the need to add the '/' at the beginning (which is only needed in static files because not in the root, not a grunt fault it's normal)

**Comment by lefnire** [comment]
Ok, i'll give this another shot & report back. I suppose we do want to try our best to make Grunt work so that we can have a unified asset workflow b/w mobile & web

**Comment by lefnire** [comment]
See above commit - I think it's working, could you take a peak and make sure I did things correctly?

**Comment by paglias** [comment]
I'm from phone but I think there are a few problems:
- bootstrap-tour js must be added to gruntfile too under uglify task like
  you did for guild service
- bootstrap tour css must be added to index.jade using env.getBuildUrl if
  it contains some images, if not import it into index.styl
- bootstrap tour CSS seems to be already minified so do not pass it to
  cssmin but to copy task (but it will work anyway, only not needed)

Tomorrow afternoon I'll work on adding a manifest file to make things easier
Il giorno 11/set/2013 00:07, "Tyler Renelle" notifications@github.com ha
scritto:

**Comment by paglias** [comment]
Everything seems perfetc now! Don't know about you but I can see the result from these, i have a lot faster loading times

**Comment by lefnire** [comment]
Awesome awesome dude, good job on this! Good timing too, because someone just emailed me about min/cat/cache - I was able to point him to this PR :)

**Pull request merged**
