### PR TITLE
improve(profile): clarify the cost of unlocks, fix #3175

### LINKED ISSUE #3175: Unlocking language on Avatar page is unclear
The current wording of "2gems/locked" is unclear, and makes it sound somehow like the whole category is locked and you have to pay to unlock it. From the Tavern:

@balamuc:

> Why does it say 2gems/locked under Head, Body and Skin in the Avatar tab? It looks like it's related to the basic types, but those were already unlocked. 

@BrightBold:

> I agree with @balamuc that that is confusing. I only figured out last week what it was supposed to mean. Maybe something wordier like "Dark gray = locked. Unlock items for 2 gems/ea or 5 gems/set" (where "dark gray" and "gems" could be replaced with images).

I'm not hung up on that particular wording; we just need something that makes it clear that we're referring to the cost of unlocking locked items, as opposed to it sounding like we're saying all the items are locked.

### PR DESCRIPTION
**Pull request by denis-sokolov**

### CODE REVIEW

**Comment by denis-sokolov** [comment]
I also want to consolidate the "2:gem:/locked" and the "Unlock set - 5:gem:", but that will have to be a separate task.

**Comment by deilann** [comment]
Can you toss me a screenshot?

**Comment by denis-sokolov** [comment]
@deilann, I was already in process, see the updated post.

**Comment by deilann** [comment]
I wonder if 2 :gem: /each makes more sense than locked. Thoughts?

**Comment by denis-sokolov** [comment]
I did not make that call, the current pull request is about positioning.

I have no significant opinion on the language. "Each" is good, "locked" is not too bad. "Locked" is better after the user has unlocked half of those.

**Comment by deilann** [comment]
yeah, I was just curious what you thought. :thumbsup: Positioning is much better, although consolidating it later, like you said, is probably a good idea.

**Pull request merged**
