### PR TITLE
Use nvm to install node 4 to vagrant env

### PR DESCRIPTION
**Pull request by KristianTashkov**
Same as [previous PR](https://github.com/HabitRPG/habitrpg/pull/6486) but targeting develop.

UUID: bb8db09b-5822-4608-bba3-1486964b8537

### CODE REVIEW

**Comment by crookedneighbor** [comment]
The install.sh file isn't executable and never gets called in the provisioning process.

**Comment by KristianTashkov** [comment]
Hmm I thought I made it executable. For the provisioning process it isn't meant to be. I was gonna put it as a command you need to run after you `vagrant ssh` the first time. I'm not sure if it will work if I run it with `sudo -H -u vagrant` from `vagrant.sh`. Will test tonight.

**Comment by KristianTashkov** [comment]
@crookedneighbor I fixed the executable problem.
I tried running `install.sh` from the provision script, but `nvm` is being picky when being installed for multiple users and I couldn't make it work. In the first couple of days while trying to make this PR work I had a solution which installed `nvm` from the provision script and made it useable from the vagrant user, but later scrapped it because installing `nvm` properly from the right user seemed cleaner and better than hacking path variables to make it work.
If you think running an extra command when you login for the first time(I can update the wiki to reflect this change) is too much, I can try to recreate the `nvm` installation but I don't really think it's worth it. Also having a handy install script that sets up nvm/node/the project, when you switch between develop (node 0.10) and api-v3 (node 4) is really handy.

**Comment by crookedneighbor** [comment]
Tier awarded!

**Pull request merged**
