### PR TITLE
Remove unneeded conditional which makes showBailey need 2 clicks

### LINKED ISSUE #9278: "Show Bailey" must be clicked twice
In https://habitica.com/user/settings/site , the button "Show Bailey" has to be clicked twice to actually show the Bailey. Bailey's most recent announcement should pop up after a single click.

### PR DESCRIPTION
**Pull request by navinpai**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Habitica_Git#Pull_Request for more info)

[//]: # (Put Issue # or URL here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes https://github.com/HabitRPG/habitica/issues/9278

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
Removed an unneeded conditional which was making the DOM not have the modal when the button is clicked the first time 

[//]: # (Put User ID in here - found in Settings -> API)

----
UUID: e6b8ef45-698b-4754-8d5c-58c88c303c15

### CODE REVIEW

**Comment by perkyguy** [comment]
@navinpai are you able to use the "Dismiss this" button and get rid of the modal in one click?

**Comment by perkyguy** [comment]
@navinpai , there were some other lurking issues with how this was all being handled. You can check them out over in a PR I submitted (PR #9315 ). This was one of the issues, but there were more that needed to be fixed to solve the underlying problem.

**Comment by paglias** [comment]
@navinpai sorry about this but I'm closing this PR in favor of #9315 since it seems to fix other issues as well

**Comment by navinpai** [comment]
That totally makes sense! Thanks for following up! 👍

**Pull request closed without merging**
