### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by tcyrus**
Change all Readme Badges to SVG's

### CODE REVIEW

**Comment by Alys** [comment]
Thank you for this! Could you please add a brief comment to explain the reason for it?

**Comment by crookedneighbor** [comment]
@Alys The main advantage will be that svg's are vectors, so they scale when zooming in the browser or viewed on a retina screen:

screen shot 2015-10-01 at 10 06 15 pm

Left side - jpeg, right side -svg

**Comment by crookedneighbor** [comment]
This will count towards a contributor tier! What's your User ID? You can find it in [Settings > API](https://habitrpg.com/#/options/settings/api). Be sure to only copy the User ID and _not_ your API Token.

**Comment by tcyrus** [comment]
@crookedneighbor, User ID: 249351d5-1477-4d68-a038-3ecdb2caeceb

**Pull request merged**
