### PR TITLE
Add wiki glossary to tavern

### PR DESCRIPTION
**Pull request by bobbyroberts99**
My local repo is behind and ahead so I'm submitting from GitHub. Not sure how to fix, so if there a bunch of old commits, please ignore. This is the only active one I've got going.

### CODE REVIEW

**Comment by lefnire** [comment]
looks good to me! I'll follow up on the repo stuff soon

**Comment by bobbyroberts99** [comment]
I'm starting over with the repo. Probably a way to fix it, but I don't want to waste your time.

**Comment by lefnire** [comment]
Yeah, starting over is probably the best bet. I imagine it's been due to
interactive rebases on my part, requiring a force-pull for you. Fresh start
is better

**Comment by bobbyroberts99** [comment]
Ok, I went through the whole install process again. I have mongoose
running but get this when i run npm start. Is the password it's
referring to from config.json or somewhere else? Do I need to edit
config.json or just copy the example? No rush, if I find something small
to change, I can always edit from GitHub.

name003

**Comment by lefnire** [comment]
That auth error is benign, means it couldn't authenticate with gmail to send you the error.

The error you're seeing is because the old data doesn't fit the new schema. For that we run migrations against the database (see the migrations directory), but that's a big PITA knowing which migrations to run on localhost, especially when you're working with temporary / test data anyway. For you it's best to just logout and create a new account on localhost, or worst-case scenario drop the database altogether and start anew.

``` shell
mongo habitrpg
>db.dropDatabase()
```

**Comment by lefnire** [comment]
(@SabreCat @danielthebard ^ might also be useful for y'all too)

**Comment by SabreCat** [comment]
Yeah, I tend to drop the database using [MongoVUE](http://blog.mongovue.com/) as one of my first troubleshooting steps, ever since the first time @lefnire pointed this out for me ^.^;

**Pull request merged**
