### PR TITLE
Clarify pet hatching instructions

### PR DESCRIPTION
**Pull request by bobbyroberts99**
This is my first PR. Hope I'm in the right place.

### CODE REVIEW

**Comment by lefnire** [comment]
Look at @bobbyroberts99 joining the fray!!

**Comment by bobbyroberts99** [comment]
Little by little. I'm going to try a create a local version on my 
laptop. Found readme.md. Hopefully, I can figure it out. If not, I'll be 
back with some questions. I'm wondering if there are more detailed 
instructions somewhere (or maybe it's perfectly obvious and the noob is 
a little dense). The commands to type are entered in Terminal, right?

Tyler Renelle wrote:

**Comment by lefnire** [comment]
Naw, README is all we've got at present. There's some high-level stuff at
https://github.com/HabitRPG/habitrpg/wiki/Contributing#coders-web--mobile
(which
is out-dated, and needs more info). Sorry m'man, I'll do another
documentation sweep in the future

**Comment by bobbyroberts99** [comment]
No rush on this (I know you're busy with Challenges), but just for learning purposes... After a commit is merged when/where does it show up on the site.

**Comment by lefnire** [comment]
we're manually pushing still, so the answer is "randomly". eventually, once we have a solid test harness in place that @djuretic has been working on (bless him), we'll then set up continuous deployment to push with each passing commit.

FYI also, `develop` is detached from beta & master presently. it's tracking the challenge.habit site, and this change will go live when challenges goes live. (this is an unusual situation with our codebase, was a technical issue)

**Comment by bobbyroberts99** [comment]
That helps me understand a bit more. Thanks

Tyler Renelle wrote:

**Comment by bobbyroberts99** [comment]
Tyler, I've got mongo and github successfully installed (I think). The "npm install -g grunt-cli bower" succeeded as well but the "npm install" returned errors. I submitted an issue here: https://github.com/isaacs/npm/issues/4071 but it doesn't help much.

Any ideas (when you have time) or can you point me to someone else who could help? I'm not in a rush on this.

Thanks,

Bob

**Comment by paglias** [comment]
You should run npm install from the directory where habitrpg's package.json
lies, you can browser a path with 'cd path'
Il 31/ott/2013 21:41 "bobbyroberts99" notifications@github.com ha scritto:

**Comment by bobbyroberts99** [comment]
That seemed to do the trick except AuthError at the end (https://www.evernote.com/shard/s207/sh/650bd9cd-fcf0-44df-9cad-6af328d77ef8/9cab4700eccc69cb32d42912bdf32b85).

I started the local host for the app and saw the site but couldn't login with my username or register a new user. The login box was unresponsive. Getting close.

Any ideas? Does it look alright otherwise? Thanks for the help!

**Comment by paglias** [comment]
You should check mongodb is running

**Pull request merged**
