### PR TITLE
fix(attribute): updated to display max level benefit as 50

### PR DESCRIPTION
**Pull request by thepeopleseason**
_Update_: fixed local env and tested locally: 
levelcap

I'd appreciate some extra eyes on this; I only tested via learn-angular.org because local environment is currently buggy. Fix for #3682

### CODE REVIEW

**Comment by Alys** [comment]
I believe the current display actually correctly matches the current code. We haven't yet gotten around to making all of the code changes required to freeze stats at level 100. For example, I think this stats calculation maps to the stats display in the Attributes section: https://github.com/HabitRPG/habitrpg-shared/blob/develop/script/index.coffee#L1470

There's a slightly terrifying amount of code that references 'stats.lvl', with some calculations repeated (undesirably?) for both use and display. It might be nice if the calculations that are done for the purposes of applying stats could set user variables/preferences/whatever that are then used for display (no need to repeat calculations purely for display).

Also, for the case where the level is greater than 100, I'm wondering if it's best to leave all the stats.lvl code as it is now, and have an additional attribute called stats.lvlReal or something. When the user levels up, stats.lvlReal is always incremented but stats.lvl is never increased above 100. This would mean that (almost?) all the calculations involving attributes/statistics could use stats.lvl and not have to be modified at all to implement the stats freeze above level 100, but the code that displays the user's level could be changed to use stats.lvlReal (a much simpler, safer change than modifying all the calculation code).

I haven't put much thought into any of this though. Opinions, anyone?

**Comment by deilann** [comment]
@Alys No, it doesn't. The max lvl/2 bonus is 50.

The only issue is that attribute points are still added upon level gain.

**Comment by Alys** [comment]
Ha! `if user.stats.lvl < 100` -- sorry! I don't know how I missed that. :)  I'm still concerned about the duplication of calculations, but it's a minor thing.

**Comment by Alys** [comment]
I'll look at this after the upcoming skills-rebalancing / level-100-attribute fix has gone live.

**Comment by Alys** [comment]
Sorry @thepeopleseason - we ignored this for far too long, and then more recently someone else provided a similar fix which we accepted. :(  I knew at the time that we had an old fix in the system but I couldn't find it until just now.

**Pull request closed without merging**
