### PR TITLE
Display an error notification when attempting to purchase invalid amount of gems - fixes #8145 - continued in PR #8688

### LINKED ISSUE #8145: buying zero gems for a gift with PayPal produces InternalServerError
On the gem gift screen, it's possible to attempt to purchase gems as a gift for another player without first entering the number of gems (i.e., to try to give zero gems). This produces an ugly error message when using PayPal (below). For Amazon, it allows you to click through to the Amazon site and for Stripe, it allows you to enter your credit card details, but both of those results are also wrong for a value of zero gems.

**The desired behaviour is that you should not be able to click on the "purchase" button until you have entered a number of gems.**

Steps to reproduce for the PayPal case (reported by Laurens van Riel, be51405a-b3c0-41f6-8f99-3e6af962d99f, in the Report a Bug guild):

**Start**:
On the page "Send gift to <username>" I got to this page from my tasks page, by clicking on a party member and then clicking the gift button.

**Actions**:
- Leaving the amount of gems on standard value=0
- Selecting the option "Purchase"
- Clicking the PayPal button.

**Result**:
White page with the text
`{"success":false,"error":"InternalServerError","message":"An unexpected error occurred."}`

### PR DESCRIPTION
**Pull request by akortesmaa**
Fixes #8145
### Changes

Trying to purchase zero or negative amount of gems now results to an error notification "Amount must be at least 1."
2016-10-21-145719_1734x688_scrot

As for the API, I was only able to do this for PayPal because Amazon & Stripe complained about missing API keys before hitting the backend. 

---

UUID: 5abc818d-baeb-4951-a66f-d6c1dba21305

### CODE REVIEW

**Comment by TheHollidayInn** [comment]
@Althenis Are you still working on this? There seems to be a build error and now merge conflicts.

**Comment by akortesmaa** [comment]
@TheHollidayInn Not since I submitted the PR. The failing test was unrelated to my changes, some other PR's had the same problem.

**Comment by TheHollidayInn** [comment]
Ah, okay, I see. If you don't mind resolving the conflicts. I'll get this merged in.

**Comment by akortesmaa** [comment]
Sure, I'll try to sort it out.

**Comment by TheHollidayInn** [comment]
```
if (amount <= 0) {
 +          throw new BadRequest(res.t('badAmountOfGemsToPurchase'));
 +        }
```
This code needs to be added to payments.checkout method that I abstracted.

**Comment by TheHollidayInn** [comment]
Closing in favor of continuation.

**Pull request closed without merging**
