### PR TITLE
[INCOMPLETE] Add partial payments.

### PR DESCRIPTION
**Pull request by Gaelan**
Successor to #1947 after I sent the PR to master instead of develop, bringing tons of unwanted commits along.
- [x] Add partial payments to schema.
- [ ] Update prices shown to reflect remaining price.
- [ ] Use partial payments when actually purchasing.
- [ ] Add UI/API for paying part of a reward.
- [ ] Decide on whether and how death affects savings.

### CODE REVIEW

**Comment by Gaelan** [comment]
I can't figure out how to get a computed (i.e. not stored in DB) value into a template. Anybody know how?

**Comment by paglias** [comment]
Which value and where? You can add a function in the $scope and reference
it or for simple computations you can use the template directly
Il 01/dic/2013 22:26 "Gaelan" notifications@github.com ha scritto:

**Comment by Gaelan** [comment]
@paglias Thanks! I'm trying to get the remaining price (instead of the whole price) into the reward list.

**Comment by paglias** [comment]
{{task.value - task.pricePaid}} should work. I'm from mobile so I don't
know which property are you using to store the price already paid so be
sure to use the correct one.
Il 01/dic/2013 22:31 "Gaelan" notifications@github.com ha scritto:

**Comment by Gaelan** [comment]
@paglias Thanks!

**Comment by lefnire** [comment]
Gonna close this, not a lot of demand for the feature, pretty stale in the queue

**Comment by Gaelan** [comment]
OK.

**Pull request closed without merging**
