### PR TITLE
added pet colour to feed/evolve notif

### PR DESCRIPTION
**Pull request by nataliechan**
Fix for #2825 . Screenshots included below. Not quite sure why some pets are Cubs and others aren't (e.g. Shade Wolf vs. Shade Panda Cub ). I figured that was a decision made elsewhere that doesn't apply to this issue, but let me know if I'm wrong in assuming that.

screenshot from 2015-02-17 12 40 23
screenshot from 2015-02-17 12 40 38
screenshot from 2015-02-17 12 40 49

### CODE REVIEW

**Comment by crookedneighbor** [comment]
One issue with this, and this is an issue with the original code, not something you did, is that the pet name is not translated (screenshot from the develop branch, not your branch):

screen shot 2015-02-17 at 6 05 20 pm

When you mentioned how some names have the word cub on them, that's because the value that is being displayed is the untranslated "key" of the pet. You'll notice if you feed one of the cotton candy pets, the name will be all run together (your branch):

screen shot 2015-02-17 at 6 11 54 pm

That's because, again, it's displaying the object key for the pet/potion, instead of the translated version.

There's a trick to displaying the full pet name correctly, but it's a tad difficult. You can see an example here, where it uses the "petName" string:
https://github.com/HabitRPG/habitrpg/blob/a8cb0fd4e9785f257ca5edbc9c62dba7577d5ca2/website/views/options/inventory/stable.jade#L8

If you want to work on that, I'd recommend making a new branch off of this one, and submitting a new pull request for review (if that one got merged in, this one would be closed automatically). That way, if it turns out to be too frustrating/hard to do it, we can fall back on this one as a stop-gap. 

If you're up for a challenge, I say go for it, but maybe set a time limit on how long you spend on it. It's going to be tedious work, regardless. 

If you don't want to work on it, this PR satisfies the original bug report, and I'm happy to merge it in as a stop gap till someone comes along and changes it to display the full pet name.

**Comment by nataliechan** [comment]
Thanks for the detailed feedback @crookedneighbor (: I'm up for trying to get the actual translatable strings in there instead of the keys - if I don't have anything workable by Monday though I'll probably just leave it to be merged as is (and will let you know accordingly). If I have questions is it ok to ask them here/on Habit?

**Comment by crookedneighbor** [comment]
Here is best. That way all the Github devs can see the question and chime in.

**Comment by nataliechan** [comment]
Looking at the example for displaying the full pet name: in .jade files, blank.text(env.language.code) will look up the text for blank, which will give t('key'), which will then be looked up in the applicable json file, and the proper value (translated string provided). Am I right so far?

Following this logic, and looking at the code specific to index.coffee: it looks like the equivalent is blank.text(env.language.code) is blank.text(req.language), e.g. message = i18n.t('messageLikesFood', {egg: egg , potion: potion, foodText: food.text(req.language)}, req.language). so the whole 'messageLikesFood' key will be looked up in the applicable json file, but the food.text will also be looked up so that the right translated string is inserted into the 'messageLIkesFood' string. Also correct?

If so... changing egg: egg to egg:egg.text(req.language), and the same for potion, should theoretically be causing the desired result. And instead, the 'ok' button for confirming feeding a pet food, doesn't do anything. Maybe I'm messing up an input check somewhere?

**Comment by nataliechan** [comment]
@crookedneighbor given lack of success so far and amount of other work that needs to get done by tomorrow night, I think I'm just going to leave the bigger issue for someone else for now, if you're ok merging my original PR as a stop gap for now. also if you have time, it would be great if you look at the last comment I made on this (useful in case I get the chance to poke at this again later) but if not that's fine (:

**Comment by crookedneighbor** [comment]
@scribblypanda Sorry, I had a reply partially written up, but I'm out of the country for this weekend and internet has been spotty. I'm going to go ahead and merge in your changes and then finish it up, I'll write out how I did here.

I'm realizing now that this would probably have been a better example of how to use the `petName` string: https://github.com/HabitRPG/habitrpg/blob/a8cb0fd4e9785f257ca5edbc9c62dba7577d5ca2/website/public/js/controllers/inventoryCtrl.js#L127-L130

Since it's kind of complicated, it gets saved in the petDisplayName variable, and then [called on this line](https://github.com/HabitRPG/habitrpg/blob/a8cb0fd4e9785f257ca5edbc9c62dba7577d5ca2/website/public/js/controllers/inventoryCtrl.js#L137)

So, first off, I'd change all three strings to use `<%= pet %>` instead of `<%= potion%> <%= egg %>`.

Next, we're going to have to rewrite that petDisplayName variable in coffeescript. 

In coffeescript (and in the context of the `common/script/index.coffee` file), that'll be:

```
potionText = if content.hatchingPotions[potion] then content.hatchingPotions[potion].text() else potion
eggText = if content.eggs[egg] then content.eggs[egg].text() else egg
petDisplayName = i18n.t('petName', { 
  potion: potionText
  egg: eggText
})
```

For  both the `potionText` and `eggText` variables, we're checking to see if the potion/egg exists in the content object, and if it does, apply the `text` method which returns the string in the user's language. If it doesn't exist, it just uses the key (ie: `cottonCandyBlue` or pandaCub). It should always exist, but we have that as a fallback.

Then you just change the egg and potion calls in the three strings to `pet: petDisplayName`.

```
message = i18n.t('messageEvolve', {pet: petDisplayName}, req.language)
```

We could have done all that work within the message itself, but it'd be kind of a mess:

```
message = i18n.t('messageEvolve', {pet: 
  i18n.t('petName', { 
    potion: if content.hatchingPotions[potion] then content.hatchingPotions[potion].text() else potion
    egg: if content.eggs[egg] then content.eggs[egg].text() else egg
  })
}, req.language)
```

Plus, we'd have to do it three times, so why repeat ourselves? Ain't nobody got time for that.

**Comment by crookedneighbor** [comment]
Tier ++

Note that the higher tiers require more effort than the lower ones, so if you make any small changes from now on, you might find that they won't grant you an extra tier immediately, but they will be noted as partial credit towards a tier. There's a bit of information about that at [Contributor Rewards](http://habitrpg.wikia.com/wiki/Contributor_Rewards) but do ask if you have questions.

**Comment by nataliechan** [comment]
@crookedneighbor Thanks for finishing it off + explaining. I think I need to spend some more time figuring out how different files link together (like here the inventoryCtrl.js file is calling the index.coffee file.. I think... but I need to figure out why/how). 

Yup, I'm aware of higher tiers requiring more effort - I'll likely keep on picking small-ish things to work on just to keep things manageable while I'm still learning languages and such, but leave the entry-level stuff alone. However, in an awkward turn of events, I think all my tiers have been removed on Habit?

**Comment by crookedneighbor** [comment]
Whoops. That was probably my fault. I'll investigate when I get home.

**Pull request merged**
