### PR TITLE
Rebalanced skills

### LINKED ISSUE #3029: Fix Overpowered Skills [$50]
When I use backstab with my level 63 rogue, I get about 200 GP. I find this level of reward for spending 15 mana is sufficiently overpowered that I don't use the ability. My User ID: 66440307-9628-4eca-b448-ba008e82a3b3.
## <bountysource-plugin>

Did you help close this issue? Go claim the **[$50 bounty](https://www.bountysource.com/issues/1435782-fix-overpowered-skills-50?utm_campaign=plugin&utm_content=tracker%2F68393&utm_medium=issues&utm_source=github)** on [Bountysource](https://www.bountysource.com/?utm_campaign=plugin&utm_content=tracker%2F68393&utm_medium=issues&utm_source=github).
</bountysource-plugin>

### PR DESCRIPTION
**Pull request by chimericdream**
Per @Alys's [suggestion](https://github.com/HabitRPG/habitrpg/pull/4807#issuecomment-77501359) in my [potion pull request](https://github.com/HabitRPG/habitrpg/pull/4807), I combined the `rebalancing-2014-12` branch from the old `habitrpg-shared` repository into the branch of the same name here. This should include all of the changes in both repositories and fixes #3029. (I am merely the one who combined the last few pieces... credit goes to [lots of people as mentioned here](https://github.com/HabitRPG/habitrpg/issues/3029#issuecomment-68128382).)

I have not yet tested this on my local VM, so this may not be ready for merging right at the moment, but it _should_ be pretty much done. All I did was rebase the `rebalancing-2014-12` branch off the latest `develop` and copy the changes made in the old repo to the new one.

ping: @Alys @deilann

### CODE REVIEW

**Comment by Alys** [comment]
We definitely don't want to merge this yet into develop. One part still needs to be finished and then I want to do some thorough testing, ideally on beta with various other users.

@chimericdream Could you please do a PR into the rebalancing branch?

**Comment by chimericdream** [comment]
@Alys not easily, no. Because of the rebase, the pull request shows 5400+ changes between the two versions of `rebalancing-2014-12`, and they can't be automatically merged.

I can make the changes on a non-rebased version of the branch. Instead of rebasing, I'll just merge develop into this branch. There shouldn't be any major issues (the rebase was clean on the first try), and it will make the PR much simpler. I'm heading to bed now, so I will do that tomorrow.

**Comment by Alys** [comment]
No worries. What we can do is just make a new habitrpg:rebalancing-2015-03 branch, and you can merge into that. I'll try to get that done before you wake up. :)

**Comment by Alys** [comment]
Although... merging does sound cleaner...

**Comment by chimericdream** [comment]
@Alys It should be cleaner, and I don't think it will be too bad. There will be one or two conflicts to fix when I merge, but I'll keep the final version of `index.coffee` and `content.coffee` backed up so I don't have to manually make the changes a second time.

**Comment by Alys** [comment]
@chimericdream the branch https://github.com/HabitRPG/habitrpg/tree/rebalancing-2015-03 exists now in case you need it.

**Pull request closed without merging**
