### PR TITLE
Fixed the null gem prize option for challenges fixes #9745

### LINKED ISSUE #9745: challenges can have `null` blank gem prize
_EDIT 2019-07-13: I've modified this post to bring it up to date with the latest information from the comments below._

It's possible for the gem prize for a challenge to be `null` but this shouldn't be possible. It should be either zero or a positive integer. For example, see the challenge shown below. 

The fix for this should be done in the API. That will make it impossible for this situation to arise no matter what method is used to create the challenge.

In addition, the website's form to create and edit a challenge should be modified to make it impossible to submit the form if a gem prize hasn't been specified (while still allowing a prize of 0 of course), and to provide useful feedback to the challenge creator if they haven't specified the gem prize amount.

The contributor who works on this should see the information MathWhiz provided in [this comment](https://github.com/HabitRPG/habitica/issues/9745#issuecomment-354557766) as that's likely to be relevant. There is currently code that is supposed to prevent a null gem prize, but it's not working and the info from MathWhiz probably explains why.

screenshot_2017-12-26_19-56-52
```
{
    "_id": "330860fd-dfcf-47dc-a470-e87beaa663bf",
    "name": "Game Draft :boom: The Rise of the Mighty Dunwanna!",
    "shortName": ":boom: TROTMD",
    "description": "The emoji ......",
    "leader": "c21096c3-d133-46ea-9642-bf940c9c43f6",
    "group": "feec0365-0078-40f1-bb0a-adac04d634ff",
    "updatedAt": "2017-06-02T20:20:35.016Z",
    "createdAt": "2017-06-02T09:53:54.641Z",
    "prize": null,
    "memberCount": 0,
    "tasksOrder": { .... data removed for brevity ....
    },
    "official": false,
    "__v": 1
}
```

Once a fix for this issue is live, an admin will do a migration to set the gem prize to 0 for all affected challenges. If the contributor who works on the fix reminds us of that in their PR, that would be appreciated! :)
_(We also have issue https://github.com/HabitRPG/habitica/issues/11264 to make a **front-end** fix to display "0" when the prize is `null`, since that should be a quick-and-easy workaround. We could revert the PR for that issue after the back-end change is live and the migration has been done.)_

### LINKED ISSUE #11264: display `null` challenge prize as 0 gems
As described at https://github.com/HabitRPG/habitica/issues/9745 it's possible for the gem prize for a challenge to be null which results in the prize box on the challenge having a blank space where the number of gems should be, as shown in the screenshot below.

As I mentioned in [one of my comments there](https://github.com/HabitRPG/habitica/issues/9745#issuecomment-508986367) a `null` prize doesn't seem to cause any problems apart from that display glitch, so this issue is to have **the website's front-end code modified so that when the prize is `null`, the number `0` is shown in the prize box**.

screenshot_2017-12-26_19-56-52

_(https://github.com/HabitRPG/habitica/issues/9745 is being left open for a fix to the back-end code and a migration to correct all the affected challenges.)_

### PR DESCRIPTION
**Pull request by kmacart**
Will need a mod to fix all the currently null challenges - my code doesn't fix that, just prevents new challenges from being null prize.

[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (https://github.com/HabitRPG/habitica/issues/11264)
fixes #9745

### Changes
[//]: # The reason you could put a null value in as a gem prize is because null is technically all data types. To prevent null gem prizes, I put required: true in the prize line.

[//]: # 0fb3db86-7009-46d6-9eea-485a8f7e6734

----
Habitica Username: @kiramac

### CODE REVIEW

**Comment by paglias** [comment]
This will need a migration to be run before it goes live or it'll break existing challenges with no prize

**Comment by Alys** [comment]
Perhaps we might want to fix this part from [the issue](https://github.com/HabitRPG/habitica/issues/9745) in a separate PR before the migration? 

"In addition, the website's form to create and edit a challenge should be modified to make it impossible to submit the form if a gem prize hasn't been specified (while still allowing a prize of 0 of course), and to provide useful feedback to the challenge creator if they haven't specified the gem prize amount."

That will prevent anyone using the website to create a gem-less challenge in between finishing the migration and deploying the API fix.
It would be a good feature to have anyway to give better feedback to the users since the API error will look ugly. :)

**Comment by kmacart** [comment]
@Alys Sure!

**Comment by SabreCat** [comment]
Looks like I can't push to your branch to resolve the conflict, @kmacart, but I'll make the changes in a commit to `develop` and credit you. This also adds the Blacksmith title to your contributor status and raises you to Tier 2. Thank you and congratulations!

**Comment by SabreCat** [comment]
I've already run a database update to replace existing `null` values, so given the groundwork of the prior PR this should be good to go live. It'll live on Staging for a few days first, then it's off to habitica.com!

**Comment by kmacart** [comment]
Thank you so much! Glad it worked =D

**Pull request closed without merging**
