### PR TITLE
maybe fixes the multilingual content result

### PR DESCRIPTION
**Pull request by negue**
Mostly everytime I try to load the contents with the API, for example my target language is german, I also get russian, english, italian and so on...

Seems that it either loses the language property or it get mixed up with all other api calls

If its possible I would like to have this change at first just pushed to the beta server and see if this bug is still happening

### CODE REVIEW

**Comment by crookedneighbor** [comment]
FYI, beta is currently being used for cron testing. 

If it's something that you want to test soon, could a temporary instance be spun up at a new subdomain? Maybe lang.habitrpg.com

**Comment by negue** [comment]
I can wait, I just need an server with more than 2 users :D, really need to have many so that the language property can (or hope not) change while processing the request

**Comment by paglias** [comment]
@negue i think we experience something similar in drops... sometimes, it's possible? Anyway I can put it on beta along with cron fix but I don't want to make things difficult for @SabreCat or @Alys (I'd had to use a custom branch to deploy from). Otherwise we can wait for a few days (sunday probably) and then put it on beta.

Anyway it doesn't seem it could cause any sort of problema anyway, why not directly on prod?

**Comment by Alys** [comment]
@paglias Don't worry about me. I cared about beta for only a very short time yesterday. :)

**Comment by negue** [comment]
In drops I get also some weird behavior yep! But I haven't looked at the drops code. Well if there is a sooner production push then it would be good to test too

**Comment by paglias** [comment]
I'm merging. Prod will be deployed before beta for sure. I don't know when, if no one else deployed this evening I'm going to deploy myself, the fix doesn't break anything so it's safe.

**Pull request merged**
