### PR TITLE
Issue: 10660 - Fixed. Changed default to Please Enter A Value

### LINKED ISSUE #10660: When cleared, the reward price shows 1.0 instead of empty, which can be confusing
Reported by Il Mago:

> Bug (display bug?) : when editing a reward, if you delete the content of the price field it appears written there 1.0, which can be misleading because if you see it and think you have already written in it it will seem strange to have the notice you need to write in it, also because with low connection the notice doesn't appear immediately

Confirmed by me, screenshot:

image

### PR DESCRIPTION
**Pull request by JesseRatt**
[//]: # (Note: See http://habitica.wikia.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #10660

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID:

### CODE REVIEW

**Comment by JesseRatt** [comment]
@paglias Updated per @Tressley 's comment.

**Comment by paglias** [comment]
thanks @JesseRatt ! If you have an Habitica UUID (Settings->Api) I'll be happy to award a contributor tier for this PR :)

**Comment by JesseRatt** [comment]
@paglias 59051374-fcfd-4014-beaa-0c2c7b847485 Is my ID. Thanks!

**Comment by paglias** [comment]
Sorry for the delay @JesseRatt but it's finally been noted in your profile towards your 3rd tier

**Pull request merged**
