### PR TITLE
Refactored group chat flagging

### PR DESCRIPTION
**Pull request by TheHollidayInn**
This is the first refactor step towards adding inbox chat flagging.

### CODE REVIEW

**Comment by Alys** [comment]
Can this be loaded onto one of the test sites so that we can test emails from flags? We'd only need it there for a day or two, depending on our availability.

**Comment by TheHollidayInn** [comment]
Sure!

**Comment by Alys** [comment]
Test plan:

- [x] one non-mod user flags a post in the Tavern:
	- [x] the post's data changes correctly in database: flagger's UUID recorded, flag count set to 1
	- [x] user does not see any change to the flagged post, even after a reload
        - [x] when user tries to flag the same message again, they see the `messageGroupChatFlagAlreadyReported` string 
	- [x] mod sees a "flagged once" indicator on the post
	- [x] Slack notification is received
	- [x] email is received to say the post was flagged
	- [x] mod can open the flag cancellation modal and can cancel the flag
		- [x] the post's data changes correctly in database: flag count set to 0
		- [x] mod then sees no indicator on the post
		- [x] email is received to say the post was unflagged
- [x] two non-mod users flag the same post in the Tavern:
	- [x] the post's data changes correctly in database: both flaggers' UUIDs recorded, flag count set to 2
	- [x] both non-mods see the message disappear after messages are refetched
	- [x] person who made the post sees no change to the post
	- [x] mod sees a "message hidden" indicator on the post
	- [x] Slack notifications are received
	- [x] emails are received
	- [x] mod can open the flag cancellation modal and can cancel the flags
		- [x] the post's data changes correctly in database: flag count set to 0
		- [x] mod then sees no indicator on the post
- [x] one mod flags a different post in the Tavern:
	- [x] the post's data changes correctly in database: flagger's UUID recorded, flag count set to 5
	- [x] a non-mod sees the message disappear after messages are refetched
	- [x] person who made the post sees no change to the post
	- [x] mod sees a "message hidden" indicator on the post
	- [x] Slack notification is received
	- [x] email is received
	- [x] mod can open the flag cancellation modal and can cancel the flags
		- [x] the post's data changes correctly in database: flag count set to 0
		- [x] mod then sees no indicator on the post
		- [x] mod can re-flag message
- [x] flagging works in a public Guild
- [x] flagging works in a private Guild
- [x] flagging works in a Party
- [x] mod user can flag their own post
   - [x] mod can unflag their own post
- [x] non-mod user can flag their own post
- [x] non-mod user can flag a mod's post
   - [x] mod can unflag their own post

**Comment by Alys** [comment]
I'm getting the error below when I go to the Tavern on beta. An internal server error message also appears in a red snackbar notification.

screenshot_2018-02-04_17-35-25

Unhandled promise rejection 
Error: Request failed with status code 500
Stack trace:
t.exports@https://habitrpg-beta.herokuapp.com/static/js/vendor.994c98a80525fe835aca.js:6:109199
t.exports@https://habitrpg-beta.herokuapp.com/static/js/vendor.994c98a80525fe835aca.js:6:172348
t.exports/</p[h]@https://habitrpg-beta.herokuapp.com/static/js/vendor.994c98a80525fe835aca.js:6:107952
es6.promise.js:97
j/</e<
es6.promise.js:97
t.exports
_perform.js:3:12
j/<
es6.promise.js:91
t.exports
_invoke.js:5
<anonymous>
_task.js:35
y
_task.js:21
b
_task.js:25

**Comment by TheHollidayInn** [comment]
I just went to tavern and it seems to be working.

**Comment by Alys** [comment]
Yeah, it's not doing it now for me either. I'll watch for it while I'm doing the tests.

**Comment by Alys** [comment]
It just did the internal server error message again when I posted a message to the Tavern in beta:

Unhandled promise rejection 
Error: Request failed with status code 500
Stack trace:
t.exports@https://habitrpg-beta.herokuapp.com/static/js/vendor.994c98a80525fe835aca.js:6:109199
t.exports@https://habitrpg-beta.herokuapp.com/static/js/vendor.994c98a80525fe835aca.js:6:172348
t.exports/</p[h]@https://habitrpg-beta.herokuapp.com/static/js/vendor.994c98a80525fe835aca.js:6:107952
es6.promise.js:97

**Comment by Alys** [comment]
And again when I loaded the Tavern using a different account: 3e595299-3d8a-4a10-bfe0-88f555e4aa0c

The previous post was for d904bd62-da08-416b-a816-ba797c9ee265

**Comment by TheHollidayInn** [comment]
eh, sorry for the delay. I'm not seeing any of this. Can you check your network panel to see what url is giving a 500? Also, can we coordinate a time so I can check the logs of beta?

**Comment by Alys** [comment]
I couldn't get the error to happen today. I'll try again tomorrow and if it still doesn't happen I'll start on the test plan.

**Comment by Alys** [comment]
All the manual tests listed above have succeeded.

That server error turned out to be from the account I was using having old cron-related data so it's not a problem.

**Pull request merged**
