### PR TITLE
Updated seeConsole message to be more helpful to the average user

### PR DESCRIPTION
**Pull request by TheHollidayInn**
Based on some suggestions from https://github.com/HabitRPG/habitrpg/issues/4808, Does this message work to solve the issue?

### CODE REVIEW

**Comment by gisikw** [comment]
Feels like if we're adjusting the wording on here, we should probably remove the Chrome-specific language, no? Console exists in Chrome/IE/FF.

**Comment by paglias** [comment]
@gisikw +1

**Comment by TheHollidayInn** [comment]
I agree as well.

So, should it say: "If the error persists, please report a bug at Help > Report a Bug (see the console for more details)." ?

Or, should there we state to only look at the console if they know what that is?

**Comment by Alys** [comment]
Instead of "see the console for more details", something like "include any error messages from the console"

I agree about stating to only look at the console if they know what that is.

**Comment by crookedneighbor** [comment]
How about: 

> If the error persists, please report a bug at Help > Report a Bug. If you're familiar with your browser's console, please include any error messages.

**Comment by Alys** [comment]
I like it! 

Except maybe shorten it slightly like this: "... please report it at Help > Report a Bug ..."

**Comment by crookedneighbor** [comment]
@TheHollidayInn Added this small change to the list of partial changes for tier 5

**Comment by TheHollidayInn** [comment]
Sweet! Although, it was pretty simple. Ha. Do I not need to update the message?

**Comment by crookedneighbor** [comment]
@TheHollidayInn I updated it.

**Pull request merged**
