### PR TITLE
Various text improvements

### PR DESCRIPTION
**Pull request by mayajosyula**
Changed wording in a few places, as described in #5262.

### CODE REVIEW

**Comment by Alys** [comment]
Thank you @agentx999! Please tell us your User ID (from Settings -> API) for a contributor tier.

**Comment by mayajosyula** [comment]
My ID is: 9261598f-9f1a-44ef-bcfb-dc8bc4a70d86

**Comment by Alys** [comment]
Partial credit towards Tier 3 has been noted in your account.

**Comment by mayajosyula** [comment]
Thank you! :)

**Pull request merged**
