### PR TITLE
fix(quests): Quests that are level-locked for purchase can now be used at any level fixes #12417

### LINKED ISSUE #12417: quests that are level-locked for purchase should be usable at any level
Currently, certain quest scrolls can only be bought or used after you have reached a certain level (the list of quests is below).

We want this to be changed so that **if you already own one of those quest scrolls, you can use it to start a quest regardless of what level you are**.

Existing features that should NOT be changed:
- quest scrolls that are given when you reach a certain level should still be given at that level
- quest scrolls that can be bought only after you have reached a certain level should still not be buyable before that level (that will prevent new players from buying a scroll that they are later given for free, which would be annoying)
- quest scrolls that are locked for buying or using before you have completed a previous quest in the same quest line should still be locked for buying and using.

See also https://github.com/HabitRPG/habitica/issues/9936#issuecomment-665149708 where this change was decided.

The affected quests are below, taken from the wiki's [Level](https://habitica.fandom.com/wiki/Level) page ("Unlocks" section):

* Level 15
   * The player receives a free Dish Disaster quest scroll.
   * The player is able to buy or use a SnackLess Monster quest scroll.2
   * The player is able to buy or use a Laundromancer quest scroll.2
* Level 30 	
   * The player receives a free Free Yourself of the Dragon's Influence quest scroll.
   * The player is able to buy or use a Find the Lair of the Wyrm quest scroll.2
   * The player is able to buy or use a Vice Awakens quest scroll.2
* Level 40 	
   * The player receives a free A Stern Talking-To quest scroll.
   * The player is able to buy or use a Gold Knight quest scroll.2
   * The player is able to buy or use a The Iron Knight quest scroll.2
* Level 60 	
   * The player receives a free The Moonstone Chain quest scroll.
   * The player is able to buy or use a Recidivate the Necromancer quest scroll.2
   * The player is able to buy or use a Recidivate Transformed quest scroll.2

### PR DESCRIPTION
**Pull request by hamboomger**
[//]: # (Note: See http://habitica.fandom.com/wiki/Using_Your_Local_Install_to_Modify_Habitica%27s_Website_and_API for more info)

[//]: # (Put Issue # here, if applicable. This will automatically close the issue if your PR is merged in)
Fixes #12417

### Changes
[//]: # (Describe the changes that were made in detail here. Include pictures if necessary)
Quests that are level-locked for purchase can now be used at any level

[//]: # (Put User ID in here - found on the Habitica website at User Icon > Settings > API)

----
UUID: 
80b61b73-2278-4947-b713-a10112cfe7f5

### CODE REVIEW

**Comment by hamboomger** [comment]
It appears that the `questLevelTooHigh` property was only used in the piece of code that I deleted, should I clean up the locales property files as well?

**Comment by paglias** [comment]
@hamboomger the PR is looking good, regarding the locales: yes, if you could clean up the files it'd be great

**Comment by hamboomger** [comment]
@paglias ok, I assume there is no such script in a project which would delete the property from all the locales simultaneously?)

**Comment by paglias** [comment]
@hamboomger unfortunately not yet, but with a find on the entire locales folder for the string key it shouldn't take too much

**Comment by paglias** [comment]
@hamboomger hi, let me know if you plan to remove the strings, otherwise that's fine, we can do it but we don't want the pr to go lost :)

**Comment by hamboomger** [comment]
@paglias you're right, unfortunately I won't be able to contribute until Friday, so maybe it's better to merge this PR now and I'll make a separate PR for the strings later

**Comment by paglias** [comment]
@hamboomger I've merged it at https://github.com/HabitRPG/habitica/commit/869d2df4faf327ddf235fffccba93a3c917c178f

**Comment by paglias** [comment]
noted towards your 3rd tier :)

**Pull request closed without merging**
