### PR TITLE
4018 negative currency rebase

### PR DESCRIPTION
**Pull request by crookedneighbor**
Re-doing pr #4172  with the necessary rebasing.

Fix for #4018

### CODE REVIEW

**Comment by crookedneighbor** [comment]
Any thoughts on this? A better way of doing it?

**Comment by paglias** [comment]
Sorry for the delay. Sincerely i don't think it's the best way to do it. First of all it triggers a different click event which would probably get executed within the next digest by Angular, then since an angular form is accessible from the scope (http://stackoverflow.com/questions/11920482/how-to-manually-trigger-angularjs-validation-from-a-button-outside-of-the-form-t/18795264#18795264) we could use it to disable submitting in case of an invalid form

**Comment by crookedneighbor** [comment]
Oh, I agree, it's definitely not the best way to do it, but so far I haven't been able to figure out a better. way. I opened the PR to get some initial code out here and talk about it, so thanks for chiming in.

Yes, forms with unique name attributes get added to scope, but it won't add to scope if the name is generated using an angular expression. At least, I couldn't get that to work when I tried it.

IE, `<form name="form-name-{{task.id}}">` does not get added to scope, possibly because the forms on the page get added to scope before the `task.id` can actually generate? I'm not an Angular expert, so I'm not sure about that, I just know that so far, it hasn't worked unless the form name is unique without an angular expression inside it.

Looking at it again, it might be that the form needs to be an ng-form instead of a regular form for the form to get added to scope with an angular generated name. Does that sound right?

Either that, or we just wrap the reward value in an `ng-form` tag and test just for that validation... but that goes against what @paglias wants to do for these as a whole, right? You want the checkmark to check for validation on the whole form so in the future, if something else gets added that requires validation, it'll just check for it automatically. (correct me if I'm wrong on that summation)

**Comment by crookedneighbor** [comment]
Gonna start over with this.

**Pull request closed without merging**
