### PR TITLE
Tranlsate mystic items

### PR DESCRIPTION
**Pull request by crookedneighbor**
Merge in with https://github.com/HabitRPG/habitrpg-shared/pull/378

Converts the time travelers popovers, title (both pre and post subscription), and the hourglass popover to strings in the shared repo so they can be translated.

### CODE REVIEW

**Comment by crookedneighbor** [comment]
screen shot 2014-12-03 at 11 05 44 pm
screen shot 2014-12-03 at 11 05 11 pm
screen shot 2014-12-03 at 11 05 35 pm

**Comment by crookedneighbor** [comment]
@paglias Does this look good to you? I tried to model it after the way the Matt in the stable has his text displayed, since that also contains a link.

I'm open to different variable names if you can think of better ones.

**Comment by paglias** [comment]
@crookedneighbor the only thing I'm asked sometimes is to avoid splitting strings because now with the link out of the string it's a bit difficult to rearrage words. 

I would change it to one string only that get passed the link as a variable. Will post an example as soon as I find it

**Comment by paglias** [comment]
See https://github.com/HabitRPG/habitrpg/blob/ee325ce27f1a8180e831c86f152723045392f04d/views/shared/modals/drops.jade#L8 and https://github.com/HabitRPG/habitrpg-shared/blob/7d22fb0944c8ba61a0e9970089653accdd814f40/locales/en/pets.json#L35

You can pass variables from jade to strings so we can change the link without having to change each string manually

**Comment by crookedneighbor** [comment]
@paglias I knew there was an easier way to pass in the links. I'll rework this later today.

Any desire to consolidate the ones that are split up into one string (Pets and mounts page are what come to mind)? Or would that be too much of a transifex headache at this point?

**Comment by paglias** [comment]
Considert that every time a string change it gets undone and must be translated once again in every language, I would leave the old ones as they are

**Comment by crookedneighbor** [comment]
@paglias Should be good now. Look good to you?

**Comment by paglias** [comment]
@crookedneighbor is good thanks!

**Pull request merged**
